#!/usr/bin/env python3
"""PART CCCCXI -- Tomotope Bacon-Shor Packet Code.

CCCCX identified the native re-encoding target:

    81 W33 matter degrees × 16 tomotope/chirality slots = 1296 slots.

This part constructs an explicit 16-slot packet code.  The natural packet is a
4×4 Bacon-Shor subsystem code:

    rows    = 4 tetrahedral chart vertices,
    columns = 2 orientations × 2 Clifford chiralities.

The packet has parameters

    [[16,1,4]] subsystem, with 9 gauge qubits.

Using 81 independent packets gives

    [[1296,81,4]] sector packet layer,

and, when used as the replacement for the base W33 weight-3 line-star logical
components, the concatenated target lower bound is

    d >= 3 × 4 = 12.

This is lower overhead than the first Steane route [[1680,81,9]] while keeping
the tomotope/chirality geometry native to the architecture.
"""
from __future__ import annotations
import itertools, json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
ROWS=4
COLS=4
N=ROWS*COLS
PACKETS=81

def ok(name, cond, value=None): return {"name":name,"passed":bool(cond),"value":value}
def q(r,c): return r*COLS+c
def bit(indices):
    x=0
    for i in indices: x ^= (1<<i)
    return x
def rank(rows):
    basis={}
    for r in rows:
        x=r
        while x:
            p=x.bit_length()-1
            if p not in basis:
                basis[p]=x; break
            x ^= basis[p]
    return len(basis)
def reduce_by_basis(x,rows):
    basis={}
    for r in rows:
        y=r
        while y:
            p=y.bit_length()-1
            if p not in basis:
                basis[p]=y; break
            y ^= basis[p]
    z=x
    while z:
        p=z.bit_length()-1
        if p not in basis: return z
        z ^= basis[p]
    return 0
def packet_layout():
    return [
        {"qubit":q(r,c),"chart_vertex":r,"orientation":c//2,"chirality":c%2,"column":c}
        for r in range(ROWS) for c in range(COLS)
    ]
def x_gauge_rows():
    # Horizontal XX pairs inside each tetrahedral chart row.
    return [bit([q(r,c),q(r,c+1)]) for r in range(ROWS) for c in range(COLS-1)]
def z_gauge_rows():
    # Vertical ZZ pairs inside each orientation/chirality column.
    return [bit([q(r,c),q(r+1,c)]) for r in range(ROWS-1) for c in range(COLS)]
def x_stabilizer_rows():
    # Center generated by products over adjacent columns: X on two columns across all rows.
    return [bit(q(r,c0) for r in range(ROWS) for c0 in (c,c+1)) for c in range(COLS-1)]
def z_stabilizer_rows():
    # Center generated by products over adjacent rows: Z on two rows across all columns.
    return [bit(q(r0,c) for r0 in (r,r+1) for c in range(COLS)) for r in range(ROWS-1)]
def commute_xz(xrows,zrows):
    return all(((x&z).bit_count()%2)==0 for x in xrows for z in zrows)
def x_centralizer_basis():
    # X logical centralizer of Z gauge: full columns.
    return [bit(q(r,c) for r in range(ROWS)) for c in range(COLS)]
def z_centralizer_basis():
    # Z logical centralizer of X gauge: full rows.
    return [bit(q(r,c) for c in range(COLS)) for r in range(ROWS)]
def min_nontrivial_weight(centralizer,stabilizers):
    # Enumerate span of centralizer basis, remove stabilizer span, return min weight.
    best=None; best_vec=None
    m=len(centralizer)
    for mask in range(1,1<<m):
        v=0
        for i,row in enumerate(centralizer):
            if (mask>>i)&1: v ^= row
        if reduce_by_basis(v,stabilizers)!=0:
            w=v.bit_count()
            if best is None or w<best:
                best=w; best_vec=v
    return best,best_vec
def packet_summary():
    Xg=x_gauge_rows(); Zg=z_gauge_rows(); Xs=x_stabilizer_rows(); Zs=z_stabilizer_rows(); rank_g=len(Xg)+len(Zg); rank_s=rank(Xs)+rank(Zs); gauge_qubits=(rank_g-rank_s)//2; k=N-rank_s-gauge_qubits
    dx,xv=min_nontrivial_weight(x_centralizer_basis(),Xs)
    dz,zv=min_nontrivial_weight(z_centralizer_basis(),Zs)
    return {"n":N,"k":k,"d":min(dx,dz),"d_X":dx,"d_Z":dz,"gauge_qubits":gauge_qubits,"rank_gauge_generators":rank_g,"rank_stabilizer_center":rank_s,"X_gauge_count":len(Xg),"Z_gauge_count":len(Zg),"X_stabilizer_rank":rank(Xs),"Z_stabilizer_rank":rank(Zs),"commuting_center":commute_xz(Xs,Zs),"logical_X_witness_weight":dx,"logical_Z_witness_weight":dz,"layout":packet_layout()}
def global_packet_layer():
    p=packet_summary()
    return {"packets":PACKETS,"n":PACKETS*p['n'],"k":PACKETS*p['k'],"d":p['d'],"gauge_qubits":PACKETS*p['gauge_qubits'],"stabilizer_center_rank":PACKETS*p['rank_stabilizer_center'],"notation":"[[1296,81,4]] subsystem packet layer"}
def concatenated_target():
    p=packet_summary()
    return {"n":PACKETS*p['n'],"k":PACKETS*p['k'],"d_lower_bound":3*p['d'],"notation":"[[1296,81,>=12]] line-star replacement target"}
def toroidal_tomotope_context():
    return {"tomotope_flags":192,"tomotope_edges":12,"local_flags_per_edge":16,"packet_factorization":"16=4 chart rows × (2 orientations × 2 chiralities) columns","toroidal_hint":"CLXIV uses H(n)=((n-3)(n-4))/12 with accepted residues {3,4,7,12}; the 4 is the tetrahedral seed and the 12 denominator is 3×4.","bacon_shor_reason":"4×4 Bacon-Shor is the smallest symmetric subsystem packet matching the tomotope 16-slot local incidence."}
def build_results():
    p=packet_summary(); g=global_packet_layer(); c=concatenated_target(); checks=[]
    checks.append(ok('packet has 16 slots',p['n']==16,p))
    checks.append(ok('packet encodes one protected degree',p['k']==1,p))
    checks.append(ok('packet distance = 4',p['d']==4 and p['d_X']==4 and p['d_Z']==4,p))
    checks.append(ok('packet has 9 gauge qubits',p['gauge_qubits']==9,p))
    checks.append(ok('stabilizer center rank = 6',p['rank_stabilizer_center']==6,p))
    checks.append(ok('gauge generator count = 24',p['rank_gauge_generators']==24,p))
    checks.append(ok('81 packets give n=1296,k=81,d=4',g['n']==1296 and g['k']==81 and g['d']==4,g))
    checks.append(ok('line-star replacement target has d>=12',c['d_lower_bound']==12,c))
    checks.append(ok('layout has orientation/chart/chirality fields',all(set(['qubit','chart_vertex','orientation','chirality','column']).issubset(x) for x in p['layout']),p['layout'][:2]))
    verified=all(ch['passed'] for ch in checks)
    return {"part":"CCCCXI","title":"Tomotope Bacon-Shor Packet Code","verified":verified,"checks_total":len(checks),"checks_passed":sum(ch['passed'] for ch in checks),"packet_code":p,"global_packet_layer":g,"concatenated_line_star_target":c,"toroidal_tomotope_context":toroidal_tomotope_context(),"architecture_upgrade":"Constructs the explicit 16-slot tomotope/chirality packet as a 4×4 Bacon-Shor subsystem code. The packet is [[16,1,4]], and 81 copies give a native [[1296,81,4]] packet layer; replacing W33 line-star logical components gives a target lower bound [[1296,81,>=12]].","theorem":"A 4×4 Bacon-Shor subsystem code has 16 physical slots, one protected logical degree, 9 gauge qubits, stabilizer-center rank 6, and distance 4. Interpreting rows as tetrahedral chart vertices and columns as orientation×chirality realizes the tomotope packet factorization 16=4×(2×2).","honesty_boundary":"This constructs the local 16-slot packet and its independent 81-packet layer. The final integrated W33-to-packet attachment map and full global subsystem distance still need a dedicated compiler.","checks":checks}
def main():
    r=build_results(); out=ROOT/'PART_CCCCXI_tomotope_bacon_shor_packet_code_results.json'; out.write_text(json.dumps(r,indent=2,sort_keys=True)+'\n',encoding='utf-8'); print(json.dumps({"part":r['part'],"verified":r['verified'],"checks_passed":r['checks_passed'],"checks_total":r['checks_total'],"packet":r['packet_code']['d'],"global":r['global_packet_layer']['notation'],"out_path":str(out)},indent=2))
if __name__=='__main__': main()
