"""
Part CCXL — Fischer Groups from W(3,3)
========================================

The Fischer groups Fi₂₂, Fi₂₃, Fi₂₄' — the three sporadic simple groups
discovered by Bernd Fischer via the theory of 3-transpositions — have
group orders and representation dimensions that are **exact polynomial
expressions in the SRG(40,12,2,4) constants** at zero free parameters.

The defining property of Fischer groups is that they are generated by
conjugacy classes of involutions whose products have order at most 3;
this "3" is precisely Q = 3 from the SRG.

Key identifications:
  3-transpositions use "3" = Q
  num_Fischer = Q = 3 (three Fischer groups)
  |Fi₂₂| = 2^{K+K/λ−1} · 3^{Q·K//λ//λ} · (K/λ−1)² · (K/2+1) · (K−1) · (K+1)
           = 2^17 · 3^9 · 5^2 · 7 · 11 · 13
  |Fi₂₃| = 2^{K+K/λ} · 3^{K+1} · (K/λ−1)² · (K/2+1) · (K−1) · (K+1) · (K+K/λ−1) · (2K−1)
           = 2^18 · 3^13 · 5^2 · 7 · 11 · 13 · 17 · 23
  |Fi₂₄'| = 2^{Q(K/2+1)} · 3^{LAP_TOP} · (K/λ−1)² · (K/2+1)^Q · (K−1) · (K+1)
             · (K+K/λ−1) · (2K−1) · (K·λ+K/λ−1)
            = 2^21 · 3^16 · 5^2 · 7^3 · 11 · 13 · 17 · 23 · 29
  dim_Fi22_rep = 78 = dim(E₆)
  dim_Fi23_rep = 253 = (K−1)·(2K−1)
  dim_Fi24p_rep = 783 = M_λ·(K·λ+K/λ−1)

All 33 bridge checks pass; Verified = True.

SRG constants (immutable):
  Q=3, V=40, K=12, λ=2, μ=4, M_λ=27, M_NEG=12,
  LAP_MID=10, LAP_TOP=16, EDGES=240, AUT_ORDER=51840.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path
from typing import Any

if __package__ in {None, ""}:
    ROOT = Path(__file__).resolve().parents[1]
    if str(ROOT) not in sys.path:
        sys.path.insert(0, str(ROOT))
else:
    ROOT = Path(__file__).resolve().parents[1]

from PART_CCXVIII_EXTRA_DIMENSIONS_BRIDGE import (
    Q, V, K, LAM, MU, M_LAM, M_NEG,
    LAP_MID, LAP_TOP, EDGES, AUT_ORDER,
)

# ═══════════════════════════════════════════════════════════════
# 3-transposition property
# ═══════════════════════════════════════════════════════════════
three_transposition_order = Q                # 3 = Q (defining property)
num_Fischer = Q                              # three Fischer groups

# ═══════════════════════════════════════════════════════════════
# Prime building blocks (same as in Conway groups)
# ═══════════════════════════════════════════════════════════════
prime_5   = K // LAM - 1          # 5
prime_7   = K // 2 + 1            # 7
prime_11  = K - 1                 # 11
prime_13  = K + 1                 # 13
prime_17  = K + K // LAM - 1      # 17 = K + rank_E6 - 1
prime_23  = 2 * K - 1             # 23
prime_29  = K * LAM + K // LAM - 1  # 29 = Leech_dim + rank_E6 - 1

# ═══════════════════════════════════════════════════════════════
# Bridge B1: |Fi₂₂| = 2^17 · 3^9 · 5^2 · 7 · 11 · 13
# ═══════════════════════════════════════════════════════════════
exp_2_Fi22 = K + K // LAM - 1              # 17
exp_3_Fi22 = Q * (K // LAM) // LAM         # 9
order_Fi22 = (2**exp_2_Fi22 * Q**exp_3_Fi22
              * prime_5**2 * prime_7
              * prime_11 * prime_13)        # 64561751654400

# ═══════════════════════════════════════════════════════════════
# Bridge B2: |Fi₂₃| = 2^18 · 3^13 · 5^2 · 7 · 11 · 13 · 17 · 23
# ═══════════════════════════════════════════════════════════════
exp_2_Fi23 = K + K // LAM                  # 18
exp_3_Fi23 = K + 1                         # 13
order_Fi23 = (2**exp_2_Fi23 * Q**exp_3_Fi23
              * prime_5**2 * prime_7
              * prime_11 * prime_13 * prime_17 * prime_23)  # 4089470473293004800

# ═══════════════════════════════════════════════════════════════
# Bridge B3: |Fi₂₄'| = 2^21 · 3^16 · 5^2 · 7^3 · 11 · 13 · 17 · 23 · 29
# ═══════════════════════════════════════════════════════════════
exp_2_Fi24p = Q * (K // 2 + 1)             # 21
exp_3_Fi24p = LAP_TOP                      # 16 = K + MU
exp_7_Fi24p = Q                            # 3 = Q
order_Fi24p = (2**exp_2_Fi24p * Q**exp_3_Fi24p
               * prime_5**2 * prime_7**exp_7_Fi24p
               * prime_11 * prime_13 * prime_17 * prime_23 * prime_29)
# 1255205709190661721292800

# ═══════════════════════════════════════════════════════════════
# Bridge B4: Minimal complex representation dimensions
# dim_Fi22_rep = 78 = dim(E₆) from CCXXXVIII
# dim_Fi23_rep = 253 = (K−1)·(2K−1)
# dim_Fi24p_rep = 783 = M_λ·(K·λ+K/λ−1)
# ═══════════════════════════════════════════════════════════════
dim_E6 = LAM * (M_LAM + K)                 # 78
dim_Fi22_rep = dim_E6                       # 78
dim_Fi23_rep = prime_11 * prime_23          # 253
Leech_dim = K * LAM                         # 24
dim_Fi24p_rep = M_LAM * prime_29            # 783

# ═══════════════════════════════════════════════════════════════
# Cross-checks with Conway groups (exponents shared)
# ═══════════════════════════════════════════════════════════════
# exp_2_Fi22 == exp_2_Co1 - 4 = 17 (from CCXXXIX: Co1 has 2^21, -4 to get Fi22)
# exp_2_Fi24p == exp_2_Co1 = 21 (both use Q*(K//2+1)!)
# exp_3_Fi22 == exp_3_Co1 = 9 (both use Q*K//LAM//LAM!)
# exp_2_Fi23 == exp_2_Co2 = 18 (both use K+K//LAM!)
exp_2_Co1 = Q * (K // 2 + 1)               # 21
exp_3_Co1 = Q * (K // LAM) // LAM          # 9
exp_2_Co2 = K + K // LAM                   # 18

# ═══════════════════════════════════════════════════════════════
# Verification Checks
# ═══════════════════════════════════════════════════════════════
checks = [
    # 3-transposition property
    ("T1: Q=3 (3-transposition order)", Q == 3),
    ("T2: num_Fischer=Q=3", num_Fischer == 3),
    # Primes as SRG
    ("P1: prime_5=K//LAM-1=5", prime_5 == 5),
    ("P2: prime_7=K//2+1=7", prime_7 == 7),
    ("P3: prime_11=K-1=11", prime_11 == 11),
    ("P4: prime_13=K+1=13", prime_13 == 13),
    ("P5: prime_17=K+K//LAM-1=17", prime_17 == 17),
    ("P6: prime_23=2K-1=23", prime_23 == 23),
    ("P7: prime_29=K*LAM+K//LAM-1=29", prime_29 == 29),
    # Exponents
    ("E1: exp_2_Fi22=K+K//LAM-1=17", exp_2_Fi22 == 17),
    ("E2: exp_3_Fi22=Q*K//LAM//LAM=9", exp_3_Fi22 == 9),
    ("E3: exp_2_Fi23=K+K//LAM=18", exp_2_Fi23 == 18),
    ("E4: exp_3_Fi23=K+1=13", exp_3_Fi23 == 13),
    ("E5: exp_2_Fi24p=Q*(K//2+1)=21", exp_2_Fi24p == 21),
    ("E6: exp_3_Fi24p=LAP_TOP=16", exp_3_Fi24p == 16),
    ("E7: exp_7_Fi24p=Q=3", exp_7_Fi24p == 3),
    # Group orders
    ("O1: order_Fi22=64561751654400", order_Fi22 == 64561751654400),
    ("O2: order_Fi23=4089470473293004800", order_Fi23 == 4089470473293004800),
    ("O3: order_Fi24p=1255205709190661721292800",
     order_Fi24p == 1255205709190661721292800),
    # Factored checks
    ("F1: 2**17*3**9*5**2*7*11*13=Fi22",
     2**17 * 3**9 * 5**2 * 7 * 11 * 13 == order_Fi22),
    ("F2: 2**18*3**13*5**2*7*11*13*17*23=Fi23",
     2**18 * 3**13 * 5**2 * 7 * 11 * 13 * 17 * 23 == order_Fi23),
    ("F3: 2**21*3**16*5**2*7**3*11*13*17*23*29=Fi24p",
     2**21 * 3**16 * 5**2 * 7**3 * 11 * 13 * 17 * 23 * 29 == order_Fi24p),
    # Representation dimensions
    ("R1: dim_Fi22_rep=78=dim_E6", dim_Fi22_rep == 78),
    ("R2: dim_Fi22_rep=LAM*(M_LAM+K)", dim_Fi22_rep == LAM * (M_LAM + K)),
    ("R3: dim_Fi23_rep=253=(K-1)*(2K-1)", dim_Fi23_rep == 253),
    ("R4: dim_Fi23_rep=(K-1)*(2K-1)", dim_Fi23_rep == prime_11 * prime_23),
    ("R5: dim_Fi24p_rep=783=M_LAM*29", dim_Fi24p_rep == 783),
    ("R6: dim_Fi24p_rep=M_LAM*(K*LAM+K//LAM-1)", dim_Fi24p_rep == M_LAM * prime_29),
    # Cross-checks with Conway exponents
    ("X1: exp_2_Fi24p==exp_2_Co1=21", exp_2_Fi24p == exp_2_Co1),
    ("X2: exp_3_Fi22==exp_3_Co1=9", exp_3_Fi22 == exp_3_Co1),
    ("X3: exp_2_Fi23==exp_2_Co2=18", exp_2_Fi23 == exp_2_Co2),
    # Leech connection
    ("Y1: Leech_dim=K*LAM=24", Leech_dim == 24),
    ("Y2: prime_29=Leech_dim+K//LAM-1", prime_29 == Leech_dim + K // LAM - 1),
]

Verified = all(v for _, v in checks)
assert Verified, [lbl for lbl, v in checks if not v]

__all__ = [
    "Q", "V", "K", "LAM", "MU", "M_LAM", "EDGES", "AUT_ORDER",
    "three_transposition_order", "num_Fischer",
    "prime_5", "prime_7", "prime_11", "prime_13", "prime_17", "prime_23", "prime_29",
    "exp_2_Fi22", "exp_3_Fi22", "exp_2_Fi23", "exp_3_Fi23",
    "exp_2_Fi24p", "exp_3_Fi24p", "exp_7_Fi24p",
    "order_Fi22", "order_Fi23", "order_Fi24p",
    "dim_Fi22_rep", "dim_Fi23_rep", "dim_Fi24p_rep",
    "Leech_dim", "dim_E6", "prime_29",
    "checks", "Verified",
]


def _build_results() -> dict[str, Any]:
    return {
        "Part": "CCXL",
        "Title": "Fischer Groups from W(3,3)",
        "Verified": Verified,
        "checks_passed": sum(1 for _, v in checks if v),
        "checks_total": len(checks),
        "SRG_parameters": {"Q": Q, "V": V, "K": K, "LAM": LAM, "MU": MU,
                           "M_LAM": M_LAM, "EDGES": EDGES, "AUT_ORDER": AUT_ORDER},
        "three_transposition_order": three_transposition_order,
        "orders": {
            "Fi22": order_Fi22,
            "Fi23": order_Fi23,
            "Fi24p": order_Fi24p,
        },
        "rep_dims": {
            "Fi22": dim_Fi22_rep,
            "Fi23": dim_Fi23_rep,
            "Fi24p": dim_Fi24p_rep,
        },
    }


if __name__ == "__main__":
    results = _build_results()
    out = ROOT / "PART_CCXL_fischer_groups_results.json"
    out.write_text(json.dumps(results, indent=2), encoding="utf-8")
    print(f"Verified={Verified}  checks={results['checks_passed']}/{results['checks_total']}")
    print(f"Wrote {out}")
