#!/usr/bin/env python3
"""
PART CCCXXX -- Projective RG Renderer Compiler
==============================================

CCCXXIX integrated the finite beta flow

    dy/dt = 67y + 140 - y^2.

CCCXXX identifies this as a projective/Mobius flow generated by a traceless
2x2 matrix

    G = [[67/2, 140],
         [1,    -67/2]].

The induced Riccati equation for y=u/v is

    y' = G_12 + (G_11-G_22)y - G_21 y^2
       = 140 + 67y - y^2.

The generator satisfies

    G^2 = (5049/4) I,

so its eigenvalues are ±sqrt(5049)/2 and the projective gap is sqrt(5049),
exactly the RG-time eigenvalue from CCCXXIX.

This makes the finite RG renderer a genuine PSL(2)-type projective action.
"""

from __future__ import annotations

import json
import math
from fractions import Fraction
from pathlib import Path
from typing import Any, Dict, List, Tuple

ROOT = Path(__file__).resolve().parents[1]

Q = 3
LAM = 2
K = 12
V = 40
PHI3 = Q * Q + Q + 1
PHI4 = Q * Q + 1
PHI6 = Q * Q - Q + 1
B = 2 * V - PHI3           # 67
A = (V // 2) * PHI6        # 140
DELTA = B * B + 4 * A      # 5049
D = math.sqrt(DELTA)

# Traceless projective generator G = [[B/2, A], [1, -B/2]].
G = ((Fraction(B, 2), Fraction(A, 1)), (Fraction(1, 1), Fraction(-B, 2)))


def ok(name: str, condition: bool, value: Any = None) -> Dict[str, Any]:
    return {"name": name, "passed": bool(condition), "value": value}


def matmul2(X: Tuple[Tuple[Fraction, Fraction], Tuple[Fraction, Fraction]],
            Y: Tuple[Tuple[Fraction, Fraction], Tuple[Fraction, Fraction]]) -> Tuple[Tuple[Fraction, Fraction], Tuple[Fraction, Fraction]]:
    return (
        (X[0][0] * Y[0][0] + X[0][1] * Y[1][0], X[0][0] * Y[0][1] + X[0][1] * Y[1][1]),
        (X[1][0] * Y[0][0] + X[1][1] * Y[1][0], X[1][0] * Y[0][1] + X[1][1] * Y[1][1]),
    )


def trace2(X: Tuple[Tuple[Fraction, Fraction], Tuple[Fraction, Fraction]]) -> Fraction:
    return X[0][0] + X[1][1]


def det2(X: Tuple[Tuple[Fraction, Fraction], Tuple[Fraction, Fraction]]) -> Fraction:
    return X[0][0] * X[1][1] - X[0][1] * X[1][0]


def frac_str(x: Fraction) -> str:
    return f"{x.numerator}/{x.denominator}" if x.denominator != 1 else str(x.numerator)


def generator_square() -> Tuple[Tuple[Fraction, Fraction], Tuple[Fraction, Fraction]]:
    return matmul2(G, G)


def mobius_matrix(t: float) -> Tuple[Tuple[float, float], Tuple[float, float]]:
    """Return exp(tG) using G^2=(Delta/4)I."""
    h = D * t / 2.0
    cosh = math.cosh(h)
    sinh_over = math.sinh(h) / (D / 2.0)
    return (
        (cosh + sinh_over * float(G[0][0]), sinh_over * float(G[0][1])),
        (sinh_over * float(G[1][0]), cosh + sinh_over * float(G[1][1])),
    )


def projective_action(y: float, t: float) -> float:
    M = mobius_matrix(t)
    return (M[0][0] * y + M[0][1]) / (M[1][0] * y + M[1][1])


def beta(y: float) -> float:
    return A + B * y - y * y


def derivative_numeric(y0: float, t: float, h: float = 1e-6) -> float:
    return (projective_action(y0, t + h) - projective_action(y0, t - h)) / (2 * h)


def fixed_points() -> Tuple[float, float]:
    return ((B + D) / 2.0, (B - D) / 2.0)


def build_results() -> Dict[str, Any]:
    checks: List[Dict[str, Any]] = []
    G2 = generator_square()
    expected_G2 = ((Fraction(DELTA, 4), Fraction(0, 1)), (Fraction(0, 1), Fraction(DELTA, 4)))
    y_plus, y_minus = fixed_points()
    y0 = float(B)
    t = 0.05
    y_projective = projective_action(y0, t)
    deriv_at_zero = derivative_numeric(y0, 0.0)
    det_exp = det2(G)

    checks.append(ok("projective generator trace is zero", trace2(G) == 0, frac_str(trace2(G))))
    checks.append(ok("projective generator determinant = -Delta/4", det_exp == Fraction(-DELTA, 4), frac_str(det_exp))))
    checks.append(ok("G^2 = (Delta/4) I", G2 == expected_G2, [[frac_str(x) for x in row] for row in G2]))
    checks.append(ok("Delta=q^3(k-1)(Phi4+Phi6)", DELTA == Q ** 3 * (K - 1) * (PHI4 + PHI6), DELTA))
    checks.append(ok("projective gap = sqrt(Delta)", abs((y_plus - y_minus) - D) < 1e-12, y_plus - y_minus))
    checks.append(ok("fixed points are eigenline slopes", abs(beta(y_plus)) < 1e-10 and abs(beta(y_minus)) < 1e-10, (y_plus, y_minus))))
    checks.append(ok("Mobius action identity at t=0", abs(projective_action(y0, 0.0) - y0) < 1e-12, projective_action(y0, 0.0))))
    checks.append(ok("Mobius derivative equals beta at t=0", abs(deriv_at_zero - beta(y0)) < 1e-4, (deriv_at_zero, beta(y0))))
    checks.append(ok("forward Mobius action moves toward attracting branch", y_projective > y0 and y_projective < y_plus, y_projective)))
    checks.append(ok("exp(tG) has determinant 1", abs((mobius_matrix(t)[0][0] * mobius_matrix(t)[1][1] - mobius_matrix(t)[0][1] * mobius_matrix(t)[1][0]) - 1.0) < 1e-12, mobius_matrix(t))))

    verified = all(check["passed"] for check in checks)

    return {
        "part": "CCCXXX",
        "title": "Projective RG Renderer Compiler",
        "verified": verified,
        "checks_total": len(checks),
        "checks_passed": sum(1 for check in checks if check["passed"]),
        "generator": {
            "G": [[frac_str(x) for x in row] for row in G],
            "trace": frac_str(trace2(G)),
            "determinant": frac_str(det_exp),
            "square": [[frac_str(x) for x in row] for row in G2],
            "square_form": "G^2=(5049/4)I",
            "eigenvalues": ["+sqrt(5049)/2", "-sqrt(5049)/2"],
        },
        "riccati_flow": {
            "coordinate": "y=u/v",
            "equation": "dy/dt = 140 + 67y - y^2",
            "beta_numerator": "B(y)=67y+140-y^2",
            "fixed_points": ["(67+sqrt(5049))/2", "(67-sqrt(5049))/2"],
        },
        "mobius_renderer": {
            "exp_tG": "cosh(sqrt(5049)t/2) I + (2/sqrt(5049)) sinh(sqrt(5049)t/2) G",
            "action": "y(t)=(a(t)y0+b(t))/(c(t)y0+d(t))",
            "sample_y0": y0,
            "sample_t": t,
            "sample_y_t": y_projective,
        },
        "architecture_upgrade": (
            "CCCXXIX integrated the beta flow.  CCCXXX shows the integrated flow is "
            "the projectivization of exp(tG) for a traceless 2x2 generator satisfying "
            "G^2=(5049/4)I.  Thus the RG renderer is a finite PSL(2)-type action."
        ),
        "theorem": (
            "The finite RG flow dy/dt=140+67y-y^2 is the Riccati/projective flow "
            "induced by G=[[67/2,140],[1,-67/2]].  Since G^2=(5049/4)I, exp(tG) "
            "is closed in hyperbolic form and has projective eigenvalue gap sqrt(5049)."
        ),
        "honesty_boundary": (
            "This proves the finite RG renderer is projective/Mobius.  It still does "
            "not assign physical continuum units to t or y."
        ),
        "checks": checks,
    }


def main() -> None:
    results = build_results()
    out_path = ROOT / "PART_CCCXXX_projective_rg_renderer_results.json"
    out_path.write_text(json.dumps(results, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    print(json.dumps({
        "part": results["part"],
        "verified": results["verified"],
        "checks_passed": results["checks_passed"],
        "checks_total": results["checks_total"],
        "out_path": str(out_path),
    }, indent=2))


if __name__ == "__main__":
    main()
