#!/usr/bin/env python3
"""
PART CCCXXXI -- Lorentzian RG Spinor Compiler
=============================================

CCCXXX showed that the finite RG renderer is the projective flow generated by

    G = [[67/2, 140],
         [1,    -67/2]]

with G^2=(5049/4)I.  CCCXXXI identifies the geometric meaning of this
projective generator.

The Lie algebra sl(2,R) is the spin algebra spin(2,1).  Writing

    G = [[z, x+y],
         [x-y, -z]],

we obtain

    z = 67/2,
    x = 141/2,
    y = 139/2,

and the Lorentzian norm is

    z^2 + x^2 - y^2 = 5049/4.

Thus the RG renderer is not merely Mobius/projective: it is a Lorentzian spinor
flow with finite W33 mass/norm sqrt(5049)/2.  Normalizing G gives an involution,
and the two fixed branches are its Clifford idempotent/eigenline sectors.
"""

from __future__ import annotations

import json
import math
from fractions import Fraction
from pathlib import Path
from typing import Any, Dict, List, Tuple

ROOT = Path(__file__).resolve().parents[1]

Q = 3
K = 12
V = 40
PHI3 = Q * Q + Q + 1
PHI4 = Q * Q + 1
PHI6 = Q * Q - Q + 1
B = 2 * V - PHI3           # 67
A = (V // 2) * PHI6        # 140
DELTA = B * B + 4 * A      # 5049
D = math.sqrt(DELTA)

FractionMatrix = Tuple[Tuple[Fraction, Fraction], Tuple[Fraction, Fraction]]
FloatMatrix = Tuple[Tuple[float, float], Tuple[float, float]]

G: FractionMatrix = ((Fraction(B, 2), Fraction(A, 1)), (Fraction(1, 1), Fraction(-B, 2)))
H: FractionMatrix = ((Fraction(1, 1), Fraction(0, 1)), (Fraction(0, 1), Fraction(-1, 1)))
E: FractionMatrix = ((Fraction(0, 1), Fraction(1, 1)), (Fraction(0, 1), Fraction(0, 1)))
F: FractionMatrix = ((Fraction(0, 1), Fraction(0, 1)), (Fraction(1, 1), Fraction(0, 1)))

Z = Fraction(B, 2)
X = Fraction(A + 1, 2)
Y = Fraction(A - 1, 2)
NORM = Z * Z + X * X - Y * Y


def ok(name: str, condition: bool, value: Any = None) -> Dict[str, Any]:
    return {"name": name, "passed": bool(condition), "value": value}


def frac_str(x: Fraction) -> str:
    return f"{x.numerator}/{x.denominator}" if x.denominator != 1 else str(x.numerator)


def matmul(Xm: FractionMatrix, Ym: FractionMatrix) -> FractionMatrix:
    return (
        (Xm[0][0] * Ym[0][0] + Xm[0][1] * Ym[1][0], Xm[0][0] * Ym[0][1] + Xm[0][1] * Ym[1][1]),
        (Xm[1][0] * Ym[0][0] + Xm[1][1] * Ym[1][0], Xm[1][0] * Ym[0][1] + Xm[1][1] * Ym[1][1]),
    )


def matadd(Xm: FractionMatrix, Ym: FractionMatrix) -> FractionMatrix:
    return (
        (Xm[0][0] + Ym[0][0], Xm[0][1] + Ym[0][1]),
        (Xm[1][0] + Ym[1][0], Xm[1][1] + Ym[1][1]),
    )


def matsub(Xm: FractionMatrix, Ym: FractionMatrix) -> FractionMatrix:
    return (
        (Xm[0][0] - Ym[0][0], Xm[0][1] - Ym[0][1]),
        (Xm[1][0] - Ym[1][0], Xm[1][1] - Ym[1][1]),
    )


def matscale(a: Fraction, Xm: FractionMatrix) -> FractionMatrix:
    return ((a * Xm[0][0], a * Xm[0][1]), (a * Xm[1][0], a * Xm[1][1]))


def commutator(Xm: FractionMatrix, Ym: FractionMatrix) -> FractionMatrix:
    return matsub(matmul(Xm, Ym), matmul(Ym, Xm))


def trace(Xm: FractionMatrix) -> Fraction:
    return Xm[0][0] + Xm[1][1]


def det(Xm: FractionMatrix) -> Fraction:
    return Xm[0][0] * Xm[1][1] - Xm[0][1] * Xm[1][0]


def m_to_json(Xm: FractionMatrix) -> List[List[str]]:
    return [[frac_str(x) for x in row] for row in Xm]


def reconstruct_from_lorentz() -> FractionMatrix:
    return ((Z, X + Y), (X - Y, -Z))


def normalized_involution() -> FloatMatrix:
    scale = 2.0 / D
    return ((scale * float(G[0][0]), scale * float(G[0][1])), (scale * float(G[1][0]), scale * float(G[1][1])))


def matmul_float(Af: FloatMatrix, Bf: FloatMatrix) -> FloatMatrix:
    return (
        (Af[0][0] * Bf[0][0] + Af[0][1] * Bf[1][0], Af[0][0] * Bf[0][1] + Af[0][1] * Bf[1][1]),
        (Af[1][0] * Bf[0][0] + Af[1][1] * Bf[1][0], Af[1][0] * Bf[0][1] + Af[1][1] * Bf[1][1]),
    )


def matadd_float(Af: FloatMatrix, Bf: FloatMatrix) -> FloatMatrix:
    return ((Af[0][0] + Bf[0][0], Af[0][1] + Bf[0][1]), (Af[1][0] + Bf[1][0], Af[1][1] + Bf[1][1]))


def matsub_float(Af: FloatMatrix, Bf: FloatMatrix) -> FloatMatrix:
    return ((Af[0][0] - Bf[0][0], Af[0][1] - Bf[0][1]), (Af[1][0] - Bf[1][0], Af[1][1] - Bf[1][1]))


def matscale_float(a: float, Af: FloatMatrix) -> FloatMatrix:
    return ((a * Af[0][0], a * Af[0][1]), (a * Af[1][0], a * Af[1][1]))


def max_abs_entry(Af: FloatMatrix) -> float:
    return max(abs(Af[i][j]) for i in range(2) for j in range(2))


def identity_float() -> FloatMatrix:
    return ((1.0, 0.0), (0.0, 1.0))


def branch_projectors() -> Tuple[FloatMatrix, FloatMatrix]:
    J = normalized_involution()
    I = identity_float()
    P_plus = matscale_float(0.5, matadd_float(I, J))
    P_minus = matscale_float(0.5, matsub_float(I, J))
    return P_plus, P_minus


def build_results() -> Dict[str, Any]:
    checks: List[Dict[str, Any]] = []
    G2 = matmul(G, G)
    expected_G2: FractionMatrix = ((Fraction(DELTA, 4), Fraction(0, 1)), (Fraction(0, 1), Fraction(DELTA, 4)))
    J = normalized_involution()
    J2 = matmul_float(J, J)
    P_plus, P_minus = branch_projectors()
    Pp2 = matmul_float(P_plus, P_plus)
    Pm2 = matmul_float(P_minus, P_minus)
    PpPm = matmul_float(P_plus, P_minus)

    checks.append(ok("G lies in sl2: trace zero", trace(G) == 0, frac_str(trace(G))))
    checks.append(ok("G decomposes as (B/2)H + A E + F", G == matadd(matadd(matscale(Fraction(B, 2), H), matscale(Fraction(A, 1), E)), F), m_to_json(G)))
    checks.append(ok("sl2 relation [H,E]=2E", commutator(H, E) == matscale(Fraction(2, 1), E), m_to_json(commutator(H, E))))
    checks.append(ok("sl2 relation [H,F]=-2F", commutator(H, F) == matscale(Fraction(-2, 1), F), m_to_json(commutator(H, F))))
    checks.append(ok("sl2 relation [E,F]=H", commutator(E, F) == H, m_to_json(commutator(E, F))))
    checks.append(ok("Lorentz reconstruction [[z,x+y],[x-y,-z]] equals G", reconstruct_from_lorentz() == G, m_to_json(reconstruct_from_lorentz())))
    checks.append(ok("Lorentz components are z=67/2, x=141/2, y=139/2", (Z, X, Y) == (Fraction(67, 2), Fraction(141, 2), Fraction(139, 2)), [frac_str(Z), frac_str(X), frac_str(Y)]))
    checks.append(ok("Lorentz norm z^2+x^2-y^2 = 5049/4", NORM == Fraction(DELTA, 4), frac_str(NORM)))
    checks.append(ok("G^2=(5049/4)I", G2 == expected_G2, m_to_json(G2)))
    checks.append(ok("det(G)=-5049/4", det(G) == Fraction(-DELTA, 4), frac_str(det(G))))
    checks.append(ok("normalized generator J=(2/sqrtDelta)G squares to I", max_abs_entry(matsub_float(J2, identity_float())) < 1e-12, J2))
    checks.append(ok("P_plus is idempotent", max_abs_entry(matsub_float(Pp2, P_plus)) < 1e-12, P_plus))
    checks.append(ok("P_minus is idempotent", max_abs_entry(matsub_float(Pm2, P_minus)) < 1e-12, P_minus))
    checks.append(ok("branch projectors are orthogonal", max_abs_entry(PpPm) < 1e-12, PpPm))
    checks.append(ok("P_plus+P_minus=I", max_abs_entry(matsub_float(matadd_float(P_plus, P_minus), identity_float())) < 1e-12, matadd_float(P_plus, P_minus)))

    verified = all(check["passed"] for check in checks)

    return {
        "part": "CCCXXXI",
        "title": "Lorentzian RG Spinor Compiler",
        "verified": verified,
        "checks_total": len(checks),
        "checks_passed": sum(1 for check in checks if check["passed"]),
        "sl2_generator": {
            "G": m_to_json(G),
            "decomposition": "G=(67/2)H + 140E + F",
            "commutators": ["[H,E]=2E", "[H,F]=-2F", "[E,F]=H"],
        },
        "lorentzian_vector": {
            "matrix_form": "G=[[z,x+y],[x-y,-z]]",
            "z": frac_str(Z),
            "x": frac_str(X),
            "y": frac_str(Y),
            "norm": frac_str(NORM),
            "norm_form": "z^2+x^2-y^2=5049/4",
            "mass_gap": "sqrt(5049)/2",
        },
        "clifford_branching": {
            "normalized_involution": "J=(2/sqrt(5049))G, J^2=I",
            "projectors": "P_±=(I±J)/2",
            "P_plus_numeric": P_plus,
            "P_minus_numeric": P_minus,
        },
        "architecture_upgrade": (
            "CCCXXX made the RG renderer projective.  CCCXXXI identifies the renderer "
            "as an sl2/spin(2,1) Lorentzian spinor flow: G is a Lorentz vector of norm "
            "5049/4 and its normalized form defines Clifford branch projectors."
        ),
        "theorem": (
            "The projective RG generator G=[[67/2,140],[1,-67/2]] is an sl2 element "
            "equivalently represented by the Lorentzian vector (z,x,y)=(67/2,141/2,139/2) "
            "with norm z^2+x^2-y^2=5049/4.  The normalized generator J=(2/sqrt(5049))G "
            "satisfies J^2=I, producing two Clifford idempotent branch projectors."
        ),
        "honesty_boundary": (
            "This is a finite Lorentzian/projective spinor structure for the RG renderer. "
            "It is not yet a derivation of physical spacetime Lorentz symmetry or a continuum spin bundle."
        ),
        "checks": checks,
    }


def main() -> None:
    results = build_results()
    out_path = ROOT / "PART_CCCXXXI_lorentzian_rg_spinor_results.json"
    out_path.write_text(json.dumps(results, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    print(json.dumps({
        "part": results["part"],
        "verified": results["verified"],
        "checks_passed": results["checks_passed"],
        "checks_total": results["checks_total"],
        "out_path": str(out_path),
    }, indent=2))


if __name__ == "__main__":
    main()
