#!/usr/bin/env python3
"""
PART CCCCCXI: Heavy Yukawa Ladder Theorem

CCCCX and CCCCCX tied the Higgs/tau identity to the free-energy cumulant
bridge.  This part organizes the heavy Yukawa seeds themselves into a compact
Perron-determinant ladder.

Starting point:
    D_t = det(I+J) = v+1 = 41.

Then:
    D_b = q*D_t + lambda = 3*41 + 2 = 125 = (mu+1)^3,
    D_c = D_b + k = 125 + 12 = 137 = |(k-1)+mu*i|^2.

The heavy Yukawa seeds become:
    y_t^3 = v/D_t = 40/41,
    y_b   = q/D_b = 3/125,
    y_c   = 1/D_c = 1/137.

The tau Yukawa is then forced by the cumulant-derived Higgs quartic:
    lambda_H = 13/100,
    y_tau = lambda_H*y_b^2/y_c = 16029/1562500.

So the heavy Yukawa ladder is generated by:
    Perron determinant -> q-dressed determinant -> valency shift/Gaussian core
    plus cumulant-Higgs closure.

Run:
    python exploration/PART_CCCCCXI_HEAVY_YUKAWA_LADDER_THEOREM.py
"""
from __future__ import annotations

import json
import math
from fractions import Fraction
from pathlib import Path


def main() -> None:
    q = 3
    assert math.factorial(q) == 2*q
    lam = 2
    mu = 4
    k = q*(q+1)
    v = (q+1)*(q*q+1)
    E = v*k//2
    r = lam
    s = -mu
    f = 24
    g = 15
    phi3 = q*q + q + 1
    phi4 = q*q + 1
    phi6 = q*q - q + 1
    delta_r = k-r
    delta_s = k-s

    # Perron determinant ladder.
    D_t = v + 1
    D_b = q * D_t + lam
    D_c = D_b + k
    D_c_gaussian = (k-1)**2 + mu**2
    D_c_cyclotomic = phi3*phi4 + phi6

    y_t_cubed = Fraction(v, D_t)
    y_b = Fraction(q, D_b)
    y_c = Fraction(1, D_c)

    # Cumulant-derived Higgs and tau closure.
    excited_total = 2*f + 2*g
    excited_first_moment = 2*f*delta_r + 2*g*delta_s
    excited_mean = Fraction(excited_first_moment, excited_total)
    gap_ratio = Fraction(delta_s, delta_r)
    lambda_H = gap_ratio / excited_mean
    y_tau = lambda_H * y_b * y_b / y_c
    yukawa_higgs_ratio = y_tau * y_c / (y_b*y_b)

    # Internal ladder relations.
    bottom_minus_top_dressed = D_b - q*D_t
    charm_minus_bottom = D_c - D_b
    charm_minus_bottom_as_gap_sum_minus_phi3 = (delta_r + delta_s) - phi3

    # Cross-link to alpha.
    alpha_core = D_c
    alpha_slip_denominator_vac = (k-1)*((k-lam)**2 + 1)
    alpha_delta_m_num = q
    alpha_delta_m_den = lam*(k-1)

    # Predicted tau numerator/denominator explicit factorization.
    y_tau_alt = Fraction(phi3 * q*q * D_c, phi4*phi4 * D_b*D_b)

    checks = {
        "true_master_equation": math.factorial(q) == 2*q,
        "w33_atoms": (q, lam, mu, k, v, E, r, s, f, g) == (3,2,4,12,40,240,2,-4,24,15),
        "top_denominator_det_I_plus_J": D_t == v+1 == 41,
        "bottom_denominator_q_dressed_perron": D_b == q*D_t + lam == 125 == (mu+1)**3,
        "charm_denominator_valency_shift": D_c == D_b + k == 137,
        "charm_denominator_gaussian": D_c == D_c_gaussian == 137,
        "charm_denominator_cyclotomic": D_c == D_c_cyclotomic == 137,
        "y_t_cubed": y_t_cubed == Fraction(40,41),
        "y_b": y_b == Fraction(3,125),
        "y_c": y_c == Fraction(1,137),
        "bottom_minus_q_top_is_lambda": bottom_minus_top_dressed == lam,
        "charm_minus_bottom_is_k": charm_minus_bottom == k == 12,
        "charm_minus_bottom_gap_form": charm_minus_bottom == charm_minus_bottom_as_gap_sum_minus_phi3,
        "lambda_H_cumulant": lambda_H == Fraction(13,100),
        "y_tau_forced": y_tau == Fraction(16029,1562500),
        "y_tau_alt": y_tau == y_tau_alt,
        "yukawa_higgs_ratio": yukawa_higgs_ratio == lambda_H,
        "alpha_core_is_charm_denominator": alpha_core == D_c,
        "alpha_vac_denominator_1111": alpha_slip_denominator_vac == 1111,
        "alpha_delta_m_is_3_over_22": Fraction(alpha_delta_m_num, alpha_delta_m_den) == Fraction(3,22),
    }

    result = {
        "part": "CCCCCXI",
        "title": "Heavy Yukawa Ladder Theorem",
        "atoms": {
            "q": q, "lambda": lam, "mu": mu, "k": k, "v": v, "E": E,
            "r": r, "s": s, "f": f, "g": g, "Phi3": phi3, "Phi4": phi4, "Phi6": phi6,
        },
        "perron_determinant_ladder": {
            "D_t": D_t,
            "D_t_formula": "det(I+J)=v+1",
            "D_b": D_b,
            "D_b_formula": "q*D_t+lambda=(mu+1)^3",
            "D_c": D_c,
            "D_c_formula": "D_b+k=|(k-1)+mu*i|^2=Phi3*Phi4+Phi6",
        },
        "heavy_yukawa_seeds": {
            "y_t_cubed": str(y_t_cubed),
            "y_b": str(y_b),
            "y_c": str(y_c),
            "y_tau_forced": str(y_tau),
            "y_tau_decimal": float(y_tau),
        },
        "cumulant_higgs_input": {
            "excited_mean": str(excited_mean),
            "gap_ratio": str(gap_ratio),
            "lambda_H": str(lambda_H),
        },
        "ladder_relations": {
            "D_b_minus_q_D_t": bottom_minus_top_dressed,
            "D_c_minus_D_b": charm_minus_bottom,
            "D_c_minus_D_b_as_Delta_r_plus_Delta_s_minus_Phi3": charm_minus_bottom_as_gap_sum_minus_phi3,
            "y_tau_yc_over_yb_squared": str(yukawa_higgs_ratio),
        },
        "alpha_crosslink": {
            "alpha_core_equals_D_c": alpha_core,
            "M_vac": alpha_slip_denominator_vac,
            "Delta_M": "3/22",
        },
        "checks": checks,
        "all_checks_pass": all(checks.values()),
        "interpretation": (
            "The heavy Yukawa seeds form a denominator ladder: top uses the Perron determinant D_t=v+1=41; "
            "bottom uses the q-dressed Perron determinant D_b=qD_t+lambda=125; charm is the valency-shifted "
            "Gaussian core D_c=D_b+k=137. The cumulant-derived Higgs quartic then forces y_tau exactly."
        ),
    }

    out = Path("PART_CCCCCXI_heavy_yukawa_ladder_theorem_results.json")
    out.write_text(json.dumps(result, indent=2) + "\n", encoding="utf-8")

    print("PART CCCCCXI: Heavy Yukawa Ladder Theorem")
    print("="*86)
    for key, ok in checks.items():
        print(f"{'PASS' if ok else 'FAIL'} {key}")
    print("-"*86)
    print(f"D_t={D_t}, D_b={D_b}, D_c={D_c}")
    print(f"y_t^3={y_t_cubed}, y_b={y_b}, y_c={y_c}, y_tau={y_tau}")
    print(f"all_checks_pass={result['all_checks_pass']}")
    print(f"wrote {out}")

    assert result["all_checks_pass"]


if __name__ == "__main__":
    main()
