"""Faithful 12-point tomotope action on the Fourier-resolved tetrahedral packet.

The user supplied a degree-12 permutation model for the tomotope automorphism
group, generated by four involutions p0, p1, p2, p3.  The natural temptation is
to identify those 12 points with the 12 tomotope edges.  That is too naive.

Using the repo's actual 192-flag bundle, the stabilizer of one flag has order
96 but its induced action on the literal 12 tomotope edges has order only 12.
So the external degree-12 model is a different faithful permutation model of
Aut(T), not the raw edge action.

This bridge identifies the right local target for that faithful 12-point model:
the Fourier-resolved tetrahedral bridge packet

    12 = 3 local modes x 4 chart vertices.

In a suitable mode-major basis,

    A = {1,2,3,4}     radial block,
    B = {5,6,7,8}     first tangential block,
    C = {9,10,11,12}  second tangential block,

the generators become exact operations on (mode, chart):

    p1: swap radial <-> tangential-1 with chart flip lambda,
    p2: swap tangential-1 <-> tangential-2 with same chart,
    p0: swap tangential-1 <-> tangential-2 with chart flip lambda,
    p3: fix radial and apply chart flip kappa on both tangential blocks,

where

    lambda = (1 2)(3 4),
    kappa  = (1 4)(2 3).

So the faithful tomotope 12-point model is naturally the 3x4 Fourier packet,
not the raw source-major 4x3 bridge list.
"""

from __future__ import annotations

from collections import deque
import json
from pathlib import Path
import sys
from typing import Any
import zipfile


ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))
if str(ROOT / "exploration") not in sys.path:
    sys.path.insert(0, str(ROOT / "exploration"))

from exploration.w33_tetrahedral_fourier_clifford_bridge import build_summary as build_fourier_summary
from exploration.w33_tomotope_order_bridge import build_tomotope_order_summary


DEFAULT_OUTPUT_PATH = ROOT / "data" / "w33_tomotope_mode_chart_action_bridge_summary.json"
TOMOTOPE_BUNDLE = ROOT / "pillars" / "TOE_tomotope_true_flag_model_v02_20260228_bundle.zip"


Permutation = tuple[int, ...]


def compose(left: Permutation, right: Permutation) -> Permutation:
    return tuple(left[index] for index in right)


def generate_group(generators: list[Permutation]) -> set[Permutation]:
    identity = tuple(range(len(generators[0])))
    group = {identity}
    queue = deque([identity])

    while queue:
        element = queue.popleft()
        for generator in generators:
            image = compose(element, generator)
            if image not in group:
                group.add(image)
                queue.append(image)
    return group


def user_tomotope_generators() -> dict[str, Permutation]:
    permutations: dict[str, list[int]] = {f"p{index}": list(range(12)) for index in range(4)}
    for left, right in [(5, 10), (6, 9), (7, 12), (8, 11)]:
        permutations["p0"][left - 1], permutations["p0"][right - 1] = (
            permutations["p0"][right - 1],
            permutations["p0"][left - 1],
        )
    for left, right in [(1, 6), (2, 5), (3, 8), (4, 7)]:
        permutations["p1"][left - 1], permutations["p1"][right - 1] = (
            permutations["p1"][right - 1],
            permutations["p1"][left - 1],
        )
    for left, right in [(5, 9), (6, 10), (7, 11), (8, 12)]:
        permutations["p2"][left - 1], permutations["p2"][right - 1] = (
            permutations["p2"][right - 1],
            permutations["p2"][left - 1],
        )
    for left, right in [(5, 8), (6, 7), (9, 12), (10, 11)]:
        permutations["p3"][left - 1], permutations["p3"][right - 1] = (
            permutations["p3"][right - 1],
            permutations["p3"][left - 1],
        )
    return {name: tuple(values) for name, values in permutations.items()}


def apply_to_subset(permutation: Permutation, subset: frozenset[int]) -> frozenset[int]:
    return frozenset(permutation[index] for index in subset)


def find_blocks(group: set[Permutation], size: int, containing: int = 0) -> list[tuple[int, ...]]:
    from itertools import combinations

    blocks: list[tuple[int, ...]] = []
    for candidate in combinations(range(len(next(iter(group)))), size):
        if containing not in candidate:
            continue
        subset = frozenset(candidate)
        if all(
            (image := apply_to_subset(permutation, subset)) == subset or image.isdisjoint(subset)
            for permutation in group
        ):
            blocks.append(tuple(index + 1 for index in sorted(subset)))
    return blocks


def has_disjoint_block_system(group: set[Permutation], seed: frozenset[int]) -> bool:
    orbit = []
    seen = {seed}
    queue = deque([seed])
    while queue:
        subset = queue.popleft()
        orbit.append(subset)
        for permutation in group:
            image = apply_to_subset(permutation, subset)
            if image not in seen:
                seen.add(image)
                queue.append(image)

    union: set[int] = set()
    for subset in orbit:
        if union & subset:
            return False
        union |= set(subset)
    return len(union) == len(next(iter(group)))


def chart_flip_lambda(chart: int) -> int:
    return {1: 2, 2: 1, 3: 4, 4: 3}[chart]


def chart_flip_kappa(chart: int) -> int:
    return {1: 4, 2: 3, 3: 2, 4: 1}[chart]


def mode_chart_labels() -> dict[tuple[str, int], int]:
    labels: dict[tuple[str, int], int] = {}
    for offset, mode in enumerate(("radial", "tangent_a", "tangent_b")):
        for chart in range(1, 5):
            labels[(mode, chart)] = 4 * offset + chart
    return labels


def serializable_mode_chart_labels() -> dict[str, int]:
    return {
        f"{mode}_{chart}": value
        for (mode, chart), value in mode_chart_labels().items()
    }


def permutation_from_mode_chart_rule(rule) -> Permutation:
    labels = mode_chart_labels()
    inverse = {value: key for key, value in labels.items()}
    image = [0] * 12
    for point in range(1, 13):
        mode, chart = inverse[point]
        mode_image, chart_image = rule(mode, chart)
        image[point - 1] = labels[(mode_image, chart_image)] - 1
    return tuple(image)


def build_mode_chart_generators() -> dict[str, Permutation]:
    def p1_rule(mode: str, chart: int) -> tuple[str, int]:
        if mode == "radial":
            return ("tangent_a", chart_flip_lambda(chart))
        if mode == "tangent_a":
            return ("radial", chart_flip_lambda(chart))
        return ("tangent_b", chart)

    def p2_rule(mode: str, chart: int) -> tuple[str, int]:
        if mode == "tangent_a":
            return ("tangent_b", chart)
        if mode == "tangent_b":
            return ("tangent_a", chart)
        return ("radial", chart)

    def p0_rule(mode: str, chart: int) -> tuple[str, int]:
        if mode == "tangent_a":
            return ("tangent_b", chart_flip_lambda(chart))
        if mode == "tangent_b":
            return ("tangent_a", chart_flip_lambda(chart))
        return ("radial", chart)

    def p3_rule(mode: str, chart: int) -> tuple[str, int]:
        if mode == "radial":
            return ("radial", chart)
        return (mode, chart_flip_kappa(chart))

    return {
        "p0": permutation_from_mode_chart_rule(p0_rule),
        "p1": permutation_from_mode_chart_rule(p1_rule),
        "p2": permutation_from_mode_chart_rule(p2_rule),
        "p3": permutation_from_mode_chart_rule(p3_rule),
    }


def literal_edge_action_order() -> int:
    with zipfile.ZipFile(TOMOTOPE_BUNDLE) as zf:
        raw = json.loads(zf.read("tomotope_r_generators_192.json"))

    generators_192 = [tuple(raw[key]) for key in ("r0", "r1", "r2", "r3")]
    monodromy = generate_group(generators_192)
    stabilizer = [element for element in monodromy if element[0] == 0]

    edge_generators = [generators_192[index] for index in (0, 2, 3)]
    edge_orbit = [-1] * 192
    next_edge = 0
    for flag in range(192):
        if edge_orbit[flag] != -1:
            continue
        queue = deque([flag])
        edge_orbit[flag] = next_edge
        while queue:
            current = queue.popleft()
            for generator in edge_generators:
                image = generator[current]
                if edge_orbit[image] == -1:
                    edge_orbit[image] = next_edge
                    queue.append(image)
        next_edge += 1

    induced: set[Permutation] = set()
    representatives = [edge_orbit.index(edge) for edge in range(next_edge)]
    for element in stabilizer:
        image = [edge_orbit[element[representative]] for representative in representatives]
        induced.add(tuple(image))
    return len(induced)


def build_summary() -> dict[str, Any]:
    user_generators = user_tomotope_generators()
    user_group = generate_group(list(user_generators.values()))
    fourier = build_fourier_summary()
    tomotope = build_tomotope_order_summary()["tomotope"]
    mode_chart_generators = build_mode_chart_generators()
    size4_blocks = find_blocks(user_group, size=4, containing=0)
    size3_blocks = find_blocks(user_group, size=3, containing=0)
    literal_edge_order = literal_edge_action_order()

    summary: dict[str, Any] = {
        "user_model": {
            "generator_cycles": {
                name: [value + 1 for value in permutation]
                for name, permutation in user_generators.items()
            },
            "group_order": len(user_group),
            "blocks_of_size_4_containing_1": size4_blocks,
            "blocks_of_size_3_containing_1": size3_blocks,
        },
        "tetrahedral_fourier_packet": {
            "chart_count": 4,
            "mode_count": 3,
            "positive_charts": fourier["chirality_packet"]["positive_charts"],
            "negative_charts": fourier["chirality_packet"]["negative_charts"],
        },
        "mode_chart_model": {
            "labels": serializable_mode_chart_labels(),
            "lambda_chart_flip": {"1": 2, "2": 1, "3": 4, "4": 3},
            "kappa_chart_flip": {"1": 4, "2": 3, "3": 2, "4": 1},
            "generator_images": {
                name: [value + 1 for value in permutation]
                for name, permutation in mode_chart_generators.items()
            },
        },
        "bundle_check": {
            "tomotope_automorphism_group_order": tomotope["automorphism_group_order"],
            "literal_edge_action_order_from_flag_stabilizer": literal_edge_order,
        },
        "tomotope_mode_chart_theorem": {
            "the_user_degree_12_permutation_group_has_order_96": len(user_group) == 96,
            "the_user_model_has_a_unique_natural_three_blocks_of_four_partition": (
                size4_blocks == [(1, 2, 3, 4)]
                and has_disjoint_block_system(user_group, frozenset({0, 1, 2, 3}))
            ),
            "the_user_model_does_not_preserve_a_source_major_four_blocks_of_three_partition": (
                not has_disjoint_block_system(user_group, frozenset({0, 1, 2}))
            ),
            "the_fourier_packet_has_exactly_three_modes_and_four_charts": (
                fourier["chirality_packet"]["positive_count"] + fourier["chirality_packet"]["negative_count"] == 4
                and len({"radial", "tangent_a", "tangent_b"}) == 3
            ),
            "the_user_generators_match_the_explicit_mode_chart_formulas": (
                user_generators == mode_chart_generators
            ),
            "the_literal_tomotope_edge_action_is_not_the_faithful_degree_12_model": (
                literal_edge_order == 12
            ),
        },
        "interpretation": (
            "The faithful degree-12 tomotope model is naturally the Fourier-resolved "
            "3x4 packet of the tetrahedral bridge system: three local modes carried by "
            "four chart vertices. The raw 12 tomotope edges are too small to support the "
            "full order-96 action faithfully, so the right local basis is mode-major, "
            "not source-major."
        ),
    }
    return summary


def main() -> None:
    summary = build_summary()
    DEFAULT_OUTPUT_PATH.write_text(json.dumps(summary, indent=2), encoding="utf-8")
    print(json.dumps(summary["tomotope_mode_chart_theorem"], indent=2))


if __name__ == "__main__":
    main()
