"""Exact dihedral/Clifford algebra on the common W33 family plane.

The previous family bridges established the concrete operators on the exact
doublet plane shared by the CKM family envelope and the promoted neutrino
branch:

    R : family reflection, with q as +1 eigenline and n as -1 eigenline
    C : triality 3-cycle
    J : family complex structure, with C = -1/2 I + (sqrt(3)/2) J

This bridge compresses those into the smallest closed algebra.

On the (q, n) basis,

    R^2 = I,
    C^3 = I,
    R C R = C^{-1},

so the family operators carry the exact dihedral D6 action generated by one
reflection and one 3-fold rotation.  At the linear-algebra level,

    J^2 = -I,
    R J = -J R,

and with K = R J the span

    {I, R, J, K}

is a four-dimensional algebra with

    R^2 = I,   J^2 = -I,   K^2 = I.

So the exact family-plane algebra is the real Clifford algebra Cl_{1,1},
equivalently M_2(R).  The physical selectors then sit inside it directly:

    P_q = (I + R)/2,
    P_n = (I - R)/2,
    C   = -1/2 I + (sqrt(3)/2) J.
"""

from __future__ import annotations

import json
import math
from pathlib import Path
import sys
from typing import Any

import numpy as np

ROOT = Path(__file__).resolve().parents[1]
DATA_DIR = ROOT / "data"
DEFAULT_OUTPUT_PATH = DATA_DIR / "w33_family_dihedral_clifford_bridge_summary.json"

if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from exploration.w33_family_triality_complex_structure_bridge import (
    build_summary as build_complex_summary,
)


def _serialize_matrix(matrix: np.ndarray) -> list[list[float]]:
    return [[float(value) for value in row] for row in matrix]


def _basis_rank(matrices: list[np.ndarray]) -> int:
    return int(np.linalg.matrix_rank(np.column_stack([matrix.reshape(-1) for matrix in matrices])))


def build_summary() -> dict[str, Any]:
    complex_summary = build_complex_summary()

    reflection = np.array(
        complex_summary["family_triality_dictionary"]["reflection_in_qn_basis"],
        dtype=float,
    )
    cycle = np.array(
        complex_summary["family_triality_dictionary"]["cycle_in_qn_basis"],
        dtype=float,
    )
    family_j = np.array(
        complex_summary["family_triality_dictionary"]["derived_family_complex_structure_J"],
        dtype=float,
    )

    identity = np.eye(2)
    family_k = reflection @ family_j
    cycle_sq = cycle @ cycle
    quark_projector = (identity + reflection) / 2.0
    neutrino_projector = (identity - reflection) / 2.0
    d6_span = [identity, cycle, cycle_sq, reflection, reflection @ cycle, reflection @ cycle_sq]
    clifford_span = [identity, reflection, family_j, family_k]

    return {
        "family_algebra_dictionary": {
            "identity": _serialize_matrix(identity),
            "reflection_R": _serialize_matrix(reflection),
            "triality_cycle_C": _serialize_matrix(cycle),
            "complex_structure_J": _serialize_matrix(family_j),
            "second_reflection_K_equals_RJ": _serialize_matrix(family_k),
            "cycle_squared_C2": _serialize_matrix(cycle_sq),
            "quark_axis_projector_Pq": _serialize_matrix(quark_projector),
            "neutrino_axis_projector_Pn": _serialize_matrix(neutrino_projector),
            "d6_group_span_rank": _basis_rank(d6_span),
            "clifford_basis_rank": _basis_rank(clifford_span),
            "basis_relations": {
                "C_in_IJ_basis": "-1/2 I + (sqrt(3)/2) J",
                "C2_in_IJ_basis": "-1/2 I - (sqrt(3)/2) J",
                "Pq_in_IR_basis": "(I + R)/2",
                "Pn_in_IR_basis": "(I - R)/2",
            },
            "multiplication_packet": {
                "R_squared": _serialize_matrix(reflection @ reflection),
                "J_squared": _serialize_matrix(family_j @ family_j),
                "K_squared": _serialize_matrix(family_k @ family_k),
                "RJ_plus_JR": _serialize_matrix(reflection @ family_j + family_j @ reflection),
                "RJ": _serialize_matrix(reflection @ family_j),
                "JR": _serialize_matrix(family_j @ reflection),
            },
        },
        "family_dihedral_clifford_theorem": {
            "the_family_reflection_and_triality_cycle_generate_an_exact_D6_action": bool(
                np.allclose(reflection @ reflection, identity, atol=1e-12)
                and np.allclose(cycle @ cycle @ cycle, identity, atol=1e-12)
                and np.allclose(reflection @ cycle @ reflection, cycle_sq, atol=1e-12)
            ),
            "the_family_complex_structure_is_recovered_exactly_from_the_triality_cycle": bool(
                np.allclose(
                    cycle,
                    -0.5 * identity + (math.sqrt(3.0) / 2.0) * family_j,
                    atol=1e-12,
                )
            ),
            "R_and_J_are_exact_Cl_1_1_generators_with_R_squared_1_J_squared_minus1_and_anticommutator_zero": bool(
                np.allclose(reflection @ reflection, identity, atol=1e-12)
                and np.allclose(family_j @ family_j, -identity, atol=1e-12)
                and np.allclose(reflection @ family_j + family_j @ reflection, np.zeros((2, 2)), atol=1e-12)
            ),
            "the_span_of_I_R_J_RJ_is_exactly_four_dimensional_and_so_is_the_full_family_plane_matrix_algebra": (
                _basis_rank(clifford_span) == 4
            ),
            "the_quark_and_neutrino_axis_projectors_are_exactly_the_two_idempotents_of_the_family_reflection": bool(
                np.allclose(quark_projector @ quark_projector, quark_projector, atol=1e-12)
                and np.allclose(neutrino_projector @ neutrino_projector, neutrino_projector, atol=1e-12)
                and np.allclose(quark_projector @ neutrino_projector, np.zeros((2, 2)), atol=1e-12)
                and np.allclose(quark_projector + neutrino_projector, identity, atol=1e-12)
            ),
            "the_common_family_plane_is_therefore_one_exact_D6_inside_Cl_1_1_operator_algebra": True,
        },
        "interpretation": (
            "The family sector has now compressed to one exact small algebra. "
            "The quark and neutrino directions are the two idempotents of the family "
            "reflection, the triality 3-cycle is the corresponding complex rotation, "
            "and together they generate an exact D6 action whose linear span is the "
            "real Clifford algebra Cl_{1,1} = M_2(R). This is the same common family "
            "operator stack behind the quark axis, the neutrino axis, and the triality "
            "rotation that feeds the higher-degree CP shadow."
        ),
    }


def main() -> None:
    summary = build_summary()
    DEFAULT_OUTPUT_PATH.write_text(json.dumps(summary, indent=2), encoding="utf-8")
    print("=" * 72)
    print("W33 FAMILY DIHEDRAL / CLIFFORD BRIDGE")
    print("=" * 72)
    for key, value in summary["family_dihedral_clifford_theorem"].items():
        status = "PASS" if value else "FAIL"
        print(f"  [{status}] {key}")


if __name__ == "__main__":
    main()
