"""Finite input grammar for the standard CKM packet from Levi-family data.

The recent CKM bridges closed the standard package as exact W33 packet ratios:

    lambda = 9/40,
    A^2    = (20^2 / q^6) * (53/43),
    R_u    = q^2 k / (5 * 53),
    tan^2 gamma = 1280/243.

This bridge sharpens the phase side by welding it to the affine mu-grammar.
Since mu = 4,

    mu^4 = 2^8 = 256,

so

    tan^2 gamma = mu^4 * 5 / q^5.

Hence the whole standard CKM packet is already generated by the finite alphabet

    {q, mu, 5, 20, 40, 53, 43, k},

with exact forms

    lambda   = q^2 / 40,
    A^2      = 20^2 * 53 / (q^6 * 43),
    R_u      = q^2 k / (5 * 53),
    tan^2 γ  = mu^4 * 5 / q^5,
    cos^2 γ  = q^5 / (q^5 + mu^4 * 5),
    sin^2 γ  = mu^4 * 5 / (q^5 + mu^4 * 5),
    |V_cb|^2 = q^2 * 53 / (mu^4 * 5^2 * 43),
    |V_ub|^2 = q^10 * k^2 / (mu^4 * 40^2 * 5^4 * 53 * 43).
"""

from __future__ import annotations

from fractions import Fraction
import json
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
DATA_DIR = ROOT / "data"
DEFAULT_OUTPUT_PATH = DATA_DIR / "w33_levi_ckm_mu_grammar_bridge_summary.json"


Q = 3
MU = 4
BOTT_FIVE = 5
CURVATURE_20 = 20
POINT_40 = 40
TRIALITY_PLUS = 53
TRIALITY_MINUS = 43
K = 12

LAMBDA = Fraction(9, 40)
A2 = Fraction(21200, 31347)
R_U = Fraction(108, 265)
TAN2_GAMMA = Fraction(1280, 243)
COS2_GAMMA = Fraction(243, 1523)
SIN2_GAMMA = Fraction(1280, 1523)
VCB2 = Fraction(477, 275200)
VUB2 = Fraction(531441, 36464000000)


def _fraction_report(value: Fraction) -> dict[str, Any]:
    return {"exact": str(value), "value": float(value)}


def build_summary() -> dict[str, Any]:
    lambda_from_grammar = Fraction(Q * Q, POINT_40)
    a2_from_grammar = Fraction(CURVATURE_20 * CURVATURE_20 * TRIALITY_PLUS, Q**6 * TRIALITY_MINUS)
    ru_from_grammar = Fraction(Q * Q * K, BOTT_FIVE * TRIALITY_PLUS)
    tan2_from_grammar = Fraction(MU**4 * BOTT_FIVE, Q**5)
    gamma_denominator = Q**5 + MU**4 * BOTT_FIVE
    cos2_from_grammar = Fraction(Q**5, gamma_denominator)
    sin2_from_grammar = Fraction(MU**4 * BOTT_FIVE, gamma_denominator)
    vcb2_from_grammar = Fraction(Q * Q * TRIALITY_PLUS, MU**4 * BOTT_FIVE**2 * TRIALITY_MINUS)
    vub2_from_grammar = Fraction(Q**10 * K * K, MU**4 * POINT_40**2 * BOTT_FIVE**4 * TRIALITY_PLUS * TRIALITY_MINUS)

    return {
        "levi_ckm_mu_grammar_dictionary": {
            "q": Q,
            "mu": MU,
            "bott_five": BOTT_FIVE,
            "curvature_20": CURVATURE_20,
            "point_40": POINT_40,
            "triality_plus_53": TRIALITY_PLUS,
            "triality_minus_43": TRIALITY_MINUS,
            "k": K,
            "mu_fourth_power": MU**4,
            "gamma_denominator_q5_plus_mu4_times_5": gamma_denominator,
            "lambda": _fraction_report(LAMBDA),
            "A_squared": _fraction_report(A2),
            "R_u": _fraction_report(R_U),
            "tan2_gamma": _fraction_report(TAN2_GAMMA),
            "cos2_gamma": _fraction_report(COS2_GAMMA),
            "sin2_gamma": _fraction_report(SIN2_GAMMA),
            "Vcb_squared": _fraction_report(VCB2),
            "Vub_squared": _fraction_report(VUB2),
        },
        "levi_ckm_mu_grammar_theorem": {
            "the_standard_branch_filtered_Cabibbo_parameter_is_exactly_q_squared_over_40": bool(
                LAMBDA == lambda_from_grammar
            ),
            "the_standard_Wolfenstein_A_squared_parameter_is_exactly_20_squared_times_53_over_q_six_times_43": bool(
                A2 == a2_from_grammar
            ),
            "the_standard_unitarity_triangle_radius_Ru_is_exactly_q_squared_k_over_5_times_53": bool(
                R_U == ru_from_grammar
            ),
            "the_standard_CKM_phase_tangent_squared_is_exactly_mu_to_4_times_5_over_q_to_5": bool(
                TAN2_GAMMA == tan2_from_grammar
            ),
            "the_standard_gamma_phase_squares_are_exactly_the_split_q5_over_q5_plus_mu4_5_and_mu4_5_over_q5_plus_mu4_5": bool(
                COS2_GAMMA == cos2_from_grammar and SIN2_GAMMA == sin2_from_grammar
            ),
            "the_standard_Vcb_scale_is_exactly_q_squared_53_over_mu4_5_squared_43": bool(
                VCB2 == vcb2_from_grammar
            ),
            "the_standard_Vub_scale_is_exactly_q10_k_squared_over_mu4_40_squared_5_to_4_53_43": bool(
                VUB2 == vub2_from_grammar
            ),
            "the_standard_CKM_packet_is_generated_by_the_exact_finite_alphabet_q_mu_5_20_40_53_43_k": bool(
                LAMBDA == lambda_from_grammar
                and A2 == a2_from_grammar
                and R_U == ru_from_grammar
                and TAN2_GAMMA == tan2_from_grammar
                and COS2_GAMMA == cos2_from_grammar
                and SIN2_GAMMA == sin2_from_grammar
                and VCB2 == vcb2_from_grammar
                and VUB2 == vub2_from_grammar
            ),
        },
        "interpretation": (
            "The standard CKM package is now generated by one finite grammar. "
            "The phase side is not separate from the affine mu-input story: "
            "tan^2(gamma) is exactly mu^4*5/q^5, and the rest of the standard "
            "Wolfenstein and unitarity-triangle data ride on the same q/mu/"
            "curvature/point/triality alphabet."
        ),
    }


def main() -> None:
    summary = build_summary()
    DEFAULT_OUTPUT_PATH.write_text(json.dumps(summary, indent=2), encoding="utf-8")
    print("=" * 72)
    print("W33 LEVI CKM MU-GRAMMAR BRIDGE")
    print("=" * 72)
    for key, value in summary["levi_ckm_mu_grammar_theorem"].items():
        status = "PASS" if value else "FAIL"
        print(f"  [{status}] {key}")


if __name__ == "__main__":
    main()
