"""Exact bridge from the modular generator weights 4,6 to the W33 packet ladder.

The modular ring side is generated by weights

    4, 6

through

    M_*(SL(2,Z)) = C[E_4, E_6].

Those two weights are not isolated classical data in this repo. They already
match the exact W33 packet ladder:

    4   = chart count,
    6   = centered toroidal shell dimension,
    10  = 4 + 6 = Phi_4 packet,
    12  = lcm(4,6) = modular period = toroidal genus numerator,
    24  = 4 * 6 = corrected noncore complement.

The first mixed modular weight is therefore 10, forced by the unique monomial
E_4 E_6, while the first collision is 12, forced by

    3*4 = 2*6 = 12,

which is exactly why dim M_12 = 2 and the Delta / 691 layer first appears
there.
"""

from __future__ import annotations

import json
import sys
from math import lcm
from pathlib import Path
from typing import Any

try:
    from exploration.w33_bridge_inputs import load_bridge_json
except ModuleNotFoundError:  # pragma: no cover - direct script execution
    from w33_bridge_inputs import load_bridge_json


ROOT = Path(__file__).resolve().parents[1]
DATA_DIR = ROOT / "data"
DEFAULT_OUTPUT_PATH = DATA_DIR / "w33_modular_generator_packet_bridge_summary.json"

if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))
if str(ROOT / "exploration") not in sys.path:
    sys.path.insert(0, str(ROOT / "exploration"))

from w33_modular_dimension_formula import dim_M


def _load_json(name: str) -> dict[str, Any]:
    return load_bridge_json(name, DATA_DIR)


def _list_monomials(k: int) -> list[tuple[int, int]]:
    monomials: list[tuple[int, int]] = []
    for b in range(k // 6 + 1):
        rem = k - 6 * b
        if rem >= 0 and rem % 4 == 0:
            monomials.append((rem // 4, b))
    return monomials


def build_summary() -> dict[str, Any]:
    mod12 = _load_json("w33_mod12_packet_selector_bridge_summary.json")
    heptad = _load_json("w33_toroidal_heptad_projector_bridge_summary.json")

    chart_count = int(mod12["packet_counts"]["chart_count"])
    centered_shell = int(heptad["dictionary"]["centered_shell_dimension"])
    phi4_packet = 10
    noncore_24 = 24
    genus_numerator = int(heptad["dictionary"]["toroidal_genus_numerator"])

    e4_weight = 4
    e6_weight = 6
    mixed_weight = e4_weight + e6_weight
    collision_weight = lcm(e4_weight, e6_weight)
    product_weight = e4_weight * e6_weight

    monomials_10 = _list_monomials(mixed_weight)
    monomials_12 = _list_monomials(collision_weight)

    return {
        "modular_generator_packet_dictionary": {
            "E4_weight": e4_weight,
            "E6_weight": e6_weight,
            "chart_count": chart_count,
            "centered_shell_dimension": centered_shell,
            "Phi_4_packet": phi4_packet,
            "modular_period": collision_weight,
            "toroidal_genus_numerator": genus_numerator,
            "corrected_24_packet": noncore_24,
            "first_mixed_modular_weight": mixed_weight,
            "first_collision_weight": collision_weight,
        },
        "monomial_dictionary": {
            "weight_10_monomials": monomials_10,
            "weight_12_monomials": monomials_12,
            "dim_M_10": dim_M(mixed_weight),
            "dim_M_12": dim_M(collision_weight),
        },
        "modular_generator_packet_theorem": {
            "E4_weight_equals_the_exact_chart_count": e4_weight == chart_count,
            "E6_weight_equals_the_exact_centered_toroidal_shell_dimension": e6_weight
            == centered_shell,
            "the_generator_sum_4_plus_6_equals_the_existing_Phi_4_packet_10": mixed_weight
            == phi4_packet,
            "the_generator_lcm_equals_the_modular_period_and_toroidal_genus_numerator": (
                collision_weight == genus_numerator == 12
            ),
            "the_generator_product_equals_the_corrected_noncore_24_packet": product_weight
            == noncore_24,
            "weight_10_is_the_unique_mixed_generator_weight_with_dim_one": (
                monomials_10 == [(1, 1)] and dim_M(mixed_weight) == 1
            ),
            "weight_12_is_the_first_generator_collision_weight_with_two_monomials": (
                monomials_12 == [(3, 0), (0, 2)] and dim_M(collision_weight) == 2
            ),
            "the_modular_generator_grammar_4_6_closes_exactly_on_the_old_W33_packet_ladder_10_12_24": (
                e4_weight == chart_count
                and e6_weight == centered_shell
                and mixed_weight == phi4_packet
                and collision_weight == genus_numerator
                and product_weight == noncore_24
            ),
        },
        "interpretation": (
            "The modular ring generators are already W33 packet numbers. Weight 4 "
            "is the tetra chart count, weight 6 is the centered toroidal shell, "
            "their sum 10 is the Phi_4 packet, their least common multiple 12 is "
            "the modular period and toroidal genus numerator, and their product 24 "
            "is the corrected noncore complement. So the modular grammar C[E4,E6] "
            "lands directly on the old operator ladder rather than floating above it."
        ),
    }


def main() -> None:
    summary = build_summary()
    DEFAULT_OUTPUT_PATH.write_text(json.dumps(summary, indent=2), encoding="utf-8")
    print("=" * 72)
    print("W33 MODULAR GENERATOR PACKET BRIDGE")
    print("=" * 72)
    for key, value in summary["modular_generator_packet_theorem"].items():
        status = "PASS" if value else "FAIL"
        print(f"  [{status}] {key}")


if __name__ == "__main__":
    main()
