#!/usr/bin/env python3
"""
PART CXLIX — Projection Layer for Previously Unclassified W(3,3) Fractions
==========================================================================

CXLVIII deliberately left several attractive W(3,3) fractions unclassified by
the Fibonacci/E6 mixer grammar:

    Phi6/Phi3 = 7/13
    (k-1)/Phi3 = 11/13
    k/Phi3 = 12/13
    Phi3/Phi6 = 13/7

This module adds the missing operation without weakening the mixer boundary.

Key distinction:
    Mixer grammar tokens are generated from the carrier/threshold pair
        C=8/13, T=5/13, D=C-T=3/13.

    Projection-layer tokens are generated by normalizing a structural W(3,3)
    atom A by the projective denominator Phi3=13:
        P(A) = A/Phi3.

The projection layer therefore classifies the formerly unmatched fractions as
field/radial/degree projections:

    P(Phi6) = 7/13          threshold-field projection
    P(k-1)  = 11/13         Hashimoto-radius/norm projection
    P(k)    = 12/13         adjacency-degree projection
    P(Phi6)^(-1)=13/7       inverse threshold-field projection

This keeps the architecture disciplined: these fractions are not retroactively
called mixer tokens. They live in a separate projection layer, whose operation
is exact and auditable.
"""

from __future__ import annotations

import json
from dataclasses import asdict, dataclass
from fractions import Fraction
from pathlib import Path
from typing import Dict, List, Optional

ROOT = Path(__file__).resolve().parent

Q = 3
K = 12
MU = 4
PHI3 = Q * Q + Q + 1
PHI4 = Q * Q + 1
PHI6 = Q * Q - Q + 1
HASHIMOTO_NORM = K - 1


@dataclass(frozen=True)
class ProjectionToken:
    name: str
    atom: str
    operation: str
    value: str
    decimal: float
    projection_class: str
    interpretation: str


def projection(atom_value: int) -> Fraction:
    """Project a W(3,3) structural atom through the Phi3 denominator."""
    return Fraction(atom_value, PHI3)


def inverse_projection(atom_value: int) -> Fraction:
    """Inverse of the Phi3-normalized projection."""
    return Fraction(PHI3, atom_value)


def projection_tokens() -> List[ProjectionToken]:
    raw = [
        (
            "threshold_field_projection",
            "Phi6",
            "P(Phi6)=Phi6/Phi3",
            projection(PHI6),
            "field projection",
            "pure Phi6 threshold-field projection",
        ),
        (
            "phi4_field_projection",
            "Phi4",
            "P(Phi4)=Phi4/Phi3",
            projection(PHI4),
            "field projection / mixer overlap",
            "Phi4 projection; also equals CXLVII complement 1-D",
        ),
        (
            "hashimoto_norm_projection",
            "k-1",
            "P(k-1)=(k-1)/Phi3",
            projection(HASHIMOTO_NORM),
            "radial projection",
            "Hashimoto radius/norm projection",
        ),
        (
            "adjacency_degree_projection",
            "k",
            "P(k)=k/Phi3",
            projection(K),
            "degree projection",
            "adjacency degree projection",
        ),
        (
            "unit_projection",
            "Phi3",
            "P(Phi3)=1",
            projection(PHI3),
            "normalization projection",
            "projective denominator closes the layer",
        ),
        (
            "inverse_threshold_projection",
            "Phi6",
            "P(Phi6)^(-1)=Phi3/Phi6",
            inverse_projection(PHI6),
            "inverse projection",
            "inverse threshold-field ratio, earlier 13/7 branch candidate",
        ),
        (
            "inverse_hashimoto_norm_projection",
            "k-1",
            "P(k-1)^(-1)=Phi3/(k-1)",
            inverse_projection(HASHIMOTO_NORM),
            "inverse radial projection",
            "inverse Hashimoto norm projection",
        ),
    ]
    return [
        ProjectionToken(name, atom, op, str(value), float(value), cls, interp)
        for name, atom, op, value, cls, interp in raw
    ]


def projection_dictionary() -> Dict[Fraction, ProjectionToken]:
    return {Fraction(t.value): t for t in projection_tokens()}


@dataclass(frozen=True)
class ProjectionClassification:
    label: str
    expression: str
    value: str
    decimal: float
    matched: bool
    projection_name: Optional[str]
    projection_class: Optional[str]
    operation: Optional[str]
    interpretation: Optional[str]


def classify_projection(label: str, value: Fraction, expression: str | None = None) -> ProjectionClassification:
    match = projection_dictionary().get(value)
    return ProjectionClassification(
        label=label,
        expression=expression or str(value),
        value=str(value),
        decimal=float(value),
        matched=match is not None,
        projection_name=None if match is None else match.name,
        projection_class=None if match is None else match.projection_class,
        operation=None if match is None else match.operation,
        interpretation=None if match is None else match.interpretation,
    )


def formerly_unclassified_classifications() -> List[ProjectionClassification]:
    raw = [
        ("phi6_over_phi3", Fraction(PHI6, PHI3), "Phi6/Phi3 = 7/13"),
        ("hashimoto_norm_over_phi3", Fraction(HASHIMOTO_NORM, PHI3), "(k-1)/Phi3 = 11/13"),
        ("k_over_phi3", Fraction(K, PHI3), "k/Phi3 = 12/13"),
        ("phi3_over_phi6", Fraction(PHI3, PHI6), "Phi3/Phi6 = 13/7"),
    ]
    return [classify_projection(label, value, expr) for label, value, expr in raw]


def projection_layer_audit() -> Dict[str, object]:
    classifications = formerly_unclassified_classifications()
    by_label = {c.label: c for c in classifications}

    checks = {
        "phi6_projection_matches": by_label["phi6_over_phi3"].matched,
        "hashimoto_norm_projection_matches": by_label["hashimoto_norm_over_phi3"].matched,
        "degree_projection_matches": by_label["k_over_phi3"].matched,
        "inverse_phi6_projection_matches": by_label["phi3_over_phi6"].matched,
        "phi4_projection_is_mixer_complement": projection(PHI4) == Fraction(10, 13),
        "projection_layer_keeps_mixer_distinction": projection(PHI6) != Fraction(8, 13) and projection(PHI6) != Fraction(5, 13),
        "radial_projection_is_hashimoto_norm": projection(HASHIMOTO_NORM) == Fraction(11, 13),
        "degree_projection_is_k_over_phi3": projection(K) == Fraction(12, 13),
    }
    assert all(checks.values())

    return {
        "module": "PART_CXLIX_PROJECTION_LAYER",
        "w33_atoms": {
            "q": Q,
            "k": K,
            "mu": MU,
            "Phi3": PHI3,
            "Phi4": PHI4,
            "Phi6": PHI6,
            "Hashimoto_norm_k_minus_1": HASHIMOTO_NORM,
        },
        "operation": {
            "projection": "P(A)=A/Phi3 for structural atom A",
            "inverse_projection": "P(A)^(-1)=Phi3/A",
            "boundary_rule": "Projection tokens are not automatically mixer tokens; they form a separate layer.",
        },
        "projection_tokens": [asdict(t) for t in projection_tokens()],
        "formerly_unclassified_classifications": [asdict(c) for c in classifications],
        "checks": checks,
        "theorem_statement": (
            "The fractions 7/13, 11/13, 12/13, and 13/7 are generated by a new "
            "projection layer P(A)=A/Phi3 and inverse projection P(A)^(-1), not by "
            "the Fibonacci/E6 mixer grammar.  This classifies Phi6/Phi3 as a "
            "threshold-field projection, (k-1)/Phi3 as a Hashimoto radial projection, "
            "k/Phi3 as a degree projection, and Phi3/Phi6 as an inverse threshold "
            "projection."
        ),
        "interpretive_note": (
            "This repairs the CXLVIII boundary without weakening it.  The mixer "
            "grammar and projection layer are distinct: mixer tokens describe "
            "carrier/threshold mixing, while projection tokens describe direct "
            "normalization of structural atoms by the Phi3 projective denominator."
        ),
    }


def main() -> int:
    audit = projection_layer_audit()
    out = ROOT / "PART_CXLIX_projection_layer_results.json"
    out.write_text(json.dumps(audit, indent=2), encoding="utf-8")
    print(json.dumps(audit, indent=2))
    print(f"\nWrote {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
