#!/usr/bin/env python3
"""
PART CLXI - Projective Stabilizer Residue
========================================

CLX asked whether the global stabilizer

    S = (2q)! = 720

normalizes the observable grammar

    C = 8/13, T = 5/13, D = 3/13, P(A)=A/Phi3.

The answer is more precise: S does not normalize the grammar by ordinary
integer divisibility because Phi3=13 does not divide 720.  Instead, S
normalizes the grammar projectively, through its residue in F_13.

At q=3:

    S mod Phi3 = 720 mod 13 = 5.

This is exactly the threshold numerator T_num=5.  Its inverse in F_13 is

    5^{-1} = 8 mod 13,

which is exactly the carrier numerator C_num=8.

Therefore the Fibonacci/E6 mixer is recovered from the projective residue of
the global root stabilizer:

    T = S/Phi3 projectively = 5/13,
    C = S^{-1}/Phi3 projectively = 8/13,
    D = C - T = 3/13.

Even better, the same residue pair generates the cyclotomic bridge:

    C + T = 13 = Phi3,
    C - T = 3 = q,
    Phi4 = Phi3 - q = 10 = 2T,
    Phi6 = Phi4 - q = 7 = 3T - C,
    k = 12 = T^2 mod 13.

Thus the root stabilizer is not just a global orbit-stabilizer denominator.
It is a projective generator of the observable grammar.
"""

from __future__ import annotations

import json
import math
from dataclasses import asdict, dataclass
from fractions import Fraction
from pathlib import Path
from typing import Dict, List

ROOT = Path(__file__).resolve().parent

Q = 3
K = 12
MU = 4
PHI3 = Q * Q + Q + 1
PHI4 = Q * Q + 1
PHI6 = Q * Q - Q + 1
HASHIMOTO_NORM = K - 1
STABILIZER = math.factorial(2 * Q)

T_NUM = STABILIZER % PHI3
C_NUM = pow(T_NUM, -1, PHI3)
D_NUM = C_NUM - T_NUM


@dataclass(frozen=True)
class ResidueIdentity:
    name: str
    formula: str
    value: str
    interpretation: str


def mod13(value: int) -> int:
    return value % PHI3


def residue_identities() -> List[ResidueIdentity]:
    return [
        ResidueIdentity(
            name="stabilizer_residue",
            formula="S=(2q)! congruent T_num mod Phi3",
            value=f"{STABILIZER} mod {PHI3} = {T_NUM}",
            interpretation="global root stabilizer projects to threshold numerator",
        ),
        ResidueIdentity(
            name="inverse_residue",
            formula="T_num^{-1} congruent C_num mod Phi3",
            value=f"{T_NUM}^(-1) mod {PHI3} = {C_NUM}",
            interpretation="projective inverse of threshold residue is carrier numerator",
        ),
        ResidueIdentity(
            name="mixer_sum",
            formula="C_num + T_num = Phi3",
            value=f"{C_NUM}+{T_NUM}={C_NUM + T_NUM}",
            interpretation="carrier and threshold close the Phi3 denominator",
        ),
        ResidueIdentity(
            name="mixer_imbalance",
            formula="C_num - T_num = q",
            value=f"{C_NUM}-{T_NUM}={D_NUM}",
            interpretation="mixer imbalance recovers the q-clock",
        ),
        ResidueIdentity(
            name="bridge_from_residue",
            formula="Phi4 = 2*T_num = Phi3 - q",
            value=f"2*{T_NUM}={2*T_NUM}={PHI4}",
            interpretation="cyclotomic bridge generated by doubled stabilizer residue",
        ),
        ResidueIdentity(
            name="threshold_field_from_residue_pair",
            formula="Phi6 = 3*T_num - C_num",
            value=f"3*{T_NUM}-{C_NUM}={3*T_NUM-C_NUM}",
            interpretation="threshold field generated from stabilizer residue and inverse",
        ),
        ResidueIdentity(
            name="degree_from_residue_square",
            formula="k congruent T_num^2 mod Phi3",
            value=f"{T_NUM}^2 mod {PHI3} = {mod13(T_NUM*T_NUM)}",
            interpretation="adjacency degree is the square of the stabilizer residue in F_13",
        ),
    ]


def projective_stabilizer_residue_audit() -> Dict[str, object]:
    checks = {
        "stabilizer_is_720": STABILIZER == 720,
        "stabilizer_not_divisible_by_phi3": STABILIZER % PHI3 != 0,
        "stabilizer_residue_is_threshold_num": T_NUM == 5,
        "inverse_residue_is_carrier_num": C_NUM == 8,
        "residue_pair_inverse": (T_NUM * C_NUM) % PHI3 == 1,
        "mixer_sum_is_phi3": C_NUM + T_NUM == PHI3,
        "mixer_imbalance_is_q": C_NUM - T_NUM == Q,
        "carrier_weight": Fraction(C_NUM, PHI3) == Fraction(8, 13),
        "threshold_weight": Fraction(T_NUM, PHI3) == Fraction(5, 13),
        "imbalance_weight": Fraction(D_NUM, PHI3) == Fraction(Q, PHI3) == Fraction(3, 13),
        "phi4_from_doubled_residue": 2 * T_NUM == PHI4 == 10,
        "phi6_from_residue_pair": 3 * T_NUM - C_NUM == PHI6 == 7,
        "degree_from_residue_square": mod13(T_NUM * T_NUM) == K == 12,
        "hashimoto_norm_from_degree_minus_one": K - 1 == HASHIMOTO_NORM == 11,
        "cyclotomic_bridge_from_residue": PHI3 - (C_NUM - T_NUM) == PHI4,
    }
    assert all(checks.values())

    return {
        "module": "PART_CLXI_PROJECTIVE_STABILIZER_RESIDUE",
        "source_links": {
            "CLX": "factorial stabilizer operator",
            "CLIII": "cyclotomic bridge operator",
            "CXLVI_CXLVII": "Fibonacci E6 mixer and observable grammar",
        },
        "w33_atoms": {
            "q": Q,
            "k": K,
            "mu": MU,
            "Phi3": PHI3,
            "Phi4": PHI4,
            "Phi6": PHI6,
            "Hashimoto_norm": HASHIMOTO_NORM,
            "stabilizer_S": STABILIZER,
        },
        "projective_residue": {
            "S_mod_Phi3": T_NUM,
            "inverse_mod_Phi3": C_NUM,
            "threshold_weight": str(Fraction(T_NUM, PHI3)),
            "carrier_weight": str(Fraction(C_NUM, PHI3)),
            "imbalance_weight": str(Fraction(D_NUM, PHI3)),
        },
        "generated_atoms": {
            "Phi3": "C_num + T_num = 13",
            "q": "C_num - T_num = 3",
            "Phi4": "2*T_num = 10 = Phi3-q",
            "Phi6": "3*T_num - C_num = 7",
            "k": "T_num^2 mod Phi3 = 12",
            "k_minus_1": "k-1 = 11",
        },
        "identities": [asdict(i) for i in residue_identities()],
        "checks": checks,
        "theorem_statement": (
            "The global stabilizer S=(2q)!=720 normalizes the observable grammar "
            "projectively: S mod Phi3 is 5, the threshold numerator, and its inverse "
            "in F_13 is 8, the carrier numerator.  Their sum gives Phi3, their "
            "difference gives q, doubled threshold gives Phi4, and the residue pair "
            "generates Phi6, k, and k-1."
        ),
        "interpretive_note": (
            "This is stronger than divisibility.  The root stabilizer is a projective "
            "generator for the two-layer observable algebra.  The Fibonacci mixer pair "
            "8:5 is the inverse/residue pair of the global factorial stabilizer modulo "
            "Phi3."
        ),
    }


def main() -> int:
    audit = projective_stabilizer_residue_audit()
    out = ROOT / "PART_CLXI_projective_stabilizer_residue_results.json"
    out.write_text(json.dumps(audit, indent=2), encoding="utf-8")
    print(json.dumps(audit, indent=2))
    print(f"\nWrote {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
