#!/usr/bin/env python3
"""
PART CXLVIII — Grammar Tagger for W(3,3) Observables
===================================================

CXLVII built an exact observable grammar from the Fibonacci E6 mixer:

    C = 8/13        carrier
    T = 5/13        threshold
    D = C-T = 3/13  imbalance

This module turns that grammar into a tagger.  The point is to stop treating
numbers such as 24/13, 10/13, 16/13, and 3/13 as isolated discoveries.
They are generated by a small set of operations on the same mixer.

Supported grammar classes:
    base/carrier          C = 8/13
    base/threshold        T = 5/13
    imbalance             D = 3/13
    complement            1-D = 10/13 = Phi4/Phi3
    plus_branch           1+D = 16/13 = (k+mu)/Phi3
    q_lift/carrier        q*C = 24/13
    q_lift/threshold      q*T = 15/13
    q_lift/imbalance      q*D = 9/13
    inverse/complement    13/10
    inverse/imbalance     13/3
    inverse/qcd_bare      13/24

The tagger is intentionally exact rational arithmetic.  If a proposed formula
cannot be written as one of these grammar tokens, it should not be promoted as
part of the mixer architecture without a new operation rule.
"""

from __future__ import annotations

import json
from dataclasses import asdict, dataclass
from fractions import Fraction
from pathlib import Path
from typing import Dict, Iterable, List, Optional

ROOT = Path(__file__).resolve().parent

Q = 3
K = 12
MU = 4
PHI3 = Q * Q + Q + 1
PHI4 = Q * Q + 1
PHI6 = Q * Q - Q + 1

C = Fraction(8, PHI3)
T = Fraction(5, PHI3)
D = C - T


@dataclass(frozen=True)
class GrammarTag:
    name: str
    value: str
    decimal: float
    grammar_class: str
    operation: str
    interpretation: str


def grammar_dictionary() -> Dict[Fraction, GrammarTag]:
    entries = [
        GrammarTag("C", str(C), float(C), "base/carrier", "C", "carrier weight"),
        GrammarTag("T", str(T), float(T), "base/threshold", "T", "threshold weight"),
        GrammarTag("D", str(D), float(D), "imbalance", "C-T", "carrier-threshold imbalance"),
        GrammarTag("Phi4_over_Phi3", str(1 - D), float(1 - D), "complement", "1-D", "Phi4/Ko complement"),
        GrammarTag("heavy_plus", str(1 + D), float(1 + D), "plus_branch", "1+D", "heavy normalized k+mu branch"),
        GrammarTag("qC", str(Q * C), float(Q * C), "q_lift/carrier", "q*C", "QCD bare embedding factor"),
        GrammarTag("qT", str(Q * T), float(Q * T), "q_lift/threshold", "q*T", "negative-sector q-lift companion"),
        GrammarTag("qD", str(Q * D), float(Q * D), "q_lift/imbalance", "q*D", "q-lifted imbalance"),
        GrammarTag("inverse_C", str(1 / C), float(1 / C), "inverse/base_carrier", "1/C", "inverse carrier"),
        GrammarTag("inverse_T", str(1 / T), float(1 / T), "inverse/base_threshold", "1/T", "inverse threshold"),
        GrammarTag("inverse_D", str(1 / D), float(1 / D), "inverse/imbalance", "1/D", "inverse imbalance"),
        GrammarTag("inverse_Phi4_over_Phi3", str(1 / (1 - D)), float(1 / (1 - D)), "inverse/complement", "1/(1-D)", "inverse Phi4 complement"),
        GrammarTag("inverse_qC", str(1 / (Q * C)), float(1 / (Q * C)), "inverse/q_lift_carrier", "1/(q*C)", "inverse QCD bare factor"),
    ]
    return {Fraction(e.value): e for e in entries}


@dataclass(frozen=True)
class TaggedObservable:
    label: str
    expression: str
    value: str
    decimal: float
    matched: bool
    tag_name: Optional[str]
    grammar_class: Optional[str]
    operation: Optional[str]
    interpretation: Optional[str]


def tag_value(label: str, value: Fraction, expression: str | None = None) -> TaggedObservable:
    dictionary = grammar_dictionary()
    match = dictionary.get(value)
    return TaggedObservable(
        label=label,
        expression=expression or str(value),
        value=str(value),
        decimal=float(value),
        matched=match is not None,
        tag_name=None if match is None else match.name,
        grammar_class=None if match is None else match.grammar_class,
        operation=None if match is None else match.operation,
        interpretation=None if match is None else match.interpretation,
    )


def canonical_observables() -> List[TaggedObservable]:
    """Constants already appearing in the recent W33 grammar pipeline."""
    raw = [
        ("carrier_weight", C, "8/13"),
        ("threshold_weight", T, "5/13"),
        ("electroweak_imbalance", D, "3/13 = q/Phi3"),
        ("phi4_complement", Fraction(PHI4, PHI3), "Phi4/Phi3 = 10/13"),
        ("heavy_plus_branch", Fraction(K + MU, PHI3), "(k+mu)/Phi3 = 16/13"),
        ("qcd_bare_k3", Fraction(24, PHI3), "24/Phi3 = q*C"),
        ("negative_companion", Fraction(15, PHI3), "15/Phi3 = q*T"),
        ("q_lifted_imbalance", Fraction(9, PHI3), "9/Phi3 = q*D"),
        ("inverse_electroweak_imbalance", Fraction(PHI3, Q), "Phi3/q = 13/3"),
        ("inverse_phi4_complement", Fraction(PHI3, PHI4), "Phi3/Phi4 = 13/10"),
        ("inverse_qcd_bare", Fraction(PHI3, 24), "Phi3/24 = 1/(q*C)"),
    ]
    return [tag_value(label, value, expr) for label, value, expr in raw]


def unmatched_probe_values() -> List[TaggedObservable]:
    """Nearby important W33 fractions that are not grammar tokens yet."""
    raw = [
        ("phi6_over_phi3", Fraction(PHI6, PHI3), "Phi6/Phi3 = 7/13"),
        ("hashimoto_norm_over_phi3", Fraction(K - 1, PHI3), "(k-1)/Phi3 = 11/13"),
        ("k_over_phi3", Fraction(K, PHI3), "k/Phi3 = 12/13"),
        ("phi3_over_phi6", Fraction(PHI3, PHI6), "Phi3/Phi6 = 13/7"),
    ]
    return [tag_value(label, value, expr) for label, value, expr in raw]


def grammar_tagger_audit() -> Dict[str, object]:
    dictionary = grammar_dictionary()
    canonical = canonical_observables()
    probes = unmatched_probe_values()

    checks = {
        "all_canonical_match": all(t.matched for t in canonical),
        "phi6_over_phi3_not_yet_basic_token": not probes[0].matched,
        "hashimoto_norm_over_phi3_not_yet_basic_token": not probes[1].matched,
        "dictionary_has_qcd_bare": Fraction(24, 13) in dictionary,
        "dictionary_has_electroweak_imbalance": Fraction(3, 13) in dictionary,
        "dictionary_has_phi4_complement": Fraction(10, 13) in dictionary,
        "dictionary_has_heavy_plus": Fraction(16, 13) in dictionary,
    }
    assert all(checks.values())

    return {
        "module": "PART_CXLVIII_GRAMMAR_TAGGER",
        "w33_atoms": {
            "q": Q,
            "k": K,
            "mu": MU,
            "Phi3": PHI3,
            "Phi4": PHI4,
            "Phi6": PHI6,
        },
        "grammar_dictionary": [asdict(v) for v in dictionary.values()],
        "canonical_observables": [asdict(t) for t in canonical],
        "unmatched_probe_values": [asdict(t) for t in probes],
        "checks": checks,
        "theorem_statement": (
            "The CXLVII observable grammar can be implemented as an exact rational "
            "tagger.  The known mixer constants 8/13, 5/13, 3/13, 10/13, 16/13, "
            "24/13, 15/13, and 9/13 are all classified by base, imbalance, "
            "complement, plus-branch, or q-lift operations.  Nearby fractions such "
            "as 7/13, 11/13, 12/13, and 13/7 are not automatically promoted without "
            "an additional grammar operation."
        ),
        "interpretive_note": (
            "This is an important discipline layer: the grammar is allowed to tag "
            "constants it generates exactly, while leaving other attractive W33 "
            "fractions unclassified until a new operation is justified."
        ),
    }


def main() -> int:
    audit = grammar_tagger_audit()
    out = ROOT / "PART_CXLVIII_grammar_tagger_results.json"
    out.write_text(json.dumps(audit, indent=2), encoding="utf-8")
    print(json.dumps(audit, indent=2))
    print(f"\nWrote {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
