"""
PART_CC: Braid Groups Bridge
=============================
Bridge the W(3,3) SRG(40,12,2,4) atoms to braid groups B_n,
Artin generators, the Burau representation, and knot invariants.

Key connections:
  - The braid group B_n on n strands is generated by elementary braids
    σ₁, …, σ_{n-1} subject to Artin relations.
  - B_Q = B_3 is the simplest non-trivial braid group.
  - The Burau representation of B_n is an (n×n) or ((n-1)×(n-1)) matrix
    representation over Z[t, t^{-1}].
  - The Jones polynomial of the unknot equals 1; it factors through the
    Temperley-Lieb algebra TL_n(δ) where δ = −t^{1/2} − t^{-1/2}.
  - The braid index of the torus knot T(p,q) = min(p,q).
  - Braid word length, Garside normal form, and permutation shadows
    are all countable.
  - W(3,3) atoms appear as strand counts, generator counts, and
    representation dimensions throughout.

Theorem CC:
    Let Γ = W(3,3) with atoms Q=3, LAM=2, V=40, K=12, PHI3=13, PHI4=10,
    PHI6=7, PHI12=73, J_INV=8, EDGES=240, EIG_MAX=5, MULT_K2=6.
    Then:
    (1) B_Q = B_3 is the first infinite non-abelian braid group:
        n = Q = 3 generators s1,s2 with the single braid relation s1 s2 s1 = s2 s1 s2.
    (2) The Artin generator count for B_{K} is K−1 = K−1 = LAM*EIG_MAX+1? 
        K−1 = 11. B_K = B_{12} has 11 = PHI6 + LAM + LAM generators.
    (3) The reduced Burau matrix for B_Q acts on a (Q−1)=LAM dimensional space.
    (4) The Temperley-Lieb algebra TL_n(δ) has dimension C_{n} (Catalan number):
        TL_Q has dim C_Q = C_3 = EIG_MAX = 5;  dim TL_{LAM} = C_2 = LAM.
    (5) The number of braid group generators for B_n = n−1.
        For B_{EIG_MAX}: generators = EIG_MAX−1 = LAM² = 4.
        For B_{J_INV}: generators = J_INV−1 = PHI6 = 7.
    (6) The braid index of the (Q, K) torus knot T(Q,K) = T(3,12) is Q = 3.
    (7) The Garside element Δ_n in B_n has a specific length:
        For B_Q: Δ_3 = σ₁σ₂σ₁ has word length Q = 3;
        half-twist length = Q(Q−1)/2 = Q*LAM/2*1 = 3 = PHI3-K+LAM = 3 ... actually Q(Q-1)/2=3. ✓
    (8) The dimension of the full Burau rep of B_n is n × n.
        For B_{K}: dim = K² = K·K = 144.
    (9) The Temperley-Lieb algebra TL_K has dimension C_K (the K-th Catalan number).
    (10) The number of simple braids (permutation braids) in B_n = n! (= number of
         permutations). For B_Q: Q! = MULT_K2·1 = 6 = MULT_K2. ✓ (3! = 6)
"""

from __future__ import annotations
import math
from dataclasses import dataclass
from typing import List, Dict, Any
import json
import os

# ---------------------------------------------------------------------------
# W(3,3) atoms
# ---------------------------------------------------------------------------
Q: int = 3
LAM: int = 2
V: int = 40
K: int = 12
PHI3: int = Q**2 + Q + 1        # 13
PHI4: int = Q**2 + 1            # 10
PHI6: int = Q**2 - Q + 1        # 7
PHI12: int = Q**4 - Q**2 + 1    # 73
J_INV: int = 2 * LAM**2         # 8
EDGES: int = V * K // 2         # 240
EIG_MAX: int = 5
MULT_K2: int = K // 2           # 6

# ---------------------------------------------------------------------------
# Braid group constants expressible via W(3,3) atoms
# ---------------------------------------------------------------------------

# B_Q = B_3: first infinite non-abelian braid group
BRAID_FIRST_NONABELIAN: int = Q         # 3 strands

# Generator count for B_n = n-1
def gen_count(n: int) -> int:
    return n - 1

GEN_COUNT_B3: int = gen_count(Q)       # 2 = LAM ✓
GEN_COUNT_B5: int = gen_count(EIG_MAX) # 4 = LAM²
GEN_COUNT_B8: int = gen_count(J_INV)   # 7 = PHI6
GEN_COUNT_B12: int = gen_count(K)      # 11 = PHI3 - LAM
GEN_COUNT_B13: int = gen_count(PHI3)   # 12 = K

# Reduced Burau representation dimension for B_n = n-1
BURAU_DIM_B3: int = Q - 1        # 2 = LAM
BURAU_DIM_B5: int = EIG_MAX - 1  # 4 = LAM²
BURAU_DIM_B8: int = J_INV - 1    # 7 = PHI6

# Full Burau representation dimension = n × n
BURAU_FULL_DIM_B3: int = Q**2    # 9
BURAU_FULL_DIM_B12: int = K**2   # 144

# Catalan number C_n (dimension of Temperley-Lieb algebra TL_n)
def catalan(n: int) -> int:
    return math.comb(2 * n, n) // (n + 1)

TL_DIM_2: int = catalan(LAM)       # C_2 = 2 = LAM
TL_DIM_3: int = catalan(Q)         # C_3 = 5 = EIG_MAX ✓
TL_DIM_4: int = catalan(LAM**2)    # C_4 = 14
TL_DIM_5: int = catalan(EIG_MAX)   # C_5 = 42

# TL_Q dimension = C_Q = C_3 = 5 = EIG_MAX ✓
TL_Q_DIM_IS_EIG_MAX: bool = (TL_DIM_3 == EIG_MAX)
# TL_LAM dimension = C_2 = 2 = LAM ✓
TL_LAM_DIM_IS_LAM: bool = (TL_DIM_2 == LAM)

# Garside element: Δ_n has word length n(n-1)/2
def garside_length(n: int) -> int:
    return n * (n - 1) // 2

GARSIDE_B3: int = garside_length(Q)       # 3·2/2 = 3 = Q ✓
GARSIDE_B5: int = garside_length(EIG_MAX) # 5·4/2 = 10 = PHI4 ✓
GARSIDE_B8: int = garside_length(J_INV)   # 8·7/2 = 28
GARSIDE_B12: int = garside_length(K)      # 12·11/2 = 66

# B_3 Garside length = Q ✓
GARSIDE_B3_IS_Q: bool = (GARSIDE_B3 == Q)
# B_5 Garside length = PHI4 = 10 ✓
GARSIDE_B5_IS_PHI4: bool = (GARSIDE_B5 == PHI4)

# Number of permutation braids = n!
PERM_BRAIDS_B3: int = math.factorial(Q)       # 6 = MULT_K2 ✓
PERM_BRAIDS_B5: int = math.factorial(EIG_MAX) # 120 = 5!

# B_3 permutation braids = Q! = 6 = MULT_K2 ✓
PERM_BRAIDS_B3_IS_MULT_K2: bool = (PERM_BRAIDS_B3 == MULT_K2)

# Braid index of torus knot T(p,q) = min(p,q)
def torus_braid_index(p: int, q: int) -> int:
    return min(p, q)

TORUS_T3_K: int = torus_braid_index(Q, K)        # min(3,12) = 3 = Q ✓
TORUS_T3_12_IS_Q: bool = (TORUS_T3_K == Q)
TORUS_T_LAM_PHI6: int = torus_braid_index(LAM, PHI6)  # min(2,7) = 2 = LAM ✓

# Artin relations count for B_n:
# Commutativity: |i-j|>=2 → C(n-1,2) - (n-2) pairs = (n-1)(n-2)/2 - (n-2) = (n-2)(n-3)/2
# Braid: n-2 relations (adjacent)
def artin_braid_relations(n: int) -> int:
    return n - 2   # adjacent braid relations σᵢσᵢ₊₁σᵢ = σᵢ₊₁σᵢσᵢ₊₁

def artin_comm_relations(n: int) -> int:
    n_gen = n - 1
    total_pairs = n_gen * (n_gen - 1) // 2
    return total_pairs - (n - 2)   # subtract adjacent pairs

BRAID_RELS_B3: int = artin_braid_relations(Q)    # 1
BRAID_RELS_B5: int = artin_braid_relations(EIG_MAX)  # 3
COMM_RELS_B3: int = artin_comm_relations(Q)      # 0 (B_3 has no commutative pairs)
COMM_RELS_B5: int = artin_comm_relations(EIG_MAX) # 3

# B_3 has exactly 1 braid relation and 0 commutative relations ✓
BRAID_RELS_B3_CORRECT: bool = (BRAID_RELS_B3 == 1 and COMM_RELS_B3 == 0)

# Center of B_n: generated by Δ_n². For B_3: Δ_3 = σ₁σ₂σ₁, Δ_3² has length 6 = MULT_K2 ✓
GARSIDE_B3_SQ_LENGTH: int = 2 * GARSIDE_B3     # 6 = MULT_K2
GARSIDE_B3_SQ_IS_MULT_K2: bool = (GARSIDE_B3_SQ_LENGTH == MULT_K2)

# Total generators count for B_n: n−1
# B_{EIG_MAX}: 4 = LAM²
GEN_COUNT_B5_IS_LAM_SQ: bool = (GEN_COUNT_B5 == LAM**2)
# B_{J_INV}: 7 = PHI6
GEN_COUNT_B8_IS_PHI6: bool = (GEN_COUNT_B8 == PHI6)
# B_{PHI3}: 12 = K
GEN_COUNT_B13_IS_K: bool = (GEN_COUNT_B13 == K)

# Temperley-Lieb parameter δ at root of unity q = exp(iπ/K)
# δ = -(q^{1/2} + q^{-1/2}) = -2·cos(π/K)
import cmath
TL_DELTA_AT_K: float = -2.0 * math.cos(math.pi / K)    # -2·cos(π/12) ≈ -1.932
TL_DELTA_POSITIVE: float = 2.0 * math.cos(math.pi / K)

# δ² - 1 relates to Jones polynomial normalizations
# At K=12: δ² = 4·cos²(π/12) ≈ 3.732
TL_DELTA_SQ: float = TL_DELTA_AT_K ** 2   # ≈ 3.732

# For completeness: Markov moves relate B_n traces to knot invariants
# The HOMFLY polynomial has variables a, z (ring Z[a±1, z±1])

# ---------------------------------------------------------------------------
# BraidCheck dataclass
# ---------------------------------------------------------------------------
@dataclass(frozen=True)
class BraidCheck:
    name: str
    description: str
    computed: Any
    expected: Any
    exact: bool = True

    @property
    def passes(self) -> bool:
        if self.exact:
            return self.computed == self.expected
        return abs(self.computed - self.expected) < 1e-10


# ---------------------------------------------------------------------------
# Check factories
# ---------------------------------------------------------------------------

def _make_atom_checks() -> List[BraidCheck]:
    return [
        BraidCheck("Q", "W(3,3) Q", Q, 3),
        BraidCheck("LAM", "W(3,3) LAM", LAM, 2),
        BraidCheck("K", "W(3,3) K", K, 12),
        BraidCheck("PHI3", "Q²+Q+1", PHI3, 13),
        BraidCheck("PHI4", "Q²+1", PHI4, 10),
        BraidCheck("PHI6", "Q²−Q+1", PHI6, 7),
        BraidCheck("J_INV", "2·LAM²", J_INV, 8),
        BraidCheck("EDGES", "V·K/2", EDGES, 240),
        BraidCheck("EIG_MAX", "max eigenvalue", EIG_MAX, 5),
    ]


def _make_generator_checks() -> List[BraidCheck]:
    return [
        BraidCheck("b3_first_nonabelian", "B_3 = first infinite non-abelian",
                   BRAID_FIRST_NONABELIAN, Q),
        BraidCheck("gen_b3", "gen(B_3) = Q−1 = LAM", GEN_COUNT_B3, LAM),
        BraidCheck("gen_b3_value", "gen(B_3) = 2", GEN_COUNT_B3, 2),
        BraidCheck("gen_b5", "gen(B_5) = LAM²", GEN_COUNT_B5, LAM**2),
        BraidCheck("gen_b5_value", "gen(B_5) = 4", GEN_COUNT_B5, 4),
        BraidCheck("gen_b8_phi6", "gen(B_8) = PHI6", GEN_COUNT_B8, PHI6),
        BraidCheck("gen_b8_value", "gen(B_8) = 7", GEN_COUNT_B8, 7),
        BraidCheck("gen_b13_k", "gen(B_{PHI3}) = K", GEN_COUNT_B13, K),
        BraidCheck("gen_b13_value", "gen(B_{PHI3}) = 12", GEN_COUNT_B13, 12),
    ]


def _make_burau_checks() -> List[BraidCheck]:
    return [
        BraidCheck("burau_dim_b3", "Reduced Burau dim B_3 = LAM",
                   BURAU_DIM_B3, LAM),
        BraidCheck("burau_dim_b3_value", "Reduced Burau dim B_3 = 2",
                   BURAU_DIM_B3, 2),
        BraidCheck("burau_dim_b5", "Reduced Burau dim B_5 = LAM²",
                   BURAU_DIM_B5, LAM**2),
        BraidCheck("burau_dim_b8", "Reduced Burau dim B_8 = PHI6",
                   BURAU_DIM_B8, PHI6),
        BraidCheck("burau_full_b3", "Full Burau dim B_3 = Q²",
                   BURAU_FULL_DIM_B3, Q**2),
        BraidCheck("burau_full_b3_value", "Full Burau dim B_3 = 9",
                   BURAU_FULL_DIM_B3, 9),
    ]


def _make_catalan_checks() -> List[BraidCheck]:
    return [
        BraidCheck("tl_dim_2", "TL_2 dim = C_2 = LAM", TL_DIM_2, LAM),
        BraidCheck("tl_dim_3", "TL_3 dim = C_3 = EIG_MAX", TL_DIM_3, EIG_MAX),
        BraidCheck("tl_dim_3_value", "TL_3 dim = 5", TL_DIM_3, 5),
        BraidCheck("tl_q_is_eig_max", "TL_Q dim = EIG_MAX", TL_Q_DIM_IS_EIG_MAX, True),
        BraidCheck("tl_lam_is_lam", "TL_LAM dim = LAM", TL_LAM_DIM_IS_LAM, True),
        BraidCheck("tl_dim_5", "TL_5 dim = C_5 = 42", TL_DIM_5, 42),
    ]


def _make_garside_checks() -> List[BraidCheck]:
    return [
        BraidCheck("garside_b3", "Garside Δ_3 length = Q", GARSIDE_B3, Q),
        BraidCheck("garside_b3_value", "Garside Δ_3 length = 3", GARSIDE_B3, 3),
        BraidCheck("garside_b5_phi4", "Garside Δ_5 length = PHI4",
                   GARSIDE_B5, PHI4),
        BraidCheck("garside_b5_value", "Garside Δ_5 length = 10", GARSIDE_B5, 10),
        BraidCheck("garside_b3_is_q", "Δ_3 length = Q", GARSIDE_B3_IS_Q, True),
        BraidCheck("garside_b5_is_phi4", "Δ_5 length = PHI4", GARSIDE_B5_IS_PHI4, True),
        BraidCheck("garside_b3_sq_mult_k2", "Δ_3² length = MULT_K2",
                   GARSIDE_B3_SQ_IS_MULT_K2, True),
        BraidCheck("garside_b3_sq_value", "Δ_3² length = 6", GARSIDE_B3_SQ_LENGTH, 6),
    ]


def _make_structural_checks() -> List[BraidCheck]:
    return [
        BraidCheck("perm_b3_mult_k2", "B_3 permutations = Q! = MULT_K2",
                   PERM_BRAIDS_B3, MULT_K2),
        BraidCheck("perm_b3_value", "B_3 permutations = 6", PERM_BRAIDS_B3, 6),
        BraidCheck("perm_b3_is_mult_k2", "Q! = MULT_K2", PERM_BRAIDS_B3_IS_MULT_K2, True),
        BraidCheck("torus_T3_12_index", "Braid index T(3,12) = Q",
                   TORUS_T3_K, Q),
        BraidCheck("torus_T3_12_value", "Braid index T(3,12) = 3", TORUS_T3_K, 3),
        BraidCheck("braid_rels_b3", "B_3 braid relations = 1", BRAID_RELS_B3, 1),
        BraidCheck("comm_rels_b3", "B_3 commutativity rels = 0", COMM_RELS_B3, 0),
        BraidCheck("braid_rels_correct", "B_3 relation counts correct",
                   BRAID_RELS_B3_CORRECT, True),
        BraidCheck("tl_delta_real", "TL δ at q=K is real",
                   isinstance(TL_DELTA_AT_K, float), True),
        BraidCheck("gen_b5_lam_sq_check", "gen(B_5) = LAM²", GEN_COUNT_B5_IS_LAM_SQ, True),
    ]


# ---------------------------------------------------------------------------
# Audit function
# ---------------------------------------------------------------------------

def braid_groups_bridge_audit() -> Dict[str, Any]:
    categories = {
        "atom_checks": _make_atom_checks(),
        "generator_checks": _make_generator_checks(),
        "burau_checks": _make_burau_checks(),
        "catalan_checks": _make_catalan_checks(),
        "garside_checks": _make_garside_checks(),
        "structural_checks": _make_structural_checks(),
    }

    all_checks = [c for checks in categories.values() for c in checks]
    failed = [c.name for c in all_checks if not c.passes]
    passing = len(all_checks) - len(failed)

    return {
        "status": "PASS" if not failed else "FAIL",
        "all_checks_pass": not bool(failed),
        "check_count": len(all_checks),
        "checks_passing": passing,
        "failed_checks": failed,
        "category_counts": {k: len(v) for k, v in categories.items()},
        "garside_lengths": {
            "B3": GARSIDE_B3,
            "B5": GARSIDE_B5,
            "B8": GARSIDE_B8,
            "B12": GARSIDE_B12,
        },
        "tl_dimensions": {
            "TL2": TL_DIM_2,
            "TL3": TL_DIM_3,
            "TL4": TL_DIM_4,
            "TL5": TL_DIM_5,
        },
        "w33_atoms": {
            "Q": Q, "LAM": LAM, "V": V, "K": K,
            "PHI3": PHI3, "PHI4": PHI4, "PHI6": PHI6,
            "J_INV": J_INV, "EDGES": EDGES, "EIG_MAX": EIG_MAX,
        },
        "theorem_cc": (
            "Every key parameter of braid groups B_n for n ∈ {Q, LAM², PHI3, PHI4, "
            "PHI6, J_INV, K, EIG_MAX} — generator count, Garside element length, "
            "Temperley-Lieb dimension, reduced Burau dimension, and permutation count — "
            "is an integer expression in the W(3,3) atoms with zero free parameters: "
            "gen(B_5)=LAM², Δ_3 length=Q, Δ_5 length=PHI4, TL_3 dim=EIG_MAX, "
            "TL_2 dim=LAM, Q!=MULT_K2, gen(B_8)=PHI6, gen(B_{13})=K."
        ),
    }


def main() -> None:
    result = braid_groups_bridge_audit()
    out_path = os.path.join(os.path.dirname(__file__),
                            "PART_CC_braid_groups_results.json")
    with open(out_path, "w") as fh:
        json.dump(result, fh, indent=2)

    n = result["check_count"]
    p = result["checks_passing"]
    status = result["status"]
    print(f"PART_CC Braid Groups Bridge: {status} ({p}/{n} checks pass)")
    if result["failed_checks"]:
        print(f"  FAILED: {result['failed_checks']}")


if __name__ == "__main__":
    main()
