#!/usr/bin/env python3
"""
PART CLVII - Spectral Action Ladder Compiler
===========================================

The older CLIV-CLV commit added Seeley-DeWitt and Atiyah-Singer data:

    a0 = kV = 480
    a2 = 2240
    a4 = 17600
    a2/a0 = 14/3
    a4/a2 = 55/7
    lambda_H = 7/55
    eta(0) = (V-k)/2 = 14
    ind(D) = q = 3

This module integrates those results with the newer CL-CLIII two-layer algebra.
The spectral action ratios are not separate numerology. They are generated by
an index/radial ladder:

    a2/a0 = eta(0) / ind(D) = 14/3.

and

    a4/a2 = C(k-1,2) / Phi6 = 55/7.

Therefore

    lambda_H = (a4/a2)^(-1) = Phi6 / C(k-1,2) = 7/55.

Interpretation:
    - the a2/a0 jump is the index-asymmetry step;
    - the a4/a2 jump is the Hashimoto radial-wedge / threshold-field step;
    - the Higgs quartic is the inverse radial-threshold step.

This welds CLIV-CLV into the current grammar instead of treating them as a
parallel spectral-action layer.
"""

from __future__ import annotations

import json
import math
from dataclasses import asdict, dataclass
from fractions import Fraction
from pathlib import Path
from typing import Dict, List

ROOT = Path(__file__).resolve().parent

Q = 3
V = 40
K = 12
LAM = 2
MU = 4
PHI3 = Q * Q + Q + 1
PHI4 = Q * Q + 1
PHI6 = Q * Q - Q + 1
HASHIMOTO_NORM = K - 1

A0 = K * V
A2 = MU * (K + MU) * (Q * Q - 4) * (LAM + MU + 1)
A4 = (K + V // 2) * PHI4 * math.comb(K - 1, 2)
ETA0 = (V - K) // 2
INDEX = Q
RADIAL_WEDGE = math.comb(HASHIMOTO_NORM, 2)


@dataclass(frozen=True)
class SpectralActionStep:
    name: str
    ratio: str
    formula: str
    layer_interpretation: str


def spectral_steps() -> List[SpectralActionStep]:
    return [
        SpectralActionStep(
            name="index_asymmetry_step",
            ratio=str(Fraction(A2, A0)),
            formula="a2/a0 = eta(0)/ind(D) = 14/3",
            layer_interpretation="Atiyah-Singer/index normalization step",
        ),
        SpectralActionStep(
            name="radial_threshold_step",
            ratio=str(Fraction(A4, A2)),
            formula="a4/a2 = C(k-1,2)/Phi6 = 55/7",
            layer_interpretation="Hashimoto radial-wedge over Phi6 threshold field",
        ),
        SpectralActionStep(
            name="higgs_quartic_inverse_step",
            ratio=str(Fraction(PHI6, RADIAL_WEDGE)),
            formula="lambda_H = Phi6/C(k-1,2) = 7/55",
            layer_interpretation="inverse radial-threshold spectral-action coupling",
        ),
    ]


def spectral_action_ladder_audit() -> Dict[str, object]:
    r20 = Fraction(A2, A0)
    r42 = Fraction(A4, A2)
    lam_h = Fraction(PHI6, RADIAL_WEDGE)
    eta_over_index = Fraction(ETA0, INDEX)
    wedge_over_phi6 = Fraction(RADIAL_WEDGE, PHI6)

    checks = {
        "a0_equals_kV": A0 == K * V == 480,
        "a2_matches_CLIV": A2 == 2240,
        "a4_matches_CLIV": A4 == 17600,
        "eta0_equals_V_minus_k_over_2": ETA0 == (V - K) // 2 == 14,
        "index_equals_q": INDEX == Q == 3,
        "a2_over_a0_is_eta_over_index": r20 == eta_over_index == Fraction(14, 3),
        "radial_wedge_is_C_11_2": RADIAL_WEDGE == 55,
        "a4_over_a2_is_wedge_over_phi6": r42 == wedge_over_phi6 == Fraction(55, 7),
        "higgs_quartic_is_inverse_radial_threshold": lam_h == Fraction(7, 55),
        "lambda_H_inverse_is_a4_over_a2": 1 / lam_h == r42,
        "eta0_is_phi3_plus_unit": ETA0 == PHI3 + 1,
        "phi6_is_threshold_field": PHI6 == 7,
    }
    assert all(checks.values())

    return {
        "module": "PART_CLVII_SPECTRAL_ACTION_LADDER_COMPILER",
        "source_hint": "integrates older CLIV Seeley-DeWitt and CLV Atiyah-Singer commit d3078164",
        "w33_atoms": {
            "q": Q,
            "v": V,
            "k": K,
            "lambda": LAM,
            "mu": MU,
            "Phi3": PHI3,
            "Phi4": PHI4,
            "Phi6": PHI6,
            "Hashimoto_norm": HASHIMOTO_NORM,
        },
        "seeley_dewitt_coefficients": {
            "a0": A0,
            "a2": A2,
            "a4": A4,
            "a2_over_a0": str(r20),
            "a4_over_a2": str(r42),
            "a4_over_a0": str(Fraction(A4, A0)),
        },
        "index_data": {
            "eta0": ETA0,
            "index": INDEX,
            "eta0_over_index": str(eta_over_index),
        },
        "radial_threshold_data": {
            "radial_wedge_C_kminus1_2": RADIAL_WEDGE,
            "Phi6_threshold_field": PHI6,
            "wedge_over_Phi6": str(wedge_over_phi6),
            "lambda_H": str(lam_h),
            "lambda_H_decimal": float(lam_h),
        },
        "steps": [asdict(s) for s in spectral_steps()],
        "checks": checks,
        "theorem_statement": (
            "The CLIV Seeley-DeWitt ratios are generated by the same W(3,3) grammar: "
            "a2/a0 is the index-asymmetry step eta(0)/ind(D)=14/3, while a4/a2 is "
            "the Hashimoto radial-wedge over threshold-field step C(k-1,2)/Phi6=55/7. "
            "The Higgs quartic is the inverse radial-threshold step lambda_H=7/55."
        ),
        "interpretive_note": (
            "This connects the older spectral-action commit to the newer mixer/projection "
            "spine. Heat-kernel coefficients are not a third unrelated pile: they form a "
            "ladder whose first step is index normalization and whose second step is the "
            "Phi6 threshold field against the Hashimoto radial wedge."
        ),
    }


def main() -> int:
    audit = spectral_action_ladder_audit()
    out = ROOT / "PART_CLVII_spectral_action_ladder_results.json"
    out.write_text(json.dumps(audit, indent=2), encoding="utf-8")
    print(json.dumps(audit, indent=2))
    print(f"\nWrote {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
