#!/usr/bin/env python3
"""Executable closure assertions for the four new W33 sides of the five-front pass.

The fifth side -- the 45-target concrete ROM isomorphism -- lives in Holotrade
because the exhaustive PSp anomaly catalogue lives there.  Its own commit/test
certificate remains authoritative.  This test checks that the W33-side modules
all execute successfully and that their ABIs actually meet rather than merely
coexisting as isolated certificates.
"""
from __future__ import annotations

from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "analysis"))

import w33_capability_address_isa as capisa  # noqa: E402
import w33_qutrit_clifford_phase_displacement_lift as phase  # noqa: E402
import w33_reversible_storage_economics as storage  # noqa: E402
import w33_structured_counter_bytecode_compiler as bytecode  # noqa: E402
from w33_universal_control_packet import validate_packet  # noqa: E402


def main() -> int:
    results = {
        "capability_address_isa": capisa.verify(),
        "qutrit_phase_displacement_lift": phase.verify(),
        "structured_counter_bytecode": bytecode.verify(),
        "reversible_storage_economics": storage.verify(),
    }
    assert all(r["status"] == "PASS" for r in results.values()), results

    # ABI join 1: the universal bytecode path really emits the packet type that
    # independently verifies against the finite control packet checker.
    source = """
    module one-step
    start entry
    block entry halt
    """
    executed = bytecode.execute_and_packetize(bytecode.parse(source), (0, 0))
    assert len(executed["packets"]) == 1
    packet = executed["packets"][0]
    assert validate_packet(packet)["ok"]

    # ABI join 2: its packet binds the exact phase-frame digest generated by the
    # new Clifford lift for that same micro-word.
    op = packet.microcode[0]
    expected_phase = phase.CliffordPhaseFrame(((op.axis, op.lam),)).phase_frame_digest
    assert packet.clifford_phase_frame_digest == expected_phase

    # ABI join 3: storage optimization is a reversible policy surface, never a
    # loophole that silently converts logical discard into a Joule claim.
    s = results["reversible_storage_economics"]
    assert s["destructive_control"]["included_in_reversible_pareto_frontier"] is False
    assert s["destructive_control"]["thermodynamic_energy_claim_joules"] is None

    # ABI join 4: evidence tiers on capability pointers are ordered strongly
    # enough to distinguish software proof from calibrated/attested execution.
    assert capisa.EvidenceTier.MODEL < capisa.EvidenceTier.VERIFIED_SOFTWARE
    assert capisa.EvidenceTier.VERIFIED_SOFTWARE < capisa.EvidenceTier.CALIBRATED_DEVICE
    assert capisa.EvidenceTier.CALIBRATED_DEVICE < capisa.EvidenceTier.ATTESTED_DEVICE

    print("W33 UNIVERSAL VM FIVE-FRONT CLOSURE: PASS")
    for name, result in results.items():
        print(f"  {name}: {result['status']}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
