from pathlib import Path
import json,pytest
import sympy as sp
ROOT=Path(__file__).resolve().parents[1];DATA=ROOT/'data'
def load(name):return json.loads((DATA/name).read_text(encoding="utf-8"))
def test_brauer_when_materialized():
 p=DATA/'w33_pass1350_u42d2_char5_blocks.json'
 if not p.exists():pytest.skip('generated by CTblLib job')
 b=[x for x in json.loads(p.read_text(encoding="utf-8"))['blocks'] if x['defect']==1];assert len(b)==2
 for x in b:assert x['ordinary_degrees']==[1,6,24,64,81] and x['brauer_degrees']==[1,6,23,58] and x['brauer_tree']==[[1,3],[2,4],[3,5],[4,5]]
def test_pass1345_basic_and_pass1351_layers_agree():
 canonical=load('w33_pass1345_modular_basic_algebras.json');ext=load('w33_pass1351_projective_layers.json')
 for p in ('2','3','5'):
  r=canonical['records'][p];e=ext['records'][p];D=sp.Matrix(r['decomposition_matrix']);C=sp.Matrix(r['cartan_matrix']);assert D.T*D==C
  assert e['vertices']==r['quiver_and_associated_graded_relations']['vertices'];assert e['projective_basic_dimensions']==[sum(row) for row in C.tolist()]
  for dim,layers in zip(e['projective_basic_dimensions'],e['radical_layers']):assert sum(sum(x) for x in layers)==dim
  for dim,layers in zip(e['projective_basic_dimensions'],e['socle_layers']):assert sum(sum(x) for x in layers)==dim
def test_literal_projective_resolutions_when_materialized():
 p=DATA/'w33_pass1351_projective_resolutions.json'
 if not p.exists():pytest.skip('generated by literal basic-algebra job')
 d=json.loads(p.read_text(encoding="utf-8"));assert d['status']=='PASS' and all(d['checks'].values())
 old=load('w33_pass1351_projective_layers.json')['records']
 for prime in ('2','3','5'):
  r=d['records'][prime];assert r['requested_resolution_depth']==10 and r['max_cover_dimension']==768
  assert r['radical_layers']==old[prime]['radical_layers'];assert r['socle_layers']==old[prime]['socle_layers']
  assert len(r['minimal_projective_resolution_prefixes'])==len(r['vertices'])
  assert r['computed_resolution_depths']==[len(x)-1 for x in r['minimal_projective_resolution_prefixes']]
  for resolution in r['minimal_projective_resolution_prefixes']:
   assert resolution[0]['syzygy']==0 and resolution[0]['module_dimension']==1
   assert all(step['syzygy']==i for i,step in enumerate(resolution))
   for step in resolution:
    if 'kernel_not_materialized' in step:assert step['cover_dimension']>step['dimension_ceiling']
def test_characteristic_five_hecke_corner_firewall():
 q=load('w33_pass1345_modular_basic_algebras.json')['records']['5']['quiver_and_associated_graded_relations']
 assert {(a['source'],a['target']) for a in q['arrows']}=={('F_5','F_4'),('F_6','F_4'),('F_4','F_5'),('F_4','F_6')}
 assert len(q['minimal_relations']['2'])==4
def test_selector_when_materialized():
 p=DATA/'w33_pass1353_selector_geometry.json'
 if not p.exists():pytest.skip('generated by geometry job')
 d=json.loads(p.read_text(encoding="utf-8"));assert d['selector_count']==40*3==120;assert d['line_stabilizer_order']==54*24==1296;assert d['cycle_stabilizer_order']==54*8==432
def test_atlas_when_materialized():
 p=DATA/'w33_pass1352_atlas_carrier_conjugacy.json'
 if not p.exists():pytest.skip('generated by Repsn job')
 d=json.loads(p.read_text(encoding="utf-8"));assert d['status']=='PASS' and d['hom_space_dimension']==1 and all(d['checks'].values())
def test_pdf_manifest_when_materialized():
 p=DATA/'w33_pass1354_pdf_manifest.json'
 if not p.exists():pytest.skip('generated after full builds')
 d=json.loads(p.read_text(encoding="utf-8"));assert d['status']=='PASS_WITH_TYPED_BUILD_ONLY_STUBS';assert {'w33_paper.pdf','photonic_holonet.pdf'}<=set(d['files']);assert d['build_observation']['status']=='PASS'
