from pathlib import Path
import hashlib,json
import sympy as sp
import pytest

ROOT=Path(__file__).resolve().parents[1]; DATA=ROOT/'data'

def load(name): return json.loads((DATA/name).read_text())
def jsha(obj): return hashlib.sha256(json.dumps(obj,sort_keys=True,separators=(',',':')).encode()).hexdigest()

def test_ambient_brauer_tree_is_two_defect_one_paths():
    d=load('w33_pass1350_u42d2_char5_blocks.json'); b=[x for x in d['blocks'] if x['defect']==1]
    assert len(b)==2
    for x in b:
        assert x['ordinary_degrees']==[1,6,24,64,81]
        assert x['brauer_degrees']==[1,6,23,58]
        assert x['brauer_tree']==[[1,3],[2,4],[3,5],[4,5]]

def test_basic_algebra_certificates():
    for p in (2,3,5):
        r=load(f'w33_pass1351_basic_algebra_p{p}.json')['record']
        D=sp.Matrix(r['decomposition_matrix']); C=sp.Matrix(r['cartan_matrix'])
        assert D.T*D==C
        assert r['basic_algebra_dimension']==sum(sum(row) for row in r['cartan_matrix'])
        q=r['quiver_and_associated_graded_relations']
        assert jsha(q['minimal_relations'])==r['minimal_relation_sha256']

def test_characteristic_five_hecke_quiver_is_separate_corner():
    q=load('w33_pass1351_basic_algebra_p5.json')['record']['quiver_and_associated_graded_relations']
    assert {(a['source'],a['target']) for a in q['arrows']}=={('F_5','F_4'),('F_6','F_4'),('F_4','F_5'),('F_4','F_6')}
    assert len(q['minimal_relations']['2'])==4

def test_selector_geometry():
    d=load('w33_pass1353_selector_geometry.json')
    assert d['selector_count']==40*3==120
    assert d['line_stabilizer_order']==54*24==1296
    assert d['cycle_stabilizer_order']==54*8==432
    assert d['cycle_orbit_size']*d['cycle_stabilizer_order']==51840

def test_atlas_conjugacy_when_materialized():
    path=DATA/'w33_pass1352_atlas_carrier_conjugacy.json'
    if not path.exists(): pytest.skip('generated by genuine GAP/Repsn release job')
    d=json.loads(path.read_text())
    assert d['status']=='PASS' and d['hom_space_dimension']==1 and all(d['checks'].values())

def test_pdf_manifest_when_materialized():
    path=DATA/'w33_pass1354_pdf_manifest.json'
    if not path.exists(): pytest.skip('generated after both complete manuscript builds')
    d=json.loads(path.read_text()); assert d['status']=='PASS'
    assert {'w33_paper.pdf','photonic_holonet.pdf'} <= set(d['files'])

def test_combined_release_when_materialized():
    path=DATA/'w33_pass1350_1354_exact_release.json'
    if not path.exists(): pytest.skip('generated by exact release job')
    d=json.loads(path.read_text()); assert d['status']=='PASS' and all(d['checks'].values())
