"""Focused regressions for the GAP-owned Passes 358--361."""

from __future__ import annotations

import importlib.util
import json
import shutil
import subprocess
from pathlib import Path

import pytest


ROOT = Path(__file__).resolve().parents[1]
GAP = shutil.which("gap")


def _run_gap(relative: str, marker: str) -> dict:
    assert GAP is not None
    result = subprocess.run(
        [GAP, "-q", str(ROOT / relative)],
        cwd=ROOT,
        check=True,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        timeout=120,
    )
    assert marker in result.stdout
    certificate = ROOT / "data" / Path(relative).with_suffix(".json").name
    # Witness and certificate basenames intentionally differ only by the
    # analysis/data directories in these two passes.
    return json.loads(certificate.read_text(encoding="utf-8"))


@pytest.mark.skipif(GAP is None, reason="GAP is required for Pass 358")
def test_pass358_exactly_repairs_the_remote_group_weil_and_transfer_claims() -> None:
    cert = _run_gap(
        "analysis/w33_pass358_github_batch_integrity_audit.g",
        "Pass358 status=PASS",
    )
    assert cert["status"] == "PASS"
    assert cert["check_count"] == 33 == len(cert["checks"])
    assert all(cert["checks"].values())
    assert cert["weil_9"]["split"] == "5+4"
    assert cert["weil_9"]["outer_real_envelope"].startswith("18=10+8")
    assert cert["transfer_p5"] == {
        "polynomial": "x^2-90x+325",
        "roots": "45+-10sqrt(17)",
        "discriminant": 6800,
    }
    assert cert["q7_order"] == {
        "prime": 3089,
        "ord_2": 772,
        "near_maximal_target": 1544,
        "passes_target": False,
    }


@pytest.mark.skipif(GAP is None, reason="GAP is required for Pass 359")
def test_pass359_constructs_the_exact_qr_css_code() -> None:
    cert = _run_gap(
        "analysis/w33_pass359_alpha_code_qr_css.g",
        "Pass359 status=PASS",
    )
    assert cert["status"] == "PASS"
    assert cert["check_count"] == 26 == len(cert["checks"])
    assert all(cert["checks"].values())
    assert cert["classical_codes"] == {
        "quadratic_residue": "[137,69,21]",
        "quadratic_nonresidue": "[137,69,21]",
        "extended": "[138,69,22]",
    }
    assert cert["quantum_code"] == "[[137,1,21]]"
    assert cert["gap_construction"]["css_product_rank"] == 0
    assert cert["gap_construction"]["logical_qubits"] == 1
    assert cert["low_weight_search"] == {
        "weight3_hits": 0,
        "weight4_pair_collisions": 0,
        "weight5_witness": False,
    }


@pytest.mark.skipif(GAP is None, reason="GAP is required for Pass 360")
def test_pass360_builds_the_affine_logical_hadamard_and_psl_action() -> None:
    cert = _run_gap(
        "analysis/w33_pass360_alpha_code_logical_hadamard.g",
        "Pass360 status=PASS",
    )
    assert cert["status"] == "PASS"
    assert cert["check_count"] == 37 == len(cert["checks"])
    assert all(cert["checks"].values())
    assert cert["affine_symmetry"] == {
        "full": "C137:C136",
        "order": 18632,
        "pure_permutation": "C137:C68",
        "pure_order": 9316,
    }
    assert cert["extended_code_symmetry"] == {
        "group": "PSL(2,137)",
        "degree": 138,
        "order": 1285608,
        "point_stabilizer_order": 9316,
    }
    assert cert["extended_pair_envelope"] == {
        "group": "PGL(2,137)",
        "order": 2571216,
        "role": "its nontrivial PSL coset swaps the two extended QR codes",
    }
    assert "transversal H" in cert["logical_gate"]
    assert cert["checks"]["nonresidue_multiplier_sends_qr_checks_to_nqr"]
    assert cert["checks"]["nonresidue_multiplier_sends_nqr_checks_to_qr"]
    assert cert["checks"]["logical_ones_pair_anticommutes"]


@pytest.mark.skipif(GAP is None, reason="GAP is required for Pass 361")
def test_pass361_proves_the_simple_clifford_maximality_boundary() -> None:
    cert = _run_gap(
        "analysis/w33_pass361_alpha_code_clifford_maximality.g",
        "Pass361 status=PASS",
    )
    assert cert["status"] == "PASS"
    assert cert["check_count"] == 23 == len(cert["checks"])
    assert all(cert["checks"].values())
    assert cert["orthogonal_decomposition"].endswith("dimensions 68+68+1")
    assert cert["uniform_clifford_quotient"] == {
        "all_label_maps": 6,
        "admissible": 2,
        "maps": ["identity", "X/Z swap"],
        "logical_image": "C2 generated by H",
    }
    assert cert["phase_mask_no_go"] == {
        "constraints_each_direction": 4692,
        "rank_each_direction": 137,
        "nullity_each_direction": 0,
    }
    assert "general nonuniform Clifford circuits" in cert["boundary"]


def test_results_index_integer_parser_normalizes_grouped_digits() -> None:
    spec = importlib.util.spec_from_file_location(
        "build_results_index", ROOT / "analysis" / "build_results_index.py"
    )
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    text = (
        "wrong determinant 35,697,025; canonical token 35697025; "
        "TeX group order 1{,}285{,}608"
    )
    assert {
        module.canonical_integer(match) for match in module.RE_INT.findall(text)
    } == {"35697025", "1285608"}
    assert module.PINNED_RESULTS == {"[[40,10,4]]", "[40,15,8]"}


def test_pass358_360_are_published_without_the_physical_overread() -> None:
    readme = (ROOT / "README.md").read_text(encoding="utf-8")
    paper = (ROOT / "w33_paper.tex").read_text(encoding="utf-8")
    website = (ROOT / "docs" / "index.html").read_text(encoding="utf-8")
    synthesis = (
        ROOT / "PASS358_359_GITHUB_BATCH_INTEGRITY_ALPHA_CODE_SYNTHESIS.md"
    ).read_text(encoding="utf-8")
    gate_synthesis = (
        ROOT / "PASS360_ALPHA_CODE_AFFINE_CLIFFORD_PSL_SYNTHESIS.md"
    ).read_text(encoding="utf-8")
    boundary_synthesis = (
        ROOT / "PASS361_ALPHA_CODE_CLIFFORD_MAXIMALITY_SYNTHESIS.md"
    ).read_text(encoding="utf-8")
    index = (ROOT / "RESULTS_INDEX.md").read_text(encoding="utf-8")

    assert "[[137,1,21]]" in readme
    assert "18=10+8" in readme
    assert "[[137,1,21]]" in paper
    assert "18=10+8" in paper
    assert "[[137,1,21]]" in website
    assert "18=10+8" in website
    assert "logical Hadamard" in readme
    assert "PGL(2,137)" in readme
    assert "logical Hadamard" in paper
    assert "PGL(2,137)" in paper
    assert "logical Hadamard" in website
    assert "PGL(2,137)" in website
    assert "4,692" in readme
    assert "4{,}692" in paper
    assert "4,692" in website
    assert "does **not** identify the code rate with the physical" in synthesis
    assert "fine-structure constant" in synthesis
    assert "37-check" in gate_synthesis
    assert "does not derive a physical coupling" in gate_synthesis
    assert "68+68+1" in boundary_synthesis
    assert "general nonuniform Clifford circuits" in boundary_synthesis
    assert "| `35697025` |" in index
    assert "| `9316` |" in index
    assert "| `18632` |" in index
    assert "| `1285608` |" in index
    assert "| `2571216` |" in index
    assert "| `4692` |" in index
    assert "| `[[40,10,4]]` |" in index
    assert "| `[40,15,8]` |" in index
    assert "analysis/2026-07-15_pass92_wrq_landscape.md" in index
