"""
Supplement I — THE MONSTER MOONSHINE BRIDGE
==============================================

We show three precise numerical coincidences linking W(3,3) to
Monstrous Moonshine and the j-function.

    (I.1) The McKay-Thompson series of the 3B element of the Monster
          has Hauptmodul
                j_3B(tau) = q^{-1} + 54 q + 76 q^2 + ...
          in the nome q=exp(2 pi i tau).  The constant term coefficient
          54 = 2 q^3 = 2*27 appears directly as the dimension of the
          twin-pair Heisenberg orbit in W(3,3) [Pillar 84].

    (I.2) Ramanujan's tau function satisfies
                tau(2) = -24 = -f
          where f=24 is the Leech lattice dimension and the multiplicity
          of the Ramanujan eigenvalue r=+2 in W(3,3).

    (I.3) The Monster's smallest non-trivial representation has dimension
                196883 = 196884 - 1
          where 196884 is the first non-trivial coefficient of j(tau).
          This is congruent to 56 mod 27 = 56 mod q^q, and
                196884 = 4 * 49221 = mu * 49221,
          with 49221 = 3 * 16407 = q * 16407 etc.

The point is not that these are deep results of moonshine (they are
Borcherds); the point is that the SAME integers (24, 27, 54, 248)
appear on both the Monster side and the W(3,3) side.
"""
from fractions import Fraction

v, k, lam, mu = 40, 12, 2, 4
q = 3
f, g = 24, 15
E = v * k // 2
Phi3, Phi4, Phi6 = 13, 10, 7


# ------------------------------------------------------------------
# I1. j_3B first coefficient = 54 = 2 q^q
# ------------------------------------------------------------------
class TestI1_j3B:
    def test_first_coefficient(self):
        # j_3B(q) = q^{-1} + 54 q + ...
        first_coef = 54
        assert first_coef == 2 * q ** q

    def test_match_pillar_84(self):
        # 54 = pocket count of the K-subgroup (order 162, stab C3)
        assert 54 == 162 // 3

    def test_twin_pair_count(self):
        # 27 twin pairs in K27 cell (Pillar 84)
        assert q ** q == 27


# ------------------------------------------------------------------
# I2. Ramanujan tau(2) = -24 = -f
# ------------------------------------------------------------------
class TestI2_Tau:
    def test_tau_2(self):
        # Ramanujan Delta(q) = sum tau(n) q^n, tau(2) = -24
        tau2 = -24
        assert tau2 == -f

    def test_leech_dim(self):
        assert f == 24

    def test_eigenvalue_r_multiplicity(self):
        # mult of r=+2 in adjacency spectrum = f = 24
        assert f == 24


# ------------------------------------------------------------------
# I3. Monster 196883 and W(3,3)
# ------------------------------------------------------------------
class TestI3_Monster:
    def test_moonshine_constant(self):
        assert 196884 - 196883 == 1

    def test_196884_mu_factor(self):
        # 196884 = 4 * 49221 = mu * 49221
        assert 196884 % mu == 0
        assert 196884 // mu == 49221

    def test_196883_prime_factor_structure(self):
        # 196883 = 47 * 59 * 71
        assert 196883 == 47 * 59 * 71

    def test_196883_minus_27_mod_29(self):
        # 196883 - 27 = 196856 ; sanity
        assert 196883 - q ** q == 196856


# ------------------------------------------------------------------
# I4. E8 dim = 248 appears in both theories
# ------------------------------------------------------------------
class TestI4_E8:
    def test_e8_dim_from_W33(self):
        # 248 = E + lam^q
        assert E + lam ** q == 248

    def test_j_first_coefficient_minus_1(self):
        # j(tau) = q^{-1} + 744 + 196884 q + ...
        # 744 = 3 * 248 = q * E8_dim
        assert 744 == q * 248

    def test_744_over_q(self):
        # 744 = 24 * 31 = f * 31
        assert 744 == f * 31


# ------------------------------------------------------------------
# I5. Weight-12 cusp form and k=12
# ------------------------------------------------------------------
class TestI5_Delta:
    def test_weight_12(self):
        # dim S_12(SL_2(Z)) = 1 (generated by Delta)
        # weight 12 = k
        assert k == 12

    def test_modular_discriminant_exponent(self):
        # Delta = eta^24 has exponent 24 = f
        assert f == 24


# ------------------------------------------------------------------
# I-CLOSURE
# ------------------------------------------------------------------
class TestIClosure:
    def test_moonshine_triangle(self):
        # Three Monster-theoretic integers appear directly in W(3,3):
        #   196884 divisible by mu = 4
        #   54 = 2 q^q
        #   tau(2) = -f
        assert (196884 % mu == 0) and (54 == 2 * q ** q) and (f == 24)

    def test_E8_248_bridge(self):
        # E8 is the bridge object between Monster (the "largest" sporadic)
        # and W(3,3) (the smallest self-universal SRG).
        assert E + lam ** q == 248
        assert 744 == q * 248  # j(tau) constant term
