"""Focused parser tests for the GAP-owned Pass 218 certificate."""

from __future__ import annotations

import json
import shutil
import subprocess
from functools import lru_cache
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SCRIPT = ROOT / "analysis" / "w33_pass218_weil_shadow_split.g"
CERTIFICATE = ROOT / "data" / "w33_pass218_weil_shadow_split.json"


@lru_cache(maxsize=1)
def _certificate() -> dict:
    """Run GAP once; Python only parses the GAP-produced certificate."""

    gap = shutil.which("gap")
    assert gap is not None, "GAP is required for the Pass 218 certificate"
    result = subprocess.run(
        [gap, "-q", str(SCRIPT)],
        cwd=ROOT,
        check=True,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        timeout=240,
    )
    assert "Pass 218 GAP Weil-shadow split: PASS (16/16 checks)" in result.stdout
    return json.loads(CERTIFICATE.read_text(encoding="utf-8"))


def test_q5_is_the_f4_galois_fusion_not_a_golay_module() -> None:
    cert = _certificate()
    q5 = cert["q5"]
    assert cert["status"] == "PASS"
    assert cert["owner"] == "GAP 4.12 MTX + CTblLib + AtlasRep"
    assert q5["image_order"] == 4_680_000
    assert q5["F2_shadow"] == (
        "irreducible dimension 24, not absolutely irreducible"
    )
    assert q5["endomorphism_ring"] == "F4, generated by J with J^2+J+1=0"
    assert q5["endomorphism_dimension_over_F2"] == 2
    assert q5["F4_submodule_dimensions"] == [0, 12, 12, 24]
    assert q5["CTblLib_2Brauer_positions"] == [2, 3]
    assert q5["AtlasRep_anchor"] == "S45G1-f4r12aB0"
    assert "Res_F4/F2(12a)" in q5["identification"]
    assert q5["old_Golay_Leech_identification"] is False


def test_q7_is_the_split_hyperbolic_dual_pair() -> None:
    q7 = _certificate()["q7"]
    assert q7["image_order"] == 138_297_600
    assert q7["composition_factors"] == [24, 24]
    assert q7["extension_verdict"] == "SPLIT: H7 = U direct-sum U*"
    assert q7["complete_submodule_dimensions"] == [0, 24, 24, 48]
    assert q7["socle_dimension"] == 48
    assert q7["radical_dimension"] == 0
    assert q7["split_projector_rank"] == 24
    assert "nonisomorphic absolutely irreducible" in q7["factor_fingerprint"]
    assert "rank-48 quadratic space with Arf invariant 0" in q7["polar_geometry"]
    assert "complementary totally singular 24-spaces" in q7["polar_geometry"]


def test_weil_fingerprints_and_database_boundary_are_explicit() -> None:
    cert = _certificate()
    assert cert["q5"]["transvection_character_values"] == (
        "(-1 plus-or-minus 5*sqrt(5))/2"
    )
    assert cert["q7"]["transvection_character_values"] == (
        "(-1 plus-or-minus 7*sqrt(-7))/2"
    )
    assert cert["field_of_definition_transition"] == {
        "q5": (
            "the Weil pair is Frobenius-conjugate over F4 and fuses to one "
            "irreducible F2 module of dimension 24"
        ),
        "q7": (
            "the Weil pair is individually defined over F2 and appears as "
            "the split dual sum 24+24"
        ),
    }
    assert cert["literature"]["reference"] == (
        "https://arxiv.org/abs/math/0212378"
    )
    assert "no local 2-Brauer table" in cert["literature"]["honest_boundary"]
    assert len(cert["checks"]) == 16
    assert all(cert["checks"].values())
