"""Regression for Passes 11655-11659 (Claude track): shear-twisted reversers (Lemma C), the Sigma module generated by
the two lowest arrows, the Hesse space geometrising W(3,3) (Burkhardt j-planes and nodes), the Hesse CP tower, and the
45 Burkhardt nodes as qutrit concurrences with the frame sum rule."""
import json
import sys
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "analysis"))


def load(name):
    return json.load(open(ROOT / "data" / name))


def test_11655_lemma_C():
    d = load("w33_pass11655_shear_twisted_reversers.json")
    n3 = d["n3"]
    assert n3["same line, other | k!=0 solutions: A Y is a k=0 solution with N(AY) = N(A): True"] == 72
    assert n3["same line, M^2 z1 = -z1 | k!=0 solutions: A Y is a k=0 solution with N(AY) = N(A): True"] == 36
    for n in ("n2", "n3"):
        assert not any(k.endswith(": False") and v for k, v in d[n].items())


def test_11656_sigma_module():
    d = load("w33_pass11656_sigma_module_two_arrows.json")
    assert d["generated_by_g6_g7"] and d["relations_match_t9_over_R"]
    rel = d["degree9_relation"]
    assert rel["coefficients"] == ["-1/4", "1", "-1/8", "1/8", "-1/2"]
    assert rel["relative_residual_on_fresh_points"] < 1e-10


def test_11657_geometry():
    d = load("w33_pass11657_hesse_space_geometrises_w33.json")
    assert d["tick_line_meeting_graph"] == {"n": 40, "k": [12], "lam": [2], "mu": [4]}
    assert d["incidence_(p on L, u_L on tick-line of p)"] == {"(False, False)": 1440, "(True, True)": 160}
    assert d["distinct_mirrors"] == 45 and d["each_mirror_from_P_and_P_perp"]
    assert d["mirror_orthogonality_graph"] == {"n": 45, "k": [12], "lam": [3], "mu": [3]}
    assert d["orthogonal_iff_octets_disjoint_(Pass_11177_GQ42)"] == "1980/1980"
    assert d["tick_planes_are_j_planes"] is True and d["mirror_roots_are_nodes"] is True
    assert d["SWAP_mirror_among_the_45"] and d["parity of qutrit 2_mirror_among_the_45"]


def test_11658_cp_tower():
    d = load("w33_pass11658_hesse_cp_tower.json")
    assert d["tower"]["n2"]["minus_one_multiplicity_of_local_parity"] == 1
    assert d["tower"]["n3"]["minus_one_multiplicity_of_local_parity"] == 4
    n1 = {int(k): v for k, v in d["n1"].items()}
    n2 = {int(k): v for k, v in d["n2"].items()}
    assert min(k for k, v in n1.items() if v["odd"]) == 6 and min(k for k, v in n2.items() if v["odd"]) == 6
    assert [n2[k]["odd"] for k in range(1, 9)] == [0, 0, 0, 0, 0, 2, 5, 10]
    for k in range(1, 9):
        assert d["reynolds_complete_n2"][str(k)] and d["reynolds_complete_n1"][str(k)]


def test_11659_nodes_are_determinants():
    d = load("w33_pass11659_burkhardt_nodes_are_concurrences.json")
    assert abs(d["node_over_det_mean"][0] - 1) < 1e-12 and d["node_over_det_spread"] < 1e-12
    assert d["rank_of_45_nodes"] == 5 and d["frames_(5_mutually_orthogonal_nodes)"] == 27
    assert d["frame_sum_rule_max_error_(27_frames_x_200_states)"] < 1e-12
    assert abs(d["max_min_det2_3_of_a_frame"] - 1 / 27) < 1e-9 and d["max_min_det2_4_of_a_frame"] < 1 / 36


def test_11659_live_det():
    import w33_pass11651_n_qutrit_hesse_space as H
    import w33_pass11657_hesse_space_geometrises_w33 as G7
    d, pts, idx, B, wg = H.setup(2)
    par2 = np.zeros((9, 9))
    for a in pts:
        par2[idx[(a[0], (-a[1]) % 3)], idx[a]] = 1
    r = G7.reflection_root(H.R_of(B, par2))
    rng = np.random.default_rng(5)
    rat = []
    for _ in range(20):
        p = rng.normal(size=9) + 1j * rng.normal(size=9)
        p /= np.linalg.norm(p)
        rat.append(np.vdot(r, B.T @ np.kron(np.kron(p, p), p)) / np.linalg.det(p.reshape(3, 3)))
    rat = np.array(rat)
    assert np.allclose(np.abs(rat), 1) and np.allclose(rat, rat[0])
