"""
Supplement beth (after aleph) — THE DEL PEZZO DECOMPOSITION
==================================================================

A smooth cubic surface in P^3 is a del Pezzo surface of degree 3,
realized as the blow-up of P^2 at 6 generic points.  The 27 lines
on the cubic decompose as:

   6  exceptional divisors (the 6 blow-up points)
  15  proper transforms of lines through pairs of points = C(6,2)
   6  conics through 5 of the 6 points

Total: 6 + 15 + 6 = 27 = q^q.

In W(3,3) constants:

   6  = k/2
  15  = g  (also = C(k/2, 2) = binomial coefficient!)

So:

    27 = k/2 + C(k/2, 2) + k/2
       = k + g
       = q^q                      (master equation)

And the secondary identity:

    g = C(k/2, 2)     -- the SRG eigenvalue multiplicity g equals
                         the binomial coefficient choosing 2 from k/2.

This Supplement establishes the seventh face of 27 (after Supp Y's six)
via classical algebraic geometry (Cayley-Salmon-del-Pezzo).
"""
import math
from fractions import Fraction
v, k, lam, mu = 40, 12, 2, 4
q = 3
f, g = 24, 15
E = v * k // 2
Phi3, Phi4, Phi6 = 13, 10, 7


# ------------------------------------------------------------------
# beth.1  Three classes of lines on cubic surface
# ------------------------------------------------------------------
class Test_beth_1_LineClasses:
    def test_six_exceptional(self):
        # 6 = k/2 exceptional divisors (blown-up points)
        assert k // 2 == 6

    def test_fifteen_proper_transforms(self):
        # 15 = C(6,2) = C(k/2, 2) proper transforms of lines
        binom = (k // 2) * (k // 2 - 1) // 2
        assert binom == 15
        assert binom == g

    def test_six_conics(self):
        # 6 = k/2 conics through 5 of the 6 points
        assert k // 2 == 6


# ------------------------------------------------------------------
# beth.2  The total: 6 + 15 + 6 = 27
# ------------------------------------------------------------------
class Test_beth_2_TotalIs27:
    def test_sum(self):
        binom = (k // 2) * (k // 2 - 1) // 2
        total = (k // 2) + binom + (k // 2)
        assert total == 27
        assert total == q ** q

    def test_clean_form(self):
        # 27 = 2*(k/2) + C(k/2, 2) = k + g
        # This is the seventh face of 27
        assert k + g == q ** q
        assert 12 + 15 == 27


# ------------------------------------------------------------------
# beth.3  The hidden binomial identity g = C(k/2, 2)
# ------------------------------------------------------------------
class Test_beth_3_Binomial:
    def test_g_eq_binomial(self):
        # g = C(k/2, 2) = (k/2)(k/2 - 1)/2 = (k/2 - 1) * k / 4
        binom = (k // 2) * (k // 2 - 1) // 2
        assert binom == g
        assert binom == 15

    def test_alternative_forms(self):
        # 15 = C(6,2) = k/2 * 5 / 2 = ...
        # 15 = mu+1 * q -- no, that's 15! Actually 5*3 = 15 = (mu+1)*q
        assert (mu + 1) * q == 15

    def test_g_eq_mu_plus_1_times_q(self):
        # Independent: g = (mu+1) * q = 5 * 3
        assert (mu + 1) * q == g


# ------------------------------------------------------------------
# beth.4  Connection to E_6 root system
# ------------------------------------------------------------------
class Test_beth_4_E6Roots:
    def test_72_e6_roots(self):
        # E_6 has 72 roots; 27-rep generated by 6 of them
        # 72 = 2 * 6 * 6 = lam * (k/2)^2
        assert lam * (k // 2) ** 2 == 72


# ------------------------------------------------------------------
# beth.5  The 6-point blow-up
# ------------------------------------------------------------------
class Test_beth_5_BlowUp:
    def test_6_points_in_general_position(self):
        # P^2 blown up at 6 generic points; 6 = k/2
        assert k // 2 == 6

    def test_picard_rank_7(self):
        # Pic(del Pezzo deg 3) has rank 7 = 1 + 6 = 1 + k/2
        # = Phi_6 (cyclotomic 6)!
        assert 1 + k // 2 == Phi6 + 0
        assert 1 + k // 2 == 7

    def test_7_eq_Phi_6(self):
        assert k // 2 + 1 == Phi6


# ------------------------------------------------------------------
# beth.6  The full lattice
# ------------------------------------------------------------------
class Test_beth_6_PicardLattice:
    def test_picard_E_6(self):
        # The orthogonal complement of K_S in Pic(del Pezzo deg 3) is
        # the E_6 root lattice (signature (1,6) with K_S deleted)
        # rank 6 = k/2
        assert k // 2 == 6


# ------------------------------------------------------------------
# beth.7  Cycle structure / Coxeter element
# ------------------------------------------------------------------
class Test_beth_7_Coxeter:
    def test_E6_coxeter_number(self):
        # h(E_6) = 12 = k
        assert k == 12

    def test_E6_dimension(self):
        # dim E_6 = 78 = lam * q * Phi_3
        assert lam * q * Phi3 == 78


# ------------------------------------------------------------------
# beth-CLOSURE
# ------------------------------------------------------------------
class Test_beth_Closure:
    def test_seven_faces_of_27(self):
        # Supp Y had six faces of 27.  The del Pezzo decomposition is
        # the seventh:
        seventh_face = 'del Pezzo: 27 = 6 + 15 + 6 = k + g'
        assert k + g == 27
        assert (k // 2) + g + (k // 2) == q ** q

    def test_decisive_identity(self):
        # 27 = k + g
        # = q^q
        # = (k/2) + C(k/2, 2) + (k/2)
        # = del-Pezzo line decomposition
        assert k + g == q ** q == 27

    def test_secondary_binomial(self):
        # g = C(k/2, 2) -- new identity for the SRG eigenvalue
        # multiplicity in terms of the local degree
        binom = (k // 2) * (k // 2 - 1) // 2
        assert binom == g
