#!/usr/bin/env python3
"""Generate the data-driven TikZ figures of the Forty Points paper.

Every coordinate below is computed, not drawn by hand:

* fig_w33portrait.tex -- W(3,3) built from the symplectic form on F_3^4, drawn in
  the 1 + 12 + 27 layout of one point, with all 240 collinearity edges.
* fig_e8coxeter.tex  -- the 240 E8 roots projected to the Coxeter plane of a
  Coxeter element c; the orbits of c^5 (order 6) are regular hexagons, 5 per ring,
  8 rings: the 40 fibres of the 6:1 fibration onto the points of W(3,3).
* fig_cone.tex       -- the real light cone of 2x2 symmetric matrices with the four
  null directions D_0, D_inf, D_+, D_- and the zig-zag to 3I, in an exact
  orthographic projection.

Run:  py -3 make_figures.py   (from papers/forty_points)
"""
from __future__ import annotations

import itertools
import math
from pathlib import Path

import numpy as np

HERE = Path(__file__).resolve().parent


# ----------------------------------------------------------------- W(3,3)
def symp(x, y):
    return (x[0] * y[2] + x[1] * y[3] - x[2] * y[0] - x[3] * y[1]) % 3


def w33_points():
    pts = []
    for v in itertools.product(range(3), repeat=4):
        if any(v):
            # canonical representative: first nonzero coordinate equal to 1
            first = next(c for c in v if c)
            if first == 1:
                pts.append(v)
    assert len(pts) == 40
    return pts


def fig_w33portrait():
    pts = w33_points()
    p = (1, 0, 0, 0)
    col = {q: {r for r in pts if r != q and symp(q, r) == 0} for q in pts}
    edges = {frozenset((a, b)) for a in pts for b in col[a]}
    assert len(edges) == 240 and all(len(col[q]) == 12 for q in pts)
    nbrs = sorted(col[p])
    far = [q for q in pts if q != p and q not in col[p]]
    assert len(far) == 27
    # the four lines through p: p + each neighbour spans a line
    lines = []
    seen = set()
    for n in nbrs:
        if n in seen:
            continue
        line = {n} | {m for m in nbrs if m != n and symp(n, m) == 0}
        assert len(line) == 3
        seen |= line
        lines.append(sorted(line))
    assert len(lines) == 4
    # each far point meets each line through p in exactly one neighbour
    sig = {}
    for f in far:
        s = []
        for L in lines:
            hits = [i for i, m in enumerate(L) if symp(f, m) == 0]
            assert len(hits) == 1
            s.append(hits[0])
        sig[f] = tuple(s)
    far.sort(key=lambda f: sig[f])
    pos = {p: (0.0, 0.0)}
    angles = [90, 180, 270, 0]
    for L, a in zip(lines, angles):
        for k, m in enumerate(L):
            ang = math.radians(a + (k - 1) * 14)
            r = 1.55
            pos[m] = (r * math.cos(ang), r * math.sin(ang))
    for k, f in enumerate(far):
        ang = math.radians(90 - 360 * k / 27)
        pos[f] = (4.1 * math.cos(ang), 4.1 * math.sin(ang))
    out = []
    kind_style = {
        "pn": "pn",  # p - neighbour
        "nn": "nn",  # neighbour - neighbour (same line)
        "nf": "nf",  # neighbour - far
        "ff": "ff",  # far - far
    }
    order = {"ff": 0, "nf": 1, "nn": 2, "pn": 3}
    typed = []
    for e in edges:
        a, b = tuple(e)
        ka = "p" if a == p else ("n" if a in col[p] else "f")
        kb = "p" if b == p else ("n" if b in col[p] else "f")
        key = "".join(sorted(ka + kb, key="pnf".index))
        typed.append((order[key], key, a, b))
    typed.sort()
    counts = {}
    for _, key, a, b in typed:
        counts[key] = counts.get(key, 0) + 1
        (x1, y1), (x2, y2) = pos[a], pos[b]
        out.append(f"\\draw[{kind_style[key]}] ({x1:.3f},{y1:.3f}) -- ({x2:.3f},{y2:.3f});")
    assert counts == {"pn": 12, "nn": 12, "nf": 108, "ff": 108}, counts
    linecol = ["teal", "sky", "gold", "sage"]
    for L, c in zip(lines, linecol):
        for m in L:
            x, y = pos[m]
            out.append(f"\\fill[{c}] ({x:.3f},{y:.3f}) circle (2.6pt);")
    for f in far:
        x, y = pos[f]
        out.append(f"\\fill[rose] ({x:.3f},{y:.3f}) circle (2.2pt);")
    out.append("\\fill[ink] (0,0) circle (3.4pt);")
    (HERE / "fig_w33portrait.tex").write_text(
        "% generated by make_figures.py -- W(3,3), 40 points, 240 edges\n" + "\n".join(out) + "\n",
        encoding="utf-8",
    )
    return counts


# ----------------------------------------------------------------- E8
def e8_simple_roots():
    # Bourbaki: alpha1 = 1/2(1,-1,-1,-1,-1,-1,-1,1), alpha2 = e1+e2,
    # alpha_k = e_{k-1} - e_{k-2} (k=3..8)
    a = np.zeros((8, 8))
    a[0] = 0.5 * np.array([1, -1, -1, -1, -1, -1, -1, 1])
    a[1] = np.array([1, 1, 0, 0, 0, 0, 0, 0])
    for k in range(2, 8):
        v = np.zeros(8)
        v[k - 1] = 1
        v[k - 2] = -1
        a[k] = v
    return a


def e8_roots():
    roots = []
    for i, j in itertools.combinations(range(8), 2):
        for si in (1, -1):
            for sj in (1, -1):
                v = np.zeros(8)
                v[i], v[j] = si, sj
                roots.append(v)
    for signs in itertools.product((0.5, -0.5), repeat=8):
        if sum(1 for s in signs if s < 0) % 2 == 0:
            roots.append(np.array(signs))
    R = np.array(roots)
    assert R.shape == (240, 8)
    return R


def reflection(a):
    return np.eye(8) - 2 * np.outer(a, a) / (a @ a)


def fig_e8coxeter():
    S = e8_simple_roots()
    R = e8_roots()
    # check the simple roots are roots
    rset = {tuple(np.round(r * 2).astype(int)) for r in R}
    for s in S:
        assert tuple(np.round(s * 2).astype(int)) in rset
    c = np.eye(8)
    for s in S:
        c = c @ reflection(s)
    # order 30
    M = np.eye(8)
    for k in range(1, 31):
        M = M @ c
        if np.allclose(M, np.eye(8)):
            order = k
            break
    assert order == 30
    w, V = np.linalg.eig(c)
    k = int(np.argmin(np.abs(w - np.exp(2j * math.pi / 30))))
    v = V[:, k]
    u1, u2 = np.real(v), np.imag(v)
    # orthonormalise
    u1 = u1 / np.linalg.norm(u1)
    u2 = u2 - (u2 @ u1) * u1
    u2 = u2 / np.linalg.norm(u2)
    P = np.stack([R @ u1, R @ u2], axis=1)
    radii = np.round(np.hypot(P[:, 0], P[:, 1]), 6)
    rings = sorted(set(radii))
    assert len(rings) == 8, rings
    c5 = np.linalg.matrix_power(c, 5)
    idx = {tuple(np.round(r * 2).astype(int)): i for i, r in enumerate(R)}
    fibres = []
    done = set()
    for i in range(240):
        if i in done:
            continue
        orb = [i]
        x = R[i]
        for _ in range(5):
            x = c5 @ x
            orb.append(idx[tuple(np.round(x * 2).astype(int))])
        assert len(set(orb)) == 6
        done |= set(orb)
        fibres.append(orb)
    assert len(fibres) == 40
    # the fibre is {+-v, +-w v, +-w^2 v}: c^15 = -1 and c^10 has order 3
    c15 = np.linalg.matrix_power(c, 15)
    assert np.allclose(c15, -np.eye(8))
    scale = 3.6 / max(rings)
    palette = ["teal", "sky", "gold", "sage", "rose"]
    out = []
    for r in rings:
        out.append(f"\\draw[ink!10,line width=0.3pt] (0,0) circle ({r*scale:.3f});")
    ring_count = {r: 0 for r in rings}
    for orb in fibres:
        rr = radii[orb[0]]
        colour = palette[ring_count[rr] % 5]
        ring_count[rr] += 1
        pts = [P[j] * scale for j in orb]
        # order hexagon vertices by angle
        pts.sort(key=lambda q: math.atan2(q[1], q[0]))
        path = " -- ".join(f"({q[0]:.3f},{q[1]:.3f})" for q in pts) + " -- cycle"
        out.append(f"\\draw[{colour}!55,line width=0.45pt] {path};")
        for q in pts:
            out.append(f"\\fill[{colour}] ({q[0]:.3f},{q[1]:.3f}) circle (1.25pt);")
    assert all(v == 5 for v in ring_count.values())
    (HERE / "fig_e8coxeter.tex").write_text(
        "% generated by make_figures.py -- E8 Coxeter plane, 40 hexagonal fibres\n"
        + "\n".join(out)
        + "\n",
        encoding="utf-8",
    )
    return len(fibres), len(rings)


# ----------------------------------------------------------------- cone
def fig_cone():
    az = math.radians(35)
    se = 0.30
    ce = math.sqrt(1 - se * se)

    def proj(x, y, z):
        xr = x * math.cos(az) - y * math.sin(az)
        yr = x * math.sin(az) + y * math.cos(az)
        return (xr, ce * z + se * yr)

    # symmetric matrix (a,b;b,c) -> (x,y,z) = (b, (a-c)/2, (a+c)/2); det = z^2-x^2-y^2
    def m2v(a, b, c):
        return (b, (a - c) / 2, (a + c) / 2)

    D = {
        "D0": m2v(1, 0, 0),
        "Dinf": m2v(0, 0, 1),
        "Dp": m2v(1, 1, 1),
        "Dm": m2v(1, -1, 1),
    }
    for x, y, z in D.values():
        assert abs(z * z - x * x - y * y) < 1e-12
    H = 3.3
    out = []
    # cone surface: silhouette tangents from apex to the rim ellipse
    cy, rx, ry = ce * H, H, se * H
    # tangent points of lines through origin to ellipse (x/rx)^2+((y-cy)/ry)^2=1
    # parametrise rim t -> (rx cos t, cy + ry sin t); tangent condition: cross(P, P') = 0
    ts = np.linspace(0, 2 * math.pi, 20001)
    f = rx * np.cos(ts) * ry * np.cos(ts) - (cy + ry * np.sin(ts)) * (-rx * np.sin(ts))
    tang = [ts[i] for i in range(len(ts) - 1) if f[i] == 0 or f[i] * f[i + 1] < 0]
    tpts = [(rx * math.cos(t), cy + ry * math.sin(t)) for t in tang]
    tpts.sort()
    (lx, ly), (rxp, ryp) = tpts[0], tpts[-1]
    out.append(f"\\coordinate (TL) at ({lx:.3f},{ly:.3f});")
    out.append(f"\\coordinate (TR) at ({rxp:.3f},{ryp:.3f});")
    out.append(f"\\def\\conecy{{{cy:.3f}}}\\def\\conerx{{{rx:.3f}}}\\def\\conery{{{ry:.3f}}}")
    angl = math.degrees(math.atan2((ly - cy) / ry, lx / rx)) % 360
    angr = math.degrees(math.atan2((ryp - cy) / ry, rxp / rx)) % 360
    out.append(f"\\def\\conetl{{{angl:.2f}}}\\def\\conetr{{{angr:.2f}}}")
    names = {"D0": "teal", "Dinf": "sky", "Dp": "gold", "Dm": "sage"}
    for k, (x, y, z) in D.items():
        s = H / z
        px, py = proj(x * s, y * s, z * s)
        qx, qy = proj(x, y, z)
        out.append(f"\\coordinate (R{k}) at ({px:.3f},{py:.3f});")
        out.append(f"\\coordinate (P{k}) at ({qx:.3f},{qy:.3f});")
    path = [(0, 0, 0)]
    acc = np.zeros(3)
    for k in ["D0", "Dinf", "Dp", "Dm"]:
        acc = acc + np.array(D[k])
        path.append(tuple(acc))
    assert np.allclose(acc, (0, 0, 3))
    for i, (x, y, z) in enumerate(path):
        px, py = proj(x, y, z)
        out.append(f"\\coordinate (Z{i}) at ({px:.3f},{py:.3f});")
    (HERE / "fig_cone.tex").write_text(
        "% generated by make_figures.py -- exact orthographic light cone\n" + "\n".join(out) + "\n",
        encoding="utf-8",
    )


if __name__ == "__main__":
    print("W(3,3) edge types:", fig_w33portrait())
    print("E8 fibres, rings:", fig_e8coxeter())
    fig_cone()
    print("cone ok")
