#include <bits/stdc++.h>
using namespace std;
struct Bits{uint64_t w[9]{};bool operator==(Bits const&o)const{for(int i=0;i<9;i++)if(w[i]!=o.w[i])return false;return true;}bool operator<(Bits const&o)const{for(int i=0;i<9;i++){if(w[i]!=o.w[i])return w[i]<o.w[i];}return false;}};
struct BH{size_t operator()(Bits const&b)const noexcept{uint64_t h=1469598103934665603ULL;for(int i=0;i<9;i++){h^=b.w[i];h*=1099511628211ULL;}return h;}};
inline bool disj(Bits const&a,Bits const&b){for(int i=0;i<9;i++)if(a.w[i]&b.w[i])return false;return true;}
struct Ent{Bits b;uint16_t type;int gen;};
struct Key2{Bits x[2];bool operator==(Key2 const&o)const{return x[0]==o.x[0]&&x[1]==o.x[1];}bool operator<(Key2 const&o)const{return x[0]<o.x[0]||(!(o.x[0]<x[0])&&x[1]<o.x[1]);}};
struct Key3{Bits x[3];bool operator==(Key3 const&o)const{return x[0]==o.x[0]&&x[1]==o.x[1]&&x[2]==o.x[2];}bool operator<(Key3 const&o)const{for(int i=0;i<3;i++){if(x[i]<o.x[i])return true;if(o.x[i]<x[i])return false;}return false;}};
struct Key4{Bits x[4];bool operator==(Key4 const&o)const{for(int i=0;i<4;i++)if(!(x[i]==o.x[i]))return false;return true;}bool operator<(Key4 const&o)const{for(int i=0;i<4;i++){if(x[i]<o.x[i])return true;if(o.x[i]<x[i])return false;}return false;}};
struct K2H{size_t operator()(Key2 const&k)const noexcept{return BH{}(k.x[0])^(BH{}(k.x[1])*0x9e3779b97f4a7c15ULL);}};
struct K3H{size_t operator()(Key3 const&k)const noexcept{return BH{}(k.x[0])^(BH{}(k.x[1])*0x9e3779b97f4a7c15ULL)^(BH{}(k.x[2])*0xc2b2ae3d27d4eb4fULL);}};
struct K4H{size_t operator()(Key4 const&k)const noexcept{return BH{}(k.x[0])^(BH{}(k.x[1])*0x9e3779b97f4a7c15ULL)^(BH{}(k.x[2])*0xc2b2ae3d27d4eb4fULL)^(BH{}(k.x[3])*0x165667b19e3779f9ULL);}};
struct Val{uint32_t count=0;uint8_t mi=0;};
const int NO=327,NR=60,NG=25920,NF=540;
vector<uint16_t> reps,act,invact;vector<uint32_t> osz;
Bits make_rep(int i){Bits b;for(int k=0;k<NR;k++){int x=reps[i*NR+k];b.w[x>>6]|=1ULL<<(x&63);}return b;}
Bits image_rep(int j,int g){Bits b;auto*p=&act[(size_t)g*NF];for(int k=0;k<NR;k++){int x=p[reps[j*NR+k]];b.w[x>>6]|=1ULL<<(x&63);}return b;}
Bits transform(Bits const&b,const uint16_t*t,const uint16_t*h){Bits z;for(int wi=0;wi<9;wi++){uint64_t x=b.w[wi];while(x){int q=__builtin_ctzll(x);x&=x-1;int f=(wi<<6)+q;if(f>=NF)continue;int y=h[t[f]];z.w[y>>6]|=1ULL<<(y&63);}}return z;}
Key2 canon2(int I,Bits const&A,Ent const&B,Ent const&C,vector<int>const&Hidx){array<Ent,3>P{{{A,(uint16_t)I,-2},B,C}};Key2 best;bool first=true;for(int q=0;q<3;q++)if(P[q].type==I){const uint16_t*t;if(P[q].gen==-2){static uint16_t id[NF];static bool init=false;if(!init){for(int i=0;i<NF;i++)id[i]=i;init=true;}t=id;}else t=&invact[(size_t)P[q].gen*NF];for(int hg:Hidx){auto*h=&act[(size_t)hg*NF];array<Bits,2>R;int u=0;for(int r=0;r<3;r++)if(r!=q)R[u++]=transform(P[r].b,t,h);if(R[1]<R[0])swap(R[0],R[1]);Key2 k{{R[0],R[1]}};if(first||k<best){best=k;first=false;}}}return best;}
Key3 canon3(int I,Bits const&A,Ent const&B,Ent const&C,Ent const&D,vector<int>const&Hidx){array<Ent,4>P{{{A,(uint16_t)I,-2},B,C,D}};Key3 best;bool first=true;for(int q=0;q<4;q++)if(P[q].type==I){const uint16_t*t;if(P[q].gen==-2){static uint16_t id[NF];static bool init=false;if(!init){for(int i=0;i<NF;i++)id[i]=i;init=true;}t=id;}else t=&invact[(size_t)P[q].gen*NF];for(int hg:Hidx){auto*h=&act[(size_t)hg*NF];array<Bits,3>R;int u=0;for(int r=0;r<4;r++)if(r!=q)R[u++]=transform(P[r].b,t,h);sort(R.begin(),R.end());Key3 k{{R[0],R[1],R[2]}};if(first||k<best){best=k;first=false;}}}return best;}
Key4 canon4(int I,Bits const&A,Ent const&B,Ent const&C,Ent const&D,Ent const&E,vector<int>const&Hidx){array<Ent,5>P{{{A,(uint16_t)I,-2},B,C,D,E}};Key4 best;bool first=true;for(int q=0;q<5;q++)if(P[q].type==I){const uint16_t*t;if(P[q].gen==-2){static uint16_t id[NF];static bool init=false;if(!init){for(int i=0;i<NF;i++)id[i]=i;init=true;}t=id;}else t=&invact[(size_t)P[q].gen*NF];for(int hg:Hidx){auto*h=&act[(size_t)hg*NF];array<Bits,4>R;int u=0;for(int r=0;r<5;r++)if(r!=q)R[u++]=transform(P[r].b,t,h);sort(R.begin(),R.end());Key4 k{{R[0],R[1],R[2],R[3]}};if(first||k<best){best=k;first=false;}}}return best;}
uint64_t fnv_bytes(uint64_t h,const void*p,size_t n){auto*b=(const uint8_t*)p;for(size_t i=0;i<n;i++){h^=b[i];h*=1099511628211ULL;}return h;}
int main(int argc,char**argv){if(argc<4){cerr<<"usage: worker reps.bin sizes.bin actions.bin [start end]\n";return 2;}int START=argc>4?atoi(argv[4]):0,END=argc>5?atoi(argv[5]):NO;reps.resize(NO*NR);act.resize((size_t)NG*NF);invact.resize((size_t)NG*NF);osz.resize(NO);auto rd=[](const char*fn,void*p,size_t n){FILE*f=fopen(fn,"rb");if(!f){perror(fn);exit(2);}if(fread(p,1,n,f)!=n){cerr<<"short\n";exit(2);}fclose(f);};rd(argv[1],reps.data(),reps.size()*2);rd(argv[2],osz.data(),osz.size()*4);rd(argv[3],act.data(),act.size()*2);for(int g=0;g<NG;g++)for(int f=0;f<NF;f++)invact[(size_t)g*NF+act[(size_t)g*NF+f]]=f;
 uint64_t totalTorbits=0,totalQorbits=0,totalPorbits=0,totalTpack=0,totalQpack=0,totalPpack=0,extendQorbits=0,extendPorbits=0,indTnum=0,indQnum=0,indPnum=0;map<int,uint64_t>tstab,qstab,pstab;uint64_t globalHash=1469598103934665603ULL;auto allst=chrono::steady_clock::now();
 for(int I=START;I<END;I++){auto st=chrono::steady_clock::now();Bits A=make_rep(I);vector<int>Hidx;for(int g=0;g<NG;g++)if(image_rep(I,g)==A)Hidx.push_back(g);if((int)Hidx.size()!=51840/(2*(int)osz[I])){cerr<<"stab mismatch I="<<I<<" got="<<Hidx.size()<<" osz="<<osz[I]<<"\n";return 3;}
 vector<Ent>D;D.reserve(20000);for(int j=0;j<NO;j++){unordered_map<Bits,int,BH>U;U.reserve(osz[j]*2+10);for(int g=0;g<NG;g++){Bits b=image_rep(j,g);if(disj(A,b)&&!U.count(b))U.emplace(b,g);}for(auto const&kv:U)D.push_back({kv.first,(uint16_t)j,kv.second});}
 sort(D.begin(),D.end(),[](Ent const&a,Ent const&b){if(a.type!=b.type)return a.type<b.type;return a.b<b.b;});size_t n=D.size(),W64=(n+63)/64;vector<uint64_t>adj(n*W64);uint64_t allEdges=0;for(size_t a=0;a<n;a++)for(size_t b=a+1;b<n;b++)if(disj(D[a].b,D[b].b)){adj[a*W64+(b>>6)]|=1ULL<<(b&63);adj[b*W64+(a>>6)]|=1ULL<<(a&63);allEdges++;}uint64_t allTri=0,allQuad=0;for(size_t b=0;b<n;b++)for(size_t c=b+1;c<n;c++)if((adj[b*W64+(c>>6)]>>(c&63))&1ULL){for(size_t z=(c>>6);z<W64;z++){uint64_t x=adj[b*W64+z]&adj[c*W64+z];if(z==(c>>6)){int sh=(c&63)+1;x&=sh==64?0ULL:~((1ULL<<sh)-1);}allTri+=__builtin_popcountll(x);while(x){int bit=__builtin_ctzll(x);x&=x-1;size_t d=z*64+bit;for(size_t y=(d>>6);y<W64;y++){uint64_t u=adj[b*W64+y]&adj[c*W64+y]&adj[d*W64+y];if(y==(d>>6)){int sh=(d&63)+1;u&=sh==64?0ULL:~((1ULL<<sh)-1);}allQuad+=__builtin_popcountll(u);}}}}indTnum+=(uint64_t)osz[I]*allEdges;indQnum+=(uint64_t)osz[I]*allTri;indPnum+=(uint64_t)osz[I]*allQuad;
 unordered_map<Key2,Val,K2H>T;unordered_map<Key3,pair<Val,bool>,K3H>Q;unordered_map<Key4,pair<Val,bool>,K4H>P;T.reserve(300000);Q.reserve(10000);P.reserve(1000);uint64_t rawE=0,rawTri=0,rawQuad=0;
 size_t first=lower_bound(D.begin(),D.end(),I,[](Ent const&e,int x){return e.type<x;})-D.begin();
 for(size_t b=first;b<n;b++)for(size_t c=b+1;c<n;c++)if((adj[b*W64+(c>>6)]>>(c&63))&1ULL){rawE++;Key2 k=canon2(I,A,D[b],D[c],Hidx);auto&v=T[k];v.count++;v.mi=(D[b].type==I)+(D[c].type==I)+1;
   for(size_t z=0;z<W64;z++){uint64_t x=adj[b*W64+z]&adj[c*W64+z];if(z<(c>>6))x=0;else if(z==(c>>6)){int sh=(c&63)+1;x&=sh==64?0ULL:~((1ULL<<sh)-1);}while(x){int bit=__builtin_ctzll(x);x&=x-1;size_t d=z*64+bit;if(d>=n||D[d].type<I)continue;rawTri++;bool ext=false;for(size_t y=0;y<W64;y++){uint64_t u=adj[b*W64+y]&adj[c*W64+y]&adj[d*W64+y];if(u)ext=true;if(y<(d>>6))u=0;else if(y==(d>>6)){int sh=(d&63)+1;u&=sh==64?0ULL:~((1ULL<<sh)-1);}while(u){int eb=__builtin_ctzll(u);u&=u-1;size_t e=y*64+eb;if(e>=n||D[e].type<I)continue;rawQuad++;bool ext6=false;for(size_t w=0;w<W64;w++)if(adj[b*W64+w]&adj[c*W64+w]&adj[d*W64+w]&adj[e*W64+w]){ext6=true;break;}Key4 pk=canon4(I,A,D[b],D[c],D[d],D[e],Hidx);auto&pv=P[pk];pv.first.count++;pv.first.mi=(D[b].type==I)+(D[c].type==I)+(D[d].type==I)+(D[e].type==I)+1;pv.second=pv.second||ext6;}}Key3 q=canon3(I,A,D[b],D[c],D[d],Hidx);auto&vv=Q[q];vv.first.count++;vv.first.mi=(D[b].type==I)+(D[c].type==I)+(D[d].type==I)+1;vv.second=vv.second||ext;}}
 }
 uint64_t tpack=0,qpack=0,ppack=0,extorb=0,extporb=0;vector<pair<Key2,Val>>tv(T.begin(),T.end());sort(tv.begin(),tv.end(),[](auto const&a,auto const&b){return a.first<b.first;});for(auto const&kv:tv){int stab=(int)Hidx.size()*kv.second.mi/kv.second.count;if((int)Hidx.size()*kv.second.mi%kv.second.count){cerr<<"nonint T I="<<I<<"\n";return 4;}uint64_t os=NG/stab;tpack+=os;tstab[stab]++;globalHash=fnv_bytes(globalHash,&I,sizeof(I));globalHash=fnv_bytes(globalHash,&kv.first,sizeof(kv.first));globalHash=fnv_bytes(globalHash,&stab,sizeof(stab));}
 vector<pair<Key3,pair<Val,bool>>>qv(Q.begin(),Q.end());sort(qv.begin(),qv.end(),[](auto const&a,auto const&b){return a.first<b.first;});for(auto const&kv:qv){auto v=kv.second.first;int stab=(int)Hidx.size()*v.mi/v.count;if((int)Hidx.size()*v.mi%v.count){cerr<<"nonint Q I="<<I<<" count="<<v.count<<" mi="<<(int)v.mi<<" H="<<Hidx.size()<<"\n";return 5;}uint64_t os=NG/stab;qpack+=os;qstab[stab]++;if(kv.second.second)extorb++;globalHash=fnv_bytes(globalHash,&I,sizeof(I));globalHash=fnv_bytes(globalHash,&kv.first,sizeof(kv.first));globalHash=fnv_bytes(globalHash,&stab,sizeof(stab));globalHash=fnv_bytes(globalHash,&kv.second.second,sizeof(bool));}
vector<pair<Key4,pair<Val,bool>>>pv(P.begin(),P.end());sort(pv.begin(),pv.end(),[](auto const&a,auto const&b){return a.first<b.first;});for(auto const&kv:pv){auto v=kv.second.first;int stab=(int)Hidx.size()*v.mi/v.count;if((int)Hidx.size()*v.mi%v.count){cerr<<"nonint P I="<<I<<" count="<<v.count<<" mi="<<(int)v.mi<<" H="<<Hidx.size()<<"\n";return 7;}uint64_t os=NG/stab;ppack+=os;pstab[stab]++;if(kv.second.second)extporb++;globalHash=fnv_bytes(globalHash,&I,sizeof(I));globalHash=fnv_bytes(globalHash,&kv.first,sizeof(kv.first));globalHash=fnv_bytes(globalHash,&stab,sizeof(stab));globalHash=fnv_bytes(globalHash,&kv.second.second,sizeof(bool));}
 totalTorbits+=T.size();totalQorbits+=Q.size();totalPorbits+=P.size();totalTpack+=tpack;totalQpack+=qpack;totalPpack+=ppack;extendQorbits+=extorb;extendPorbits+=extporb;double sec=chrono::duration<double>(chrono::steady_clock::now()-st).count();cout<<"I "<<I<<" D "<<n<<" H "<<Hidx.size()<<" rawE "<<rawE<<" Torb "<<T.size()<<" rawQ "<<rawTri<<" Qorb "<<Q.size()<<" extQ "<<extorb<<" rawP "<<rawQuad<<" Porb "<<P.size()<<" extP "<<extporb<<" sec "<<sec<<"\n"<<flush;
 }
 double sec=chrono::duration<double>(chrono::steady_clock::now()-allst).count();uint64_t independentT=indTnum/3,independentQ=indQnum/4,independentP=indPnum/5;if(START==0&&END==NO&&(indTnum%3||indQnum%4||indPnum%5||independentT!=totalTpack||independentQ!=totalQpack||independentP!=totalPpack)){cerr<<"independent count mismatch T "<<independentT<<"/"<<totalTpack<<" Q "<<independentQ<<"/"<<totalQpack<<" P "<<independentP<<"/"<<totalPpack<<"\n";return 6;}auto hist=[](map<int,uint64_t>const&m){ostringstream o;o<<"{";bool f=true;for(auto const&kv:m){if(!f)o<<",";f=false;o<<"\""<<kv.first<<"\":"<<kv.second;}o<<"}";return o.str();};cerr<<"FINAL {\"start\":"<<START<<",\"end\":"<<END<<",\"triple_orbits\":"<<totalTorbits<<",\"quad_orbits\":"<<totalQorbits<<",\"five_orbits\":"<<totalPorbits<<",\"triple_packings\":"<<totalTpack<<",\"quad_packings\":"<<totalQpack<<",\"five_packings\":"<<totalPpack<<",\"independent_triple_packings\":"<<independentT<<",\"independent_quad_packings\":"<<independentQ<<",\"independent_five_packings\":"<<independentP<<",\"extendable_quad_orbits\":"<<extendQorbits<<",\"extendable_five_orbits\":"<<extendPorbits<<",\"triple_stabilizer_histogram\":"<<hist(tstab)<<",\"quad_stabilizer_histogram\":"<<hist(qstab)<<",\"five_stabilizer_histogram\":"<<hist(pstab)<<",\"fnv64\":\""<<hex<<setw(16)<<setfill('0')<<globalHash<<dec<<"\",\"seconds\":"<<sec<<"}\n";
}
