#include <bits/stdc++.h>
using namespace std; constexpr int RW=9,EW=4;
struct RBits{uint64_t w[RW];}; struct EBits{uint64_t w[EW];};
int nf,ne; vector<array<int,4>> re; vector<RBits> edgeMask,conflictMask; vector<EBits> rowEdges; vector<int> sol; FILE*outf; uint64_t countsol=0,nodes=0;
inline int pcand(const RBits&a,const RBits&m){int n=0;for(int i=0;i<RW;i++)n+=__builtin_popcountll(a.w[i]&m.w[i]);return n;}
inline bool etest(const EBits&u,int e){return (u.w[e>>6]>>(e&63))&1ULL;}
inline RBits randnot(const RBits&a,const RBits&b){RBits c;for(int i=0;i<RW;i++)c.w[i]=a.w[i]&~b.w[i];return c;}
inline EBits eor(const EBits&a,const EBits&b){EBits c;for(int i=0;i<EW;i++)c.w[i]=a.w[i]|b.w[i];return c;}
void dfs(const RBits&avail,const EBits&used){nodes++; if(sol.size()==60){countsol++; array<uint16_t,60>a;vector<int>s=sol;sort(s.begin(),s.end());for(int i=0;i<60;i++)a[i]=s[i];fwrite(a.data(),2,60,outf);return;} int best=-1,bn=100;for(int e=0;e<ne;e++)if(!etest(used,e)){int n=pcand(avail,edgeMask[e]);if(n<bn){bn=n;best=e;if(n<=1)break;}}if(best<0||bn==0)return;uint64_t cand[RW];for(int i=0;i<RW;i++)cand[i]=avail.w[i]&edgeMask[best].w[i];for(int wi=0;wi<RW;wi++)while(cand[wi]){int b=__builtin_ctzll(cand[wi]);cand[wi]&=cand[wi]-1;int r=wi*64+b;if(r>=nf)continue;sol.push_back(r);RBits na=randnot(avail,conflictMask[r]);EBits nu=eor(used,rowEdges[r]);dfs(na,nu);sol.pop_back();}}
int main(int argc,char**argv){if(argc<3)return 2;ifstream in(argv[1]);int ng;in>>nf>>ne>>ng;re.resize(nf);edgeMask.assign(ne,{});conflictMask.assign(nf,{});rowEdges.assign(nf,{});for(int r=0;r<nf;r++)for(int j=0;j<4;j++){int e;in>>e;re[r][j]=e;edgeMask[e].w[r>>6]|=1ULL<<(r&63);rowEdges[r].w[e>>6]|=1ULL<<(e&63);}for(int r=0;r<nf;r++)for(int j=0;j<4;j++){int e=re[r][j];for(int w=0;w<RW;w++)conflictMask[r].w[w]|=edgeMask[e].w[w];}RBits avail{};for(int r=0;r<nf;r++)avail.w[r>>6]|=1ULL<<(r&63);EBits used{};int fixed=0;avail=randnot(avail,conflictMask[fixed]);used=eor(used,rowEdges[fixed]);sol.push_back(fixed);outf=fopen(argv[2],"wb");uint64_t zero=0;fwrite(&zero,8,1,outf);auto st=chrono::steady_clock::now();dfs(avail,used);fseek(outf,0,SEEK_SET);fwrite(&countsol,8,1,outf);fclose(outf);double sec=chrono::duration<double>(chrono::steady_clock::now()-st).count();cerr<<"nodes="<<nodes<<" sols="<<countsol<<" sec="<<sec<<"\n";cout<<"{\"solutions\":"<<countsol<<",\"nodes\":"<<nodes<<",\"seconds\":"<<sec<<"}\n";return 0;}
