#include <bits/stdc++.h>
using namespace std;
static const int N=540,C=240,K=9,ALL=(1<<K)-1;
array<array<int,K>,C> clq; array<array<int,4>,N> vclq; array<unsigned short,N> dom;
vector<pair<int,unsigned short>> trail; uint64_t nodes=0,propagations=0,backtracks=0; chrono::steady_clock::time_point start_time; double limit_sec=60; bool timed_out=false;
inline int pc(int x){return __builtin_popcount((unsigned)x);}
void setdom(int v,unsigned short nd,deque<int>&q){if(dom[v]==nd)return;trail.push_back({v,dom[v]});dom[v]=nd;for(int j=0;j<4;j++)q.push_back(vclq[v][j]);}
void undo(size_t m){while(trail.size()>m){auto [v,d]=trail.back();trail.pop_back();dom[v]=d;}}
bool reduce_clique(int ci,deque<int>&q){propagations++;bool F[10][512]{},B[10][512]{};F[0][0]=true;for(int i=0;i<K;i++){int d=dom[clq[ci][i]];if(!d)return false;for(int m=0;m<=ALL;m++)if(F[i][m])for(int a=d&~m;a;){int b=a&-a;a-=b;F[i+1][m|b]=true;}}if(!F[K][ALL])return false;B[K][0]=true;for(int i=K-1;i>=0;i--){int d=dom[clq[ci][i]];for(int m=0;m<=ALL;m++)if(B[i+1][m])for(int a=d&~m;a;){int b=a&-a;a-=b;B[i][m|b]=true;}}for(int i=0;i<K;i++){int v=clq[ci][i],d=dom[v],nd=0;for(int a=d;a;){int b=a&-a;a-=b;bool ok=false;for(int m=0;m<=ALL&&!ok;m++)if(F[i][m]&&!(m&b)){int t=ALL^m^b;if(B[i+1][t])ok=true;}if(ok)nd|=b;}if(!nd)return false;if(nd!=d)setdom(v,(unsigned short)nd,q);}return true;}
bool propagate(deque<int>&q){array<unsigned char,C> inq{};deque<int>qq;while(!q.empty()){int c=q.front();q.pop_front();if(!inq[c])inq[c]=1,qq.push_back(c);}while(!qq.empty()){int c=qq.front();qq.pop_front();inq[c]=0;deque<int>a;if(!reduce_clique(c,a))return false;while(!a.empty()){int d=a.front();a.pop_front();if(!inq[d])inq[d]=1,qq.push_back(d);}}return true;}
int choose_var(){int best=-1,bs=10,bscore=-1;for(int v=0;v<N;v++){int s=pc(dom[v]);if(s<=1)continue;int score=0;for(int j=0;j<4;j++)for(int i=0;i<K;i++)score+=10-pc(dom[clq[vclq[v][j]][i]]);if(s<bs||(s==bs&&score>bscore))bs=s,best=v,bscore=score;}return best;}
bool verify(){for(int v=0;v<N;v++)if(pc(dom[v])!=1)return false;for(int c=0;c<C;c++){int u=0;for(int i=0;i<K;i++)u|=dom[clq[c][i]];if(u!=ALL)return false;}return true;}
bool dfs(){nodes++;if(chrono::duration<double>(chrono::steady_clock::now()-start_time).count()>limit_sec){timed_out=true;return false;}int v=choose_var();if(v<0)return verify();vector<pair<int,int>>vals;for(int a=dom[v];a;){int b=a&-a;a-=b;int score=0;for(int j=0;j<4;j++)for(int i=0;i<K;i++)if(dom[clq[vclq[v][j]][i]]&b)score++;vals.push_back({-score,b});}sort(vals.begin(),vals.end());for(auto [s,b]:vals){if(!(dom[v]&b))continue;size_t m=trail.size();deque<int>q;setdom(v,b,q);if(propagate(q)&&dfs())return true;undo(m);backtracks++;if(timed_out)return false;size_t m2=trail.size();deque<int>q2;unsigned short nd=dom[v]&~b;if(!nd){undo(m2);return false;}setdom(v,nd,q2);if(!propagate(q2)){undo(m2);return false;}}return false;}
int main(int argc,char**argv){if(argc<3){cerr<<"usage: solver seconds cliques.txt\n";return 2;}limit_sec=atof(argv[1]);ifstream f(argv[2]);if(!f)return 3;vector<vector<int>>inc(N);for(int c=0;c<C;c++)for(int i=0;i<K;i++){f>>clq[c][i];inc[clq[c][i]].push_back(c);}for(int v=0;v<N;v++){if(inc[v].size()!=4)return 4;for(int j=0;j<4;j++)vclq[v][j]=inc[v][j];dom[v]=ALL;}deque<int>q;for(int i=0;i<K;i++)setdom(clq[0][i],1u<<i,q);start_time=chrono::steady_clock::now();bool sat=propagate(q)&&dfs();double sec=chrono::duration<double>(chrono::steady_clock::now()-start_time).count();cout<<"status "<<(sat?"SAT":timed_out?"UNKNOWN":"UNSAT")<<"\n"<<"nodes "<<nodes<<" backtracks "<<backtracks<<" propagations "<<propagations<<" seconds "<<fixed<<setprecision(6)<<sec<<"\n";if(sat){cout<<"coloring";for(int v=0;v<N;v++)cout<<" "<<__builtin_ctz(dom[v]);cout<<"\n";}return sat?10:timed_out?0:20;}
