#include <algorithm>
#include <array>
#include <bit>
#include <cstdint>
#include <fstream>
#include <iostream>
#include <vector>
struct Bits{uint64_t x[4];};
static inline bool has(const Bits&a,int i){return(a.x[i>>6]>>(i&63))&1;}
static inline void clr(Bits&a,int i){a.x[i>>6]&=~(1ULL<<(i&63));}
static inline int cntand(const Bits&a,const Bits&b){return std::popcount(a.x[0]&b.x[0])+std::popcount(a.x[1]&b.x[1])+std::popcount(a.x[2]&b.x[2])+std::popcount(a.x[3]&b.x[3]);}
std::array<uint64_t,240> col;std::array<Bits,45> inc;uint64_t C[240][5];std::vector<uint8_t> ambiguous;int support_[8],target;uint64_t nodes,sol,newmarks;
static inline uint64_t rank4(int a,int b,int c,int d){if(a>b)std::swap(a,b);if(c>d)std::swap(c,d);if(a>c){std::swap(a,c);std::swap(b,d);}if(b>c)std::swap(b,c);if(c>d)std::swap(c,d);--a;--b;--c;--d;return C[a][1]+C[b][2]+C[c][3]+C[d][4];}
void markleaf(){sol++;std::array<int,8>s{};for(int i=0;i<target;i++)s[i]=support_[i];std::sort(s.begin(),s.begin()+target);bool in[240]={};for(int i=0;i<target;i++)in[s[i]]=true;std::vector<int>x,o;for(int i=1;i<target;i++)x.push_back(s[i]);for(int i=1;i<240;i++)if(!in[i])o.push_back(i);if(target==4){for(int q:x)for(int a=0;a<(int)o.size()-2;a++)for(int b=a+1;b<(int)o.size()-1;b++)for(int c=b+1;c<(int)o.size();c++){auto r=rank4(q,o[a],o[b],o[c]);if(!ambiguous[r])ambiguous[r]=1,newmarks++;}}else if(target==6){for(int a=0;a<4;a++)for(int b=a+1;b<5;b++)for(int c=0;c<(int)o.size()-1;c++)for(int d=c+1;d<(int)o.size();d++){auto r=rank4(x[a],x[b],o[c],o[d]);if(!ambiguous[r])ambiguous[r]=1,newmarks++;}}else{for(int a=0;a<5;a++)for(int b=a+1;b<6;b++)for(int c=b+1;c<7;c++)for(int q:o){auto r=rank4(x[a],x[b],x[c],q);if(!ambiguous[r])ambiguous[r]=1,newmarks++;}}}
void dfs(uint64_t odd,Bits avail,int used){nodes++;int rem=target-used;if(!rem){if(!odd)markleaf();return;}int no=std::popcount(odd);if(no>3*rem||((no&1)!=(rem&1)))return;if(odd){int vb=-1,cb=999;for(uint64_t z=odd;z;z&=z-1){int v=std::countr_zero(z),c=cntand(avail,inc[v]);if(!c)return;if(c<cb){cb=c;vb=v;}}Bits work=avail;for(int e=0;e<240;e++)if(has(work,e)&&has(inc[vb],e)){Bits next=work;clr(next,e);support_[used]=e;dfs(odd^col[e],next,used+1);clr(work,e);}}else{Bits work=avail;for(int e=0;e<240;e++)if(has(work,e)){Bits next=work;clr(next,e);support_[used]=e;dfs(col[e],next,used+1);clr(work,e);}}}
int main(int argc,char**argv){if(argc<4){std::cerr<<"usage: worker syndrome_columns degree.bin output.json\n";return 2;}std::ifstream in(argv[1]);for(auto &x:col)if(!(in>>x))return 3;for(auto &b:inc)b={{0,0,0,0}};for(int e=0;e<240;e++)for(int v=0;v<45;v++)if((col[e]>>v)&1)inc[v].x[e>>6]|=1ULL<<(e&63);for(int n=0;n<240;n++){C[n][0]=1;for(int k=1;k<=4;k++)C[n][k]=n?C[n-1][k]+C[n-1][k-1]:0;}uint64_t N=C[239][4];std::vector<uint16_t>deg(N);std::ifstream db(argv[2],std::ios::binary);db.read((char*)deg.data(),deg.size()*2);if(!db)return 4;ambiguous.assign(N,0);for(uint64_t i=0;i<N;i++)ambiguous[i]=deg[i]>0;std::array<uint64_t,3>expect={9,240,14139};for(int z=0;z<3;z++){target=4+2*z;nodes=sol=newmarks=0;support_[0]=0;Bits a={{~0ULL,~0ULL,~0ULL,(1ULL<<48)-1}};clr(a,0);dfs(col[0],a,1);if(sol!=expect[z])return 5+z;}std::vector<uint64_t>lower;lower.reserve(2276000);for(int i=0;i<240;i++)lower.push_back(col[i]);for(int i=0;i<240;i++)for(int j=i+1;j<240;j++)for(int k=j+1;k<240;k++)lower.push_back(col[i]^col[j]^col[k]);std::sort(lower.begin(),lower.end());lower.erase(std::unique(lower.begin(),lower.end()),lower.end());std::vector<uint64_t>key(N);uint64_t q=0;for(int a=1;a<237;a++)for(int b=a+1;b<238;b++)for(int c=b+1;c<239;c++)for(int d=c+1;d<240;d++){uint64_t syn=col[0]^col[a]^col[b]^col[c]^col[d];key[q++]=(syn<<1)|(!ambiguous[rank4(a,b,c,d)]);}std::sort(key.begin(),key.end());uint64_t chart=0,unique=0,external=0;for(uint64_t i=0;i<N;){uint64_t syn=key[i]>>1,j=i+1;while(j<N&&(key[j]>>1)==syn)j++;bool low=std::binary_search(lower.begin(),lower.end(),syn);if(!low&&j-i==1){chart++;if(key[i]&1)unique++;else external++;}i=j;}if(chart!=62359342||unique!=31899289)return 9;std::ofstream o(argv[3]);o<<"{\"status\":\"PASS\",\"fixed_chart_singleton\":"<<chart<<",\"fixed_external_collision\":"<<external<<",\"fixed_unique\":"<<unique<<",\"global_unique\":"<<unique*48<<",\"global_ambiguous\":"<<(130809308-unique)*48<<",\"partition\":"<<84201264ULL+unique*48+(130809308-unique)*48<<"}\n";std::cout<<"PASS exact U5="<<unique*48<<"\n";}
