#include <algorithm>
#include <array>
#include <bit>
#include <cstdint>
#include <cstdlib>
#include <fstream>
#include <functional>
#include <iostream>
#include <queue>
#include <string>
#include <sys/mman.h>
#include <fcntl.h>
#include <unistd.h>
#include <vector>
using U=std::uint64_t;struct Bits{U x[4];};struct Rec{U syn,rank;};
static std::array<U,240> col;static std::array<Bits,45> inc;static U C[240][6];static int support_[12],target_;static U leaves_;static std::ofstream support_out;
static inline bool has(const Bits&a,int i){return(a.x[i>>6]>>(i&63))&1ULL;}static inline void clr(Bits&a,int i){a.x[i>>6]&=~(1ULL<<(i&63));}static inline int cntand(const Bits&a,const Bits&b){return std::popcount(a.x[0]&b.x[0])+std::popcount(a.x[1]&b.x[1])+std::popcount(a.x[2]&b.x[2])+std::popcount(a.x[3]&b.x[3]);}
static void prep(const char*p){std::ifstream f(p);for(auto&x:col)if(!(f>>x))std::exit(3);for(auto&b:inc)b={{0,0,0,0}};for(int e=0;e<240;e++)for(int v=0;v<45;v++)if((col[e]>>v)&1ULL)inc[v].x[e>>6]|=1ULL<<(e&63);for(int n=0;n<240;n++){C[n][0]=1;for(int k=1;k<=5;k++)C[n][k]=n?C[n-1][k]+C[n-1][k-1]:0;}}
static inline U rank5(std::array<int,5>a){std::sort(a.begin(),a.end());for(int&i:a)--i;return C[a[0]][1]+C[a[1]][2]+C[a[2]][3]+C[a[3]][4]+C[a[4]][5];}
static void dfs(U odd,Bits avail,int used){int rem=target_-used;if(!rem){if(!odd){for(int i=0;i<target_;i++){std::uint8_t x=support_[i];support_out.write((char*)&x,1);}leaves_++;}return;}int no=std::popcount(odd);if(no>3*rem||((no&1)!=(rem&1)))return;if(odd){int vb=-1,cb=999;for(U z=odd;z;z&=z-1){int v=std::countr_zero(z),c=cntand(avail,inc[v]);if(!c)return;if(c<cb){cb=c;vb=v;}}Bits work=avail;for(int e=0;e<240;e++)if(has(work,e)&&has(inc[vb],e)){Bits next=work;clr(next,e);support_[used]=e;dfs(odd^col[e],next,used+1);clr(work,e);}}else{Bits work=avail;for(int e=0;e<240;e++)if(has(work,e)){Bits next=work;clr(next,e);support_[used]=e;dfs(col[e],next,used+1);clr(work,e);}}}
static int root_pivot(U odd,const Bits&a){int vb=-1,cb=999;for(U z=odd;z;z&=z-1){int v=std::countr_zero(z),c=cntand(a,inc[v]);if(!c)return-1;if(c<cb){cb=c;vb=v;}}return vb;}
static void choose_rec(const std::vector<int>&s,int n,int at,std::vector<int>&c,const std::function<void(const std::vector<int>&)>&fn){if(!n){fn(c);return;}for(int i=at;i+n<=(int)s.size();i++){c.push_back(s[i]);choose_rec(s,n-1,i+1,c,fn);c.pop_back();}}
static std::vector<std::string>read_list(const char*p){std::ifstream f(p);std::vector<std::string>v;std::string s;while(std::getline(f,s))if(!s.empty())v.push_back(s);return v;}
int main(int ac,char**av){if(ac<2)return 2;std::string m=av[1];
 if(m=="lower_chunk"){if(ac!=5)return 2;prep(av[2]);int a=std::atoi(av[4]);std::vector<U>v;if(a<0){v.push_back(0);for(int i=0;i<240;i++)for(int j=i+1;j<240;j++)v.push_back(col[i]^col[j]);}else for(int b=a+1;b<238;b++)for(int c=b+1;c<239;c++)for(int d=c+1;d<240;d++)v.push_back(col[a]^col[b]^col[c]^col[d]);std::sort(v.begin(),v.end());v.erase(std::unique(v.begin(),v.end()),v.end());std::ofstream o(av[3],std::ios::binary);o.write((char*)v.data(),v.size()*8);return 0;}
 if(m=="chart_chunk"){if(ac!=6)return 2;prep(av[2]);int a=std::atoi(av[4]),b=std::atoi(av[5]);std::vector<Rec>v;for(int c=b+1;c<238;c++)for(int d=c+1;d<239;d++)for(int e=d+1;e<240;e++)v.push_back({col[0]^col[a]^col[b]^col[c]^col[d]^col[e],rank5({a,b,c,d,e})});std::sort(v.begin(),v.end(),[](auto&x,auto&y){return x.syn<y.syn||(x.syn==y.syn&&x.rank<y.rank);});std::ofstream o(av[3],std::ios::binary);o.write((char*)v.data(),v.size()*sizeof(Rec));return 0;}
 if(m=="codeword_shard"){if(ac!=6)return 2;prep(av[2]);target_=std::atoi(av[4]);int slot=std::atoi(av[5]);Bits a={{~0ULL,~0ULL,~0ULL,(1ULL<<48)-1}};clr(a,0);U odd=col[0];int vb=root_pivot(odd,a);std::vector<int>cand;for(int e=0;e<240;e++)if(has(a,e)&&has(inc[vb],e))cand.push_back(e);if(slot<0||slot>=(int)cand.size())return 5;Bits work=a;for(int j=0;j<slot;j++)clr(work,cand[j]);int e=cand[slot];Bits next=work;clr(next,e);support_[0]=0;support_[1]=e;support_out.open(av[3],std::ios::binary);dfs(odd^col[e],next,2);std::cerr<<"leaves="<<leaves_<<"\n";return 0;}
 if(m=="init_bitmap"){U bits=6230484547ULL,bytes=((bits+63)/64)*8;int fd=open(av[2],O_CREAT|O_TRUNC|O_RDWR,0644);if(fd<0||ftruncate(fd,bytes))return 3;close(fd);return 0;}
 if(m=="mark_chunk"){if(ac!=6)return 2;prep(av[2]);int w=std::atoi(av[4]);int fd=open(av[5],O_RDWR);U bits=C[239][5],bytes=((bits+63)/64)*8;auto*map=(U*)mmap(nullptr,bytes,PROT_READ|PROT_WRITE,MAP_SHARED,fd,0);std::ifstream f(av[3],std::ios::binary);std::vector<std::uint8_t>buf(w);while(f.read((char*)buf.data(),w)){std::vector<int>S(buf.begin(),buf.end()),inS,out;std::sort(S.begin(),S.end());bool in[240]={};for(int x:S){in[x]=true;if(x)inS.push_back(x);}for(int x=1;x<240;x++)if(!in[x])out.push_back(x);std::vector<int>A,B;choose_rec(inS,w/2-1,0,A,[&](auto&aa){choose_rec(out,6-w/2,0,B,[&](auto&bb){std::array<int,5>e{};int q=0;for(int x:aa)e[q++]=x;for(int x:bb)e[q++]=x;U r=rank5(e);__atomic_fetch_or(map+(r>>6),1ULL<<(r&63),__ATOMIC_RELAXED);});});}msync(map,bytes,MS_ASYNC);munmap(map,bytes);close(fd);return 0;}
 if(m=="merge_chart"){auto fs=read_list(av[2]);struct S{Rec r;int f;};struct Q{bool operator()(S const&a,S const&b)const{return a.r.syn>b.r.syn||(a.r.syn==b.r.syn&&a.r.rank>b.r.rank);}};std::vector<std::ifstream>in;for(auto&s:fs)in.emplace_back(s,std::ios::binary);std::priority_queue<S,std::vector<S>,Q>q;for(int i=0;i<(int)in.size();i++){Rec r;if(in[i].read((char*)&r,sizeof r))q.push({r,i});}std::ofstream o(av[3],std::ios::binary);while(!q.empty()){auto s=q.top();q.pop();o.write((char*)&s.r,sizeof s.r);Rec r;if(in[s.f].read((char*)&r,sizeof r))q.push({r,s.f});}return 0;}
 if(m=="merge_u64"){auto fs=read_list(av[2]);struct S{U x;int f;};struct Q{bool operator()(S const&a,S const&b)const{return a.x>b.x;}};std::vector<std::ifstream>in;for(auto&s:fs)in.emplace_back(s,std::ios::binary);std::priority_queue<S,std::vector<S>,Q>q;for(int i=0;i<(int)in.size();i++){U x;if(in[i].read((char*)&x,8))q.push({x,i});}std::ofstream o(av[3],std::ios::binary);bool h=false;U last=0;while(!q.empty()){auto s=q.top();q.pop();if(!h||s.x!=last){o.write((char*)&s.x,8);last=s.x;h=true;}U x;if(in[s.f].read((char*)&x,8))q.push({x,s.f});}return 0;}
 if(m=="count"){std::ifstream ch(av[2],std::ios::binary),lo(av[3],std::ios::binary);int fd=open(av[4],O_RDONLY);U bits=6230484547ULL,bytes=((bits+63)/64)*8;auto*map=(const U*)mmap(nullptr,bytes,PROT_READ,MAP_SHARED,fd,0);U low=0;bool hl=bool(lo.read((char*)&low,8));Rec r;if(!ch.read((char*)&r,sizeof r))return 4;U groups=0,single=0,unique=0;while(ch){U syn=r.syn,n=0,rank=0;do{n++;rank=r.rank;}while(ch.read((char*)&r,sizeof r)&&r.syn==syn);while(hl&&low<syn)hl=bool(lo.read((char*)&low,8));if(n==1&&!(hl&&low==syn)){single++;if(((map[rank>>6]>>(rank&63))&1ULL)==0)unique++;}groups++;if(!ch)break;}std::ofstream o(av[5]);o<<"{\"status\":\"PASS\",\"syndrome_groups\":"<<groups<<",\"fixed_chart_singleton_nonlower\":"<<single<<",\"fixed_global_unique\":"<<unique<<",\"global_U6\":"<<unique*40<<"}\n";return 0;}return 2;}
