import Mathlib

/-!
# Pass 565: native fifth-cyclotomic order scaffold

This file constructs the algebraic order generated by a root of the shifted
fifth-cyclotomic polynomial using `AdjoinRoot`.  It deliberately stops before
claiming that the quotient has already been completed to `Q_5(zeta_5)`.
-/

open Polynomial

namespace W33.Pass565

/-- The shifted fifth-cyclotomic polynomial in the uniformizer coordinate. -/
def shiftedPhiFive : Polynomial ℤ :=
  X ^ 4 - C 5 * X ^ 3 + C 10 * X ^ 2 - C 10 * X + C 5

/-- The integral algebraic order `Z[lambda]/(shiftedPhiFive)`. -/
abbrev CyclotomicFiveOrder := AdjoinRoot shiftedPhiFive

/-- The distinguished class of `X`, representing `lambda = 1-zeta_5`. -/
noncomputable def lambdaBar : CyclotomicFiveOrder :=
  AdjoinRoot.root shiftedPhiFive

/-- Evaluation of the shifted polynomial agrees with the expected quartic. -/
theorem shiftedPhiFive_eval (x : ℤ) :
    shiftedPhiFive.eval x = x ^ 4 - 5 * x ^ 3 + 10 * x ^ 2 - 10 * x + 5 := by
  simp [shiftedPhiFive]
  ring

/-- The translated polynomial is monic of degree four. -/
theorem shiftedPhiFive_monic : shiftedPhiFive.Monic := by
  simp [shiftedPhiFive]

/-- The native order is inhabited. -/
theorem cyclotomicFiveOrder_nonempty : Nonempty CyclotomicFiveOrder := by
  exact ⟨0⟩

/-- Data still required to turn the native order into the completed local field.
The construction is explicit about the remaining mathematical boundary. -/
structure CompletionInterface where
  completedCarrier : Type*
  embedOrder : CyclotomicFiveOrder → completedCarrier
  residue : completedCarrier → ZMod 5
  lambdaImage : completedCarrier
  lambda_compatibility : embedOrder lambdaBar = lambdaImage

end W33.Pass565
