import Mathlib

namespace W33.Pass806

/-!
# The two-branch gluing theorem (arithmetic core)

For an integral operator `S` with `S (S - c) = 0`, written in a basis adapting
the saturated `c`-eigenlattice as `S = [[c•I, Y], [0, 0]]`, the gluing of the two
saturated eigenlattices is

  `ℤⁿ / (L_c ⊕ L_0) = image (Y mod c) ≅ ⨁ ᵢ ℤ / (c / gcd c dᵢ)`,

where the `dᵢ` are the Smith invariants of `Y`.  The proof has two halves: a
reduction to Smith normal form, where unimodular `U`, `V` stay invertible mod `c`
so `image (U D V mod c) ≅ image (D mod c)`; and the evaluation of the image of a
*diagonal* matrix, which is the direct sum of the cyclic groups generated by each
`dᵢ` in `ZMod c`.

This file formalizes the second half — the part carrying the actual arithmetic of
the formula — together with the two structural facts used throughout the
deformation arc:

* every cyclic factor of the gluing divides the conductor `c`;
* a factor is the *full* conductor `ℤ/c` exactly when `gcd c dᵢ = 1`.

The first is why `c` is an invariant of the abstract order, while the number of
full-conductor summands stays a property of the realization — `(ℤ/4)^66` for the
cycle lattice, `(ℤ/2)^{(q-1)²/2}` for the flat block, where no `dᵢ` is coprime to
the conductor at all.
-/

variable {c : ℕ}

/-- The cyclic subgroup generated by `d` in `ZMod c` has order `c / gcd c d`.
This is the single-invariant case of the gluing formula: the contribution of one
Smith invariant `d` at conductor `c`. -/
theorem addOrderOf_natCast_zmod (hc : 0 < c) (d : ℕ) :
    addOrderOf ((d : ZMod c)) = c / Nat.gcd c d := by
  simpa using ZMod.addOrderOf_coe d hc.ne'

/-- The conductor annihilates the gluing: in `ZMod c` every element is killed by
`c`, so each cyclic factor divides `c`. -/
theorem conductor_annihilates (x : ZMod c) : (c : ℕ) • x = 0 := by
  rw [nsmul_eq_mul, ZMod.natCast_self, zero_mul]

/-- A Smith invariant coprime to the conductor contributes a *full* `ℤ/c`
summand: `d` generates all of `ZMod c` exactly when `gcd c d = 1`. -/
theorem full_conductor_iff_coprime (hc : 0 < c) (d : ℕ) :
    addOrderOf ((d : ZMod c)) = c ↔ Nat.gcd c d = 1 := by
  rw [addOrderOf_natCast_zmod hc d, Nat.div_eq_self]
  constructor
  · rintro (h | h)
    · omega
    · exact h
  · intro h
    exact Or.inr h

/-- A Smith invariant divisible by the conductor contributes nothing. -/
theorem trivial_of_conductor_dvd (hc : 0 < c) {d : ℕ} (h : c ∣ Nat.gcd c d) :
    addOrderOf ((d : ZMod c)) = 1 := by
  rw [addOrderOf_natCast_zmod hc d]
  have hle : Nat.gcd c d ≤ c := Nat.le_of_dvd hc (Nat.gcd_dvd_left c d)
  have hge : c ≤ Nat.gcd c d :=
    Nat.le_of_dvd (Nat.gcd_pos_of_pos_left d hc) h
  rw [le_antisymm hle hge, Nat.div_self hc]

end W33.Pass806
