import W33.Pass586CyclotomicLocalizedDVR
import Mathlib.RingTheory.DedekindDomain.Dvr

/-!
# Pass 591: Dedekind-to-DVR closure for the fifth-cyclotomic localization

The arithmetic owner certifies that the shifted fifth-cyclotomic order has the
same discriminant `5^3` as the cyclotomic field, hence index one in the ring of
integers. This file isolates the final generic Mathlib step: once that concrete
presentation is registered as a Dedekind domain, localization at the nonzero
prime generated by `lambdaBar` is a DVR.
-/

namespace W33.Pass591

-- Pass581 owns `uniformizerIdeal`; without it the dot notation below cannot
-- resolve and reports `Unknown identifier uniformizerIdeal.IsPrime`.
open W33.Pass570 W33.Pass575 W33.Pass581 W33.Pass586

noncomputable section

/-- Mathlib's Dedekind localization theorem supplies the desired DVR instance. -/
noncomputable def localizedCyclotomicFiveOrderIsDVR
    [IsDomain CyclotomicFiveOrder]
    [IsDedekindDomain CyclotomicFiveOrder]
    [uniformizerIdeal.IsPrime]
    -- `hλ` is not a legal identifier: Lean 4 reserves `λ` as the lambda token.
    (hlam : uniformizerIdeal ≠ ⊥) :
    IsDiscreteValuationRing LocalCyclotomicFiveOrder :=
  IsLocalization.AtPrime.isDiscreteValuationRing_of_dedekind_domain
    CyclotomicFiveOrder hlam LocalCyclotomicFiveOrder

/-- The exact ramification relation already proved in the localized order. -/
theorem localized_lambda_pow_four :
    localLambda ^ 4 =
      algebraMap CyclotomicFiveOrder LocalCyclotomicFiveOrder
          (AdjoinRoot.of shiftedPhiFive 5) * unitFactor :=
  local_ramification_relation

/-- Explicit remaining presentation-level input for the index-one ring-of-integers identification. -/
structure ConcreteMaximalOrderCertificate : Prop where
  order_is_domain : IsDomain CyclotomicFiveOrder
  order_is_dedekind : IsDedekindDomain CyclotomicFiveOrder
  lambda_prime : uniformizerIdeal.IsPrime
  lambda_ne_bot : uniformizerIdeal ≠ ⊥

end

end W33.Pass591
