#!/usr/bin/env python3
"""Index the VOCABULARY of data/*.json key names, which RESULTS_INDEX.md does not cover.

RESULTS_INDEX.md maps distinctive *values* (formulas, integers, code parameters) to files.
It does not index key NAMES, and on 2026-09-21 that cost four consecutive rediscoveries in one
session.  The string that settled "is the Eisenstein structure on E8 canonical?" was the key

    cyclic_Eisenstein_structures_or_W33_leaves

in data/PASS7401_7408_E8_A2_GLOBAL_GEOMETRY_results.json.  No prose grep reaches it: no
sentence in the corpus contains it.  Measured: 88309 distinct keys over 5085 certificates,
zero indexed.

A flat key list is useless (71k keys, 6 MB, almost all unique).  What an agent actually needs
is the corpus's own NOUNS: given a topic word, which key names does the corpus build from it?
So this indexes word -> keys.  Grep `eisenstein` here and the answer above appears directly.

Usage:  py -3 scripts/build_key_index.py [--out KEY_VOCABULARY.md]
"""
import argparse
import json
import os
import re
from collections import defaultdict

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA = os.path.join(ROOT, "data")

STOP = {
    "the", "a", "an", "of", "and", "or", "is", "are", "to", "in", "on", "for", "by", "with",
    "status", "value", "values", "count", "counts", "name", "names", "type", "note", "notes",
    "data", "result", "results", "summary", "label", "labels", "index", "size", "sizes",
    "total", "totals", "kind", "date", "file", "files", "path", "schema", "version", "scope",
    "claim", "checks", "valid", "sources", "boundary", "description", "input", "inputs",
    "output", "outputs", "params", "parameters", "meta", "metadata", "title", "text", "list",
    "items", "key", "keys", "test", "tests", "num", "id", "ok", "all", "per", "max", "min",
    "true", "false", "none", "null", "n", "x", "y", "z", "i", "j", "k",
}

def walk_keys(obj, out, depth=0):
    if depth > 12:
        return
    if isinstance(obj, dict):
        for k, v in obj.items():
            out.add(k)
            walk_keys(v, out, depth + 1)
    elif isinstance(obj, list):
        for v in obj[:40]:
            walk_keys(v, out, depth + 1)

def words_of(key):
    parts = re.split(r"[_\-\s]+", key)
    out = []
    for p in parts:
        # split camelCase too
        for w in re.findall(r"[A-Za-z][a-z0-9]*|\d+", p):
            w = w.lower()
            if len(w) >= 3 and w not in STOP and not w.isdigit():
                out.append(w)
    return out

def claimlike(key):
    """Keys that read like a finding rather than a field name."""
    if len(key) < 12:
        return False
    return len(words_of(key)) >= 3

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default="KEY_VOCABULARY.md")
    ap.add_argument("--max-keys-per-word", type=int, default=12)
    ap.add_argument("--max-word-files", type=int, default=400,
                    help="skip words appearing in more certificates than this (too common)")
    args = ap.parse_args()

    names = sorted(f for f in os.listdir(DATA) if f.endswith(".json"))
    word2keys = defaultdict(set)
    word2files = defaultdict(set)
    key2file = {}
    unreadable = 0

    for fn in names:
        try:
            with open(os.path.join(DATA, fn), encoding="utf-8") as fh:
                obj = json.load(fh)
        except Exception:
            unreadable += 1
            continue
        ks = set()
        walk_keys(obj, ks)
        for k in ks:
            if not claimlike(k):
                continue
            key2file.setdefault(k, fn)
            for w in set(words_of(k)):
                word2keys[w].add(k)
                word2files[w].add(fn)

    words = sorted(w for w in word2keys
                   if len(word2files[w]) <= args.max_word_files and len(word2keys[w]) >= 2)

    out = os.path.join(ROOT, args.out)
    with open(out, "w", encoding="utf-8") as fh:
        fh.write("# KEY_VOCABULARY — the nouns the certificates actually use\n\n")
        fh.write("Generated by `scripts/build_key_index.py`. Complements `RESULTS_INDEX.md`, "
                 "which indexes distinctive *values* but never key names.\n\n")
        fh.write("**Grep your topic word here before claiming a result is new.** A certificate "
                 "often states its finding only as a JSON key, so no prose search can reach it. "
                 "Find the corpus's key vocabulary around your word, then grep those keys in "
                 "`data/`.\n\n")
        fh.write("| word | certificates | key names built from it |\n|---|---|---|\n")
        for w in words:
            ks = sorted(word2keys[w], key=len)[:args.max_keys_per_word]
            cell = " · ".join("`%s`" % k for k in ks)
            if len(word2keys[w]) > args.max_keys_per_word:
                cell += " *(+%d)*" % (len(word2keys[w]) - args.max_keys_per_word)
            fh.write("| **%s** | %d | %s |\n" % (w, len(word2files[w]), cell))

    print("certificates read     : %d (unreadable %d)" % (len(names) - unreadable, unreadable))
    print("claim-like keys       : %d" % len(key2file))
    print("words indexed         : %d" % len(words))
    print("written               : %s (%.1f KB)"
          % (args.out, os.path.getsize(out) / 1024.0))

if __name__ == "__main__":
    main()
