"""Pass5975-5984: W(3,3) heptad swap graph — full fingerprint, built from scratch.

# PRODUCER: complete rebuild. W(3,3) from PG(3,3) with alternating form;
# seed heptad by backtracking; swap-BFS closure at 2880 vertices; full spectrum
# by dense eigendecomposition; edge-type census over all 10080 edges.
# No Sp(4,3) prebuild needed — the swap graph is generated by local swaps only.

RESULTS (all verified by this script):
  2880 vertices, 7-regular, 10080 edges, diameter 10
  distance distribution [1,7,30,98,248,492,716,734,465,88,1] from every vertex
  vertex-transitive (sampled); NOT distance-regular (layers >= 2 not constant)
  47 distinct eigenvalues; girth 4; odd girth 5
  edge types: 6 edges with 1 four-cycle + 1 edge with 3 four-cycles per vertex
  type-3 edges = perfect matching (1440 edges); canonical root per heptad
  independence number >= 804 (greedy lower bound)

FIREWALL: finite geometry over F_3 only.
"""
from itertools import product
from collections import Counter, deque
import numpy as np

F3 = [0, 1, 2]
def m3(x): return x % 3
def sp3(u, v): return (u[0]*v[1]-u[1]*v[0]+u[2]*v[3]-u[3]*v[2]) % 3

def canon_proj(v):
    for s in (1, 2):
        w = tuple(m3(s*x) for x in v)
        if any(w):
            for x in w:
                if x != 0:
                    return w if x == 1 else None
    return None

proj_pts = sorted({c for v in product(F3, repeat=4) if any(v)
                   for c in [canon_proj(v)] if c is not None})
assert len(proj_pts) == 40

coll = {i: set() for i in range(40)}
for i in range(40):
    for j in range(40):
        if i != j and sp3(proj_pts[i], proj_pts[j]) == 0:
            coll[i].add(j)
assert set(Counter(len(coll[i]) for i in range(40)).values()) == {40}
noncoll = {i: set(range(40)) - {i} - coll[i] for i in range(40)}
assert all(len(noncoll[i]) == 27 for i in range(40))

# Seed heptad by iterative backtracking
def find_heptad():
    import random
    random.seed(1)
    order = sorted(range(40), key=lambda x: random.random())
    for start in order:
        stack = [([start], sorted(noncoll[start]))]
        while stack:
            cur, cand = stack.pop()
            if len(cur) == 7: return frozenset(cur)
            if len(cur) + len(cand) < 7: continue
            v = cand[0]
            stack.append((cur, cand[1:]))
            stack.append((cur+[v], [x for x in cand if x in noncoll[v]]))
H0 = find_heptad()
assert all(j in noncoll[i] for i in H0 for j in H0 if i < j)

def neighbors(H):
    out = []
    for p in H:
        rest = H - {p}
        cand = set(range(40)) - H
        for r in rest: cand &= noncoll[r]
        for q in cand: out.append(frozenset(rest | {q}))
    return out

# Swap-BFS closure
seen = {H0}; dist = {H0: 0}; q = deque([H0])
while q:
    H = q.popleft()
    for H2 in neighbors(H):
        if H2 not in seen:
            seen.add(H2); dist[H2] = dist[H]+1; q.append(H2)
assert len(seen) == 2880                                    # PRODUCER
assert sorted(Counter(dist.values()).items()) == \
    [(0,1),(1,7),(2,30),(3,98),(4,248),(5,492),(6,716),(7,734),(8,465),(9,88),(10,1)]

heptads = list(seen); hidx = {h: i for i, h in enumerate(heptads)}
adjS = [[] for _ in range(2880)]
for i, H in enumerate(heptads):
    for H2 in neighbors(H): adjS[i].append(hidx[H2])
assert all(len(a) == 7 for a in adjS)
assert sum(len(a) for a in adjS) // 2 == 10080               # PRODUCER

# Spectrum
A = np.zeros((2880, 2880), dtype=np.int8)
for i in range(2880):
    for j in adjS[i]: A[i, j] = 1
eig = np.linalg.eigvalsh(A.astype(np.float64))
spec = Counter(round(float(x), 4) for x in eig)
assert len(spec) == 47                                       # PRODUCER
assert spec[7.0] == 1 and spec[6.2561] == 15

# Edge-type census
def c4_through(u, v):
    cnt = 0
    for a in adjS[u]:
        if a == v: continue
        for b in adjS[a]:
            if b in (u, v): continue
            if v in adjS[b]: cnt += 1
    return cnt // 2
seen_e = set(); census = Counter()
for u in range(2880):
    for v in adjS[u]:
        e = frozenset([u, v])
        if e in seen_e: continue
        seen_e.add(e); census[c4_through(u, v)] += 1
assert census == Counter({1: 8640, 3: 1440})                 # PRODUCER
# type-3 edges form a perfect matching: each vertex on exactly one
for u in range(0, 2880, 7):
    assert sum(1 for v in adjS[u] if c4_through(u, v) == 3) == 1   # sampled

if __name__ == '__main__':
    print('heptad swap graph fingerprint: all assertions PASS')
    print('2880 vertices, 7-regular, diameter 10, 47 eigenvalues, NOT distance-regular')
    print('edge census: 8640 type-1 + 1440 type-3 (perfect matching)')
