#!/usr/bin/env python3
"""Part CCCCCXCVII: explicit vertex-lift certificate for six-slot generators.

Starting from the CCCCCXCVI bridge payload, this module lifts each tomotope
slot generator to an explicit vertex permutation in S4 via the tetrahedral-edge
representation.
"""

from __future__ import annotations

import json
from dataclasses import asdict, dataclass
from itertools import permutations
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
BRIDGE_PATH = ROOT / "data" / "tomotope_six_kernel_s4_edge_bridge.json"
OUT_PATH = ROOT / "data" / "tomotope_six_kernel_vertex_lift.json"


def _compose(p: tuple[int, ...], q: tuple[int, ...]) -> tuple[int, ...]:
    return tuple(p[q[i]] for i in range(len(p)))


def _inverse(p: tuple[int, ...]) -> tuple[int, ...]:
    inv = [0] * len(p)
    for i, j in enumerate(p):
        inv[j] = i
    return tuple(inv)


def _edge_action_from_vertex(perm: tuple[int, ...]) -> tuple[int, ...]:
    edges = [(0, 1), (0, 2), (0, 3), (1, 2), (1, 3), (2, 3)]
    edge_index = {edge: idx for idx, edge in enumerate(edges)}
    image: list[int] = []
    for u, v in edges:
        uv = tuple(sorted((perm[u], perm[v])))
        image.append(edge_index[uv])
    return tuple(image)


def _slot_label_to_index(action: list[int] | list[str]) -> tuple[int, ...]:
    if action and isinstance(action[0], str):
        return tuple(int(str(x)[1:]) - 1 for x in action)
    return tuple(int(x) for x in action)


@dataclass(frozen=True)
class LiftSummary:
    generator_count: int
    vertex_group_order: int
    all_generators_lifted: bool
    all_lifts_verified_on_edges: bool


def build_vertex_lift() -> dict[str, Any]:
    bridge = json.loads(BRIDGE_PATH.read_text(encoding="utf-8"))
    conjugator = tuple(bridge["conjugator_to_tetrahedral_edge_model"])
    conjugator_inv = _inverse(conjugator)

    slot_generators = {
        name: _slot_label_to_index(action)
        for name, action in bridge["slot_generators"].items()
    }

    # Convert tomotope slot generators into tetrahedral-edge coordinates.
    tetra_edge_generators = {
        name: _compose(conjugator, _compose(g, conjugator_inv))
        for name, g in slot_generators.items()
    }

    # Build lookup edge-action -> vertex permutation in S4.
    edge_to_vertex: dict[tuple[int, ...], tuple[int, ...]] = {}
    for perm in permutations(range(4)):
        edge_perm = _edge_action_from_vertex(tuple(perm))
        edge_to_vertex[edge_perm] = tuple(perm)

    lifts: dict[str, list[int]] = {}
    all_lifted = True
    all_verified = True
    for name, edge_perm in tetra_edge_generators.items():
        vertex = edge_to_vertex.get(edge_perm)
        if vertex is None:
            all_lifted = False
            continue
        lifts[name] = list(vertex)
        all_verified = all_verified and (_edge_action_from_vertex(vertex) == edge_perm)

    # Group order generated by lifted vertex perms.
    lifted_vertex_perms = [tuple(v) for v in lifts.values()]
    identity = tuple(range(4))
    group: set[tuple[int, ...]] = {identity}
    frontier = [identity]
    while frontier:
        g = frontier.pop()
        for a in lifted_vertex_perms:
            h = _compose(a, g)
            if h not in group:
                group.add(h)
                frontier.append(h)

    summary = LiftSummary(
        generator_count=len(slot_generators),
        vertex_group_order=len(group),
        all_generators_lifted=(all_lifted and len(lifts) == len(slot_generators)),
        all_lifts_verified_on_edges=all_verified,
    )

    return {
        "summary": asdict(summary),
        "conjugator": list(conjugator),
        "tetrahedral_edge_generators": {k: list(v) for k, v in tetra_edge_generators.items()},
        "lifted_vertex_generators": lifts,
        "notes": (
            "Each tomotope slot generator is conjugated into tetrahedral-edge coordinates "
            "and matched to an explicit S4 vertex permutation whose induced edge action agrees exactly."
        ),
    }


def write_vertex_lift(path: Path = OUT_PATH) -> Path:
    payload = build_vertex_lift()
    path.write_text(json.dumps(payload, indent=2), encoding="utf-8")
    return path


def main() -> None:
    out = write_vertex_lift()
    print(f"Wrote {out}")


if __name__ == "__main__":
    main()
