"""Convert an external SAT solver model into the repo assignment JSON and verify.

Usage:
  python scripts/transport_cnf_model_to_assignment.py --cnf data/transport_seed0_seed0.cnf --model solver_output.txt --out data/transport_from_model_seed0.json --verify

The script reads the CNF file to extract the `c varmap: ...` JSON comment written
by the repo CNF exporter, parses the solver model (list of integer literals),
and writes an assignment mapping {quadrangle_index: branch_label} for positives.
If `--verify` is passed, the script will call the repo verifier to produce a
certificate JSON.
"""

from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
from pathlib import Path
from typing import Dict, Set


def parse_varmap_from_cnf(cnf_path: Path) -> Dict[str, list]:
    with cnf_path.open("r", encoding="utf-8") as fh:
        for _ in range(50):
            line = fh.readline()
            if not line:
                break
            if line.startswith("c varmap:"):
                txt = line.split("c varmap:", 1)[1].strip()
                return json.loads(txt)
    raise RuntimeError("varmap not found in CNF header; ensure CNF was generated by the exporter")


def parse_model_file(model_path: Path) -> Set[int]:
    txt = model_path.read_text(encoding="utf-8")
    # extract integer literals
    ints = re.findall(r"-?\d+", txt)
    vals = set()
    for s in ints:
        v = int(s)
        if v > 0:
            vals.add(v)
    return vals


def map_model_to_assignment(varmap: Dict[str, list], positives: Set[int]) -> Dict[int, int]:
    assignment: Dict[int, int] = {}
    for var_str, pair in varmap.items():
        vnum = int(var_str)
        if vnum in positives:
            idx, b = pair
            assignment[int(idx)] = int(b)
    return assignment


def run_verifier(result_path: Path) -> None:
    cmd = [sys.executable, str(Path(__file__).resolve().parents[1] / "scripts" / "transport_result_verify.py"), str(result_path)]
    proc = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
    out, err = proc.communicate()
    if proc.returncode != 0:
        print("Verifier failed:\n", err)
    else:
        print(out)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--cnf", required=True, help="Path to CNF file generated by exporter (contains c varmap: ...)")
    parser.add_argument("--model", required=True, help="Path to solver model output (text containing integer literals)")
    parser.add_argument("--out", required=False, help="Output JSON path for assignment", default=None)
    parser.add_argument("--verify", action="store_true", help="Run the repo verifier on the produced assignment JSON")
    args = parser.parse_args()

    cnf = Path(args.cnf)
    model = Path(args.model)
    if not cnf.exists():
        raise SystemExit(f"CNF file not found: {cnf}")
    if not model.exists():
        raise SystemExit(f"Model file not found: {model}")

    varmap = parse_varmap_from_cnf(cnf)
    positives = parse_model_file(model)
    assignment = map_model_to_assignment(varmap, positives)

    out_path = Path(args.out) if args.out else (Path("data") / f"transport_from_model_{cnf.stem}.json")
    out_path.parent.mkdir(parents=True, exist_ok=True)
    res = {"status": "found_from_model", "assignment": assignment}
    out_path.write_text(json.dumps(res, indent=2))
    print(json.dumps(res, indent=2))

    if args.verify:
        run_verifier(out_path)


if __name__ == "__main__":
    main()
