"""Pass 6003-6010 closure-ledger compatibility wrapper, corrected by Pass6017-6024.

The original file mixed exact finite arithmetic, formal avatars, unaudited prior
claims, and several statements now refuted by source-code replay. It is retained
as a tiered ledger, not a "full closure theorem".
"""
from fractions import Fraction

# Exact statements independently retained by the Pass6017-6024 audit.
retained_exact = [
    "W(3,3) is SRG(40,12,2,4)",
    "Yukawa block A has trace/det=(542,61200) and positive discriminant 48964",
    "Yukawa block B has trace/det=(982,137232) and positive discriminant 415396",
    "the formal 162x162 square-zero avatar with an inserted I_81 off-diagonal has rank 81",
    "the arithmetic identity (217/12)*780 = 14105",
]

# Source-code audit corrections. These must not be inherited as proved facts.
corrected = [
    "CE2 anchor-22 is NOT globally closed: only three imported witnesses were checked; the purported orbit weights were generated by a hard-coded rule on integer labels",
    "the claimed primitive generator (780,7944,62600,53979) has gcd 1, NOT 217",
    "the displayed Yukawa 2x2 blocks do NOT have (1,1) as an eigenvector, so the claimed generation-flag alignment is refuted",
    "the K3 glue is a FORMAL inserted matrix avatar; a genuine K3-side nonzero off-diagonal curvature witness remains open",
    "the Qiskit completed-avatar file is an encoding/search scaffold, not an implemented theorem oracle: its test circuit only applies Hadamards and measures",
    "Yang-Mills 1818 MeV, neutrino 0.0500 eV, inflation r=1/45, and 3.206 TeV scalar are ANSATZ/COMPARISON-ONLY per Pass5957-5964",
]

open_walls = [
    "CE2 anchor (22,*) full orbit from actual W33/CE2 data and automorphism action",
    "CE2 anchor (23,*) full orbit beyond the imported seed rows",
    "CE2 anchors (24,*)...(39,*)",
    "genuine K3-side nonzero off-diagonal curvature/glue witness",
    "K3-side realization of the Yukawa reduced blocks",
    "an actual proof, if any, of the proposed generation-family flag relation",
    "a circuit-computed oracle predicate rather than an assigned marked shard",
    "any physical observable map for the downgraded mass/inflation ansatze",
]

# Values retained only as bookkeeping/ansatz entries, NOT as predictions.
ansatz_numbers = {
    "m_nu3_eV": 0.0500,
    "Delta_YM_MeV": 1818,
    "r_inflation": Fraction(1,45),
    "m_scalar_GeV": 3206,
    "claimed_transport_gcd_SUPERSEDED": 217,
    "actual_gcd_of_780_7944_62600_53979": 1,
    "bridge_coefficient_formal_numerator": 351,
    "formal_glue_rank": 81,
    "middle_dim": 162,
}

print("="*72)
print("W33 BRIDGE LEDGER — CORRECTED CLAIM TIERS (Pass6017-6024)")
print("="*72)
print("\nRETAINED EXACT IN THIS AUDIT:")
for x in retained_exact:
    print("  [EXACT]", x)
print("\nCORRECTED / DOWNGRADED:")
for x in corrected:
    print("  [CORRECTED]", x)
print("\nOPEN WALLS:")
for x in open_walls:
    print("  [OPEN]", x)
print("\nANSATZ/BOOKKEEPING NUMBERS:")
for k,v in ansatz_numbers.items():
    print(f"  {k}: {v}")
print("\nCanonical audits: Pass5957-5964 and Pass6017-6024.")
