"""Q8 spectral-action master audit for W(3,3).

This module packages the current public Q8 claim surface into exact finite
arithmetic, then keeps nearby but non-identical claims in a separate boundary
packet.  The point is to make the master story executable without letting
legacy paper formulas, table shorthand, or frontier continuum interpretations
silently merge with the exact W(3,3) identities.
"""

from __future__ import annotations

from fractions import Fraction
from functools import lru_cache
from typing import Dict, Tuple

Q = 3
LAMBDA = 2
MU = 4
K = 12
V = 40
F = 24
E = V * K // 2
PHI3 = Q * Q + Q + 1
PHI4 = Q * Q + 1
PHI6 = Q * Q - Q + 1
PHI12 = Q**4 - Q**2 + 1
X = Fraction(Q, PHI3)


def frac_text(value: Fraction) -> str:
    """Return a stable display string for exact rational values."""
    if value.denominator == 1:
        return str(value.numerator)
    return f"{value.numerator}/{value.denominator}"


def symplectic_selection_holds(q: int) -> bool:
    """The public W(3,3) selector: (q+1)^2 = 2(q+1)(q-1)."""
    return (q + 1) ** 2 == 2 * (q + 1) * (q - 1)


def e8_root_selection_holds(q: int) -> bool:
    """E8 root-count selector: q^5 - q = 240."""
    return q**5 - q == 240


def atmospheric_sum_rule_polynomial(q: int) -> int:
    """PMNS atmospheric sum rule numerator over Phi_3(q)."""
    return q * (q - 3)


def fibonacci(n: int) -> int:
    a, b = 0, 1
    for _ in range(n):
        a, b = b, a + b
    return a


def fibonacci_square_hits(limit: int = 30) -> Tuple[int, ...]:
    """Return n <= limit satisfying F(n) = n^2."""
    return tuple(n for n in range(1, limit + 1) if fibonacci(n) == n * n)


def positive_integer_hits(predicate, limit: int = 20) -> Tuple[int, ...]:
    return tuple(q for q in range(1, limit + 1) if predicate(q))


@lru_cache(maxsize=1)
def q8_spectral_action_master_audit() -> Dict[str, object]:
    theta13_from_x = Fraction(2) * X * X / (9 * (1 - 2 * X))
    higgs_ratio_from_x = Fraction(2) * (1 - 2 * X) / (4 + X)
    sin_sq_of_arctan_x = X * X / (1 + X * X)
    omega_from_generator = 3 * X
    omega_from_cosmo_table = Fraction(V + 1, 60)
    alpha_paper_exact = Fraction(137, 1) + Fraction(880, 24445)

    exceptional_dimensions = {
        "dim_G2": {
            "formula": "2*Phi6",
            "value": 2 * PHI6,
            "target": 14,
        },
        "dim_F4": {
            "formula": "v+k",
            "value": V + K,
            "target": 52,
        },
        "dim_E6": {
            "formula": "2v-lambda",
            "value": 2 * V - LAMBDA,
            "target": 78,
        },
        "dim_E7": {
            "formula": "vq+Phi3",
            "value": V * Q + PHI3,
            "target": 133,
        },
        "dim_E8": {
            "formula": "E+2^q",
            "value": E + 2**Q,
            "target": 248,
        },
        "D_bosonic": {
            "formula": "f+lambda",
            "value": F + LAMBDA,
            "target": 26,
        },
        "D_super": {
            "formula": "k-lambda",
            "value": K - LAMBDA,
            "target": 10,
        },
        "D_M_theory": {
            "formula": "k-1",
            "value": K - 1,
            "target": 11,
        },
    }

    monster_nontrivial = (V + PHI6) * (V + K + PHI6) * (PHI12 - LAMBDA)
    leech_kissing = Q * E * (Q * PHI3 * PHI6)
    mckay_coefficient = monster_nontrivial + 1
    boundary_conflict_ids = (
        "omega_lambda_generator_vs_cosmo_table",
        "cabibbo_sin_vs_tan_shorthand",
        "legacy_pmns_theta12_formula",
        "so32_label_misprint",
        "alpha_table_rounding_or_formula_conflict",
    )
    claim_ledger_rows = (
        {
            "id": "q3_selector",
            "tier": "repo-exact finite",
            "claim": "q=3 is selected by the finite W(3,3) filters",
            "formula": "(q+1)^2=2(q+1)(q-1); q^5-q=240; q(q-3)=0; F(12)=12^2",
            "value": "q=3",
            "source_packet": "q3_selection_packet",
            "boundary_status": "theorem",
        },
        {
            "id": "master_variable",
            "tier": "repo-exact finite",
            "claim": "the promoted Q8 generator is x=sin^2(theta_W)",
            "formula": "x=q/Phi3=(lambda+1)/(k+1)",
            "value": frac_text(X),
            "source_packet": "master_variable_packet",
            "boundary_status": "generator; RG/dressing belongs outside the exact row",
        },
        {
            "id": "pmns_mixing_packet",
            "tier": "repo-exact finite",
            "claim": "the promoted PMNS packet is generated by x",
            "formula": "sin2(theta12)=4x/3; sin2(theta23)=1-2x; sin2(theta13)=2x^2/(9(1-2x))",
            "value": "4/13, 7/13, 2/91",
            "source_packet": "master_variable_packet",
            "boundary_status": "legacy theta12=3/10 is separated as a conflict",
        },
        {
            "id": "cabibbo_local_generator",
            "tier": "repo-exact finite",
            "claim": "the local Cabibbo generator is the same x",
            "formula": "tan(theta_C)=x",
            "value": frac_text(X),
            "source_packet": "master_variable_packet",
            "boundary_status": "do not rewrite as exact sin(theta_C)=x",
        },
        {
            "id": "spectral_action_ko_qcd",
            "tier": "repo-exact finite",
            "claim": "the product KO signature and QCD beta coefficient are fixed by q=3",
            "formula": "4+2q=10=2 mod 8; (11Nc-2Nf)/3=Phi6(3)",
            "value": "KO=10=2 mod 8; beta0=7",
            "source_packet": "spectral_action_arithmetic_packet",
            "boundary_status": "theorem",
        },
        {
            "id": "exceptional_dimension_packet",
            "tier": "repo-exact finite",
            "claim": "exceptional and string-critical dimensions are exact W(3,3) counts",
            "formula": "2Phi6, v+k, 2v-lambda, vq+Phi3, E+2^q, f+lambda, k-lambda, k-1",
            "value": "14, 52, 78, 133, 248, 26, 10, 11",
            "source_packet": "exceptional_dimension_packet",
            "boundary_status": "theorem",
        },
        {
            "id": "hierarchy_496_packet",
            "tier": "repo-exact finite",
            "claim": "the 496 hierarchy denominator has exact W(3,3) decompositions",
            "formula": "496=dim(SO32)=2*dim(E8)=2E+16",
            "value": "496",
            "source_packet": "hierarchy_packet",
            "boundary_status": "literal 2E+2dim(E8) is separated as a conflict",
        },
        {
            "id": "monster_leech_packet",
            "tier": "repo-exact finite",
            "claim": "the Monster and Leech coefficients factor through W(3,3) counts",
            "formula": "196883=(v+Phi6)(v+k+Phi6)(Phi12-lambda); 196884-196560=mu*q^4",
            "value": "196883, 196884, 196560, 324",
            "source_packet": "monster_leech_packet",
            "boundary_status": "theorem",
        },
        {
            "id": "alpha_inverse_formula",
            "tier": "boundary-explicit finite formula",
            "claim": "the paper alpha formula has a precise exact value",
            "formula": "137+880/24445",
            "value": frac_text(alpha_paper_exact),
            "source_packet": "boundary_conflicts.alpha_table_rounding_or_formula_conflict",
            "boundary_status": "not the legacy 137.036004 table shorthand",
        },
        {
            "id": "omega_lambda_cosmo_table",
            "tier": "dressed phenomenology",
            "claim": "the cosmology table value is distinct from the generator value 3x",
            "formula": "(v+1)/60 versus 3x",
            "value": f"{frac_text(omega_from_cosmo_table)} versus {frac_text(omega_from_generator)}",
            "source_packet": "boundary_conflicts.omega_lambda_generator_vs_cosmo_table",
            "boundary_status": "separate dressed cosmology row",
        },
        {
            "id": "q8_public_surfaces",
            "tier": "boundary-explicit source of truth",
            "claim": "paper and index claims must be read through this executable ledger",
            "formula": "exact finite rows first; dressed/frontier rows cannot overwrite them",
            "value": "claim ledger governs Q8 wording",
            "source_packet": "claim_ledger_packet",
            "boundary_status": "source-of-truth guardrail",
        },
    )
    claim_ledger_tiers = (
        "repo-exact finite",
        "boundary-explicit finite formula",
        "dressed phenomenology",
        "boundary-explicit source of truth",
        "frontier realization",
    )

    return {
        "source_scope": {
            "claim": "Q8 spectral action on M^4 x W(3,3) with one exact q=3 finite carrier",
            "status": "exact finite arithmetic audit with frontier and legacy boundaries separated",
            "action": "S = Tr(f(D^2/Lambda^2))",
            "product_dirac": "D = D_M tensor 1 + gamma_5 tensor D_F",
        },
        "w33_constants": {
            "q": Q,
            "lambda": LAMBDA,
            "mu": MU,
            "k": K,
            "v": V,
            "f": F,
            "E": E,
            "Phi3": PHI3,
            "Phi4": PHI4,
            "Phi6": PHI6,
            "Phi12": PHI12,
            "srg": (V, K, LAMBDA, MU),
        },
        "q3_selection_packet": {
            "symplectic_equation": "(q+1)^2 = 2(q+1)(q-1)",
            "symplectic_positive_integer_hits_1_to_20": positive_integer_hits(
                symplectic_selection_holds
            ),
            "e8_root_equation": "q^5 - q = 240",
            "e8_root_positive_integer_hits_1_to_20": positive_integer_hits(
                e8_root_selection_holds
            ),
            "atmospheric_sum_rule_polynomial": "q(q-3)",
            "atmospheric_positive_integer_hits_1_to_20": positive_integer_hits(
                lambda q: atmospheric_sum_rule_polynomial(q) == 0
            ),
            "fibonacci_square_hits_1_to_30": fibonacci_square_hits(),
            "nontrivial_fibonacci_square_hits_1_to_30": tuple(
                n for n in fibonacci_square_hits() if n != 1
            ),
        },
        "master_variable_packet": {
            "x": frac_text(X),
            "x_from_w33": {
                "q_over_Phi3": frac_text(Fraction(Q, PHI3)),
                "lambda_plus_1_over_k_plus_1": frac_text(Fraction(LAMBDA + 1, K + 1)),
            },
            "closures": {
                "sin2_theta_W": frac_text(X),
                "tan_theta_C": frac_text(X),
                "sin2_theta_12": frac_text(Fraction(4) * X / 3),
                "sin2_theta_23": frac_text(1 - 2 * X),
                "sin2_theta_13": frac_text(theta13_from_x),
                "mH2_over_v2": frac_text(higgs_ratio_from_x),
                "a2_over_a0": frac_text(Fraction(2, 1) / X - 4),
                "a4_over_a0": frac_text(Fraction(8, 1) / X + 2),
                "c6_over_a0": frac_text(Fraction(6, 1) / X),
                "c6_over_cEH_cont": frac_text(Fraction(9, 1) / X),
            },
        },
        "spectral_action_arithmetic_packet": {
            "internal_ko_dimension": 2 * Q,
            "product_ko_dimension": 4 + 2 * Q,
            "product_ko_dimension_mod_8": (4 + 2 * Q) % 8,
            "standard_model_ko_signature_mod_8": 2,
            "qcd_beta0": Fraction(11 * Q - 2 * (2 * Q), 3),
            "qcd_beta0_text": frac_text(Fraction(11 * Q - 2 * (2 * Q), 3)),
            "qcd_beta0_equals_Phi6": Fraction(11 * Q - 2 * (2 * Q), 3) == PHI6,
            "higgs_ratio_mH2_over_v2": frac_text(higgs_ratio_from_x),
        },
        "exceptional_dimension_packet": exceptional_dimensions,
        "hierarchy_packet": {
            "exponent_2Phi6": 2 * PHI6,
            "dim_SO32": 32 * 31 // 2,
            "dim_E8": exceptional_dimensions["dim_E8"]["value"],
            "exact_496_decompositions": {
                "2_dim_E8": 2 * exceptional_dimensions["dim_E8"]["value"],
                "2E_plus_16": 2 * E + 16,
                "SO32_adjoint": 32 * 31 // 2,
            },
            "hierarchy_expression": "1/(10^(2Phi6) * 496)",
            "hierarchy_denominator_without_power": 32 * 31 // 2,
        },
        "monster_leech_packet": {
            "monster_nontrivial_rep": monster_nontrivial,
            "monster_factorization": {
                "v_plus_Phi6": V + PHI6,
                "v_plus_k_plus_Phi6": V + K + PHI6,
                "Phi12_minus_lambda": PHI12 - LAMBDA,
            },
            "mckay_coefficient": mckay_coefficient,
            "leech_kissing": leech_kissing,
            "mckay_minus_leech": mckay_coefficient - leech_kissing,
            "mu_q4_gap": MU * Q**4,
        },
        "claim_ledger_packet": {
            "source_of_truth": "scripts/w33_q8_spectral_action_master_audit.py",
            "tier_order": claim_ledger_tiers,
            "row_count": len(claim_ledger_rows),
            "repo_exact_row_count": sum(
                row["tier"] == "repo-exact finite" for row in claim_ledger_rows
            ),
            "boundary_explicit_row_count": sum(
                row["tier"].startswith("boundary-explicit") for row in claim_ledger_rows
            ),
            "dressed_phenomenology_row_count": sum(
                row["tier"] == "dressed phenomenology" for row in claim_ledger_rows
            ),
            "frontier_row_count": sum(
                row["tier"] == "frontier realization" for row in claim_ledger_rows
            ),
            "rows": claim_ledger_rows,
            "conflict_ids": boundary_conflict_ids,
            "paper_index_guardrail": (
                "Use this ledger before reading public Q8 tables: alpha, "
                "Cabibbo sine/tangent, PMNS theta12, Omega_Lambda, and 496 "
                "labels have explicit boundary rows."
            ),
        },
        "boundary_conflicts": {
            "omega_lambda_generator_vs_cosmo_table": {
                "generator_formula": "Omega_Lambda = 3x",
                "generator_value": frac_text(omega_from_generator),
                "cosmo_table_formula": "(v+1)/60",
                "cosmo_table_value": frac_text(omega_from_cosmo_table),
                "equal": omega_from_generator == omega_from_cosmo_table,
            },
            "cabibbo_sin_vs_tan_shorthand": {
                "exact_generator_statement": "tan(theta_C) = x",
                "sin2_if_theta_C_is_arctan_x": frac_text(sin_sq_of_arctan_x),
                "x_squared": frac_text(X * X),
                "sin_theta_C_equals_x_is_exact": sin_sq_of_arctan_x == X * X,
            },
            "legacy_pmns_theta12_formula": {
                "promoted_value_mu_over_Phi3": frac_text(Fraction(MU, PHI3)),
                "legacy_value_q_over_k_minus_lambda": frac_text(
                    Fraction(Q, K - LAMBDA)
                ),
                "equal": Fraction(MU, PHI3) == Fraction(Q, K - LAMBDA),
            },
            "so32_label_misprint": {
                "exact_2E_plus_16": 2 * E + 16,
                "exact_2_dim_E8": 2 * exceptional_dimensions["dim_E8"]["value"],
                "literal_2E_plus_2_dim_E8": 2 * E
                + 2 * exceptional_dimensions["dim_E8"]["value"],
                "literal_equals_496": (
                    2 * E + 2 * exceptional_dimensions["dim_E8"]["value"] == 496
                ),
            },
            "alpha_table_rounding_or_formula_conflict": {
                "paper_exact_fraction": frac_text(alpha_paper_exact),
                "paper_exact_decimal_12": f"{float(alpha_paper_exact):.12f}",
                "index_q8_table_value": "137.036004",
                "same_as_index_q8_table_to_6_decimals": (
                    f"{float(alpha_paper_exact):.6f}" == "137.036004"
                ),
            },
        },
        "theorem": {
            "symplectic_equation_selects_q3": positive_integer_hits(
                symplectic_selection_holds
            )
            == (Q,),
            "e8_root_count_selects_q3": positive_integer_hits(e8_root_selection_holds)
            == (Q,),
            "atmospheric_sum_rule_selects_q3_among_positive_integers": (
                positive_integer_hits(lambda q: atmospheric_sum_rule_polynomial(q) == 0)
                == (Q,)
            ),
            "nontrivial_fibonacci_square_selector_is_12": tuple(
                n for n in fibonacci_square_hits() if n != 1
            )
            == (K,),
            "master_variable_closures_match_promoted_pmns_values": (
                Fraction(4) * X / 3 == Fraction(MU, PHI3)
                and 1 - 2 * X == Fraction(PHI6, PHI3)
                and theta13_from_x == Fraction(LAMBDA, PHI3 * PHI6)
            ),
            "spectral_action_ko_dimension_matches_sm_signature": ((4 + 2 * Q) % 8 == 2),
            "qcd_beta0_is_Phi6": Fraction(11 * Q - 2 * (2 * Q), 3) == PHI6,
            "exceptional_dimension_table_is_exact": all(
                row["value"] == row["target"] for row in exceptional_dimensions.values()
            ),
            "monster_and_leech_factorizations_are_exact": (
                monster_nontrivial == 196883
                and mckay_coefficient == 196884
                and leech_kissing == 196560
                and mckay_coefficient - leech_kissing == MU * Q**4
            ),
            "boundary_conflicts_are_explicit_not_absorbed": True,
        },
    }


if __name__ == "__main__":
    import json

    print(json.dumps(q8_spectral_action_master_audit(), indent=2))
