"""Pass 6361-6376: Sp(4,5) stabiliser exact computation scaffold.

The q=5 stabiliser is the next falsifiable step after the q=3 exact result.
This script:
1. Formalizes the Sp(4,5) BFS strategy mirroring the q=3 approach.
2. Records group order and BFS parameters.
3. Computes the exact calibration prediction from q=3.
4. States the falsifiable claim: |Stab(18-set)| divides |Sp(4,5)| = 1,344,000.
"""

import math
from fractions import Fraction

# === Group orders ===
Sp43_order = 51840
Sp45_order = 1344000

# q=3 proved: orbit index = 2880
orbit_index_q3 = 2880
stab_order_q3 = Sp43_order // orbit_index_q3  # = 18

# Calibration prediction for q=5:
# If orbit index scales as ~ q^4 (rough), then at q=5:
q3, q5 = 3, 5
scaled_index_q5 = orbit_index_q3 * (q5**4 // q3**4)  # rough
predicted_stab_q5 = Sp45_order // scaled_index_q5

print("=== Sp(4,5) Stabiliser Computation Scaffold ===")
print(f"|Sp(4,3)| = {Sp43_order}, |Sp(4,5)| = {Sp45_order}")
print(f"q=3 stabiliser order: {stab_order_q3} (PROVED)")
print(f"q=3 orbit index: {orbit_index_q3}")
print(f"Scaled orbit index estimate at q=5 (q^4 law): ~{scaled_index_q5}")
print(f"Predicted |Stab(18-set)| at q=5: ~{predicted_stab_q5}")
print()

# === BFS parameters ===
# Sp(4,5) is generated by symplectic transvections over F5.
# BFS on generators has complexity O(|Sp(4,5)|) = O(1.344e6).
# Memory: store visited elements as sets of tuples.
print("=== BFS Parameters ===")
print(f"|Sp(4,5)| = {Sp45_order:,}")
print(f"Estimated BFS time: ~10-30 minutes on a modern CPU (cf. q=3 was fast)")
print(f"BFS memory: ~200 MB for a hash-set of 1.344M 4x4 matrices over F5")
print()

# === Falsifiable claim ===
print("=== Falsifiable Claim ===")
print("Claim: |Stab(alpha(W(3,5)))| is small relative to |Sp(4,5)|.")
print(f"Specifically: orbit index >= 1000 (i.e. |Stab| <= {Sp45_order // 1000}).")
print("This is falsifiable by exact BFS on Sp(4,5).")
print()

# === Divisors of Sp(4,5) near predicted range ===
print("=== Divisors of |Sp(4,5)| = 1,344,000 ===")
divisors = [d for d in range(1, 201) if Sp45_order % d == 0]
print(f"Divisors up to 200: {divisors}")
print(f"q=3 stab order 18 is among these: {18 in divisors}")
print(f"Predicted ~{predicted_stab_q5} is a divisor: {Sp45_order % predicted_stab_q5 == 0 if predicted_stab_q5 > 0 else 'N/A'}")
print("\nSp(4,5) stabiliser scaffold: COMPLETE. Exact BFS pending.")
