#!/usr/bin/env bash
set -euo pipefail

bash tools/bt1340_run_extended_release_lock.sh
python tools/bt1378_verify_runtime_contract.py
python tools/bt1379_verify_s3_gauge_max2csp_spec.py
python tools/bt1380_verify_post_1377_bridge_index.py
python tools/bt1381_s3_gauge_global_solver_probe.py --restarts 20
python tools/bt1382_non_clifford_port_abi.py
python tools/bt1383_verify_runtime_frontier_integration.py
python tools/bt1384_export_s3_gauge_maxsat.py
python tools/bt1385_hesse_sic_t_port_abi.py
python tools/bt1388_hesse_sic_t_factory_model.py
python tools/bt1390_import_s3_maxsat_certificate.py
python tools/bt1391_hesse_sic_t_queue_model.py
python tools/bt1393_ladder_consistency_audit.py
python tools/bt1394_reduced_qutrit_demonstrator.py
python tools/bt1395_s3_maxsat_bound_pathway.py
python tools/bt1396_qutrit_quantum_erasure_readout.py
python tools/bt1397_verify_example_optimality_certificate.py
python tools/bt1400_qutrit_erasure_noise_sensitivity.py
python tools/bt1402_photonic_manuscript_runtime_frontier.py
python tools/bt1403_hesse_port_eraser_lift.py
python tools/bt1404_holonet_scope_microframe.py
python tools/bt1405_continuous_q6_path_router.py
python tools/bt1406_tomotope_body_edge_pulse_scheduler.py
python tools/bt1407_microframe_transaction_composer.py
python tools/bt1408_witting_contextual_communication_bridge.py
python tools/bt1409_witting_duplex_admission_scheduler.py
python -m pytest -q tests/test_bt1378_bt1380_runtime_contracts.py tests/test_bt1381_bt1383_runtime_frontier.py tests/test_bt1384_bt1386_maxsat_port_paper.py tests/test_bt1387_bt1389_runtime_release_lock.py tests/test_bt1390_bt1392_certificate_queue_workflow.py tests/test_bt1393_bt1395_audit_qutrit_maxsat.py tests/test_bt1396_bt1398_erasure_certificate_paper.py tests/test_bt1399_bt1401_pdf_noise_release.py tests/test_bt1402_photonic_manuscript_runtime_frontier.py tests/test_bt1403_hesse_port_eraser_lift.py tests/test_bt1404_holonet_scope_microframe.py tests/test_bt1405_continuous_q6_path_router.py tests/test_bt1406_tomotope_body_edge_pulse_scheduler.py tests/test_bt1407_microframe_transaction_composer.py tests/test_bt1408_witting_contextual_communication_bridge.py tests/test_bt1409_witting_duplex_admission_scheduler.py

echo "BT1389 runtime frontier release lock passed"
echo "BT1401 runtime frontier release lock passed"
echo "BT1402 runtime frontier release lock passed"
echo "BT1403 runtime frontier release lock passed"
echo "BT1404 runtime frontier release lock passed"
echo "BT1405 runtime frontier release lock passed"
echo "BT1406 runtime frontier release lock passed"
echo "BT1407 runtime frontier release lock passed"
echo "BT1408 runtime frontier release lock passed"
echo "BT1409 runtime frontier release lock passed"
