#!/usr/bin/env python3
"""Idempotently integrate Passes 2901--2907 and repair the canonical blueprint.

This is intentionally a rewrite pass rather than an append-only inserter.  It corrects
stale evidence language, separates part-specific measurements, repairs two geometry
misstatements, and inserts the new execution/readout architecture in the body.
"""
from __future__ import annotations

import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
INSERT = r"\input{analysis/BT2901_BT2907_seven_frontiers_insert}%"
STAMP = "% BT2901-BT2907-BLUEPRINT-REWRITE-V1"


def replace_literal(text: str, old: str, new: str, label: str, required: bool = True) -> tuple[str, bool]:
    if new in text:
        return text, False
    if old not in text:
        if required:
            raise RuntimeError(f"missing blueprint anchor: {label}")
        return text, False
    return text.replace(old, new, 1), True


def replace_regex(text: str, pattern: str, replacement: str, label: str, required: bool = True) -> tuple[str, bool]:
    if re.search(pattern, text, flags=re.S) is None:
        if required:
            raise RuntimeError(f"missing blueprint regex anchor: {label}")
        return text, False
    new_text, count = re.subn(pattern, replacement, text, count=1, flags=re.S)
    return new_text, bool(count)


CONTROL_SECTION = r'''
% =====================================================================================
\section{Four representations, four jobs}\label{sec:representations}
% =====================================================================================

\begin{plain}
The machine now has four compact descriptions of the same underlying frame, and they must
not be confused.  The seven-bit code is the execution state.  The four-bit support mask is
cheap one-way telemetry.  The protected observer words trade more wires and time for error
correction.  The ninety-six-state selector--tomotope token is a control word, not stored
quantum data.  Earlier drafts occasionally used the word ``state'' for all four; this
section removes that ambiguity from the architecture.
\end{plain}

\begin{spec}[Representation contract]
\begin{tabular}{@{}p{3.2cm}p{2.1cm}p{6.4cm}@{}}
\toprule
\textbf{Representation} & \textbf{Width} & \textbf{Contract} \\
\midrule
Affine frame code & $7$ bits & Lossless code for all $81$ Pauli frames; execution may read and write it. \\
Support telemetry & $4$ bits & Zero/nonzero mask only; frame $\to$ support is one-way in the netlist. \\
Protected observer & $24$ or $28$ taps & Diagnostic feature word used for identification/correction, not the live datapath. \\
Typed control token & $7$ raw bits, $96$ valid & Selects face, matching channel, and tomotope phase cell. \\
\bottomrule
\end{tabular}
\end{spec}

\begin{gotwrong}[Support is observable, not executable]
The refinement count $16\to40\to78\to81$ was once easy to read as four increasingly
accurate compressed machine states.  It is not.  Exhausting every nonempty subset of the
four-operation micro-ISA proves that the coarsest exact support-refining execution
quotient for the full ISA has all $81$ singleton classes.  The intermediate partitions
are observer states only.  In fact $F_p$, $Z_p$, and either controlled-add direction
already force the full frame.
\end{gotwrong}

\begin{spec}[Intrinsic selector channel]
For a noncollinear pair $x,y$ and a distinguished common neighbour $c$, the three residual
selector channels form the affine line $C(x,y)\setminus\{c\}$.  The multiplier-one
stabilizer induces its translation group $C_3$; the full projective similitude stabilizer
induces $\operatorname{AGL}(1,3)\cong S_3$.  There is therefore no globally equivariant
numbering $0,1,2$.  Hardware may choose a local encoding, but interfaces transport it as
an affine-line torsor rather than pretending the labels are geometric invariants.
\end{spec}
'''


ENGINE_SECTION = r'''
% =====================================================================================
\section{The support transform and diagnostic scheduler}\label{sec:support-transform}
% =====================================================================================

\begin{plain}
A dense fifteen-by-fifteen table is not how the support dynamics should be built.  The
table factors into thirty-two tiny two-input butterflies, followed by fifteen corrected
outputs.  Diagnosis has a second surprise: the best order in which to visit the fifteen
nonzero masks is not generated by a linear feedback register.  A short ROM is both more
honest and better.
\end{plain}

\begin{spec}[Butterfly engine]
At $q=3$ the local kernel is $(u,v)\mapsto(u+2v,u-v)$.  Four stages of eight butterflies
and fifteen output cycles give a $47$-cycle sequential quotient engine.  A serial dense
reference needs $15\times15=225$ cycles, so the exact cycle reduction is
\[
  \frac{225-47}{225}=\frac{178}{225}.
\]
Equality is checked on all fifteen basis vectors and thirty-two deterministic signed
probes.  Logic cells, routed frequency, and switching activity remain measured quantities
pending the dedicated workflow.
\end{spec}

\begin{spec}[Diagnostic mask ROM]
The $210$ directed first-passage costs form $39$ matching-stabilizer orbits.  Exact
Held--Karp optimization gives a Hamiltonian mask cycle of cost $315$ and $8336$ rooted
optima.  The best $\mathrm{GL}(4,2)$ Singer cycle costs $1317/4$, an exact gap of $57/4$.
The scheduler is therefore a fifteen-entry nonlinear permutation ROM, not an LFSR.
\end{spec}

\begin{gotwrong}[Forty is not enough]
The first observer refinement has forty classes, but those classes are not the forty
projective points of $W(3,3)$.  Their sizes are $1^7 2^{29}4^4$, symplectic
orthogonality is ambiguous on $216$ unordered class pairs, and no union of Hamming-distance
relations on their signatures yields $\mathrm{SRG}(40,12,2,4)$.  A matching count is a
search hint, never an identification theorem.
\end{gotwrong}
'''


def patch_wrapper(path: Path) -> bool:
    text = path.read_text(encoding="utf-8")
    if INSERT in text:
        return False
    anchors = [
        r"\input{analysis/BT2854_BT2860_seven_frontiers_insert}%",
        r"\input{analysis/BT2847_BT2853_protected_observer_noisy_m36_insert}%",
        r"\input{analysis/BT2820_BT2824_blueprint_hardening_insert}%",
    ]
    anchor = next((a for a in anchors if a in text), None)
    if anchor is None:
        raise RuntimeError(f"no manuscript wrapper anchor in {path}")
    path.write_text(text.replace(anchor, anchor + "\n    " + INSERT, 1), encoding="utf-8")
    return True


def patch_blueprint(path: Path) -> bool:
    text = path.read_text(encoding="utf-8")
    original = text

    if STAMP not in text:
        text = STAMP + "\n" + text

    text, _ = replace_literal(
        text,
        "Every number in this document is measured or proved.  Nothing is estimated.  Where a\n%  figure was WRONG in earlier work, the wrong figure is printed next to the right one,\n%  because how a number was wrong is part of what makes the right one trustworthy.",
        "Every promoted figure in this document is explicitly typed as proved, measured,\n%  published, derived, modelled, or open.  Modelled quantities are never presented as\n%  measurements.  Where a figure was wrong, its correction and detection method remain.",
        "top evidence promise",
        required=False,
    )
    text = text.replace(
        r"\normalsize Every figure in this document is measured or proved.}",
        r"\normalsize Every promoted figure is typed: proved, measured, published, modelled, or open.}",
        1,
    )
    text = re.sub(r"Passes 2700--\d+", "Passes 2700--2907", text, count=1)

    text = text.replace(
        "A support readout erases exactly $8/3$ of a bit, so its energy\ncost is fixed by thermodynamics rather than by engineering.",
        "A support-only observation discards exactly $8/3$ bits of conditional phase\ninformation.  Landauer supplies a thermodynamic floor for erasing that information, not\nan engineering power forecast.",
        1,
    )
    text = text.replace(
        "The arithmetic\ncore fits in \\textbf{43 logic cells} on a \\$25 chip and runs at \\textbf{208.9\\,MHz} ---\nmeasured, not estimated.",
        "On the HX8K target the minimal arithmetic core uses \\textbf{43 logic cells} at\n\\textbf{208.86\\,MHz}; on the UP5K it uses the same 43 cells at 72.40\\,MHz.  Those are\npart-specific measurements, not interchangeable headline numbers.",
        1,
    )
    text = text.replace(
        "The physical layer is a\nphotonic gate a laboratory has already demonstrated at $0.92$ fidelity.",
        "Published time-bin/frequency-bin experiments report a two-qutrit gate fidelity near\n$0.92$; this is prior-art evidence for a component class, not a measurement of the\nunbuilt Holonet stack.",
        1,
    )

    old_arith = (
        r"\textbf{Arithmetic unit}      & Public: $72$ iCE40 cells at $60.80$\,MHz."
        "\n                                "
        r"Minimal: $\mathbf{43}$ cells at $\mathbf{72.40}$\,MHz."
        "\n                                "
        r"Both measured, \S\ref{sec:budget}. \\"
    )
    new_arith = (
        r"\textbf{Arithmetic unit}      & HX8K: minimal $43$ LC at $208.86$\,MHz; public $72$ LC at"
        "\n                                "
        r"$175.72$\,MHz; minimal plus support $48$ LC at $207.64$\,MHz."
        "\n                                "
        r"UP5K: the corresponding clocks are $72.40$, $60.80$, and $72.05$\,MHz. \\"
    )
    if old_arith in text:
        text = text.replace(old_arith, new_arith, 1)

    text = text.replace(
        r"$4$ trits of state, $72$ logic cells, $60.80$\,MHz};",
        r"$7$-bit frame code; minimal execution $43$ LC; support readout adds $5$ LC};",
        1,
    )

    text = text.replace(
        "Physically this is done by splitting a\nsingle photon's degrees of freedom: its arrival \\emph{time} carries one qutrit and its\n\\emph{colour} carries the other. It is one particle, entangled with its own history.",
        "The proposed optical encoding assigns one qutrit to arrival-time bins and one to\nfrequency bins on a single carrier.  The words ``past'' and ``future'' name these two\nlogical registers; they do not assert a demonstrated closed-time-loop interaction or a\nnew physical form of temporal entanglement.",
        1,
    )
    text = text.replace(
        r"\textit{One photon. Two degrees of freedom. The entanglement is between the"
        "\n     "
        r"particle and itself.}};",
        r"\textit{One optical carrier, two encoded qutrit degrees of freedom.  The"
        "\n     "
        r"past/future names are architectural labels.}};",
        1,
    )

    uniqueness_old = (
        "Those four numbers --- $40$, $12$, $2$, $4$ --- pin the shape down completely. "
        "There is\nessentially one object in the world with that compatibility pattern, and it has been\n"
        "studied since the 1900s under the name $W(3,3)$.")
    uniqueness_new = (
        "Those four numbers are necessary but not sufficient: there are $28$ nonisomorphic\n"
        "strongly regular graphs with parameters $(40,12,2,4)$.  This machine's graph is\n"
        "identified as $W(3,3)$ by the projective symplectic construction and the\n"
        "generalized-quadrangle incidence axiom, not by the SRG parameters alone.")
    if uniqueness_old in text:
        text = text.replace(uniqueness_old, uniqueness_new, 1)

    path_old = (
        "That last property --- ``exactly one'' --- is the entire content of the word\n"
        "\\emph{quadrangle}. It is a strong constraint: it means the geometry contains no\n"
        "triangles, so there is never any ambiguity about how to get from one place to another.\n"
        "For a computer, that is precisely what you want from an address space and from a routing\n"
        "fabric: there is one shortest path, and no loops to break ties in.")
    path_new = (
        "The ``exactly one'' statement is an incidence projection rule: for a point outside a\n"
        "line there is one point on that line collinear with it.  It does not imply unique\n"
        "shortest paths in the collinearity graph.  Each four-point line is a $K_4$, so that\n"
        "graph contains triangles; the triangle-free object is the bipartite point--line\n"
        "incidence graph, whose generalized-quadrangle girth is eight.  Routing claims must\n"
        "therefore be proved by the routing code, not inferred from the word quadrangle.")
    if path_old in text:
        text = text.replace(path_old, path_new, 1)

    text = text.replace(
        "There are eleven of them. They are not\napologies; they are the reason the other numbers in this document can be trusted.",
        "The errata index is authoritative and grows when a claim is corrected. These boxes are\nnot apologies; they are the reason the other numbers in this document can be trusted.",
        1,
    )

    if r"\label{sec:representations}" not in text:
        marker = r"\section{The instruction set}\label{sec:isa}"
        if marker not in text:
            raise RuntimeError("instruction-set marker missing")
        text = text.replace(marker, CONTROL_SECTION + "\n" + marker, 1)

    if r"\label{sec:support-transform}" not in text:
        candidates = [
            r"\section{The network}\label{sec:network}",
            r"\section{The network}",
            r"\section{Verification}",
            r"\section{The verification methodology}",
        ]
        marker = next((m for m in candidates if m in text), None)
        if marker is None:
            marker = r"\end{document}"
        text = text.replace(marker, ENGINE_SECTION + "\n" + marker, 1)

    if INSERT not in text:
        marker = r"\end{document}"
        if marker not in text:
            raise RuntimeError("blueprint end marker missing")
        text = text.replace(marker, INSERT + "\n" + marker, 1)

    if text != original:
        path.write_text(text, encoding="utf-8")
        return True
    return False


def patch_index(path: Path) -> bool:
    text = path.read_text(encoding="utf-8")
    ident = 'id="pass-2901-2907-selector-butterfly-observer"'
    if ident in text:
        return False
    section = '''
<section id="pass-2901-2907-selector-butterfly-observer" class="section theorem-section">
  <div class="section-number">Passes 2901--2907</div>
  <h2>Intrinsic selector channels and nonlinear support diagnosis</h2>
  <p>The three residual selector channels are an affine line with C3 translations and S3 transition functions; no global geometry-equivariant numbering exists.</p>
  <p>A literal q=3 butterfly engine evaluates the fifteen-state quotient in 47 modeled cycles rather than 225 dense serial cycles. The full micro-ISA still requires all 81 frame states for exact execution.</p>
  <p>The 96 typed selector--tomotope tokens carry a regular determinant-twisted group action. The optimal fifteen-mask passage schedule costs 315 and is provably nonlinear: every GL(4,2) Singer cycle costs more.</p>
  <p>The first forty observer classes are not W(3,3); the matching count is explicitly recorded as a falsified identification.</p>
</section>
'''
    marker = "</body>"
    if marker in text:
        text = text.replace(marker, section + marker, 1)
    else:
        text += section
    path.write_text(text, encoding="utf-8")
    return True


def close_registry(path: Path) -> bool:
    data = json.loads(path.read_text(encoding="utf-8"))
    completion = {
        "verifier": "analysis/bt2901_2907_seven_frontiers.py",
        "aggregate_certificate": "data/PART_BT2901_BT2907_SEVEN_FRONTIERS_results.json",
        "tests": "tests/test_bt2901_2907_seven_frontiers.py",
        "rtl": [
            "rtl/w33_pass2902_q3_hadamard_engine.sv",
            "rtl/w33_pass2902_q3_dense_reference.sv",
            "rtl/tb_w33_pass2902_q3_hadamard_engine.sv",
        ],
        "insert": "analysis/BT2901_BT2907_seven_frontiers_insert.tex",
        "blueprint_rewrite": "tools/integrate_bt2901_bt2907.py",
    }
    if data.get("status") == "complete" and data.get("completion") == completion:
        return False
    data["status"] = "complete"
    data["completion"] = completion
    path.write_text(json.dumps(data, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    return True


def main() -> None:
    changed: list[str] = []
    for name in ("w33_paper.tex", "photonic_holonet.tex"):
        if patch_wrapper(ROOT / name):
            changed.append(name)
    if patch_blueprint(ROOT / "holonet_machine_blueprint.tex"):
        changed.append("holonet_machine_blueprint.tex")
    if patch_index(ROOT / "docs" / "index.html"):
        changed.append("docs/index.html")
    registry = ROOT / "data" / "w33_pass_namespace_registry_v2.d" / "2901-2907.json"
    if close_registry(registry):
        changed.append(str(registry.relative_to(ROOT)))
    print("changed:", ", ".join(changed) if changed else "none")


if __name__ == "__main__":
    main()
