#!/usr/bin/env python3
"""Fail-closed historical manuscript compiler for Pass 1348.

The repository contains references to historical Holonet inserts that were never
committed. This tool never promotes missing claims. It creates visible,
build-directory-only provenance stubs for the narrowly typed missing paths,
then compiles from the real source tree through TEXINPUTS. Any other missing
input is fatal.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import os
from pathlib import Path
import re
import shutil
import subprocess
import tempfile

ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / "data"
INPUT_RE = re.compile(r"\\(?:input|include)\{([^}]+)\}")
TYPED_MISSING_RE = re.compile(r"^analysis/BT\d+_BT\d+_holonet_insert\.tex$")
SOURCES = ("w33_paper.tex", "photonic_holonet.tex")
GENERATED_FIGURES = {
    "analysis/w33_cc_floor_fig.tex": "analysis/w33_cc_floor.py",
    "analysis/w33_decisive_r_test_fig.tex": "analysis/w33_decisive_r_test.py",
    "analysis/w33_mass_ladder_fig.tex": "analysis/w33_mass_ladder.py",
    "analysis/w33_ns_r_forecast_fig.tex": "analysis/w33_ns_r_forecast.py",
    "analysis/w33_tower_falsification_fig.tex": "analysis/w33_tower_falsification_figure.py",
    "analysis/w33_killshot_dashboard_fig.tex": "analysis/w33_killshot_dashboard.py",
}


def resolve_input(raw: str) -> Path:
    candidate = Path(raw)
    if candidate.suffix == "":
        candidate = candidate.with_suffix(".tex")
    return candidate


def collect_inputs(source: Path) -> tuple[set[Path], set[Path]]:
    seen: set[Path] = set()
    missing: set[Path] = set()
    stack = [source]
    while stack:
        current = stack.pop()
        if current in seen or not current.exists():
            continue
        seen.add(current)
        text = current.read_text(encoding="utf-8", errors="replace")
        for raw in INPUT_RE.findall(text):
            rel = resolve_input(raw)
            target = ROOT / rel
            if target.exists():
                stack.append(target)
            else:
                missing.add(rel)
    return seen, missing


def stub_text(rel: Path) -> str:
    escaped = str(rel).replace("_", r"\_")
    return (
        "% Build-only provenance stub generated by Pass 1348.\n"
        "\\begin{center}\n"
        "\\fbox{\\begin{minipage}{0.92\\linewidth}\\small\n"
        "Historical insert unavailable in this checkout: \\texttt{" + escaped + "}. "
        "No theorem, numerical result, or experimental claim is promoted from this absent packet.\n"
        "\\end{minipage}}\n"
        "\\end{center}\n"
    )


def compile_one(source_name: str, overlay: Path, outroot: Path) -> dict:
    source = ROOT / source_name
    if not source.exists():
        return {"source": source_name, "status": "SOURCE_UNAVAILABLE"}
    _, missing = collect_inputs(source)
    typed = sorted(rel for rel in missing if TYPED_MISSING_RE.match(str(rel)))
    fatal = sorted(rel for rel in missing if rel not in typed)
    if fatal:
        raise SystemExit(
            "Unrecognized missing TeX inputs for %s: %s"
            % (source_name, ", ".join(map(str, fatal)))
        )
    for rel in typed:
        target = overlay / rel
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(stub_text(rel), encoding="utf-8")

    outdir = outroot / Path(source_name).stem
    outdir.mkdir(parents=True, exist_ok=True)
    env = os.environ.copy()
    env["TEXINPUTS"] = f"{overlay}//:{ROOT}//:" + env.get("TEXINPUTS", "")
    command = [
        "latexmk", "-pdf", "-interaction=nonstopmode", "-halt-on-error",
        f"-outdir={outdir}", source_name,
    ]
    completed = subprocess.run(
        command, cwd=ROOT, env=env, text=True,
        stdout=subprocess.PIPE, stderr=subprocess.STDOUT,
    )
    log = outdir / "pass1348_latexmk.out"
    log.write_text(completed.stdout, encoding="utf-8")
    if completed.returncode != 0:
        raise SystemExit(f"latexmk failed for {source_name}; see {log}")
    pdf = outdir / (Path(source_name).stem + ".pdf")
    payload = pdf.read_bytes()
    page_count = None
    if shutil.which("pdfinfo"):
        info = subprocess.run(["pdfinfo", str(pdf)], text=True, stdout=subprocess.PIPE, check=True).stdout
        match = re.search(r"^Pages:\s+(\d+)$", info, re.MULTILINE)
        page_count = int(match.group(1)) if match else None
    return {
        "source": source_name,
        "status": "PASS" if not typed else "PASS_WITH_TYPED_BUILD_ONLY_STUBS",
        "typed_stub_count": len(typed),
        "typed_stub_paths": [str(x) for x in typed],
        "pdf": str(pdf.relative_to(ROOT)),
        "pdf_sha256": hashlib.sha256(payload).hexdigest(),
        "pages": page_count,
    }


def ensure_generated_figures() -> list[str]:
    generated = []
    for figure, producer in GENERATED_FIGURES.items():
        target = ROOT / figure
        if target.exists():
            continue
        script = ROOT / producer
        if not script.exists():
            raise SystemExit(f"Missing generated figure {figure} and producer {producer}")
        subprocess.run(["python", producer], cwd=ROOT, check=True)
        if not target.exists():
            raise SystemExit(f"Producer {producer} did not emit {figure}")
        generated.append(figure)
    return generated


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--require-all", action="store_true")
    parser.add_argument("--output", default="data/w33_pass1348_manuscript_build_observation.json")
    args = parser.parse_args()

    generated_figures = ensure_generated_figures()
    outroot = ROOT / "build" / "pass1348_historical_manuscripts"
    outroot.mkdir(parents=True, exist_ok=True)
    with tempfile.TemporaryDirectory(prefix="w33-pass1348-tex-") as tmp:
        overlay = Path(tmp)
        records = [compile_one(source, overlay, outroot) for source in SOURCES]
    if args.require_all and any(x["status"] == "SOURCE_UNAVAILABLE" for x in records):
        raise SystemExit("--require-all requested but at least one manuscript source is unavailable")
    result = {
        "schema": "w33.pass1348.manuscript_build_observation.v1",
        "status": "PASS" if all(x["status"].startswith("PASS") for x in records) else "PARTIAL",
        "records": records,
        "generated_figures": generated_figures,
        "policy": "Typed stubs exist only in a temporary TEXINPUTS overlay and visibly state that no claim is promoted.",
    }
    target = ROOT / args.output
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(json.dumps(result, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    print(json.dumps(result, indent=2, sort_keys=True))


if __name__ == "__main__":
    main()
