#!/usr/bin/env python3
"""BT1177 -- direct 27-line Schlaefli triangle bridge.

Build the 27 cubic-surface line labels a_i, b_i, c_ij and the 45 tritangent
triples.  The line-intersection graph generated by these triples is
SRG(27,10,1,5), and its 45 triangles are exactly the tritangent triples.  This
links the BT1170/BT1172 45-object model directly to the 27-line Schlaefli graph.
"""

from __future__ import annotations

import itertools
import json
from collections import Counter

import numpy as np

SIX = range(6)


def matchings(items):
    items = tuple(items)
    if not items:
        yield ()
        return
    first = items[0]
    for k in range(1, len(items)):
        second = items[k]
        rest = items[1:k] + items[k+1:]
        for tail in matchings(rest):
            yield tuple(sorted((tuple(sorted((first, second))),) + tail))


def build_lines_and_planes():
    lines = [("a", i) for i in SIX] + [("b", i) for i in SIX]
    lines += [("c", tuple(sorted((i, j)))) for i, j in itertools.combinations(SIX, 2)]
    tritangents = []
    for i in SIX:
        for j in SIX:
            if i != j:
                tritangents.append(tuple(sorted((("a", i), ("b", j), ("c", tuple(sorted((i, j))))))))
    for m in sorted(set(matchings(SIX))):
        tritangents.append(tuple(sorted(("c", d) for d in m)))
    return lines, sorted(set(tritangents))


def srg_stats(A):
    n = A.shape[0]
    deg = A.sum(axis=1)
    adj, non = [], []
    for i in range(n):
        for j in range(i + 1, n):
            c = int(A[i] @ A[j])
            (adj if A[i, j] else non).append(c)
    return {
        "vertices": int(n),
        "edges": int(A.sum() // 2),
        "degree_set": sorted(map(int, set(deg))),
        "adjacent_common": dict(Counter(map(int, adj))),
        "nonadjacent_common": dict(Counter(map(int, non))),
    }


def main():
    lines, tritangents = build_lines_and_planes()
    idx = {line: i for i, line in enumerate(lines)}
    A = np.zeros((len(lines), len(lines)), dtype=int)
    for tri in tritangents:
        for u, v in itertools.combinations(tri, 2):
            A[idx[u], idx[v]] = A[idx[v], idx[u]] = 1

    triangles = []
    for i, j, k in itertools.combinations(range(len(lines)), 3):
        if A[i, j] and A[i, k] and A[j, k]:
            triangles.append(tuple(sorted((lines[i], lines[j], lines[k]))))
    triangles = sorted(set(triangles))

    payload = {
        "bt": 1177,
        "title": "27-line Schlaefli triangle bridge",
        "line_count": len(lines),
        "tritangent_count": len(tritangents),
        "graph_stats": srg_stats(A),
        "triangle_count": len(triangles),
        "triangles_equal_tritangents": triangles == tritangents,
        "checks": {
            "lines_27": len(lines) == 27,
            "tritangents_45": len(tritangents) == 45,
            "triangles_45": len(triangles) == 45,
            "triangles_are_exactly_tritangents": triangles == tritangents,
            "srg_27_10_1_5": srg_stats(A) == {
                "vertices": 27,
                "edges": 135,
                "degree_set": [10],
                "adjacent_common": {1: 135},
                "nonadjacent_common": {5: 216},
            },
        },
    }
    payload["checks"]["all_checks_pass"] = all(payload["checks"].values())
    print(json.dumps(payload, indent=2, sort_keys=True))


if __name__ == "__main__":
    main()
