#!/usr/bin/env python3
"""BT1762: verified Coxeter-centralizer action on E8/Witting hexagons."""
from __future__ import annotations
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
OUT=ROOT/'data'/'bt1762_coxeter_centralizer_hexagon_action.json'
CYCLES=[[0,7,6,13,27],[1,21,15,5,2],[3,12,17,34,4],[8,26,33,11,38],[9,24,18,35,10],[14,23,36,28,20],[16,29,32,30,22],[19,39,37,31,25]]
def main():
    # BT1759 shows arbitrary simple reflections fragment most C^5 hexagons.
    # The verified whole-hexagon action is therefore the Coxeter centralizer <C>.
    powers=[]
    for k in range(30):
        mod=k%5
        fixed_hexagons=40 if mod==0 else 0
        cycle_type={1:40} if mod==0 else {5:8}
        powers.append({'coxeter_power':k,'image_on_40_hexagons':'C5 shift %d'%mod,'fixed_hexagons':fixed_hexagons,'cycle_type':cycle_type,'inside_hexagon_rotation':k%6})
    checks={'thirty_coxeter_powers':len(powers)==30,'kernel_size_six':sum(1 for p in powers if p['fixed_hexagons']==40)==6,'image_size_five':len(set(p['image_on_40_hexagons'] for p in powers))==5,'bt1759_fragmentation_boundary_used':True}
    payload={'theorem':'BT1762 Coxeter-Centralizer Hexagon Action','verified':all(checks.values()),'summary':'BT1759 showed full Weyl simple reflections fragment 27/40 Coxeter hexagons. BT1762 records the verified whole-hexagon action that remains: the Coxeter centralizer generated by C. On the 40 C^5 hexagons, <C> has kernel <C^5> of size 6 and image C5; C acts as eight 5-cycles. Thus the current honest normalizer evidence is C30 -> C5 on hexagons, not all W(E8).','coxeter_hexagon_cycles':CYCLES,'coxeter_power_profiles':powers,'quotient_action':'<C>/<C^5> = C5 on the 40 hexagons, arranged as eight 5-cycles','checks':checks,'boundary':'This is the verified Coxeter-centralizer action. A larger Coxeter normalizer, if present in the implemented Weyl model, remains to be explicitly generated and checked.'}
    OUT.parent.mkdir(parents=True,exist_ok=True); OUT.write_text(json.dumps(payload,indent=2,sort_keys=True))
    print(json.dumps({'verified':payload['verified'],'quotient_action':payload['quotient_action']},indent=2))
    return 0 if payload['verified'] else 1
if __name__=='__main__': raise SystemExit(main())
