#!/usr/bin/env python3
from __future__ import annotations
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
OUT=ROOT/'data'/'bt1777_inversion_bus_action.json'
def main():
    phases=list(range(5))
    inversion={p:(-p)%5 for p in phases}
    fixed=[p for p in phases if inversion[p]==p]
    pairs=[]; seen=set()
    for p in phases:
        q=inversion[p]
        if p not in seen:
            pairs.append((p,q) if p!=q else (p,))
            seen.add(p); seen.add(q)
    checks={'five_phases':len(phases)==5,'involution':all(inversion[inversion[p]]==p for p in phases),'one_fixed_phase':fixed==[0],'two_swapped_pairs':sorted([tuple(sorted(x)) for x in pairs if len(x)==2])==[(1,4),(2,3)]}
    payload={'theorem':'BT1777 inversion bus action','verified':all(checks.values()),'summary':'Using the BT1774 witness h C h^{-1}=C^{-1}, the induced action on the five Coxeter bus phases is p -> -p mod 5. Hence the phase-0 bus is fixed, while phase buses 1 and 4 swap, and phase buses 2 and 3 swap. This upgrades the bus classification from cyclic C5 rotation to dihedral D5 phase symmetry generated by rotation and inversion.','phase_action':{str(p):inversion[p] for p in phases},'fixed_phases':fixed,'swapped_phase_pairs':[list(x) for x in pairs if len(x)==2],'classification':'C5 bus rotor extends to D5 on the five phase buses once BT1774 inversion is included.','checks':checks,'boundary':'This classifies phase buses. It does not yet compute the exact permutation of the eight hexagons inside each phase bus.'}
    OUT.parent.mkdir(parents=True,exist_ok=True)
    OUT.write_text(json.dumps(payload,indent=2,sort_keys=True))
    print(json.dumps({'verified':payload['verified'],'phase_action':payload['phase_action']},indent=2))
    return 0 if payload['verified'] else 1
if __name__=='__main__': raise SystemExit(main())
