#!/usr/bin/env python3
"""BT1865: integral representative equivalence classes.

Enumerates the full integral automorphism group of the A2 Gram form in simple-root
coordinates. This sharpens BT1860: the sign-kernel candidate is the central
inversion -I in O(A2), not an ordinary Weyl-group element. O(A2) has order 12,
W(A2) has order 6, and -I represents the nontrivial central coset invisible
mod 2.
"""
from __future__ import annotations

import json
from itertools import product
from pathlib import Path

OUT = Path("data/PART_BT1865_INTEGRAL_REPRESENTATIVE_EQUIVALENCE_CLASSES_results.json")

G = ((2, -1), (-1, 2))
S1 = ((-1, 1), (0, 1))
S2 = ((1, 0), (1, -1))
NEG_I = ((-1, 0), (0, -1))
I2 = ((1, 0), (0, 1))


def matmul(A, B):
    return tuple(tuple(sum(A[i][k] * B[k][j] for k in range(2)) for j in range(2)) for i in range(2))


def transpose(A):
    return tuple(tuple(A[j][i] for j in range(2)) for i in range(2))


def preserves_gram(M):
    return matmul(transpose(M), matmul(G, M)) == G


def closure(gens):
    seen = {I2}
    frontier = [I2]
    while frontier:
        A = frontier.pop()
        for X in gens:
            B = matmul(A, X)
            if B not in seen:
                seen.add(B)
                frontier.append(B)
    return seen


def det(M):
    return M[0][0] * M[1][1] - M[0][1] * M[1][0]


def theorem_summary():
    O = set()
    for entries in product(range(-2, 3), repeat=4):
        M = ((entries[0], entries[1]), (entries[2], entries[3]))
        if preserves_gram(M):
            O.add(M)
    W = closure([S1, S2])
    outer = sorted(O - W)
    classes = {
        "identity_class": [list(map(list, I2))],
        "central_inversion_class": [list(map(list, NEG_I))]
    }
    checks = {
        "O_A2_order_12": len(O) == 12,
        "W_A2_order_6": len(W) == 6,
        "negative_identity_preserves_gram": NEG_I in O,
        "negative_identity_not_in_plain_Weyl_group": NEG_I not in W,
        "two_cosets_over_Weyl": len(outer) == 6,
        "sign_kernel_representatives_two_classes": len(classes) == 2
    }
    return {
        "theorem": "BT1865 Integral Representative Equivalence Classes",
        "A2_gram": [list(r) for r in G],
        "O_A2_order": len(O),
        "W_A2_order": len(W),
        "negative_identity": [list(r) for r in NEG_I],
        "negative_identity_det": det(NEG_I),
        "negative_identity_role": "central inversion in O(A2); outside the plain W(A2) generated by simple reflections",
        "equivalence_classes_for_size2_sign_kernel": classes,
        "reading": "The sign-kernel lift has two support-level classes: identity and central inversion. The latter is Gram-preserving and mod-2 invisible, but should be called a full A2 lattice automorphism rather than an ordinary Weyl element.",
        "checks": checks,
        "all_pass": all(checks.values()),
        "honest_scope": "Classifies integral A2 lattice representatives up to the Weyl subgroup. It does not yet pick a physical chain representative inside E8."
    }


def main() -> int:
    summary = theorem_summary()
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(json.dumps(summary, indent=2) + "\n", encoding="utf-8")
    print(json.dumps(summary, indent=2))
    return 0 if summary["all_pass"] else 1


if __name__ == "__main__":
    raise SystemExit(main())
