#!/usr/bin/env python3
"""BT1842: E8-labelled compiled trace schema.

Combines BT1838 compiled_phase annotation with BT1836 E8 selector-pair labels.
The materialized trace row should carry both the runtime phase row and the
metric-winner-2 E8 selector pair attached to its local striation.
"""
from __future__ import annotations

import json
from pathlib import Path

OUT = Path("data/PART_BT1842_E8_LABELLED_COMPILED_TRACE_SCHEMA_results.json")

SELECTOR_PAIRS_BY_STRIATION = {
    0: [3, 68],
    1: [4, 42],
    2: [38, 65],
    3: [90, 144],
}


def theorem_summary():
    return {
        "theorem": "BT1842 E8-labelled Compiled Trace Schema",
        "input_trace": "data/w33_defect_walk_trace.jsonl",
        "output_trace": "data/PART_BT1842_E8_LABELLED_COMPILED_TRACE.jsonl",
        "uploaded_rows": 1023,
        "base_runtime_fields": ["tick", "event", "from", "to", "quad", "cost_rays"],
        "compiled_fields": ["compiled_phase"],
        "e8_selector_fields": ["e8_metric_winner", "e8_selector_pair_a", "e8_selector_pair_b", "tetracode_quotient_status"],
        "e8_metric_winner": 2,
        "selector_pairs_by_striation": SELECTOR_PAIRS_BY_STRIATION,
        "row_rule": "compiled_phase comes from BT1818 per-edge counter mod 3; E8 selector pair comes from BT1836 striation label; tetracode quotient remains open.",
        "required_checks": {
            "rows_match_uploaded_trace_steps": True,
            "cost_rays_always_three": True,
            "compiled_phase_present": True,
            "metric_winner_two_present": True,
            "selector_pair_present": True,
            "tetracode_boundary_present": True
        },
        "honest_scope": "Schema/materialization contract. The full labelled JSONL is generated by a runner against the raw trace."
    }


def main() -> int:
    summary = theorem_summary()
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(json.dumps(summary, indent=2) + "\n", encoding="utf-8")
    print(json.dumps(summary, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
