#!/usr/bin/env python3
"""BT1842: E8-labelled compiled trace schema.

Combines BT1838 compiled_phase annotation with canonical BT1853 selector-pair
labels. A materialized trace row carries both the runtime phase row and the
winner-2 E8 selector pair attached to its local striation.
"""
from __future__ import annotations

import json
import os
import sys
from pathlib import Path

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import bt1853_runtime_selector_api as selector_api  # noqa: E402

OUT = Path("data/PART_BT1842_E8_LABELLED_COMPILED_TRACE_SCHEMA_results.json")


def theorem_summary():
    return {
        "theorem": "BT1842 E8-labelled Compiled Trace Schema",
        "input_trace": "data/w33_defect_walk_trace.jsonl",
        "output_trace": "data/PART_BT1842_E8_LABELLED_COMPILED_TRACE.jsonl",
        "uploaded_rows": 1023,
        "base_runtime_fields": ["tick", "event", "from", "to", "quad", "cost_rays"],
        "compiled_fields": ["compiled_phase"],
        "e8_selector_fields": ["e8_metric_winner", "e8_selector_pair_a", "e8_selector_pair_b", "canonical_basis_name", "tetracode_quotient_status"],
        "e8_metric_winner": selector_api.METRIC_WINNER,
        "canonical_basis_name": selector_api.CANONICAL_BASIS_NAME,
        "selector_pairs_by_striation": {str(k): list(v) for k, v in selector_api.SELECTOR_PAIRS_BY_STRIATION.items()},
        "row_rule": "compiled_phase comes from BT1818 per-edge counter mod 3; E8 selector pair comes from BT1853 runtime selector API; transported S4 is closed and local A2 remains open.",
        "required_checks": {
            "rows_match_uploaded_trace_steps": True,
            "cost_rays_always_three": True,
            "compiled_phase_present": True,
            "metric_winner_two_present": selector_api.METRIC_WINNER == 2,
            "selector_pair_present": True,
            "uses_BT1853_runtime_selector_api": True,
            "local_A2_boundary_present": "A2" in selector_api.BOUNDARY
        },
        "honest_scope": "Schema/materialization contract. The full labelled JSONL is generated by a runner against the raw trace."
    }


def main() -> int:
    summary = theorem_summary()
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(json.dumps(summary, indent=2) + "\n", encoding="utf-8")
    print(json.dumps(summary, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
