#!/usr/bin/env python3
"""Exact Sp(4,3) group and centralizer routines for Passes 2762-2766."""
from bt2762_core import *

def action(g, geometry):
    points, p_index, lines, l_index, flags, f_index, edges, e_index, apartments, a_index = geometry
    pp = tuple((p_index[norm(mv(g, p))] for p in points))
    ll = tuple((l_index[frozenset((norm(mv(g, p)) for p in line))] for line in lines))
    ff = tuple((f_index[pp[p], ll[l]] for p, l in flags))
    ee = tuple((e_index[tuple(sorted((pp[a], pp[b])))] for a, b in edges))
    aa = tuple((a_index[frozenset((pp[p] for p in ps)), frozenset((ll[l] for l in ls))] for ps, ls in apartments))
    return (pp, ll, ff, ee, aa)

def conjugacy_classes(group):
    gens = GENERATORS + tuple((inv(g) for g in GENERATORS))
    invs = tuple((inv(g) for g in gens))
    unassigned = set(group)
    classes = []
    while unassigned:
        rep = min(unassigned)
        cls = {rep}
        q = deque([rep])
        while q:
            x = q.popleft()
            for s, si in zip(gens, invs):
                y = mm(mm(s, x), si)
                if y not in cls:
                    cls.add(y)
                    q.append(y)
        classes.append((rep, cls))
        unassigned -= cls
    return classes

def find_s3_complement(centralizer, center):
    for a in sorted(centralizer):
        if order(a) != 3 or a in center:
            continue
        for b in sorted(centralizer):
            if order(b) != 2:
                continue
            if mm(mm(b, a), b) != inv(a):
                continue
            h = closure((a, b))
            if len(h) != 6 or h & center != {I}:
                continue
            products = {mm(z, x) for z in center for x in h}
            if len(products) == 108:
                return (a, b, h)
    raise AssertionError('no S3 complement')

def find_center_generators(center):
    for z6 in sorted(center):
        if order(z6) != 6:
            continue
        for z3 in sorted(center):
            if order(z3) == 3 and len(closure((z6, z3))) == 18:
                return (z6, z3)
    raise AssertionError('center is not generated by C6 x C3')
