#!/usr/bin/env python3
from __future__ import annotations
import hashlib,json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1];DATA=ROOT/'data'
def load(n):return json.loads((DATA/n).read_text())
def sha(n):return hashlib.sha256((DATA/n).read_bytes()).hexdigest()
def main():
 d2=load('PART_BT2777_M36_4_2_STABILIZER_CENSUS_summary.json');d3=load('PART_BT2778_METAPLECTIC_INTERFEROMETER_summary.json');d4=load('PART_BT2779_STRUCTURED_CX_COMPILER_summary.json');d6=load('PART_BT2781_REPEATER_REMOTE_SUM_summary.json');rom=load('PART_BT2767_M36_PREPARATION_ROM.json');rows={r['grade']:r for r in d2['rows']};s1280=d6['scenario_summary']['1280']['best_distillable_rate']
 checks={'distill_codes_5355':d2['search_space']['isotropic_rank2_codes']==5355,'distill_branches_21420':d2['search_space']['branches']==21420,'distill_no_improving_shallow':rows['shallow']['certified_nonimproving_branches']==rows['shallow']['m36_closed_branches']==35,'distill_no_improving_deep':rows['deep']['certified_nonimproving_branches']==rows['deep']['m36_closed_branches']==237,'distill_no_improving_mid':rows['mid']['certified_nonimproving_branches']==rows['mid']['m36_closed_branches']==11,'sensor_classes_34':d3['class_count']==34,'sensor_trace_pairs_33':d3['theta_pair_count']==33,'sensor_min_trace_one_ninth':abs(d3['minimum_nonzero_normalized_trace_magnitude']-1/9)<1e-12,'sensor_four_quadrature_budget':d3['total_detector_events_four_quadratures']==4*d3['shots_per_quadrature_hoeffding'],'compiler_group_51840':d4['checks']['group_elements']==51840,'compiler_pairs_40x12':d4['factorization']['cosets']==480 and d4['checks']['all_pairs_present'],'compiler_suffixes_108':d4['factorization']['suffixes']==108,'compiler_all_rewrites':d4['checks']['all_rewrites_verified'],'compiler_compression_gt_40':d4['memory_bits']['compression_ratio']>40,'rom_deterministic_schema':rom['schema'].endswith('.v2') and 'NumPy' in rom['determinism'],'repeater_fixed_points':d6['isotropic_recurrence']['fixed_points']==[1/9,1/3,1.0],'repeater_improvement_region':d6['isotropic_recurrence']['improvement_region']=='F > 1/3','repeater_1280_distillable':s1280 is not None and s1280['distillable'],'repeater_1280_segmented':s1280['segments']>1,'repeater_remote_rate_positive':s1280['remote_sum_rate_hz']>0}
 assert all(checks.values()),[k for k,v in checks.items() if not v];arts=['PART_BT2767_M36_PREPARATION_ROM.json','PART_BT2777_M36_4_2_STABILIZER_CENSUS_summary.json','PART_BT2778_METAPLECTIC_INTERFEROMETER_summary.json','PART_BT2779_STRUCTURED_CX_COMPILER_summary.json','PART_BT2781_REPEATER_REMOTE_SUM_summary.json'];out={'schema':'w33.pass2777_2781.five_frontiers.v1','status':'COMPLETE_LOCAL_EXACT_REMOTE_HARDWARE_PENDING','checks':checks,'check_count':len(checks),'artifact_sha256':{n:sha(n) for n in arts},'boundaries':{'distillation':'complete only for identical two-copy binary [[4,2]] stabilizer projections','sensor':'shot budget assumes independent phase-stable path measurements and calibrated determinant','compiler':'exact matrix accumulator remains upstream input','hardware':'Icarus/Yosys/nextpnr evidence must be observed remotely','repeater':'exact Bell-diagonal recurrences plus engineering scenarios, not measured end-to-end hardware'}};p=DATA/'PART_BT2777_BT2781_FIVE_FRONTIERS_results.json';p.write_text(json.dumps(out,indent=2,sort_keys=True)+'\n');print(f'PASS {len(checks)}/{len(checks)}; wrote {p}')
if __name__=='__main__':main()
