#!/usr/bin/env python3
from __future__ import annotations
import argparse, collections, hashlib, importlib.util, itertools, json, math
from fractions import Fraction
from pathlib import Path
import numpy as np
import sympy as sp

ROOT=Path(__file__).resolve().parents[1]
SPEC=importlib.util.spec_from_file_location('base',ROOT/'analysis/bt3187_3192_chromatic_defect_block_filter.py')
BASE=importlib.util.module_from_spec(SPEC); assert SPEC.loader; SPEC.loader.exec_module(BASE)
OUT=ROOT/'data/PART_BT3226_BT3234_PORT_SPIRAL_results.json'
def json_default(o):
 if isinstance(o,np.bool_): return bool(o)
 if isinstance(o,np.integer): return int(o)
 if isinstance(o,np.floating): return float(o)
 if o is sp.true: return True
 if o is sp.false: return False
 if isinstance(o,sp.Integer): return int(o)
 if isinstance(o,sp.Rational): return str(o)
 if isinstance(o,sp.Basic): return str(o)
 raise TypeError(f'not JSON serializable: {type(o).__name__}')


def cells_of(h,blocks):
 out=[]; by=[]
 for block in blocks:
  local=h[np.ix_(block,block)]
  comp=np.ones((12,12),dtype=np.int8)-np.eye(12,dtype=np.int8)-local
  unseen=set(range(12)); cc=[]
  while unseen:
   seed=min(unseen); unseen.remove(seed); q=[seed]; part={seed}
   while q:
    x=q.pop()
    for y in list(unseen):
     if comp[x,y]: unseen.remove(y); part.add(y); q.append(y)
   cc.append(sorted(block[x] for x in part))
  cc.sort(); assert tuple(sorted(map(len,cc)))==(4,4,4)
  by.append(cc); out.extend(cc)
 return out,by


def geometry():
 points,a,lines,edges,frames,m,h=BASE.build_geometry()
 _,blocks,_=BASE.canonical_blocks(points,a,lines,frames)
 cells,by=cells_of(h,blocks)
 d=np.zeros((540,45),dtype=np.int8)
 for j,b in enumerate(blocks): d[b,j]=1
 n=((d.T@m)>0).astype(np.int8)
 return points,a,lines,edges,frames,m,h,blocks,cells,by,n


def modular_span_closure(gens,p=1000003):
 """Exact dimension over F_p of algebra generated by integer matrices."""
 piv={}; basis=[]; queue=[]
 def add(mat):
  v=(np.asarray(mat,dtype=np.int64)%p).reshape(-1).copy()
  for col,bv in sorted(piv.items()):
   if v[col]: v=(v-v[col]*bv)%p
  nz=np.flatnonzero(v)
  if not len(nz): return False
  col=int(nz[0]); v=v*pow(int(v[col]),-1,p)%p
  for c,bv in list(piv.items()):
   if bv[col]: piv[c]=(bv-bv[col]*v)%p
  piv[col]=v; basis.append(np.asarray(mat,dtype=np.int64)%p); queue.append(len(basis)-1); return True
 for g in gens:add(g)
 qi=0
 while qi<len(queue):
  i=queue[qi]; qi+=1
  current=list(range(len(basis)))
  for j in current:
   add((basis[i]@basis[j])%p)
   add((basis[j]@basis[i])%p)
 return len(basis)


def port_terwilliger(h,blocks,cells):
 b=np.zeros((540,135),dtype=np.int8)
 for j,c in enumerate(cells): b[c,j]=1
 cmat=b.T@h@b
 r0=np.eye(135,dtype=np.int64)
 r1=(cmat==16).astype(np.int64); np.fill_diagonal(r1,0)
 r2=(cmat==1).astype(np.int64); np.fill_diagonal(r2,0)
 r3=np.ones((135,135),dtype=np.int64)-r0-r1-r2
 e=[]
 for r in [r0,r1,r2,r3]: e.append(np.diag(r[0].astype(np.int64)))
 dims={}
 for p in (1000003,1000033,1000037): dims[str(p)]=modular_span_closure([r0,r1,r2,r3,*e],p)
 A=np.zeros((45,45),dtype=np.int64)
 for i,j in itertools.combinations(range(45),2):
  if h[np.ix_(blocks[i],blocks[j])].sum(): A[i,j]=A[j,i]=1
 I=np.eye(45,dtype=np.int64); J=np.ones((45,45),dtype=np.int64); R=[I,A,J-I-A]
 E=[np.diag(r[0].astype(np.int64)) for r in R]
 bd={str(p):modular_span_closure([*R,*E],p) for p in (1000003,1000033,1000037)}
 return {
  'cell_port_terwilliger_dimension_mod_primes':dims,
  'block_terwilliger_dimension_mod_primes':bd,
  'generators':'four 135-cell relation matrices plus four dual subconstituent projectors at one base cell',
  'status':'EXACT_MODULAR_ALGEBRA_DIMENSION_AND_SDP_DATA_SURFACE_NO_RATIONAL_DUAL_BOUND',
  'boundary':'Matching dimensions at three large primes are exact finite-field computations and a strong characteristic-zero diagnostic, but no rational SDP dual certificate proving chi(H)>=11 was obtained.'
 }


def sat_shards(m,h):
 inc=[tuple(map(int,np.where(m[:,e])[0])) for e in range(240)]
 cands=[]
 for e1,e2 in itertools.combinations(range(1,240),2):
  score=(len(set(inc[0])&set(inc[e1]))+len(set(inc[0])&set(inc[e2]))+len(set(inc[e1])&set(inc[e2])),e1,e2)
  cands.append(score)
 _,e1,e2=min(cands)
 shards=[]
 for a in range(10):
  for b in range(10):
   assumptions=[5400+e1*10+a+1,5400+e2*10+b+1]
   payload=f'e1={e1};e2={e2};a={a};b={b};assumptions={assumptions}'
   shards.append({'id':f'{a:01d}{b:01d}','missing_colors':[a,b],'assumption_literals':assumptions,'sha256':hashlib.sha256(payload.encode()).hexdigest()})
 return {
  'base_dimacs_sha256':'6c0c3daac0ac1592fd3d84c45cad157c8e6e1b95ffe87b47868db4589c6b7cd5',
  'fixed_missing_edge0':9,'split_edges':[e1,e2],'shards':len(shards),
  'coverage':'Every model has exactly one missing color at each split edge, hence belongs to exactly one of 100 shards.',
  'disjointness':'Distinct shards contain contradictory one-hot missing-color assumptions.',
  'manifest_sha256':hashlib.sha256(json.dumps(shards,sort_keys=True,separators=(',',':')).encode()).hexdigest(),
  'proof_gate':'Each UNSAT shard must carry a checked DRAT/LRAT proof; any SAT shard must pass the independent 540-color model checker.',
  'status':'EXACT_DISJOINT_SHARD_SURFACE_NO_SOLVER_CERTIFICATES',
  'shard_records':shards
 }


def near_cover(m,h,blocks):
 colors=BASE.load_coloring(); sizes=collections.Counter(map(int,colors)); c=next(k for k,v in sizes.items() if v==60)
 cover=tuple(sorted(map(int,np.where(colors==c)[0]))); pos={v:i for i,v in enumerate(cover)}
 assert all(not h[u,v] for u,v in itertools.combinations(cover,2))
 edge_owner={}
 for v in cover:
  for e in np.where(m[v])[0]: assert int(e) not in edge_owner; edge_owner[int(e)]=pos[v]
 assert len(edge_owner)==240
 outside=[]
 for v in range(540):
  if v in pos: continue
  sig=tuple(sorted(edge_owner[int(e)] for e in np.where(m[v])[0]))
  assert len(sig)==4 and len(set(sig))==4
  outside.append((v,sig))
 mult=collections.defaultdict(list)
 for v,sig in outside: mult[sig].append(v)
 candidate_hist={}; alpha_hist={}; max_alpha={}; witnesses={}
 for d in range(1,7):
  total=math.comb(60,d); cand=collections.defaultdict(list)
  if d>=4:
   for v,sig in outside:
    rem=[x for x in range(60) if x not in sig]; base=sum(1<<x for x in sig)
    for extra in itertools.combinations(rem,d-4): cand[base+sum(1<<x for x in extra)].append(v)
  ch=collections.Counter(len(vs) for vs in cand.values()); ah=collections.Counter(); best=0; wit=None
  for mask,vs in cand.items():
   alpha=0; bestset=()
   for bits in range(1<<len(vs)):
    if bits.bit_count()<=alpha: continue
    selected=tuple(vs[i] for i in range(len(vs)) if bits>>i&1)
    if all(not h[u,w] for u,w in itertools.combinations(selected,2)): alpha=len(selected);bestset=selected
   ah[alpha]+=1
   if alpha>best: best=alpha;wit={'deleted_cover_frames':[cover[i] for i in range(60) if mask>>i&1], 'replacement_frames':list(bestset)}
  ah[0]+=total-len(cand)
  candidate_hist[str(d)]={str(k):int(v) for k,v in sorted(ch.items())}
  alpha_hist[str(d)]={str(k):int(v) for k,v in sorted(ah.items())}
  max_alpha[str(d)]=int(best)
  if wit:witnesses[str(d)]=wit
 loci=[]
 for sig,vs in sorted(mult.items()):
  if len(vs)!=8:continue
  sub=h[np.ix_(vs,vs)]
  parts=[tuple(comb) for comb in itertools.combinations(vs,4) if all(not h[u,w] for u,w in itertools.combinations(comb,2))]
  assert set(map(int,sub.sum(1)))=={4} and int(sub.sum()//2)==16 and len(parts)==2
  owners=tuple(cover[i] for i in sig)
  for part in parts:
   new=(set(cover)-set(owners))|set(part)
   assert len(new)==60 and all(not h[u,w] for u,w in itertools.combinations(new,2))
   assert len({int(e) for v in new for e in np.where(m[v])[0]})==240
  loci.append({'owner_indices':list(sig),'owner_frames':list(owners),'outside_frames':list(vs),'replacement_parts':[list(x) for x in parts]})
 assert len(loci)==5 and len(set().union(*(set(x['owner_frames']) for x in loci)))==20
 cover_hashes=set(); edge_cover_hist=collections.Counter()
 for choices in itertools.product(range(3),repeat=5):
  new=set(cover)
  for i,ch in enumerate(choices):
   if ch:
    new-=set(loci[i]['owner_frames']); new|=set(loci[i]['replacement_parts'][ch-1])
  assert len(new)==60 and all(not h[u,w] for u,w in itertools.combinations(new,2))
  edge_count=len({int(e) for v in new for e in np.where(m[v])[0]});edge_cover_hist[edge_count]+=1
  cover_hashes.add(hashlib.sha256(','.join(map(str,sorted(new))).encode()).hexdigest())
 assert len(cover_hashes)==3**5 and edge_cover_hist==collections.Counter({240:3**5})
 return {
  'frozen_cover_color':int(c),'cover_size':60,'outside_frames':480,
  'distinct_four_owner_signatures':len(mult),
  'signature_multiplicity_histogram':{str(k):int(v) for k,v in sorted(collections.Counter(map(len,mult.values())).items())},
  'deletion_size_to_candidate_count_histogram':candidate_hist,
  'deletion_size_to_max_compatible_replacement_histogram':alpha_hist,
  'maximum_compatible_replacements':max_alpha,'witnesses':witnesses,
  'exact_K44_switch_loci':loci,'commuting_switch_loci':5,
  'exact_cover_switch_family_size':3**5,'switch_family_coordinate_alphabet':'retain / replacement part A / replacement part B',
  'all_switch_family_members_cover_all_240_support_edges_once':True,
  'theorem':'The frozen 60-frame exact cover contains five disjoint four-frame loci. At each locus, the eight outside frames with the same four-owner signature induce K4,4; its two bipartition classes are the only four-frame replacements. The five switches commute, producing 3^5=243 distinct exact 60-frame covers.',
  'scope':'Complete for all deletions of at most six frames from this frozen cover and for the generated five-locus switch family; not a classification of all independent sets or all exact covers.'
 }


def proper(colors,h):
 return all(colors[u]!=colors[v] for u,v in zip(*np.where(np.triu(h,1))))


def kempe_audit(h):
 initial=BASE.load_coloring().astype(int); assert proper(initial,h)
 adj=[list(map(int,np.where(h[v])[0])) for v in range(540)]
 def comps(col,a,b):
  unseen={v for v,x in enumerate(col) if x in (a,b)};out=[]
  while unseen:
   s=min(unseen);unseen.remove(s);q=[s];cc=[s]
   while q:
    x=q.pop()
    for y in adj[x]:
     if y in unseen:unseen.remove(y);q.append(y);cc.append(y)
   out.append(tuple(sorted(cc)))
  return out
 def alternatives(col,v):return [x for x in range(11) if x!=col[v] and all(col[u]!=x for u in adj[v])]
 def enumerate_moves(col,target):
  before=int(np.sum(col==target));out=[]
  for v in map(int,np.where(col==target)[0]):
   for new in alternatives(col,v):
    t=col.copy();t[v]=new;out.append((int(np.sum(t==target)),('direct',v,new),t))
  for a,b in itertools.combinations(range(11),2):
   for cc in comps(col,a,b):
    t=col.copy();t[list(cc)]=[b if t[x]==a else a for x in cc];assert proper(t,h)
    out.append((int(np.sum(t==target)),('swap',a,b,cc),t.copy()))
    for v in map(int,np.where(t==target)[0]):
     for new in alternatives(t,v):
      q=t.copy();q[v]=new;out.append((int(np.sum(q==target)),('swap_recolor',a,b,cc,v,new),q))
  out.sort(key=lambda x:(x[0],len(x[1][3]) if x[1][0].startswith('swap') else 0,repr(x[1])))
  return before,out
 alt_hist={str(t):{str(k):int(v) for k,v in sorted(collections.Counter(len(alternatives(initial,int(x))) for x in np.where(initial==t)[0]).items())} for t in range(11)}
 records=[]
 for target in range(11):
  col=initial.copy();steps=[]
  while True:
   before,moves=enumerate_moves(col,target)
   improving=next((x for x in moves if x[0]<before),None)
   if improving is None:break
   after,mv,nxt=improving;assert proper(nxt,h)
   if mv[0]=='direct':payload={'kind':'direct','vertex':mv[1],'new_color':mv[2]}
   elif mv[0]=='swap':payload={'kind':'swap','colors':[mv[1],mv[2]],'component':list(mv[3])}
   else:payload={'kind':'swap_recolor','colors':[mv[1],mv[2]],'component':list(mv[3]),'vertex':mv[4],'new_color':mv[5]}
   steps.append({'before':before,'after':after,'move':payload});col=nxt
  final=int(np.sum(col==target));_,remaining=enumerate_moves(col,target)
  improving_count=sum(x[0]<final for x in remaining);assert improving_count==0 and proper(col,h)
  records.append({'target':target,'initial_size':int(np.sum(initial==target)),'final_size':final,'steps':steps,
                  'checked_neighborhood_move_count_at_local_optimum':len(remaining),'improving_moves_at_local_optimum':0,
                  'final_coloring_sha256':hashlib.sha256(bytes(map(int,col))).hexdigest()})
 assert {x['final_size'] for x in records}=={41}
 return {
  'alternative_color_count_histograms_on_initial_target_vertices':alt_hist,
  'deterministic_descent_records':records,
  'universal_local_floor_in_checked_neighborhood':41,
  'checked_neighborhood':'one direct recolor, or one connected bichromatic-component swap, optionally followed by one direct recolor of a target-colour vertex',
  'status':'EXPLICIT_PROPER_DESCENTS_TO_41_AND_EXHAUSTIVE_ONE_MOVE_LOCAL_OPTIMA_NO_TEN_COLORING',
  'boundary':'The recorded sequences are replayable and every terminal colouring exhausts the stated one-move neighborhood. This does not exclude longer non-monotone Kempe/Vizing sequences or prove chi(H)=11.'
 }


def oa_atlas(m,h,blocks,by,n):
 V4=[[(i^j) for j in range(4)] for i in range(4)]
 C4=[[(i+j)%4 for j in range(4)] for i in range(4)]
 def words_block(bi):
  local=by[bi]; maps=[{v:j for j,v in enumerate(cell)} for cell in local]; words=[]; edge_to_word={}
  for e in map(int,np.where(n[bi])[0]):
   selected=[v for v in blocks[bi] if m[v,e]]
   w=tuple(maps[q][next(v for v in selected if v in local[q])] for q in range(3))
   words.append(w);edge_to_word[e]=w
  return sorted(words),edge_to_word
 def latin(words):
  L=[[-1]*4 for _ in range(4)]
  for a,b,c in words:L[a][b]=c
  assert all(x>=0 for row in L for x in row);return L
 def isotopic(L,T):
  perms=list(itertools.permutations(range(4)))
  for pr in perms:
   for pc in perms:
    mp={};ok=True
    for i in range(4):
     for j in range(4):
      s=L[pr[i]][pc[j]];t=T[i][j]
      if s in mp and mp[s]!=t:ok=False;break
      mp[s]=t
     if not ok:break
    if ok and len(mp)==4 and len(set(mp.values()))==4:return {'row_perm':pr,'col_perm':pc,'sym_perm':[mp[x] for x in range(4)]}
  return None
 types=collections.Counter(); examples={}
 for bi in range(45):
  ws,_=words_block(bi);L=latin(ws);iv=isotopic(L,V4);ic=isotopic(L,C4)
  typ='V4' if iv else ('C4' if ic else 'other');types[typ]+=1
  examples.setdefault(typ,{'block':bi,'latin':L,'isotopy':iv or ic})
 tri_hol= {'S3_holonomy_values':6,'matching_triples_per_support_triangle':6**3,'matching_triples_per_holonomy':6**2}
 support_blocks=[tuple(map(int,np.where(n[:,e])[0])) for e in range(240)]
 assert set(map(len,support_blocks))=={3}
 return {
  'local_OA_isotopy_types':dict(types),'examples':examples,
  'support_triangles':240,'blocks_per_support':3,
  'transport_obstruction':tri_hol,
  'theorem':'The local OA atlas is exact. The finite geometry supplies K3,3 relations, not canonical bijections; choosing a perfect matching gives an S3 gauge variable. Around each support triangle all six holonomies occur equally often (36 of 216 matching triples each), so no intrinsic voltage/curvature is selected without additional hardware or phase data.',
  'boundary':'Any nontrivial global holonomy requires an externally specified matching/phase convention; it is not determined by the incidence geometry alone.'
 }


def z9_surface(m,h,blocks,by,n):
 colors=BASE.load_coloring().astype(int)
 def check(col,k):
  onehot=sum(((1 if 0<=x<k else 0)-1)**2 for x in col)
  edgecoll=0; missing=[]
  for e in range(240):
   fs=np.where(m[:,e])[0]; vals=[int(col[v]) for v in fs]
   edgecoll+=len(vals)-len(set(vals));missing.append(k-len(set(vals)))
  cellviol=0
  for local in by:
   for c in range(k):
    used=[sum(col[v]==c for v in cell) for cell in local]
    cellviol+=sum(used[i]*used[j] for i,j in itertools.combinations(range(3),2))
  return {'onehot_residual_mod9':onehot%9,'edge_collision_residual':edgecoll,'missing_count_histogram':dict(collections.Counter(missing)),'cell_exclusivity_residual_mod9':cellviol%9,'valid':onehot==0 and edgecoll==0 and cellviol==0}
 good=check(colors,11); bad=colors.copy();bad[0]=bad[int(np.where(h[0])[0][0])];mut=check(bad,11)
 inv={'frame_boolean':5400,'frame_onehot':540,'edge_pairwise_distinct':86400,'missing_boolean':2400,'missing_onehot':240,'missing_frame_coupling':21600,'cell_exclusivity_quadratics':45*10*3}
 return {
  'ring':'Z/9Z','polynomial_inventory':inv,'frozen_11_color_positive_control':good,'single_collision_negative_control':mut,
  'status':'NONLINEAR_PORT_LIFT_CHECKER_READY_NO_TEN_COLOR_DECISION',
  'conclusion':'The first port-specific constraint absent from the Smith/linear layer is cell exclusivity: for each block and color, occupancies in distinct K4 cells have pairwise product zero. The checker catches a properness mutation, but no Z/9 contradiction for ten colors has been certified.'
 }


def spiral_exact():
 phi=(sp.Integer(1)+sp.sqrt(5))/2
 R4=sp.Matrix([[0,-1,0],[1,0,0],[0,0,1]])
 U6=sp.Matrix([[1,0,0],[0,0,1],[0,-1,1]])
 M=R4**2*U6;B=M[1:3,1:3]
 I=sp.I;C=sp.Matrix([[I,-1],[1,0]])
 a,b,c,d=sp.symbols('a b c d');P=sp.Matrix([[a,b],[c,d]])
 sol=sp.linsolve(list(C*P-P*(I*B)),(a,b,c,d))
 basis=list(sol)[0]
 params=sorted(set().union(*(x.free_symbols for x in basis)),key=str)
 chosen=None
 vals=[0,1,2,-1,I,-I]
 for tup in itertools.product(vals,repeat=len(params)):
  Q=sp.Matrix(2,2,[sp.simplify(x.subs(dict(zip(params,tup)))) for x in basis])
  if sp.simplify(Q.det())!=0: chosen=Q;break
 assert chosen is not None and sp.simplify(C*chosen-chosen*(I*B))==sp.zeros(2)
 J=sp.Matrix([[0,-1],[1,0]]);Omega=sp.Matrix([[0,1],[-1,0]])
 L=sp.Matrix([[-2,1],[1,2]])
 G=Omega*J
 checks={
  'M_charpoly':sp.factor(M.charpoly().as_expr())== (sp.Symbol('lambda')+1)*(sp.Symbol('lambda')**2-sp.Symbol('lambda')-1),
  'B_charpoly':sp.factor(B.charpoly().as_expr())==sp.Symbol('lambda')**2-sp.Symbol('lambda')-1,
  'C_charpoly':sp.factor(C.charpoly().as_expr())==sp.Symbol('lambda')**2-sp.I*sp.Symbol('lambda')+1,
  'similarity_C_to_iB':sp.simplify(C*chosen-chosen*(I*B))==sp.zeros(2),
  'symplectic_quarter_turn':J.T*Omega*J==Omega,
  'metric_from_omega_J':G==sp.eye(2),
  'B_lorentz_anti_isometry':B.T*L*B==-L,
  'B_squared_lorentz_isometry':(B**2).T*L*(B**2)==L,
  'phase_lift_symplectic':C.T*Omega*C==Omega,
 }
 assert all(checks.values())
 examples={1:[0],2:[1,-2],3:[2,-2],14:[5,2,-3,-6]}
 evals={str(n):sp.simplify(sum(phi**k for k in exps)) for n,exps in examples.items()}
 assert all(v==int(k) for k,v in evals.items())
 return {
  'R4':R4.tolist(),'U6':U6.tolist(),'R4_squared_U6':M.tolist(),'golden_plane_block':B.tolist(),
  'golden_plane_eigenvalues':['phi','-1/phi'],'phase_lift_companion':[['i','-1'],['1','0']],
  'phase_lift_eigenvalues':['i*phi','-i/phi'],'similarity_matrix':[[str(x) for x in row] for row in chosen.tolist()],
  'unit_spiral_definition':'u_k=(phi*exp(i alpha))^k; for alpha=pi/2, u_{k+2}=i u_{k+1}-u_k and the companion determinant is 1.',
  'recursive_iterative_duality':'On the universal logarithmic cover (rho,theta)=(k log phi,k pi/2), the discrete spiral is a straight lattice line. Exponentiating to the punctured plane makes it a four-armed logarithmic spiral. The symplectic quarter-turn (rho,theta)->(-theta,rho) exchanges radial and angular roles and sends pitch a to -1/a.',
  'lorentz_duality':{'metric':L.tolist(),'one_step':'B^T L B = -L','two_step':'(B^2)^T L (B^2) = L','boost_eigenvalues':['phi^2','phi^-2'],'rapidity':'2 log(phi)','boundary':'This is an exact O(1,1)-type algebraic analogy on the golden plane, not evidence that the controller is physical spacetime.'},
  'perpendicular_space_correction':'A tangent vector does not by itself become a metric tensor. The exact symplectic statement is v -> i_v omega in T*, and a compatible quarter-turn J recovers g(v,w)=omega(v,Jw). For nested orthogonal loops use the direct sum omega_n=sum_k d rho_k wedge d theta_k; return coupling is an extra boundary map, not automatic orthogonality.',
  'phigital_examples_exponents':{str(k):v for k,v in examples.items()},
  'phigital_geometry_boundary':'Base-phi/phigital arithmetic is standard at alpha=0. The alpha=pi/2 spiral lift is a new phase embedding used here; it preserves the golden recurrence and determinant-one dual mode, but it is not a standard numeral system and is not a physical relativity law.',
  'checks':checks
 }


def physical_compiler(m,blocks,by,n):
 words=[]
 for bi in range(45):
  maps=[{v:j for j,v in enumerate(cell)} for cell in by[bi]]
  for slot,e in enumerate(sorted(map(int,np.where(n[bi])[0]))):
   selected=[v for v in blocks[bi] if m[v,e]]
   w=tuple(maps[q][next(v for v in selected if v in by[bi][q])] for q in range(3))
   words.append((bi,slot,e,*w))
 assert len(words)==720 and len({(b,s) for b,s,*_ in words})==720
 inv=True
 for bi in range(45):
  local=[x for x in words if x[0]==bi]
  for i,j in itertools.combinations(range(3),2): inv &= len({(x[3+i],x[3+j]) for x in local})==16
 return {
  'rom_entries':720,'rom_word_bits':14,'payload':'8-bit global support edge plus three 2-bit local port labels',
  'forward_address_bits':10,'inverse_from_any_two_ports':bool(inv),
  'logical_rom_bits':720*14,
  'status':'SYNTHESIZABLE_SOURCE_MODEL_READY_PLACEMENT_UNOBSERVED',
  'boundary':'The compiler emits exact incidence labels. It does not choose one of the six K3,3 physical matchings and does not establish optical loss, timing, FPGA area or Landauer dissipation.'
 }


def certificate():
 points,a,lines,edges,frames,m,h,blocks,cells,by,n=geometry()
 data={
  'schema':'w33.pass3226_3234.port_spiral.v1',
  'live_chromatic_boundary':'10 <= chi(H) <= 11',
  'pass3226_port_sat':sat_shards(m,h),
  'pass3227_port_terwilliger':port_terwilliger(h,blocks,cells),
  'pass3228_near_cover':near_cover(m,h,blocks),
  'pass3229_kempe_vizing':kempe_audit(h),
  'pass3230_oa_voltage':oa_atlas(m,h,blocks,by,n),
  'pass3231_z9_lift':z9_surface(m,h,blocks,by,n),
  'pass3232_physical_port_compiler':physical_compiler(m,blocks,by,n),
  'pass3233_3234_unit_spiral_phigital':spiral_exact(),
  'claim_boundary':'No ten-colouring or checked UNSAT proof was obtained; no rational SDP dual bound above nine, general near-cover theorem, complete Kempe obstruction, nontrivial Z/9 contradiction, observed RTL/synthesis/PDF result, or physical spiral/relativity claim is made.'
 }
 data['sha256_without_hash_field']=hashlib.sha256(json.dumps(data,sort_keys=True,separators=(',',':'),default=json_default).encode()).hexdigest()
 return data

def verify_ten_coloring(path):
 tok=list(map(int,Path(path).read_text().split()));tok=tok[1:] if len(tok)==541 and tok[0]==10 else tok
 if len(tok)!=540:return {'valid':False,'reason':'expected 540 colours'}
 col=np.asarray(tok,dtype=int);*_,m,h=BASE.build_geometry()
 proper_ok=all(col[u]!=col[v] for u,v in zip(*np.where(np.triu(h,1))))
 missing=[set(range(10))-set(map(int,col[np.where(m[:,e])[0]])) for e in range(240)]
 return {'valid':bool(set(map(int,col))<=set(range(10)) and proper_ok and all(len(x)==1 for x in missing)),
         'proper':bool(proper_ok),'class_sizes':{str(k):int(v) for k,v in sorted(collections.Counter(map(int,col)).items())},
         'one_missing_color_per_support':bool(all(len(x)==1 for x in missing))}


def emit_rom(path):
 _,_,_,_,_,m,_,blocks,_,by,n=geometry();rows=[]
 for bi in range(45):
  maps=[{v:j for j,v in enumerate(cell)} for cell in by[bi]]
  for e in sorted(map(int,np.where(n[bi])[0])):
   selected=[v for v in blocks[bi] if m[v,e]]
   ports=tuple(maps[q][next(v for v in selected if v in by[bi][q])] for q in range(3))
   rows.append((e<<6)|(ports[0]<<4)|(ports[1]<<2)|ports[2])
 assert len(rows)==720
 Path(path).write_text('\n'.join(f'{x:04x}' for x in rows)+'\n')
 return hashlib.sha256(Path(path).read_bytes()).hexdigest()


if __name__=='__main__':
 ap=argparse.ArgumentParser();ap.add_argument('--verify-model');ap.add_argument('--emit-rom');args=ap.parse_args()
 if args.verify_model:
  verdict=verify_ten_coloring(args.verify_model);print(json.dumps(verdict,indent=2,sort_keys=True));raise SystemExit(0 if verdict['valid'] else 1)
 data=certificate(); OUT.write_text(json.dumps(data,indent=2,sort_keys=True,default=json_default)+'\n')
 if args.emit_rom:data['rom_sha256']=emit_rom(args.emit_rom)
 print(json.dumps({'sha256':data['sha256_without_hash_field'],'status':'PASS_EXACT_EIGHT_FRONT_SOURCE'},sort_keys=True))
