#!/usr/bin/env python3
"""
BT701-local — Braid-word functor boundary for the local K33 cycle register.

BT698 built the dimension-preserving register functor
    H1(K33;F2) ~= F2^4 -> (C^2_Fib)^tensor4.
BT701-local upgrades this to the first braid-word boundary statement.

A four-Fibonacci-anyon fixed-total-charge block is a two-state module.  A braid
representation on that block is generated by adjacent braid generators acting
on that two-dimensional fusion basis.  Therefore:

  * one block can encode one binary cycle bit;
  * four independent blocks encode the full 16-state [9,4,4] K33 cycle code;
  * two Fibonacci blocks encode only a rank-2 quotient of H1(K33;F2), not the
    full cycle code.

This script verifies the K33 cycle basis, the full tensor dimension, and the
rank losses for representative quotient maps.
"""
from __future__ import annotations
from itertools import product
from collections import Counter
import numpy as np


def gf2_rank(M: np.ndarray) -> int:
    A = (M.copy() % 2).astype(np.uint8)
    m, n = A.shape
    r = 0
    for c in range(n):
        pivot = None
        for i in range(r, m):
            if A[i,c]:
                pivot = i
                break
        if pivot is None:
            continue
        if pivot != r:
            A[[r,pivot]] = A[[pivot,r]]
        for i in range(m):
            if i != r and A[i,c]:
                A[i] ^= A[r]
        r += 1
        if r == m:
            break
    return r


def main() -> None:
    # K33 edges L_i--R_j.
    edges = [(i,j) for i in range(3) for j in range(3)]
    idx = {e:i for i,e in enumerate(edges)}
    H = np.zeros((6,9), dtype=np.uint8)
    for e,(i,j) in enumerate(edges):
        H[i,e] = 1
        H[3+j,e] = 1
    assert gf2_rank(H) == 5
    assert 9 - gf2_rank(H) == 4

    tree = [(0,0),(0,1),(0,2),(1,0),(2,0)]
    chords = [e for e in edges if e not in tree]
    assert chords == [(1,1),(1,2),(2,1),(2,2)]

    basis = []
    for i,j in chords:
        rect = [(0,0),(i,0),(i,j),(0,j)]
        v = np.zeros(9, dtype=np.uint8)
        for e in rect:
            v[idx[e]] = 1
        assert int(v.sum()) == 4
        assert np.all((H @ v) % 2 == 0)
        basis.append(v)
    B = np.stack(basis, axis=1)
    assert gf2_rank(B.T) == 4

    code = set()
    weight = Counter()
    for bits in product([0,1], repeat=4):
        cw = tuple(int(x) for x in ((B @ np.array(bits, dtype=np.uint8)) % 2))
        code.add(cw)
        weight[sum(cw)] += 1
    assert len(code) == 16
    assert min(w for w in weight if w > 0) == 4

    # Full Fibonacci register: four two-state blocks.
    full_blocks = 4
    full_dim = 2**full_blocks
    assert full_dim == 16

    # A two-block architecture can only carry rank 2.  Test representative
    # quotient maps F2^4 -> F2^2.
    quotient_maps = {
        "first_two_bits": np.array([[1,0,0,0],[0,1,0,0]], dtype=np.uint8),
        "pair_parities": np.array([[1,0,0,1],[0,1,1,0]], dtype=np.uint8),
        "row_col_parities": np.array([[1,1,0,0],[1,0,1,0]], dtype=np.uint8),
    }
    for name,Q in quotient_maps.items():
        assert gf2_rank(Q) == 2, name
        image = {tuple(int(x) for x in (Q @ np.array(bits, dtype=np.uint8)) % 2)
                 for bits in product([0,1], repeat=4)}
        assert len(image) == 4, name

    print("BT701-local braid-word functor boundary: PASS")
    print("K33_cycle_code=[9,4,4]")
    print("cycle_rank=4")
    print("code_states=16")
    print("fundamental_rectangle_basis=4")
    print("full_fibonacci_blocks_required=4")
    print("full_tensor_dimension=16")
    print("two_block_architecture_dimension=4")
    print("two_block_architecture_is_quotient=True")
    print("braid_boundary=need explicit braid generators per block for representation functor")


if __name__ == "__main__":
    main()
