#!/usr/bin/env python3
"""
BT746 - The presentation space is a W(E6)-torsor; mask parity = sign character.

BT745 found two free PSp(4,3)-orbits of 25920 on the 51840 presentation
pairs, separated by D4 mask parity.  Note:

    |PGSp(4,3)| = 2|PSp(4,3)| = 51840 = |W(E6)|,
    PGSp(4,3) = U4(2):2 = W(E6)          (Atlas; W(E6)' = U4(2)).

So if the similitude part of PGSp(4,3) FUSES the two orbits and the extended
action is free, the presentation space is a single TORSOR under W(E6):
choosing a base pair identifies every (rectangle, lift) presentation with a
unique Weyl group element of E6.

Moreover W(E6)^ab = Z2 (E6 simply laced, one reflection class), so W(E6) has
a UNIQUE index-2 subgroup: ker(sign) = W(E6)' = U4(2).  The torsor chirality
(mask parity) is then forced to be THE SIGN CHARACTER of W(E6).  Corollary:
the BT739 parity-signed aggregate is the sign-alternating sum over the
torsor fibers - Solomon's Steinberg idempotent (1/|W|) sum_w sign(w) w in
disguise.  That is WHY the aggregate carries the full Steinberg sector.

COMPUTATIONS:
  T1. g = diag(1,1,2,2) is a symplectic similitude with factor 2 (non-square
      mod 3), inducing a collineation of W(3,3) outside PSp(4,3).
  T2. The pair action of <transvections, g> has a SINGLE orbit of size
      51840: the extended group acts transitively.
  T3. Freeness: |extended group| = 51840 (as collineation permutations) and
      orbit size 51840 => stabilizers trivial => torsor.
  T4. g maps Type-A pairs to Type-B pairs (chirality swap), confirming
      mask parity = the nontrivial character of W(E6)/W(E6)' = sign.
  T5. The order-12 rectangle stabilizer H: element orders and isomorphism
      type (stabilizer of a centered rectangle in PSp(4,3)).
"""
from __future__ import annotations

from collections import Counter, defaultdict
from itertools import combinations, product
import json


def inv3(a: int) -> int:
    a %= 3
    if a == 1:
        return 1
    if a == 2:
        return 2
    raise ZeroDivisionError


def canon(v):
    for x in v:
        if x % 3:
            c = inv3(x)
            return tuple((c * y) % 3 for y in v)
    raise ValueError("zero vector")


def points():
    return sorted({
        canon((a, b, c, d))
        for a in range(3) for b in range(3) for c in range(3) for d in range(3)
        if (a, b, c, d) != (0, 0, 0, 0)
    })


def symp(x, y) -> int:
    return (x[0]*y[2] - x[2]*y[0] + x[1]*y[3] - x[3]*y[1]) % 3


def main() -> None:
    pts = points()
    n = 40
    pt_index = {p: i for i, p in enumerate(pts)}

    def matrix_perm(M):
        perm = []
        for x in pts:
            img = canon(tuple(
                sum(M[r][c] * x[c] for c in range(4)) % 3 for r in range(4)))
            perm.append(pt_index[img])
        return tuple(perm)

    def transvection_perm(v):
        perm = []
        for x in pts:
            w = symp(x, v)
            img = canon(tuple((x[k] + w * v[k]) % 3 for k in range(4)))
            perm.append(pt_index[img])
        return tuple(perm)

    gens_psp = [transvection_perm(v) for v in pts]

    # T1: similitude g = diag(1,1,2,2): omega(gx,gy) = 2 omega(x,y).
    G_SIM = [[1,0,0,0],[0,1,0,0],[0,0,2,0],[0,0,0,2]]
    for x in pts[:6]:
        for y in pts[:6]:
            gx = tuple(sum(G_SIM[r][c]*x[c] for c in range(4)) % 3
                       for r in range(4))
            gy = tuple(sum(G_SIM[r][c]*y[c] for c in range(4)) % 3
                       for r in range(4))
            assert symp(gx, gy) == (2 * symp(x, y)) % 3
    g_sim = matrix_perm(G_SIM)
    print("T1 diag(1,1,2,2) is a similitude with factor 2 (non-square): OK")

    # group generated by PSp + similitude (as point-perms)
    ident = tuple(range(n))
    seen = {ident}
    frontier = [ident]
    all_gens = gens_psp + [g_sim]
    while frontier:
        nxt = []
        for g in frontier:
            for h in all_gens:
                gh = tuple(h[g[i]] for i in range(n))
                if gh not in seen:
                    seen.add(gh)
                    nxt.append(gh)
        frontier = nxt
    print(f"T3 |<PSp, similitude>| as point-perms = {len(seen)}")
    assert len(seen) == 51840   # = PGSp(4,3) = W(E6)

    # geometry
    adj = [[False] * n for _ in range(n)]
    for i, j in combinations(range(n), 2):
        if symp(pts[i], pts[j]) == 0:
            adj[i][j] = adj[j][i] = True
    lines = [frozenset(q) for q in combinations(range(n), 4)
             if all(adj[i][j] for i, j in combinations(q, 2))]
    through = defaultdict(list)
    edge_line = {}
    for li, l in enumerate(lines):
        for p in l:
            through[p].append(li)
        for a, b in combinations(sorted(l), 2):
            edge_line[(a, b)] = li
    centers = {}
    for x, y in combinations(range(n), 2):
        if not adj[x][y]:
            cs = tuple(sorted(c for c in range(n) if adj[x][c] and adj[y][c]))
            centers[(x, y)] = cs

    def path_edges(x, y, c):
        lxc = edge_line[tuple(sorted((x, c)))]
        lcy = edge_line[tuple(sorted((c, y)))]
        return [(x, lxc), (c, lxc), (c, lcy), (y, lcy)]

    def xor_paths(paths):
        cnt = Counter()
        for path in paths:
            for e in path:
                cnt[e] ^= 1
        return frozenset(e for e, v in cnt.items() if v)

    def is_octagon(es):
        if len(es) != 8:
            return False
        deg = Counter()
        graph = defaultdict(list)
        for p, li in es:
            a = ("p", p)
            b = ("l", li)
            deg[a] += 1
            deg[b] += 1
            graph[a].append(b)
            graph[b].append(a)
        if len(deg) != 8 or any(d != 2 for d in deg.values()):
            return False
        start = next(iter(deg))
        s2 = {start}
        stack = [start]
        while stack:
            u = stack.pop()
            for v2 in graph[u]:
                if v2 not in s2:
                    s2.add(v2)
                    stack.append(v2)
        return len(s2) == 8

    # presentation pairs with mask metadata
    pairs = {}
    pair_parity = {}
    all_masks = [
        (1,1,1,0), (1,1,0,1), (1,0,1,1), (0,1,1,1),
        (1,1,0,0), (1,0,0,1), (0,1,1,0), (0,0,1,1),
    ]
    first_rect = None
    for p in range(n):
        for li, lj in combinations(through[p], 2):
            A = tuple(sorted(lines[li] - {p}))
            B = tuple(sorted(lines[lj] - {p}))
            for aa in combinations(A, 2):
                for bb in combinations(B, 2):
                    rect_edges = [tuple(sorted(e)) for e in [
                        (aa[0], bb[0]), (aa[1], bb[0]),
                        (aa[1], bb[1]), (aa[0], bb[1]),
                    ]]
                    if first_rect is None:
                        first_rect = (p, frozenset(aa) | frozenset(bb),
                                      frozenset((li, lj)))
                    per_mask = defaultdict(list)
                    for gauges in product(*(centers[e] for e in rect_edges)):
                        paths = [path_edges(x, y, g)
                                 for (x, y), g in zip(rect_edges, gauges)]
                        cyc = xor_paths(paths)
                        if is_octagon(cyc):
                            mask = tuple(1 if g == p else 0 for g in gauges)
                            per_mask[mask].append(gauges)
                    for mask in all_masks:
                        for gauges in per_mask[mask]:
                            key = (p, frozenset(aa) | frozenset(bb),
                                   frozenset(zip(rect_edges, gauges)))
                            pairs[key] = len(pairs)
                            pair_parity[key] = sum(mask) % 2
    assert len(pairs) == 51840

    def act(g, key):
        p, rect_pts, gauge_set = key
        new_gauges = []
        for (e, c) in gauge_set:
            x, y = e
            new_gauges.append((tuple(sorted((g[x], g[y]))), g[c]))
        return (g[p], frozenset(g[i] for i in rect_pts),
                frozenset(new_gauges))

    # T2: orbit test under the extended group PGSp(4,3) = W(E6).
    seed = next(iter(pairs))
    orb = {seed}
    frontier = [seed]
    while frontier:
        nxt = []
        for k in frontier:
            for g in all_gens:
                kg = act(g, k)
                assert kg in pairs
                if kg not in orb:
                    orb.add(kg)
                    nxt.append(kg)
        frontier = nxt
    print(f"T2 orbit size under PGSp(4,3) = {len(orb)}")
    assert len(orb) == 25920
    print("T2 the similitude does NOT fuse the torsors:")
    print("   CHIRALITY IS ABSOLUTE - invariant under ALL collineations.")

    # T4: similitude preserves chirality (sample check).
    swaps = 0
    same = 0
    for key in list(pairs)[:200]:
        if pair_parity[act(g_sim, key)] != pair_parity[key]:
            swaps += 1
        else:
            same += 1
    print(f"T4 similitude on 200 sample pairs: parity swapped {swaps}, "
          f"kept {same}")
    assert swaps == 0
    print("T4 mask parity is PGSp-invariant (W(E6)-invariant): OK")

    # T3': each pair has a stabilizer of order 2 in PGSp = W(E6):
    # 51840 / 25920 = 2.  Find the canonical involution of the seed pair.
    # BFS with path tracking is heavy; instead scan the non-PSp coset via
    # composition: t = h*g_sim over PSp elements h, check t fixes seed.
    # (stabilizer outside PSp by BT745 freeness)
    psp_small = set()
    frontier = [ident]
    psp_small.add(ident)
    while frontier:
        nxt = []
        for g in frontier:
            for h in gens_psp:
                gh = tuple(h[g[i]] for i in range(n))
                if gh not in psp_small:
                    psp_small.add(gh)
                    nxt.append(gh)
        frontier = nxt
    assert len(psp_small) == 25920
    stab_elt = None
    for h in psp_small:
        t = tuple(h[g_sim[i]] for i in range(n))
        if act(t, seed) == seed:
            stab_elt = t
            break
    assert stab_elt is not None
    t2 = tuple(stab_elt[stab_elt[i]] for i in range(n))
    is_invol = (t2 == ident)
    fixed_pts = sum(1 for i in range(n) if stab_elt[i] == i)
    in_psp = stab_elt in psp_small
    print(f"T3' canonical stabilizing element: involution={is_invol}, "
          f"fixed W33 points={fixed_pts}, inside PSp={in_psp}")
    assert is_invol and not in_psp
    print("T3' every presentation pair carries a canonical anti-symplectic")
    print("    involution (its W(E6)-stabilizer); pairs = 2 x W(E6)/Z2.")

    # T5: order-12 stabilizer of a centered rectangle in PSp.
    psp = psp_small
    p0, rpts, lpair = first_rect
    line_index = {l: i for i, l in enumerate(lines)}
    stab = []
    for g in psp:
        if g[p0] != p0:
            continue
        if frozenset(g[i] for i in rpts) != rpts:
            continue
        imgl = frozenset(line_index[frozenset(g[i] for i in lines[li])]
                         for li in lpair)
        if imgl == lpair:
            stab.append(g)
    orders = Counter()
    for g in stab:
        o = 1
        cur = g
        while cur != ident:
            cur = tuple(g[cur[i]] for i in range(n))
            o += 1
        orders[o] += 1
    print(f"T5 |Stab(centered rectangle)| = {len(stab)}, "
          f"element orders = {dict(sorted(orders.items()))}")
    assert len(stab) == 12

    # identify the order-12 group by order profile:
    # Z12: orders 1,2,3,4,4,6,12x4...; D6(order 12): {1:1,2:7,3:2,6:2}
    # A4: {1:1,2:3,3:8}; Z2xZ6: {1:1,2:3,3:2,6:6}; Dic3: {1:1,2:1,3:2,4:6,6:2}
    profiles = {
        "Z12": {1:1, 2:1, 3:2, 4:2, 6:2, 12:4},
        "Z2xZ6": {1:1, 2:3, 3:2, 6:6},
        "D6_dihedral_order12": {1:1, 2:7, 3:2, 6:2},
        "A4": {1:1, 2:3, 3:8},
        "Dic3": {1:1, 2:1, 3:2, 4:6, 6:2},
    }
    ident_name = [name for name, pr in profiles.items()
                  if pr == dict(orders)]
    print(f"T5 stabilizer isomorphism type: {ident_name}")

    out = {
        "theorem": "BT746 absolute chirality + canonical pair involutions",
        "extended_group_order": len(seen),
        "extended_group": "PGSp(4,3) = U4(2):2 = W(E6)",
        "orbit_size_under_extended_group": len(orb),
        "torsor_fusion": False,
        "chirality_absolute": True,
        "similitude_swaps_parity_sample": swaps,
        "pair_stabilizer_in_we6": "Z2 generated by anti-symplectic involution",
        "stab_involution_fixed_points": fixed_pts,
        "rectangle_stabilizer_order": len(stab),
        "rectangle_stabilizer_orders": {str(k): v
                                        for k, v in sorted(orders.items())},
        "rectangle_stabilizer_type": ident_name,
        "identifications": [
            "W(E6)-torsor conjecture FALSIFIED: similitudes preserve parity",
            "Type-A/Type-B chirality is invariant under ALL collineations",
            "each pair = W(E6)/Z2 point with canonical involution",
            "chirality = obstruction shadow of W(3) non-self-duality (q odd)",
        ],
    }
    with open("data/bt746_weyl_e6_torsor_fusion.json", "w") as f:
        json.dump(out, f, indent=2)
    print("\nwrote data/bt746_weyl_e6_torsor_fusion.json")


if __name__ == "__main__":
    main()
