#!/usr/bin/env python3
"""
BT865 - Dual torsor Steinberg compiler.

BT858 identified two canonical order-27 translation groups:

  * the point shell is a torsor for the extraspecial Heisenberg group
    3^(1+2), exponent 3;
  * the Bell-line shell is a torsor for the elementary group F3^3.

BT861 identified H1 of the W(3,3) triangle complex with the 81-dimensional
Steinberg module, and BT863 verified Steinberg-character vanishing on every
nonidentity element of either order-27 group.  This script closes the bridge.

  T1  On both torsors, St restricted to O3 has character 3 times the regular
      character: St|O3 = 3 Reg(O3) over C.
  T2  Over the code's native field F3, construct three explicit cyclic
      O3-submodules in H1.  Each is generated by one cycle and its 27 group
      translates; together they give an 81-dimensional basis modulo
      boundaries.  Thus H1(F3)|O3 is free of rank 3 over F3[O3].
  T3  The Heisenberg center Z = C3 is the canonical triality axis.  Over C
      its three central-character sectors have dimensions 27,27,27.  Over
      F3 they coalesce into a unipotent Jordan filtration: for N=z-I on H1,
      rank(N), rank(N^2), rank(N^3) = 54,27,0, so ker(N) subset ker(N^2)
      subset H1 has dimensions 27,54,81 and three 27-dimensional quotients.
  T4  Every one of the 13 projective C3 directions in either O3 has the same
      native Jordan profile.  Only the Heisenberg side has a characteristic
      direction: its unique center.

The three orbit generators found below are deterministic witnesses, not a
claim of a canonical basis.  The canonical statements are freeness, the
Heisenberg center, and its filtration.
"""
from __future__ import annotations

from collections import Counter
from itertools import combinations, product
import json
import random


P = 3


def canon(v):
    for x in v:
        if x % P:
            scale = 1 if x % P == 1 else 2
            return tuple((scale * y) % P for y in v)
    raise ValueError("zero vector")


def rref_mod3(matrix):
    a = [[int(x) % P for x in row] for row in matrix]
    rows = len(a)
    cols = len(a[0]) if rows else 0
    pivots = []
    r = 0
    for c in range(cols):
        pivot = next((i for i in range(r, rows) if a[i][c]), None)
        if pivot is None:
            continue
        a[r], a[pivot] = a[pivot], a[r]
        if a[r][c] == 2:
            a[r] = [(2 * x) % P for x in a[r]]
        for i in range(rows):
            if i == r or not a[i][c]:
                continue
            factor = a[i][c]
            a[i] = [(a[i][j] - factor * a[r][j]) % P
                    for j in range(cols)]
        pivots.append(c)
        r += 1
        if r == rows:
            break
    return a, pivots


def nullspace_mod3(matrix):
    rref, pivots = rref_mod3(matrix)
    cols = len(matrix[0])
    free = [c for c in range(cols) if c not in pivots]
    basis = []
    for f in free:
        v = [0] * cols
        v[f] = 1
        for row, p in enumerate(pivots):
            v[p] = (-rref[row][f]) % P
        basis.append(v)
    return basis, pivots


class GF3Span:
    """Incremental exact span in F3^n, stored in row-echelon form."""

    def __init__(self, vectors=()):
        self.pivots = {}
        for v in vectors:
            self.add(v)

    def copy(self):
        out = GF3Span()
        out.pivots = {p: v[:] for p, v in self.pivots.items()}
        return out

    @property
    def rank(self):
        return len(self.pivots)

    def reduce(self, vector):
        v = [int(x) % P for x in vector]
        while True:
            pivot = next((i for i, x in enumerate(v) if x), None)
            if pivot is None or pivot not in self.pivots:
                return v
            factor = v[pivot]
            row = self.pivots[pivot]
            v = [(v[i] - factor * row[i]) % P for i in range(len(v))]

    def add(self, vector):
        v = self.reduce(vector)
        pivot = next((i for i, x in enumerate(v) if x), None)
        if pivot is None:
            return False
        if v[pivot] == 2:
            v = [(2 * x) % P for x in v]
        self.pivots[pivot] = v
        return True


def main():
    pts = sorted({canon(v) for v in product(range(P), repeat=4) if any(v)})
    n = len(pts)
    pt_index = {p: i for i, p in enumerate(pts)}

    def symp(x, y):
        return (x[0] * y[2] - x[2] * y[0]
                + x[1] * y[3] - x[3] * y[1]) % P

    adj = [[False] * n for _ in range(n)]
    for i, j in combinations(range(n), 2):
        if symp(pts[i], pts[j]) == 0:
            adj[i][j] = adj[j][i] = True
    lines = [frozenset(q) for q in combinations(range(n), 4)
             if all(adj[i][j] for i, j in combinations(q, 2))]
    line_index = {line: i for i, line in enumerate(lines)}
    line_sets = [set(line) for line in lines]
    assert n == 40 and len(lines) == 40

    edges = sorted((i, j) for i, j in combinations(range(n), 2)
                   if adj[i][j])
    edge_index = {edge: i for i, edge in enumerate(edges)}
    triangles = sorted({tuple(sorted(t)) for line in lines
                        for t in combinations(sorted(line), 3)})
    assert len(edges) == 240 and len(triangles) == 160

    # Boundary maps over F3.  d0 maps C1 -> C0; d1 maps C2 -> C1.
    d0 = [[0] * len(edges) for _ in range(n)]
    for ei, (a, b) in enumerate(edges):
        d0[a][ei] = 2
        d0[b][ei] = 1
    d1_columns = []
    for x, y, z in triangles:
        col = [0] * len(edges)
        col[edge_index[(y, z)]] = 1
        col[edge_index[(x, z)]] = 2
        col[edge_index[(x, y)]] = 1
        d1_columns.append(col)

    cycle_basis, d0_pivots = nullspace_mod3(d0)
    boundary_span = GF3Span(d1_columns)
    assert len(d0_pivots) == 39
    assert len(cycle_basis) == 201
    assert boundary_span.rank == 120
    assert len(cycle_basis) - boundary_span.rank == 81

    def transvection_perm(v):
        out = []
        for x in pts:
            w = symp(x, v)
            out.append(pt_index[canon(tuple(
                (x[t] + w * v[t]) % P for t in range(4)))])
        return tuple(out)

    generators = [transvection_perm(v) for v in pts]
    identity = tuple(range(n))

    def compose(a, b):
        return tuple(a[b[i]] for i in range(n))

    def inverse(g):
        out = [0] * n
        for i, x in enumerate(g):
            out[x] = i
        return tuple(out)

    psp = {identity}
    frontier = [identity]
    while frontier:
        nxt = []
        for g in frontier:
            for h in generators:
                hg = compose(h, g)
                if hg not in psp:
                    psp.add(hg)
                    nxt.append(hg)
        frontier = nxt
    psp = sorted(psp)
    assert len(psp) == 25920

    def line_perm(g):
        return tuple(line_index[frozenset(g[x] for x in line)]
                     for line in lines)

    def order(g):
        value = 1
        current = g
        while current != identity:
            current = compose(g, current)
            value += 1
        return value

    def subgroup_generated(gens, limit=1000):
        gens = list(gens)
        group = {identity}
        frontier = [identity]
        while frontier:
            nxt = []
            for x in frontier:
                for g in gens:
                    y = compose(g, x)
                    if y not in group:
                        group.add(y)
                        if len(group) > limit:
                            return group
                        nxt.append(y)
            frontier = nxt
        return group

    def find_normal_o3(stabilizer, seed):
        rng = random.Random(seed)
        threes = [g for g in stabilizer if order(g) == 3]
        for attempt in range(1, 12001):
            chosen = [rng.choice(threes) for _ in range(3)]
            subgroup = subgroup_generated(chosen, limit=27)
            if len(subgroup) != 27:
                continue
            normal = True
            for c in stabilizer:
                ci = inverse(c)
                if any(compose(compose(c, x), ci) not in subgroup
                       for x in subgroup):
                    normal = False
                    break
            if normal:
                # Return a minimal generating subset for later orbit work.
                minimal = []
                span = {identity}
                for g in sorted(subgroup):
                    if g in span:
                        continue
                    minimal.append(g)
                    span = subgroup_generated(minimal, limit=27)
                    if len(span) == 27:
                        break
                return subgroup, minimal, attempt
        raise RuntimeError("normal O3 search failed")

    point0 = 0
    line0 = 0
    point_stabilizer = [g for g in psp if g[point0] == point0]
    line0_set = lines[line0]
    line_stabilizer = [g for g in psp
                       if frozenset(g[x] for x in line0_set) == line0_set]
    assert len(point_stabilizer) == len(line_stabilizer) == 648

    point_o3, point_o3_gens, point_attempts = find_normal_o3(
        point_stabilizer, 86501)
    line_o3, line_o3_gens, line_attempts = find_normal_o3(
        line_stabilizer, 86502)

    def center(group):
        return {g for g in group
                if all(compose(g, h) == compose(h, g) for h in group)}

    point_center = center(point_o3)
    line_center = center(line_o3)
    assert len(point_center) == 3
    assert len(line_center) == 27
    assert all(order(g) == 3 for g in point_o3 if g != identity)
    assert all(order(g) == 3 for g in line_o3 if g != identity)

    point_shell = [x for x in range(n)
                   if x != point0 and not adj[point0][x]]
    line_shell = [li for li in range(40)
                  if li != line0 and not (line_sets[li] & line_sets[line0])]
    line_perms = {g: line_perm(g) for g in point_o3 | line_o3}
    point_orbit = {g[point_shell[0]] for g in point_o3}
    line_orbit = {line_perms[g][line_shell[0]] for g in line_o3}
    assert len(point_shell) == len(line_shell) == 27
    assert point_orbit == set(point_shell)
    assert line_orbit == set(line_shell)

    # Steinberg character from the Solomon-Tits alternating trace.
    flags = [(p, li) for li, line in enumerate(lines) for p in line]

    def steinberg_character(g):
        lp = line_perms.get(g)
        if lp is None:
            lp = line_perm(g)
        fixed_points = sum(g[p] == p for p in range(n))
        fixed_lines = sum(lp[li] == li for li in range(40))
        fixed_flags = sum(g[p] == p and lp[li] == li for p, li in flags)
        return fixed_flags - fixed_points - fixed_lines + 1

    point_chars = Counter(steinberg_character(g) for g in point_o3)
    line_chars = Counter(steinberg_character(g) for g in line_o3)
    assert point_chars == Counter({0: 26, 81: 1})
    assert line_chars == Counter({0: 26, 81: 1})
    print("T1 St|Heisenberg_O3 = 3 Reg(O3): character {81:1, 0:26}")
    print("T1 St|F3^3_O3       = 3 Reg(O3): character {81:1, 0:26}")

    def act_on_edges(g, vector):
        out = [0] * len(edges)
        for ei, coefficient in enumerate(vector):
            if not coefficient:
                continue
            a, b = edges[ei]
            ga, gb = g[a], g[b]
            if ga < gb:
                gi, sign = edge_index[(ga, gb)], 1
            else:
                gi, sign = edge_index[(gb, ga)], 2
            out[gi] = (out[gi] + sign * coefficient) % P
        return out

    def add_vectors(a, b, scale=1):
        return [(a[i] + scale * b[i]) % P for i in range(len(a))]

    def random_cycle(rng):
        out = [0] * len(edges)
        used = False
        for basis_vector in cycle_basis:
            coefficient = rng.randrange(P)
            if coefficient:
                used = True
                out = add_vectors(out, basis_vector, coefficient)
        return out if used else cycle_basis[rng.randrange(len(cycle_basis))][:]

    def explicit_free_basis(group, seed):
        rng = random.Random(seed)
        span = boundary_span.copy()
        witnesses = []
        group_ordered = sorted(group)
        for copy_index in range(3):
            accepted = None
            for attempt in range(1, 2001):
                candidate = random_cycle(rng)
                trial = span.copy()
                orbit = [act_on_edges(g, candidate) for g in group_ordered]
                old_rank = trial.rank
                for vector in orbit:
                    trial.add(vector)
                gain = trial.rank - old_rank
                if gain == 27:
                    accepted = (candidate, orbit, trial, attempt)
                    break
            if accepted is None:
                raise RuntimeError(f"failed to find regular copy {copy_index}")
            candidate, orbit, span, attempt = accepted
            witnesses.append({
                "attempt": attempt,
                "support": [i for i, x in enumerate(candidate) if x],
                "coefficients": [x for x in candidate if x],
                "orbit_size": len({tuple(v) for v in orbit}),
                "rank_gain_mod_boundaries": 27,
            })
        assert span.rank == 201
        return witnesses, span.rank

    point_witnesses, point_total_rank = explicit_free_basis(point_o3, 86511)
    line_witnesses, line_total_rank = explicit_free_basis(line_o3, 86512)
    print("T2 H1(F3)|Heisenberg_O3 is free rank 3: orbit gains 27+27+27")
    print("T2 H1(F3)|F3^3_O3       is free rank 3: orbit gains 27+27+27")

    def induced_nilpotent_ranks(g):
        def n_action(v):
            return add_vectors(act_on_edges(g, v), v, scale=2)

        images = cycle_basis
        ranks = []
        current = images
        for _ in range(3):
            current = [n_action(v) for v in current]
            span = boundary_span.copy()
            before = span.rank
            for v in current:
                span.add(v)
            ranks.append(span.rank - before)
        return tuple(ranks)

    central_generator = next(g for g in point_center if g != identity)
    central_ranks = induced_nilpotent_ranks(central_generator)
    assert central_ranks == (54, 27, 0)

    def cyclic_subgroups(group):
        seen = set()
        subgroups = []
        for g in sorted(group):
            if g == identity or g in seen:
                continue
            g2 = compose(g, g)
            subgroup = frozenset((identity, g, g2))
            subgroups.append(subgroup)
            seen.update(subgroup)
        return subgroups

    point_directions = cyclic_subgroups(point_o3)
    line_directions = cyclic_subgroups(line_o3)
    assert len(point_directions) == len(line_directions) == 13
    point_profiles = Counter(induced_nilpotent_ranks(
        next(g for g in subgroup if g != identity))
        for subgroup in point_directions)
    line_profiles = Counter(induced_nilpotent_ranks(
        next(g for g in subgroup if g != identity))
        for subgroup in line_directions)
    assert point_profiles == Counter({(54, 27, 0): 13})
    assert line_profiles == Counter({(54, 27, 0): 13})
    print("T3 Heisenberg center: complex sectors 27+27+27; native ranks")
    print("   rank(N), rank(N^2), rank(N^3) = 54,27,0")
    print("   kernel flag dimensions = 27,54,81; quotients = 27,27,27")
    print("T4 all 13 C3 directions on both torsors have profile 54,27,0")
    print("   only the Heisenberg torsor has a characteristic direction: Z(O3)")

    checks = {
        "point_o3_order_27": len(point_o3) == 27,
        "line_o3_order_27": len(line_o3) == 27,
        "point_o3_heisenberg_center_3": len(point_center) == 3,
        "line_o3_elementary_center_27": len(line_center) == 27,
        "point_shell_regular": point_orbit == set(point_shell),
        "line_shell_regular": line_orbit == set(line_shell),
        "complex_restrictions_three_regular": (
            point_chars == line_chars == Counter({0: 26, 81: 1})),
        "native_point_free_rank_3": point_total_rank == 201,
        "native_line_free_rank_3": line_total_rank == 201,
        "heisenberg_center_jordan_profile": central_ranks == (54, 27, 0),
        "all_point_directions_same_profile": (
            point_profiles == Counter({(54, 27, 0): 13})),
        "all_line_directions_same_profile": (
            line_profiles == Counter({(54, 27, 0): 13})),
    }
    assert all(checks.values())

    output = {
        "theorem": "BT865 dual torsor Steinberg compiler",
        "chain_complex": {
            "C0": 40,
            "C1": 240,
            "C2": 160,
            "rank_d0_mod3": 39,
            "rank_d1_mod3": 120,
            "dim_H1_mod3": 81,
        },
        "point_state_torsor": {
            "group": "extraspecial Heisenberg 3^(1+2), exponent 3",
            "order": len(point_o3),
            "center_order": len(point_center),
            "normal_o3_search_attempts": point_attempts,
            "shell_regular": True,
            "complex_restriction": "3 Reg(H27)",
            "complex_irreducible_blocks": {
                "central_character_1": {
                    "dimension": 27,
                    "content": "9 linear characters, multiplicity 3 each",
                },
                "central_character_omega": {
                    "dimension": 27,
                    "content": "3-dimensional Schrodinger irrep, multiplicity 9",
                },
                "central_character_omega2": {
                    "dimension": 27,
                    "content": "conjugate 3-dimensional Schrodinger irrep, multiplicity 9",
                },
            },
            "native_free_module": "H1(F3) = F3[H27]^3",
            "orbit_basis_witnesses": point_witnesses,
        },
        "line_program_torsor": {
            "group": "elementary F3^3",
            "order": len(line_o3),
            "center_order": len(line_center),
            "normal_o3_search_attempts": line_attempts,
            "shell_regular": True,
            "complex_restriction": "3 Reg(F3^3)",
            "complex_fourier_channels": 27,
            "multiplicity_per_channel": 3,
            "native_free_module": "H1(F3) = F3[F3^3]^3",
            "orbit_basis_witnesses": line_witnesses,
        },
        "canonical_triality_axis": {
            "source": "unique center Z(H27) = C3",
            "complex_sector_dimensions": [27, 27, 27],
            "native_nilpotent_ranks": list(central_ranks),
            "native_kernel_dimensions": [27, 54, 81],
            "native_successive_quotients": [27, 27, 27],
            "jordan_blocks_size_3": 27,
        },
        "direction_census": {
            "point_c3_directions": len(point_directions),
            "line_c3_directions": len(line_directions),
            "point_profiles": {str(k): v for k, v in point_profiles.items()},
            "line_profiles": {str(k): v for k, v in line_profiles.items()},
        },
        "boundary": (
            "The two free rank-3 coordinatizations are exact, but a canonical "
            "intertwiner between the nonisomorphic torsor groups is not claimed; "
            "it requires chosen shells and orbit generators."
        ),
        "checks": checks,
    }
    with open("data/bt865_dual_torsor_steinberg_compiler.json", "w") as handle:
        json.dump(output, handle, indent=2)
    print("\nwrote data/bt865_dual_torsor_steinberg_compiler.json")
    print("BT865 PASS")


if __name__ == "__main__":
    main()
