#!/usr/bin/env python3
"""
BT881 - Spacetime is the space of local gauge groups: 40 points, 40
        generation-centred gauge groups, generating everything.

BT880: each point p has a gauge group C(R_p) = Stab(p) (order 648)
whose centre is the generation Z3 = <R_p> (the long-root subgroup at
p).  Globally:

  T1  there are exactly 40 long-root Z3 subgroups, one per point
      (40 points <-> 40 generation centres <-> 40 local gauge groups);
      80 = 2*40 transvection elements.
  T2  the 40 are a single PSp-conjugacy class of subgroups (all local
      gauge/generation structures are equivalent - substrate
      homogeneity: every spacetime point looks the same).
  T3  the 40 long-root Z3 subgroups GENERATE all of PSp(4,3): the
      global symmetry is built from the local generation symmetries.
      So the 40 points of W(3,3) ARE the space of local gauge groups,
      each generation-Z3-centred, and spacetime is the index set of
      the generation/gauge structure.
"""
from __future__ import annotations

from collections import Counter
from itertools import combinations, product
import json
import random


def canon(v):
    for x in v:
        if x % 3:
            c = 1 if x % 3 == 1 else 2
            return tuple((c * y) % 3 for y in v)
    raise ValueError


def main():
    pts = sorted({canon(v) for v in product(range(3), repeat=4) if any(v)})
    n = 40
    pt_index = {p: i for i, p in enumerate(pts)}

    def symp(x, y):
        return (x[0]*y[2] - x[2]*y[0] + x[1]*y[3] - x[3]*y[1]) % 3

    adj = [[False]*n for _ in range(n)]
    for i, j in combinations(range(n), 2):
        if symp(pts[i], pts[j]) == 0:
            adj[i][j] = adj[j][i] = True

    def transvection_perm(v):
        out = []
        for x in pts:
            w = symp(x, v)
            out.append(pt_index[canon(tuple(
                (x[t] + w * v[t]) % 3 for t in range(4)))])
        return tuple(out)

    gens = [transvection_perm(v) for v in pts]
    ident = tuple(range(n))

    def compose(a, b):
        return tuple(a[b[i]] for i in range(n))

    def order_of(gp):
        o, cur = 1, gp
        while cur != ident:
            cur = compose(gp, cur)
            o += 1
        return o

    # T1: the long-root Z3 subgroup at each point = <t_v>
    # t_v is the transvection generator transvection_perm(v) -- but as a
    # PERMUTATION it may coincide for v and 2v.  Build <t_v> per point.
    longroot = {}
    for i, v in enumerate(pts):
        t = transvection_perm(v)
        assert order_of(t) == 3
        sub = frozenset({ident, t, compose(t, t)})
        longroot[i] = sub
    distinct = set(longroot.values())
    print(f"T1 long-root Z3 subgroups (one per point): {len(distinct)} "
          f"distinct, from {n} points")
    assert len(distinct) == 40
    nontrivial = set()
    for s in distinct:
        for g in s:
            if g != ident:
                nontrivial.add(g)
    print(f"   transvection elements: {len(nontrivial)} = 2*40 = 80")
    assert len(nontrivial) == 80

    # build PSp
    psp = {ident}
    fr = [ident]
    while fr:
        nx = []
        for gp in fr:
            for h in gens:
                gh = compose(h, gp)
                if gh not in psp:
                    psp.add(gh)
                    nx.append(gh)
        fr = nx
    assert len(psp) == 25920

    # T2: are the 40 long-root subgroups a single conjugacy class?
    def conj_sub(c, S):
        inv = [0]*n
        for i in range(n):
            inv[c[i]] = i
        inv = tuple(inv)
        return frozenset(compose(compose(c, x), inv) for x in S)

    S0 = longroot[0]
    orbit = set()
    for c in psp:
        orbit.add(conj_sub(c, S0))
    print(f"T2 conjugates of one long-root Z3: {len(orbit)} "
          f"(= 40 => single class, all local structures equivalent)")
    assert orbit == distinct and len(orbit) == 40

    # T3: do the 40 long-root subgroups generate PSp?
    rootgens = []
    for s in distinct:
        for g in s:
            if g != ident:
                rootgens.append(g)
                break
    G = {ident}
    fr = [ident]
    while fr:
        nx = []
        for gp in fr:
            for h in rootgens:
                gh = compose(h, gp)
                if gh not in G:
                    G.add(gh)
                    nx.append(gh)
        fr = nx
    print(f"T3 group generated by the 40 long-root Z3's: order {len(G)} "
          f"(= 25920 => they generate all of PSp(4,3))")
    assert len(G) == 25920
    print("   => the 40 points of W(3,3) ARE the space of local gauge")
    print("      groups, each generation-Z3-centred; spacetime is the")
    print("      index set of the generation/gauge structure, and the")
    print("      global symmetry is built from the local generation")
    print("      symmetries.")

    out = {
        "theorem": "BT881 forty local gauge groups",
        "long_root_subgroups": len(distinct),
        "transvection_elements": len(nontrivial),
        "single_conjugacy_class": len(orbit) == 40,
        "generate_PSp": len(G) == 25920,
    }
    with open("data/bt881_forty_local_gauge_groups.json", "w") as fj:
        json.dump(out, fj, indent=2)
    print("\nwrote data/bt881_forty_local_gauge_groups.json")


if __name__ == "__main__":
    main()
