#!/usr/bin/env python3
"""BT971 - nontrivial lane transport maps.

BT968 committed minimal ABI self-maps.  BT971 adds a nontrivial square-lane
transport model: full D8 acts on the four lanes, but only a V4 subgroup preserves
the light/cache family partition used by the current ABI.
"""
from __future__ import annotations
from itertools import permutations
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "data/bt971_nontrivial_lane_transport_maps.json"
LANES = [0,1,2,3]
LIGHT = {0,1}
CACHE = {2,3}

OPS = {
    "id": {0:0,1:1,2:2,3:3},
    "light_swap": {0:1,1:0,2:2,3:3},
    "cache_swap": {0:0,1:1,2:3,3:2},
    "both_swap": {0:1,1:0,2:3,3:2},
    "quarter_turn": {0:2,2:1,1:3,3:0},
    "half_turn": {0:1,1:0,2:3,3:2},
    "diagonal_reflection": {0:0,2:2,1:3,3:1},
    "other_diagonal_reflection": {0:2,2:0,1:1,3:3}
}


def preserves_family(op):
    return {op[x] for x in LIGHT} == LIGHT and {op[x] for x in CACHE} == CACHE


def compose(a,b):
    return {x:a[b[x]] for x in LANES}


def main() -> None:
    family_preserving = {name:op for name,op in OPS.items() if preserves_family(op)}
    result = {
        "theorem": "BT971 nontrivial lane transport maps",
        "status": "nontrivial family-preserving subgroup identified",
        "lane_families": {"light": sorted(LIGHT), "cache": sorted(CACHE)},
        "full_square_transport_ops": {k:{str(x):y for x,y in v.items()} for k,v in OPS.items()},
        "family_preserving_ops": list(family_preserving.keys()),
        "family_preserving_order": len(family_preserving),
        "family_preserving_reading": "The current ABI light/cache partition is preserved by a V4 subgroup generated by light_swap and cache_swap. The full square D8 contains operations that cross the light/cache partition.",
        "abi_consequence": "BT968 singleton role maps prove strict role preservation. BT971 adds nontrivial family-level transport: light rails can swap, cache rails can swap, but full D8 is too large for the present ABI partition.",
        "boundary": "This is a lane-level transport model. It is not a derivation of the full optical D8/D12 action on packets.",
        "checks": {"T1_family_preserving_order_4": len(family_preserving)==4, "T2_light_swap_present": "light_swap" in family_preserving, "T3_cache_swap_present": "cache_swap" in family_preserving, "T4_quarter_turn_not_family_preserving": not preserves_family(OPS["quarter_turn"]), "T5_boundary_explicit": True}
    }
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(json.dumps(result, indent=2), encoding="utf-8")
    print("BT971 wrote", OUT)

if __name__ == "__main__":
    main()
