#!/usr/bin/env python3
"""Pass 4683 — normalizer of the Pass4656 labelled Schreier cohomology class.

The Pass4656 base is not an invariant orbital graph; it is the labelled
Schreier multigraph for five specifically chosen cyclic transvection factors.
Therefore a PSp-module structure on its fixed H^1 cannot be assumed.

Compute the natural PGSp normalizer of those five order-three cyclic factors.
Inside PSp it is trivial; inside PGSp it is C2, generated by an outer-coset
involution.  That involution acts on the apartment and flag carriers and hence
lifts to the C2 cover, so by naturality it fixes the cover class.  The correct
conclusion is a scope obstruction: no PSp orbit/module of [alpha] in this fixed
H^1 is defined.
"""
from __future__ import annotations
import json,math
from pathlib import Path
import numpy as np
from w33_pass4472_4479_apartment_module_thermo_ihara_pauli import build_geometry,build_line_perm,perm_group,transvection_matrix
ROOT=Path(__file__).resolve().parents[1]
OUT=ROOT/'data/PART_W33_PASS4683_VOLTAGE_NORMALIZER_SCOPE_REGEN.json'

def comp(p,q):return tuple(p[q[i]] for i in range(len(q)))
def inv(p):
    q=[0]*len(p)
    for i,j in enumerate(p):q[j]=i
    return tuple(q)
def order(p):
    seen=[False]*len(p);z=1
    for i in range(len(p)):
        if not seen[i]:
            j=i;n=0
            while not seen[j]:seen[j]=True;n+=1;j=p[j]
            z=math.lcm(z,n)
    return z

def main():
    pts,pidx,lines,lidx,_,_,_,_,_=build_geometry()
    cand=[build_line_perm(transvection_matrix(v),pts,pidx,lines,lidx) for v in pts]
    # Pass4656 freezes these five factor indices.  They generate PSp even if a
    # different greedy generating set is available in the current helper.
    idx=[0,1,4,5,13];S=[cand[i] for i in idx];G=perm_group(S);assert len(G)==25920
    Spm=set(S+[inv(s) for s in S])
    def normalizes(h):
        hi=inv(h)
        return all(comp(comp(h,s),hi) in Spm for s in S)
    NP=[h for h in G if normalizes(h)];assert len(NP)==1

    outer=build_line_perm(np.diag([1,2,1,2])%3,pts,pidx,lines,lidx)
    PG=set(G)|{comp(outer,g) for g in G};assert len(PG)==51840
    NPG=[h for h in PG if normalizes(h)];assert len(NPG)==2
    assert CounterOrders(NPG)=={1:1,2:1}
    nontrivial=next(h for h in NPG if order(h)==2);assert nontrivial not in G

    # The bare standard outer is not itself the normalizer element; only an
    # outer-coset conjugate normalizes the frozen five-factor presentation.
    bare=[comp(comp(outer,s),inv(outer)) in Spm for s in S]
    assert not all(bare)

    old=json.loads((ROOT/'data/PART_W33_PASS4656_APARTMENT_C2_VOLTAGE_COHOMOLOGY.json').read_text(encoding='utf-8'))
    assert old['cohomology']['deck_class_nonzero'] is True and old['cohomology']['dimension']==3241
    out={'pass':4683,
      'fixed_base':'Pass4656 five-factor labelled Schreier multigraph on 810 flags',
      'cohomology':{'dimension':3241,'deck_class_nonzero':True},
      'natural_factor_normalizer':{'inside_PSp_order':1,'inside_PGSp_order':2,'isomorphism':'C2','nontrivial_element_order':2,'nontrivial_element_outer_coset':True,'standard_outer_itself_normalizes':False},
      'class_action':{'normalizer_fixes_deck_class':True,'reason':'the nontrivial normalizer element lifts to the same apartment C2 cover, so pullback preserves its isomorphism class'},
      'scope_obstruction':{'PSp_action_on_fixed_labelled_base':False,'PSp_orbit_of_alpha_in_this_H1':'not defined','small_PSp_module_generated_by_alpha':'not defined until a PSp-invariant base complex is chosen'},
      'theorem':'The nonzero Pass4656 deck class is stabilized by the C2 natural PGSp normalizer of its frozen five-factor Schreier presentation. Full PSp does not act on that fixed labelled base, so promoting the 3241-dimensional H1 to a PSp module would be invalid.',
      'boundary':'Exact normalizer/scope theorem for the frozen labelled Schreier presentation; it does not deny that a different PSp-invariant complex may carry an equivariant cover class.'}
    OUT.write_text(json.dumps(out,indent=2,sort_keys=True)+'\n',encoding='utf-8');print(json.dumps(out,indent=2,sort_keys=True));return 0

def CounterOrders(G):
    d={}
    for g in G:d[order(g)]=d.get(order(g),0)+1
    return d
if __name__=='__main__':raise SystemExit(main())
