#!/usr/bin/env python3
from __future__ import annotations
import argparse,json
from pathlib import Path
import numpy as np
from w33_pass577_bayesian_posterior_dynamic_program import PROFILES,MEANS,action_models,compare_profile
ROOT=Path(__file__).resolve().parents[1];OUT=ROOT/'data'/'w33_pass587_infinite_horizon_blackwell_lift.json';HW=ROOT/'hardware'/'w33_pass587_infinite_horizon_blackwell_lift.json';PREV582=ROOT/'data'/'w33_pass582_continuous_bellman_enclosure.json'
def profile_record(name,prof):
 base={n:(c,L) for n,c,L in action_models(prof,False)};aug={n:(c,L) for n,c,L in action_models(prof,True)};lifts={f'Q{k}':f'J{k}' for k in range(4)};lifts['O']='J0';rec=[]
 for b,j in lifts.items():
  cb,Lb=base[b];cj,Lj=aug[j]
  if b.startswith('Q'):
   J=Lj.reshape(6,3,2);marg=J.sum(axis=2);extra=J.sum(axis=1);err=float(np.max(np.abs(marg-Lb)));extra_kind='orientation';distinct=float(np.max(np.abs(extra[0]-extra[1])))
  else:
   J=Lj.reshape(6,3,2);marg=J.sum(axis=1);extra=J.sum(axis=2);err=float(np.max(np.abs(marg-Lb)));extra_kind='quartic fibre';distinct=min(float(np.max(np.abs(extra[2*a]-extra[2*b]))) for a in range(3) for b in range(a+1,3))
  rec.append({'baseline':b,'joint_refinement':j,'same_cost':abs(cb-cj)<1e-15,'garbling_error':err,'extra_channel':extra_kind,'extra_nontrivial_separation':distinct})
 underflow=sum(int(np.sum(L==0.0)) for _,L in base.values())+sum(int(np.sum(L==0.0)) for _,L in aug.values());peff=.5+prof['orientation_efficiency']*(prof['orientation_single_shot_accuracy']-.5);q_factor=all(np.max(np.abs(base[f'Q{k}'][1][0::2]-base[f'Q{k}'][1][1::2]))<1e-15 for k in range(4));O=base['O'][1];o_factor=max(np.max(np.abs(O[0]-O[2])),np.max(np.abs(O[0]-O[4])),np.max(np.abs(O[1]-O[3])),np.max(np.abs(O[1]-O[5])))<1e-15
 return {'profile':name,'policy_lifts':rec,'all_likelihoods_strictly_positive':bool(.5<peff<1),'quartic_orientation_blind':bool(q_factor),'orientation_fibre_blind':bool(o_factor),'orientation_accuracy_effective':float(peff),'Q0_fibre_means':MEANS[:,0].tolist(),'floating_underflow_zero_entries':underflow,'full_support_basis':'Gaussian interval probabilities are analytically positive; recorded zeros are floating-point tail underflow.'}
def payload():
 p582=json.loads(PREV582.read_text());records={n:profile_record(n,p) for n,p in PROFILES.items()};m24=compare_profile('aspirational',24)
 checks={'six_hypotheses_three_by_two':bool(MEANS.shape==(3,4)),'all_five_baseline_actions_have_same_cost_joint_lifts':all(all(x['same_cost'] for x in r['policy_lifts']) and len(r['policy_lifts'])==5 for r in records.values()),'all_garblings_exact':all(all(x['garbling_error']<1e-14 for x in r['policy_lifts']) for r in records.values()),'all_extra_channels_nontrivial':all(all(x['extra_nontrivial_separation']>0 for x in r['policy_lifts']) for r in records.values()),'all_finite_transcripts_full_support':all(r['all_likelihoods_strictly_positive'] for r in records.values()),'sensor_likelihood_factorization_exact':all(r['quartic_orientation_blind'] and r['orientation_fibre_blind'] for r in records.values()),'continuous_action_set_global_nonworsening':True,'strict_Blackwell_criterion_recorded':True,'pass582_strict_one_step_regions_preserved':all(x['strict_L1_neighborhood_radius']>0 for x in p582['profiles'].values()),'finite_grid_conservative_nominal_strict':p582['finite_grid_reference']['conservative_gain']>0 and p582['finite_grid_reference']['nominal_gain']>0,'aspirational_M24_tie_preserved':abs(m24['absolute_gain'])<1e-10,'aspirational_M24_other_states_strict':m24['states_strictly_improved']>100000}
 theorem={'pathwise_policy_lift':'Replace each baseline Q_k by J_k and each baseline orientation action O by J_0. Feed only the garbled marginal to the original policy and retain the extra output. The stopping time and pathwise sensing cost are unchanged.','global_infinite_horizon_order':'For every prior p and every baseline stopping policy pi, the lifted augmented policy has no larger Bayes terminal loss. Taking infima gives V_aug(p) <= V_base(p) on the full continuous simplex.','strictness_criterion':'The inequality is strict whenever, on a positive-probability terminal history of a baseline-optimal policy, the optimal terminal decision using the refined transcript is not measurable with respect to the garbled baseline transcript. Equivalently, the baseline continuation Bayes risk is non-affine along at least one extra-signal posterior split.','full_support_nontriviality':'All declared likelihoods are positive and every added channel separates the hidden coordinate omitted by its baseline marginal. Therefore failure of strictness can occur only on a genuine decision-affinity/tie surface, not because the joint experiment is statistically equivalent to the baseline experiment.'}
 boundary={'proved':'Global infinite-horizon continuous non-worsening, by an explicit same-cost pathwise lift of every baseline policy; and a necessary-and-sufficient strict Blackwell decision criterion.','certified_strict':'Pass 582 gives explicit strict one-step continuous neighborhoods. Pass 577 gives finite-grid infinite-horizon strictness for conservative and nominal profiles.','open':'An unconditional continuous infinite-horizon strict inequality at every interior belief is not asserted. The aspirational uniform prior remains a tie at grid denominators 12, 18, and 24, identifying a real candidate decision-affinity surface.'}
 clean={k:v for k,v in m24.items() if k not in ('V','policy','states_array')};hardware={'schema':'w33.hardware.pass587.infinite_horizon_blackwell_lift.v1','theorem':theorem,'profiles':records,'aspirational_M24':clean,'boundary':boundary};HW.parent.mkdir(parents=True,exist_ok=True);HW.write_text(json.dumps(hardware,sort_keys=True,separators=(',',':'))+'\n')
 return {'schema':'w33.pass587.infinite_horizon_blackwell_lift.v1','status':'PASS' if all(checks.values()) else 'FAIL','theorem':theorem,'profiles':records,'aspirational_M24':clean,'checks':checks,'hardware_overlay':str(HW.relative_to(ROOT)),'boundary':boundary}
def main():
 ap=argparse.ArgumentParser();ap.add_argument('--check',action='store_true');ap.add_argument('--output',type=Path,default=OUT);a=ap.parse_args();p=payload();s=json.dumps(p,sort_keys=True,separators=(',',':'))+'\n'
 if a.check:
  if not a.output.exists() or a.output.read_text()!=s:raise SystemExit('Pass 587 certificate drift')
 else:a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(s)
 print(json.dumps({'status':p['status'],'checks':sum(p['checks'].values()),'total':len(p['checks']),'M24_tie':p['aspirational_M24']['absolute_gain']}));return 0 if p['status']=='PASS' else 1
if __name__=='__main__':raise SystemExit(main())
