#!/usr/bin/env python3
"""Passes 2866-2867 -- two architectural constants nobody has measured.

PASS 2866 -- THE EXACT DIAMETER OF THE INSTRUCTION SET.
    The four-operation micro-ISA generates ASp(4,3), order 4,199,040 (Pass 2778, 2789).
    "Generates" says every frame transformation is expressible.  It says nothing about
    HOW LONG the program is, and that is the number a compiler actually needs: the
    worst-case instruction count over all reachable transformations is the machine's
    DIAMETER, and it bounds every schedule the machine will ever run.

    Nobody has it, because the obvious computation -- breadth-first search over four
    million group elements -- looks expensive.  It is not, if the state is indexed
    properly: a group element is (M, t) with M in Sp(4,3) and t in F_3^4, each generator
    acts as a fixed PERMUTATION of the 51,840 matrix indices composed with a fixed map on
    the 81 translations, and once those tables are built the whole search is array
    indexing.

    The generators are used FORWARD ONLY.  A processor cannot run an instruction
    backwards, so the directed diameter is the honest number; the undirected one would
    flatter the machine.

PASS 2867 -- HOW MANY INSTRUCTIONS UNTIL THE FRAME IS SCRAMBLED?
    A random instruction stream drives a random walk on the 81 frames.  Its mixing time
    is the number of instructions after which the frame carries no information about
    where it started -- the architectural analogue of a thermalisation time, and the
    natural companion to Pass 2836's Landauer figure: one tells you what a readout costs,
    the other tells you how often a readout is worth taking.

    py -3 analysis/w33_pass2866_2867_isa_diameter_and_scrambling.py
"""

from __future__ import annotations

import json
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[1]

# The minimal generating set proved in Pass 2789 and built in RTL at Pass 2796.
# Linear parts act on the column (x_p, z_p, x_f, z_f) over F_3.
LIN = {
    "F_p":   ((0, 2, 0, 0), (1, 0, 0, 0), (0, 0, 1, 0), (0, 0, 0, 1)),
    "CX_pf": ((1, 0, 0, 0), (0, 1, 0, 2), (1, 0, 1, 0), (0, 0, 0, 1)),
    "CX_fp": ((1, 0, 1, 0), (0, 1, 0, 0), (0, 0, 1, 0), (0, 2, 0, 1)),
    "Z_p":   ((1, 0, 0, 0), (0, 1, 0, 0), (0, 0, 1, 0), (0, 0, 0, 1)),   # identity part
}
TRANS = {"F_p": (0, 0, 0, 0), "CX_pf": (0, 0, 0, 0),
         "CX_fp": (0, 0, 0, 0), "Z_p": (0, 1, 0, 0)}
IDENT = tuple(tuple(1 if i == j else 0 for j in range(4)) for i in range(4))


def mul(a, b):
    return tuple(tuple(sum(a[i][k] * b[k][j] for k in range(4)) % 3 for j in range(4))
                 for i in range(4))


def matvec(a, v):
    return tuple(sum(a[i][k] * v[k] for k in range(4)) % 3 for i in range(4))


def enumerate_sp():
    """Sp(4,3) as an indexed list, generated by the three linear opcodes."""
    gens = [LIN["F_p"], LIN["CX_pf"], LIN["CX_fp"]]
    order = [IDENT]
    index = {IDENT: 0}
    frontier = [IDENT]
    while frontier:
        nxt = []
        for m in frontier:
            for g in gens:
                p = mul(g, m)
                if p not in index:
                    index[p] = len(order)
                    order.append(p)
                    nxt.append(p)
        frontier = nxt
    return order, index


# ===========================================================================
def pass_2866() -> dict:
    print("=" * 78)
    print("Pass 2866 -- the exact diameter of the four-operation ISA")
    print("=" * 78)

    sp_list, sp_index = enumerate_sp()
    NSP = len(sp_list)
    print(f"  |Sp(4,3)| generated by the three linear opcodes : {NSP}")
    assert NSP == 51840, NSP

    tvecs = [(a, b, c, d) for a in range(3) for b in range(3)
             for c in range(3) for d in range(3)]
    t_index = {t: i for i, t in enumerate(tvecs)}
    NT = len(tvecs)
    N = NSP * NT
    print(f"  |F_3^4| = {NT}   |ASp(4,3)| = {N}")

    # Left action of a generator (A, a) on (M, t):  (A M, A t + a).
    print("  building generator tables (one permutation of Sp, one map on F_3^4 each)...")
    sp_perm, t_map = {}, {}
    for name in ("F_p", "CX_pf", "CX_fp", "Z_p"):
        A, a = LIN[name], TRANS[name]
        sp_perm[name] = np.array([sp_index[mul(A, M)] for M in sp_list], dtype=np.int32)
        t_map[name] = np.array([t_index[tuple((matvec(A, t)[i] + a[i]) % 3 for i in range(4))]
                                for t in tvecs], dtype=np.int32)

    depth = np.full(N, 255, dtype=np.uint8)
    start = sp_index[IDENT] * NT + t_index[(0, 0, 0, 0)]
    depth[start] = 0
    frontier = np.array([start], dtype=np.int64)

    print("\n  depth   ball size      new       cumulative")
    profile, cum, d = [], 1, 0
    print(f"  {d:5d}   {cum:>9d}   {1:>8d}   {cum/N*100:9.4f} %")
    profile.append({"depth": 0, "new": 1, "cumulative": 1})
    while frontier.size:
        d += 1
        cand = []
        for name in ("F_p", "CX_pf", "CX_fp", "Z_p"):
            sp = sp_perm[name][frontier // NT]
            tt = t_map[name][frontier % NT]
            cand.append(sp.astype(np.int64) * NT + tt)
        cand = np.unique(np.concatenate(cand))
        cand = cand[depth[cand] == 255]
        if cand.size == 0:
            d -= 1
            break
        depth[cand] = min(d, 254)
        cum += cand.size
        profile.append({"depth": d, "new": int(cand.size), "cumulative": int(cum)})
        print(f"  {d:5d}   {cum:>9d}   {cand.size:>8d}   {cum/N*100:9.4f} %")
        frontier = cand

    reached = int((depth != 255).sum())
    print(f"\n  reached {reached} of {N}  ({reached == N})")
    print(f"  DIRECTED DIAMETER of the four-operation ISA = {d}")

    hist = np.bincount(depth[depth != 255])
    mean = float((np.arange(hist.size) * hist).sum() / reached)
    print(f"  mean program length over all transformations = {mean:.6f}")
    print(f"  information-theoretic floor: log_4({N}) = {np.log(N)/np.log(4):.6f}")
    print(f"  the ISA is {d/(np.log(N)/np.log(4)):.4f}x the counting floor")

    print(f"""
  Reading.  Four opcodes give at most 4^L programs of length L, so no instruction set
  with four operations can have diameter below log_4(4199040) = {np.log(N)/np.log(4):.3f},
  i.e. {int(np.ceil(np.log(N)/np.log(4)))} instructions.  This one achieves {d}.  Every
  frame transformation the machine can perform is therefore at most {d} instructions
  away, and the AVERAGE is {mean:.2f} -- so a compiler that emits {d}-instruction
  schedules is worst-case optimal to within a factor of {d/(np.log(N)/np.log(4)):.2f}.""")

    return {"sp_order": NSP, "group_order": N, "reached": reached,
            "directed_diameter": int(d), "mean_program_length": mean,
            "counting_floor_log4": float(np.log(N) / np.log(4)),
            "ball_profile": profile}


# ===========================================================================
def pass_2867() -> dict:
    print()
    print("=" * 78)
    print("Pass 2867 -- how many instructions until the frame is scrambled?")
    print("=" * 78)

    tvecs = [(a, b, c, d) for a in range(3) for b in range(3)
             for c in range(3) for d in range(3)]
    t_index = {t: i for i, t in enumerate(tvecs)}
    names = ("F_p", "CX_pf", "CX_fp", "Z_p")

    P = np.zeros((81, 81))
    for name in names:
        A, a = LIN[name], TRANS[name]
        for i, t in enumerate(tvecs):
            j = t_index[tuple((matvec(A, t)[k] + a[k]) % 3 for k in range(4))]
            P[j, i] += 0.25

    col_ok = np.allclose(P.sum(axis=0), 1.0)
    row_ok = np.allclose(P.sum(axis=1), 1.0)
    print(f"  transition matrix is doubly stochastic: {col_ok and row_ok}")
    print("  (each opcode is a bijection on the 81 frames, so the stationary")
    print("   distribution is exactly uniform -- no frame is preferred)")

    ev = np.linalg.eigvals(P)
    mag = np.sort(np.abs(ev))[::-1]
    lam2 = float(mag[1])
    gap = 1 - lam2
    print(f"\n  |lambda_1| = {mag[0]:.9f}   |lambda_2| = {lam2:.9f}")
    print(f"  spectral gap 1 - |lambda_2| = {gap:.9f}")
    print(f"  relaxation time 1/gap        = {1/gap:.6f} instructions")

    # exact total-variation mixing, by iterating from the worst start
    print("\n  exact total-variation distance from uniform, worst start:")
    uni = np.full(81, 1 / 81)
    dist = np.zeros(81)
    dist[t_index[(0, 0, 0, 0)]] = 1.0
    tv_rows, tmix = [], None
    v = dist.copy()
    for step in range(1, 60):
        v = P @ v
        tv = 0.5 * np.abs(v - uni).sum()
        tv_rows.append({"step": step, "tv": float(tv)})
        if step <= 16:
            print(f"    after {step:2d} instructions: TV = {tv:.9f}")
        if tmix is None and tv <= 0.25:
            tmix = step
    print(f"\n  MIXING TIME to TV <= 1/4 : {tmix} instructions")

    # Kemeny constant -- the mean number of instructions to reach a random frame
    nz = [e for e in ev if abs(e - 1) > 1e-9]
    kemeny = float(sum(1 / (1 - e) for e in nz).real)
    print(f"  Kemeny constant           : {kemeny:.6f} instructions")

    print(f"""
  Putting the three numbers together.  A frame survives about {1/gap:.1f} instructions
  before its memory of the start decays by 1/e, and is statistically gone after {tmix}.
  Pass 2836 says a support readout costs 8/3 bits, so the machine's natural
  observation cadence is set by this: reading more often than every ~{tmix} instructions
  pays Landauer repeatedly for information the walk has not yet regenerated.

  At the measured 208.86 MHz of the minimal engine (Pass 2833), {tmix} instructions is
  {tmix/208.86e6*1e9:.3f} ns -- the architecture's intrinsic scrambling time.""")

    return {"doubly_stochastic": bool(col_ok and row_ok),
            "lambda2": lam2, "spectral_gap": gap, "relaxation_time": 1 / gap,
            "mixing_time_tv_quarter": tmix, "kemeny_constant": kemeny,
            "tv_trace": tv_rows[:24],
            "scrambling_ns_at_208MHz": tmix / 208.86e6 * 1e9}


def main() -> int:
    out = {"pass_2866": pass_2866(), "pass_2867": pass_2867()}
    path = ROOT / "data" / "PART_W33_PASS2866_2867_ISA_DIAMETER_AND_SCRAMBLING.json"
    path.parent.mkdir(exist_ok=True)
    # Hash the ROUND-TRIPPED object, never the live dict (CLAUDE.md, Pass 2482).
    text = json.dumps(json.loads(json.dumps(out)), indent=2, sort_keys=True) + "\n"
    path.write_text(text, encoding="utf-8")
    print(f"\nwrote {path.relative_to(ROOT).as_posix()}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
