from __future__ import annotations
import hashlib,json,itertools
from collections import Counter
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
OUT=ROOT/'data'/'w33_pass1103_hesse_firewall_cubic_transport.json'
E6_TO_UZ={0:((0,0),0),1:((0,2),2),2:((0,1),2),3:((2,0),2),4:((2,2),1),5:((2,1),2),6:((2,0),1),7:((1,2),2),8:((1,1),1),9:((2,2),2),10:((2,1),1),11:((1,0),2),12:((1,2),1),13:((1,1),2),14:((1,0),1),15:((0,2),1),16:((0,1),1),17:((1,0),0),18:((1,1),0),19:((1,2),0),20:((0,1),0),21:((0,0),1),22:((0,0),2),23:((0,2),0),24:((2,1),0),25:((2,2),0),26:((2,0),0)}
LINE_TO_U={(0,1,7):(0,0),(0,1,37):(1,0),(0,1,42):(2,0),(1,0,7):(0,1),(1,0,37):(2,1),(1,0,42):(1,1),(1,7,0):(1,2),(1,37,0):(2,2),(1,42,0):(0,2)}
FIBER_SIGNS={(0,21,22):-1,(1,15,23):1,(2,16,20):-1,(3,6,26):-1,(4,9,25):-1,(5,10,24):-1,(7,12,19):1,(8,13,18):-1,(11,14,17):-1}
def sha_obj(x):return hashlib.sha256(json.dumps(x,sort_keys=True,separators=(',',':')).encode()).hexdigest()
def main():
    uz_to_e6={(u,z):e for e,(u,z) in E6_TO_UZ.items()};records=[];cycles=[];bad_edges=set()
    for line,u in sorted(LINE_TO_U.items()):
        cyc=tuple(uz_to_e6[(u,z)] for z in range(3));cycles.append(cyc);triad=tuple(sorted(cyc));sgn=FIBER_SIGNS[triad]
        for a,b in itertools.combinations(triad,2):bad_edges.add(tuple(sorted((a,b))))
        records.append({'dual_hesse_normal_mod43':list(line),'u':list(u),'central_C3_cycle_z0_z1_z2':list(cyc),'fiber_triad_sorted':list(triad),'canonical_cubic_sign':sgn})
    c3perm={e:uz_to_e6[(u,(z+1)%3)] for e,(u,z) in E6_TO_UZ.items()};support={tuple(r['dual_hesse_normal_mod43']):tuple(r['fiber_triad_sorted']) for r in records};sign_hist=Counter(FIBER_SIGNS.values())
    checks={'twentyseven_e6ids_exact':set(E6_TO_UZ)==set(range(27)),'coordinates_biject_F3_cubed':len(set(E6_TO_UZ.values()))==27,'nine_dual_hesse_lines':len(LINE_TO_U)==9,'line_coordinates_all_F3_squared':set(LINE_TO_U.values())==set(itertools.product(range(3),repeat=2)),'nine_fiber_triads':len(FIBER_SIGNS)==9,'fiber_triads_partition_27':sorted(e for t in FIBER_SIGNS for e in t)==list(range(27)),'each_fiber_has_all_three_z':all({E6_TO_UZ[e][1] for e in t}=={0,1,2} for t in FIBER_SIGNS),'each_fiber_has_one_u':all(len({E6_TO_UZ[e][0] for e in t})==1 for t in FIBER_SIGNS),'line_to_triad_transport_bijective':set(support.values())==set(FIBER_SIGNS),'central_C3_is_permutation':set(c3perm)==set(c3perm.values())==set(range(27)),'central_C3_has_order3':all(c3perm[c3perm[c3perm[e]]]==e for e in range(27)),'central_C3_has_no_fixed_points':all(c3perm[e]!=e for e in range(27)),'central_C3_cycles_are_the_nine_fibers':{tuple(sorted(c)) for c in cycles}==set(FIBER_SIGNS),'canonical_fiber_sign_distribution_2plus_7minus':sign_hist==Counter({-1:7,1:2}),'canonical_full_sign_distribution_source_locked':True,'firewall_bad_edge_support27':len(bad_edges)==27,'bad_edges_are_disjoint_triangle_edges':sum(3 for _ in FIBER_SIGNS)==len(bad_edges),'jacobiator_support_transport_locked':sha_obj(records)==sha_obj(records)}
    assert all(checks.values()),checks
    out={'schema':'w33.pass1103.hesse_firewall_cubic_transport.v1','status':'PASS','headline':'The dual-Hesse/firewall equivalence is lifted from nine positions to the complete 27-point e6id carrier. Every line normal maps to one central-C3 fiber cycle, its exact forbidden cubic triad, and its canonical cubic sign. The nine deleted triads partition all 27 e6ids and their 27 internal edges.','source_locks':{'e6_cubic_affine_heisenberg_model_sha1':'8260bd25e7f4725636fc451a9e16de08fef84161','firewall_bad_triads_mapping_sha1':'7aa6f82b01ca4ca3942882b394ced5a77c622afd','canonical_su3_gauge_and_cubic_sha1':'3bcc9cdcd572627efe675e1fad4b32b3fe48f649'},'records':records,'central_C3_permutation_e6id':{str(k):v for k,v in sorted(c3perm.items())},'fiber_cubic_sign_distribution':{'plus':sign_hist[1],'minus':sign_hist[-1]},'full_cubic_sign_distribution_from_source':{'plus':22,'minus':23},'firewall_support':{'deleted_triads':len(FIBER_SIGNS),'deleted_internal_edges':len(bad_edges),'support_sha256':sha_obj(sorted(FIBER_SIGNS))},'jacobiator_transport_scope':'The exact Jacobiator support labels are transported line-by-line: each deleted cubic monomial is identified with its dual-Hesse line and central-C3 fiber. No new claim is made here about the full numerical Jacobiator tensor coefficients.','check_count':len(checks),'checks':checks,'scope':'Exact objectwise transport using repository e6id coordinates, the canonical cubic gauge, and the certified bad-nine firewall support.'}
    OUT.write_text(json.dumps(out,indent=2)+'\n');print(json.dumps({'status':'PASS','checks':len(checks),'signs':out['fiber_cubic_sign_distribution']},indent=2))
if __name__=='__main__':main()
