#!/usr/bin/env python3
"""Pass 4800 bonkers — the intrinsic triangle code yields [[270,182,4]]_3 CSS.

Passes4798-4799 give a self-orthogonal C=[270,44,18]_3 generated by the
45 point-vs-triangle rows (one dependency).  Taking H_X=H_Z=B is therefore a
valid qutrit CSS construction.  The dual has minimum exactly four: dependencies
of one, two, or three distinct 0/1 weight-3 triangle columns are impossible,
while the four triples of any four points inside a K5 sum to zero because each
point occurs three times.  Since d(C)=18, those weight-4 words are logical.
"""
from __future__ import annotations
import itertools,json
from pathlib import Path
import numpy as np
ROOT=Path(__file__).resolve().parents[1]
OUT=ROOT/'data/PART_W33_PASS4800_TRIANGLE_QUTRIT_CSS.json'

def Qm(v):
    x1,x2,x3,x4,x5,x6=v
    return (x1*x2+x3*x4+x5+x5*x6+x6)&1
def bits(x):return tuple((x>>i)&1 for i in range(6))
def rank_mod(M,p):
    A=[[int(x)%p for x in row] for row in M];r=0
    for c in range(len(A[0])):
        s=next((i for i in range(r,len(A)) if A[i][c]),None)
        if s is None:continue
        A[r],A[s]=A[s],A[r];z=pow(A[r][c],-1,p);A[r]=[(z*x)%p for x in A[r]]
        for i in range(len(A)):
            if i!=r and A[i][c]:
                z=A[i][c];A[i]=[(a-z*b)%p for a,b in zip(A[i],A[r])]
        r+=1
    return r

def main()->int:
    qp=[x for x in range(1,64) if Qm(bits(x))==0];assert len(qp)==27
    ql=sorted({tuple(sorted((a,b,a^b))) for a,b in itertools.combinations(qp,2) if (a^b) in qp});assert len(ql)==45
    K5=[tuple(i for i,Q in enumerate(ql) if p in Q) for p in qp];assert len(set(K5))==27 and {len(C) for C in K5}=={5}
    triangles=sorted({tuple(sorted(T)) for C in K5 for T in itertools.combinations(C,3)});assert len(triangles)==270
    B=np.zeros((45,270),dtype=int)
    for j,T in enumerate(triangles):B[list(T),j]=1
    assert rank_mod(B.tolist(),3)==44
    assert not np.any((B@B.T)%3)
    # Columns are distinct 0/1 incidence vectors of distinct 3-subsets.
    cols=[tuple(int(x) for x in B[:,j]) for j in range(270)]
    assert len(set(cols))==270 and all(sum(c)==3 for c in cols)
    # Generic lower-bound proof for dual distance:
    #  * no weight1: no zero column;
    #  * no weight2: distinct 0/1 columns are not nonzero scalar multiples in F3;
    #  * no weight3: after scaling, either all coefficients have one sign, forcing
    #    every used point into all 3 equal supports, or two have one sign and one
    #    the other; an overlap gives coefficient 2 and disjoint supports require a
    #    weight-3 column to cancel six positions. Both are impossible.
    dual_lower_bound=4
    # Weight-4 witness from a 4-subset inside a K5: all four 3-subsets sum to 0 mod3.
    S=tuple(sorted(K5[0][:4]));Ts=[tuple(sorted(T)) for T in itertools.combinations(S,3)]
    tid={T:i for i,T in enumerate(triangles)};ids=[tid[T] for T in Ts]
    witness=np.sum(B[:,ids],axis=1)%3
    assert not np.any(witness) and len(ids)==4
    dual_distance=4
    classical_distance=18  # exact theorem of Pass4799, rechecked by its workflow lane
    assert dual_distance<classical_distance
    n=270;r=44;k=n-2*r;assert k==182
    out={'pass':4800,'field':'F3','check_matrix':'45 x 270 point-triangle incidence B with rank 44',
      'commutation':'B B^T = 0 mod 3','Hx_rank':44,'Hz_rank':44,
      'classical_stabilizer_row_code':'[270,44,18]_3','dual_distance':4,
      'dual_weight4_witness_triangle_indices':ids,
      'dual_weight4_witness_model':'four 3-subsets of any chosen 4-set inside one GQ K5; every point occurs three times',
      'quantum_code':'[[270,182,4]]_3','logical_qutrits':182,'distance':4,
      'theorem':'Taking the intrinsic triangle-incidence matrix as both CSS check families gives a valid qutrit [[270,182,4]]_3 stabilizer code. Self-orthogonality supplies commutation; rank 44 gives k=182; the dual distance is exactly 4 and d(C)=18 keeps the weight-4 dual witnesses outside the stabilizer.',
      'boundary':'Finite CSS/stabilizer theorem only. No fault-tolerance threshold, local hardware realization, or physical energy scale is inferred from these algebraic parameters.'}
    OUT.write_text(json.dumps(out,indent=2,sort_keys=True)+'\n');print(json.dumps(out,indent=2,sort_keys=True));return 0
if __name__=='__main__':raise SystemExit(main())
