# Pass 1029: there is no orientation switch inside Sp(4,3).  Chirality is a
# BASE-level datum, and it is not the 2-primary class.
#
# Pass 1028 (other track) built the restriction-syndrome decoder on the Pass 1023
# halves and then left one candidate open, in its own words: "The independent
# binary chirality coordinate missing from the ternary selector is a natural
# candidate for an orientation-switch datum, but this pass does not claim or
# construct such an equivariant switch."
#
# This pass closes that candidate NEGATIVELY, and separates two ways of being C2
# that the corpus has been treating as interchangeable.
#
# The definition of chirality is the corpus's own, from
# analysis/A_REFLECTION_GROUP_CANNOT_ORIENT_ITSELF.md: a chirality is a datum
# distinguishing two objects exchanged by some w with det(w) = -1.  So the
# question "can the substrate switch orientation internally?" is literally the
# question "does the group contain an element of determinant -1?".
#
# Two facts settle it.
#
#   (a) Sp(4,3) is PERFECT.  det is a homomorphism to the abelian group {+-1}, so
#       it kills every commutator, hence kills the whole of a perfect group.
#       Therefore EVERY element of Sp(4,3) has det = +1.  No orientation switch
#       exists inside the total-space group, for any choice of element -- this is
#       a proof, not a search.
#
#   (b) The antipodal map, which GENERATES the 2-primary class of Pass 1023, is
#       -I on R^8 and has det = (-1)^8 = +1.  So the 2-primary "sign" obstruction
#       is generated by an ORIENTATION-PRESERVING element.
#
# Consequence: the chirality obstruction and the 2-primary section obstruction are
# both C2, and they are different C2s.  One is the determinant character (a
# quotient of the group); the other is a central subgroup lying inside its kernel.
# A quotient C2 and a central sub-C2 are not the same class and cannot be merged.
#
# Where det = -1 does live: not in Sp(4,3), but in the base-level group
# W(E6) = PGSp(4,3), which is not perfect.  That is exactly the two-level picture
# of Pass 1021 -- Sp(4,3) on the total space, W(E6) on the base -- so chirality is
# a BASE phenomenon and the sign obstruction is a TOTAL-SPACE phenomenon.
#
# PRIOR ART -- cited, not reclaimed:
#   * analysis/A_REFLECTION_GROUP_CANNOT_ORIENT_ITSELF.md -- the chirality
#     obstruction itself, and the det(w) = -1 definition.  Entirely its result.
#   * Pass 1028 -- the syndrome decoder and the open orientation-switch candidate.
#   * Pass 1023 -- the 2-primary / 3-primary split.
#   * Pass 1021/1020 -- the two-level fibration and Sp(4,3) perfect, W(E6) not.

REPO := GAPInfo.SystemEnvironment.W33_REPO;;
OUT := Concatenation(REPO, "/data/w33_pass1029_no_orientation_switch_inside.json");;
DIAG := Concatenation(REPO, "/data/w33_pass1029_diagnostic.txt");;

Assert29 := function(label, cond)
  if not cond then Error(Concatenation("Pass1029 failed: ", label)); fi;
end;;
Bool29 := function(v) if v then return "true"; fi; return "false"; end;;

Main29 := function()
  local roots, v, i, j, si, sj, m, k, rootIndex, ReflPerm, simples, S, Sinv,
        W, cox, w, negPerm, C, K, N, Det, detK, detNeg, detRefl, detN,
        nOrientReversing, checks, names, stream, tag, g;

  roots := [];
  for i in [1..8] do
    for j in [i+1..8] do
      for si in [1,-1] do for sj in [1,-1] do
        v := ListWithIdenticalEntries(8, 0);
        v[i] := 2*si; v[j] := 2*sj; Add(roots, v);
      od; od;
    od;
  od;
  for m in [0..255] do
    v := List([0..7], k -> (-1)^(QuoInt(m, 2^k) mod 2));
    if Number(v, x -> x = -1) mod 2 = 0 then Add(roots, v); fi;
  od;
  Assert29("240 roots", Length(roots) = 240);
  rootIndex := function(x) return Position(roots, x); end;
  ReflPerm := function(r)
    return PermList(List(roots, x -> rootIndex(x - ((x * r) / 4) * r)));
  end;
  simples := [
    [ 1,-1,-1,-1,-1,-1,-1, 1], [ 2, 2, 0, 0, 0, 0, 0, 0],
    [-2, 2, 0, 0, 0, 0, 0, 0], [ 0,-2, 2, 0, 0, 0, 0, 0],
    [ 0, 0,-2, 2, 0, 0, 0, 0], [ 0, 0, 0,-2, 2, 0, 0, 0],
    [ 0, 0, 0, 0,-2, 2, 0, 0], [ 0, 0, 0, 0, 0,-2, 2, 0] ];
  W := Group(List(simples, ReflPerm));
  Assert29("|W(E8)|", Size(W) = 696729600);

  # THE DETERMINANT CHARACTER, computed explicitly.  The simple roots are a basis
  # S of R^8.  An element g sends the i-th simple root to roots[ idx(s_i)^g ], so
  # the matrix of g in the simple-root basis is S^-1 * S_g, and det(g) is the
  # ratio of determinants.  No character table, no assumption.
  S := simples;
  Sinv := S ^ -1;
  Det := function(g)
    local Sg;
    Sg := List(simples, r -> roots[ rootIndex(r) ^ g ]);
    return Determinant(Sinv * Sg);
  end;

  # sanity: a reflection must have det -1, and det must be multiplicative
  detRefl := Det(ReflPerm(simples[1]));
  Assert29("reflection has det -1", detRefl = -1);
  Assert29("det is multiplicative on a sample",
    Det(ReflPerm(simples[1]) * ReflPerm(simples[2])) = 1);

  cox := Product(List(simples, ReflPerm));
  w := cox ^ 10;
  negPerm := PermList(List(roots, x -> rootIndex(-x)));
  C := Centralizer(W, w);
  K := DerivedSubgroup(C);
  N := Normalizer(W, Group(w));
  Assert29("|K| = 51840", Size(K) = 51840);

  detK  := Set(List(GeneratorsOfGroup(K), Det));
  detNeg := Det(negPerm);
  detN  := Set(List(GeneratorsOfGroup(N), Det));
  nOrientReversing := Number(GeneratorsOfGroup(N), g2 -> Det(g2) = -1);

  checks := rec();

  # (a) Sp(4,3) is perfect, so det kills it -- verified on generators AND proved
  checks.Sp43_is_perfect := IsPerfect(K);
  checks.Sp43_generators_all_have_det_plus_one := detK = [1];
  checks.no_orientation_switch_inside_Sp43 := IsPerfect(K) and detK = [1];

  # (b) the generator of the 2-primary class is orientation-PRESERVING
  checks.antipodal_map_has_det_plus_one := detNeg = 1;
  checks.antipodal_map_is_central_in_K := negPerm in K and negPerm in Centre(K);

  # (c) therefore the two C2s are different
  checks.chirality_C2_is_not_the_2primary_C2 :=
    detNeg = 1 and detRefl = -1;

  # (d) STRONGER THAN EXPECTED.  det = -1 exists in W(E8) (any reflection), but
  # the ENTIRE omega-normaliser -- order 311040, covering both the total space
  # Sp(4,3) and the base W(E6) -- is orientation-preserving.  det is a
  # homomorphism, so checking the generators settles the whole group.
  #
  # The reason is structural, not accidental: every element of the normaliser is
  # C-linear or conjugate-linear on C^4.  A C-linear A has det_R(A) = |det_C(A)|^2
  # > 0, and complex conjugation on C^4 = R^8 has det = (-1)^4 = +1.  A complex
  # structure INDUCES an orientation, so nothing preserving that structure can
  # reverse it.  The Eisenstein structure is itself the obstruction.
  checks.det_minus_one_exists_in_WE8 := detRefl = -1;
  checks.whole_normaliser_is_orientation_preserving := detN = [1];
  checks.orientation_reversal_is_outside_the_eisenstein_tower :=
    detN = [1] and detRefl = -1 and Size(N) < Size(W);
  checks.K_is_proper_in_normaliser := IsSubgroup(N, K) and Size(N) > Size(K);

  names := RecNames(checks);
  stream := OutputTextFile(DIAG, false);
  SetPrintFormattingStatus(stream, false);
  for tag in names do
    WriteAll(stream, Concatenation(tag, " = ", Bool29(checks.(tag)), "\n"));
  od;
  WriteAll(stream, Concatenation("detK = ", String(detK), "\n"));
  WriteAll(stream, Concatenation("detNeg = ", String(detNeg), "\n"));
  WriteAll(stream, Concatenation("detN = ", String(detN), "\n"));
  WriteAll(stream, Concatenation("|N| = ", String(Size(N)), "\n"));
  WriteAll(stream, Concatenation("orientation-reversing gens of N = ",
    String(nOrientReversing), " of ", String(Length(GeneratorsOfGroup(N))), "\n"));
  CloseStream(stream);
  Assert29("all checks", ForAll(names, tag -> checks.(tag)));

  stream := OutputTextFile(OUT, false);
  SetPrintFormattingStatus(stream, false);
  WriteAll(stream, "{\n");
  WriteAll(stream, "  \"schema\": \"w33.pass1029.no_orientation_switch_inside.gap.v1\",\n");
  WriteAll(stream, "  \"status\": \"PASS\",\n");
  WriteAll(stream, "  \"headline\": \"No orientation switch exists inside Sp(4,3). It is perfect, so the determinant character kills it and every element has det +1; and the antipodal map generating the 2-primary class is -I on R^8, also det +1. So the chirality obstruction (which needs det = -1) and the 2-primary section obstruction are different C2s: a quotient character versus a central subgroup inside its kernel. Chirality is a BASE-level datum, carried by W(E6), not by the total-space group.\",\n");
  WriteAll(stream, "  \"determinant_character\": {\n");
  WriteAll(stream, "    \"method\": \"explicit: matrix of g in the simple-root basis, S^-1 * S_g, then Determinant\",\n");
  WriteAll(stream, Concatenation("    \"reflection\": ", String(detRefl), ",\n"));
  WriteAll(stream, Concatenation("    \"antipodal_map\": ", String(detNeg), ",\n"));
  WriteAll(stream, Concatenation("    \"Sp43_generators\": ", String(detK), ",\n"));
  WriteAll(stream, Concatenation("    \"normaliser_generators\": ", String(detN), "\n"));
  WriteAll(stream, "  },\n");
  WriteAll(stream, "  \"closes\": \"Pass 1028's open candidate: the missing binary chirality coordinate cannot be an equivariant orientation-switch datum internal to Sp(4,3), because no element of a perfect group has det -1. The proof is one line and needs no search over elements.\",\n");
  WriteAll(stream, "  \"separation\": \"chirality C2 = the determinant character, a QUOTIENT of the group; 2-primary C2 = the antipodal map, a CENTRAL SUBGROUP lying inside ker(det). A quotient C2 and a central sub-C2 are not the same class and must not be merged.\",\n");
  WriteAll(stream, "  \"two_level_reading\": \"Consistent with Pass 1021: Sp(4,3) is the total-space group and is entirely orientation-preserving; W(E6) = PGSp(4,3) is the base group and is not perfect, so det = -1 lives there. Chirality is a base phenomenon; the sign obstruction is a total-space phenomenon.\",\n");
  WriteAll(stream, "  \"scope\": \"This is a negative result about internal realisability. It does not construct any external orientation datum, and it does not touch the 3-primary phase side.\",\n");
  WriteAll(stream, Concatenation("  \"check_count\": ", String(Length(names)), ",\n"));
  WriteAll(stream, "  \"checks\": {\n");
  for tag in names do
    WriteAll(stream, Concatenation("    \"", tag, "\": ", Bool29(checks.(tag))));
    if tag <> names[Length(names)] then WriteAll(stream, ","); fi;
    WriteAll(stream, "\n");
  od;
  WriteAll(stream, "  }\n}\n");
  CloseStream(stream);
  Print("Pass1029 status=PASS checks=", Length(names), " output=", OUT, "\n");
end;;

Main29();;
QUIT;
