from pathlib import Path
import importlib.util
from fractions import Fraction
import sympy as sp

ROOT=Path(__file__).resolve().parents[1]
s=importlib.util.spec_from_file_location("dw",ROOT/"analysis/w33_diagonal_weld_e8_lie_generation.py");m=importlib.util.module_from_spec(s);s.loader.exec_module(m)
compiler,bridge,table=m.load_inputs();amps=m.backgrounds(bridge);vecs=m.source_generators(compiler,amps)
rb,_=m.closure((vecs[(1,"center")],vecs[(2,"center")]),table,m.RationalBasis()); B=rb.vectors
def br(a,b):return m.bracket(a,b,table,None)

# Exact ideal generated by B[6], known by two modular audits to be I15.
def exact_ideal(seed):
 M=m.RationalBasis(); q=[]
 if M.add(seed,0):q=[M.vectors[-1]]
 while q:
  v=q.pop()
  for g in B:
   if M.add(br(g,v),0):q.append(M.vectors[-1])
 return M
I15=exact_ideal(B[6]); print("I15",len(I15.rows))
assert len(I15.rows)==15

# Exact quotient basis L/I15, pivot ordered.
base=m.RationalBasis()
for v in I15.vectors:base.add(v,0)
Q=m.RationalBasis()
for v in B:
 r=list(map(Fraction,v))
 for p in sorted(base.rows):
  if r[p]:
   f=r[p]; row=base.rows[p]; r=[a-f*b for a,b in zip(r,row)]
 Q.add(r,0)
qp=sorted(Q.rows); qbasis=[Q.rows[p] for p in qp]; print("Qdim",len(qbasis),"piv",qp)
assert len(qbasis)==9

def reduce_I(v):
 r=list(map(Fraction,v))
 for p in sorted(base.rows):
  if r[p]:
   f=r[p];row=base.rows[p];r=[a-f*b for a,b in zip(r,row)]
 return r
def qcoords(v):
 r=reduce_I(v);co=[]
 for p in qp:
  c=r[p];co.append(c)
  if c:
   row=Q.rows[p];r=[a-c*b for a,b in zip(r,row)]
 assert all(x==0 for x in r)
 return co

n=9
ads=[]
for i,a in enumerate(qbasis):
 A=sp.zeros(n,n)
 for j,b in enumerate(qbasis):
  c=qcoords(br(a,b))
  for k,x in enumerate(c): A[k,j]=sp.Rational(x.numerator,x.denominator)
 ads.append(A)
# centroid unknown 9x9 X commuting with all ad_i
vars=sp.symbols('x0:'+str(n*n)); X=sp.Matrix(n,n,vars)
eq=[]
for A in ads:
 C=X*A-A*X
 eq.extend(list(C))
M,b=sp.linear_eq_to_matrix(eq,vars)
ns=M.nullspace(); print("centroid_dim",len(ns))
Cs=[sp.Matrix(n,n,list(v)) for v in ns]
for i,C in enumerate(Cs):
 print("C",i,"trace",sp.trace(C),"charpoly",sp.factor(C.charpoly().as_expr()))
# locate identity direction and simple primitive candidates
t=sp.symbols('lambda')
cands=[]
for coeff in [(1,0,0),(0,1,0),(0,0,1),(1,1,0),(1,0,1),(0,1,1),(1,2,3),(1,-1,2),(2,3,5)]:
 if len(Cs)!=3:break
 C=sum((sp.Rational(c)*A for c,A in zip(coeff,Cs)),sp.zeros(n))
 cp=sp.factor(C.charpoly(t).as_expr())
 fac=sp.factor_list(cp)
 cands.append((coeff,cp,fac))
 print("combo",coeff,"charpoly",cp,"factors",fac)
# choose first whose charpoly is cubic^3 and compute cubic discrim
for coeff,cp,fac in cands:
 if len(fac[1])==1 and fac[1][0][1]==3 and sp.Poly(fac[1][0][0],t).degree()==3:
  f=sp.Poly(fac[1][0][0],t)
  print("PRIMITIVE",coeff,"minpoly",f.as_expr(),"disc",sp.discriminant(f.as_expr(),t))
  print("numberfield_disc",sp.polys.numberfields.round_two(f)[1] if hasattr(sp.polys.numberfields,'round_two') else "na")
  break
# Killing determinant exact
K=sp.Matrix(n,n,lambda i,j:sp.trace(ads[i]*ads[j]))
print("Krank",K.rank(),"Kdet_factor",sp.factorint(abs(int(K.det()))) if K.det().q==1 else K.det())
import numpy as np
ev=np.linalg.eigvalsh(np.array(K.evalf(),dtype=float))
print("Ksignature",sum(ev>1e-9),sum(ev<-1e-9),sum(abs(ev)<=1e-9),"evals",ev.tolist())
C0=Cs[0]; Id=sp.eye(9)
Theta=sp.Rational(64625659617,1564341125)*C0**2-sp.Rational(11877391716,312868225)*C0+sp.Rational(1599657,933935)*Id
R=sp.simplify(Theta**3-Theta**2-53*Theta-120*Id)
print("smallpoly_residual",max(abs(x) for x in R),"theta_charpoly",sp.factor(Theta.charpoly().as_expr()),"smallpoly_disc",sp.discriminant(sp.Symbol("lambda")**3-sp.Symbol("lambda")**2-53*sp.Symbol("lambda")-120,sp.Symbol("lambda")))
