#!/usr/bin/env python3
from __future__ import annotations
import argparse,hashlib,json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1];OUT=ROOT/'data'/'w33_pass588_594_deep_symmetry_release.json'
FILES={str(n):ROOT/'data'/f'w33_pass{n}_{name}.json' for n,name in [(588,'minimal_degree_groupoid'),(589,'full_linear_symmetry_centralizer'),(590,'oriented_singer_cover'),(591,'cyclotomic_dedekind_dvr'),(592,'aspirational_affinity_correction'),(593,'icosahedral_singer_fibre'),(594,'johnson_pentagon_holonomy')]}
def payload():
 raw={k:v.read_bytes() for k,v in FILES.items()};p={k:json.loads(raw[k]) for k in raw};cust={k:{'path':str(FILES[k].relative_to(ROOT)),'sha256':hashlib.sha256(raw[k]).hexdigest(),'checks':sum(p[k]['checks'].values())} for k in p}
 checks={'all_seven_owners_pass':all(x['status']=='PASS' for x in p.values()),'owner_check_total86':sum(x['checks'] for x in cust.values())==86,'degree13_transpositions_optimal':p['588']['transpositions']['exact_degree']==13,'all_1093_top_forms_distinct':p['588']['point_indicator']['distinct_degree13_leading_forms']==1093,'full_linear_spectral_group_C3':p['589']['colored_projective_search']['identification'].startswith('C3'),'centralizer_family_order_locked':p['589']['centralizer_family']['invertible_centralizer_order']==18935612583143002835272704,'universal_linear_A4_no_go':p['589']['checks']['universal_linear_A4_no_go'],'oriented_Johnson112':p['590']['oriented_Johnson']['double_cover_objects']==112,'common_refinement672':p['590']['Singer_refinement']['oriented_flags']==672,'Singer_pentagon_image_S5_A5':p['590']['six_pentagon_action']['image_order']==120 and p['590']['six_pentagon_action']['oriented_image_order']==60,'maximal_order_index1':p['591']['global_order']['index_squared']==1,'localized_e4_f1':p['591']['local_prime']['ramification_index']==4 and p['591']['local_prime']['residue_degree']==1,'aspirational_grid_tie_superseded':p['592']['checks']['old_grid_value_violates_orientation_lower_bound'],'continuous_uniform_gap_gt0_9995':p['592']['strictness']['certified_uniform_gap_lower_bound']>.9995,'strict_uniform_neighborhood':p['592']['strictness']['L1_neighborhood_radius']>.00249,'Singer_fibre_P1F5':p['593']['six_fibre']['mobius_model']=='PGL(2,5) on P1(F5)','Singer_augmentation280':p['593']['augmentation']['global_bundle_dimension']==280,'Johnson_connection_holonomy_S5':p['594']['holonomy']['order']==120,'Johnson_triangles_generate_holonomy':p['594']['holonomy']['triangles_generate_full_holonomy']}
 return {'schema':'w33.pass588_594.deep_symmetry.release.v1','status':'PASS' if all(checks.values()) else 'FAIL','owner_check_total':sum(x['checks'] for x in cust.values()),'owner_custody':cust,'headline':{'588':'Generalized Reed-Muller support plus 1,093 distinct leading forms proves every projective transposition has optimal reduced degree 13.','589':'An exact colored-projective-frame search proves the full linear spectral automorphism group of PG(12,3) is C3, ruling out every linear A4 extension across all 1.893e25 intertwiners.','590':'The oriented Johnson double cover has 112 signed exterior-basis objects and a common 672-object refinement with the Singer pentagon flags.','591':'Discriminant equality gives index-one maximal order; Dedekind localization closes the DVR theorem generically and arithmetic gives e=4,f=1.','592':'The prior aspirational grid tie is invalid: an exact marginal lower bound and explicit joint SPRT certify a continuous uniform-prior gain above 0.9995.','593':'Each Singer six-fibre is P1(F5), the six icosahedral fivefold axes; its irreducible augmentation is five-dimensional and globally totals 280.','594':'A canonical even Johnson edge connection has full exceptional degree-six S5 holonomy, generated already by triangle loops.'},'release_checks':checks,'boundary':'Exact for the declared polynomial-function ring, full linear projective spectral coloring, finite A8/S5 actions, cyclotomic arithmetic, and readout model. No sub-degree-13 non-transposition generating theorem, nonlinear A4 no-go, E7 minuscule identification, compiled concrete Dedekind instance, or complete equality-surface classification is claimed.'}
def main():
 ap=argparse.ArgumentParser();ap.add_argument('--check',action='store_true');ap.add_argument('--output',type=Path,default=OUT);a=ap.parse_args();p=payload();s=json.dumps(p,sort_keys=True,separators=(',',':'))+'\n'
 if a.check:
  if not a.output.exists() or a.output.read_text()!=s:raise SystemExit('drift')
 else:a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(s)
 print(json.dumps({'status':p['status'],'checks':sum(p['release_checks'].values()),'total':len(p['release_checks']),'owners':p['owner_check_total']}));return 0 if p['status']=='PASS' else 1
if __name__=='__main__':raise SystemExit(main())
