#!/usr/bin/env python3
"""Export the certified BT360/BT361 selector design as GAP assignments.

Several historical GAP certificates read data/bt360_120sheet_design_for_gap.txt,
but that generated file was never tracked.  This exporter removes the hidden
prerequisite by rebuilding the 120 sheets from the repository's deterministic
constructors and writing the exact overlap matrix, anchor lines, phase labels,
and W(3,3) lines in GAP syntax.
"""

from __future__ import annotations

import sys
from collections import defaultdict
from pathlib import Path
from typing import Iterable

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from analysis.w33_BREAKTHROUGH_357_minimal_logical_orbit_stabilizers import (  # noqa: E402
    build_w33,
    generate_projective_symplectic_group,
)
from analysis.w33_BREAKTHROUGH_360_selector_zmin_sheet_design import (  # noqa: E402
    selector_failure_edge_supports,
    sheet_orbit,
)
from analysis.w33_BREAKTHROUGH_361_selector_qutrit_phase_bundle import (  # noqa: E402
    sheet_anchor_line,
)

OUT = ROOT / "data" / "bt360_120sheet_design_for_gap.txt"


def gap_list(values: Iterable[object]) -> str:
    rendered = []
    for value in values:
        if isinstance(value, (list, tuple)):
            rendered.append(gap_list(value))
        else:
            rendered.append(str(value))
    return "[" + ",".join(rendered) + "]"


def main() -> int:
    points, edges, edge_index, lines, _adjacency = build_w33()
    group = generate_projective_symplectic_group(points)
    base_sheet = frozenset(selector_failure_edge_supports(edges, edge_index))
    sheets = sheet_orbit(group, base_sheet, edges, edge_index)
    if len(sheets) != 120:
        raise AssertionError(f"expected 120 selector sheets, found {len(sheets)}")

    intersections = [
        [len(left & right) for right in sheets]
        for left in sheets
    ]
    anchors = [sheet_anchor_line(sheet, edges, lines) for sheet in sheets]

    fibres: dict[int, list[int]] = defaultdict(list)
    for sheet_id, line_id in enumerate(anchors):
        fibres[line_id].append(sheet_id)
    if sorted(len(fibre) for fibre in fibres.values()) != [3] * 40:
        raise AssertionError("selector anchors are not forty fibres of size three")

    phases = [-1] * 120
    for line_id in sorted(fibres):
        for phase, sheet_id in enumerate(sorted(fibres[line_id])):
            phases[sheet_id] = phase
    if sorted(phases).count(-1):
        raise AssertionError("phase export left an unlabelled sheet")

    lines_zero_based = [list(line) for line in lines]
    payload = "\n".join(
        [
            "# Deterministically regenerated by w33_pass1026_export_selector_gap_data.py",
            f"intersection_matrix := {gap_list(intersections)};;",
            f"anchor_line_by_sheet := {gap_list(anchors)};;",
            f"phase_by_sheet := {gap_list(phases)};;",
            f"lines := {gap_list(lines_zero_based)};;",
            "",
        ]
    )
    OUT.parent.mkdir(exist_ok=True)
    OUT.write_text(payload, encoding="utf-8")
    print(
        "Pass1026 selector GAP export: PASS — "
        f"sheets={len(sheets)} fibres={len(fibres)} output={OUT.relative_to(ROOT)}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
