#!/usr/bin/env python3
"""Pass 11607: weld the Hesse CP discriminant to the unique Spin(10) Weyl selector.

The result is an exact finite-carrier/EFT statement.  It does not construct a
Lorentzian chiral path integral, anomaly measure, or E8 shell-selection theorem.
"""
import hashlib
import itertools
import json
from pathlib import Path

import sympy as s

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "data/PART_W33_PASS11607_HESSE_CP_WEYL_SELECTOR.json"


def portable_hash(path: Path) -> str:
    if path.suffix == ".json":
        raw = json.dumps(json.loads(path.read_text()), sort_keys=True, separators=(",", ":")).encode()
    else:
        raw = path.read_bytes().replace(b"\r\n", b"\n")
    return hashlib.sha256(raw).hexdigest()


def d3_group():
    out = []
    for perm in itertools.permutations(range(3)):
        inv = sum(perm[i] > perm[j] for i in range(3) for j in range(i + 1, 3))
        parity = -1 if inv % 2 else 1
        for signs in itertools.product([-1, 1], repeat=3):
            if signs[0] * signs[1] * signs[2] != 1:
                continue
            M = s.zeros(3)
            for i in range(3):
                M[i, perm[i]] = signs[i]
            out.append((M, parity))
    assert len(out) == 24
    return out


def monomials_of_degree(d):
    return [(a, b, d - a - b) for a in range(d + 1) for b in range(d + 1 - a)]


def sign_projector_rank(d):
    basis = monomials_of_degree(d)
    pos = {e: i for i, e in enumerate(basis)}
    P = s.zeros(len(basis))
    for M, eps in d3_group():
        for j, exps in enumerate(basis):
            target = [0, 0, 0]
            coeff = s.Integer(1)
            for i, power in enumerate(exps):
                nz = [k for k in range(3) if M[i, k] != 0]
                assert len(nz) == 1
                k = nz[0]
                coeff *= M[i, k] ** power
                target[k] += power
            P[pos[tuple(target)], j] += eps * coeff
    P /= 24
    assert P * P == P
    return int(P.rank()), P, basis


def flavor_sign_sector():
    x, y, z = s.symbols("x y z", real=True)
    v = s.Matrix([x, y, z])
    rho2 = x*x + y*y + z*z
    W = s.expand((x*x-y*y)*(y*y-z*z)*(z*z-x*x))
    for M, eps in d3_group():
        sub = dict(zip(v, M*v))
        assert s.expand(rho2.subs(sub, simultaneous=True) - rho2) == 0
        assert s.expand(W.subs(sub, simultaneous=True) - eps*W) == 0

    dims = {}
    projectors = {}
    bases = {}
    for degree in range(7):
        rank, P, basis = sign_projector_rank(degree)
        dims[str(degree)] = rank
        projectors[degree] = P
        bases[degree] = basis
    assert [dims[str(d)] for d in range(6)] == [0]*6
    assert dims["6"] == 1

    poly = s.Poly(W, x, y, z)
    coeff = s.zeros(len(bases[6]), 1)
    for mon, val in poly.terms():
        coeff[bases[6].index(mon), 0] = val
    assert projectors[6] * coeff == coeff

    m = s.Matrix([1, 2, 3]) / s.sqrt(14)
    orbit = {tuple(s.simplify(a) for a in M*m) for M, _ in d3_group()}
    vals = []
    for p in orbit:
        val = s.factor(W.subs({x:p[0], y:p[1], z:p[2]}))
        vals.append(val)
    c = s.Rational(15, 343)
    assert len(orbit) == 24
    assert vals.count(c) == 12 and vals.count(-c) == 12

    return {
        "group": "W(D3) ~= S4 in the signed-permutation realization, order 24",
        "sign_character": "permutation parity; A4 is the even kernel",
        "anti_invariant_dimensions_by_bloch_degree_0_to_6": dims,
        "minimal_anti_invariant_bloch_degree": 6,
        "minimal_anti_invariant_field_degree": 12,
        "generator": "W=(x^2-y^2)(y^2-z^2)(z^2-x^2)",
        "theorem": "No nonzero polynomial carrying the odd S4/A4 sign character exists below Bloch degree 6. At degree 6 the sign-isotypic space is one-dimensional and generated by W. Since each Bloch coordinate is bilinear in the Hesse doublet, W has field degree 12.",
        "vacuum_rays": 24,
        "vacuum_W_values": ["+15 rho^6/343", "-15 rho^6/343"],
        "vacuum_W_multiplicities": [12, 12],
    }


def spin10_pin_lift():
    gd = json.loads((ROOT / "data/w33_pass10961_albert_clifford9_gammas.json").read_text())
    g9 = [s.Matrix([[s.Rational(x) for x in row] for row in M]) for M in gd["gamma9"]]
    I16, Z16 = s.eye(16), s.zeros(16)
    gam = [
        s.Matrix.vstack(s.Matrix.hstack(Z16, x), s.Matrix.hstack(x, Z16))
        for x in g9
    ] + [s.diag(I16, -I16)]
    I32 = s.eye(32)
    for a in gam:
        assert a*a == I32
    prod = I32
    for a in gam:
        prod *= a
    Chi = s.I * prod
    assert Chi*Chi == I32
    assert Chi.H == Chi

    # The certified two-tick clock is i*Gamma_10.  Its adjoint action is the
    # order-two Pin reflection even though the spinor lift squares to -I.
    R = s.I * gam[9]
    Rinv = -R
    assert R*R == -I32
    assert s.simplify(R*Chi*Rinv + Chi) == s.zeros(32)

    bivectors = []
    normalized = []
    for i, j in itertools.combinations(range(10), 2):
        B = gam[i]*gam[j]
        expected = -B if 9 in (i, j) else B
        got = s.simplify(R*B*Rinv)
        assert got == expected
        assert B*Chi == Chi*B
        bivectors.append((i, j))
        normalized.append(-1 if 9 in (i, j) else 1)

    plus = len((Chi-I32).nullspace())
    minus = len((Chi+I32).nullspace())
    assert plus == 16 and minus == 16
    return {
        "chirality_spectrum": {"+1": plus, "-1": minus},
        "pin_lift": "R=i Gamma_10 = certified two-tick clock G^2",
        "pin_square": "R^2=-I",
        "adjoint_order": 2,
        "chirality_action": "R Chi R^-1 = -Chi",
        "so10_normalizer": "R fixes bivectors Gamma_i Gamma_j with i,j<10 and negates the nine bivectors containing Gamma_10; hence it normalizes the full so(10) bivector algebra.",
        "bivectors_checked": len(bivectors),
        "commutant": "[Chi, so(10)]=0",
        "projective_boundary": "The odd lift is projective on spinors because R^2=-I, but its adjoint action is an honest Z2 automorphism. No claim is made that the flavor S4 and Spin(10) Pin lift are the same microscopic group.",
    }


def diagonal_selector():
    flavor = flavor_sign_sector()
    spin = spin10_pin_lift()
    c = s.Rational(15, 343)

    # At a Hesse vacuum, W=s*c*rho^6 with s=+-1.  Define
    # A=c*rho^6 I + W Chi; H=lambda A^2.  In units rho=1, lambda=1:
    # H_s=4 c^2 P_s, so one Weyl block is an exact kernel.
    gap = s.factor(4*c*c)
    rows = []
    for sig in [1, -1]:
        rows.append({
            "W_sign": sig,
            "W_over_rho6": str(sig*c),
            "zero_chirality": -sig,
            "gapped_chirality": sig,
            "zero_multiplicity": 16,
            "gapped_multiplicity": 16,
            "gap_coefficient_times_lambda_rho12": str(gap),
        })

    return {
        "flavor": flavor,
        "spin10": spin,
        "diagonal_action": "For even Hesse transformations use the identity on the Spin(10) carrier; for the odd CP/reflection coset use Ad_R. Then W -> eps W and Chi -> eps Chi, so W Chi is invariant. The action-level diagonal symmetry is exact in the adjoint/projective sense.",
        "minimal_portal": "eta W Chi is the lowest-Bloch-degree polynomial gauge-invariant portal that compensates the odd flavor sign character; W is forced up to invariant factors by the explicit degree-0..6 sign-projector computation.",
        "positive_filter": "H_gap=lambda[(15/343) rho^6 I + W Chi]^2, lambda>0",
        "positive_filter_expansion": "lambda[((15/343)^2 rho^12 + W^2) I + (30/343) rho^6 W Chi]",
        "vacuum_rows": rows,
        "vacuum_theorem": "At every one of the 24 Pass11600 Hesse minima, H_gap is exactly 4 lambda (15/343)^2 rho^12 times one Weyl projector and vanishes on the other 16-dimensional Weyl block. The 12 CP-conjugate vacua exchange which chirality is the kernel.",
        "residual_symmetry": "The even A4 flavor subgroup acts without an internal Pin flip and preserves each W-sign orbit. The odd coset exchanges the two vacuum orbits and, through R, exchanges the two Weyl kernels.",
        "field_degree": {"linear_diagonal_portal": 12, "manifestly_positive_exact_kernel_filter": 24},
        "boundary": "This is an exact positive internal penalty/filter on the executable finite Spin(10) carrier. It does not by itself construct a relativistic chiral fermion measure, prove anomaly cancellation, select the E8 (27,3) rather than conjugate shell, derive the portal coefficient, protect this high-dimension EFT operator, or prove that the gapped block decouples in a local continuum theory.",
    }


def produce():
    out = {
        "status": "PASS_HESSE_CP_DISCRIMINANT_WELDS_TO_UNIQUE_WEYL_SELECTOR",
        "pass_number": 11607,
        "reservation": "7d4cdfacf",
        "result": diagonal_selector(),
    }
    sources = [
        "analysis/w33_pass11600_dynamical_hesse_flavor.py",
        "data/w33_pass11600_dynamical_hesse_flavor.json",
        "analysis/w33_pass11593_unique_weyl_selector.py",
        "data/PART_W33_PASS11593_UNIQUE_WEYL_SELECTOR.json",
        "analysis/w33_pass11598_clock_floquet_chirality.py",
        "data/PART_W33_PASS11598_CLOCK_FLOQUET_CHIRALITY.json",
        "data/w33_pass10961_albert_clifford9_gammas.json",
    ]
    out["source_sha256"] = {p: portable_hash(ROOT / p) for p in sources}
    out["producer_sha256"] = portable_hash(Path(__file__))
    OUT.write_text(json.dumps(out, indent=2, sort_keys=True) + "\n")
    print(json.dumps(out, indent=2, sort_keys=True))
    return out


if __name__ == "__main__":
    produce()
