#!/usr/bin/env python3
"""Pass10033-10040 outside-box: the common C13 clock carries a canonical C2 orientation.

Both the abstract V2 Singer clock and the G2(4):2 torus clock have a C12 group
of automorphisms of C13.

V2 side:
  N_GL12(C13) = C4095:C12, with C12 generated by Frobenius x -> x^2 on
  F_{2^12}; ord_13(2)=12.

G2 side:
  N_{G2(4)}(C13) = C13:C6,
  N_{G2(4):2}(C13) = C13:C12.

Therefore the unique quotient C12/C6 = C2 is canonical on BOTH clock
normalizers.  On the G2 side it is exactly the outer-extension bit distinguishing
G2(4) from G2(4):2.  On the abstract V2 side it is Frobenius parity.  This gives
a precise candidate orientation character to compare with the earlier Golay
A4<S4 bit once an actual V2/G2 transporter exists.
"""
from __future__ import annotations
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
OUT=ROOT/'data/PART_W33_PASS10033_10040_C13_CLOCK_ORIENTATION_CHARACTER.json'

def order_mod(a,n):
    x=1
    for k in range(1,n+1):
        x=x*a%n
        if x==1:return k
    raise RuntimeError

def main():
    assert order_mod(2,13)==12
    assert 2**12-1==4095==13*315
    assert 4095*12==49140
    assert 13*6==78 and 13*12==156
    # The unique index-two subgroup of cyclic C12 has order 6.
    assert 12//6==2
    out={
      'schema':'w33.pass10033_10040.c13_clock_orientation_character.v1','status':'PASS','passes':'10033-10040','outside_box':True,
      'V2_abstract':{
        'normalizer':'C4095:C12','clock_automorphism':'C12 = <Frob_2>','ord_13_2':12,
        'orientation_kernel':'C6=<Frob_2^2>','orientation_quotient':'C12/C6=C2','reading':'Frobenius parity'},
      'G2':{
        'inside_G2_4':'N(C13)=C13:C6, order 78',
        'inside_G2_4_colon_2':'N(C13)=C13:C12, order 156',
        'orientation_quotient':'(C13:C12)/(C13:C6)=C2','reading':'outer-extension bit G2(4):2 / G2(4)'},
      'common_character':{
        'domain':'Aut(C13)=C12','kernel':'C6','codomain':'C2',
        'candidate_weld':'identify Frobenius parity on the V2 semilinear clock with the G2 outer-extension parity'},
      'theorem':'The shared C13 clock has a canonical binary orientation character C12 -> C2 with kernel C6. On G2(4):2 this character is exactly the outer involution quotient; on the abstract V2 Singer normalizer it is Frobenius parity. Thus a C2 orientation bit is intrinsic to the clock normalizer rather than attached ad hoc.',
      'boundary':'Standard Singer/finite-field and G2 torus-normalizer structure. Equality with the earlier Golay A4<S4 orientation bit is a concrete future compatibility test, not claimed here.'}
    OUT.write_text(json.dumps(out,indent=2,sort_keys=True)+'\n')
    print(json.dumps({'status':'PASS','clock':'C13','automorphisms':'C12','orientation':'C2'}))
    return 0
if __name__=='__main__':raise SystemExit(main())
