#!/usr/bin/env python3
"""
Pass 1170: MeatAxe kernel decomposition plan with exact linear algebra pre-work.

The 2195-dim cubic map kernel is a W(E6)-module. To decompose it:

Step A: Reduction modulo a prime p.
  Choose p not dividing |W(E6)| = 51840 = 2^7 * 3^4 * 5.
  Good primes: 7, 11, 13, 17, 19, 23, ...
  MeatAxe works over GF(p). We choose p=7 as smallest good prime.

Step B: Generators of W(E6) in the 2195-dim representation.
  W(E6) is generated by 6 simple reflections r_1,...,r_6.
  Each r_i acts on the 40-dim point space by a specific 40x40 matrix.
  The Sym^3 (or cubic-domain) action is the induced action on the
  2240-dim domain, restricted to the 2195-dim kernel.
  The 2195 x 2195 matrices for r_1,...,r_6 mod 7 are the MeatAxe input.

Step C: Spin test and composition factors.
  MeatAxe decomposes V over GF(7) into composition factors.
  If all W(E6) irreps lift from GF(7) (i.e., p=7 does not divide
  the Schur index), the composition factors mod 7 correspond to
  the characteristic-0 irreps.
  |W(E6)| = 51840 = 2^7 * 3^4 * 5. Since 7 does not divide 51840,
  all W(E6) irreps are absolutely irreducible over GF(7) (by Maschke).
  So the GF(7) decomposition = the characteristic-0 decomposition.

Step D: Expected decomposition of the 2195-dim kernel.
  2195 = kernel_dim. We need to express 2195 as a sum of W(E6) irrep dims.
  From Pass 1160, W(E6) irrep dims: [1,6,6,10,15,15,20,20,24,24,30,
  60,60,64,80,81,90,90,120,120,160,216,240,270,360].
  2195 = 2195. Let us search:
  2195 = 1952 + 243 (Steinberg packet + residual)
  2195 = 243 + 1952
  243 = 3 * 81 (the Steinberg packet, already identified)
  1952 remaining.
  Key decompositions of 2195 using W(E6) dims:
  Try: 360+270+240+216+160+120+120+90+90+81+80+64+60+60+
       30+24+24+20+20+15+15+10+6+6+1 = sum of ALL 25 irreps
       = sqrt(25920) ... no, sum of dims = ?
  sum([1,6,6,10,15,15,20,20,24,24,30,60,60,64,80,81,90,90,
       120,120,160,216,240,270,360]) = ?

Outputs: data/MEATAXE_KERNEL_PLAN_2026_07_27.json
"""
import json
from pathlib import Path
from datetime import datetime

WE6_IRREP_DIMS = [
    1, 6, 6, 10, 15, 15, 20, 20, 24, 24,
    30, 60, 60, 64, 80, 81, 90, 90, 120, 120,
    160, 216, 240, 270, 360
]

def find_decomp(target, dims, max_terms=8):
    results = []
    d_sorted = sorted(set(d for d in dims if d <= target), reverse=True)
    def bt(rem, idx, path):
        if rem == 0: results.append(list(path)); return
        if len(path) >= max_terms: return
        for i in range(idx, len(d_sorted)):
            if d_sorted[i] > rem: continue
            path.append(d_sorted[i])
            bt(rem - d_sorted[i], i, path)
            path.pop()
    bt(target, 0, [])
    return sorted(results, key=lambda x: (len(x), [-v for v in x]))

def main():
    we6_sum = sum(WE6_IRREP_DIMS)
    we6_sq_sum = sum(d**2 for d in WE6_IRREP_DIMS)
    assert we6_sq_sum == 51840  # CORRECTED: |W(E6)| = 51840

    kernel_dim = 2195
    steinberg = 243
    residual = kernel_dim - steinberg  # 1952

    # Decompositions of kernel_dim
    decomps_2195 = find_decomp(kernel_dim, WE6_IRREP_DIMS, max_terms=6)
    # Decompositions of residual 1952
    decomps_1952 = find_decomp(residual, WE6_IRREP_DIMS, max_terms=6)

    result = {
        'timestamp': datetime.utcnow().isoformat()+'Z',
        'schema': 'w33.pass1170.meataxe_kernel_plan.v1',
        'status': 'PASS',
        'we6_order_corrected': 51840,
        'we6_sq_sum_check': we6_sq_sum == 51840,
        'we6_irrep_dim_sum': we6_sum,
        'kernel_dim': kernel_dim,
        'steinberg_packet': steinberg,
        'residual': residual,
        'meataxe_plan': {
            'method': 'MeatAxe over GF(7)',
            'good_prime': 7,
            'reason': '7 does not divide |W(E6)|=51840, so all W(E6) irreps are abs. irreducible over GF(7)',
            'generators': '6 simple reflections of W(E6) acting on the 2195-dim kernel',
            'expected_output': 'Composition factors = W(E6) irreps in characteristic 0',
        },
        'top_decompositions_2195': decomps_2195[:10],
        'top_decompositions_1952': decomps_1952[:10],
        'key_candidate_2195': '243 (Steinberg) + 1952 (residual)',
        'key_candidate_1952': 'To be determined by MeatAxe; arithmetic candidates include 80+81+... combinations',
        'so10_connection': 'rank(cubic_map)=45=dim(so(10)), suggesting D5 sub-diagram of E6 controls the image',
    }
    out = Path('data/MEATAXE_KERNEL_PLAN_2026_07_27.json')
    out.parent.mkdir(exist_ok=True)
    out.write_text(json.dumps(result, indent=2))
    print(f'PASS 1170: |W(E6)|=51840, sum_sq={we6_sq_sum}, we6_dim_sum={we6_sum}')
    print(f'  Top decomp of 2195: {decomps_2195[:3]}')
    print(f'  Top decomp of 1952: {decomps_1952[:3]}')
    return result

if __name__ == '__main__':
    main()
