"""Exact W33 matching-cochain CSS codes with distances 3 through 8.
Each selected family is generated by 80 eight-link Wilson stabilizers,
plus 79 independent four-link Gauss checks. One logical ternary qutrit.
"""
import json,sys,numpy as np
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1];sys.path.insert(0,str(ROOT/'analysis'))
from w33_20261009_toe_integral_clique_levi_bridge import chain
from w33_20261009_round18_chirality_plaquette_audit import cycles_touching
from w33_pass1081_1086_core import rank_mod
OUT=ROOT/'data/w33_20261009_toe26_css_matching_family.json'
MATCHES={3:[0,4,8],4:[0,4,8,12],5:[0,93,153,44,38],
 6:[82,65,122,90,149,60],7:[128,6,34,37,156,144,143],
 8:[45,135,76,157,55,20,128,123]}
def wilson():
 _,_,_,_,_,_,flags,_,_,_,D,M,R=chain()
 ed=[(p,40+l) for p,l in flags];lookup={edge:i for i,edge in enumerate(ed)}
 rings=set()
 for j in range(160):rings.update(cycles_touching(ed,j))
 rings=sorted(rings); assert len(rings)==1620
 C=np.zeros((1620,160),dtype=np.int8)
 for i,ring in enumerate(rings):
  for a,b in zip(ring,ring[1:]+ring[:1]):
   C[i,lookup[(min(a,b),max(a,b))]]=1 if a<b else -1
 assert np.all((D@C.T)%3==0) and rank_mod(C,3)==81
 return ed,D,C
def selected_basis(A,p=3):
 piv={};out=[]
 for ri,row in enumerate(A):
  z=row.astype(np.int16)%p
  for col,u in sorted(piv.items()):
   if z[col]:z=(z-z[col]*u)%p
  nz=np.flatnonzero(z)
  if len(nz):
   j=int(nz[0]);z=z*pow(int(z[j]),-1,p)%p
   piv[j]=z;out.append(ri)
 return out
def run():
 ed,D,C=wilson();cases={}
 for r,F in MATCHES.items():
  endpoints=[x for j in F for x in ed[j]]
  assert len(F)==r and len(set(endpoints))==2*r
  f=np.zeros(160,dtype=np.int8);f[F]=1
  pair=(C.astype(np.int16)@f)%3
  mask=pair==0;S=C[mask]
  rank=rank_mod(S,3);gens=selected_basis(S)
  assert rank==len(gens)==80
  # An eight-cycle not included is a weight-eight nontrivial Z logical.
  witness=int(np.flatnonzero(~mask)[0])
  assert pair[witness] and np.count_nonzero(C[witness])==8
  # All weight<=2 X errors are detected: distinct normalized column syndromes.
  normalized=[]
  for vec in (S.astype(np.int16)%3).T:
   nz=next(int(a) for a in vec if a)
   normalized.append((vec if nz==1 else 2*vec%3).tobytes())
  assert len(set(normalized))==160
  cases[str(r)]=dict(matching_edges=F,selected_eight_cycles=int(mask.sum()),
   Wilson_rank=rank,independent_weight_eight_checks=len(gens),
   code_parameters=f'[[160,1,{r}]]_3',
   X_distance=r,Z_distance=8,overall_distance=r,
   local_Z_logical_eightcycle_index=witness,
   all_weight_one_two_X_detected=True)
  print('W33 MATCHING',r,'loops',mask.sum(),'d_X',r,'d_Z',8,flush=True)
 out=dict(status='PASS',n_physical_qutrits=160,rank_Gauss_X=79,
  all_native_wilson_eightcycle_rank=81,
  matching_css_codes=cases,highest_verified_code='[[160,1,8]]_3',
  proof_of_X_distance='Let f be supported on r pairwise disjoint edges, 3<=r<=8. Each nontrivial logical X has cochain f+D^T phi (or twice it) for a ternary potential phi, since the selected Wilson rows span exactly the 80D hyperplane ker(f) within 81D cycle space. Write T for the set of edges across unequal phi labels. If |T|>=16, Hamming wt(f+D^T phi)>=|T|-r>=r. If |T|<16, spectral expansion with Levi degree4 and nontrivial adjacency eigenvalue sqrt6 forces each phi color class size <=10 or >=70. One class has >=70 vertices. Let S be the other <=10. Girth8 forces an induced subgraph on <=10 vertices to have <=1 independent cycle, giving |boundary S|>=16 whenever |S|>=7. Therefore |S|<=6, and the induced subgraph is a forest, so |boundary S|>=2|S|+2. Because f is supported on a matching, at most |S| of its edges can cross phi color classes. Hence wt(f+D^T phi)>=r+|T|-2|S|>=r+2. Constant phi has weight exactly r. Thus d_X=r.',
  proof_of_Z_distance='Nontrivial Z logicals lie in ker(D) and have weight at least girth8. Since all native 8cycle rows span rank81 but the selected hyperplane has rank80, an omitted native 8cycle pairs nontrivially with f, has weight8, and is a Z logical. Thus d_Z=8. Hence d=min(r,8)=r. The r=8 code saturates the upper bound imposed by length-eight cycles.',
  confidence='Analytic combinatorial bound plus exact finite-field ranks and 160 syndrome-column checks. An independent 400-variable ternary minimum-weight ILP checks the coset optima in companion producer.',
  hardware_boundary='Exact ideal CSS codes, not a measured threshold, scalable q-family, practical decoder, or immunity to correlated circuit faults. The matching picks edges and breaks full PSp symmetry.')
 OUT.write_text(json.dumps(out,indent=2)+'\n')
 return out
if __name__=='__main__':run()
