#!/usr/bin/env python3
"""Pass5358: characteristic-2 nonsplitting firewall for the PSL2 pair-fiber bridge.

Pass5356 proves in characteristic zero that the unordered-pair module is
Sym^2(St), using C[P^1(q)] = 1 + St. This cancellation cannot be reduced mod 2.

For odd q, n=q+1 is even. Put V=F2[P^1(q)], j=sum_x e_x, and let eps:V->F2
be augmentation. Transitivity makes Hom_G(V,1) one-dimensional, generated by
eps. But eps(j)=n=0 in F2. Hence every G-map V->1 kills the invariant vector j,
so no G-equivariant projection V-><j> exists. Therefore <j> is not a direct
summand of V.

This is an exact elementary reason why the characteristic-zero cancellation in
Pass5356 does not prove the all-odd binary footprint rank theorem. The diagonal
and off-diagonal coordinate subspaces of Sym^2(V) remain permutation-stable,
but there is no justified replacement of V by 1+St in characteristic two.
"""
from __future__ import annotations
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
OUT=ROOT/'data/PART_W33_PASS5358_CHAR2_PROJECTIVE_LINE_NONSPLITTING_FIREWALL.json'

def row(q):
    n=q+1
    assert q%2==1 and n%2==0
    return {'q':q,'projective_line_degree':n,'augmentation_of_all_one_mod2':n%2,
      'invariant_functional_dimension_for_transitive_action':1,'trivial_projection_possible':False}

def main():
    rows={str(q):row(q) for q in (3,5,7,9,11,13,17,19,25,27)}
    out={'pass':5358,'status':'THEOREM_CHAR2_PROJECTIVE_LINE_TRIVIAL_SUBMODULE_DOES_NOT_SPLIT',
      'domain':'odd prime powers q',
      'module':'V=F2[P^1(q)]',
      'proof':'The invariant vector j lies in ker(eps) because q+1 is even. By transitivity Hom_G(V,1) is generated by augmentation eps, so every G-map to the trivial module kills j. Thus no equivariant projection onto <j> exists.',
      'consequence':'The characteristic-zero identity C[pairs] ~= Sym^2(St) cannot be obtained in characteristic 2 by reducing the splitting C[P^1]=1+St.',
      'relation_to_footprint':'This blocks a tempting but invalid shortcut from the local pair-fiber theorem to rank_2(F)=q(q^2+1)/2.',
      'checks':rows,
      'boundary':'This is a nonsplitting theorem and a proof firewall, not a determination of the full modular pair-module lattice and not a proof or disproof of the all-odd footprint rank conjecture.'}
    OUT.write_text(json.dumps(out,indent=2,sort_keys=True)+'\n');print(json.dumps(out,indent=2,sort_keys=True))
if __name__=='__main__':main()
