#!/usr/bin/env python3
"""Pass10397-10404: fixing the internal F4 scalar turns canonical V2 into the Suzuki 1782 G-set.

Pass10389-10396 proves that the A4 factor in

  Stab_Co1(V2) = G2(4) x A4

acts on V2 through A4/V4=C3=F4^x.  Choose a nontrivial scalar s of order 3.
Inside the stabilizer,

  C_Stab(V2)(s) = G2(4) x C3.

Compare its order with the four Co1 order-3 class centralizers from ATLAS.  Only class
3A can contain this subgroup.  Moreover C_Co1(3A) has order 1,345,036,492,800, exactly
the order of 3.Suz.  Therefore s is the fixed-point-free complex-Leech scalar class and

  C_Co1(s) ~= 3.Suz.

The orbit of V2 under this centralizer has size

  [3.Suz : G2(4) x C3] = 1782.

Since the central C3 is generated by s, quotienting it gives precisely

  Suz / G2(4),

the canonical 1782-point Suzuki graph G-set.  Thus the Suzuki vertices admit an objectwise
reading: they are the conjugates of canonical V2 inside Co1 that are fixed by one chosen
internal F4 scalar s.
"""
from __future__ import annotations
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
OUT=ROOT/'data/PART_W33_PASS10397_10404_SCALAR3A_SUZUKI1782_V2_ORBIT.json'

def main():
    g2=251_596_800;c3=3;local=g2*c3
    co1_order3={'3A':1_345_036_492_800,'3B':58_786_560,'3C':12_597_120,'3D':544_320}
    candidates=[k for k,v in co1_order3.items() if v>=local and v%local==0]
    assert candidates==['3A']
    suz=448_345_497_600
    assert 3*suz==co1_order3['3A']
    idx=co1_order3['3A']//local;assert idx==1782
    # Known Suzuki graph parameters / subgroup index.
    assert suz//g2==1782
    assert 1782*416//2==370_656
    out={
      'schema':'w33.pass10397_10404.scalar3a_suzuki1782_v2_orbit.v1','status':'PASS','passes':'10397-10404',
      'input':{'Stab_Co1_V2':'G2(4) x A4','internal_scalar':'s in A4/V4 = C3 = F4^x','source':'Pass10389-10396'},
      'centralizer_inside_V2_stabilizer':{'C_Stab_s':'G2(4) x C3','order':local},
      'Co1_order3_class_gate':{'ATLAS_centralizer_orders':co1_order3,'only_possible_class':'3A'},
      'complex_Leech_scalar':{'class':'3A','C_Co1_s':'3.Suz','order':co1_order3['3A'],'Suz_order':suz},
      'V2_orbit':{'stabilizer_in_3Suz':'G2(4) x C3','size':idx,'central_C3_quotient':'Suz/G2(4)','identified_G_set':'1782 Suzuki-graph vertices'},
      'Suzuki_graph':{'parameters':[1782,416,100,96],'edges':370656},
      'theorem':'Fix a nontrivial internal F4 scalar s on canonical V2. It is necessarily Co1 class 3A, with centralizer 3.Suz. The 3.Suz orbit of V2 has exactly 1782 elements, and after quotienting the central scalar C3 it is the homogeneous space Suz/G2(4), i.e. the canonical Suzuki-graph vertex G-set. Thus Suzuki vertices are objectwise scalar-compatible conjugates of V2.',
      'boundary':'Uses the exact orbit-7 stabilizer from Pass10345/10389 and the ATLAS Co1 order-3 centralizer table plus the standard C_Co1(3A)=3.Suz identification. It identifies the vertex G-set; adjacency is the standard rank-3 Suz/G2(4) orbital relation already used elsewhere in the repo.'}
    OUT.write_text(json.dumps(out,indent=2,sort_keys=True)+'\n')
    print(json.dumps({'status':'PASS','class':'3A','centralizer':'3.Suz','V2_orbit':1782}))
    return 0
if __name__=='__main__':raise SystemExit(main())
