#!/usr/bin/env python3
"""Pass10057-10064: the three orientation C2 characters are exactly compatible.

Three index-two characters were independently found:
  * Golay/W33 line orientation: S4 -> S4/A4 = C2 (sign),
  * G2 clock orientation: C12 -> C12/C6 = C2,
  * Singer/Frobenius orientation: C12 -> C12/C6 = C2.

The compatibility question is whether the C12 clock can act on the four W33
line channels so that its orientation is exactly the Golay sign.  Yes.

There is a canonical quotient C12 -> C4.  Embed C4 in S4 as a 4-cycle.  A
4-cycle is odd, so sign of the k-th power is (-1)^k.  Pulling sign back to C12
has kernel the even powers, exactly C6.  Hence all three C2 characters are one
and the same abstract character under this clock-to-four-channel map.

This proves character compatibility, not an objectwise V2/G2/Niemeier
transporter.  The latter remains the geometric selector problem.
"""
from __future__ import annotations
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
OUT=ROOT/'data/PART_W33_PASS10057_10064_ORIENTATION_CHARACTER_COMPATIBILITY.json'

def compose(p,q): return tuple(p[q[i]] for i in range(len(p)))
def power(p,n):
    r=tuple(range(len(p)))
    for _ in range(n):r=compose(r,p)
    return r
def parity(p):
    inv=sum(1 for i in range(len(p)) for j in range(i+1,len(p)) if p[i]>p[j])
    return inv%2

def main():
    cycle=(1,2,3,0) # (0 1 2 3)
    signs=[parity(power(cycle,k%4)) for k in range(12)]
    clock=[k%2 for k in range(12)]
    assert signs==clock
    kernel=[k for k in range(12) if signs[k]==0]
    assert kernel==[0,2,4,6,8,10]
    # quotient C12 -> C4 has kernel C3={0,4,8}; sign preimage kernel C6.
    qker=[k for k in range(12) if k%4==0]
    assert qker==[0,4,8]
    out={
      'schema':'w33.pass10057_10064.orientation_character_compatibility.v1','status':'PASS','passes':'10057-10064',
      'three_characters':{
        'Golay_W33':'sign: S4 -> S4/A4 = C2',
        'G2_clock':'C12 -> C12/C6 = C2',
        'Singer_Frobenius':'C12 -> C12/C6 = C2'},
      'compatibility_map':{
        'clock_to_channels':'C12 -> C4, generator maps to generator',
        'C4_embedding':'C4 < S4 generated by a 4-cycle on the four W33 line channels',
        'pullback':'sign((1234)^k)=(-1)^k',
        'kernel_in_C12':'C6 = even powers',
        'quotient_kernel':'C3 = <clock^4>'},
      'verified_sign_sequence':signs,
      'theorem':'The Golay A4<S4 orientation, the G2 outer-extension orientation, and the Singer Frobenius-parity orientation are exactly the same C2 character after the canonical clock quotient C12->C4 and a 4-cycle action on the four W33 line channels. Character-level compatibility is therefore proved.',
      'uniqueness':'All C4 subgroups generated by 4-cycles in S4 are conjugate, so this compatibility is unique up to relabelling the four channels.',
      'boundary':'No objectwise symplectic/Leech transporter is constructed here. This proves the three binary characters can be identified without contradiction and specifies the required channel action.'}
    OUT.write_text(json.dumps(out,indent=2,sort_keys=True)+'\n')
    print(json.dumps({'status':'PASS','kernel':'C6','channel_action':'4-cycle','characters_agree':True}))
    return 0
if __name__=='__main__':raise SystemExit(main())
