"""Pass 11843: the commutant in E8 of the finite Lorentz group through the W(E6) (Tits) embedding.

Pass 11837 found that through the Weil embedding Sp(4,3) -> SU(9) -> Aut(E8) the finite Lorentz group SL(2,9) commutes
only with u(1)_P.  Here the same abstract group acts through the other classical route, PSp(4,3) = W(E6)' acting on
E8 > E6 x A2 by Tits lifts of Weyl group elements.  Under PSp(4,3) = W(E6)', a Kramers reversal is a root pair +-alpha
of E6 (Pass 11210: the 36 reflections), and its finite Lorentz group (image A6, Pass 11832) is W(A5)', the derived
Weyl group of the A5 of roots orthogonal to alpha.

E8 is built in a Chevalley basis with the Frenkel-Kac sign cocycle (Jacobi verified); n_beta = exp(ad E) exp(-ad F)
exp(ad E).  The finite Lorentz group is lifted as the group generated by the even Tits words n_b n_c (b, c simple roots
of A5); the commutant is the common fixed subalgebra, analysed for dimension, centre, derived algebra and rank.
"""

from __future__ import annotations

import itertools
import json
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "data" / "w33_pass11843_e8_tits_lorentz_commutant.json"

# E8 Cartan matrix, Bourbaki labels 1..8 -> indices 0..7: chain 1-3-4-5-6-7-8 and 2-4
EDGES = [(0, 2), (2, 3), (3, 4), (4, 5), (5, 6), (6, 7), (1, 3)]
C = 2 * np.eye(8, dtype=int)
for a, b in EDGES:
    C[a, b] = C[b, a] = -1


def ip(a, b):
    return int(np.asarray(a) @ C @ np.asarray(b))


def roots():
    simple = [tuple(int(i == j) for i in range(8)) for j in range(8)]
    pos = set(simple)
    frontier = list(simple)
    while frontier:
        new = []
        for b in frontier:
            for i in range(8):
                e = np.array([int(k == i) for k in range(8)])
                q = 0
                x = np.array(b) - e
                while tuple(x) in pos:
                    q += 1
                    x = x - e
                p = q - ip(b, e)
                if p > 0:
                    nb = tuple(int(t) for t in np.array(b) + e)
                    if nb not in pos:
                        pos.add(nb)
                        new.append(nb)
        frontier = new
    pos = sorted(pos)
    assert len(pos) == 120
    return pos + [tuple(-t for t in v) for v in pos]


ROOTS = roots()
RI = {v: i for i, v in enumerate(ROOTS)}
N = 8 + 240
M = np.triu(C % 2, 1) + np.eye(8, dtype=int)


def eps(a, b):
    return -1 if (np.array(a) @ M @ np.array(b)) % 2 else 1


SIGN = -1  # [e_a, e_-a] = SIGN * eps(a,-a) h_a ; fixed by the Jacobi check


def bracket_basis():
    """structure constants: T[i, j] = [b_i, b_j] as a dense vector."""
    T = np.zeros((N, N, N))
    for i, a in enumerate(ROOTS):
        ia = 8 + i
        ca = C @ np.array(a)
        for k in range(8):  # [h_k, e_a] = (a, a_k) e_a
            T[k, ia, ia] = ca[k]
            T[ia, k, ia] = -ca[k]
        for j, b in enumerate(ROOTS):
            ib = 8 + j
            s = tuple(x + y for x, y in zip(a, b))
            if s in RI:
                T[ia, ib, 8 + RI[s]] = eps(a, b)
            elif all(x == 0 for x in s):
                T[ia, ib, :8] = SIGN * eps(a, b) * np.array(a)
    return T


def br(T, x, y):
    return np.einsum("i,j,ijk->k", x, y, T)


def jacobi(T, rng):
    worst = 0.0
    for _ in range(5):
        x, y, z = rng.normal(size=(3, N))
        j = br(T, br(T, x, y), z) + br(T, br(T, y, z), x) + br(T, br(T, z, x), y)
        worst = max(worst, float(abs(j).max()))
    return worst


def ad(T, x):
    return np.einsum("i,ijk->kj", x, T)


def vec_root(a, coef=1.0):
    v = np.zeros(N)
    v[8 + RI[tuple(a)]] = coef
    return v


def expm_nil(A):
    out, term = np.eye(N), np.eye(N)
    for k in range(1, 6):
        term = term @ A / k
        out = out + term
    return out


def tits(T, b):
    b = tuple(b)
    nb = tuple(-x for x in b)
    E = vec_root(b)
    F = vec_root(nb, SIGN * eps(b, nb))
    h = br(T, E, F)
    assert np.allclose(br(T, h, E), 2 * E)
    adE, adF = ad(T, E), ad(T, F)
    return expm_nil(adE) @ expm_nil(-adF) @ expm_nil(adE)


def is_automorphism(T, g, rng):
    x, y = rng.normal(size=(2, N))
    return float(abs(g @ br(T, x, y) - br(T, g @ x, g @ y)).max())


def simple_system(sub, rng):
    f = rng.normal(size=8)
    pos = [r for r in sub if np.array(r) @ f > 0]
    S = set(pos)
    simple = [r for r in pos if not any(tuple(np.array(r) - np.array(s)) in S for s in pos if s != r)]
    return simple


def fixed_subalgebra(gens):
    A = np.vstack([g - np.eye(N) for g in gens])
    _, s, vh = np.linalg.svd(A)
    null = vh[np.sum(s > 1e-8):].T
    return null


def analyse(T, B, rng):
    n = B.shape[1]
    if n == 0:
        return dict(dim=0)
    pinv = np.linalg.pinv(B)
    st = np.zeros((n, n, n))
    clos = 0.0
    for i in range(n):
        for j in range(n):
            v = br(T, B[:, i], B[:, j])
            c = pinv @ v
            clos = max(clos, float(abs(B @ c - v).max()))
            st[i, j] = c
    adm = np.transpose(st, (0, 2, 1))
    kill = np.einsum("ikl,jlk->ij", adm, adm)
    der = np.linalg.matrix_rank(st.reshape(n * n, n), tol=1e-7)
    centre = n - np.linalg.matrix_rank(np.concatenate(list(adm), axis=0), tol=1e-7)
    x = np.tensordot(rng.normal(size=n), adm, axes=1)
    rank = n - np.linalg.matrix_rank(x, tol=1e-7)
    # Killing form of E8 restricted: signature tells compact structure only for real forms; record eigenvalue signs
    kw = np.linalg.eigvalsh((kill + kill.T) / 2)
    return dict(dim=n, closure_error=clos, derived_dim=int(der), centre_dim=int(centre), rank=int(rank),
                killing_rank=int(np.sum(abs(kw) > 1e-6)))


def main():
    rng = np.random.default_rng(11843)
    global SIGN
    T = bracket_basis()
    jac = jacobi(T, rng)
    if jac > 1e-8:
        SIGN = 1
        T = bracket_basis()
        jac = jacobi(T, rng)
    assert jac < 1e-8, jac
    res = {"pass_id": 11843, "e8": dict(dim=N, roots=len(ROOTS), jacobi_max=jac, sign=SIGN)}
    # A2 x E6: gamma1, gamma2 with (g1, g2) = -1
    g1 = ROOTS[0]
    g2 = next(r for r in ROOTS if ip(g1, r) == -1)
    E6 = [r for r in ROOTS if ip(r, g1) == 0 and ip(r, g2) == 0]
    A2 = [r for r in ROOTS if all(ip(r, e) == 0 for e in E6)]
    alpha = E6[0]
    A5 = [r for r in E6 if ip(r, alpha) == 0]
    A1 = [r for r in E6 if all(ip(r, e) == 0 for e in A5)]
    res["subsystems"] = dict(E6=len(E6), A2=len(A2), A5=len(A5), A1=len(A1))
    assert (len(E6), len(A2), len(A5), len(A1)) == (72, 6, 30, 2)
    s5 = simple_system(A5, rng)
    s6 = simple_system(E6, rng)
    assert len(s5) == 5 and len(s6) == 6
    n5 = [tits(T, b) for b in s5]
    n6 = [tits(T, b) for b in s6]
    res["tits_automorphism_max_error"] = max(is_automorphism(T, g, rng) for g in n5 + n6)
    # Weyl action check on the Cartan: n_b restricted to h is the reflection s_b
    out = {}
    lorentz = [a @ b for a, b in itertools.permutations(n5, 2)]
    out["lorentz_W(A5)'_even_tits_words"] = analyse(T, fixed_subalgebra(lorentz), rng)
    out["with_parity_W(A5)_all_tits"] = analyse(T, fixed_subalgebra(n5), rng)
    out["with_torus_2_elements"] = analyse(T, fixed_subalgebra(lorentz + [g @ g for g in n5]), rng)
    out["control_W(E6)'_even_words"] = analyse(T, fixed_subalgebra([a @ b for a, b in itertools.permutations(n6, 2)]), rng)
    # which named pieces are inside the Lorentz commutant: su(3) = A2 part, su(2)_alpha = A1 part
    Bl = fixed_subalgebra(lorentz)
    Pl = Bl @ np.linalg.pinv(Bl)

    def contains(rootset):
        vs = [vec_root(r) for r in rootset]
        for r in rootset:
            h = np.zeros(N)
            h[:8] = r
            vs.append(h)
        return bool(all(np.allclose(Pl @ v, v, atol=1e-8) for v in vs))
    out["contains_su3_A2"] = contains(A2)
    out["contains_su2_alpha"] = contains(A1)
    res["commutants"] = out
    for k, v in out.items():
        print(k, v, flush=True)
    json.dump(res, open(OUT, "w"), indent=1, default=str)
    print(json.dumps({k: v for k, v in res.items() if k != "commutants"}))


if __name__ == "__main__":
    main()
