#!/usr/bin/env python3
"""Pass 4339 -- synthesise all four machines of the design space.

Pass 4321 priced the 2x2 design space in mixing, growth, localisation and entropy
production, but only machines A and C had gate counts (Pass 4279).  A design table with two
of four rows empty is not a design table.

Verilog is generated FROM THE OPCODE MATRICES, so the netlist cannot disagree with the
algebra, and every machine is simulated against the group computation before its cell count
is believed -- Pass 4290 was added precisely because a 1.95x ratio had been quoted from a
module that was never run.

    py -3 analysis/w33_pass4339_synthesise_all_four_machines.py
"""

from __future__ import annotations

import json
import shutil
import subprocess
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "build" / "w33_rtl"

ID4 = tuple(tuple(1 if i == j else 0 for j in range(4)) for i in range(4))
LIN = {"F_p": ((0, 2, 0, 0), (1, 0, 0, 0), (0, 0, 1, 0), (0, 0, 0, 1)),
       "F_f": ((1, 0, 0, 0), (0, 1, 0, 0), (0, 0, 0, 2), (0, 0, 1, 0)),
       "CX_pf": ((1, 0, 0, 0), (0, 1, 0, 2), (1, 0, 1, 0), (0, 0, 0, 1)),
       "CX_fp": ((1, 0, 1, 0), (0, 1, 0, 0), (0, 0, 1, 0), (0, 2, 0, 1))}


def mv(A, v):
    return tuple(sum(A[i][k] * v[k] for k in range(4)) % 3 for i in range(4))


def mm(a, b):
    return tuple(tuple(sum(a[i][k] * b[k][j] for k in range(4)) % 3 for j in range(4))
                 for i in range(4))


def minv(M):
    a = [list(M[i]) + [1 if j == i else 0 for j in range(4)] for i in range(4)]
    r = 0
    for c in range(4):
        p = next(i for i in range(r, 4) if a[i][c] % 3)
        a[r], a[p] = a[p], a[r]
        iv = 1 if a[r][c] % 3 == 1 else 2
        a[r] = [(x * iv) % 3 for x in a[r]]
        for i in range(4):
            if i != r and a[i][c] % 3:
                f = a[i][c] % 3
                a[i] = [(a[i][k] - f * a[r][k]) % 3 for k in range(8)]
        r += 1
    return tuple(tuple(a[i][4:]) for i in range(4))


def inv_op(g):
    M, t = g
    Mi = minv(M)
    return (Mi, tuple((-mv(Mi, t)[i]) % 3 for i in range(4)))


def close(gs):
    out, seen = [], set()
    for g in gs:
        for h in (g, inv_op(g)):
            if h not in seen:
                seen.add(h)
                out.append(h)
    return out


Z = {i: (ID4, tuple(1 if j == i else 0 for j in range(4))) for i in range(4)}
BIASED = [(LIN["F_p"], (0, 0, 0, 0)), (LIN["CX_pf"], (0, 0, 0, 0)),
          (LIN["CX_fp"], (0, 0, 0, 0)), Z[0]]
SYMMETRIC = BIASED + [(LIN["F_f"], (0, 0, 0, 0)), Z[2]]
MACHINES = {
    "w33_machine_a": ("A biased, irreversible", BIASED),
    "w33_machine_b": ("B symmetric, irreversible", SYMMETRIC),
    "w33_machine_c": ("C biased, reversible", close(BIASED)),
    "w33_machine_d": ("D symmetric, reversible", close(SYMMETRIC)),
}


def emit(ops, module):
    w = max(1, (len(ops) - 1).bit_length())
    L = [f"// Generated by analysis/w33_pass4339_synthesise_all_four_machines.py",
         f"// {module}: {len(ops)} opcodes over GF(3)^4, two bits per trit.",
         f"module {module} (",
         "  input  wire        clk,",
         "  input  wire        rst,",
         f"  input  wire [{w - 1}:0] op,",
         "  output wire [7:0]  frame",
         ");"]
    L += [f"  reg [1:0] x{i};" for i in range(4)]
    L += ["  assign frame = {x3, x2, x1, x0};", "",
          "  function [1:0] a3;",
          "    input [1:0] u; input [1:0] v;",
          "    reg [2:0] s;",
          "    begin s = u + v; a3 = (s >= 3) ? (s - 3) : s[1:0]; end",
          "  endfunction", "",
          "  function [1:0] m3;",
          "    input [1:0] c; input [1:0] u;",
          "    begin",
          "      case (c)",
          "        2'd0: m3 = 2'd0;",
          "        2'd1: m3 = u;",
          "        default: m3 = (u == 2'd0) ? 2'd0 : ((u == 2'd1) ? 2'd2 : 2'd1);",
          "      endcase",
          "    end",
          "  endfunction", "",
          "  always @(posedge clk) begin",
          "    if (rst) begin x0 <= 2'd0; x1 <= 2'd0; x2 <= 2'd0; x3 <= 2'd0; end",
          "    else begin",
          "      case (op)"]
    for k, (M, t) in enumerate(ops):
        L.append(f"        {w}'d{k}: begin")
        for i in range(4):
            terms = [f"m3(2'd{M[i][j]}, x{j})" for j in range(4) if M[i][j]]
            e = terms[0] if terms else "2'd0"
            for x in terms[1:]:
                e = f"a3({e}, {x})"
            if t[i]:
                e = f"a3({e}, 2'd{t[i]})"
            L.append(f"          x{i} <= {e};")
        L.append("        end")
    L += ["        default: begin x0 <= x0; x1 <= x1; x2 <= x2; x3 <= x3; end",
          "      endcase", "    end", "  end", "endmodule"]
    return "\n".join(L) + "\n"


def parse_stat(stdout, stderr=""):
    stats, per = {}, {}
    for line in (stdout or "").splitlines():
        parts = line.strip().split()
        if len(parts) == 2 and parts[0].isdigit():
            n, what = int(parts[0]), parts[1]
            if what == "cells":
                stats["cells"] = n
            elif what == "wires":
                stats["wires"] = n
            elif what.startswith("$_"):
                per[what] = n
    stats["by_cell"] = per
    if "cells" not in stats:
        stats["error"] = ((stderr or "") + (stdout or ""))[-300:]
    return stats


def wsl_run(cmd, timeout=300):
    return subprocess.run(["wsl", "-e", "bash", "-lc", cmd],
                          capture_output=True, text=True, timeout=timeout)


def main() -> int:
    print("=" * 78)
    print("Pass 4339 -- all four machines, synthesised and simulated")
    print("=" * 78)
    OUT.mkdir(parents=True, exist_ok=True)
    rng = np.random.default_rng(4339)
    results = {}

    wp = subprocess.run(["wsl", "wslpath", "-a", str(OUT)],
                        capture_output=True, text=True).stdout.strip()

    for mod, (label, ops) in MACHINES.items():
        v = OUT / f"{mod}.v"
        v.write_text(emit(ops, mod), encoding="utf-8")
        w = max(1, (len(ops) - 1).bit_length())

        # --- reference trajectory from the group itself
        seq = [int(x) for x in rng.integers(0, len(ops), size=50)]
        x = (0, 0, 0, 0)
        for s in seq:
            M, t = ops[s]
            x = tuple((mv(M, x)[k] + t[k]) % 3 for k in range(4))
        (OUT / f"{mod}_seq.txt").write_text(
            "".join(format(s, f"0{w}b") + "\n" for s in seq), encoding="utf-8")
        tb = f"""`timescale 1ns/1ps
module tb_{mod};
  reg clk=0, rst=1; reg [{w - 1}:0] op=0; wire [7:0] frame;
  {mod} dut(.clk(clk), .rst(rst), .op(op), .frame(frame));
  reg [{w - 1}:0] seq [0:{len(seq) - 1}];
  integer k;
  always #5 clk = ~clk;
  initial begin
    $readmemb("{mod}_seq.txt", seq);
    @(negedge clk); rst=0;
    for (k=0; k<{len(seq)}; k=k+1) begin op = seq[k]; @(negedge clk); end
    $display("FRAME (%0d, %0d, %0d, %0d)",
             frame[1:0], frame[3:2], frame[5:4], frame[7:6]);
    $finish;
  end
endmodule
"""
        (OUT / f"tb_{mod}.v").write_text(tb, encoding="utf-8")

        sim = wsl_run(
            f'cp "{wp}"/{mod}.v "{wp}"/tb_{mod}.v "{wp}"/{mod}_seq.txt /tmp/ && '
            f'cd /tmp && ~/.local/w33-hardware/bin/iverilog -o s_{mod} {mod}.v '
            f'tb_{mod}.v && ./s_{mod}')
        want = f"({x[0]}, {x[1]}, {x[2]}, {x[3]})"
        ok = want in (sim.stdout or "")

        script = (f"read_verilog /tmp/{mod}.v; hierarchy -top {mod}; proc; opt; fsm; "
                  f"opt; techmap; opt; abc -g AND,OR,XOR,NAND,NOR,XNOR,MUX; opt; stat")
        syn = wsl_run(f"~/.local/w33-hardware/bin/yosys -p '{script}'")
        st = parse_stat(syn.stdout, syn.stderr)
        results[mod] = {"label": label, "opcodes": len(ops), "op_bits": w,
                        "verified": bool(ok), "expected_frame": list(x),
                        **{k: v2 for k, v2 in st.items() if k != "by_cell"}}
        print(f"  {label:28s} ops {len(ops):2d}  verified {str(ok):5s}  "
              f"cells {st.get('cells', '?'):>5}  wires {st.get('wires', '?'):>5}")

    print()
    good = [r for r in results.values() if r.get("verified") and "cells" in r]
    if len(good) == 4:
        a = results["w33_machine_a"]["cells"]
        print(f"  {'machine':28s} {'ops':>4s} {'cells':>6s} {'vs A':>6s}")
        for mod, (label, _) in MACHINES.items():
            r = results[mod]
            print(f"  {label:28s} {r['opcodes']:4d} {r['cells']:6d} "
                  f"{r['cells'] / a:6.2f}x")
        b = results["w33_machine_b"]["cells"]
        c = results["w33_machine_c"]["cells"]
        d = results["w33_machine_d"]["cells"]
        print(f"""
  THE DESIGN TABLE IS COMPLETE, and the two axes cost differently.  Fixing the p/f bias
  (A to B) costs {b / a:.2f}x; fixing the arrow of time (A to C) costs {c / a:.2f}x; fixing both
  (A to D) costs {d / a:.2f}x.

  {'The two prices are close to multiplicative' if abs(d / a - (b / a) * (c / a)) < 0.35 else 'The two prices are NOT multiplicative'}: (B/A)x(C/A) = {(b / a) * (c / a):.2f} against the measured
  D/A = {d / a:.2f}.  That matters for a designer, because it says whether the two fixes share
  logic or pay separately -- and Pass 4314 already showed the DEFECTS are independent, which
  does not by itself imply the REMEDIES are.

  Every row was simulated against the group computation before its cell count was recorded.
  Pass 4290 exists because a 1.95x ratio was once quoted from a module that had never been
  run, and that is not a mistake worth making twice.""")
    else:
        print("  not all four verified+synthesised; refusing to report a ratio table")
        for mod, r in results.items():
            if not r.get("verified") or "cells" not in r:
                print(f"    {mod}: verified={r.get('verified')} "
                      f"cells={r.get('cells')} {str(r.get('error', ''))[:120]}")

    p = ROOT / "data" / "PART_W33_PASS4339_FOUR_MACHINES_SYNTHESISED.json"
    p.parent.mkdir(exist_ok=True)
    # Hash the ROUND-TRIPPED object, never the live dict (CLAUDE.md, Pass 2482).
    p.write_text(json.dumps(json.loads(json.dumps(results)), indent=2, sort_keys=True)
                 + "\n", encoding="utf-8")
    print(f"\nwrote {p.relative_to(ROOT).as_posix()}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
