#!/usr/bin/env python3
"""Exact W33 oriented-288 / binary-tetrahedral Clifford interior bridge.

The order-576 W33 minimum-vector stabilizer H has a unique index-two subgroup
H+ obtained by killing the C2 quotient of its S3 factor.  Geometrically this is
the oriented minimum-vector stabilizer; algebraically it is generated by H'
and the order-three elements of H.

Independently, the determinant-one single-qubit Clifford commutator C1' is the
binary tetrahedral group 2T ~= SL(2,3).  The local two-qubit group

    C1' tensor C1' ~= (2T x 2T) / diag(C2)

has order 288.  Its 2-core is the central product Q8 * Q8 = 2_+^{1+4}, and the
quotient by that 2-core is C3 x C3.

This certificate reconstructs both groups independently, builds an explicit
isomorphism through their characteristic extraspecial kernels, and checks all
288^2 products.  It then records the extension-class divergence above the
common interior: W33 adds an involutory factor exchange, whereas the standard
complex Clifford non-entangling lift adds a swap whose square is scalar phase.
"""
from __future__ import annotations

import itertools
import json
from collections import Counter, deque
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
ANALYSIS = Path(__file__).resolve().parent
if str(ANALYSIS) not in sys.path:
    sys.path.insert(0, str(ANALYSIS))

from w33_threeway_576_provenance_closure import (  # noqa: E402
    action_mats,
    center,
    compose,
    derived_subgroup,
    find_GL4_conjugator,
    generated_group,
    mapply,
    mcomp,
    minv,
    normal_form,
    pinv,
    porder,
    psp_minimum_stabilizer,
    quotient_E_coords,
    sha,
)

OUT = ROOT / "data" / "w33_oriented288_binary_tetrahedral_bridge.json"


def oriented_w33_288():
    H = psp_minimum_stabilizer()
    Hprime = derived_subgroup(H, 40)
    Hplus = generated_group(
        tuple(Hprime) + tuple(g for g in H if porder(g) == 3), 40
    )
    assert len(Hplus) == 288
    assert len(center(Hplus)) == 2
    assert len(derived_subgroup(Hplus, 40)) == 32
    return Hplus


# ---------------------------------------------------------------------------
# Binary tetrahedral central product (SL(2,3) x SL(2,3))/diag(-I,-I).

def det2(m):
    return (m[0] * m[3] - m[1] * m[2]) % 3


def mmul(a, b):
    return (
        (a[0] * b[0] + a[1] * b[2]) % 3,
        (a[0] * b[1] + a[1] * b[3]) % 3,
        (a[2] * b[0] + a[3] * b[2]) % 3,
        (a[2] * b[1] + a[3] * b[3]) % 3,
    )


def minv3(m):
    return (m[3], (-m[1]) % 3, (-m[2]) % 3, m[0])


def neg(m):
    return tuple((-x) % 3 for x in m)


SL23 = tuple(m for m in itertools.product(range(3), repeat=4) if det2(m) == 1)
I2 = (1, 0, 0, 1)


def canon_pair(a, b):
    return min((a, b), (neg(a), neg(b)))


CID = canon_pair(I2, I2)
CP = frozenset(canon_pair(a, b) for a in SL23 for b in SL23)


def cmul(x, y):
    return canon_pair(mmul(x[0], y[0]), mmul(x[1], y[1]))


def cinv(x):
    return canon_pair(minv3(x[0]), minv3(x[1]))


def corder(x):
    y = CID
    for n in range(1, 25):
        y = cmul(x, y)
        if y == CID:
            return n
    raise AssertionError("central-product order bound")


def cclosure(gens):
    group = {CID}
    queue = deque([CID])
    gens = tuple(gens)
    while queue:
        x = queue.popleft()
        for g in gens:
            y = cmul(g, x)
            if y not in group:
                group.add(y)
                queue.append(y)
    return group


def ccenter(group):
    return [g for g in group if all(cmul(g, h) == cmul(h, g) for h in group)]


def cderived(group):
    comms = set()
    for g in group:
        gi = cinv(g)
        for h in group:
            hi = cinv(h)
            comms.add(cmul(cmul(cmul(gi, hi), g), h))
    return cclosure(comms)


def cquotient_coords(E):
    Z = ccenter(E)
    assert len(Z) == 2
    z = next(x for x in Z if x != CID)
    cosets = []
    ci = {}
    for x in sorted(E, key=str):
        if x in ci:
            continue
        C = tuple(sorted((x, cmul(z, x)), key=str))
        k = len(cosets)
        cosets.append(C)
        for y in C:
            ci[y] = k
    reps = [C[0] for C in cosets]
    idc = ci[CID]
    add = [[ci[cmul(a, b)] for b in reps] for a in reps]
    coord = {idc: 0}
    basis = []
    for c in range(16):
        if c in coord:
            continue
        bit = 1 << len(basis)
        for d, v in list(coord.items()):
            coord[add[d][c]] = v | bit
        basis.append(c)
        if len(coord) == 16:
            break
    assert len(coord) == 16 and len(basis) == 4
    invcoord = {v: c for c, v in coord.items()}
    qform = {coord[c]: (0 if cmul(r, r) == CID else 1) for c, r in enumerate(reps)}
    return {
        "z": z,
        "cosets": cosets,
        "ci": ci,
        "reps": reps,
        "coord": coord,
        "invcoord": invcoord,
        "basis": basis,
        "q": qform,
    }


def caction_mats(group, Edata):
    breps = [Edata["reps"][c] for c in Edata["basis"]]
    mats = {}
    for g in group:
        gi = cinv(g)
        cols = []
        for r in breps:
            y = cmul(cmul(g, r), gi)
            cols.append(Edata["coord"][Edata["ci"][y]])
        mats[g] = tuple(cols)
    return mats


def cnormal_form(Edata, E):
    z = Edata["z"]
    basis = [Edata["reps"][c] for c in Edata["basis"]]
    prod = {}
    for v in range(16):
        x = CID
        for i in range(4):
            if v & (1 << i):
                x = cmul(x, basis[i])
        prod[v] = x
    nf = {}
    for v, x in prod.items():
        nf[x] = (0, v)
        nf[cmul(z, x)] = (1, v)
    assert set(nf) == set(E)
    return nf


def cgroup_from_two(a, b):
    return cclosure((a, b, cinv(a), cinv(b)))


def build_result():
    assert len(SL23) == 24
    assert len(CP) == 288

    H = oriented_w33_288()
    HE = derived_subgroup(H, 40)
    CE = cderived(CP)
    assert len(HE) == len(CE) == 32

    hhist = dict(sorted(Counter(porder(g) for g in H).items()))
    chist = dict(sorted(Counter(corder(g) for g in CP).items()))
    expected = {1: 1, 2: 19, 3: 80, 4: 12, 6: 80, 12: 96}
    assert hhist == chist == expected

    HQ = quotient_E_coords(HE, 40)
    CQ = cquotient_coords(CE)
    HA = action_mats(H, HQ)
    CA = caction_mats(CP, CQ)
    assert len(set(HA.values())) == len(set(CA.values())) == 9
    P = find_GL4_conjugator(set(HA.values()), set(CA.values()), HQ["q"], CQ["q"])
    assert P == (2, 9, 1, 4)

    # Lift the GL(4,2) map to the characteristic extraspecial kernels.
    _, Hnf = normal_form(HQ, HE, 40)
    Cnf = cnormal_form(CQ, CE)
    target_cosets = [CQ["invcoord"][mapply(P, 1 << i)] for i in range(4)]
    zC = CQ["z"]
    phiE = None
    for toggles in itertools.product((0, 1), repeat=4):
        tb = []
        for i, c in enumerate(target_cosets):
            base = CQ["cosets"][c][0]
            tb.append(cmul(zC, base) if toggles[i] else base)
        tprod = {}
        for v in range(16):
            x = CID
            for i in range(4):
                if v & (1 << i):
                    x = cmul(x, tb[i])
            tprod[v] = x
        phi = {}
        for h, (eps, v) in Hnf.items():
            phi[h] = cmul(zC, tprod[v]) if eps else tprod[v]
        if len(set(phi.values())) < 32:
            continue
        if all(phi[compose(a, b)] == cmul(phi[a], phi[b]) for a in HE for b in HE):
            phiE = phi
            break
    assert phiE is not None

    # Pick a C3 x C3 quotient basis on H, transport it by P, and require
    # conjugation compatibility on every element of the extraspecial kernel.
    mats = set(HA.values())
    I4 = (1, 2, 4, 8)

    def mord(A):
        x = I4
        for n in range(1, 7):
            x = mcomp(A, x)
            if x == I4:
                return n
        raise AssertionError

    def mclosure(gens):
        group = {I4}
        queue = deque([I4])
        gens = tuple(gens)
        while queue:
            x = queue.popleft()
            for g in gens:
                y = mcomp(g, x)
                if y not in group:
                    group.add(y)
                    queue.append(y)
        return group

    pair = None
    for a in mats:
        if mord(a) != 3:
            continue
        for b in mats:
            if mord(b) != 3 or b in mclosure((a,)):
                continue
            if mcomp(a, b) == mcomp(b, a) and len(mclosure((a, b))) == 9:
                pair = (a, b)
                break
        if pair:
            break
    assert pair is not None

    h_opts = [[g for g, A in HA.items() if A == M and porder(g) == 3] for M in pair]
    hgens = None
    for a in h_opts[0]:
        for b in h_opts[1]:
            if compose(a, b) != compose(b, a):
                continue
            C = generated_group((a, b), 40)
            if len(C) == 9 and len(C & HE) == 1:
                hgens = (a, b)
                HC = C
                break
        if hgens:
            break
    assert hgens is not None

    Pi = minv(P)
    target_pair = tuple(mcomp(mcomp(P, A), Pi) for A in pair)
    c_opts = [[g for g, A in CA.items() if A == M and corder(g) == 3] for M in target_pair]

    def hconj(g, x):
        return compose(compose(g, x), pinv(g))

    def cconj(g, x):
        return cmul(cmul(g, x), cinv(g))

    cgens = []
    for hg, opts in zip(hgens, c_opts):
        good = [cg for cg in opts if all(phiE[hconj(hg, x)] == cconj(cg, phiE[x]) for x in HE)]
        assert len(good) == 1
        cgens.append(good[0])
    assert cmul(cgens[0], cgens[1]) == cmul(cgens[1], cgens[0])
    CC = cgroup_from_two(*cgens)
    assert len(CC) == 9 and len(CC & CE) == 1

    # Complement map by simultaneous word walk.
    hid = tuple(range(40))
    cmap = {hid: CID}
    queue = deque([hid])
    gpairs = []
    for a, b in zip(hgens, cgens):
        gpairs.extend(((a, b), (pinv(a), cinv(b))))
    while queue:
        h = queue.popleft()
        c = cmap[h]
        for a, b in gpairs:
            nh = compose(a, h)
            nc = cmul(b, c)
            if nh not in cmap:
                cmap[nh] = nc
                queue.append(nh)
            else:
                assert cmap[nh] == nc
    assert len(cmap) == 9

    # Unique semidirect decomposition and full isomorphism.
    decomp = {}
    for ee in HE:
        for c in HC:
            x = compose(ee, c)
            assert x not in decomp
            decomp[x] = (ee, c)
    assert set(decomp) == H
    full_map = {h: cmul(phiE[ee], cmap[c]) for h, (ee, c) in decomp.items()}
    assert len(set(full_map.values())) == 288 and set(full_map.values()) == set(CP)
    assert all(full_map[compose(a, b)] == cmul(full_map[a], full_map[b]) for a in H for b in H)

    checks = {
        "W33_oriented_subgroup_order_288": len(H) == 288,
        "binary_tetrahedral_central_product_order_288": len(CP) == 288,
        "spectra_identical": hhist == chist,
        "derived_subgroups_are_extraspecial_order32": len(HE) == len(CE) == 32,
        "quotient_actions_are_C3_squared_order9": len(set(HA.values())) == len(set(CA.values())) == 9,
        "explicit_GL4_conjugator_found": P == (2, 9, 1, 4),
        "extraspecial_kernel_isomorphism": len(set(phiE.values())) == 32,
        "full_map_bijective": len(set(full_map.values())) == 288,
        "full_288_squared_homomorphism_check": True,
    }

    return {
        "schema": "w33.oriented288-binary-tetrahedral-bridge.v1",
        "status": "PASS" if all(checks.values()) else "FAIL",
        "W33_oriented_288": {
            "order": len(H),
            "center_order": len(center(H)),
            "derived_order": len(HE),
            "element_orders": hhist,
            "structure": "2_+^{1+4} : (C3 x C3)",
        },
        "binary_tetrahedral_local_Clifford": {
            "single_factor": "2T ~= SL(2,3), order 24",
            "construction": "(2T x 2T) / diag(C2)",
            "order": len(CP),
            "center_order": len(ccenter(CP)),
            "derived_order": len(CE),
            "element_orders": chist,
            "literature_name": "C1' tensor C1'",
            "literature_GAP_id": "SmallGroup(288,860)",
        },
        "explicit_isomorphism": {
            "GL4_conjugator_columns": list(P),
            "extraspecial_map_sha256": sha(sorted((str(k), str(v)) for k, v in phiE.items())),
            "full_map_sha256": sha(sorted((str(k), str(v)) for k, v in full_map.items())),
            "full_288_squared_homomorphism_check": True,
        },
        "extension_class_reading": {
            "common_interior": "W33 H+_288 ~= C1' tensor C1'",
            "W33_outer_completion": "adjoin an order-two factor-exchange lift",
            "complex_Clifford_outer_completion": "adjoin a special SWAP whose square is scalar phase; after quotienting only +/-I the swap lift has order four",
            "consequence": "the two 576 completions differ only outside the common 288 interior, at the lift of factor exchange",
        },
        "boundary": (
            "The binary-tetrahedral construction and the W33 isomorphism are verified here exactly. "
            "The naming of the central product as C1' tensor C1' and GAP ID SmallGroup(288,860) follows "
            "the two-qubit Clifford classification. This is a finite group theorem, not a hardware-phase claim."
        ),
        "checks": checks,
    }


def main():
    result = build_result()
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(json.dumps(result, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    print(json.dumps({
        "status": result["status"],
        "order": result["W33_oriented_288"]["order"],
        "GL4": result["explicit_isomorphism"]["GL4_conjugator_columns"],
        "full_check": result["explicit_isomorphism"]["full_288_squared_homomorphism_check"],
    }, sort_keys=True))
    return 0 if result["status"] == "PASS" else 1


if __name__ == "__main__":
    raise SystemExit(main())
