"""TOE48 magnetized realism: derive toy Higgs VEV selection, phase no-go,
plus elementary one-torus D-flatness obstruction. Not a global SM model.
"""
import json,runpy
from pathlib import Path
import numpy as np
R=Path(__file__).resolve().parents[1]
a=runpy.run_path(str(R/"analysis/w33_20261010_toe46_magnetized_overlap_flux336.py"))
Y=a["Y"];assert Y.shape==(6,3,3)
rng=np.random.default_rng(48002)
mu2=1.; lam=1.
# V=-mu²sum|h|² + lam(sum|h|²)² +delta sum |h_k|^4
def radial(delta):
 assert lam+min(delta,delta/6)>0
 if delta>0:
  neffective=6
  lam_eff=lam+delta/6
  magnitudes=np.full(6,np.sqrt(mu2/(2*lam_eff*6)))
 else:
  neffective=1
  lam_eff=lam+delta
  magnitudes=np.zeros(6);magnitudes[0]=np.sqrt(mu2/(2*lam_eff))
 V=-mu2**2/(4*lam_eff)
 direct=-mu2*sum(magnitudes**2)+lam*sum(magnitudes**2)**2+delta*sum(magnitudes**4)
 assert abs(V-direct)<1e-12
 return V,magnitudes,neffective
Vm,hm,nm=radial(-.2)
Vp,hp,np_=radial(.6)
assert nm==1 and np_==6
def cp(u,d):
 Hu=u@u.conj().T;Hd=d@d.conj().T
 C=Hu@Hd-Hd@Hu
 return float(np.imag(np.trace(C@C@C))),float(np.linalg.norm(C))
single=np.tensordot(hm,Y,axes=1)
# Monomial case always diagonal H, no CKM from one Higgs mode
assert np.max(abs(single@single.conj().T-np.diag(np.diag(single@single.conj().T))))<1e-12
cpvals=[]; comm=[]
for k in range(140):
 ua=hp*np.exp(1j*rng.uniform(-np.pi,np.pi,6))
 da=hp*np.exp(1j*rng.uniform(-np.pi,np.pi,6))
 Yu=np.tensordot(ua,Y,axes=1)
 Yd=np.tensordot(da,Y,axes=1)
 c,m=cp(Yu,Yd)
 cpvals.append(c);comm.append(m)
 # identical potential energy for each phase choice
 def V(h):return -mu2*np.vdot(h,h).real+lam*np.vdot(h,h).real**2+.6*sum(abs(h)**4)
 assert abs(V(ua)-Vp)<1e-12 and abs(V(da)-Vp)<1e-12
cpvals=np.array(cpvals);comm=np.array(comm)
assert np.max(abs(cpvals))>1e-7
assert np.std(cpvals)>1e-8
# Flux stack toy mA=0,mB=3,mC=6 creates pair differences -3,-3,+6,
# but on a SINGLE T2 the three U1 slopes m_i/A cannot all equal, so
# with no charged VEV, no common-D-flat equal-slope supersym branch.
flux=np.array([0,3,6],int)
diffs=[int(flux[i]-flux[j]) for i,j in [(0,1),(1,2),(2,0)]]
assert diffs==[-3,-3,6] and sum(diffs)==0
assert len(set(flux))>1
# A single T2 has index degenerate rank3 but full 3-T2 chiral index
# requires products of flux differences on all 3 tori, absent here.
out={"status":"TOE48_MINIMAL_MAGNETIZED_HIGGS_POTENTIAL_NO_PREDICTIVE_CKM_AND_D_FLAT_FIREWALL",
"one_torus_flux_stacks":flux.tolist(),"pairwise_flows":diffs,"normalized_overlap_Y_shape":list(Y.shape),
"potential":"V=-mu² sum|h|² + lambda(sum|h|²)² + delta sum|h_k|^4, mu²=lambda=1",
"negative_delta":{"delta":-.2,"VEV_support_modes":nm,"minimum_V":Vm,
"one_Higgs_YYdag_diagonal":True},
"positive_delta":{"delta":.6,"VEV_support_modes":np_,"minimum_V":Vp,
"degenerate_phase_moduli_count_before_gauge_reduction":6,
"exact_minimum_all_equal_magnitudes":hp.tolist(),
"phase_samples_with_identical_V":len(cpvals),
"CP_odd_ImTr_commutator_cubed_min":float(cpvals.min()),
"CP_odd_ImTr_commutator_cubed_max":float(cpvals.max()),
"CP_odd_ImTr_commutator_cubed_std":float(cpvals.std()),
"noncommuting_massmetric_fraction":float(np.mean(comm>1e-5))},
"analytic_minimization":"At fixed R=sum|h|², sum|h|^4 lies between R²/6 and R². For delta>0, global minimum has six equal nonzero magnitudes and V=-mu^4/[4(lambda+delta/6)]; for delta<0 and lambda+delta>0, minimum is a single active Higgs mode and V=-mu^4/[4(lambda+delta)]. ALL complex Higgs phases drop out from V; CP is not predicted by this potential.",
"one_torus_D_flat_obstruction":"With only a single positive-area T² and no charged scalar compensating D terms, line bundles of fluxes 0,3,6 have unequal slopes, so cannot all obey a common equal-slope SUSY D-flat condition. Additional T² fluxes, compensating fields or different gauge bundle data are required.",
"global_consistency_missing":["complete 10D gauge group and chiral spectrum","flux/tadpole/anomaly cancellation","Kahler metrics for ALL charged fields","multi-torus D/F constraints","Higgs potential generated by actual action","Wilson periods and gauge identifications","RG-evolved masses and CKM"],
"boundary":"This is an exact result for an intentionally MINIMAL assumed Higgs potential and toy normalized one-torus overlap tensor, not a first-principles SM compactification. Complex VEVs are tunable; nonzero CP invariant does not prove dynamical CP breaking."}
(R/"data/w33_20261010_toe48_magnetized_potential_firewall.json").write_text(json.dumps(out,indent=2)+"\n")
print(json.dumps({"status":out["status"],"cp_range":[cpvals.min(),cpvals.max()],"negative_mode":nm,"positive_mode":np_}))
