#!/usr/bin/env python3
"""Visible flag-quadrangle pairs as a homogeneous orbit.

Previous finite dictionary:
  X_min = point-line flags of W(3,3)              (160 objects)
  Z_min = ordinary quadrangles of W(3,3)         (1620 objects)
  visible projective X/Z pairs = 160*81 = 1620*8 = 12960
  vector-level nonzero X/Z pairs = 4*12960 = 51840 = |W(E6)|

This script proves the projective part is homogeneous: the visible flag-quadrangle
incidence set is a single orbit under the projective symplectic group generated by
symplectic transvections.  The permutation group generated on the 40 projective
points has order 25920 = |PSp(4,3)|, and the visible incidence orbit has size
12960, so the stabilizer has order 2.

Thus the Weyl count is not only arithmetic:
  |W(E6)| = 4 * |visible projective flag-quadrangle incidences|.
Equivalently, it is the scalar-phase lift of a homogeneous PSp(4,3) orbit.
"""
from __future__ import annotations

import json
from collections import Counter, deque
from itertools import combinations, product
from pathlib import Path

P = 3
Vec = tuple[int, int, int, int]


def canonical(v) -> Vec:
    vv = tuple(int(x) % P for x in v)
    if vv == (0, 0, 0, 0):
        raise ValueError("zero vector")
    for x in vv:
        if x:
            inv = 1 if x == 1 else 2
            return tuple((inv * y) % P for y in vv)  # type: ignore[return-value]
    raise AssertionError


def omega(u: Vec, v: Vec) -> int:
    return (u[0]*v[2] - u[2]*v[0] + u[1]*v[3] - u[3]*v[1]) % P


def compose(p: tuple[int, ...], q: tuple[int, ...]) -> tuple[int, ...]:
    """Permutation composition p after q."""
    return tuple(p[q[i]] for i in range(len(q)))


def build_geometry():
    points = []
    seen = set()
    for raw in product(range(P), repeat=4):
        if raw == (0, 0, 0, 0):
            continue
        c = canonical(raw)
        if c not in seen:
            seen.add(c)
            points.append(c)
    point_index = {p: i for i, p in enumerate(points)}

    edges = [(i, j) for i, j in combinations(range(len(points)), 2) if omega(points[i], points[j]) == 0]
    adjacency = [[False]*len(points) for _ in points]
    for i, j in edges:
        adjacency[i][j] = adjacency[j][i] = True

    lines = set()
    for i, j in edges:
        u, v = points[i], points[j]
        line = set()
        for a, b in product(range(P), repeat=2):
            if a == 0 and b == 0:
                continue
            line.add(point_index[canonical((a*u[t] + b*v[t] for t in range(4)))])
        lines.add(tuple(sorted(line)))
    lines = sorted(lines)
    line_index = {L: i for i, L in enumerate(lines)}

    edge_to_line = {}
    for li, L in enumerate(lines):
        for e in combinations(L, 2):
            edge_to_line[tuple(sorted(e))] = li

    flags = [(p, li) for li, L in enumerate(lines) for p in L]
    flag_index = {f: i for i, f in enumerate(flags)}

    quads = {}
    for a, b in combinations(range(len(points)), 2):
        if adjacency[a][b]:
            continue
        common = [x for x in range(len(points)) if adjacency[a][x] and adjacency[b][x]]
        for c, d in combinations(common, 2):
            cycle_edges = tuple(sorted(tuple(sorted(e)) for e in ((a, c), (c, b), (b, d), (d, a))))
            if cycle_edges not in quads:
                quads[cycle_edges] = {"cycle_edges": cycle_edges}
    quad_list = list(quads.values())
    quad_index = {q["cycle_edges"]: i for i, q in enumerate(quad_list)}

    def q_flags(q):
        fs = set()
        for u, v in q["cycle_edges"]:
            li = edge_to_line[tuple(sorted((u, v)))]
            fs.add((u, li))
            fs.add((v, li))
        return frozenset(fs)

    quad_flag_sets = [q_flags(q) for q in quad_list]
    visible = set()
    for qi, fs in enumerate(quad_flag_sets):
        for f in fs:
            visible.add((flag_index[f], qi))

    return points, point_index, edges, adjacency, lines, line_index, flags, flag_index, quad_list, quad_index, visible


def transvection_perm(points, point_index, a_idx: int) -> tuple[int, ...]:
    a = points[a_idx]
    perm = []
    for x in points:
        coef = omega(x, a)
        y = tuple((x[t] + coef*a[t]) % P for t in range(4))
        perm.append(point_index[canonical(y)])
    return tuple(perm)


def generate_projective_symplectic_group(points, point_index):
    gens = sorted({transvection_perm(points, point_index, i) for i in range(len(points))})
    identity = tuple(range(len(points)))
    seen = {identity}
    q = deque([identity])
    while q:
        g = q.popleft()
        for s in gens:
            h = compose(s, g)
            if h not in seen:
                seen.add(h)
                q.append(h)
    return gens, seen


def line_map_for_perm(perm, lines, line_index):
    return [line_index[tuple(sorted(perm[x] for x in L))] for L in lines]


def flag_map_for_perm(perm, lines, line_index, flags, flag_index):
    lm = line_map_for_perm(perm, lines, line_index)
    return [flag_index[(perm[p], lm[li])] for p, li in flags]


def quad_map_for_perm(perm, quad_list, quad_index):
    arr = []
    for q in quad_list:
        mapped = tuple(sorted(tuple(sorted((perm[u], perm[v]))) for u, v in q["cycle_edges"]))
        arr.append(quad_index[mapped])
    return arr


def main() -> int:
    points, point_index, edges, adjacency, lines, line_index, flags, flag_index, quad_list, quad_index, visible = build_geometry()
    gens, group = generate_projective_symplectic_group(points, point_index)

    gen_flag_maps = [flag_map_for_perm(g, lines, line_index, flags, flag_index) for g in gens]
    gen_quad_maps = [quad_map_for_perm(g, quad_list, quad_index) for g in gens]

    start = next(iter(visible))
    orbit = {start}
    q = deque([start])
    while q:
        f, z = q.popleft()
        for fm, qm in zip(gen_flag_maps, gen_quad_maps):
            nxt = (fm[f], qm[z])
            if nxt not in orbit:
                orbit.add(nxt)
                q.append(nxt)

    checks = {
        "geometry_counts": len(points) == 40 and len(edges) == 240 and len(lines) == 40 and len(flags) == 160 and len(quad_list) == 1620,
        "visible_projective_count": len(visible) == 12960,
        "transvection_generated_group_order": len(group) == 25920,
        "visible_pairs_single_orbit": orbit == visible,
        "orbit_stabilizer": len(group) // len(orbit) == 2,
        "weyl_lift": 4 * len(visible) == 51840,
    }

    payload = {
        "theorem_name": "Visible Pair Orbit-Weyl Torsor Theorem",
        "summary": {
            "points": len(points),
            "lines": len(lines),
            "flags_Xmin": len(flags),
            "quadrangles_Zmin": len(quad_list),
            "visible_projective_pairs": len(visible),
            "projective_group_order": len(group),
            "visible_orbit_size": len(orbit),
            "projective_stabilizer_order": len(group) // len(orbit),
            "vector_lift_count": 4 * len(visible),
            "W_E6_order": 51840,
            "all_checks_passed": all(checks.values()),
        },
        "checks": checks,
        "identities": {
            "PSp_order": "25920",
            "projective_visible_orbit": "12960 = 25920 / 2",
            "scalar_phase_lift": "4 * 12960 = 51840 = |W(E6)|",
            "interpretation": "Nonzero vector-level minimal X/Z pairings are the scalar-phase lift of one homogeneous visible flag-quadrangle orbit.",
        },
    }
    root = Path(__file__).resolve().parents[1]
    out = root / "data" / "w33_visible_pair_orbit_weyl_torsor.json"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    print(json.dumps(payload["summary"], indent=2, sort_keys=True))
    return 0 if payload["summary"]["all_checks_passed"] else 1


if __name__ == "__main__":
    raise SystemExit(main())
