#!/usr/bin/env python3
"""Compress the complete 18x18 E8 holonomy bracket tensor into a packet scheduler.

Parents:
  data/w33_e8_holonomy_bracket_rank_tensor.json
  data/w33_packet18_external_regular_holonomy_action.json

The 18 holonomy sectors are labelled by
    K = C3_rho x C3_a x C2_b.
The exact external packet theorem realizes K regularly on packet18, so every
packet block can carry one holonomy label.

Lie grading gives the target sector lookup-free:
    z = x + y  in K.
All 324 ordered brackets are nonzero.  The parent tensor proves that 284/324
are target-surjective.  Only 40 ordered pairs are deficient, and those 40
collapse to 13 orbits under the exact C2 x C2 symmetry generated by
independent inversion of rho and a.

Therefore the full bracket-rank scheduler is:

  1. add the two packet holonomy labels componentwise (mod 3,3,2);
  2. set rank = dim(target);
  3. canonicalize the ordered input pair under the four inversion symmetries;
  4. if it matches one of 13 exception records, subtract the stored deficiency.

This reconstructs all 324 ranks exactly from:
  * 18 sector dimensions,
  * 13 exception deficiencies,
  * the fixed four-element symmetry action.

It does NOT define a multiplication on the cosets G/C4.  The addition used by
the scheduler is the external holonomy-character group law already realized as
a regular permutation action on packet18.
"""
from __future__ import annotations
import json
from pathlib import Path

ROOT=Path(__file__).resolve().parents[1]
OUT=ROOT/'data/w33_packet18_e8_bracket_scheduler.json'

def parse(s): return tuple(map(int,s.split(',')))
def key(x): return ','.join(map(str,x))
def add(x,y): return ((x[0]+y[0])%3,(x[1]+y[1])%3,(x[2]+y[2])%2)
def ap(M,c):
    r,a,b=c
    return ((M[0]*r+M[1]*a)%3,(M[2]*r+M[3]*a)%3,b)

def canon_pair(x,y,mats):
    O=[(key(ap(M,x)),key(ap(M,y))) for M in mats]
    return min(O)

def main(write=True):
    tensor=json.loads((ROOT/'data/w33_e8_holonomy_bracket_rank_tensor.json').read_text())
    packet=json.loads((ROOT/'data/w33_packet18_external_regular_holonomy_action.json').read_text())
    assert tensor['status']=='PASS_COMPLETE_18x18_BRACKET_TENSOR'
    assert packet['status']=='PASS_EXTERNAL_REGULAR_HOLONOMY_ACTION'

    sectors=[parse(s) for s in tensor['sector_order']]
    dims={parse(k):int(v) for k,v in tensor['sector_dimensions'].items()}
    mats=[tuple(M) for M in tensor['rank_tensor_symmetry']['matrices_mod3']]
    assert len(mats)==4

    # Build the 13-record exception table from orbit representatives.
    exceptions={}
    records=[]
    for o in tensor['rank_tensor_symmetry']['deficient_orbits']:
        rep=o['representative']
        x=parse(rep['left']);y=parse(rep['right'])
        c=canon_pair(x,y,mats)
        assert c==(rep['left'],rep['right'])
        d=int(o['deficiency'])
        assert c not in exceptions
        exceptions[c]=d
        records.append({
          'canonical_left':c[0],'canonical_right':c[1],
          'deficiency':d,'orbit_size':int(o['size']),
          'target':rep['target'],'rank':int(rep['rank']),
          'target_dim':int(rep['target_dim'])})
    assert len(exceptions)==13
    assert sum(r['orbit_size'] for r in records)==40

    # Reconstruct every rank from target addition + 13 exception records.
    predicted=[]
    mismatches=[]
    exception_hits=0
    for i,x in enumerate(sectors):
        row=[]
        for j,y in enumerate(sectors):
            z=add(x,y)
            c=canon_pair(x,y,mats)
            d=exceptions.get(c,0)
            if d: exception_hits+=1
            rank=dims[z]-d
            row.append(rank)
            actual=int(tensor['rank_matrix'][i][j])
            if rank!=actual:
                mismatches.append({
                  'left':key(x),'right':key(y),'target':key(z),
                  'predicted':rank,'actual':actual,'canonical':list(c)})
        predicted.append(row)
    assert not mismatches
    assert exception_hits==40
    assert predicted==tensor['rank_matrix']

    # Packet address for a holonomy label.
    def packet_addr(c):
        rho,a,b=c
        return {'rho':rho,'a':a,'b':b,'hesse_bin':3*rho+a,
                'packet18_index':2*(3*rho+a)+b}
    target_examples=[]
    for x,y in [
        ((0,0,0),(0,0,0)),
        ((0,1,1),(0,2,1)),
        ((1,1,0),(2,2,1)),
        ((2,1,1),(2,2,0)),
    ]:
        z=add(x,y);c=canon_pair(x,y,mats);d=exceptions.get(c,0)
        target_examples.append({
          'left':packet_addr(x),'right':packet_addr(y),'target':packet_addr(z),
          'canonical_exception_pair':list(c),'deficiency':d,
          'rank':dims[z]-d,'target_dim':dims[z]})

    out={
      'schema':'w33.packet18_e8_bracket_scheduler.v1',
      'status':'PASS_EXACT_LOOKUP_LIGHT_BRACKET_SCHEDULER',
      'headline':'The complete 18x18 E8 holonomy bracket-rank tensor compiles onto packet18 as group-add target routing plus a 13-record deficiency table. All 324 brackets are nonzero; 284 use the full target dimension by default. The remaining 40 ordered pairs are exactly 13 C2xC2 inversion orbits. This reconstructs every bracket rank with no 324-entry rank matrix.',
      'routing':{
        'label_group':'K=C3_rho x C3_a x C2_b',
        'target_rule':'(rho,a,b)+(rho2,a2,b2) componentwise mod (3,3,2)',
        'packet_address':'hesse_bin=3*rho+a; packet18_index=2*hesse_bin+b',
        'all_products_nonzero':True},
      'rank_compiler':{
        'default':'rank = dimension(target)',
        'surjective_pairs':284,
        'deficient_pairs':40,
        'symmetry':'C2 x C2 independent inversion of rho and a',
        'exception_orbits':13,
        'exception_records':records,
        'reconstruction_exact_324_of_324':True},
      'storage_comparison':{
        'raw_rank_entries':324,
        'sector_dimensions':18,
        'exception_records':13,
        'integer_payload_entries_after_compression':31,
        'raw_to_payload_ratio':324/31,
        'note':'symmetry matrices and fixed modular-add rules are code constants rather than rank payload entries'},
      'examples':target_examples,
      'packet_boundary':'The target addition is the external holonomy-character law carried by packet labels. It is not multiplication of right cosets in G/C4, whose stabilizer C4 is nonnormal.',
      'physical_boundary':'This schedules sector addresses and bracket ranks; it does not supply structure constants, phases, or a hardware realization of the E8 Lie bracket.',
      'parents':['data/w33_e8_holonomy_bracket_rank_tensor.json',
                 'data/w33_packet18_external_regular_holonomy_action.json'],
      'checks':{
        'all324_reconstructed':True,
        '13_exception_orbits':True,
        '40_exception_hits':True,
        'target_routing_is_group_addition':True,
        'packet_regular_action_loaded':True}}
    if write:OUT.write_text(json.dumps(out,indent=2)+'\n')
    print(json.dumps(out,indent=2));return out

if __name__=='__main__':main(True)
