#!/usr/bin/env python3
"""Pass5293: all-odd footprint rank is a same-point-difference generation problem.

For odd q, Pass5288 proves the W-line code lies in ker(F^T), hence
rank_2(F)<=g=q(q^2+1)/2.  This pass adds an exact q=11 anchor and records the
stronger structural equivalence obtained from the chamber dependency/cut-space
theorem.

Let D_q be the apartment-code subspace generated by differences of two chamber
stars based at the same W-point.  The point-even chamber coefficient space has
dimension v*q, v=(q+1)(q^2+1).  Intersecting the full Levi cut-space dependency
kernel with point-even coefficients forces the line-side cut label b into ker N,
where N is the W point-line incidence matrix.  For odd q,
nullity_2(N)=g.  Modding out the global constant cut gives kernel dimension
v+g-1, hence

    dim D_q = v*q-(v+g-1) = q^4-g.

D_q has zero point parity, so D_q <= K0, the zero-P-parity residual.  Since
 dim K0=q^4-rank_2(F), one gets the exact equivalence

    rank_2(F)=g  <=>  K0=D_q.

Thus the all-odd rank conjecture is equivalent to a concrete generation theorem:
every zero-P word is generated by same-point chamber-star differences.
"""
from __future__ import annotations
import itertools,json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
OUT=ROOT/'data/PART_W33_PASS5293_ALLODD_RANK_REDUCTION_Q11.json'

def gf2_rank(rows):
    piv={}
    for x in rows:
        while x:
            p=x.bit_length()-1
            if p in piv:x^=piv[p]
            else:piv[p]=x;break
    return len(piv)

def norm(v,q):
    for x in v:
        if x:
            s=pow(x,-1,q);return tuple(s*y%q for y in v)
    raise ValueError

def sp(u,v,q):return (u[0]*v[2]-u[2]*v[0]+u[1]*v[3]-u[3]*v[1])%q

def points(q):
    P=[]
    for a,b,c in itertools.product(range(q),repeat=3):P.append((1,a,b,c))
    for b,c in itertools.product(range(q),repeat=2):P.append((0,1,b,c))
    for c in range(q):P.append((0,0,1,c))
    P.append((0,0,0,1));return P

def line_bases(q):
    for a,b,c,d in itertools.product(range(q),repeat=4):yield (1,0,a,b),(0,1,c,d)
    for a,b,c in itertools.product(range(q),repeat=3):yield (1,a,0,b),(0,0,1,c)
    for a,b in itertools.product(range(q),repeat=2):yield (1,a,b,0),(0,0,0,1)
    for a,b in itertools.product(range(q),repeat=2):yield (0,1,0,a),(0,0,1,b)
    for a in range(q):yield (0,1,a,0),(0,0,0,1)
    yield (0,0,1,0),(0,0,0,1)

def line_points(u,v,q,pi):
    S={pi[norm(v,q)]}
    for a in range(q):S.add(pi[norm(tuple((u[k]+a*v[k])%q for k in range(4)),q)])
    return tuple(sorted(S))

def q11_anchor():
    q=11;P=points(q);pi={p:i for i,p in enumerate(P)};assert len(P)==1464
    carriers={};noniso=0
    for u,v in line_bases(q):
        if sp(u,v,q)==0:continue
        noniso+=1;H=line_points(u,v,q,pi)
        Hp=tuple(i for i,x in enumerate(P) if sp(x,u,q)==0 and sp(x,v,q)==0)
        C=tuple(sorted(set(H)|set(Hp)));assert len(C)==24;carriers[C]=1
    assert noniso==14762 and len(carriers)==7381
    rows=[0]*len(P)
    for j,C in enumerate(sorted(carriers)):
        for p in C:rows[p]|=1<<j
    assert {x.bit_count() for x in rows}=={121}
    r=gf2_rank(rows);assert r==671
    return {'q':11,'W_points':1464,'P_components':7381,'point_footprint_weight':121,'rank_F2':r,'target_g':671}

def main():
    for q in (3,5,7,9,11):
        v=(q+1)*(q*q+1);g=q*(q*q+1)//2
        dimD=v*q-(v+g-1)
        assert dimD==q**4-g
    anchor=q11_anchor()
    out={'pass':5293,'status':'THEOREM_ALLODD_RANK_EQUIVALENT_TO_SAME_POINT_DIFFERENCE_GENERATION_WITH_Q11_ANCHOR',
      'all_odd_upper_bound':'rank_2(F)<=g=q(q^2+1)/2',
      'same_point_difference_dimension':'dim D_q=q^4-g',
      'relation_space':'Among the v(q-1)=q^4-1 local fiber coordinates, relations have dimension g-1 and are canonically ker(N)/<1>.',
      'equivalence':'rank_2(F)=g iff the zero-P residual K0 is generated by same-point chamber-star differences D_q.',
      'rank_equality_anchors':{'q3':15,'q5':65,'q7':175,'q9':369,'q11':671},
      'q11':anchor,
      'boundary':'The generation theorem K0=D_q is not yet proved for every odd q. Literature on mod-2 Sp/O(5) permutation modules supplies the surrounding submodule lattice, but an objectwise identification of this footprint quotient map is still required.'}
    OUT.write_text(json.dumps(out,indent=2)+'\n');print(json.dumps(out,indent=2))
if __name__=='__main__':main()
