"""Round34 exact Clifford(6) spin lifts of A6 to 2.A6=SL2(9).

Represent basis e_i^2=+1 in Cl6 via 64-bitmask and rational
coefficients, and use normalized root reflections to lift 3-cycles:
u_ij=(e_i-e_j)/sqrt2; lift(ijk)=u_ij u_jk.
All even products rational; no floating approximations.
"""
from pathlib import Path
from fractions import Fraction as F
from collections import deque,Counter
import json,math
ROOT=Path(__file__).resolve().parents[1]
OUT=ROOT/'data/w33_20261010_toe34_spin_sl29_exact_clifford.json'
def sign(a,b):
 n=0
 while a:
  low=a&-a;i=low.bit_length()-1
  n+=(b&((1<<i)-1)).bit_count()
  a^=low
 return -1 if n%2 else 1
def mul(x,y):
 z={}
 for a,u in x.items():
  for b,v in y.items():
   k=a^b
   z[k]=z.get(k,F(0))+u*v*sign(a,b)
 return {k:v for k,v in z.items() if v}
def add(x,y,scale=1):
 z=dict(x)
 for k,v in y.items():z[k]=z.get(k,F(0))+scale*v
 return {k:v for k,v in z.items() if v}
def root(i,j):return {1<<i:F(1),1<<j:F(-1)}
def lift(i,j,k):return {mask:v/2 for mask,v in mul(root(i,j),root(j,k)).items()}
def key(x):return tuple(sorted((m,v.numerator,v.denominator) for m,v in x.items()))
def power(x,n):
 a={0:F(1)}
 for j in range(n):a=mul(a,x)
 return a
def run():
 ONE={0:F(1)};NEG={0:F(-1)}
 gen=[lift(0,1,j) for j in (2,3,4,5)]
 assert all(power(x,3)==ONE for x in gen)
 seen={key(ONE):ONE};q=deque([ONE])
 while q:
  u=q.popleft()
  for g in gen:
   v=mul(u,g);k=key(v)
   if k not in seen:seen[k]=v;q.append(v)
   if len(seen)>750:raise ValueError('not finite spin lift; unexpected >750')
 assert len(seen)==720,len(seen)
 assert key(NEG) in seen
 assert all(not(m.bit_count()%2) for x in seen.values() for m in x)
 scalar=Counter()
 for x in seen.values():
  if all(m==0 for m in x):scalar[str(x[0])]+=1
 assert scalar=={'1':1,'-1':1},scalar
 # The canonical Spin(6) half-spin rep is complex dimension4:
 # in Clifford even subalgebra Cl6^+ ~= Mat4(C)⊕Mat4(C);
 # the central scalar (-1) acts as -I4 on BOTH halfspin.
 # Embed Spin6≅SU4 -> SU5 as diag(U4,1).
 # This represents a faithful 720-element central double cover,
 # not the 360-element projective A6.
 r=dict(status='PASS',
  group='2.A6=SL(2,9) generated by four lifted (0,1,j) three-cycles, j=2,3,4,5',
  exact_clifford_basis='Cl6 over Q with e_i²=+1, basis masks0..63; root normalized (e_i-e_j)/sqrt2; products of two roots rational',
  generators=[{str(mask):str(v) for mask,v in x.items()} for x in gen],
  each_generator_order=3,exact_group_order=720,even_clifford_only=True,
  central_negative_identity_present=True,scalar_centre_elements=dict(scalar),
  base_projective_group_order=360,
  spinorial_4D_construction='Via Spin(6)≅SU(4), each even Clifford lift acts on complex chiral half-spin module C^4. Central -1 acts as -I4, so the 4D representation does not factor through A6. The explicit exact Clifford group words specify generators without requiring floating-point matrices.',
  SU5_embedding='diag(4D spinorial SU4 action,1) lies inside SU5 (det=1) and is faithful SL2(9). The central element acts as diag(-I4,+1), not a scalar, and has determinant1.',
  E8_candidate='A maximal-rank (SU5_L×SU5_G)/Z5 subgroup of compact E8 admits this SL2(9) subgroup in SU5_L. SU5_G commutes with it, but the actual E8 centralizer, translation compatibility, Lorentz chiral physical matter and dynamical gauge symmetry require separate calculations.',
  not_done='No faithful 4D Hilbert spinor wavefunction as observed fermion; no E8 root matrices or full commutant restriction are computed; no Z3.M translations or physical vacuum, no SM generations. This route is distinct from the parallel Weyl-Tits A6 bosonic subgroup.')
 OUT.write_text(json.dumps(r,indent=2)+'\n')
 print('ROUND34 SPIN 720 exact rational Clifford elements',len(seen),'scalar',scalar,flush=True)
 return r
if __name__=='__main__':run()
