from __future__ import annotations
import json,hashlib
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1];OUT=ROOT/'data'/'w33_pass1096_formal_character_hesse_e8_lock.json'
def main():
 c=json.loads((ROOT/'data'/'w33_pass1092_u42dot2_character_identification.json').read_text());h=json.loads((ROOT/'data'/'w33_pass1093_dual_hesse_firewall_fiber_equivalence.json').read_text());e=json.loads((ROOT/'data'/'w33_pass1094_e8_root_sheet_bridge.json').read_text());v=json.loads((ROOT/'data'/'w33_pass1095_vendor_controller_adapter.json').read_text());lean=(ROOT/'formal/W33/Pass1096CharacterHesseE8Lock.lean').read_text()
 sizes=[x['class_size'] for x in c['atlas_classes']];plus=c['characters']['81_plus']['values'];minus=c['characters']['81_minus']['values'];root=e['root_action']['character_ATLAS_order'];lines=e['antipodal_root_line_action']['character_ATLAS_order'];sign=c['outer_sign_character']
 dot=lambda a,b:sum(s*x*y for s,x,y in zip(sizes,a,b))
 checks={'twentyfive_ATLAS_classes':len(sizes)==25,'81_minus_is_sign_twist':minus==[a*b for a,b in zip(sign,plus)],'root_81plus_numerator_zero':dot(plus,root)==0,'root_81minus_numerator_zero':dot(minus,root)==0,'line_81plus_numerator_zero':dot(plus,lines)==0,'line_81minus_numerator_zero':dot(minus,lines)==0,'restriction_81plus_to_inner81':c['restriction_U42dot2_to_U42']['81_plus']=={'81':1},'restriction_81minus_to_inner81':c['restriction_U42dot2_to_U42']['81_minus']=={'81':1},'induction_inner81_is_plus_minus':c['induction_U42_to_U42dot2']['81']=={'81_minus':1,'81_plus':1},'dual_hesse_fiber_equivalence_passed':h['status']=='PASS' and h['checks']['explicit_bijection_to_F3_squared'],'vendor_adapter_passed':v['status']=='PASS' and v['checks']['dry_run_never_acquires'],'lean_defines_character_vectors':all(x in lean for x in ['chi81Plus','chi81Minus','e8RootCharacter','e8RootLineCharacter']),'lean_locks_four_zero_inner_products':lean.count('no_81')==4,'lean_locks_sign_twist':'minus_is_sign_twist' in lean,'lean_locks_dimension_sums':'inner_frame_dimension' in lean and 'outer_frame_dimension' in lean,'tensor_hashes_locked':c['characters']['81_plus']['degree']==81 and '1455f33e' in lean and '66476d71' in lean,'formal_import_target':'Pass1091FrameOrbitalIntertwiner' in lean}
 assert all(checks.values()),checks
 out={'schema':'w33.pass1096.formal_character_hesse_e8_lock.v1','status':'PASS','headline':'Compact formal locks now freeze the official-class 81_plus/minus characters, their outer-sign twist, the four exact zero multiplicities in the E8 root and root-line modules, the rank/dimension decompositions, and the two Steinberg tensor hashes. The dual-Hesse/fiber equivalence and vendor adapter remain executable external certificates.','lean_module':'formal/W33/Pass1096CharacterHesseE8Lock.lean','lean_sha256':hashlib.sha256(lean.encode()).hexdigest(),'check_count':len(checks),'checks':checks,'scope':'Python recheck plus Lean source generation. Local Lean is unavailable; compilation is delegated to CI.'};OUT.write_text(json.dumps(out,indent=2)+'\n');print(json.dumps({'status':'PASS','checks':len(checks),'lean_sha256':out['lean_sha256']},indent=2))
if __name__=='__main__':main()
