#!/usr/bin/env python3
"""
The whole cosmological tower as one dated point in the (n_s, r) plane. The substrate
predicts (n_s, r) = (0.9667, 0.00333) -- the N = 60 point on the Starobinsky line r =
3(1-n_s)^2 -- consistent with Planck today and a sharp target for CMB-S4 / LiteBIRD: r is
a 6.7 sigma detection (sigma(r) ~ 0.0005), the point is pinned to a tiny ellipse, and N is
measured to sigma(N) ~ 3.6, testing N = 2 beat = 60 against N = 50 at ~2.8 sigma. One figure
turns the entire inflationary tower into a single falsifiable wager in the plane every
experiment reports.

w33_consistency_audit.py found n_s the tightest external point. This forecasts exactly how
the next experiments localise the substrate in (n_s, r).

THE SUBSTRATE POINT. (n_s, r) = (1 - 1/beat, 1/(Phi_4 beat)) = (0.9667, 0.00333), which lies
on the Starobinsky curve r = 3(1-n_s)^2 (since r = 12/N^2 and 1-n_s = 2/N) at N = 60. So the
prediction is not a blob but a POINT on a known one-parameter curve, with N = 60 the
location.

THE CURRENT STATUS (Planck + BICEP/Keck 2021). n_s = 0.9649 +/- 0.0042, r < 0.036. The
substrate n_s is 0.42 sigma high; r is well below the bound. Consistent.

THE FORECAST (CMB-S4 / LiteBIRD, sigma(n_s) ~ 0.002, sigma(r) ~ 0.0005). If the truth is the
substrate point:
  * r detection:  r/sigma(r) = 0.00333/0.0005 = 6.7 sigma  (tensors detected),
  * on the line:  the measured (n_s, r) tests r = 3(1-n_s)^2 (Starobinsky/substrate) against
                  e.g. chaotic m^2 phi^2 (r = 8(1-n_s)/... far higher r) -- excluded already,
  * N measured:   sigma(N) = (N^2/2) sigma(n_s) = 3.6, so N = 60 +/- 3.6 -- tests N = 2 beat
                  = 60 against N = 50 at (60-50)/3.6 = 2.8 sigma.
So by the mid-2030s the substrate is either confirmed as the Starobinsky N=60 point (r ~
1/300, n_s ~ 0.967) or excluded.

THE FIGURE. A TikZ (n_s, r) plane is emitted to analysis/w33_ns_r_forecast_fig.tex: the
Starobinsky line r = 3(1-n_s)^2, the substrate N=60 point, the Planck 1 sigma n_s band, and
the CMB-S4 forecast ellipse (sigma(n_s)=0.002, sigma(r)=0.0005) centred on the substrate
point -- the single figure summarising the cosmological tower's falsifiability.

Honest scope: the substrate point and the Starobinsky-line membership are exact; the
forecast sigma(n_s), sigma(r) are the experiments' published sensitivities (realised values
depend on foregrounds/delensing); the N and r significances follow. A concrete, dated
falsification target, not a new prediction -- the packaging of Passes 6-11 into one plot.

Verifies the substrate point on r = 3(1-n_s)^2, the detection/N significances, and emits the
figure.
"""
from __future__ import annotations

import json


def main():
    out = {}
    q = 3
    Phi4 = q * q + 1  # 10
    beat = 30
    N = 2 * beat  # 60
    n_s = 1 - 1 / beat
    r = 1 / (Phi4 * beat)
    print("== the cosmological tower as one (n_s, r) point ==")
    print(
        f"  substrate (n_s, r) = ({n_s:.4f}, {r:.5f}); on Starobinsky line r=3(1-n_s)^2: "
        f"{3*(1-n_s)**2:.5f}"
    )
    assert abs(r - 3 * (1 - n_s) ** 2) < 1e-9
    out["substrate_point"] = {
        "n_s": round(n_s, 4),
        "r": round(r, 5),
        "on_line": "r = 3(1-n_s)^2 (Starobinsky), N=60",
    }

    # current status
    ns_planck, ns_err = 0.9649, 0.0042
    sig_now = (n_s - ns_planck) / ns_err
    print(
        f"\n[current]  Planck n_s={ns_planck}+/-{ns_err} -> substrate {sig_now:.2f} sigma; r<0.036 OK"
    )
    out["current"] = {"n_s_sigma": round(sig_now, 2), "r": "< 0.036 (consistent)"}

    # forecast
    sig_ns, sig_r = 0.002, 0.0005
    r_det = r / sig_r
    sig_N = (N**2 / 2) * sig_ns
    N_vs_50 = (N - 50) / sig_N
    print(f"\n[CMB-S4/LiteBIRD forecast: sigma(n_s)={sig_ns}, sigma(r)={sig_r}]")
    print(f"  r detection: r/sigma(r) = {r_det:.1f} sigma")
    print(
        f"  N measured: sigma(N) = (N^2/2) sigma(n_s) = {sig_N:.1f} -> N = 60 +/- {sig_N:.1f}"
    )
    print(f"  tests N=2 beat=60 vs N=50 at {N_vs_50:.1f} sigma")
    assert r_det > 5
    out["forecast"] = {
        "sigma_ns": sig_ns,
        "sigma_r": sig_r,
        "r_detection_sigma": round(r_det, 1),
        "sigma_N": round(sig_N, 1),
        "N_vs_50_sigma": round(N_vs_50, 1),
    }

    # emit TikZ figure
    fig = r"""% Auto-generated by w33_ns_r_forecast.py -- the (n_s, r) falsifiability plane
\begin{figure}[ht]\centering
\begin{tikzpicture}[x=18cm,y=90cm]
  \def\nsa{0.955}\def\nsb{0.975}
  \draw[thick,-{Stealth}] (\nsa,0)--(\nsb,0) node[right]{$n_s$};
  \draw[thick,-{Stealth}] (\nsa,0)--(\nsa,0.012) node[above]{$r$};
  \foreach \x in {0.955,0.960,0.965,0.970,0.975} \draw (\x,0)--(\x,-0.0003) node[below=1pt]{\footnotesize\x};
  \foreach \y in {0.000,0.004,0.008,0.012} \draw (\nsa,\y)--(\nsa-0.0006,\y) node[left=1pt]{\footnotesize\y};
  % Starobinsky line r = 3(1-n_s)^2
  \draw[blue!60!black,thick,domain=0.955:0.975,samples=50,variable=\x] plot (\x,{3*(1-\x)*(1-\x)});
  \node[blue!60!black,font=\footnotesize,anchor=west] at (0.9565,0.0072) {Starobinsky $r=3(1-n_s)^2$};
  % N markers on the line
  \foreach \Nv/\lbl in {50/50,55/55,60/60} {
    \pgfmathsetmacro\nsv{1-2/\Nv}\pgfmathsetmacro\rv{12/(\Nv*\Nv)}
    \fill[blue!60!black] (\nsv,\rv) circle (1.2pt);
    \node[font=\tiny,anchor=south west] at (\nsv,\rv) {$N{=}\lbl$};
  }
  % substrate N=60 point with CMB-S4 forecast ellipse
  \fill[red] (0.96667,0.003333) circle (1.6pt);
  \node[red,font=\footnotesize,anchor=north west] at (0.96667,0.003333) {substrate ($N{=}60$)};
  \draw[red,thick] (0.96667,0.003333) ellipse [x radius=0.002, y radius=0.0005];
  \node[red,font=\tiny,anchor=south] at (0.96667,0.00383) {CMB-S4 $1\sigma$};
  % Planck n_s band
  \draw[gray,dashed] (0.9649,0)--(0.9649,0.012);
  \draw[gray!40,fill=gray!12,opacity=0.5] (0.9607,0)rectangle(0.9691,0.012);
  \node[gray,font=\tiny,anchor=south,rotate=90] at (0.9649,0.009) {Planck $n_s$};
\end{tikzpicture}
\caption{The cosmological tower as one point in the $(n_s,r)$ plane. The substrate predicts
the $N=2\,\mathrm{beat}=60$ point (red) on the Starobinsky line $r=3(1-n_s)^2$ (blue):
$(n_s,r)=(0.9667,1/300)$. It sits $0.42\sigma$ from Planck's $n_s$ (grey band) and below the
current $r$ bound. A CMB-S4/LiteBIRD measurement ($\sigma(n_s)\sim0.002$, $\sigma(r)\sim
0.0005$; red ellipse) detects $r=1/300$ at $6.7\sigma$, pins the point, and measures
$N=60\pm3.6$ -- testing $N=2\,\mathrm{beat}$ against $N=50$ at $2.8\sigma$.}
\label{fig:ns-r-forecast}
\end{figure}
"""
    with open("analysis/w33_ns_r_forecast_fig.tex", "w") as fh:
        fh.write(fig)
    print("\nwrote analysis/w33_ns_r_forecast_fig.tex (TikZ (n_s,r) figure)")
    out["figure"] = "analysis/w33_ns_r_forecast_fig.tex"

    print(
        "\nRESULT: the entire cosmological tower is one dated point in the (n_s, r) plane."
    )
    print(
        "  The substrate predicts (n_s, r) = (0.9667, 1/300), the N = 2 beat = 60 point on"
    )
    print(
        "  the Starobinsky line r = 3(1-n_s)^2 -- not a region but a point on a known"
    )
    print("  curve. Today it sits 0.42 sigma from Planck's n_s and below the r bound")
    print(
        "  (consistent). A CMB-S4 / LiteBIRD measurement (sigma(n_s) ~ 0.002, sigma(r) ~"
    )
    print(
        "  0.0005) detects r = 1/300 at 6.7 sigma, pins the point to a tiny ellipse, and"
    )
    print(
        "  measures N = 60 +/- 3.6, testing N = 2 beat = 60 against N = 50 at 2.8 sigma. So"
    )
    print(
        "  by the mid-2030s the whole tower is confirmed as the Starobinsky N=60 point or"
    )
    print(
        "  excluded -- a single figure (emitted here) carrying the falsifiability of Passes"
    )
    print("  6-11 in the one plane every inflation experiment reports.")

    out["summary"] = (
        "the cosmological tower as ONE dated point in the (n_s, r) plane. The substrate "
        "predicts (n_s, r) = (1-1/beat, 1/(Phi_4 beat)) = (0.9667, 1/300), the N = 2 beat = "
        "60 point on the Starobinsky line r = 3(1-n_s)^2 -- a point on a known one-parameter "
        "curve, with N=60 the location. Current (Planck + BK 2021): n_s 0.42 sigma high, r < "
        "0.036, consistent. Forecast (CMB-S4/LiteBIRD, sigma(n_s)~0.002, sigma(r)~0.0005): r "
        "detected at 6.7 sigma, the point pinned to a tiny ellipse, N measured to sigma(N) = "
        "(N^2/2)sigma(n_s) = 3.6 (N = 60 +/- 3.6), testing N=2 beat=60 vs N=50 at 2.8 sigma. "
        "So by the mid-2030s the tower is confirmed as the Starobinsky N=60 point or "
        "excluded. A TikZ figure (analysis/w33_ns_r_forecast_fig.tex) shows the Starobinsky "
        "line, the substrate point, the Planck n_s band, and the CMB-S4 ellipse. HONEST: the "
        "point and line-membership are exact; sigma(n_s), sigma(r) are published "
        "sensitivities (realised values depend on foregrounds/delensing). The packaging of "
        "Passes 6-11 into one falsifiable plot, not a new prediction."
    )
    out["sources"] = [
        "substrate (n_s,r) (w33_starobinsky.py, w33_consistency_audit.py); Starobinsky line "
        "r=3(1-n_s)^2; Planck+BK 2021 n_s=0.9649+/-0.0042, r<0.036; CMB-S4 sigma(r)~0.0005, "
        "LiteBIRD/CMB-S4 sigma(n_s)~0.002 (forecasts); sigma(N)=(N^2/2)sigma(n_s) from 1-n_s=2/N."
    ]
    with open("data/w33_ns_r_forecast.json", "w") as fh:
        json.dump(out, fh, indent=2)
    print("wrote data/w33_ns_r_forecast.json")


if __name__ == "__main__":
    main()
