#!/usr/bin/env python3
"""Pass5158: close the q=5 leader-21 sharp sector using selected four-edge paths.

Pass5148 leaves only m=21,n1=33.  It proves N_112>=48, hence triple-star
intersection mass at least 25*48=1200, while 1242 suffices.  The missing input
is already forced by the selected Levi graph itself: every selected four-edge
path produces two distinct chamber triples of gallery signature (1,2,3), each
worth q=5 common apartments by Pass5140.

For m=21,n1=33 and maximum selected Levi degree 3, if n_i is the total number
of degree-i selected Levi vertices, then
  n1+n2=9,  n2+3 n3=33,
so (n1,n2,n3) is one of (0,9,8),(3,6,9),(6,3,10),(9,0,11).
Pass5148's deletion constraint forces every leaf to attach to degree 3.
A degree-2 vertex therefore centers at least one selected four-edge path.
A degree-3 vertex with zero/one leaf neighbor centers at least 3/1 such paths
(respectively; stronger values occur when its nonleaf neighbors have degree 3).
This gives a uniform P4>=6, already enough: N_123>=2P4>=12.
"""
from __future__ import annotations
import json, math
from fractions import Fraction
from pathlib import Path

ROOT=Path(__file__).resolve().parents[1]
OUT=ROOT/'data/PART_W33_PASS5158_Q5_CUBIC_LEADER22_PATH_CLOSURE.json'


def degree_profiles():
    out=[]
    for n3 in range(0,22):
        n2=33-3*n3
        n1=9-n2
        if n1>=0 and n2>=0 and n1+2*n2+3*n3==42:
            out.append((n1,n2,n3))
    assert out==[(0,9,8),(3,6,9),(6,3,10),(9,0,11)]
    return out


def conservative_p4_lower(profile):
    """Very conservative lower bound on selected Levi 4-edge paths.

    Each degree-2 center has no leaf neighbor (leaf--2 is forbidden), so its two
    neighboring degree factors (d-1) are >=1 and it centers >=1 path.
    For degree-3 centers, allocating two leaves to a center can suppress its
    guaranteed contribution to zero; with <=1 leaf it contributes >=1.  We only
    need a weak global lower bound, so maximize the number of suppressed
    degree-3 centers by spending two leaves apiece.
    """
    n1,n2,n3=profile
    suppressed=min(n3,n1//2)
    remaining=n3-suppressed
    # If one leaf remains after making suppressed centers, spend it on one
    # remaining center; that center still contributes >=1.  Thus every remaining
    # degree-3 center contributes at least one under this deliberately weak bound.
    return n2+remaining


def main():
    profiles=degree_profiles()
    rows=[]
    for p in profiles:
        lb=conservative_p4_lower(p)
        rows.append({'n1':p[0],'n2':p[1],'n3':p[2],'P4_lower':lb})
    # The deliberately weak degree-only bound is already much stronger than needed.
    p4=min(r['P4_lower'] for r in rows)
    assert p4>=6
    n123=2*p4
    assert n123>=12

    # Pass5148 sharp sector: pairwise bound -439 and N112>=48.
    pair_bound=-439
    n112=48
    triple_mass=25*n112+5*n123
    cubic=Fraction(pair_bound,1)+Fraction(6,7)*triple_mass
    integer_lb=(cubic.numerator+cubic.denominator-1)//cubic.denominator
    assert triple_mass>=1260
    assert cubic>=641
    assert integer_lb>=641>625

    # Pointwise parity polynomial used by Pass5142/5148; apartment occupancy <=8.
    slack=[]
    for r in range(9):
        lhs=7*(r&1)
        rhs=7*r-14*math.comb(r,2)+6*math.comb(r,3)
        assert lhs>=rhs
        slack.append(lhs-rhs)

    out={
      'pass':5158,
      'status':'THEOREM_Q5_STRICT_COUNTEREXAMPLE_LEADER_AT_LEAST_22',
      'q':5,'leader_size_closed':21,'target_distance':625,
      'sharp_sector_input':{'m':21,'N1':33,'pair_weight_lower_bound':pair_bound,'N112_lower':n112},
      'degree_profiles':rows,
      'selected_four_edge_paths_lower':p4,
      'N123_injection':'Every selected four-edge Levi path e0-e1-e2-e3 gives the two distinct triples {e0,e1,e3} and {e0,e2,e3}, both with gallery signature (1,2,3). Levi girth eight makes the missing geodesic edge unique, so these triples are not multiply generated by different selected four-edge paths.',
      'N123_lower':n123,
      'triple_intersection_mass_lower':triple_mass,
      'cubic_weight_lower_bound_exact':str(cubic),
      'integer_weight_lower_bound':integer_lb,
      'parity_minorant_slack_r0_to_r8':slack,
      'conclusion':'Pass5145 closed leader 20 and Pass5148 reduced leader 21 to N1=33. The selected four-edge-path contribution supplies at least 60 additional triple-intersection units beyond Pass5148, raising the cubic weight bound to at least 641. Hence every q5 apartment-code word of weight <625 has minimum chamber leader at least 22.',
      'boundary':'This closes leader 21 only. The q5/all-q minimum-distance theorem remains open for leaders >=22 and the weight-625 equality shell remains unclassified.'
    }
    OUT.write_text(json.dumps(out,indent=2)+'\n')
    print(json.dumps(out,indent=2))

if __name__=='__main__':main()
