#!/usr/bin/env python3
"""Pass9197-9204: exact E6^4 carrier-centralizer image on the W33 root-shadow line.

The rank-24 root-shadow theorem found that N(E6^4) sees exactly one W(3,3)
line.  This pass computes the quotient action of two explicit centralizing
subgroups:
  (i) four independent local order-9 E6 phases; and
  (ii) all signed monomial automorphisms of the tetracode glue.
Together they generate the full line stabilizer in Sp(4,3), hence the full
projective W33 line stabilizer 3^3:S4 of order 648.
"""
from __future__ import annotations
import itertools, json, sys
from collections import deque
from pathlib import Path
import numpy as np
from sympy import Matrix, eye, zeros

ROOT=Path(__file__).resolve().parents[1]
sys.path.insert(0,str(ROOT/'analysis'))
import w33_rank24_root_shadow_core as rs
OUT=ROOT/'data/PART_W33_PASS9197_9204_E6_CENTRALIZER_LINE_STABILIZER.json'
P=3
QG=np.array([[1,0,2,2],[0,1,2,1]],dtype=np.int64)%P

def rref_key(a):
 a=np.array(a,dtype=np.int64)%P;m,n=a.shape;r=0
 for c in range(n):
  q=next((i for i in range(r,m) if a[i,c]),None)
  if q is None: continue
  a[[r,q]]=a[[q,r]];a[r]=a[r]*pow(int(a[r,c]),-1,P)%P
  for i in range(m):
   if i!=r and a[i,c]:a[i]=(a[i]-a[i,c]*a[r])%P
  r+=1
 return tuple(tuple(int(x) for x in row) for row in a[:r])

def key(a): return (np.asarray(a,dtype=np.int64)%P).astype(np.uint8).tobytes()
def closure(gens):
 I=np.eye(gens[0].shape[0],dtype=np.int64)%P;D={key(I):I};q=deque([I])
 while q:
  a=q.popleft()
  for b in gens:
   c=a@b%P;k=key(c)
   if k not in D:D[k]=c;q.append(c)
 return list(D.values())

def main():
 E6=rs.E6
 w=Matrix(np.loadtxt(ROOT/'analysis/_e6_ord9.txt',dtype=np.int64).tolist())
 b=Matrix(np.loadtxt(ROOT/'analysis/_niemeier_e6_4_basis.txt',dtype=np.int64).tolist())
 gram=Matrix(np.loadtxt(ROOT/'analysis/_niemeier_e6_4_gram.txt',dtype=np.int64).tolist())
 mz=E6*w*E6.inv();a=zeros(24)
 for k in range(4):a[6*k:6*k+6,6*k:6*k+6]=mz
 x=b.T.inv()*a*b.T
 h,j=rs.quotient_form(x,gram)
 # right inverse to quotient map
 piv=None
 for cols in itertools.combinations(range(24),4):
  try: ri=rs.inv_mod(h[:,cols],P);piv=cols;break
  except ValueError: pass
 assert piv is not None
 u=np.zeros((24,4),dtype=np.int64);u[list(piv),:]=ri
 def induced(y):
  Y=np.array(y.tolist(),dtype=np.int64)%P;m=h@Y@u%P
  assert np.array_equal(m@h%P,h@Y%P)
  assert np.array_equal(m.T@j@m%P,j)
  return m
 # Four local order-9 phases.  Their quotient image is exactly 3^3.
 phases=[]
 for comp in range(4):
  aa=zeros(24)
  for k in range(4):aa[6*k:6*k+6,6*k:6*k+6]=mz if k==comp else eye(6)
  y=b.T.inv()*aa*b.T
  assert all(v.q==1 for v in y) and y*x==x*y
  phases.append(induced(y))
 phase_group=closure(phases);assert len(phase_group)==27
 # Signed tetracode monomial automorphisms: 48 lifts, all 24 block permutations.
 qkey=rref_key(QG);mon=[];permset=set()
 for perm in itertools.permutations(range(4)):
  for signs in itertools.product([1,2],repeat=4):
   m4=np.zeros((4,4),dtype=np.int64)
   for src,dst in enumerate(perm):m4[src,dst]=signs[src]
   if rref_key(QG@m4)!=qkey:continue
   yy=zeros(24)
   for src,dst in enumerate(perm):
    s=1 if signs[src]==1 else -1
    yy[6*dst:6*dst+6,6*src:6*src+6]=s*eye(6)
   y=b.T.inv()*yy*b.T
   assert all(v.q==1 for v in y) and y*x==x*y
   mon.append(induced(y));permset.add(perm)
 assert len(mon)==48 and len(permset)==24
 mon_group=closure(mon);assert len(mon_group)==48
 full=closure(phases+mon);assert len(full)==1296
 # Projectivize by +/-I: 648 classes.
 pkeys=set()
 for m in full:pkeys.add(min(key(m),key((-m)%P)))
 assert len(pkeys)==648
 # Recover one visible quotient point per E6 block and verify S4 action on the line.
 roots6=rs.e6_roots();binv=b.T.inv();line=[]
 for comp in range(4):
  q=None
  for rv in roots6:
   amb=zeros(24,1);amb[6*comp:6*comp+6,0]=E6*Matrix(rv);z=binv*amb
   q0=rs.projective((h@(np.array([int(v) for v in z],dtype=np.int64)%P))%P)
   if q0 is not None:q=q0;break
  assert q is not None;line.append(q)
 assert rs.is_line(line,j)
 perms=set()
 for m in full:
  image=[]
  for q in line:
   qq=rs.projective((m@np.array(q,dtype=np.int64))%P);image.append(line.index(qq))
  perms.add(tuple(image))
 assert len(perms)==24
 out={
  'schema':'w33.pass9197_9204.e6_centralizer_line_stabilizer.v1','status':'PASS','passes':'9197-9204',
  'local_phase_image_order':27,
  'tetracode_monomial_lifts':48,
  'block_permutation_image_order':24,
  'sp4_line_stabilizer_image_order':1296,
  'projective_line_stabilizer_image_order':648,
  'projective_structure':'3^3:S4',
  'theorem':'The explicit carrier-centralizing subgroup generated by the four local E6 order-9 phases and the signed tetracode monomial automorphisms maps onto the entire W(3,3) line stabilizer. Its image has order 1296 in Sp(4,3) and 648 projectively; the 3^3 kernel comes from local phase differences and the four root-shadow points carry the full S4 action.',
  'other_carriers':{'A2^12':'any carrier centralizer image preserves its four-point root shadow, hence lies in a conjugate 648 line stabilizer; exact image not claimed here','E8^3':'the root shadow is all 40 W33 points, so support alone imposes no proper line-stabilizer bound'},
  'claim_boundary':'Exact for the exhibited E6^4 centralizing subgroup and its quotient image; because that image already equals the full ambient W33 line stabilizer, no larger projective image preserving the line is possible.'}
 OUT.write_text(json.dumps(out,indent=2,sort_keys=True)+'\n');print(json.dumps({'status':'PASS','phase':27,'Sp_line':1296,'PSp_line':648,'line_action':24}))
 return 0
if __name__=='__main__':raise SystemExit(main())
