#!/usr/bin/env python3
"""Pass5378: the complete all-odd footprint minimum shell spans the full code.

Pass5189 already proves, for every prime power q, that the binary incidence-dual
C_W^perp has minimum distance 2(q+1), and that its complete minimum shell is
exactly the set of dual grids H union H^perp, one for each P-component.  Hence
the minimum shell has q^2(q^2+1)/2 words.

Pass5376 proves the missing odd-q span theorem:

    im_2(F)=C_W^perp.

But the columns of F are exactly the Pass5189 dual-grid minimum words.  Thus,
for every odd prime power q, the complete minimum shell spans the entire code.
Equivalently the footprint code is

    [(q+1)(q^2+1), q(q^2+1)/2, 2(q+1)]_2

and is generated by a single PSp4(q)-orbit consisting of all of its minimum
codewords.

This is strictly stronger than the old q=5-only spanning statement in Pass5189.
"""
from __future__ import annotations
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
OUT=ROOT/'data/PART_W33_PASS5378_FOOTPRINT_CODE_MINIMUM_ORBIT.json'

def row(q:int)->dict[str,int]:
    assert q%2==1 and q>=3
    n=(q+1)*(q*q+1);k=q*(q*q+1)//2;d=2*(q+1);b=q*q*(q*q+1)//2
    assert d<n and 0<k<n
    return {'q':q,'length':n,'dimension':k,'minimum_distance':d,
      'complete_minimum_shell_size':b,'minimum_word_weight':d,
      'minimum_shell_spans_code':True}

def main()->None:
    rows={str(q):row(q) for q in (3,5,7,9,11,13,17,19,25,27,49)}
    out={'pass':5378,'status':'THEOREM_ALLODD_COMPLETE_MINIMUM_SHELL_SPANS_FOOTPRINT_CODE',
      'domain':'all odd prime powers q',
      'code':'C_F=im_2(F)=C_W^perp',
      'parameters':'[(q+1)(q^2+1), q(q^2+1)/2, 2(q+1)]_2',
      'complete_minimum_shell':'Exactly the q^2(q^2+1)/2 dual grids H union H^perp / P-component blocks.',
      'spanning_theorem':'The complete minimum shell is exactly the column set of F, and Pass5376 proves its span equals C_W^perp.',
      'repo_inputs':['Pass5189: all-q minimum distance and complete minimum-shell classification.','Pass5376: all-odd equality im_2(F)=C_W^perp.'],
      'literature_crosscheck':{
        'authors':'Jon-Lark Kim, Keith E. Mellinger, Leo Storme',
        'title':'Small weight codewords in LDPC codes defined by (dual) classical generalized quadrangles',
        'journal':'Designs, Codes and Cryptography 42 (2007), 73--92',
        'doi':'10.1007/s10623-006-9017-6',
        'result':'The W(q) LDPC code has minimum distance 2(q+1); its minimum words are the hyperbolic-quadric/regulus dual grids.'
      },
      'sample_parameters':rows,
      'boundary':'This classifies and spans the minimum shell for the point incidence-dual / footprint image. It does not determine the minimum distance of the distinct footprint-kernel K0 or the q=11 dual weight-20 problem.'}
    OUT.write_text(json.dumps(out,indent=2,sort_keys=True)+'\n');print(json.dumps(out,indent=2,sort_keys=True))
if __name__=='__main__':main()
