#!/usr/bin/env python3
"""Pass 4649 — full split-octonion triality closure and W33 reconstruction.

Starting only from the W33-derived plus-type V8, the deterministic PSp(4,3)
embedding of Pass4477/4641, split-octonion triality tau, and octonion conjugation
sigma, this verifier computes the permutation groups on the 405 outer D4 objects
(135 singular points + 135 left annihilators + 135 right annihilators).

It proves:
  <PSp,tau> has order 522,547,200 = |Omega_8^+(2)|*3;
  the type-preserving subgroup generated by the three triality-conjugate PSp
  copies has order 174,182,400 = |Omega_8^+(2)|;
  adjoining conjugation gives order 1,045,094,400 = |Omega_8^+(2)|*6,
  with diagram quotient S3.

It then computes the pairwise/triple intersections of the three PSp copies.
A pairwise intersection has order 216 and fixes pointwise one anisotropic F2
2-plane (three nonsingular vectors). The orbit of that plane contains exactly
40 disjoint anisotropic planes partitioning all 120 nonsingular vectors. The
mutual-polar-orthogonality graph on those 40 planes is exactly SRG(40,12,2,4),
thereby reconstructing W(3,3) from triality-subgroup intersection geometry.
"""
from __future__ import annotations

import json
from collections import Counter
from itertools import combinations
from pathlib import Path

import numpy as np
from sympy.combinatorics import Permutation, PermutationGroup

from w33_pass4472_4479_apartment_module_thermo_ihara_pauli import (
    build_geometry, build_line_perm, perm_group, transvection_matrix,
)
from w33_pass4587_w33_derived_d4_triality import rank_basis_int, span
from w33_pass4641_split_octonion_triality import (
    mask, norm, tup, zmul, zorn_to_hyper_mask,
)

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "data/PART_W33_PASS4649_FULL_TRIALITY_GROUP_INTERSECTIONS.json"


def hyper_to_zorn_mask(hm):
    h = tup(hm)
    return mask((h[0], h[1], h[2], h[4], h[6], h[3], h[5], h[7]))


def permute_mask40(m, p, j):
    out = 0
    x = int(m)
    while x:
        lsb = x & -x
        i = lsb.bit_length() - 1
        out |= 1 << p[i]
        x ^= lsb
    return min(out, out ^ j)


def zconj(m):
    z = list(tup(m))
    z[0], z[1] = z[1], z[0]
    return mask(z)


def main():
    pts, pidx, lines, lidx, _, Astar, _, _, _ = build_geometry()
    Astar = np.asarray(Astar, dtype=np.uint8)

    all_trans = [build_line_perm(transvection_matrix(v), pts, pidx, lines, lidx) for v in pts]
    selected = []
    line_group = {tuple(range(40))}
    for p in all_trans:
        trial = perm_group(selected + [p])
        if len(trial) > len(line_group):
            selected.append(p)
            line_group = trial
        if len(line_group) == 25920:
            break
    assert len(selected) == 5 and len(line_group) == 25920

    n = 40
    j = (1 << n) - 1
    cols = []
    for c in range(n):
        m = 0
        for r in np.flatnonzero(Astar[:, c]):
            m |= 1 << int(r)
        cols.append(m)
    edges = [(i, k) for i in range(n) for k in range(i + 1, n) if Astar[i, k]]
    B9 = rank_basis_int([cols[i] ^ cols[k] for i, k in edges])
    V9 = set(span(B9))
    assert len(B9) == 9 and j in V9
    rep = lambda x: min(int(x), int(x) ^ j)
    reps = {rep(x) for x in V9}
    q = lambda x: (rep(x).bit_count() // 4) & 1
    polar = lambda x, y: q(x) ^ q(y) ^ q(rep(x) ^ rep(y))
    singular_v = sorted(x for x in reps if x and q(x) == 0)
    assert len(singular_v) == 135

    hb = []
    for _ in range(4):
        cand = [x for x in singular_v if x not in hb and all(polar(x, z) == 0 for z in hb)]
        e = cand[0]
        f = next(y for y in singular_v if y != e and all(polar(y, z) == 0 for z in hb) and polar(e, y) == 1)
        hb.extend([e, f])
    assert len(rank_basis_int(hb)) == 8

    coord_to_v = {}
    v_to_coord = {}
    for c in range(256):
        x = 0
        for i, b in enumerate(hb):
            if (c >> i) & 1:
                x ^= b
        rr = rep(x)
        coord_to_v[c] = rr
        v_to_coord[rr] = c
        h = tup(c)
        assert q(rr) == ((h[0]*h[1] + h[2]*h[3] + h[4]*h[5] + h[6]*h[7]) & 1)

    zorn_gen_maps = []
    for p in selected:
        hyper_map = []
        for c in range(256):
            im = permute_mask40(coord_to_v[c], p, j)
            hyper_map.append(v_to_coord[im])
        zmap = tuple(hyper_to_zorn_mask(hyper_map[zorn_to_hyper_mask(m)]) for m in range(256))
        assert all(norm(tup(zmap[m])) == norm(tup(m)) for m in range(256))
        zorn_gen_maps.append(zmap)

    sing_z = sorted(m for m in range(1, 256) if norm(tup(m)) == 0)
    assert len(sing_z) == 135
    L, R = {}, {}
    zero = (0,) * 8
    elems = [tup(m) for m in range(256)]
    for x in sing_z:
        xt = tup(x)
        L[x] = frozenset(mask(y) for y in elems if zmul(xt, y) == zero)
        R[x] = frozenset(mask(y) for y in elems if zmul(y, xt) == zero)
        assert len(L[x]) == len(R[x]) == 16
    L_lookup = {S: x for x, S in L.items()}
    R_lookup = {S: x for x, S in R.items()}
    sidx = {x: i for i, x in enumerate(sing_z)}

    type_gens = []
    for zm in zorn_gen_maps:
        perm = [None] * 405
        for x in sing_z:
            i = sidx[x]
            lx = L_lookup[frozenset(zm[y] for y in L[x])]
            rx = R_lookup[frozenset(zm[y] for y in R[x])]
            perm[i] = sidx[zm[x]]
            perm[135 + i] = 135 + sidx[lx]
            perm[270 + i] = 270 + sidx[rx]
        type_gens.append(Permutation(perm))
    G0 = PermutationGroup(type_gens)
    assert G0.order() == 25920

    tau_arr = [None] * 405
    for x in sing_z:
        i = sidx[x]
        tau_arr[i] = 135 + i
        tau_arr[135 + i] = 270 + i
        tau_arr[270 + i] = i
    tau = Permutation(tau_arr)
    assert tau.order() == 3

    G1_gens = [tau * g * (tau**2) for g in type_gens]
    G2_gens = [(tau**2) * g * tau for g in type_gens]
    G1 = PermutationGroup(G1_gens)
    G2 = PermutationGroup(G2_gens)
    assert G1.order() == G2.order() == 25920

    omega = PermutationGroup(type_gens + G1_gens + G2_gens)
    assert omega.order() == 174182400
    assert PermutationGroup(type_gens + G1_gens).order() == 174182400
    omega3 = PermutationGroup(type_gens + [tau])
    assert omega3.order() == 522547200

    for a in range(256):
        for b in range(256):
            assert zconj(mask(zmul(tup(a), tup(b)))) == mask(zmul(tup(zconj(b)), tup(zconj(a))))
    sigma_arr = [None] * 405
    for x in sing_z:
        i = sidx[x]
        xc = zconj(x)
        jx = sidx[xc]
        assert frozenset(zconj(y) for y in L[x]) == R[xc]
        assert frozenset(zconj(y) for y in R[x]) == L[xc]
        sigma_arr[i] = jx
        sigma_arr[135 + i] = 270 + jx
        sigma_arr[270 + i] = 135 + jx
    sigma = Permutation(sigma_arr)
    assert sigma.order() == 2
    assert sigma * tau * sigma == tau**2
    full = PermutationGroup(type_gens + [tau, sigma])
    assert full.order() == 1045094400

    G1.schreier_sims(); G2.schreier_sims()
    inter01 = [g for g in G0.generate_schreier_sims() if G1.contains(g)]
    inter012 = [g for g in inter01 if G2.contains(g)]
    I01 = PermutationGroup(inter01)
    I012 = PermutationGroup(inter012)
    assert I01.order() == 216
    assert I012.order() == 6
    pair_orders = Counter(int(g.order()) for g in I01.generate_schreier_sims())
    triple_orders = Counter(int(g.order()) for g in I012.generate_schreier_sims())
    assert pair_orders == Counter({12:108,4:54,3:26,6:18,2:9,1:1})
    assert triple_orders == Counter({2:3,3:2,1:1})
    assert I01.center().order() == 3 and I01.derived_subgroup().order() == 54
    assert (not I012.is_abelian) and I012.center().order() == 1 and I012.derived_subgroup().order() == 3

    def lincols(g):
        arr = list(g.array_form)
        if len(arr) < 405:
            arr += list(range(len(arr), 405))
        cols8 = []
        for i in range(8):
            z = hyper_to_zorn_mask(1 << i)
            im = arr[sidx[z]]
            assert 0 <= im < 135
            cols8.append(zorn_to_hyper_mask(sing_z[im]))
        return tuple(cols8)

    def apply(cols8, m):
        out = 0
        for i in range(8):
            if (m >> i) & 1:
                out ^= cols8[i]
        return out

    def qh(m):
        h = tup(m)
        return (h[0]*h[1] + h[2]*h[3] + h[4]*h[5] + h[6]*h[7]) & 1

    def ph(a, b):
        return qh(a) ^ qh(b) ^ qh(a ^ b)

    inter_cols = [lincols(g) for g in inter01]
    nons = [m for m in range(1, 256) if qh(m) == 1]
    fixed = [m for m in nons if all(apply(c, m) == m for c in inter_cols)]
    assert len(fixed) == 3 and fixed[0] ^ fixed[1] ^ fixed[2] == 0
    base_plane = frozenset(fixed)

    planes = set()
    setwise = pointwise = 0
    for g in G0.generate_schreier_sims():
        c = lincols(g)
        im = frozenset(apply(c, m) for m in base_plane)
        planes.add(im)
        if im == base_plane:
            setwise += 1
            if all(apply(c, m) == m for m in base_plane):
                pointwise += 1
    assert len(planes) == 40
    assert (setwise, pointwise) == (648, 216)
    assert len(set().union(*planes)) == 120
    assert all(len(A & B) == 0 for A, B in combinations(planes, 2))

    plist = list(planes)
    AW = np.zeros((40, 40), dtype=np.int64)
    cross_orth = Counter()
    for i, j2 in combinations(range(40), 2):
        z = sum(1 for a in plist[i] for b in plist[j2] if ph(a, b) == 0)
        cross_orth[z] += 1
        if z == 9:
            AW[i, j2] = AW[j2, i] = 1
    assert cross_orth == Counter({3:540,9:240})
    assert set(map(int, AW.sum(axis=1))) == {12}
    adj, non = Counter(), Counter()
    for i, j2 in combinations(range(40), 2):
        c = int(AW[i] @ AW[j2])
        (adj if AW[i,j2] else non)[c] += 1
    assert adj == Counter({2:240}) and non == Counter({4:540})

    out = {
        "pass": 4649,
        "triality_closure": {
            "PSp_order": 25920,
            "three_triality_conjugates": 3,
            "two_conjugates_generate_type_preserving_order": 174182400,
            "type_preserving_group": "Omega_8^+(2)",
            "PSp_plus_order3_triality_order": 522547200,
            "PSp_plus_order3_triality_group": "Omega_8^+(2):3",
            "octonion_conjugation_order": 2,
            "diagram_relation": "sigma*tau*sigma=tau^-1",
            "full_group_order": 1045094400,
            "full_group": "Omega_8^+(2):S3",
            "diagram_quotient": "S3"
        },
        "PSp_intersections": {
            "pairwise_order": 216,
            "pairwise_center_order": 3,
            "pairwise_derived_order": 54,
            "pairwise_element_order_census": {str(k): int(v) for k,v in sorted(pair_orders.items())},
            "triple_order": 6,
            "triple_isomorphism": "S3",
            "triple_element_order_census": {str(k): int(v) for k,v in sorted(triple_orders.items())}
        },
        "anisotropic_plane_reconstruction": {
            "pairwise_intersection_fixed_nonsingular_vectors": 3,
            "fixed_vectors_form_anisotropic_2space_nonzero_shell": True,
            "plane_orbit_size": 40,
            "setwise_stabilizer_order": 648,
            "pointwise_stabilizer_order": 216,
            "partition_of_120_nonsingular_vectors": "40 x 3",
            "pair_cross_orthogonality_counts": {"3": 540, "9": 240},
            "total_orthogonality_graph": "SRG(40,12,2,4)",
            "adjacent_common_neighbors": 2,
            "nonadjacent_common_neighbors": 4,
            "identification": "W(3,3) reconstructed from triality-conjugate PSp intersection geometry"
        },
        "theorem": "The explicit W33-derived octonion triality closes to Omega_8^+(2):S3. Pairwise triality-conjugate PSp intersections recover a 40-plane partition of the 120 anisotropic vectors whose total-orthogonality graph is W33 itself.",
        "literature_context": "Pellegrini--Tamburini Bellani, J. Group Theory 2022: order-three D4 triality of P Omega_8^+(q) in Steinberg generators. The q=2 subgroup/intersection computation here is explicit and independent.",
        "boundary": "Finite group/building theorem only; no physical triality or particle interpretation."
    }
    OUT.write_text(json.dumps(out, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    print(json.dumps(out, indent=2, sort_keys=True))
    return 0

if __name__ == "__main__":
    raise SystemExit(main())
