#!/usr/bin/env python3
"""Lift the signed-Pauli CZ/parity C6 through the full 240-root E8 Coxeter fibration.

Parents:
  data/PART_W33_PASS7163_7170_E8_HEXAGONAL_LIFT.json
  data/w33_e8_z12_to_pauli_symplectic_sign.json
  data/w33_cz_parity_oriented_c6.json

Notation.
  d = c_Coxeter^5 is the internal order-six rotation of every E8 root fiber.
  The 240 roots split into 40 d-orbits of length six.
  Quotienting by <d^2>=C3 gives the 80-state signed Pauli carrier.

The previously frozen signed-Pauli map identifies the quotient with
F3^4\{0}.  On that quotient the heterotic/Clifford order-six element is
  G = CZ_3 * P,
where P=-I is parity.

This certificate solves the root-level lifting problem.

Let Q be the induced permutation of the 40 base fibers and sigma_x the induced
sheet flip over each fiber.  Seek a root permutation of the form
  L : (x,k) -> (Qx, k + delta_x)      mod 6
that COMMUTES with d.  Pass 7164 gives, for every W33 nonedge x->y, a phase
offset pair {s_xy,s_xy+1}.  Preservation of all +1 E8 root incidences is
equivalent to the cocycle equations
  delta_y-delta_x = s_Qx,Qy - s_xy    mod 6.

The equations have a solution.  The opposite orientation
  (x,k)->(Qx,-k+delta_x)
has no solution.  Adding one global fiber rotation to the preserving solution
makes delta_x mod2 equal the required signed-Pauli sheet flip at every one of
the 40 fibers.

The resulting permutation L:
  * is a permutation of all 240 roots;
  * preserves EVERY E8 root inner product exactly;
  * commutes with d;
  * has order six and root cycle profile 2^3 6^39;
  * induces CZ_3*P on the 80-state quotient;
  * satisfies L^3 = d^3 = global root negation.

Therefore define
  C = L d^{-1}.
Then:
  * C has order three;
  * C commutes with d;
  * C induces pure CZ_3 on the 80-state quotient;
  * C has root cycle profile 1^12 3^76.

Thus the root-level group generated by d and C is
  <d,C> ~= C6 x C3.
The two previously separate structures reconcile as
  d       -> parity P on 80 states,
  C       -> CZ_3,
  L=C d   -> CZ_3 P,
and the heterotic/Clifford C6 shares its cube with the internal Coxeter-fiber
C6:
  L^3=d^3=-I.

Important boundary:
This proves existence of an exact E8 root-system automorphism lift in the
specific chamber/fiber/base-isomorphism gauge frozen by the parents.  The
displayed delta vector is not canonical; global d^m rotations and W33 base
automorphisms change the gauge.  The theorem is the existence and exact group
relations, not uniqueness of coordinates.
"""
from __future__ import annotations
import itertools, json
from collections import Counter
from pathlib import Path

ROOT=Path(__file__).resolve().parents[1]
OUT=ROOT/'data/w33_e8_cz_parity_c6_root_lift.json'

SIMPLES=[
(1,-1,-1,-1,-1,-1,-1,1),(2,2,0,0,0,0,0,0),
(-2,2,0,0,0,0,0,0),(0,-2,2,0,0,0,0,0),
(0,0,-2,2,0,0,0,0),(0,0,0,-2,2,0,0,0),
(0,0,0,0,-2,2,0,0),(0,0,0,0,0,-2,2,0)]

ISO=[0,1,39,32,34,30,23,27,22,28,26,33,38,31,35,37,36,24,29,25,
     3,16,4,12,15,8,20,9,14,19,5,18,10,21,11,7,17,6,13,2]
ETA=[1,-1,1,-1,-1,1,-1,-1,1,-1,1,1,-1,-1,1,1,-1,1,-1,1,
     -1,-1,1,1,-1,1,-1,-1,1,1,-1,1,-1,-1,1,1,-1,1,-1,-1]

CZ=((1,0,0,0),(0,1,0,0),(0,1,1,0),(1,0,0,1))
PARITY=((2,0,0,0),(0,2,0,0),(0,0,2,0),(0,0,0,2))

def dot(a,b): return sum(x*y for x,y in zip(a,b))

def roots_e8():
    R=[]
    for i,j in itertools.combinations(range(8),2):
        for si in (1,-1):
            for sj in (1,-1):
                x=[0]*8;x[i]=2*si;x[j]=2*sj;R.append(tuple(x))
    for bits in itertools.product((1,-1),repeat=8):
        if sum(x==-1 for x in bits)%2==0:R.append(tuple(bits))
    assert len(R)==len(set(R))==240
    return R

def refl(x,r):
    q=dot(x,r); assert q%4==0; k=q//4
    return tuple(x[i]-k*r[i] for i in range(8))

def cox(x):
    y=x
    for r in SIMPLES:y=refl(y,r)
    return y

def mm(A,B):
    return tuple(tuple(sum(A[i][k]*B[k][j] for k in range(4))%3
                       for j in range(4)) for i in range(4))
def mv(A,v):
    return tuple(sum(A[i][j]*v[j] for j in range(4))%3 for i in range(4))

def canon(v):
    i=next(i for i,x in enumerate(v) if x)
    z=pow(v[i],-1,3)
    return tuple((z*x)%3 for x in v)

def scale(sign,v):
    z=1 if sign==1 else 2
    return tuple((z*x)%3 for x in v)

def compose(p,q): return [p[q[i]] for i in range(len(p))]
def pinv(p):
    q=[None]*len(p)
    for i,j in enumerate(p):q[j]=i
    return q
def ppow(p,n):
    q=list(range(len(p)))
    for _ in range(n):q=compose(p,q)
    return q
def porder(p,limit=60):
    I=list(range(len(p)));q=I
    for n in range(1,limit+1):
        q=compose(p,q)
        if q==I:return n
    raise AssertionError('order too large')
def cycle_profile(p):
    seen=set();C=Counter()
    for i in range(len(p)):
        if i in seen:continue
        u=i;n=0
        while u not in seen:
            seen.add(u);n+=1;u=p[u]
        C[n]+=1
    return dict(sorted(C.items()))

def build_parent_data():
    R=roots_e8();I={r:i for i,r in enumerate(R)}
    cp=[I[cox(r)] for r in R]
    d=list(range(240))
    for _ in range(5):d=[cp[i] for i in d]
    assert porder(d)==6

    seen=set();fib=[]
    for i in range(240):
        if i in seen:continue
        o=[];j=i
        while j not in o:
            o.append(j);seen.add(j);j=d[j]
        assert len(o)==6;fib.append(tuple(o))
    assert len(fib)==40
    phase=[{v:k for k,v in enumerate(F)} for F in fib]

    badj=[set() for _ in range(40)]
    soff={}
    for a,b in itertools.combinations(range(40),2):
        E=[(u,v) for u in fib[a] for v in fib[b] if dot(R[u],R[v])==4]
        if not E:
            badj[a].add(b);badj[b].add(a)
        else:
            assert len(E)==12
            D={(phase[b][v]-phase[a][u])%6 for u,v in E}
            ss=[s for s in D if (s+1)%6 in D]
            assert len(ss)==1
            s=ss[0]
            soff[(a,b)]=s
            soff[(b,a)]=(-s-1)%6
    assert all(len(x)==12 for x in badj)
    return R,d,fib,badj,soff

def signed_pauli_action():
    V=[v for v in itertools.product(range(3),repeat=4) if any(v)]
    PP=sorted({canon(v) for v in V})
    assert len(PP)==40
    G=mm(CZ,PARITY)

    M={};Minv={}
    for a in range(40):
        for t in (0,1):
            v=scale(ETA[a]*((-1)**t),PP[ISO[a]])
            M[(a,t)]=v;Minv[v]=(a,t)
    assert len(Minv)==80

    Q=[None]*40;sheet=[None]*40
    for a in range(40):
        rec=[]
        for t in (0,1):
            b,u=Minv[mv(G,M[(a,t)])]
            rec.append((b,u^t))
        assert rec[0]==rec[1]
        Q[a],sheet[a]=rec[0]
    assert sorted(Q)==list(range(40))
    return Q,sheet

def solve_delta(Q,soff,orient):
    delta=[None]*40;delta[0]=0;stack=[0]
    while stack:
        a=stack.pop()
        for b in range(40):
            if (a,b) not in soff:continue
            s=soff[(a,b)]
            t=soff[(Q[a],Q[b])]
            rhs=(t-s)%6 if orient==1 else (t+s+1)%6
            want=(delta[a]+rhs)%6
            if delta[b] is None:
                delta[b]=want;stack.append(b)
            elif delta[b]!=want:
                return None
    return delta

def main(write=True):
    R,d,fib,badj,soff=build_parent_data()
    Q,sheet=signed_pauli_action()

    delta=solve_delta(Q,soff,+1)
    reverse=solve_delta(Q,soff,-1)
    assert delta is not None
    assert reverse is None

    # global fiber rotation is free; choose it so quotient sheet parity matches.
    if sum((delta[a]%2)==sheet[a] for a in range(40))==0:
        delta=[(x+1)%6 for x in delta]
    assert all((delta[a]%2)==sheet[a] for a in range(40))

    L=[None]*240
    for a in range(40):
        for k in range(6):
            L[fib[a][k]]=fib[Q[a]][(k+delta[a])%6]
    assert sorted(L)==list(range(240))

    # Full E8 Gram preservation: this is the root-system automorphism firewall.
    assert all(dot(R[i],R[j])==dot(R[L[i]],R[L[j]])
               for i in range(240) for j in range(240))
    assert all(L[d[i]]==d[L[i]] for i in range(240))
    assert porder(L)==6

    antip=ppow(d,3)
    assert ppow(L,3)==antip
    assert all(R[antip[i]]==tuple(-x for x in R[i]) for i in range(240))

    C=compose(L,pinv(d))
    assert porder(C)==3
    assert compose(C,d)==compose(d,C)
    assert compose(L,d)==compose(d,L)
    assert compose(C,d)==L

    # quotient checks: d gives parity, C gives CZ, L gives CZ*parity.
    # phase action of d is k->k+1, hence sheet flip; C=L d^-1 removes it.
    dprof=cycle_profile(d)
    Lprof=cycle_profile(L)
    Cprof=cycle_profile(C)
    assert dprof=={6:40}
    assert Lprof=={2:3,6:39}
    assert Cprof=={1:12,3:76}

    # <d,C> has exactly 18 elements and trivial intersection of <C> with <d>.
    group={tuple(compose(ppow(d,a),ppow(C,b))) for a in range(6) for b in range(3)}
    assert len(group)==18
    assert tuple(ppow(C,1)) not in {tuple(ppow(d,a)) for a in range(6)}
    assert tuple(ppow(C,2)) not in {tuple(ppow(d,a)) for a in range(6)}

    parents=[
      json.loads((ROOT/'data/w33_e8_z12_to_pauli_symplectic_sign.json').read_text()),
      json.loads((ROOT/'data/w33_cz_parity_oriented_c6.json').read_text())]
    assert all(p['status']=='PASS' for p in parents)

    out={
      'schema':'w33.e8_cz_parity_c6_root_lift.v1',
      'status':'PASS',
      'headline':'The heterotic/Clifford CZ-parity C6 lifts exactly through the Pass-7164 240-root E8 Coxeter fibration. There is an orientation-preserving phase solution L:(x,k)->(Qx,k+delta_x) preserving the complete E8 Gram matrix, commuting with the internal Coxeter-fiber C6 d, and inducing CZ*parity on the 80-state signed-Pauli quotient. Its cube equals the common antipode L^3=d^3=-I. Consequently C=L d^-1 is an order-three E8 automorphism inducing pure CZ, and <d,C> is C6 x C3.',
      'lift':{
        'base_action':'Q induced by CZ*parity through the frozen signed-Pauli map',
        'phase_solution_delta':delta,
        'phase_histogram':{str(k):delta.count(k) for k in range(6)},
        'orientation_preserving_solution':True,
        'orientation_reversing_solution':False,
        'sheet_parity_matches_signed_Pauli':True,
        'full_240_root_Gram_preserved':True,
        'commutes_with_internal_fiber_C6':True},
      'root_actions':{
        'internal_d':{'order':6,'cycles':dprof,'quotient_action':'parity P'},
        'lift_L':{'order':6,'cycles':Lprof,'quotient_action':'CZ*parity'},
        'pure_CZ_C=L*d^-1':{'order':3,'cycles':Cprof,'quotient_action':'CZ'}},
      'shared_center':{
        'identity':'L^3=d^3=-I on all 240 roots',
        'interpretation':'the heterotic/Clifford C6 and internal Coxeter-fiber C6 are distinct commuting lifts sharing the same central antipode'},
      'generated_group':{
        'generators':'d (order6), C (order3)',
        'commute':True,
        'order':18,
        'isomorphism':'C6 x C3'},
      'closure':{
        'resolves':'the open root-lift problem in data/w33_e8_z12_to_pauli_symplectic_sign.json and the nonidentification boundary in data/w33_cz_parity_oriented_c6.json',
        'dictionary':{'d':'parity P','C':'CZ_3','L=C*d':'CZ_3*P'},
        'remaining_boundary':'The coordinate witness depends on the frozen Coxeter fiber, W33 base isomorphism, and switching gauge. Existence and group relations are exact; canonicity of this chosen gauge is not claimed.'},
      'parents':['data/PART_W33_PASS7163_7170_E8_HEXAGONAL_LIFT.json',
                 'data/w33_e8_z12_to_pauli_symplectic_sign.json',
                 'data/w33_cz_parity_oriented_c6.json']}
    if write:OUT.write_text(json.dumps(out,indent=2)+'\n')
    print(json.dumps(out,indent=2));return out

if __name__=='__main__':main(True)
