#!/usr/bin/env python3
"""Pass5318: the Hoffman/D4 triality quotient on the Klein-Latin PG(3,2) spread.

Pass5300 identifies H/Z(H) with the order-288 even-parastrophe affine group L+
of the Klein V4 Latin square.  Pass5308 identifies the characteristic order-192
W(D4) subgroup N<H, so N/Z has order96.  On the Latin side the corresponding
characteristic subgroup N+ is generated by all 2-power-order elements of L+.

The five PG(3,2) spread lines are row, column, symbol, and the two orthogonal
mates.  N+ fixes the first three lines individually and swaps the two mate lines.
The quotient L+/N+ = C3 is represented by a cyclic parastrophe that acts

    row -> column -> symbol -> row

while fixing each mate line.  Thus the outer D4 triality C3 has an exact Latin
spread action, distinct from the inner S3 quotient of the tomotope96 group.
"""
from __future__ import annotations
import json
from pathlib import Path
from sympy.combinatorics import PermutationGroup

from analysis.w33_pass5300_hoffman576_latin_group_bridge import latin_groups,mapply,rank4

ROOT=Path(__file__).resolve().parents[1]
OUT=ROOT/'data/PART_W33_PASS5318_LATIN_SPREAD_TRIALITY_ACTION.json'
SPREAD=[
  frozenset({1,2,3}),      # row
  frozenset({4,8,12}),     # column
  frozenset({5,10,15}),    # symbol
  frozenset({6,11,13}),    # orthogonal mate 1
  frozenset({7,9,14}),     # orthogonal mate 2
]
NAMES=['row','column','symbol','mate1','mate2']

def key(g,n=16):return tuple(g(i) for i in range(n))
def affine(g):
    t=g(0);A=tuple(g(e)^t for e in (1,2,4,8));assert rank4(A)==4
    assert all(g(x)==(mapply(A,x)^t) for x in range(16));return t,A

def spread_perm(A):
    out=[]
    for L in SPREAD:
        I=frozenset(mapply(A,x) for x in L);out.append(SPREAD.index(I))
    return tuple(out)

def orbit(mats,x):
    O={x};Q=[x]
    while Q:
        a=Q.pop()
        for A in mats:
            b=mapply(A,a)
            if b not in O:O.add(b);Q.append(b)
    return O

def main():
    _,Lp,Lact=latin_groups();assert Lp.order()==288 and len(Lact)==18
    els=list(Lp.generate_schreier_sims())
    Np=PermutationGroup([g for g in els if int(g.order()) in (1,2,4)])
    assert Np.order()==96 and Np.center().order()==1 and Np.derived_subgroup().order()==48
    Nkeys={key(g) for g in Np.generate_schreier_sims()}
    assert all(key((~h)*g*h) in Nkeys for h in Lp.generators for g in Np.generators)

    Nlin={affine(g)[1] for g in Np.generate_schreier_sims()};assert len(Nlin)==6
    Nspread={spread_perm(A) for A in Nlin}
    assert Nspread=={(0,1,2,3,4),(0,1,2,4,3)}

    rem=set(range(1,16));dorbs=[]
    while rem:
        O=orbit(Nlin,next(iter(rem)));dorbs.append(O);rem-=O
    dorbs=sorted(dorbs,key=lambda O:(len(O),min(O)))
    assert dorbs==[
      {1,2,3},{4,8,12},{5,10,15},{6,7,9,11,13,14}
    ]

    full_spread={spread_perm(A) for A in Lact};assert len(full_spread)==6
    assert full_spread=={
      (0,1,2,3,4),(0,1,2,4,3),
      (1,2,0,3,4),(1,2,0,4,3),
      (2,0,1,3,4),(2,0,1,4,3)}

    t=None
    for g in els:
        if key(g) in Nkeys or int(g.order())!=3:continue
        if PermutationGroup(list(Np.generators)+[g]).order()==288:
            t=g;break
    assert t is not None
    At=affine(t)[1];tp=spread_perm(At)
    assert tp==(1,2,0,3,4)

    out={'pass':5318,'status':'THEOREM_D4_TRIALITY_IS_ROW_COLUMN_SYMBOL_C3_ON_KLEIN_MOLS_SPREAD',
      'latin_even_group_order':288,'characteristic_tomotope_kernel_order':96,
      'kernel_structure':'(C2)^4:S3','quotient':'C3',
      'spread_lines':{NAMES[i]:sorted(SPREAD[i]) for i in range(5)},
      'kernel_direction_orbits':[sorted(O) for O in dorbs],
      'kernel_spread_action':['identity','swap(mate1,mate2)'],
      'outer_triality_representative':{'order':3,'linear_columns':list(At),'spread_permutation':list(tp)},
      'outer_triality_action':'row -> column -> symbol -> row; mate1 and mate2 fixed individually',
      'full_spread_action':'C3 on {row,column,symbol} times C2 on {mate1,mate2}',
      'bridge':'Under Pass5300 H/Z ~= L+ and Pass5308 N=W(D4), the quotient H/N=C3 is realized on the Latin side by cyclic parastrophe of row, column, and symbol.',
      'boundary':'This is an affine finite-geometry action theorem. The inner S3 of the tomotope96 group and the outer triality C3 are distinct actions and must not be conflated.'}
    OUT.write_text(json.dumps(out,indent=2)+'\n');print(json.dumps(out,indent=2))
if __name__=='__main__':main()
