#!/usr/bin/env python3
"""W33 branched-torus flat H27 holonomy and Z3 magnetic phase census.

Only a flat connection on pi1=Z² has commuting holonomies. The standard
Heisenberg order-27 central extension measures the obstruction via determinant.
This is finite gauge kinematics, NOT an emergent physical gauge theory.
"""
import json,itertools,collections,sys
from pathlib import Path
import numpy as np
ROOT=Path(__file__).resolve().parents[1];sys.path.insert(0,str(ROOT/"analysis"))
from w33_20261008_h27_h13_five_frontiers import um,mm
OUT=ROOT/"data"/"w33_20261008_torus_H27_flat_flux.json"

def compute():
 pi=json.loads((ROOT/"data/w33_20261008_twenty_apartment_fundamental_group.json").read_text())
 assert pi["final_relator_is_commutator"] and pi["generators_after_Tietze"]==2
 H={v:um(*v) for v in itertools.product(range(3),repeat=3)}
 assert len(H)==27
 census=collections.Counter()
 commuting=[]
 for x,y in itertools.product(H,repeat=2):
  a,b,c=x;d,e,f=y
  curvature=(2*(a*e-b*d))%3
  M=mm(H[x],H[y])-mm(H[y],H[x])
  is_flat=not np.any(M%3)
  assert is_flat==(curvature==0)
  census[curvature]+=1
  if is_flat:commuting.append((x,y))
 assert census=={0:297,1:216,2:216}
 # quotient of Hom(pi1,H27) by simultaneous conjugacy in H27.
 # conjugation acts as center shifts generated by underlying cross products.
 def conjugate(z,x):
  a,b,c=x;d,e,f=z
  return (a,b,(c+2*(d*b-e*a))%3)
 orbit=set()
 for pair in commuting:
  transforms=tuple(sorted({(conjugate(z,pair[0]),conjugate(z,pair[1])) for z in H}))
  orbit.add(transforms)
 assert len(orbit)==105,len(orbit)
 distribution=collections.Counter(len(o) for o in orbit)
 assert distribution=={3:96,1:9},distribution
 # Each rank-one torus has 9 abelian U(1) character values mod 3.
 Z3_H1={((a,b)) for a,b in itertools.product(range(3),repeat=2)}
 assert len(Z3_H1)==9
 return {"pi1":"Z²","H1_mod3":"F3²",
      "Z3_flat_line_bundle_characters":9,
      "nontrivial_Z3_flat_characters":8,
      "H27_group_order":27,
      "all_ordered_H27_holonomy_pairs":729,
      "ordered_holonomy_pair_center_commutator_flux_histogram":dict(census),
      "flat_H27_ordered_holonomy_pairs":297,
      "nonflat_H27_ordered_holonomy_pairs":432,
      "flat_H27_holonomy_conjugacy_classes":105,
      "flat_conjugacy_orbit_length_histogram":dict(distribution),
      "H27_commutator_flux_formula":"2*(a*e-b*d) mod3 for torus cycles (a,b),(d,e)",
      "cup_product_pairing":"standard nondegenerate determinant after 19 elementary CW generator-relator eliminations to one-cell torus model",
      "physics_boundary":"The F3 symplectic intersection/cup form can support Heisenberg magnetic translation phases; flat torus H27 bundles require determinant zero, nonzero central phase signals flux/twisting and cannot be represented as an ordinary flat H27 holonomy pair.",
      "physical_flux_quantization_or_SM_gauge_derived":False}
if __name__=="__main__":
 x=compute()
 OUT.write_text(json.dumps(x,indent=2,sort_keys=True)+"\n")
 print(json.dumps(x,indent=2),flush=True)
 print("TORUS_H27_FLUX_PASS")
