#!/usr/bin/env python3
"""Pass9965-9972 outside-box: a canonical gauge-invariant C2 phase character from F9.

The explicit glue phase space is F9^6 with i^2=-1.  Its finite unitary phase
group is the norm-one subgroup of F9^x.  The field norm

    N: F9^x -> F3^x = {+1,-1},   N(z)=z^(3+1)=z^4

is surjective and has kernel U(1,F9/F3)=C4={1,-1,i,-i}.  Therefore N(uz)=N(z)
for every norm-one gauge phase u.  The two norm cosets are a canonical C2
channel that can carry the orientation/parity bit without using absolute phase.

In the unramified local lift Q3(i), these are the reductions of Teichmuller
units: mu_8 -> F9^x, with norm-one mu_4 and quotient mu_8/mu_4=C2.
"""
from __future__ import annotations
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
OUT=ROOT/'data/PART_W33_PASS9965_9972_F9_NORM_PHASE_CHARACTER.json'

def mul(x,y):
    a,b=x;c,d=y
    return ((a*c+2*b*d)%3,(a*d+b*c)%3)
def power(x,n):
    r=(1,0)
    while n:
        if n&1:r=mul(r,x)
        x=mul(x,x);n//=2
    return r
def order(x):
    return next(n for n in range(1,9) if power(x,n)==(1,0))

def main():
    units=[(a,b) for a in range(3) for b in range(3) if (a,b)!=(0,0)]
    assert len(units)==8
    data={z:{'order':order(z),'norm':power(z,4)} for z in units}
    plus=[z for z in units if data[z]['norm']==(1,0)]
    minus=[z for z in units if data[z]['norm']==(2,0)]
    assert set(plus)=={(1,0),(2,0),(0,1),(0,2)}
    assert len(plus)==len(minus)==4
    assert all(order(z) in (1,2,4) for z in plus)
    assert all(order(z)==8 for z in minus)
    i=(0,1);assert power(i,2)==(2,0) and order(i)==4
    # Gauge invariance of norm under every kernel phase.
    for u in plus:
        for z in units:
            assert power(mul(u,z),4)==power(z,4)
    out={
      'schema':'w33.pass9965_9972.f9_norm_phase_character.v1','status':'PASS','passes':'9965-9972','outside_box':True,
      'field':'F9=F3[i]/(i^2+1)',
      'unit_group':{'order':8,'structure':'C8','primitive_norm_minus_units':[list(z) for z in minus]},
      'norm_map':{'formula':'N(z)=z^4','codomain':'F3^x=C2','surjective':True,
                  'kernel':[list(z) for z in plus],'kernel_structure':'C4 = {1,-1,i,-i}','coset_sizes':[4,4]},
      'gauge_invariance':'For every u with N(u)=1, N(u z)=N(z); the norm sign is invariant under the full finite unitary phase gauge.',
      'local_field_lift':{'unramified_field':'Q3(i)','Teichmuller_units':'mu_8 reduces to F9^x','norm_one_units':'mu_4','binary_quotient':'mu_8/mu_4 = C2'},
      'orientation_encoding':('The abstract orientation/parity bit may be encoded in the two norm cosets. This is a canonical binary channel compatible with the F9 glue arithmetic and immune to multiplication by norm-one phase gauges.'),
      'theorem':'The F9 phase alphabet carries a canonical gauge-invariant C2 norm character. Its kernel is exactly the order-4 unitary phase subgroup generated by the glue complex structure i, so a binary orientation channel can be encoded without absolute phase.',
      'boundary':'Exact finite-field and Teichmuller-unit arithmetic. Mapping the repository A4/S4 orientation bit to the two norm cosets is a proposed encoding convention, not yet derived from a hardware Hamiltonian.'}
    OUT.write_text(json.dumps(out,indent=2,sort_keys=True)+'\n');print(json.dumps({'status':'PASS','norm_plus':len(plus),'norm_minus':len(minus)}));return 0
if __name__=='__main__':raise SystemExit(main())
