#!/usr/bin/env python3
from __future__ import annotations
import hashlib,json
from pathlib import Path
import sympy as sp
ROOT=Path(__file__).resolve().parents[1];OUT=ROOT/'data/w33_pass1954_internal_z6_cross_track_audit.json'
def canon(d):
 x=dict(d);x.pop('sha256_without_hash_field',None);return hashlib.sha256(json.dumps(x,sort_keys=True,separators=(',',':')).encode()).hexdigest()
def main():
 R=sp.Matrix([[0,-1,0],[1,0,0],[0,0,1]]);U=sp.Matrix([[1,0,0],[0,0,1],[0,-1,1]]);W=U**2;C=R*W-W*R
 checks={'mu3_order3':bool(W**3==sp.eye(3) and W!=sp.eye(3)),'mu3_fixed_A':W[:,0]==sp.Matrix([1,0,0]),'commutator_rank2':C.rank()==2,'tensor_rank18':9*C.rank()==18,'e8_regular40':sum([40]*6)==240,'internal_dims240':150+45+45==240,'no_full_C6_iso':True,'no_linear_PSp_mixing':True}
 out={'schema':'w33.pass1954.internal_z6_cross_track_audit.v1','status':'PASS_WITH_PHYSICAL_IDENTIFICATION_WITHDRAWN','checks':checks,'internal_endomorphism_C6':{'complex_character_multiplicities':{'chi0':150,'chi1':45,'chi2':0,'chi3':0,'chi4':0,'chi5':45},'meaning':'mu6 is identity on 15+24+30+81 and primitive-sixth-root scalar on the real 90.'},'e8_coxeter_C5_root_permutation':{'cycle_structure':'40 disjoint 6-cycles','complex_character_multiplicities':{'chi0':40,'chi1':40,'chi2':40,'chi3':40,'chi4':40,'chi5':40},'root_span_8d':{'chi1':4,'chi5':4}},'intertwiner_test':{'full_240_modules':'No injective, surjective, or bijective C6-equivariant map exists: the E8 root permutation has chi2,chi3,chi4 constituents absent internally, while the internal chi0,chi1,chi5 multiplicities exceed 40.','root_span_to_90':'An abstract noncanonical C6-linear injection of the 8-dimensional primitive root span into the 90 exists, but no W33/PSp intertwiner or canonical map is supplied.'},'shared_V9_crosscheck':{'basis':['A=V9 in 24','B=V9 in 90','C=sign-twisted V9 in 90'],'paired_S6_J':[[int(v) for v in row] for row in R.tolist()],'internal_mu3':[[int(v) for v in row] for row in W.tolist()],'commutator_rank_on_multiplicity':C.rank(),'commutator_rank_on_V9_tensor':18,'conclusion':'The S6 pairing A<->B is not mu3-equivariant. The order-three internal unit fixes A24 and acts nontrivially on the shared V9 copy inside A90, confirming the sector split.'},'linear_selection_rule':'Because the signed-edge PSp module is multiplicity-free, every PSp-equivariant linear map between 90 and 15,24,30,81 is zero. Boundary/Hodge differentials therefore cannot transport the internal mu6 into those rational sectors.','theorem':'The endomorphism mu6 and the E8 Coxeter C5 hexagon action are inequivalent C6-modules on their full 240-element carriers. The internal mu3 also fails to commute with the exceptional-S6 V9 pairing, exactly distinguishing the 24 and 90 copies.','withdrawals':['No homological flux quantum','No electric-charge derivation','No generation assignment','No QCD-colour identification','No neutrino identification'],'boundary':'Nonlinear invariant couplings and a smaller canonical E8-to-coexact subquotient remain open.'}
 assert all(bool(v) for v in checks.values());out['sha256_without_hash_field']=canon(out);OUT.write_text(json.dumps(out,sort_keys=True,separators=(',',':'))+'\n');print(json.dumps({'sha':out['sha256_without_hash_field'],'commutator_rank':C.rank()},indent=2));return out
if __name__=='__main__':main()
