#!/usr/bin/env python3
"""Execute five exact frontier audits for the 216/540 sentinel circuit geometry.

This single reconstruction deliberately shares the expensive PSp(4,3), C5, C6,
and bicolour incidence setup across five logically separate targets:

1. Restrict all seven bicolour spectral sectors to the order-648 W33 point
   stabilizer K, with exact character inner products and central-C3 splitting.
2. Give the conjugate sixes in the 24-sector a concrete Eisenstein/deck model:
   the 12-dimensional rational carrier has J=z-z^2 with J^2=-3, and a
   deterministic six-fibre witness spans it over Q(sqrt(-3)).
3. Resolve the 540-side right-kernel geometry, including the exact 216+324
   image/kernel split and the mutual position of the three 324-dimensional
   kernels for M, M+, M-.
4. Compute modular ranks of M, M+, M- and their Gram operators at the primes
   singled out by the integral spectrum (plus controls), providing a Smith-
   filtration audit without claiming a full integral SNF where it is not proved.
5. Close the 17 cross orbitals into the full two-fibre Schurian coherent
   configuration: enumerate C5xC5 and C6xC6 orbitals, certify cross-product
   structure constants, and locate A20/A30 inside the same-fibre orbital algebra.

All spectral projectors are exact integer Lagrange polynomials.  No floating
point eigenspaces are used.
"""
from __future__ import annotations

import hashlib
import itertools
import json
from collections import Counter, defaultdict, deque
from pathlib import Path

import numpy as np
import sympy as sp

import w33_20260829_216_clifford_torsor_nogo as base
from w33_20260830_sentinel_six_circuit_orbit import six_circuits

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "data/PART_W33_20260831_ALL5_FRONTIER_AUDIT.json"


def rank_mod(A: np.ndarray, p: int) -> int:
    """Row rank over F_p, vectorized enough for the 432x540 matrices here."""
    B = np.array(A, dtype=np.int64, copy=True) % p
    m, n = B.shape
    r = 0
    for c in range(n):
        piv = np.flatnonzero(B[r:, c])
        if not len(piv):
            continue
        q = r + int(piv[0])
        if q != r:
            B[[r, q]] = B[[q, r]]
        inv = pow(int(B[r, c]), -1, p)
        B[r, :] = (B[r, :] * inv) % p
        rows = np.flatnonzero(B[:, c])
        rows = rows[rows != r]
        if len(rows):
            # Keep products in int64: all primes used below are tiny except the
            # generic witness prime, for which coefficients remain <1e12.
            fac = B[rows, c].copy()
            B[rows, :] = (B[rows, :] - fac[:, None] * B[r, :][None, :]) % p
        r += 1
        if r == m:
            break
    return r


def rank_mod_columns(cols: list[np.ndarray], p: int = 1000003) -> int:
    if not cols:
        return 0
    return rank_mod(np.column_stack(cols), p)


def permutation_matrix(p: tuple[int, ...]) -> np.ndarray:
    n = len(p)
    Z = np.zeros((n, n), dtype=np.int64)
    for i, j in enumerate(p):
        Z[j, i] = 1
    return Z


def orbit_ids(act_left, act_right, n_left: int, n_right: int):
    """Orbital ids for a transitive diagonal action generated by paired perms."""
    ids = np.full(n_left * n_right, -1, dtype=np.int32)
    reps = []
    sizes = []
    rid = 0
    for seed in range(n_left * n_right):
        if ids[seed] >= 0:
            continue
        ids[seed] = rid
        reps.append(seed)
        Q = deque([seed]); size = 0
        while Q:
            z = Q.popleft(); size += 1
            a, b = divmod(z, n_right)
            for pl, pr in zip(act_left, act_right):
                nz = pl[a] * n_right + pr[b]
                if ids[nz] < 0:
                    ids[nz] = rid; Q.append(nz)
        sizes.append(size); rid += 1
    return ids.reshape((n_left, n_right)), reps, sizes


def lagrange_projector_numerators(C: np.ndarray, roots: list[int]):
    """Return integer Q_s,D_s with P_s=Q_s/D_s for each simple root s."""
    n = C.shape[0]
    powers = [np.eye(n, dtype=np.int64)]
    for _ in range(1, len(roots)):
        powers.append(powers[-1] @ C)
    out = {}
    x = sp.Symbol('x')
    for s in roots:
        others = [r for r in roots if r != s]
        poly = sp.Poly(sp.prod(x-r for r in others), x)
        # coeffs are high-to-low; convert to low-to-high.
        coeff = [int(v) for v in reversed(poly.all_coeffs())]
        Q = np.zeros_like(C)
        for k, a in enumerate(coeff):
            Q += a * powers[k]
        D = 1
        for r in others:
            D *= s-r
        assert int(np.trace(Q)) % D == 0
        out[s] = (Q, D)
    return out


def digest_json(obj) -> str:
    raw = json.dumps(obj, sort_keys=True, separators=(",", ":")).encode()
    return hashlib.sha256(raw).hexdigest()


def main():
    # ------------------------------------------------------------------
    # Shared geometry and native PSp generators.
    # ------------------------------------------------------------------
    pts, idx, _lines, N = base.geometry()
    supports, masks = base.supports_from_N(N)

    c5 = []
    for C5 in itertools.combinations(range(45), 5):
        w = 0
        for i in C5:
            w ^= masks[i]
        if w == 0:
            c5.append(C5)
    c6 = six_circuits(masks)
    assert len(c5) == 216 and len(c6) == 540
    i5 = {C:i for i,C in enumerate(c5)}
    i6 = {C:i for i,C in enumerate(c6)}

    gens40 = []
    for v in pts:
        for alpha in (1,2):
            p=[]
            for x0 in pts:
                zz = alpha * base.form(x0,v) % 3
                y = base.norm(tuple((x0[k] + zz*v[k]) % 3 for k in range(4)))
                p.append(idx[y])
            gens40.append(tuple(p))
    si = {S:i for i,S in enumerate(supports)}
    gens45 = [tuple(si[frozenset(p[x] for x in S)] for S in supports) for p in gens40]
    chosen=(18,62,77,10)
    g40=[gens40[i] for i in chosen]
    g45=[gens45[i] for i in chosen]
    Gpaired = base.closure_paired(g40,g45)
    assert len(Gpaired)==25920

    act5=[tuple(i5[tuple(sorted(g[x] for x in C5))] for C5 in c5) for g in g45]
    act6=[tuple(i6[tuple(sorted(g[x] for x in C6))] for C6 in c6) for g in g45]

    # Full maximal-overlap incidence and its two colour orbitals.
    s5=[set(C) for C in c5]; s6=[set(C) for C in c6]
    M=np.zeros((216,540),dtype=np.int64)
    for a in range(216):
        for b in range(540):
            if len(s5[a] & s6[b])==3:
                M[a,b]=1
    assert set(map(int,M.sum(axis=1)))=={20}
    assert set(map(int,M.sum(axis=0)))=={8}

    seed=next(a*540+b for a in range(216) for b in range(540) if M[a,b])
    O={seed}; Qw=deque([seed])
    while Qw:
        z0=Qw.popleft(); a,b=divmod(z0,540)
        for p5,p6 in zip(act5,act6):
            nz=p5[a]*540+p6[b]
            if nz not in O:
                O.add(nz); Qw.append(nz)
    assert len(O)==2160
    Mp=np.zeros_like(M)
    for z0 in O:
        a,b=divmod(z0,540); Mp[a,b]=1
    Mm=M-Mp
    for X in (Mp,Mm):
        assert set(map(int,X.sum(axis=1)))=={10}
        assert set(map(int,X.sum(axis=0)))=={4}

    I=np.eye(216,dtype=np.int64)
    A30=Mp@Mp.T-10*I
    cross=Mp@Mm.T+Mm@Mp.T
    assert not np.any(cross % 4)
    A20=cross//4
    assert np.array_equal(A30@A20,A20@A30)
    Csep=A30+7*A20
    sectors=[
        (-58,12,-10,15),
        (-22,6,-4,15),
        (-18,-4,-2,81),
        (8,-6,2,20),
        (14,0,2,60),
        (62,6,8,24),
        (170,30,20,1),
    ]
    roots=[s for s,_,_,_ in sectors]
    projectors=lagrange_projector_numerators(Csep,roots)
    for s,_a,_b,d in sectors:
        Qs,Ds=projectors[s]
        assert int(np.trace(Qs))==d*Ds

    # ------------------------------------------------------------------
    # 1. Restrict all seven sectors to K, resolving the central C3 pieces.
    # ------------------------------------------------------------------
    Kpairs=sorted((p40,p45) for p40,p45 in Gpaired if p40[0]==0)
    assert len(Kpairs)==648
    K45=[x[1] for x in Kpairs]
    kgens=base.deterministic_generators(set(K45),45)
    Z=[z for z in K45 if all(base.compose(z,g)==base.compose(g,z) for g in kgens)]
    assert len(Z)==3
    e45=tuple(range(45)); zc=next(z for z in Z if z!=e45); zc2=base.compose(zc,zc)

    def c5perm(g):
        return tuple(i5[tuple(sorted(g[x] for x in C5))] for C5 in c5)
    Kp={g:c5perm(g) for g in K45}

    char_table={}
    restriction=[]
    for s,a30,a20,d in sectors:
        Qs,Ds=projectors[s]
        vals={}
        for g in K45:
            p=Kp[g]
            num=sum(int(Qs[i,p[i]]) for i in range(216))
            assert num % Ds==0
            vals[g]=num//Ds
        char_table[s]=vals
        cz=vals[zc]; cz2=vals[zc2]
        assert cz==cz2
        d0=(d+2*cz)//3; dw=(d-cz)//3
        assert d0+2*dw==d and d0>=0 and dw>=0

        # Exact character norms of the full, central-trivial, and each omega part.
        nfull=sum(v*v for v in vals.values())
        n0=0; nw=0
        for g in K45:
            c0=vals[g]
            c1=vals[base.compose(zc,g)]
            c2=vals[base.compose(zc2,g)]
            ss=c0+c1+c2
            assert ss%3==0
            n0 += (ss//3)**2
            nn=c0*c0+c1*c1+c2*c2-c0*c1-c0*c2-c1*c2
            assert nn%9==0
            nw += nn//9
        assert nfull%648==0 and n0%648==0 and nw%648==0
        restriction.append({
            "separatorEigenvalue":s,"A30":a30,"A20":a20,"dimension":d,
            "centerTrace":cz,"centralDimensions":{"trivial":d0,"omega":dw,"omega2":dw},
            "characterNorm":nfull//648,"trivialPartNorm":n0//648,"omegaPartNorm":nw//648,
        })

    # Inner-product Gram of all seven restricted K characters.
    restriction_gram=[]
    for s,*_ in sectors:
        row=[]
        for t,*__ in sectors:
            nn=sum(char_table[s][g]*char_table[t][g] for g in K45)
            assert nn%648==0
            row.append(nn//648)
        restriction_gram.append(row)

    # ------------------------------------------------------------------
    # 2. Concrete Eisenstein/deck geometry of the conjugate sixes.
    # ------------------------------------------------------------------
    s24=62
    Q24,D24=projectors[s24]
    zperm=Kp[zc]
    Zmat=permutation_matrix(zperm); Z2=Zmat@Zmat
    J=Zmat-Z2
    Nnt=Q24@(2*I-Zmat-Z2)  # denominator 3*D24; image = nontrivial C3 carrier
    assert rank_mod(Nnt,1000003)==12
    assert not np.any((J@J+3*I)@Nnt)
    assert np.array_equal(J@Nnt,Nnt@J)

    fibres=[]; seen=set()
    for i in range(216):
        if i in seen: continue
        cyc=[]; q=i
        while q not in seen:
            seen.add(q); cyc.append(q); q=zperm[q]
        assert len(cyc)==3
        fibres.append(tuple(cyc))
    assert len(fibres)==72

    chosen_fibres=[]; basis_cols=[]; rr=0
    for fi,F in enumerate(fibres):
        v=Nnt[:,F[0]].copy(); jv=J@v
        nr=rank_mod_columns(basis_cols+[v,jv])
        if nr==rr+2:
            chosen_fibres.append(fi); basis_cols.extend([v,jv]); rr=nr
            if rr==12: break
    assert len(chosen_fibres)==6 and rr==12
    Bsmall=np.column_stack(basis_cols)
    assert sp.Matrix(Bsmall.tolist()).rank()==12
    six_fibre_witness=[{
        "fibreIndex":fi,
        "circuitIndices":list(fibres[fi]),
        "circuits":[list(c5[j]) for j in fibres[fi]],
    } for fi in chosen_fibres]

    # ------------------------------------------------------------------
    # 3. 540-side image/kernel decomposition and the three kernel positions.
    # ------------------------------------------------------------------
    generic=1000003
    rankM=rank_mod(M,generic); rankP=rank_mod(Mp,generic); rankN=rank_mod(Mm,generic)
    assert (rankM,rankP,rankN)==(216,216,216)
    stackPN=np.vstack([Mp,Mm])
    stackMP=np.vstack([M,Mp])
    stackMN=np.vstack([M,Mm])
    rsp=rank_mod(stackPN,generic); rsmp=rank_mod(stackMP,generic); rsmn=rank_mod(stackMN,generic)
    assert rsp==rsmp==rsmn
    pair_intersection=540-rsp
    assert pair_intersection>=0
    # K+ intersect K- is automatically contained in K(M++M-), so the triple
    # intersection equals this pair intersection; the other two pair
    # intersections equal it by the same linear identity.
    kernel_dims={"M":540-rankM,"Mplus":540-rankP,"Mminus":540-rankN,
                 "pairwiseIntersection":pair_intersection,"tripleIntersection":pair_intersection}

    right_spectrum={"0":324,"4":96,"16":35,"28":60,"64":24,"160":1}

    # ------------------------------------------------------------------
    # 4. Modular rank / Smith-filtration audit.
    # ------------------------------------------------------------------
    primes=[2,3,5,7,11,13]
    modular=[]
    Gram=M@M.T; Gp=Mp@Mp.T; Gm=Mm@Mm.T
    assert np.array_equal(Gp,Gm)
    for p in primes:
        modular.append({
            "p":p,
            "rankM":rank_mod(M,p),"rankMplus":rank_mod(Mp,p),"rankMminus":rank_mod(Mm,p),
            "rankGramM":rank_mod(Gram,p),"rankGramColour":rank_mod(Gp,p),
        })
    # det(MM^T) from the exact characteristic-zero spectrum.
    gram_det_factor={"2":601,"5":1,"7":60}

    # ------------------------------------------------------------------
    # 5. Full two-fibre Schurian coherent configuration.
    # ------------------------------------------------------------------
    rel55,reps55,sizes55=orbit_ids(act5,act5,216,216)
    rel66,reps66,sizes66=orbit_ids(act6,act6,540,540)
    rel56,reps56,sizes56=orbit_ids(act5,act6,216,540)
    assert len(reps56)==17
    assert sorted(sizes56)==[1080,2160,2160,2160,3240,4320,4320,6480,6480,6480,6480,6480,12960,12960,12960,12960,12960]

    # Locate the two bicolour maximal-overlap orbitals and A30/A20 fusions.
    colour_ids=sorted(set(int(rel56[a,b]) for a,b in zip(*np.nonzero(Mp))))
    colour2_ids=sorted(set(int(rel56[a,b]) for a,b in zip(*np.nonzero(Mm))))
    assert len(colour_ids)==len(colour2_ids)==1 and colour_ids!=colour2_ids
    a30_ids=sorted(set(int(rel55[a,b]) for a,b in zip(*np.nonzero(A30))))
    a20_ids=sorted(set(int(rel55[a,b]) for a,b in zip(*np.nonzero(A20))))

    # Cross*transpose structure constants into the 55 and 66 orbital algebras.
    c_to_55=[]
    for rid,seed55 in enumerate(reps55):
        a,a2=divmod(seed55,216)
        T=np.zeros((17,17),dtype=np.int64)
        np.add.at(T,(rel56[a,:],rel56[a2,:]),1)
        c_to_55.append(T.tolist())
    c_to_66=[]
    for rid,seed66 in enumerate(reps66):
        b,b2=divmod(seed66,540)
        T=np.zeros((17,17),dtype=np.int64)
        np.add.at(T,(rel56[:,b],rel56[:,b2]),1)
        c_to_66.append(T.tolist())

    structure={
        "crossTo55":c_to_55,
        "crossTo66":c_to_66,
    }
    coherent={
        "r55":len(reps55),"r66":len(reps66),"r56":17,"r65":17,
        "totalRank":len(reps55)+len(reps66)+34,
        "sizes55":sorted(sizes55),"sizes66":sorted(sizes66),"sizes56":sorted(sizes56),
        "maximalOverlapColourRelationIds":[colour_ids[0],colour2_ids[0]],
        "A30FusionOf55Orbitals":a30_ids,
        "A20FusionOf55Orbitals":a20_ids,
        "crossProductStructureConstantsSHA256":digest_json(structure),
        "crossProductStructureConstants":structure,
        "proof":"all relations are exact orbitals of the same PSp(4,3) action; one representative therefore determines every orbital structure constant",
    }

    out={
        "schema":"w33.20260831.all5-frontier-audit.v1",
        "status":"PASS",
        "shared":{"G":"PSp(4,3)","order":25920,"C5":216,"C6":540,"crossPairs":116640},
        "track1_allSevenKRestrictions":{
            "KOrder":648,"center":"C3","sectorRows":restriction,
            "restrictedCharacterInnerProductGram":restriction_gram,
            "theorem":"All seven exact bicolour spectral sectors have certified K-restriction characters and central-C3 isotypic dimensions; norms distinguish irreducible from reducible restricted pieces without character-table guessing.",
        },
        "track2_eisensteinSixes":{
            "sectorDimension":24,"centralNontrivialRationalDimension":12,
            "deckOperator":"J=z-z^2","identity":"J^2=-3 on the 12-dimensional rational carrier",
            "complexDimensions":[6,6],"field":"Q(sqrt(-3)) = Q(omega)",
            "deterministicSixFibreBasisWitness":six_fibre_witness,
            "theorem":"The two conjugate irreducible sixes are the +/-sqrt(-3) eigenspaces of the canonical central-deck orientation operator on a 12-dimensional rational carrier; six deck fibres give an explicit Q(omega)-basis witness.",
        },
        "track3_rightKernel":{
            "rightGramSpectrum":right_spectrum,"imageDimension":216,"kernelDimension":324,
            "colourImageDimensions":[216,216],"stackedColourRowRank":rsp,"kernelDimensions":kernel_dims,
            "theorem":"The 540-space splits as im(M^T) of dimension 216 plus ker(M) of dimension 324.  The M, M+, M- kernels are three 324-dimensional subspaces whose pairwise and triple intersection dimension is certified from the stacked colour rank.",
        },
        "track4_modularSmithFiltration":{
            "ranks":modular,"gramDeterminantPrimeValuations":gram_det_factor,
            "boundary":"These are exact modular ranks and determinant valuations.  They are a Smith-filtration audit, not a claimed complete integral Smith normal form of the rectangular incidence matrices.",
        },
        "track5_fullCoherentConfiguration":coherent,
    }
    OUT.parent.mkdir(parents=True,exist_ok=True)
    OUT.write_text(json.dumps(out,indent=2,sort_keys=True)+"\n")
    summary={
        "status":"PASS",
        "Krows":[(r["dimension"],r["centralDimensions"],r["characterNorm"]) for r in restriction],
        "kernel":kernel_dims,
        "modular":[(r["p"],r["rankM"],r["rankMplus"],r["rankGramM"]) for r in modular],
        "coherentRank":coherent["totalRank"],"r55":coherent["r55"],"r66":coherent["r66"],
        "A30orb":a30_ids,"A20orb":a20_ids,
    }
    print(json.dumps(summary,sort_keys=True))


if __name__=="__main__":
    main()
