#!/usr/bin/env python3
"""Pass5633 bonkers: could the nine vertical E6 fibers be gauge bosons?

The AG(2,3) bundle makes the cochain degree explicit.  The nine bad cubics are in
bijection with the NINE BASE SITES/fibers.  Local Z3 gauge parameters therefore
live in C^0 with dimension 9 (8 effective after the global constant mode).  A
connection lives on links, i.e. C^1.  Because every pair of affine-plane points
lies on a unique line, the one-skeleton generated by all affine lines is K9 with
36 undirected links.  Its incidence map has rank 8 and cycle space dimension 28.

Thus the count 9 naturally belongs to local gauge transformations/Gauss-law sites,
not propagating link-connection modes.  The tempting 'bad9 = gauge bosons' reading
is a cochain-degree mismatch.
"""
from __future__ import annotations
import itertools,json
from pathlib import Path
import numpy as np
ROOT=Path(__file__).resolve().parents[1]
OUT=ROOT/'data/PART_W33_PASS5633_BAD9_GAUGE_GENERATOR_NOT_BOSON.json'

def main():
    pts=[(x,y) for x in range(3) for y in range(3)]; pi={p:i for i,p in enumerate(pts)}
    lines=[]
    for c in range(3):lines.append([(c,y) for y in range(3)])
    for m in range(3):
        for c in range(3):lines.append([(x,(m*x+c)%3) for x in range(3)])
    assert len(lines)==12
    edges=set()
    for L in lines:
        for a,b in itertools.combinations(L,2):edges.add(tuple(sorted((pi[a],pi[b]))))
    assert len(edges)==36==9*8//2
    # Oriented incidence over R; connected K9 has rank V-1=8.
    B=np.zeros((9,36),float)
    for j,(a,b) in enumerate(sorted(edges)):B[a,j]=-1;B[b,j]=1
    rank=int(np.linalg.matrix_rank(B)); assert rank==8
    cycle_dim=36-rank; assert cycle_dim==28
    # Fourier decomposition of each 3-state fiber: 1 + chi + chibar.
    w=np.exp(2j*np.pi/3);F=np.array([[w**(j*k) for k in range(3)] for j in range(3)],complex)
    assert abs(np.linalg.det(F))>1e-9
    out={
      'pass':5633,'status':'BAD9_LIVE_IN_GAUGE_C0_SITE_DEGREE_NOT_CONNECTION_C1',
      'AG23':{'sites':9,'lines':12,'one_skeleton_edges':36,'one_skeleton':'K9'},
      'gauge_cochains':{'C0_local_parameters':9,'effective_nonconstant_gauge_parameters':8,'C1_link_variables':36,'incidence_rank':rank,'cycle_space_dimension':cycle_dim},
      'fiber_Fourier':'Each 3-state Z3 fiber decomposes over C into trivial + chi + chibar; over all nine fibers this is 9 + 9 + 9 linear modes.',
      'bad9_position':'The nine vertical cubics are indexed by the nine fibers/base sites, so their natural cochain degree is site/local-gauge (C0), not link/connection (C1).',
      'no_go':'Identifying the bad9 themselves with propagating gauge bosons from the number 9 is structurally wrong in the natural bundle gauge complex. Gauge connections require link data (36 on the full affine one-skeleton, or another explicitly chosen edge carrier).',
      'alternative_reading':'If given a physical role, the vertical nine are more naturally candidates for local gauge constraints, Gauss-law/site singlets, or vertical potential terms than gauge-boson states.',
      'physics_firewall':'This does not derive a gauge theory or Gauss law; it only fixes the cochain degree forced by the reconstructed bundle.'
    }
    OUT.write_text(json.dumps(out,indent=2,sort_keys=True)+'\n');print(json.dumps(out,indent=2,sort_keys=True))
if __name__=='__main__':main()
