#!/usr/bin/env python3
"""Pass5377: close the all-odd rank-complement / kernel / K0-generation triad.

Pass5376 proves for every odd prime power q

    im_2(F)=C_W^perp,
    rank_2(F)=g=q(q^2+1)/2,
    ker_2(F^T)=C_W.

Pass5267 gives the characteristic-zero frame law

    rank_Q(F)=1+f, null_Q(F)=g,
    f=q(q+1)^2/2.

Pass5299 proves all-odd

    D_q <= K0,
    dim D_q=q^4-g,
    dim K0=q^4-rank_2(F),

so rank_2(F)=g iff K0=D_q.

Thus the formerly open triad is now closed for all odd prime powers q, and the
characteristic-0 / characteristic-2 rank complement is exact globally.
"""
from __future__ import annotations
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
OUT=ROOT/'data/PART_W33_PASS5377_ALLODD_RANK_COMPLEMENT_GENERATION_CLOSURE.json'

def row(q:int)->dict[str,int]:
    v=(q+1)*(q*q+1); f=q*(q+1)**2//2; g=q*(q*q+1)//2
    rankQ=1+f; nullQ=g; rank2=g; null2=1+f
    D=q**4-g; K=q**4-rank2
    assert v==rankQ+nullQ==rank2+null2 and D==K
    return {'q':q,'v':v,'f':f,'g':g,'rank_Q':rankQ,'null_Q':nullQ,
      'rank_F2':rank2,'null_F2':null2,'D_q_dimension':D,'K0_dimension':K}

def main()->None:
    rows={str(q):row(q) for q in (3,5,7,9,11,13,17,19,25,27,49)}
    out={'pass':5377,'status':'THEOREM_ALLODD_RANK_COMPLEMENT_KERNEL_AND_K0_GENERATION_CLOSED',
      'domain':'all odd prime powers q',
      'rank_complement':['rank_Q(F)=1+f=null_2(F^T)','null_Q(F)=g=rank_2(F)'],
      'kernel_theorem':'ker_2(F^T)=C_W and im_2(F)=C_W^perp.',
      'generation_theorem':'K0=D_q: the zero-footprint residual is generated by same-point chamber-star differences.',
      'dimensions':'f=q(q+1)^2/2, g=q(q^2+1)/2, dim K0=dim D_q=q^4-g.',
      'logic':['Pass5267: characteristic-zero frame rank/nullity.','Pass5299: D_q<=K0 and equality iff rank_2(F)=g.','Pass5376: rank_2(F)=g and ker_2(F^T)=C_W for every odd prime power q.'],
      'sample_rows':rows,
      'supersedes':['Pass5334 all-odd binary rank conjecture boundary','Pass5335 arbitrary-q kernel-open boundary','Pass5299 final-generation-open boundary'],
      'remaining_boundaries':['q=11 dual weight-20 existence / d=121 remains open.','Hoffman shortened-code minimum distance remains in {28,32,36,40}.','This theorem does not determine the minimum distance of the footprint image code.']}
    OUT.write_text(json.dumps(out,indent=2,sort_keys=True)+'\n');print(json.dumps(out,indent=2,sort_keys=True))
if __name__=='__main__':main()
