#!/usr/bin/env python3
"""Pass 984: the 2-primary gluing separates cospectral graphs, and the signed
edge action is the correct one.

Pass 983 established that the odd-p coalescence rank does NOT separate the
cospectral family T(8), Chang(matching), Chang(8-cycle) -- it is 7 for all three
-- while the classical 2-rank does (6 against 8).  It also left an explicit open
item: a naive test suggested the signed-turn operator K does not commute with
Aut(W(3,3)), which was flagged as probably an artefact of using an unsigned
action.  This pass settles both.

(a) THE 2-PRIMARY GLUING IS A GRAPH INVARIANT FINER THAN THE SPECTRUM.

Computing the full 2-primary part of the three-branch eigenlattice gluing
(local Smith over Z/2^N on the projector-congruence stack) for the family:

        T(8)               (Z/2)^6 (+) (Z/4)      2-rank 6
        Chang(matching)    (Z/2)^7 (+) (Z/4)      2-rank 8
        Chang(8-cycle)     (Z/2)^7 (+) (Z/4)      2-rank 8

The three graphs are cospectral, so no spectral invariant can tell them apart;
the gluing does separate T(8) from the Chang graphs.  It therefore carries
information the spectrum does not.  It does NOT separate the two Chang graphs
from each other, so it is not a complete invariant for this family -- the same
limitation the 2-rank has.

This is the concrete payoff of the p = 2 case that Pass 983 identified as the
place where the content sits: the odd primes are spectrally determined here, the
prime 2 is not.

(b) THE ACTION ON ORIENTED EDGES IS SIGNED.

K acts on the 240 ORIENTED edge chains.  A graph automorphism permutes edges but
may reverse an orientation, so it acts by a signed permutation matrix P with
P[e', e] = +-1 according to whether the image pair is in increasing order.  With
that action, K commutes with every automorphism tested (8 of 8); with the
unsigned permutation matrix it commutes with none (0 of 8).  Pass 983's negative
result was an artefact of the wrong action, exactly as suspected there, and the
correct statement is that Aut(W(3,3)) acts on the oriented edge space by signed
permutations commuting with K.

BOUNDARY.  The separation is exhibited on one cospectral family of three graphs,
not proved in general; the gluing is shown to be strictly finer than the spectrum
for that family and is not claimed to be a complete invariant.  The commutation
is verified on eight sampled automorphisms generated by symplectic transvections,
not proved for the whole group.  The ramified p = 2 coalescence theorem itself
remains open: this pass supplies data it must reproduce, not the theorem.
"""
from __future__ import annotations

import argparse
import importlib.util
import itertools
import json
import random
from collections import Counter
from math import gcd
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "data" / "w33_pass984_gluing_separates_cospectral.json"
BASE = ROOT / "analysis" / "w33_pass682_flatblock_h1_branch_separation.py"


def v2(x, cap=30):
    if x == 0:
        return cap
    v = 0
    while x % 2 == 0:
        x //= 2
        v += 1
    return v


def local_smith_2(A, PREC, cap=30):
    A = A.copy().astype(object) % PREC
    rows, cols = A.shape
    vals = []
    r = step = 0
    while step < cols and r < rows:
        best, bv = None, cap + 1
        for i in range(r, rows):
            for j in range(step, cols):
                x = int(A[i, j]) % PREC
                if x == 0:
                    continue
                v = v2(x, cap)
                if v < bv:
                    bv, best = v, (i, j)
                if bv == 0:
                    break
            if bv == 0:
                break
        if best is None:
            break
        i, j = best
        if i != r:
            A[[r, i]] = A[[i, r]]
        if j != step:
            A[:, [step, j]] = A[:, [j, step]]
        piv = int(A[r, step]) % PREC
        u = piv // (1 << bv)
        uinv = pow(u, -1, PREC // (1 << bv)) if PREC // (1 << bv) > 1 else 1
        A[r] = (A[r] * uinv) % PREC
        for i2 in range(r + 1, rows):
            x = int(A[i2, step]) % PREC
            if x:
                A[i2] = (A[i2] - (x // (1 << bv)) * A[r]) % PREC
        for j2 in range(step + 1, cols):
            x = int(A[r, j2]) % PREC
            if x:
                A[:, j2] = (A[:, j2] - (x // (1 << bv)) * A[:, step]) % PREC
        vals.append(bv)
        r += 1
        step += 1
    vals.extend([cap] * (min(rows, cols) - len(vals)))
    return vals


def rank_p(M, p):
    M = [[int(x) % p for x in r] for r in M]
    rows = len(M)
    cols = len(M[0]) if rows else 0
    r = 0
    for c in range(cols):
        piv = next((i for i in range(r, rows) if M[i][c] % p), None)
        if piv is None:
            continue
        M[r], M[piv] = M[piv], M[r]
        inv = pow(M[r][c], p - 2, p)
        M[r] = [(x * inv) % p for x in M[r]]
        for i in range(rows):
            if i != r and M[i][c]:
                f = M[i][c]
                M[i] = [(M[i][j] - f * M[r][j]) % p for j in range(cols)]
        r += 1
    return r


def gluing_2part(A, cs):
    n = A.shape[0]
    Ao = A.astype(object)
    I = np.eye(n, dtype=object)
    Ds = []
    for c in cs:
        D = 1
        for d in cs:
            if d != c:
                D *= (c - d)
        Ds.append(abs(D))
    M = 1
    for D in Ds:
        M = M * D // gcd(M, D)
    PREC = 1 << 26
    blocks = []
    for c, D in zip(cs, Ds):
        X = I.copy()
        for d in cs:
            if d != c:
                X = X @ (Ao - d * I)
        blocks.append(((M // D) * X) % PREC)
    S = np.vstack(blocks) % PREC
    vals = local_smith_2(S, PREC)
    vM = v2(M)
    return dict(sorted(Counter(vM - v for v in vals if v < vM).items()))


def chang_family():
    prs = list(itertools.combinations(range(8), 2))
    n = 28
    T = np.zeros((n, n), dtype=np.int64)
    for a in range(n):
        for b in range(n):
            if a != b and set(prs[a]) & set(prs[b]):
                T[a, b] = 1
    idx = {p_: i for i, p_ in enumerate(prs)}

    def switch(M, S):
        B = M.copy()
        for i in range(n):
            for j in range(n):
                if i != j and ((i in S) != (j in S)):
                    B[i, j] = 1 - B[i, j]
        return B

    S1 = {idx[(0, 1)], idx[(2, 3)], idx[(4, 5)], idx[(6, 7)]}
    cyc = [(0, 1), (1, 2), (2, 3), (3, 4), (4, 5), (5, 6), (6, 7), (0, 7)]
    S2 = {idx[tuple(sorted(e))] for e in cyc}
    return {"T(8)": T, "Chang_matching": switch(T, S1),
            "Chang_8cycle": switch(T, S2)}


def part_A_separation(checks):
    fam = chang_family()
    rows = {}
    spectra, glues = set(), set()
    for nm, A in fam.items():
        ev = tuple(sorted(int(round(x))
                          for x in np.linalg.eigvalsh(A.astype(float))))
        spectra.add(ev)
        g = gluing_2part(A, [12, 4, -2])
        glues.add(json.dumps(g, sort_keys=True))
        rows[nm] = {"two_rank": rank_p(A.tolist(), 2),
                    "two_primary_gluing": g,
                    "as_group": " (+) ".join(f"(Z/{2**k})^{v}"
                                             for k, v in sorted(g.items()))}
    checks["family_is_cospectral"] = (len(spectra) == 1)
    checks["gluing_separates_the_family"] = (len(glues) > 1)
    checks["gluing_does_not_separate_the_two_changs"] = (
        rows["Chang_matching"]["two_primary_gluing"]
        == rows["Chang_8cycle"]["two_primary_gluing"])
    return {"rows": rows, "distinct_gluings": len(glues),
            "reading": (
                "The three graphs are cospectral, so no spectral invariant "
                "distinguishes them; the 2-primary gluing is (Z/2)^6 (+) (Z/4) "
                "for T(8) and (Z/2)^7 (+) (Z/4) for both Chang graphs, so it "
                "separates T(8) from them and carries information the spectrum "
                "does not.  It does not separate the two Chang graphs from each "
                "other, so it is finer than the spectrum but not complete.")}


def part_B_signed_action(checks):
    spec = importlib.util.spec_from_file_location("w33_pass682_base", BASE)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    pts, edges, tris, K, d1, d2 = mod.build()
    Q = 3
    OM = mod.OMEGA
    pidx = {p: i for i, p in enumerate(pts)}
    eidx = {tuple(sorted(e)): i for i, e in enumerate(edges)}

    def act(M, i):
        v = np.array(pts[i], dtype=np.int64)
        w = tuple(int(x) % Q for x in (M @ v) % Q)
        return pidx[mod.norm(w)]

    def transv(vv, lam):
        M = np.eye(4, dtype=np.int64)
        for b in range(4):
            e = np.zeros(4, dtype=np.int64)
            e[b] = 1
            val = int((e @ OM @ np.array(vv)) % Q)
            M[:, b] = (e + lam * val * np.array(vv)) % Q
        return M % Q

    random.seed(984)
    vecs = [np.array(v) for v in itertools.product(range(Q), repeat=4) if any(v)]
    signed_ok = unsigned_ok = 0
    N = 8
    for _ in range(N):
        M = transv(random.choice(vecs), random.choice([1, 2]))
        vp = [act(M, i) for i in range(40)]
        P = np.zeros((240, 240), dtype=np.int64)
        U = np.zeros((240, 240), dtype=np.int64)
        for i, (a, b) in enumerate(edges):
            A2, B2 = vp[a], vp[b]
            j = eidx[tuple(sorted((A2, B2)))]
            P[j, i] = 1 if A2 < B2 else -1
            U[j, i] = 1
        if np.array_equal(P @ K, K @ P):
            signed_ok += 1
        if np.array_equal(U @ K, K @ U):
            unsigned_ok += 1
    checks["signed_action_commutes_with_K"] = (signed_ok == N)
    checks["unsigned_action_does_not"] = (unsigned_ok == 0)
    return {"automorphisms_tested": N,
            "signed_commuting": signed_ok, "unsigned_commuting": unsigned_ok,
            "resolves": ("Pass 983's open item: the earlier negative result used "
                         "an unsigned permutation and was an artefact"),
            "reading": (
                "With the signed oriented-edge action, K commutes with all eight "
                "sampled automorphisms; with the unsigned action it commutes with "
                "none.  Aut(W(3,3)) acts on the oriented edge space by signed "
                "permutation matrices that commute with K.")}


def part_C_boundary(checks):
    checks["boundary_stated"] = True
    return {"open": ["the ramified p = 2 coalescence theorem itself",
                     "whether the gluing separates the two Chang graphs by some "
                     "finer reading (it does not at the 2-primary level)",
                     "conjugacy classification of A5 in Aut(W(3,3)) (GAP absent "
                     "in this environment)"],
            "scope": ("separation exhibited on one cospectral family of three "
                      "graphs; commutation verified on eight sampled "
                      "automorphisms, not proved for the whole group")}


def main_payload():
    checks = {}
    A = part_A_separation(checks)
    B = part_B_signed_action(checks)
    C = part_C_boundary(checks)
    status = "PASS" if all(checks.values()) else "FAIL"
    return {
        "schema": "w33.pass984.gluing_separates_cospectral.v1",
        "status": status,
        "headline": (
            "THE 2-PRIMARY GLUING SEES BEYOND THE SPECTRUM, AND THE EDGE ACTION "
            "IS SIGNED.  On the cospectral family T(8), Chang(matching), "
            "Chang(8-cycle) the 2-primary eigenlattice gluing is (Z/2)^6 (+) "
            "(Z/4) for T(8) and (Z/2)^7 (+) (Z/4) for both Chang graphs: it "
            "separates T(8) from them, so it carries information no spectral "
            "invariant can, though it does not separate the two Chang graphs and "
            "is therefore not complete.  This is the payoff of the p = 2 case "
            "Pass 983 located as where the content sits.  Separately, Pass 983's "
            "open item is resolved: K commutes with the SIGNED oriented-edge "
            "action of Aut(W(3,3)) in 8 of 8 sampled automorphisms and with the "
            "unsigned action in 0 of 8, so the earlier negative result was an "
            "artefact of the wrong action."),
        "part_A_separation": A,
        "part_B_signed_action": B,
        "part_C_boundary": C,
        "checks": {k: bool(v) for k, v in checks.items()},
    }


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    ap.add_argument("--output", type=Path, default=OUT)
    a = ap.parse_args()
    pl = main_payload()
    text = json.dumps(pl, sort_keys=True, separators=(",", ":")) + "\n"
    if a.check:
        if not a.output.exists() or a.output.read_text() != text:
            raise SystemExit("Pass 984 certificate drift")
    else:
        a.output.parent.mkdir(parents=True, exist_ok=True)
        a.output.write_text(text)
    print(json.dumps({"status": pl["status"],
                      "checks": sum(pl["checks"].values()),
                      "total": len(pl["checks"])}))
    return 0 if pl["status"] == "PASS" else 1


if __name__ == "__main__":
    raise SystemExit(main())
