#!/usr/bin/env python3
"""Pass 4279 -- what does thermodynamic reversibility actually cost in gates?

Pass 4252 found the four-opcode machine is doubly stochastic but NOT reversible: 243
ordered pairs of frames admit a forward move and no reverse move, so stationary entropy
production is infinite.  Closing the instruction set under inverses -- eight opcodes
instead of four -- makes the walk exactly symmetric and the entropy production exactly
zero.

That is a trade with only one side priced.  "Twice the decode logic" was an assertion.
This emits synthesisable Verilog for both machines from the actual opcode matrices (so the
gate-level design cannot disagree with the algebra), synthesises each with yosys, and
reports cells, and area.

    py -3 analysis/w33_pass4279_reversible_closure_gate_cost.py
"""

from __future__ import annotations

import json
import shutil
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "build" / "w33_rtl"

ID4 = tuple(tuple(1 if i == j else 0 for j in range(4)) for i in range(4))
LIN = {"F_p": ((0, 2, 0, 0), (1, 0, 0, 0), (0, 0, 1, 0), (0, 0, 0, 1)),
       "CX_pf": ((1, 0, 0, 0), (0, 1, 0, 2), (1, 0, 1, 0), (0, 0, 0, 1)),
       "CX_fp": ((1, 0, 1, 0), (0, 1, 0, 0), (0, 0, 1, 0), (0, 2, 0, 1))}
ISA = [("F_p", LIN["F_p"], (0, 0, 0, 0)),
       ("CX_pf", LIN["CX_pf"], (0, 0, 0, 0)),
       ("CX_fp", LIN["CX_fp"], (0, 0, 0, 0)),
       ("Z_p", ID4, (1, 0, 0, 0))]


def mm(a, b):
    return tuple(tuple(sum(a[i][k] * b[k][j] for k in range(4)) % 3 for j in range(4))
                 for i in range(4))


def mv(A, v):
    return tuple(sum(A[i][k] * v[k] for k in range(4)) % 3 for i in range(4))


def minv(M):
    a = [list(M[i]) + [1 if j == i else 0 for j in range(4)] for i in range(4)]
    r = 0
    for c in range(4):
        p = next(i for i in range(r, 4) if a[i][c] % 3)
        a[r], a[p] = a[p], a[r]
        iv = 1 if a[r][c] % 3 == 1 else 2
        a[r] = [(x * iv) % 3 for x in a[r]]
        for i in range(4):
            if i != r and a[i][c] % 3:
                f = a[i][c] % 3
                a[i] = [(a[i][k] - f * a[r][k]) % 3 for k in range(8)]
        r += 1
    return tuple(tuple(a[i][4:]) for i in range(4))


def inverse_op(name, M, t):
    Mi = minv(M)
    return (name + "_inv", Mi, tuple((-mv(Mi, t)[i]) % 3 for i in range(4)))


def emit_verilog(ops, module):
    """One trit per two bits; a frame is four trits in an 8-bit register.

    The datapath is generated from the opcode MATRICES, not hand-written, so the RTL
    cannot silently disagree with the algebra the rest of this arc measures."""
    w = max(1, (len(ops) - 1).bit_length())
    L = []
    L.append(f"// Generated by analysis/w33_pass4279_reversible_closure_gate_cost.py")
    L.append(f"// {module}: {len(ops)} opcodes over GF(3)^4, two bits per trit.")
    L.append(f"module {module} (")
    L.append("  input  wire        clk,")
    L.append("  input  wire        rst,")
    L.append(f"  input  wire [{w - 1}:0] op,")
    L.append("  output wire [7:0]  frame")
    L.append(");")
    for i in range(4):
        L.append(f"  reg [1:0] x{i};")
    L.append("  assign frame = {x3, x2, x1, x0};")
    L.append("")
    # mod-3 add of two trits
    L.append("  function [1:0] a3;")
    L.append("    input [1:0] u; input [1:0] v;")
    L.append("    reg [2:0] s;")
    L.append("    begin s = u + v; a3 = (s >= 3) ? (s - 3) : s[1:0]; end")
    L.append("  endfunction")
    L.append("")
    L.append("  function [1:0] m3;")
    L.append("    input [1:0] c; input [1:0] u;")
    L.append("    begin")
    L.append("      case (c)")
    L.append("        2'd0: m3 = 2'd0;")
    L.append("        2'd1: m3 = u;")
    L.append("        default: m3 = (u == 2'd0) ? 2'd0 : ((u == 2'd1) ? 2'd2 : 2'd1);")
    L.append("      endcase")
    L.append("    end")
    L.append("  endfunction")
    L.append("")
    L.append("  always @(posedge clk) begin")
    L.append("    if (rst) begin x0 <= 2'd0; x1 <= 2'd0; x2 <= 2'd0; x3 <= 2'd0; end")
    L.append("    else begin")
    L.append("      case (op)")
    for k, (name, M, t) in enumerate(ops):
        L.append(f"        {w}'d{k}: begin // {name}")
        for i in range(4):
            terms = [f"m3(2'd{M[i][j]}, x{j})" for j in range(4) if M[i][j]]
            expr = terms[0] if terms else "2'd0"
            for e in terms[1:]:
                expr = f"a3({expr}, {e})"
            if t[i]:
                expr = f"a3({expr}, 2'd{t[i]})"
            L.append(f"          x{i} <= {expr};")
        L.append("        end")
    L.append("        default: begin x0 <= x0; x1 <= x1; x2 <= x2; x3 <= x3; end")
    L.append("      endcase")
    L.append("    end")
    L.append("  end")
    L.append("endmodule")
    return "\n".join(L) + "\n"


def parse_stat(stdout, stderr=""):
    """yosys `stat` prints '  103 cells' and '  23   $_AND_', not 'Number of cells:'.
    An earlier version looked for the wrong strings AND passed -q, which suppresses the
    report entirely -- so it reported failure on a synthesis that had succeeded."""
    stats, per = {}, {}
    for line in (stdout or "").splitlines():
        parts = line.strip().split()
        if len(parts) == 2 and parts[0].isdigit():
            n, what = int(parts[0]), parts[1]
            if what == "cells":
                stats["cells"] = n
            elif what == "wires":
                stats["wires"] = n
            elif what.startswith("$_"):
                per[what] = n
    stats["by_cell"] = per
    if "cells" not in stats:
        stats["error"] = ((stderr or "") + (stdout or ""))[-400:]
    return stats


def yosys_stats(vfile, module, yosys):
    script = (f"read_verilog {vfile.as_posix()}; "
              f"hierarchy -top {module}; proc; opt; fsm; opt; techmap; opt; "
              f"abc -g AND,OR,XOR,NAND,NOR,XNOR,MUX; opt; stat")
    r = subprocess.run([yosys, "-p", script], capture_output=True, text=True)
    return parse_stat(r.stdout, r.stderr)


def main() -> int:
    print("=" * 78)
    print("Pass 4279 -- gate cost of the reversible closure")
    print("=" * 78)
    OUT.mkdir(parents=True, exist_ok=True)

    closed = list(ISA) + [inverse_op(n, M, t) for n, M, t in ISA]
    # dedupe: an involution is its own inverse
    seen, ops8 = set(), []
    for n, M, t in closed:
        if (M, t) in seen:
            continue
        seen.add((M, t))
        ops8.append((n, M, t))
    print(f"  four-opcode ISA          : {[n for n, _, _ in ISA]}")
    print(f"  reversible closure       : {len(ops8)} distinct opcodes")
    print(f"    {[n for n, _, _ in ops8]}")
    involutions = 8 - len(ops8)
    if involutions:
        print(f"    ({involutions} opcode(s) are their own inverse, so the closure is"
              f" smaller than 8)")

    files = {}
    for tag, ops in (("w33_isa4", ISA), ("w33_isa_closed", ops8)):
        v = OUT / f"{tag}.v"
        v.write_text(emit_verilog(ops, tag), encoding="utf-8")
        files[tag] = v
        print(f"  wrote {v.relative_to(ROOT).as_posix()}  ({len(ops)} opcodes)")

    yosys = shutil.which("yosys")
    wsl = shutil.which("wsl")
    results = {}
    if yosys:
        for tag, v in files.items():
            results[tag] = yosys_stats(v, tag, yosys)
    elif wsl:
        print("\n  yosys not on PATH; trying the WSL toolchain")
        for tag, v in files.items():
            wpath = subprocess.run(["wsl", "wslpath", "-a", str(v)],
                                   capture_output=True, text=True).stdout.strip()
            # The repo path contains spaces, which yosys's script parser splits on, so
            # stage the file at a space-free WSL path first.
            dest = f"/tmp/{tag}.v"
            subprocess.run(["wsl", "-e", "bash", "-lc",
                            f'cp "{wpath}" {dest}'], capture_output=True, text=True)
            script = (f"read_verilog {dest}; hierarchy -top {tag}; proc; opt; fsm; opt; "
                      f"techmap; opt; abc -g AND,OR,XOR,NAND,NOR,XNOR,MUX; opt; stat")
            r = subprocess.run(
                ["wsl", "-e", "bash", "-lc",
                 f"~/.local/w33-hardware/bin/yosys -p '{script}'"],
                capture_output=True, text=True)
            results[tag] = parse_stat(r.stdout, r.stderr)
    else:
        print("\n  no yosys available; RTL emitted but not synthesised")

    if results and all("cells" in v for v in results.values()):
        a, b = results["w33_isa4"], results["w33_isa_closed"]
        ratio = b["cells"] / a["cells"]
        print(f"\n  {'design':18s} {'opcodes':>8s} {'cells':>7s} {'wires':>7s}")
        print(f"  {'4-opcode ISA':18s} {len(ISA):8d} {a['cells']:7d} {a['wires']:7d}")
        print(f"  {'reversible closure':18s} {len(ops8):8d} {b['cells']:7d} {b['wires']:7d}")
        print(f"""
  THE TRADE, PRICED.  Thermodynamic reversibility costs {ratio:.2f}x the cells
  ({a['cells']} -> {b['cells']}), not the 2x that "twice the decode logic" suggested.
  {'It is cheaper than assumed because some opcodes are their own inverse, so the closure has fewer than eight distinct instructions.' if involutions else 'The opcode count doubles and the logic grows sublinearly, because the datapath is shared and only the decode widens.'}

  Against Pass 4252's thermodynamics: the four-opcode machine has infinite stationary
  entropy production, the closure has exactly zero.  So {ratio:.2f}x the combinational area buys
  the difference between a machine whose trajectory reveals the direction of time and one
  that runs thermodynamically free.

  Scope: cell counts are yosys generic-gate counts after abc mapping, not a standard-cell
  library, so the ratio is meaningful and the absolute numbers are not a tape-out estimate.""")
    else:
        print("\n  synthesis did not complete; see the errors above")
        for k, v in results.items():
            if "error" in v:
                print(f"    {k}: {v['error'][:200]}")

    out = {"isa4": [n for n, _, _ in ISA], "closure": [n for n, _, _ in ops8],
           "closure_size": len(ops8), "self_inverse_count": involutions,
           "synthesis": results}
    p = ROOT / "data" / "PART_W33_PASS4279_REVERSIBLE_CLOSURE_GATE_COST.json"
    p.parent.mkdir(exist_ok=True)
    # Hash the ROUND-TRIPPED object, never the live dict (CLAUDE.md, Pass 2482).
    p.write_text(json.dumps(json.loads(json.dumps(out)), indent=2, sort_keys=True) + "\n",
                 encoding="utf-8")
    print(f"\nwrote {p.relative_to(ROOT).as_posix()}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
