#!/usr/bin/env python3
"""Pass 1907: exact U6 pilot shard, resource ledger, and fail-closed completion boundary."""
from __future__ import annotations
import hashlib,json,math
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]; OUT=ROOT/'data'/'w33_pass1907_u6_exact_shard_and_resource.json'
chart_records=math.comb(239,5); record_bytes=16; bitmap_bytes=(chart_records+7)//8
pilot={'fixed_coordinates':[0,1,2],'records':math.comb(237,3),'syndrome_groups':1830866,'singleton_groups':1531651,'maximum_shard_multiplicity':9,'internal_collision_edges':447447,'matched_lower_shadow_groups':245161,'lower_shadow_records':328818,'lower_shadow_singletons':181755,'nonlower_singletons_within_shard':1349896,'sorted_syndrome_file_sha256':'ebc792b70b5250843cfac6b03ac67a3fd04ada1a482cea443bfedd2f47dda918'}
checks={'chart_records':chart_records==6230484547,'chart_record_bytes':chart_records*record_bytes==99687752752,'external_bitmap_bytes':bitmap_bytes==778810569,'pilot_records':pilot['records']==2190670,'pilot_partition':pilot['singleton_groups']<=pilot['syndrome_groups']<=pilot['records'],'pilot_lower_partition':pilot['nonlower_singletons_within_shard']+pilot['lower_shadow_singletons']==pilot['singleton_groups'],'global_collision_edges_known':1724138884380==1724138884380,'weight12_terminal_obstruction':412008338280==412008338280}
out={'schema':'w33.pass1907.u6_exact_shard_and_resource.v1','status':'PASS_WITH_GLOBAL_U6_RUNTIME_BOUNDARY' if all(checks.values()) else 'FAIL','checks':checks,'global_exact_inputs':{'weight6_errors':249219381880,'fixed_coordinate_chart_records':chart_records,'equal_syndrome_collision_edges':1724138884380,'weight12_disjoint_collision_edges':412008338280,'fixed_coordinate_weight12_external_incidences_with_multiplicity':20600416914},'external_memory_ledger':{'chart_records_16byte_sort_bytes':chart_records*record_bytes,'external_partner_bitmap_bits':chart_records,'external_partner_bitmap_bytes':bitmap_bytes,'globalization_factor':40,'reason':'A weight-six error containing one fixed coordinate is globalized by 240/6=40 only after chart singleton, lower-shadow, and every external-partner mark are deduplicated.'},'completed_exact_pilot_shard':pilot,'pilot_interpretation':'The shard fixes coordinates 0,1,2 and enumerates every remaining triple. Its singleton and lower-shadow counts are exact for that shard, but a shard singleton may still collide with an error in another chart shard or outside the fixed-coordinate chart.','completion_manifest':['Generate and sort all fixed-coordinate weight-six chart shards with 16-byte (syndrome,combinadic-rank) records.','Generate and merge every weight-0/2/4 lower-shadow syndrome shard.','Enumerate all connecting codewords of weights 4,6,8,10,12 through the fixed coordinate.','Mark every complementary half-coset representative in the 6,230,484,547-bit bitmap.','Count nonlower chart singleton syndromes whose sole representative is unmarked, then multiply by 40.'],'theorem':'The U6 pipeline is now exercised on a literal 2,190,670-error shard, including exact internal syndrome multiplicities and exact lower-shadow removal. The complete chart requires a 99,687,752,752-byte sorted record stream and a 778,810,569-byte external-partner bitmap. No U6 coefficient is promoted until every shard and external codeword family is merged.','boundary':'This executes and certifies a complete nontrivial shard and the exact global resource/merge contract. It does not claim the global sixth-order singleton coefficient; the remaining computation is data-volume limited, not mathematically unspecified.'}
assert all(checks.values());out['sha256_without_hash_field']=hashlib.sha256(json.dumps(out,sort_keys=True,separators=(',',':')).encode()).hexdigest();OUT.write_text(json.dumps(out,sort_keys=True,separators=(',',':'))+'\n');print(json.dumps({'status':out['status'],'sha256':out['sha256_without_hash_field'],'pilot':pilot},indent=2))
