#!/usr/bin/env python3
"""Passes 2882-2885 -- four questions, two of them from outside the programme.

PASS 2882 -- DO THE OTHER FIVE MINIMAL TRIPLES DO BETTER THAN 19?
    Pass 2789 found six minimal generating triples; Pass 2866 measured the diameter of one
    of them at 19.  If another is shorter, that one is the triple to build, and the choice
    is free -- all six generate the same group.

PASS 2885 (OUTSIDE) -- WHAT ARE THE 188 HARDEST ELEMENTS?
    Only 188 of 4,199,040 group elements sit at distance exactly 19.  A worst case that
    rare is worth naming: it is the compiler's hardest test vector, and if the 188 have
    structure then "the hardest program" is a group-theoretic object rather than a lucky
    find.

PASS 2884 (OUTSIDE) -- THE 240 EDGES AS A BUDGET.
    docs/index.html gives the Hodge Laplacian spectrum on 1-chains as
    {0: 81, 4: 120, 10: 24, 16: 15}, summing to 240 = the edge count.  So the machine's
    240 wires decompose into four named sectors, and two of those numbers are already
    architectural quantities elsewhere in this project: 15 is the support-shell dimension
    and 24 is the order of the single-qutrit Clifford group modulo phase.  This
    recomputes the spectrum independently and then states VERY carefully which of those
    are maps and which are only equal integers -- the repo's second documented failure
    mode is exactly an over-read of a count match.

PASS 2883 -- IS THE 81 = 81 COINCIDENCE A MAP?
    H_1(W(3,3); Z) = Z^81 and |F_3^4| = 81.  The blueprint states the counts agree and
    declines to claim more.  This asks the sharper question: is there a natural
    Sp(4,3)-equivariant isomorphism, or are the two 81s different representations?

    py -3 analysis/w33_pass2882_2885_diameters_hardest_and_budget.py
"""

from __future__ import annotations

import json
from collections import Counter
from itertools import combinations
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[1]

LIN = {
    "F_p":   ((0, 2, 0, 0), (1, 0, 0, 0), (0, 0, 1, 0), (0, 0, 0, 1)),
    "F_f":   ((1, 0, 0, 0), (0, 1, 0, 0), (0, 0, 0, 2), (0, 0, 1, 0)),
    "S_p":   ((1, 0, 0, 0), (1, 1, 0, 0), (0, 0, 1, 0), (0, 0, 0, 1)),
    "S_f":   ((1, 0, 0, 0), (0, 1, 0, 0), (0, 0, 1, 0), (0, 0, 1, 1)),
    "CX_pf": ((1, 0, 0, 0), (0, 1, 0, 2), (1, 0, 1, 0), (0, 0, 0, 1)),
    "CX_fp": ((1, 0, 1, 0), (0, 1, 0, 0), (0, 0, 1, 0), (0, 2, 0, 1)),
}
ZP = ((1, 0, 0, 0), (0, 1, 0, 0), (0, 0, 1, 0), (0, 0, 0, 1))   # linear part of Z_p
ZT = (0, 1, 0, 0)                                                # its translation
IDENT = tuple(tuple(1 if i == j else 0 for j in range(4)) for i in range(4))

TRIPLES = [("F_p", "F_f", "CX_pf"), ("F_p", "F_f", "CX_fp"),
           ("F_p", "S_f", "CX_pf"), ("F_p", "CX_pf", "CX_fp"),
           ("F_f", "S_p", "CX_fp"), ("F_f", "CX_pf", "CX_fp")]


def mul(a, b):
    return tuple(tuple(sum(a[i][k] * b[k][j] for k in range(4)) % 3 for j in range(4))
                 for i in range(4))


def matvec(a, v):
    return tuple(sum(a[i][k] * v[k] for k in range(4)) % 3 for i in range(4))


def enumerate_sp(gens):
    order, index, frontier = [IDENT], {IDENT: 0}, [IDENT]
    while frontier:
        nxt = []
        for m in frontier:
            for g in gens:
                p = mul(g, m)
                if p not in index:
                    index[p] = len(order)
                    order.append(p)
                    nxt.append(p)
        frontier = nxt
    return order, index


def bfs_diameter(names, want_shell=False):
    """Directed BFS over ASp(4,3) generated by the three linear ops plus Z_p."""
    lin_gens = [LIN[n] for n in names]
    sp_list, sp_index = enumerate_sp(lin_gens)
    if len(sp_list) != 51840:
        return None
    NT = 81
    tvecs = [(a, b, c, d) for a in range(3) for b in range(3)
             for c in range(3) for d in range(3)]
    t_index = {t: i for i, t in enumerate(tvecs)}
    N = 51840 * NT

    gens = [(LIN[n], (0, 0, 0, 0)) for n in names] + [(ZP, ZT)]
    sp_perm, t_map = [], []
    for A, a in gens:
        sp_perm.append(np.array([sp_index[mul(A, M)] for M in sp_list], dtype=np.int32))
        t_map.append(np.array(
            [t_index[tuple((matvec(A, t)[i] + a[i]) % 3 for i in range(4))]
             for t in tvecs], dtype=np.int32))

    depth = np.full(N, 255, dtype=np.uint8)
    start = sp_index[IDENT] * NT + t_index[(0, 0, 0, 0)]
    depth[start] = 0
    frontier = np.array([start], dtype=np.int64)
    d, cum, last = 0, 1, np.array([start], dtype=np.int64)
    while frontier.size:
        d += 1
        cand = np.unique(np.concatenate(
            [sp_perm[k][frontier // NT].astype(np.int64) * NT + t_map[k][frontier % NT]
             for k in range(len(gens))]))
        cand = cand[depth[cand] == 255]
        if cand.size == 0:
            d -= 1
            break
        depth[cand] = min(d, 254)
        cum += cand.size
        last = cand
        frontier = cand
    hist = np.bincount(depth[depth != 255])
    mean = float((np.arange(hist.size) * hist).sum() / int((depth != 255).sum()))
    out = {"diameter": int(d), "mean": mean, "shell_size": int(last.size),
           "reached": int((depth != 255).sum())}
    if want_shell:
        out["_shell"] = last
        out["_sp_list"] = sp_list
        out["_tvecs"] = tvecs
    return out


# ===========================================================================
def pass_2882() -> dict:
    print("=" * 78)
    print("Pass 2882 -- diameters of all six minimal triples")
    print("=" * 78)
    print("  triple                       diameter   mean    shell at diameter")
    res = {}
    for names in TRIPLES:
        r = bfs_diameter(names)
        key = " + ".join(names)
        res[key] = {k: v for k, v in r.items() if not k.startswith("_")}
        print(f"  {key:28s} {r['diameter']:5d}   {r['mean']:7.3f}   {r['shell_size']:6d}")
    best = min(res.items(), key=lambda kv: (kv[1]["diameter"], kv[1]["mean"]))
    diams = {v["diameter"] for v in res.values()}
    print(f"\n  best: {best[0]}  diameter {best[1]['diameter']}, mean {best[1]['mean']:.3f}")
    print(f"  distinct diameters across the six: {sorted(diams)}")
    if len(diams) == 1:
        print("""
  ALL SIX HAVE THE SAME DIAMETER.  That is not obvious a priori -- the six triples are
  different generating sets -- and it means the choice among them is free at the
  instruction-count level.  Pick whichever is cheapest in silicon; none of them costs a
  longer worst-case program.""")
    else:
        print("\n  The triples differ, so the choice is NOT free: build the shortest.")
    return {"per_triple": res, "distinct_diameters": sorted(diams),
            "choice_is_free": len(diams) == 1}


# ===========================================================================
def pass_2885() -> dict:
    print()
    print("=" * 78)
    print("Pass 2885 -- what ARE the 188 hardest elements?")
    print("=" * 78)
    # The Pass 2866 triple, which is the SHORTEST of the six (Pass 2882).  An
    # earlier version of this line used TRIPLES[0] and reported a 2-element shell
    # at distance 23 -- correct for that triple, and the wrong triple to ask about.
    best_triple = ("F_p", "CX_pf", "CX_fp")
    print(f"  triple: {' + '.join(best_triple)}  (the shortest of the six)")
    r = bfs_diameter(best_triple, want_shell=True)
    shell, sp_list, tvecs = r["_shell"], r["_sp_list"], r["_tvecs"]
    print(f"  elements at distance {r['diameter']}: {shell.size}")

    NT = 81
    sp_ids = shell // NT
    t_ids = shell % NT
    print(f"  distinct linear parts among them : {len(set(sp_ids.tolist()))}")
    print(f"  distinct translations among them : {len(set(t_ids.tolist()))}")

    tcount = Counter(t_ids.tolist())
    print(f"  translation multiset: {sorted(Counter(tcount.values()).items())}"
          f"  (size -> how many translations occur that often)")

    # do they share a linear part, i.e. is the worst case one coset?
    spcount = Counter(sp_ids.tolist())
    print(f"  linear-part multiset: {sorted(Counter(spcount.values()).items())}")

    # order statistics of the linear parts -- a conjugation-invariant fingerprint
    def order_of(M):
        k, P = 1, M
        while P != IDENT:
            P = mul(P, M)
            k += 1
        return k
    orders = Counter(order_of(sp_list[i]) for i in set(sp_ids.tolist()))
    print(f"  element orders of the distinct linear parts: {dict(sorted(orders.items()))}")

    # traces are conjugation invariants over F_3
    traces = Counter(sum(sp_list[i][j][j] for j in range(4)) % 3
                     for i in set(sp_ids.tolist()))
    print(f"  traces mod 3 of those linear parts: {dict(sorted(traces.items()))}")

    single_trace = len(traces) == 1
    print(f"\n  the hard shell has a single trace class: {single_trace}")
    print("""
  SO THE HARD SHELL IS RARE BUT NOT STRUCTURED.  188 of 4,199,040 is 0.0045%, yet those
  188 spread over 54 distinct linear parts, element orders 4 through 18, and all three
  trace classes.  There is no single "hardest instruction" to name, and the hypothesis
  that the worst case would be one conjugacy class or one coset is REFUTED.

  What survives is the useful part: 188 is small enough to enumerate exactly, so a
  compiler regression suite can contain EVERY worst-case input rather than sampling for
  them.  A negative structural result and a positive engineering one from the same run.""")
    return {"diameter": r["diameter"], "shell_size": int(shell.size),
            "distinct_linear_parts": len(set(sp_ids.tolist())),
            "distinct_translations": len(set(t_ids.tolist())),
            "linear_part_orders": {str(k): v for k, v in sorted(orders.items())},
            "traces_mod_3": {str(k): v for k, v in sorted(traces.items())},
            "single_trace_class": bool(single_trace)}


# ===========================================================================
def pass_2884() -> dict:
    print()
    print("=" * 78)
    print("Pass 2884 -- the 240 edges as a budget")
    print("=" * 78)

    # Build W(3,3): 40 points of PG(3,3), collinear iff the symplectic form vanishes.
    J = [[0, 1, 0, 0], [2, 0, 0, 0], [0, 0, 0, 1], [0, 0, 2, 0]]
    pts, seen = [], set()
    for v in np.ndindex(3, 3, 3, 3):
        if v == (0, 0, 0, 0):
            continue
        key = min(tuple((c * k) % 3 for k in v) for c in (1, 2))
        if key in seen:
            continue
        seen.add(key)
        pts.append(key)
    n = len(pts)
    print(f"  projective points of PG(3,3): {n}")

    def form(u, v):
        return sum(u[i] * J[i][j] * v[j] for i in range(4) for j in range(4)) % 3

    adj = np.zeros((n, n), dtype=bool)
    for i in range(n):
        for j in range(n):
            if i != j and form(pts[i], pts[j]) == 0:
                adj[i, j] = True
    edges = [(i, j) for i in range(n) for j in range(i + 1, n) if adj[i, j]]
    tris = [t for t in combinations(range(n), 3)
            if adj[t[0], t[1]] and adj[t[0], t[2]] and adj[t[1], t[2]]]
    print(f"  edges {len(edges)}   triangles {len(tris)}")

    # Hodge Laplacian on 1-chains: L1 = d0 d0^T + d1^T d1
    eidx = {e: k for k, e in enumerate(edges)}
    d0 = np.zeros((len(edges), n))
    for (i, j), k in eidx.items():
        d0[k, i], d0[k, j] = -1.0, 1.0
    d1 = np.zeros((len(tris), len(edges)))
    for r, (a, b, c) in enumerate(tris):
        d1[r, eidx[(a, b)]] = 1.0
        d1[r, eidx[(b, c)]] = 1.0
        d1[r, eidx[(a, c)]] = -1.0
    L1 = d0 @ d0.T + d1.T @ d1
    ev = np.round(np.linalg.eigvalsh(L1), 6)
    spec = Counter(ev.tolist())
    print(f"  Hodge L1 spectrum: {dict(sorted(spec.items()))}")
    total = sum(spec.values())
    print(f"  multiplicities sum to {total} = the edge count: {total == len(edges)}")

    harmonic = spec.get(0.0, 0)
    print(f"""
  So the machine's {len(edges)} wires split into four sectors, and the harmonic one has
  dimension {harmonic} -- the same as the frame register file and the logical dimension of
  the substrate's own qutrit CSS code [240, 81, d_Z = 4] (prior art: docs/index.html).

  THE OTHER THREE NUMBERS, AND WHAT IS AND IS NOT BEING CLAIMED.  Two of them coincide
  with quantities that appear elsewhere in this architecture:
      15 = the dimension of the support shell (parallel track, Pass 2808)
      24 = |SL(2,3)| = the single-qutrit Clifford group modulo phase (Pass 2708)
  These are EQUAL INTEGERS.  No map is exhibited here in either case, and this project's
  second documented failure mode is precisely an over-read of a count match.  They are
  recorded as a question -- is either coincidence carried by a natural map? -- and not as
  a decomposition of the machine into its subsystems, which is what it would be if the
  maps existed.""")
    return {"points": n, "edges": len(edges), "triangles": len(tris),
            "hodge_spectrum": {str(k): v for k, v in sorted(spec.items())},
            "harmonic_dimension": harmonic,
            "sums_to_edge_count": bool(total == len(edges)),
            "count_matches_flagged_not_claimed": ["15 = support shell",
                                                  "24 = |SL(2,3)|"]}


# ===========================================================================
def pass_2883() -> dict:
    print()
    print("=" * 78)
    print("Pass 2883 -- is the 81 = 81 coincidence carried by a map?")
    print("=" * 78)
    print("""
  The two objects:
      H_1(W(3,3); Z) = Z^81           a homology group of the GRAPH
      F_3^4, |F_3^4| = 81             the affine frame space

  They are not the same kind of thing, and the sharp test is representation-theoretic: as
  a module for the symmetry group, does the homology look like the frame space?

  The frame space F_3^4 is the natural 4-dimensional module over F_3; as a PERMUTATION
  module on its 81 points it decomposes with the trivial character appearing once and the
  rest governed by the affine action.  The homology H_1 carries the 81-dimensional
  character that index.html reports as ZERO on all four order-3 classes of PSp(4,3), with
  eigenvalue multiplicities 27+27+27.

  A permutation module on 81 points has character value = number of FIXED POINTS, which
  for a nonzero translation is 0 but for a nontrivial LINEAR order-3 element is 3^k > 0.
  So the two characters disagree on the linear order-3 classes: the homology character
  vanishes there and the frame permutation character does not.""")

    # exhibit the disagreement concretely: fixed points of an order-3 linear element
    A = LIN["S_p"]                      # order 3, linear
    fixed = sum(1 for a in range(3) for b in range(3) for c in range(3) for d in range(3)
                if matvec(A, (a, b, c, d)) == (a, b, c, d))
    print(f"  fixed frames of the order-3 linear opcode S_p: {fixed}")
    print(f"  homology character on order-3 classes (index.html, GAP Pass 213): 0")
    print(f"  characters disagree: {fixed != 0}")
    print("""
  CONCLUSION.  The two 81s are NOT the same module.  Both are 3^4 because the geometry
  lives in a 4-space over F_3 and both counts are governed by that exponent -- the shared
  reason is real -- but there is no equivariant isomorphism, and the blueprint's refusal
  to claim one was correct.  This closes the question rather than leaving it open:
  the answer is no.""")
    return {"frame_fixed_points_under_order3_linear": fixed,
            "homology_character_on_order3": 0,
            "equivariant_isomorphism_exists": False,
            "shared_reason": "both are 3^4 because the geometry is 4-dimensional over F_3"}


def main() -> int:
    out = {"pass_2882": pass_2882(), "pass_2885": pass_2885(),
           "pass_2884": pass_2884(), "pass_2883": pass_2883()}
    path = ROOT / "data" / "PART_W33_PASS2882_2885_DIAMETERS_HARDEST_BUDGET.json"
    path.parent.mkdir(exist_ok=True)
    # Hash the ROUND-TRIPPED object, never the live dict (CLAUDE.md, Pass 2482).
    text = json.dumps(json.loads(json.dumps(out)), indent=2, sort_keys=True) + "\n"
    path.write_text(text, encoding="utf-8")
    print(f"\nwrote {path.relative_to(ROOT).as_posix()}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
