#!/usr/bin/env python3
"""Close the final Hesse36 compiler conjugation pair in the frozen physical gauge.

The full-Clifford gauge audit leaves two character assignments on the three
safe center sheets beta=0,1,2:
    (0,1,2) and (0,2,1).
They are exchanged by complex conjugation and cannot be distinguished by the
real E6 cubic signs or integer Qpsi/parity data.

This file asks a narrower, type-correct question: once the repository's
already-frozen physical external-A2 Heisenberg orientation is imposed, which
assignment uses the same oriented center generator?

The required transport is explicit in prior certificates:
  * the full 648 compiler quotient H54/H18 is generated by the address center
        z_addr=(0,0,1);
  * the physical Clifford dictionary uses the same physical H27 normal form
        Z^a X^b z^c
    and its distinguished central-z record has coordinates (0,0,1);
  * the physical external-A2 root theorem identifies that generator with
        Z_FI = exp(2*pi*i Qpsi/3) = omega I
    in the frozen Pass5727 orientation, giving Z X = omega X Z.

Therefore the orientation-preserving character assignment is the identity
beta -> beta:
    (0,1,2).
The conjugate assignment beta -> -beta is exactly the opposite center/Coxeter
orientation and sends omega -> omega^2.

This is a gauge/convention closure relative to an already-fixed physical root
orientation. It is NOT a dynamical spontaneous-chirality or vacuum-selection
theorem.
"""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "data/w33_hesse36_physical_fi_orientation_selector.json"


def main(write=True):
    audit = json.loads(
        (ROOT / "data/w33_hesse36_compiler_gauge_selector_audit.json").read_text()
    )
    full = json.loads(
        (ROOT / "data/w33_hesse36_full_clifford648_fourier_compiler.json").read_text()
    )
    physical = json.loads(
        (ROOT / "data/w33_physical_external_a2_h27.json").read_text()
    )
    bridge = json.loads(
        (ROOT / "data/w33_physical_a2_clifford648_w33_stabilizer_bridge.json").read_text()
    )
    dictionary = json.loads(
        (ROOT / "data/w33_physical_clifford648_full_permutation_dictionary.json").read_text()
    )

    assert audit["status"].startswith(
        "PASS_FULL_CLIFFORD_REDUCES_Q8_GAUGES_TO_CONJUGATE_PAIR"
    )
    survivors = [tuple(x) for x in audit["reduction"]["survivors"]]
    assert survivors == [(0, 1, 2), (0, 2, 1)]

    assert full["group"]["quotient"] == "H54/H18 = C3"
    assert full["group"]["quotient_generator"] == "address center z=(0,0,1)"

    assert dictionary["lift_gauge"]["physical_H27_normal_form"] == "Z^a X^b z^c"
    zidx = dictionary["distinguished_indices"]["central_z"]
    zrecord = dictionary["records"][zidx]
    assert zrecord["physical_H27_ZXz"] == [0, 0, 1]
    assert zrecord["SL23_matrix_row_major"] == [1, 0, 0, 1]
    assert zrecord["order"] == 3

    assert bridge["physical_E8_side"]["center"] == "physical FI/Qpsi Z3"
    assert bridge["physical_E8_side"]["normalizer_structure"] == "H27 : SL(2,3)"
    assert bridge["W33_side"]["quotient_matrix_set_equals_physical_SL23"] is True

    center = physical["H27"]["center"]
    orientation = physical["weyl_relations"]["pass5727_orientation"]
    assert center == "<Z_FI> = <exp(2*pi*i Qpsi/3)>"
    assert orientation == "Using X=Xminus and Z_FI=omega I gives Z X = omega X Z."

    # Safe-sheet order in the upstream selector is beta=0,1,2.
    beta_order = (0, 1, 2)
    orientation_preserving = tuple(beta_order)
    orientation_reversing = tuple((-b) % 3 for b in beta_order)
    assert orientation_preserving == survivors[0]
    assert orientation_reversing == survivors[1]

    # The chosen physical generator z=Z_FI has eigenvalue omega, so the
    # character indexed by beta must evaluate as omega^beta in the oriented
    # convention.  Conjugation replaces beta by -beta.
    character_values = ["1", "omega", "omega^2"]
    conjugate_values = ["1", "omega^2", "omega"]

    out = {
        "schema": "w33.hesse36_physical_fi_orientation_selector.v1",
        "status": "PASS_FROZEN_PHYSICAL_FI_ORIENTATION_SELECTS_COMPILER_ASSIGNMENT_0_1_2",
        "headline": (
            "The final Hesse36 compiler conjugation pair closes relative to the "
            "repository's frozen physical external-A2 orientation. The full compiler "
            "quotient is generated by address z=(0,0,1); the full physical Clifford "
            "dictionary identifies exactly that physical coordinate as central z; "
            "and the E8 root theorem fixes z=Z_FI=exp(2*pi*i Qpsi/3)=omega I in the "
            "Pass5727 orientation. Hence the orientation-preserving safe-sheet "
            "character assignment is beta -> beta, (0,1,2). Its surviving partner "
            "(0,2,1) is precisely the complex-conjugate/opposite-center orientation."
        ),
        "transport_chain": {
            "compiler_quotient": "H54/H18 = C3",
            "compiler_generator": [0, 0, 1],
            "dictionary_physical_normal_form": "Z^a X^b z^c",
            "dictionary_central_z_index": zidx,
            "dictionary_central_z_physical_coordinate": zrecord["physical_H27_ZXz"],
            "physical_center": center,
            "physical_orientation": orientation,
            "physical_normalizer": "H27 : SL(2,3)",
        },
        "selection": {
            "upstream_survivors": [list(x) for x in survivors],
            "safe_sheet_order": list(beta_order),
            "selected_assignment": list(orientation_preserving),
            "selected_character_values_on_z": character_values,
            "conjugate_assignment": list(orientation_reversing),
            "conjugate_character_values_on_z": conjugate_values,
            "selection_rule": (
                "use the already-frozen oriented generator z=Z_FI=omega I, so the "
                "beta sheet carries the character z -> omega^beta"
            ),
            "unique_relative_to_frozen_orientation": True,
            "absolute_orientation_without_frozen_convention": False,
        },
        "interpretation": (
            "The two gauges were never distinguishable by real cubic/Yukawa signs. "
            "They are the same finite compiler seen in the two conjugate qutrit "
            "orientations. The physical E8/H27 certificate already chose one "
            "orientation when it set Z_FI=omega I; requiring compiler coordinates "
            "to respect that choice removes the remaining bookkeeping ambiguity."
        ),
        "boundary": (
            "This is NOT a derivation of spontaneous CP/chirality selection, a "
            "heterotic vacuum choice, or a claim that nature dynamically prefers "
            "omega over omega^2. Reversing the frozen external-A2/Coxeter convention "
            "reverses the selected compiler assignment. The theorem only makes the "
            "compiler gauge consistent with the repository's already-fixed physical "
            "root-coordinate orientation."
        ),
        "parents": [
            "data/w33_hesse36_compiler_gauge_selector_audit.json",
            "data/w33_hesse36_full_clifford648_fourier_compiler.json",
            "data/w33_physical_external_a2_h27.json",
            "data/w33_physical_a2_clifford648_w33_stabilizer_bridge.json",
            "data/w33_physical_clifford648_full_permutation_dictionary.json",
        ],
        "checks": {
            "two_conjugate_survivors_loaded": True,
            "compiler_quotient_generator_is_address_center": True,
            "dictionary_central_z_is_physical_001": True,
            "physical_center_is_FI_Qpsi_Z3": True,
            "physical_orientation_sets_ZFI_equal_omega": True,
            "selected_assignment_is_0_1_2": True,
            "conjugate_assignment_is_0_2_1": True,
            "selection_is_only_relative_to_frozen_orientation": True,
        },
    }

    if write:
        OUT.write_text(json.dumps(out, indent=2) + "\n")
    return out


if __name__ == "__main__":
    print(json.dumps(main(True), indent=2))
