#!/usr/bin/env python3
"""Self-adjoint W(3,3) phase operator and classical-xi coefficient audit.

The restricted adjacency operator A_perp is self-adjoint with eigenvalues
2 (multiplicity 24) and -4 (multiplicity 15). Because W(3,3) is Ramanujan,
C=A_perp/(2*sqrt(11)) is a self-adjoint contraction. The phase operator
Theta=arccos(C) is therefore self-adjoint and factorizes the nontrivial Ihara
determinant exactly.

This file also performs the missing coefficient comparison with the classical
Hadamard product. A one-parameter scaling can match the quadratic coefficient,
but the scale-free quartic and sextic moment ratios do not match. Thus Theta
is a genuine finite Hilbert-Polya operator for graph-RH, not yet for classical RH.
"""

from __future__ import annotations

import json
import math
from pathlib import Path
from typing import Any

import mpmath as mp

ROOT = Path(__file__).resolve().parents[1]
BRANCH = 11
LOG_BRANCH = math.log(BRANCH)
SECTORS = (
    {"adjacency_eigenvalue": 2, "multiplicity": 24},
    {"adjacency_eigenvalue": -4, "multiplicity": 15},
)


def sector_angle(adjacency_eigenvalue: int) -> float:
    return math.acos(adjacency_eigenvalue / (2 * math.sqrt(BRANCH)))


def ihara_roots(adjacency_eigenvalue: int) -> tuple[complex, complex]:
    theta = sector_angle(adjacency_eigenvalue)
    radius = 1 / math.sqrt(BRANCH)
    return (
        radius * complex(math.cos(theta), math.sin(theta)),
        radius * complex(math.cos(theta), -math.sin(theta)),
    )


def ihara_factor(u: complex, adjacency_eigenvalue: int) -> complex:
    return 1 - adjacency_eigenvalue * u + BRANCH * u * u


def phase_factor(u: complex, adjacency_eigenvalue: int) -> complex:
    """Factor generated by the self-adjoint angle theta."""
    theta = sector_angle(adjacency_eigenvalue)
    return (
        (1 - math.sqrt(BRANCH) * complex(math.cos(theta), math.sin(theta)) * u)
        * (1 - math.sqrt(BRANCH) * complex(math.cos(theta), -math.sin(theta)) * u)
    )


def lifted_ordinates(adjacency_eigenvalue: int, n_min: int, n_max: int) -> list[float]:
    """Imaginary ordinates from u=11^{-s}, including logarithm branches."""
    theta = sector_angle(adjacency_eigenvalue)
    return [(theta + 2 * math.pi * n) / LOG_BRANCH for n in range(n_min, n_max + 1)]


def principal_phase_moments(max_power: int = 3) -> dict[int, float]:
    """S_{2k}=sum multiplicity/theta^{2k} for the principal phase operator."""
    return {
        2 * k: sum(
            sector["multiplicity"]
            / sector_angle(sector["adjacency_eigenvalue"]) ** (2 * k)
            for sector in SECTORS
        )
        for k in range(1, max_power + 1)
    }


def full_log_tower_moments(max_power: int = 3, cutoff: int = 5000) -> dict[int, float]:
    """Moment sums over the vertical arithmetic lattice induced by log branches."""
    moments: dict[int, float] = {}
    for k in range(1, max_power + 1):
        total = 0.0
        for sector in SECTORS:
            theta = sector_angle(sector["adjacency_eigenvalue"])
            total += sector["multiplicity"] * sum(
                (LOG_BRANCH / (theta + 2 * math.pi * n)) ** (2 * k)
                for n in range(-cutoff, cutoff + 1)
            )
        moments[2 * k] = total
    return moments


def completed_xi(s: complex | mp.mpc) -> mp.mpc:
    z = mp.mpc(s)
    return (
        mp.mpf("0.5")
        * z
        * (z - 1)
        * mp.power(mp.pi, -z / 2)
        * mp.gamma(z / 2)
        * mp.zeta(z)
    )


def classical_xi_log_moments(max_power: int = 3) -> dict[int, mp.mpf]:
    """Hadamard moment sums inferred from log xi(1/2+z)/xi(1/2).

    If log Xi(z)=sum_k (-1)^{k+1} S_{2k} z^{2k}/k, this returns S_{2k}.
    The derivatives exist independently of RH; interpreting them as positive
    ordinate moments is the Hilbert-Polya target.
    """
    mp.mp.dps = 80
    center = mp.mpf("0.5")
    normalizer = completed_xi(center)
    log_xi = lambda z: mp.log(completed_xi(center + z) / normalizer)
    moments: dict[int, mp.mpf] = {}
    for k in range(1, max_power + 1):
        derivative = mp.diff(log_xi, 0, 2 * k)
        coefficient = derivative / mp.factorial(2 * k)
        moments[2 * k] = ((-1) ** (k + 1)) * k * mp.re(coefficient)
    return moments


def ratio_invariants(moments: dict[int, float | mp.mpf]) -> dict[str, float]:
    s2 = float(moments[2])
    return {
        "S4_over_S2_squared": float(moments[4]) / s2**2,
        "S6_over_S2_cubed": float(moments[6]) / s2**3,
    }


def scaled_predictions(
    candidate: dict[int, float], target: dict[int, mp.mpf]
) -> dict[str, float]:
    scale = math.sqrt(candidate[2] / float(target[2]))
    return {
        "scale_matching_S2": scale,
        "predicted_S4": candidate[4] / scale**4,
        "target_S4": float(target[4]),
        "predicted_S6": candidate[6] / scale**6,
        "target_S6": float(target[6]),
        "relative_error_S4": abs(candidate[4] / scale**4 - float(target[4]))
        / abs(float(target[4])),
        "relative_error_S6": abs(candidate[6] / scale**6 - float(target[6]))
        / abs(float(target[6])),
    }


def build_certificate() -> dict[str, Any]:
    factor_checks = {}
    pole_checks = {}
    sectors = []
    for sector in SECTORS:
        eigenvalue = sector["adjacency_eigenvalue"]
        theta = sector_angle(eigenvalue)
        roots = ihara_roots(eigenvalue)
        sample_u = complex(0.07, -0.03)
        factor_checks[str(eigenvalue)] = abs(
            ihara_factor(sample_u, eigenvalue) - phase_factor(sample_u, eigenvalue)
        ) < 1e-12
        pole_checks[str(eigenvalue)] = all(
            abs(abs(root) - 1 / math.sqrt(BRANCH)) < 1e-12 for root in roots
        )
        sectors.append(
            {
                **sector,
                "theta": theta,
                "cos_theta": eigenvalue / (2 * math.sqrt(BRANCH)),
                "ihara_roots": [
                    {"real": r.real, "imag": r.imag, "modulus": abs(r)}
                    for r in roots
                ],
                "first_lifted_ordinates": lifted_ordinates(eigenvalue, -2, 2),
            }
        )

    principal = principal_phase_moments()
    tower = full_log_tower_moments()
    classical = classical_xi_log_moments()

    principal_ratios = ratio_invariants(principal)
    tower_ratios = ratio_invariants(tower)
    classical_ratios = ratio_invariants(classical)
    principal_fit = scaled_predictions(principal, classical)
    tower_fit = scaled_predictions(tower, classical)

    checks = {
        "phase_operator_is_self_adjoint": True,
        "normalized_adjacency_is_contraction": all(
            abs(sector["adjacency_eigenvalue"]) < 2 * math.sqrt(BRANCH)
            for sector in SECTORS
        ),
        "phase_factorization_exact": all(factor_checks.values()),
        "graph_poles_on_critical_circle": all(pole_checks.values()),
        "principal_operator_fails_classical_scale_free_ratios": abs(
            principal_ratios["S4_over_S2_squared"]
            - classical_ratios["S4_over_S2_squared"]
        )
        > 1e-3,
        "log_tower_fails_classical_scale_free_ratios": abs(
            tower_ratios["S4_over_S2_squared"]
            - classical_ratios["S4_over_S2_squared"]
        )
        > 1e-3,
        "finite_matrix_cannot_equal_entire_xi": True,
    }

    return {
        "status": "PASS" if all(checks.values()) else "FAIL",
        "operator": {
            "definition": "Theta_W = arccos(A_perp/(2*sqrt(11)))",
            "dimension": 39,
            "self_adjoint": True,
            "exact_determinant_identity": (
                "det(I-2*sqrt(11)*u*cos(Theta_W)+11*u^2 I) "
                "= (1-2u+11u^2)^24(1+4u+11u^2)^15"
            ),
            "sectors": sectors,
        },
        "coefficient_comparison": {
            "classical_xi_log_moments": {
                str(k): mp.nstr(v, 30) for k, v in classical.items()
            },
            "principal_phase_moments": {str(k): v for k, v in principal.items()},
            "full_log_tower_moments_cutoff_5000": {
                str(k): v for k, v in tower.items()
            },
            "scale_free_ratios": {
                "classical": classical_ratios,
                "principal_phase": principal_ratios,
                "full_log_tower": tower_ratios,
            },
            "principal_one_scale_fit": principal_fit,
            "tower_one_scale_fit": tower_fit,
            "verdict": (
                "the exact W33 phase operator reproduces graph-RH but not the first "
                "three classical xi Hadamard coefficients under a single scale"
            ),
        },
        "transfer_obstruction": {
            "finite_dimension": (
                "a finite determinant is a polynomial and cannot equal xi, which has "
                "infinitely many nontrivial zeros"
            ),
            "log_lift": (
                "the multivalued logarithm creates rigid arithmetic vertical towers; "
                "their coefficient ratios still disagree with classical xi"
            ),
            "next_operator_target": (
                "an infinite self-adjoint W33 tower with a trace-class regularized "
                "determinant and coefficient equality to xi"
            ),
        },
        "checks": checks,
    }


def main() -> None:
    payload = build_certificate()
    output = ROOT / "data" / "w33_rh_phase_operator_certificate.json"
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(json.dumps(payload, indent=2), encoding="utf-8")
    print(json.dumps(payload, indent=2))
    print(f"wrote {output}")


if __name__ == "__main__":
    main()
