// Pass5176: exact connected radius-six census for the provenance-refined q=3 decoder.
// Input is generated by w33_pass5176_q3_radius6_graph_export.py.
#include <algorithm>
#include <array>
#include <cstdint>
#include <fstream>
#include <iostream>
#include <string>
#include <unordered_set>
#include <utility>
#include <vector>
using namespace std;

static vector<vector<int>> adjv;
static vector<array<int,6>> charts;
static vector<vector<pair<int,int>>> ach;
static int leadarr[8]={0,8,16,1,32,2,4,0};

static int syn(int m){
    int s=0;
    s|=((((m>>0)&1)^((m>>1)&1)^((m>>3)&1))<<0);
    s|=((((m>>0)&1)^((m>>2)&1)^((m>>4)&1))<<1);
    s|=((((m>>1)&1)^((m>>2)&1)^((m>>5)&1))<<2);
    return s;
}
static bool hasAdj(int a,int b){
    auto &v=adjv[a]; return binary_search(v.begin(),v.end(),b);
}
static uint64_t packv(vector<int> v){
    sort(v.begin(),v.end()); uint64_t k=0;
    for(size_t i=0;i<v.size();++i)k|=(uint64_t)v[i]<<(11*i);
    return k;
}
static vector<int> unpack(uint64_t k,int cnt){
    vector<int> v(cnt);for(int i=0;i<cnt;i++)v[i]=(k>>(11*i))&2047;return v;
}

struct Sweep { vector<int> corr; int maxvote=0,maxsingleton=0,mindeg=0; };

static Sweep refinedSweep(const vector<int>& errs){
    int touched[24],masks[24],nt=0;
    auto addmask=[&](int ci,int bit){
        for(int i=0;i<nt;i++)if(touched[i]==ci){masks[i]^=bit;return;}
        touched[nt]=ci;masks[nt]=bit;nt++;
    };
    for(int a:errs)for(auto [ci,pos]:ach[a])addmask(ci,1<<pos);
    int cand[64],vcnt[64],sing[64],nc=0;
    auto addvote=[&](int a,bool singleton){
        for(int i=0;i<nc;i++)if(cand[i]==a){vcnt[i]++;if(singleton)sing[i]++;return;}
        cand[nc]=a;vcnt[nc]=1;sing[nc]=singleton?1:0;nc++;
    };
    for(int i=0;i<nt;i++){
        int m=masks[i],lm=leadarr[syn(m)];if(!lm)continue;
        int p=__builtin_ctz((unsigned)lm),a=charts[touched[i]][p];
        bool singleton=(__builtin_popcount((unsigned)m)==1 && ((m>>p)&1));
        addvote(a,singleton);
    }
    Sweep out;if(!nc)return out;
    for(int i=0;i<nc;i++)out.maxvote=max(out.maxvote,vcnt[i]);
    vector<int>M;
    for(int i=0;i<nc;i++)if(vcnt[i]==out.maxvote)M.push_back(i);
    for(int i:M)out.maxsingleton=max(out.maxsingleton,sing[i]);
    vector<int>F;
    for(int i:M)if(sing[i]==out.maxsingleton)F.push_back(i);
    out.mindeg=999;
    vector<pair<int,int>> deg;
    for(int i:F){
        int d=0;for(int j:F)if(i!=j&&hasAdj(cand[i],cand[j]))d++;
        deg.push_back({i,d});out.mindeg=min(out.mindeg,d);
    }
    for(auto [i,d]:deg)if(d==out.mindeg)out.corr.push_back(cand[i]);
    sort(out.corr.begin(),out.corr.end());return out;
}

static bool subset(const vector<int>& a,const vector<int>& E){
    for(int x:a)if(!binary_search(E.begin(),E.end(),x))return false;return true;
}

static bool hubOnlyFailsKnownWitness(){
    // Under pure max-vote -> minimum tie-degree, this connected weight-six witness
    // has a 9-vertex 4-regular max-vote tie containing three false coordinates.
    vector<int>E={0,219,492,493,526,527};
    // Recompute the max-vote set without singleton filtering.
    int touched[24],masks[24],nt=0;
    auto addmask=[&](int ci,int bit){for(int i=0;i<nt;i++)if(touched[i]==ci){masks[i]^=bit;return;}touched[nt]=ci;masks[nt]=bit;nt++;};
    for(int a:E)for(auto [ci,pos]:ach[a])addmask(ci,1<<pos);
    int cand[64],vcnt[64],nc=0;
    auto addvote=[&](int a){for(int i=0;i<nc;i++)if(cand[i]==a){vcnt[i]++;return;}cand[nc]=a;vcnt[nc]=1;nc++;};
    for(int i=0;i<nt;i++){int lm=leadarr[syn(masks[i])];if(lm)addvote(charts[touched[i]][__builtin_ctz((unsigned)lm)]);}
    int z=0;for(int i=0;i<nc;i++)z=max(z,vcnt[i]);vector<int>M;for(int i=0;i<nc;i++)if(vcnt[i]==z)M.push_back(cand[i]);
    if(z!=2||M.size()!=9)return false;
    for(int a:M){int d=0;for(int b:M)if(a!=b&&hasAdj(a,b))d++;if(d!=4)return false;}
    return find(M.begin(),M.end(),494)!=M.end()&&find(E.begin(),E.end(),494)==E.end();
}

int main(int argc,char**argv){
    string path=argc>1?argv[1]:"/tmp/w33_pass5176_q3_graph.txt";
    ifstream f(path);int n,nc;if(!(f>>n>>nc))return 3;
    adjv.assign(n,{});for(int i=0;i<n;i++){adjv[i].resize(20);for(int&x:adjv[i])f>>x;sort(adjv[i].begin(),adjv[i].end());}
    charts.resize(nc);ach.assign(n,{});for(int ci=0;ci<nc;ci++)for(int p=0;p<6;p++){f>>charts[ci][p];ach[charts[ci][p]].push_back({ci,p});}
    if(n!=1620||nc!=1080||!hubOnlyFailsKnownWitness())return 4;

    unordered_set<uint64_t> cur,nxt;cur.insert(0);
    vector<size_t> expected={0,1,20,490,13269,381480,11401011};
    vector<int> maxSweeps(7,0);
    for(int size=1;size<=6;size++){
        if(cur.size()!=expected[size]){cerr<<"count mismatch size "<<size<<" got "<<cur.size()<<"\n";return 5;}
        size_t tested=0;
        for(uint64_t key:cur){
            vector<int>E={0};auto oth=unpack(key,size-1);E.insert(E.end(),oth.begin(),oth.end());sort(E.begin(),E.end());
            if(size<6){
                int steps=0;
                while(!E.empty()){
                    Sweep s=refinedSweep(E);if(s.corr.empty()||!subset(s.corr,E))return 6;
                    vector<int>N;set_symmetric_difference(E.begin(),E.end(),s.corr.begin(),s.corr.end(),back_inserter(N));E.swap(N);steps++;if(steps>4)return 7;
                }
                maxSweeps[size]=max(maxSweeps[size],steps);
            }else{
                Sweep s=refinedSweep(E);if(s.corr.empty()||!subset(s.corr,E)){
                    cerr<<"weight6 false correction after "<<tested<<" cases\n";return 8;
                }
            }
            tested++;
        }
        if(size==6)break;
        nxt.clear();size_t reserve=size==1?100:size==2?1000:size==3?30000:size==4?500000:12000000;nxt.reserve(reserve);
        for(uint64_t key:cur){
            auto oth=unpack(key,size-1);vector<int>verts={0};verts.insert(verts.end(),oth.begin(),oth.end());sort(verts.begin(),verts.end());
            vector<int>cand;cand.reserve(20*size);for(int v:verts)for(int u:adjv[v])cand.push_back(u);
            sort(cand.begin(),cand.end());cand.erase(unique(cand.begin(),cand.end()),cand.end());
            for(int u:cand){if(binary_search(verts.begin(),verts.end(),u))continue;auto no=oth;no.push_back(u);nxt.insert(packv(no));}
        }
        cur.swap(nxt);
    }
    if(maxSweeps[1]!=1||maxSweeps[2]!=1||maxSweeps[3]>2||maxSweeps[4]>2||maxSweeps[5]>3)return 9;
    cout<<"{\"status\":\"PASS\",\"connected_weight6\":11401011,\"hub_only_witness\":[0,219,492,493,526,527],\"hub_only_false\":494,\"refined_false_first_corrections\":0,\"radius5_max_sweeps\":3}\n";
    return 0;
}
