#!/usr/bin/env python3
"""Pass5309: the central quotient of Hoffman W(D4) is the published tomotope action.

Pass5308 gives N ~= W(D4), |N|=192.  Here we act on the 13 Hoffman cover
cells.  N has orbit structure 1+12, its center C2 is exactly the action kernel,
and the induced order-96 group on the 12 moving cells is permutation-conjugate
to the four published tomotope generators of Monson--Pellicer--Williams.
"""
from __future__ import annotations
import json
from pathlib import Path
from sympy.combinatorics import Permutation,PermutationGroup
from analysis.w33_pass5300_hoffman576_latin_group_bridge import q5_hoffman,COVER

ROOT=Path(__file__).resolve().parents[1]
OUT=ROOT/'data/PART_W33_PASS5309_HOFFMAN_TOMOTOPE_DEGREE12_ACTION.json'

def key(g):return tuple(g.array_form)
def cp(cycles):
    a=list(range(12))
    for cyc in cycles:
        for x,y in zip(cyc,cyc[1:]+cyc[:1]):a[x-1]=y-1
    return Permutation(a)
def gset(G):return {key(g) for g in G.generate_schreier_sims()}

def main():
    H,H13,_,_=q5_hoffman();els=list(H.generate_schreier_sims())
    N=PermutationGroup([g for g in els if int(g.order()) in (1,2,4)]);assert N.order()==192
    ci={c:i for i,c in enumerate(COVER)}
    N13=PermutationGroup([Permutation([ci[g(c)] for c in COVER]) for g in N.generators])
    assert N13.order()==96
    orbs=sorted(N13.orbits(),key=len);assert list(map(len,orbs))==[1,12]
    fixed=next(iter(orbs[0]));O=sorted(orbs[1])
    kernel=[g for g in N.generate_schreier_sims() if all(g(c)==c for c in COVER)]
    assert len(kernel)==2 and gset(PermutationGroup(kernel))==gset(N.center())

    # Restrict the 12-orbit to labels 0..11.
    NR=PermutationGroup([Permutation([O.index(g(x)) for x in O]) for g in N13.generators])
    assert NR.order()==96

    # Published tomotope generators, Ars Math. Contemp. 5 (2012), p.9.
    r0=cp([(5,10),(6,9),(7,12),(8,11)])
    r1=cp([(1,6),(2,5),(3,8),(4,7)])
    r2=cp([(5,9),(6,10),(7,11),(8,12)])
    r3=cp([(5,8),(6,7),(9,12),(10,11)])
    T=PermutationGroup([r0,r1,r2,r3]);assert T.order()==96

    # Explicit conjugating relabeling found by the F2^4 semidirect-module isomorphism.
    f=[0,3,9,5,6,10,1,4,11,2,8,7]
    P=Permutation(f)
    C=PermutationGroup([(~P)*g*P for g in NR.generators])
    assert gset(C)==gset(T)
    assert T.center().order()==1 and T.derived_subgroup().order()==48 and T.abelian_invariants()==[2]

    out={'pass':5309,'status':'THEOREM_HOFFMAN_WD4_CENTRAL_QUOTIENT_IS_PUBLISHED_TOMOTOPE_ACTION',
      'N_order':192,'N_structure':'W(D4)','cover_orbits':[1,12],'distinguished_cover_cell_index':fixed,
      'action_kernel_order':2,'action_kernel':'Z(W(D4))',
      'induced_degree12_order':96,'tomotope_published_group_order':96,
      'explicit_12point_conjugator':f,
      'statement':'After the displayed relabeling, the induced Hoffman action on the 12 moving cover cells is exactly the subgroup generated by the four published tomotope permutations.',
      'group_isomorphism':'W(D4)/Z(W(D4)) ~= Gamma(T)',
      'tomotope_structure':'((C2)^4:C3):C2 = (C2)^4:S3',
      'boundary':'This is an exact finite permutation-action theorem. The one fixed Hoffman cell is external to the 12-point tomotope action and is not assigned a geometric tomotope face without an additional incidence map.'}
    OUT.write_text(json.dumps(out,indent=2)+'\n');print(json.dumps(out,indent=2))
if __name__=='__main__':main()
