#!/usr/bin/env python3
from __future__ import annotations
import argparse,hashlib,json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1];OUT=ROOT/'data'/'w33_pass583_587_groupoid_intertwiner_johnson_local_blackwell_release.json'
FILES={583:ROOT/'data'/'w33_pass583_collision_groupoid_polynomial.json',584:ROOT/'data'/'w33_pass584_colored_intertwiner_a4.json',585:ROOT/'data'/'w33_pass585_singer_pentagon_triples.json',586:ROOT/'data'/'w33_pass586_cyclotomic_local_dvr.json',587:ROOT/'data'/'w33_pass587_infinite_horizon_blackwell_lift.json'}
def payload():
 raw={k:f.read_bytes() for k,f in FILES.items()};p={k:json.loads(raw[k]) for k in FILES}
 checks={'all_owner_certificates_pass':all(x['status']=='PASS' for x in p.values()),'owner_check_total61':sum(sum(x['checks'].values()) for x in p.values())==61,'exceptional_triple_closed_by_polynomial_S3':p[583]['checks']['two_transpositions_generate_S3'],'equivalence_groupoid_arrows3199632':p[583]['spectral_partition']['equivalence_groupoid_arrows']==3199632,'no_cubic_triangular_symmetry':p[583]['low_degree_no_go']['tested']==784 and not p[583]['low_degree_no_go']['survivors'],'explicit_C3_intertwiner':p[584]['C3_intertwiner']['equation']=='U_packet T = T P_colored','transported_A4_reduces_to_C3':len(p[584]['A4_transport']['spectral_symmetry_indices'])==3,'Singer_objects_are_triple_pentagon_pairs':p[585]['objectwise_model']['count']=='C(8,3)*6 = 56*6 = 336','Singer_six_fibre_is_S5_with_C3_kernel':p[585]['six_fibre']['image_order']==120 and p[585]['six_fibre']['kernel_order']==3,'E7_and_exterior_boundaries_preserved':p[585]['checks']['E7_branch_dimension_28_plus_28'] and p[585]['checks']['unsigned_wedge_obstruction'],'global_cyclotomic_order_nonlocal_corrected':p[586]['correction']['correct_sequence'].startswith('O5 -> Localization'),'localized_residue_degree1':p[586]['algebra']['residue_degree']==1,'localized_ramification_index4':p[586]['algebra']['ramification_index']==4,'local_unit_factor':p[586]['algebra']['unit_factor_residue_mod_lambda']==4,'all_baseline_policies_have_same_cost_lifts':p[587]['checks']['all_five_baseline_actions_have_same_cost_joint_lifts'],'global_infinite_horizon_nonworsening':p[587]['checks']['continuous_action_set_global_nonworsening'],'strict_Blackwell_condition_explicit':p[587]['checks']['strict_Blackwell_criterion_recorded'],'aspirational_tie_surface_M24':p[587]['checks']['aspirational_M24_tie_preserved']}
 custody={k:{'path':str(FILES[k].relative_to(ROOT)),'sha256':hashlib.sha256(raw[k]).hexdigest(),'check_count':sum(p[k]['checks'].values())} for k in FILES}
 return {'schema':'w33.pass583_587.groupoid_intertwiner_johnson_local_blackwell.release.v1','status':'PASS' if all(checks.values()) else 'FAIL','owner_check_total':sum(x['check_count'] for x in custody.values()),'owner_custody':custody,'headline':{'583':'The last exceptional triple is separated by packet covariants and closed by explicit degree-13 polynomial transpositions; all residual spectral collisions form a canonical finite equivalence groupoid.','584':'An explicit 12x12 F3 intertwiner identifies the colored 600-cell C3 module with the Hjelmslev packet module; exhaustive transport shows the full A4 is not spectral and only C3 survives.','585':'The 336 Singer objects are exactly pairs of a 3-subset and one of six Sylow-5 pentagons on its complement; the 56 Johnson quotient is the undecorated triple set and the fibre action is S5 with C3 kernel.','586':'The global cyclotomic order is correctly replaced by its localization at (lambda); the residue field is F5 and lambda^4=5u with u a local unit, yielding e=4 and f=1 arithmetically.','587':'Every infinite-horizon baseline policy has an explicit same-cost joint refinement, proving global continuous non-worsening and isolating strictness exactly to a decision-affinity condition; the aspirational uniform prior remains a candidate tie surface through M=24.'},'release_checks':checks,'boundary':'Exact for the finite polynomial-function groupoid, deterministic colored-module intertwiner, A8 Singer flag model, localized arithmetic, and declared readout experiment. No low-degree geometric generation of the full collision groupoid, universal no-go over all C3 intertwiners, objectwise W33/E6 identification of the 280-module, compiled DVR instance, or unconditional strict continuous infinite-horizon inequality on every interior belief is claimed.'}
def main():
 ap=argparse.ArgumentParser();ap.add_argument('--check',action='store_true');ap.add_argument('--output',type=Path,default=OUT);a=ap.parse_args();p=payload();s=json.dumps(p,sort_keys=True,separators=(',',':'))+'\n'
 if a.check:
  if not a.output.exists() or a.output.read_text()!=s:raise SystemExit('Passes 583-587 release certificate drift')
 else:a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(s)
 print(json.dumps({'status':p['status'],'checks':sum(p['release_checks'].values()),'total':len(p['release_checks']),'owners':p['owner_check_total']}));return 0 if p['status']=='PASS' else 1
if __name__=='__main__':raise SystemExit(main())
