#!/usr/bin/env python3
"""Pass5209: exact q=5 footprint-code hull and mod-four weight law.

Let F be the 156x325 W-point/P-component incidence matrix.  Pass5202 gives
rank_2 F=65 and ker(F^T)=the 91-dimensional W-line code.  Pass5201 gives
FF^T=J over F2.  Therefore C=im(F^T) has dimension 65, and the image of the
even-weight point-input subspace is exactly C cap C^perp, of dimension 64.
The odd-input coset is the other coset of this hull.

Every point row has weight 25.  Pass5186 gives pair intersections 5 for
collinear W-points and 1 for noncollinear W-points, hence every pair
intersection is odd.  For a sum of k point rows, inclusion-exclusion modulo 4
gives

 wt(sum r_i) = sum wt(r_i) - 2 sum_{i<j}|r_i cap r_j| (mod 4)
             = k - 2*C(k,2) = k(2-k) (mod 4).

The kernel ker(F^T) is generated by W-lines of even weight 6, so parity of k is
independent of the chosen point-row representation.  Consequently every hull
word has weight 0 mod4 and every word in the odd coset has weight 1 mod4.

The 156 point rows give weight-25 words.  Pair sums have weight 40 when the
points are collinear and 48 otherwise.  Thus the remaining d=25 problem is
sharply localized: below 25, only hull weights 4,8,12,16,20,24 and odd-coset
weights 1,5,9,13,17,21 can occur.
"""
from __future__ import annotations
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
OUT=ROOT/'data/PART_W33_PASS5209_Q5_FOOTPRINT_CODE_HULL_MOD4.json'

def main():
    q5={'length':325,'dimension':65,'hull_dimension':64,
        'point_rows':156,'point_row_weight':25,
        'collinear_pair_count':2340,'collinear_row_sum_weight':40,
        'noncollinear_pair_count':9750,'noncollinear_row_sum_weight':48}
    assert 25+25-2*5==40 and 25+25-2*1==48
    assert all((k-2*(k*(k-1)//2))%4==(0 if k%2==0 else 1) for k in range(20))
    out={'pass':5209,'status':'THEOREM_Q5_FOOTPRINT_CODE_HULL_AND_MOD4_WEIGHT_LAW',
      'code':'C_F=im_F2(F^T) <= F2^325','parameters_known':'[325,65,d]_2 with d<=25',
      'Gram_mod2':'F F^T=J',
      'kernel':'ker(F^T) is the 91-dimensional W(3,5) line code (Pass5202), generated by even weight-6 lines.',
      'hull':'C_F cap C_F^perp is exactly the image of even-weight point inputs and has dimension 64.',
      'weight_congruence':'Hull words have weight 0 mod4; the other coset has weight 1 mod4.',
      'mod4_proof':'For k point rows, wt mod4 = k-2*C(k,2)=k(2-k), because every row has weight25=1 mod4 and every pair intersection is odd.',
      'q5':q5,
      'below25_candidates':{'hull':[4,8,12,16,20,24],'odd_coset':[1,5,9,13,17,21]},
      'target':'Exclude these weights to prove [325,65,25]_2; Pass5207 then closes the complete q5 weight625 equality shell.',
      'boundary':'The minimum-distance-25 claim is not yet proved. This pass gives exact code/hull/congruence structure only.'}
    OUT.write_text(json.dumps(out,indent=2)+'\n');print(json.dumps(out,indent=2))
if __name__=='__main__':main()
