#!/usr/bin/env python3
"""Pass5167: close q=5 chamber leader 25 with five-edge paths.

Pass5166 gives C_24=40.  Edge deletion from an m=25 cut-minimal selected Levi
graph gives W<=floor(40*25/23)=43.  Pair+cubic+four-edge-path bounds close
W<=42.  At W=43 the deletion constraint forces endpoint-degree sum >=5 on
every selected edge.  Consequently every selected edge has degree 2 or 3 at
both ends and centers at least four selected five-edge paths.  Hence P5>=100.

A selected five-edge Levi path e0-e1-e2-e3-e4 injects three distinct positive
triple-star signatures:
  {e0,e1,e4}, {e0,e3,e4}: (1,3,4), each intersection 1;
  {e0,e2,e4}:             (2,2,4), intersection 1.
Levi girth eight makes the shorter geodesic subpaths unique, so these triples
are not multiply generated by different five-edge paths.  The extra 3P5 units
close the final W=43 branch.
"""
from __future__ import annotations
import json
from fractions import Fraction
from pathlib import Path
from analysis.w33_pass5134_q5_leader18_second_order_wall import optimize
from analysis.w33_pass5161_q5_cubic_leader23_localtype_dp import (
    p4_relaxed,profiles,centered_wedge_floor,ceil_frac)
from analysis.w33_pass5166_q5_cubic_leader25_edgetype_dp import edge_type_n112_floor

ROOT=Path(__file__).resolve().parents[1]
OUT=ROOT/'data/PART_W33_PASS5167_Q5_CUBIC_LEADER26_FIVEPATH.json'


def main():
    m=25;prev_cap=40
    cap=(prev_cap*m)//(m-2);assert cap==43
    pair={}
    for W in range(33,cap+1):
        ov,dist,feas,lb=optimize(m,W)
        pair[str(W)]={'distance_counts':list(dist),'pair_weight_lower_bound':lb}
    assert [pair[str(W)]['pair_weight_lower_bound'] for W in range(33,44)]==[
        1121,817,481,177,-127,-431,-735,-1039,-1375,-1679,-1983]

    branches={'N1<=34':{'integer_weight_lower_bound':817}}
    # Generic cubic/four-edge-path branches through W=40.
    for W in range(35,41):
        vals=[p4_relaxed(*p,max(2,W-prev_cap+2)) for p in profiles(m,W)]
        p4=min(v for v in vals if v is not None)
        n112=centered_wedge_floor(m,W)-3*(W//3)
        mass=25*n112+10*p4
        b=Fraction(pair[str(W)]['pair_weight_lower_bound'])+Fraction(6,7)*mass
        branches[f'N1={W}']={'N112_lower':n112,'P4_lower':p4,
          'triple_mass_lower':mass,'integer_weight_lower_bound':ceil_frac(b)}
    assert [branches[f'N1={W}']['integer_weight_lower_bound'] for W in range(35,41)]==[
        1476,1227,1078,967,813,740]

    # W=41,42: edge-type N112 floors improve the generic convex bound.
    for W,exp_n112,exp_p4,exp_lb in ((41,64,92,785),(42,68,104,670)):
        minsum=W-prev_cap+2;rows=[]
        for p in profiles(m,W):
            n112,types=edge_type_n112_floor(*p,minsum)
            p4=p4_relaxed(*p,minsum)
            if n112 is not None and p4 is not None:
                rows.append((p,n112,p4,types))
        n112=min(r[1] for r in rows);p4=min(r[2] for r in rows)
        assert (n112,p4)==(exp_n112,exp_p4)
        mass=25*n112+10*p4
        b=Fraction(pair[str(W)]['pair_weight_lower_bound'])+Fraction(6,7)*mass
        assert ceil_frac(b)==exp_lb
        branches[f'N1={W}']={'N112_lower':n112,'P4_lower':p4,
          'triple_mass_lower':mass,'integer_weight_lower_bound':ceil_frac(b)}

    # W=43: endpoint sum >=5.  Only degree profile (0,7,12) survives the
    # local stub constraints; N112>=72 and P4>=118.
    W=43;minsum=5;rows=[]
    for p in profiles(m,W):
        n112,types=edge_type_n112_floor(*p,minsum)
        p4=p4_relaxed(*p,minsum)
        if n112 is not None and p4 is not None:rows.append((p,n112,p4,types))
    assert len(rows)==1 and rows[0][0]==(0,7,12)
    n112=rows[0][1];p4=rows[0][2]
    assert (n112,p4)==(72,118)
    # Every central edge contributes at least 2*2=4 five-edge paths.
    p5=4*m;assert p5==100
    extra_unit_triples=3*p5
    mass=25*n112+10*p4+extra_unit_triples
    b=Fraction(pair[str(W)]['pair_weight_lower_bound'])+Fraction(6,7)*mass
    assert ceil_frac(b)==829
    branches['N1=43']={'degree_profile':[0,7,12],'endpoint_degree_sum_min':5,
      'N112_lower':n112,'P4_lower':p4,'N123_lower':2*p4,
      'P5_lower':p5,'N134_plus_N224_lower':extra_unit_triples,
      'triple_mass_lower':mass,'integer_weight_lower_bound':ceil_frac(b)}

    out={'pass':5167,'status':'THEOREM_Q5_STRICT_COUNTEREXAMPLE_LEADER_AT_LEAST_26',
      'q':5,'leader_size_closed':25,'target_distance':625,'adjacent_pair_cap':cap,
      'pair_relaxations':pair,'branches':branches,
      'five_path_injection':'Each selected five-edge Levi path yields two (1,3,4) triples and one (2,2,4) triple. Each signature has chamber-star triple intersection 1 by Pass5140. Girth eight gives uniqueness of the proper geodesic subpaths.',
      'conclusion':'All leader-25 sectors have apartment weight at least 670 before the final five-path branch, and N1=43 has lower bound 829 after the forced five-edge-path correction. Hence every q5 apartment-code word of weight <625 has minimum chamber leader at least 26.',
      'boundary':'This closes leader 25 only. The q5/all-q minimum-distance theorem remains open for leaders >=26 and the weight-625 equality shell remains unclassified.'}
    OUT.write_text(json.dumps(out,indent=2)+'\n');print(json.dumps(out,indent=2))

if __name__=='__main__':main()
