#!/usr/bin/env python3
"""Pass4962 — Q(4,3) matching curvature and its abelian/nonabelian cohomology.

The R2 perfect matchings of the 120-Steiner association scheme define the S3
connection from Pass4945 on the 540 edges of the disjointness graph of the 40
Q(4,3)=W33-line fibers.  We attach all 3240 graph triangles as 2-cells.

Results:
* over F2 the triangle-edge boundary rank is 501, exactly the cycle rank;
  hence H^1 of the triangle-filled 2-skeleton is zero;
* the sign of the S3 transport is an edge 1-cochain whose curvature is zero on
  1080 triangles and one on 2160 triangles;
* after transporting every triangle holonomy to a common root, the reflected
  triangles realize all three transpositions and generate S3 itself.
Thus full nonabelian holonomy is already generated by local triangle curvature.
"""
from __future__ import annotations
import itertools,json
from collections import Counter,deque
from pathlib import Path
import networkx as nx

ROOT=Path(__file__).resolve().parents[1]
OUT=ROOT/'data/PART_W33_PASS4962_Q43_S3_CURVATURE_COHOMOLOGY.json'

def Q6(v):
    a,c,d,e,f,g=v;return (a*c+d*e+f+f*g+g)&1
def add2(a,b):return tuple(x^y for x,y in zip(a,b))
def polar(a,b):return Q6(add2(a,b))^Q6(a)^Q6(b)
def comp(p,q):return tuple(p[q[i]] for i in range(len(q)))
def closure(gens,n):
    I=tuple(range(n));S={I};D=deque([I])
    while D:
        a=D.popleft()
        for g in gens:
            z=comp(g,a)
            if z not in S:S.add(z);D.append(z)
    return S
def compose_map(p,q):return tuple(q[p[i]] for i in range(len(p)))
def invperm(p):return tuple(p.index(i) for i in range(len(p)))
def parity(p):
    return sum(p[i]>p[j] for i in range(3) for j in range(i+1,3))&1
def gf2_rank(rows):
    piv={};r=0
    for x in rows:
        while x:
            p=x.bit_length()-1
            if p in piv:x^=piv[p]
            else:piv[p]=x;r+=1;break
    return r

def main()->int:
    # Cubic-surface/double-six carrier and PSp action, as in Pass4945/4955.
    vecs=[v for v in itertools.product((0,1),repeat=6) if any(v)]
    sing=[v for v in vecs if Q6(v)==0];nons=[v for v in vecs if Q6(v)==1];si={v:i for i,v in enumerate(sing)}
    trans=[tuple(si[add2(x,v) if polar(x,v) else x] for x in sing) for v in nons]
    gp=[];S={tuple(range(27))}
    for g in [comp(trans[0],t) for t in trans[1:]]:
        T=closure(gp+[g],27)
        if len(T)>len(S):gp.append(g);S=T
        if len(S)==25920:break
    assert len(S)==25920
    qp=[sum(bit<<i for i,bit in enumerate(v)) for v in sing]
    pts=sorted({tuple(sorted((a,b,a^b))) for a,b in itertools.combinations(qp,2) if a^b in qp})
    lines=[tuple(i for i,P in enumerate(pts) if x in P) for x in qp]
    G=nx.Graph();G.add_nodes_from(range(27))
    for i,j in itertools.combinations(range(27),2):
        if set(lines[i])&set(lines[j]):G.add_edge(i,j)
    C6=[frozenset(c) for c in nx.find_cliques(nx.complement(G)) if len(c)==6]
    DS=set()
    for A,B in itertools.combinations(C6,2):
        if A&B:continue
        H=G.subgraph(A|B)
        if H.number_of_edges()==30 and set(dict(H.degree()).values())=={5} and nx.is_bipartite(H):DS.add(frozenset(A|B))
    DS=sorted(DS,key=lambda x:tuple(sorted(x)));assert len(DS)==36;di={S:i for i,S in enumerate(DS)}
    H36=nx.Graph();H36.add_nodes_from(range(36))
    for i,j in itertools.combinations(range(36),2):
        if len(DS[i]&DS[j])==6:H36.add_edge(i,j)
    st=sorted(t for t in itertools.combinations(range(36),3)
      if all(H36.has_edge(*e) for e in itertools.combinations(t,2)) and len(DS[t[0]]&DS[t[1]]&DS[t[2]])==0)
    assert len(st)==120;sti={t:i for i,t in enumerate(st)}
    SP=[]
    for g in gp:
        dp=tuple(di[frozenset(g[x] for x in S)] for S in DS)
        SP.append(tuple(sti[tuple(sorted(dp[i] for i in t))] for t in st))

    seen=set();orbits=[]
    for p in itertools.combinations(range(120),2):
        if p in seen:continue
        O={p};seen.add(p);D=deque([p])
        while D:
            a=D.popleft()
            for op in SP:
                b=tuple(sorted((op[a[0]],op[a[1]])))
                if b not in O:O.add(b);seen.add(b);D.append(b)
        orbits.append(sorted(O))
    R1,R2,R3,R4=sorted(orbits,key=len);assert list(map(len,(R1,R2,R3,R4)))==[120,1620,2160,3240]
    FG=nx.Graph();FG.add_nodes_from(range(120));FG.add_edges_from(R1)
    fibers=sorted([sorted(c) for c in nx.connected_components(FG)]);assert len(fibers)==40
    fi={x:i for i,F in enumerate(fibers) for x in F};pos={x:i for F in fibers for i,x in enumerate(F)}
    Q=nx.Graph();Q.add_nodes_from(range(40))
    for a,b in R3:Q.add_edge(fi[a],fi[b])
    Qbar=nx.complement(Q);Qbar.remove_edges_from(nx.selfloop_edges(Qbar));assert Qbar.number_of_edges()==540

    r2=set(R2)
    def edgeperm(u,v):
        p=[None]*3
        for x in fibers[u]:
            ys=[y for y in fibers[v] if tuple(sorted((x,y))) in r2];assert len(ys)==1
            p[pos[x]]=pos[ys[0]]
        return tuple(p)
    transports={}
    for u,v in Qbar.edges():
        p=edgeperm(u,v);transports[(u,v)]=p;transports[(v,u)]=invperm(p)

    edges=sorted(tuple(sorted(e)) for e in Qbar.edges());ei={e:i for i,e in enumerate(edges)}
    triangles=[];boundary_rows=[];curv=Counter()
    for a,b,c in itertools.combinations(range(40),3):
        if not (Qbar.has_edge(a,b) and Qbar.has_edge(a,c) and Qbar.has_edge(b,c)):continue
        triangles.append((a,b,c));bits=0
        for e in ((a,b),(a,c),(b,c)):bits^=1<<ei[tuple(sorted(e))]
        boundary_rows.append(bits)
        curv[parity(transports[(a,b)])^parity(transports[(b,c)])^parity(transports[(c,a)])]+=1
    assert len(triangles)==3240 and curv==Counter({1:2160,0:1080})
    rank_d0=39;rank_d1=gf2_rank(boundary_rows);cycle_rank=540-40+1
    assert rank_d1==cycle_rank==501
    h1=540-rank_d0-rank_d1;assert h1==0

    # Root all nonabelian triangle curvature elements to one fiber.
    parent={0:None}
    for u,v in nx.bfs_edges(Qbar,0):parent[v]=u
    root_to={0:(0,1,2)}
    for v in nx.bfs_tree(Qbar,0):
        if v==0:continue
        u=parent[v];root_to[v]=compose_map(root_to[u],transports[(u,v)])
    rooted=[]
    for a,b,c in triangles:
        p=transports[(a,b)];p=compose_map(p,transports[(b,c)]);p=compose_map(p,transports[(c,a)])
        q=compose_map(root_to[a],p);q=compose_map(q,invperm(root_to[a]));rooted.append(q)
    rset=set(rooted);identity=(0,1,2)
    transpositions={p for p in itertools.permutations(range(3)) if parity(p)==1}
    assert rset==transpositions|{identity}
    hol=closure(list(transpositions),3);assert len(hol)==6

    out={
      'pass':4962,
      'base':'Q(4,3) disjointness graph on the forty Steiner/W33-line fibers',
      'cell_counts':{'vertices':40,'edges':540,'triangles_as_2_cells':3240},
      'F2_cohomology':{
        'rank_d0':rank_d0,'graph_cycle_rank':cycle_rank,'triangle_boundary_rank':rank_d1,
        'H1_dimension':h1,
        'interpretation':'triangle boundaries span the entire graph cycle space; every flat C2 connection is gauge-trivial'},
      'sign_curvature':{'flat_triangles':curv[0],'odd_reflection_triangles':curv[1]},
      'rooted_nonabelian_curvature':{
        'conjugacy_types':['identity','transposition'],
        'all_three_transpositions_present':True,
        'subgroup_generated_by_triangle_curvatures':'S3','generated_order':len(hol)},
      'theorem':'After filling all 3240 triangles of the Q(4,3) disjointness graph, H^1 over F2 vanishes because the triangle boundary rank equals the full 501-dimensional cycle space. The sign abelianization of the Steiner matching connection has curvature on exactly 2160 triangles. Rooting the nonabelian triangle holonomies to one fiber yields the identity plus all three transpositions, and those local curvature elements generate the full S3 holonomy group.',
      'consequence':'The Pass4945 full S3 holonomy is generated already by local triangle curvature; no additional flat topological C2 sector survives the triangle relations.',
      'boundary':'The particular labels of the three transpositions depend on fiber gauges and rooting. Their conjugacy class, the generated subgroup S3, and the F2 rank statements are gauge invariant.'}
    OUT.write_text(json.dumps(out,indent=2,sort_keys=True)+'\n');print(json.dumps(out,indent=2,sort_keys=True));return 0
if __name__=='__main__':raise SystemExit(main())
