#!/usr/bin/env python3
from __future__ import annotations
import argparse,hashlib,json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
OUT=ROOT/'data'/'w33_pass573_577_c3_600cell_scheme_dvr_idempotent_dp_release.json'
FILES={
 573:ROOT/'data'/'w33_pass573_hjelmslev_c3_600cell_apex.json',
 574:ROOT/'data'/'w33_pass574_singer_coherent_configuration.json',
 575:ROOT/'data'/'w33_pass575_cyclotomic_dvr_kernel_formal.json',
 576:ROOT/'data'/'w33_pass576_exact_walsh_central_idempotents.json',
 577:ROOT/'data'/'w33_pass577_bayesian_posterior_dynamic_program.json',
}
def payload():
 raw={n:f.read_bytes() for n,f in FILES.items()};p={n:json.loads(raw[n]) for n in FILES}
 checks={
  'all_owner_certificates_pass':all(x['status']=='PASS' for x in p.values()),
  'dominant_C3_triples177377':p[573]['hjelmslev_symmetry']['dominant_size3_single_C3_orbits']==177377,
  'C3_projective_orbits266450':p[573]['hjelmslev_symmetry']['projective_orbits']==266450,
  'residual_collisions44999':p[573]['hjelmslev_symmetry']['residual_collisions_after_C3_quotient']==44999,
  '600cell_exact_12_plus_1':p[573]['checks']['apex_has_12_neighbors'] and p[573]['checks']['neighbors_share_hyperplane'],
  '600cell_module_mismatch_preserved':p[573]['checks']['module_mismatch_falsifier'],
  'Singer_scheme_rank9':p[574]['scheme']['rank']==9,
  'Singer_scheme_multiplicities':p[574]['spectral']['multiplicities']==[1,7,20,28,45,45,56,64,70],
  'Singer_full_aut_A8':p[574]['automorphisms']['full_automorphism_upper_bound']==20160,
  'residue_kernel_principal_source':p[575]['checks']['kernel_equality_statement_exact'],
  'Walsh_group_D10_C4':p[576]['group']['identification']=='D10 x C4',
  'six_exact_idempotent_signatures':len(p[576]['formula_signatures'])==6,
  'central_projector_ranks':p[576]['signed_Walsh_representation']['projector_ranks']==[104]*8+[408]*8,
  'DP_conservative_gain':p[577]['results']['conservative']['absolute_gain']>0,
  'DP_nominal_gain':p[577]['results']['nominal']['absolute_gain']>0,
  'DP_aspirational_boundary':abs(p[577]['results']['aspirational']['absolute_gain'])<1e-8 and p[577]['results']['aspirational']['states_strictly_improved']>0,
  'owner_check_total58':sum(sum(x['checks'].values()) for x in p.values())==58,
 }
 return {
  'schema':'w33.pass573_577.c3_600cell_scheme_dvr_idempotent_dp.release.v1','status':'PASS' if all(checks.values()) else 'FAIL',
  'owner_check_total':sum(sum(x['checks'].values()) for x in p.values()),
  'owner_custody':{str(n):{'path':str(FILES[n].relative_to(ROOT)),'sha256':hashlib.sha256(raw[n]).hexdigest(),'check_count':len(p[n]['checks'])} for n in FILES},
  'headline':{
   '573':'A projective C3 shear explains 177,377 of 177,400 dominant Hjelmslev triples; the 600-cell has an exact 12-neighbor hyperplane plus apex split, but the C3 modules differ.',
   '574':'The 336 Singer normalizers form a commutative rank-9 association scheme with full color automorphism group GL(4,2) ~= A8.',
   '575':'The residue kernel in the native fifth-cyclotomic order is proved in Lean source to equal the principal ideal generated by lambdaBar.',
   '576':'The Walsh group is D10 x C4 and all 16 primitive central idempotents are verified exactly over Q(i,sqrt(5)).',
   '577':'Finite-grid posterior dynamic programming rigorously improves the staged policy for conservative and nominal calibration, while recording the aspirational-prior tie.'
  },
  'release_checks':checks,
  'boundary':'Exact for the structured F3^13 family, standard-coordinate 600-cell vertex figure, 336-point Singer scheme, native order-level residue theorem source, signed fixed-magnitude Walsh representation, and finite-grid observation model. No natural C3-equivariant identification with the icosahedron vertices, complete 9^40 image, completed 5-adic field, or continuous-belief Bayes-optimal theorem is claimed.'
 }
def main():
 ap=argparse.ArgumentParser();ap.add_argument('--check',action='store_true');ap.add_argument('--output',type=Path,default=OUT);a=ap.parse_args();p=payload();text=json.dumps(p,sort_keys=True,separators=(',',':'))+'\n'
 if a.check:
  if not a.output.exists() or a.output.read_text()!=text:raise SystemExit('Passes 573-577 release certificate drift')
 else:a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(text)
 print(json.dumps({'status':p['status'],'owner_checks':p['owner_check_total'],'release_checks':sum(p['release_checks'].values()),'total_release_checks':len(p['release_checks'])}));return 0 if p['status']=='PASS' else 1
if __name__=='__main__':raise SystemExit(main())
