#!/usr/bin/env python3
"""Exact A8^3 Niemeier glue code and its coupling to the three Pauli-graded sl9 factors."""
import itertools,json,math
from collections import Counter
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
OUT=ROOT/'data'/'w33_a8_cubed_niemeier_glue.json'
G=[(1,1,4),(1,4,1),(4,1,1)]
def add(a,b):return tuple((x+y)%9 for x,y in zip(a,b))
def mul(n,a):return tuple((n*x)%9 for x in a)
def order(a):
    x=(0,0,0)
    for n in range(1,10):
        x=add(x,a)
        if x==(0,0,0):return n
def qnum(k):return k*(9-k)
def h_num(word):return sum(qnum(k) for k in word)
def bnum(a,b):return sum(a[i]*b[i] for i in range(3))%9
def dimk(k):return math.comb(9,k)
def main(write=True):
    C=sorted({tuple((i*G[0][j]+k*G[1][j]+l*G[2][j])%9 for j in range(3)) for i,k,l in itertools.product(range(9),repeat=3)})
    assert len(C)==27
    ordc=Counter(order(x) for x in C)
    basis=None
    for a in C:
        if order(a)!=9:continue
        A={mul(i,a) for i in range(9)}
        for b in C:
            if order(b)==3 and b not in A:
                H={add(mul(i,a),mul(j,b)) for i in range(9) for j in range(3)}
                if H==set(C):basis=(a,b);break
        if basis:break
    hc=Counter(h_num(w) for w in C)
    iso=all(h_num(w)%18==0 for w in C)
    bilo=all(bnum(a,b)==0 for a in C for b in C)
    perms=list(itertools.permutations(range(3)));s3=all(tuple(w[i] for i in pi) in C for w in C for pi in perms)
    proj=[{w[i] for w in C} for i in range(3)]
    rows=[{'word':list(w),'order':order(w),'ground_weight':h_num(w)/18,
           'ground_rep':[f'Lambda^{k}(9)' if k not in(0,8) else ('1' if k==0 else '9bar') for k in w],
           'ground_dimension':math.prod(dimk(k) for k in w)} for w in C]
    out={'schema':'w33.a8_cubed_niemeier_glue_intertwiner.v1','status':'PASS',
      'headline':'The A8^3 Niemeier extension couples the three SU(9)_1 factors by a 27-sector simple-current glue code C <= (Z9)^3, C ~= Z9 x Z3, generated by permutations of (1,1,4). The first cross-factor fields occur at weight 2; weight-one remains sl9^3. The glue constrains SU(9) center charges, while the F3^4 Pauli degrees in each adjoint factor remain independent.',
      'glue':{'ambient':'(A8*/A8)^3 ~= (Z9)^3','input_generators':[list(x) for x in G],'order':len(C),'abstract_structure':'Z9 x Z3','basis_order9_order3':[list(x) for x in basis],'element_order_census':{str(k):v for k,v in sorted(ordc.items())},'totally_isotropic_quadratic':iso,'totally_isotropic_bilinear':bilo,'S3_factor_permutation_invariant':s3,'coordinate_projections_are_surjective':[len(x)==9 for x in proj]},
      'conformal_weight_census':{str(n/18):c for n,c in sorted(hc.items())},
      'minimal_cross_factor_weight':min(h_num(w)/18 for w in C if sum(k!=0 for k in w)>=2),
      'generator_vertex_operators':[{'glue_word':list(w),'order':order(w),'ground_weight':h_num(w)/18,'finite_SU9_rep_dimensions':[dimk(k) for k in w],'ground_tensor_dimension':math.prod(dimk(k) for k in w),'operator_form':f'V_[{w[0]},{w[1]},{w[2]}] ~ exp(i(<lambda_{w[0]},phi1>+<lambda_{w[1]},phi2>+<lambda_{w[2]},phi3>))'} for w in G],
      'fusion_rule':'V_c x V_d -> V_{c+d mod 9}; the 27 glue sectors form the simple-current group C.',
      'pauli_intertwining':{'each_factor_adjoint_grading':'F3^4 two-qutrit Pauli grading','center_charge_action':'the SU(9) center zeta_9 I acts on Lambda^k(9) by zeta_9^k','glue_selection':'only triples of center charges (k1,k2,k3) in C occur in the extended lattice VOA','Pauli_action_on_sector':'P(v1) tensor P(v2) tensor P(v3), with P(vi) induced on Lambda^ki(9)','no_diagonal_Pauli_constraint':True,'reason':'adjoint Pauli currents have center charge 0, so glue extension does not identify or equate the three F3^4 labels; it couples the factors through their Z9 center/simple-current charges instead.'},
      'sector_table':rows,
      'checks':{'27_glue_words':len(C)==27,'structure_Z9xZ3':ordc==Counter({9:18,3:8,1:1}),'quadratic_isotropic':iso,'bilinear_isotropic':bilo,'S3_invariant':s3,'first_nontrivial_cross_factor_weight_is_2':min(h_num(w)/18 for w in C if w!=(0,0,0))==2,'weight_one_no_glue_currents':all(h_num(w)/18!=1 for w in C if w!=(0,0,0))}}
    assert all(out['checks'].values())
    if write:OUT.write_text(json.dumps(out,indent=2)+'\n')
    print(json.dumps({k:out[k] for k in ['headline','glue','conformal_weight_census','minimal_cross_factor_weight','generator_vertex_operators','pauli_intertwining','checks']},indent=2));return out
if __name__=='__main__':main(True)
