"""Eight interface investigations; supplied geometry is not a completed TOE.

11734-41 owns the rank14 tensor and E6 root dictionary; 11681 the actual
E8 bracket; 11271/11636 the E6 cubic. The Koszul/type112 method is from
Blesneag et al. (1512.05322); E8 Dorfman conventions from Inverso--Rovere
(2410.14520). We construct particular witnesses, not new general theories.
"""
from __future__ import annotations
from collections import Counter
from functools import lru_cache
import hashlib
import itertools as it
import json
from pathlib import Path
import sys
import numpy as np
import sympy as s
from scipy.linalg import expm
from scipy.sparse import coo_matrix

ROOT=Path(__file__).resolve().parents[1]
sys.path.insert(0,str(ROOT/'analysis'))
import w33_pass11734_11741_gauging_and_chiral_quotient as M
P=M.P; E=M.E; B=M.B
OUT=ROOT/'data/w33_pass11742_11749_nonzero_flavor_and_flux_frame.json'
K=((-2,1,1,0),(0,-3,0,1),(2,2,-1,-1))
G=s.diag(1,-1); H=s.Matrix([[0,1],[1,0]])
CHARS=tuple(it.product((1,-1),repeat=2))


def clean(d):return {a:s.cancel(v) for a,v in d.items() if v}
def add(*vs):
    out=Counter()
    for v in vs:
        for a,c in v.items():out[a]+=c
    return clean(out)
def scale(c,v):return clean({a:c*x for a,x in v.items()})


@lru_cache(None)
def bracket(a,b):
    if a[0]=='H' and b[0]=='H':return {}
    if b[0]=='H':return scale(-1,bracket(b,a))
    if a[0]=='H':
        labs,ws,_=P.roots();w=ws[labs.index(b)]
        return clean({b:s.Rational(w[a[1]]-w[8],3)})
    return M.bracket_exact(a,b)


def bv(a,b):
    return add(*(scale(x*y,bracket(r,t)) for r,x in a.items() for t,y in b.items()))


def pairing(a,b):
    if a[0]=='H' or b[0]=='H':
        return int(a[0]==b[0]=='H')*(1+int(a==b))
    t,c=P.dual(a);return c if t==b else 0


def cohomology_actions():
    return [(-s.kronecker_product(G,G),-s.kronecker_product(H,H)),
            (-s.kronecker_product(G,G),-s.kronecker_product(H,H)),
            (s.kronecker_product(G,G),s.kronecker_product(H,H))]


def character_vector(actions,char):
    a,b=actions;basis=(a-char[0]*s.eye(4)).col_join(b-char[1]*s.eye(4)).nullspace()
    assert len(basis)==1
    v=basis[0];den=s.ilcm(*[x.q for x in v]);v=v*den
    first=next(x for x in v if x);return v if first>0 else -v


def cup(a,b,c):
    # Three independent Serre pairings: y, z and w; x contributes H1(-2).
    return sum(a[2*i+j]*b[2*i+k]*c[2*j+k] for i,j,k in it.product(range(2),repeat=3))


@lru_cache(None)
def flavor_certificate():
    assert tuple(map(sum,zip(*K)))==(0,0,0,0)
    h=[M.tetraquadric_cohomology(n) for n in K]
    hd=[M.tetraquadric_cohomology(tuple(-v for v in n)) for n in K]
    assert h==[[0,4,0,0]]*3 and hd==[[0,0,4,0]]*3
    d=(5+s.sqrt(241))/36;t=(1,s.Rational(2,3)+3*d,s.Rational(1,2),d)
    kap=[sum(t[j]*t[k] for j,k in it.combinations([j for j in range(4) if j!=i],2)) for i in range(4)]
    slopes=[s.simplify(sum(a*b for a,b in zip(n,kap))) for n in K]
    assert slopes==[0]*3 and all(v>0 for v in t)
    c2,c3=M.chern_coefficients(K);assert 2*sum(c3.values())==-24
    actions=cohomology_actions();vectors=[character_vector(a,(1,1)) for a in actions]
    traces=[]
    for a,b in actions:
        assert a*a==b*b==s.eye(4) and a*b==b*a
        traces.append([int(s.trace(x)) for x in (s.eye(4),a,b,a*b)])
    assert traces==[[4,0,0,0]]*3
    raw=cup(*vectors);assert raw==2
    # O(2) eigenbasis: u^2+v^2, u^2-v^2, 2uv, with three distinct characters.
    chars=((1,1),(1,-1),(-1,1))
    invariant=[v for v in it.product(range(3),repeat=4)
               if all(np.prod([chars[j][k] for j in v])==1 for k in range(2))]
    assert len(invariant)==21
    # At every CP1 point at least two of these three sections are nonzero.
    # Check all minimal availability patterns, not only coordinate corners.
    patterns=list(it.product(list(it.combinations(range(3),2)),repeat=4))
    assert all(any(all(v[i] in avail[i] for i in range(4)) for v in invariant) for avail in patterns)
    return dict(status='PASS',matter_bundle_K=[list(n) for n in K],structure_bundle='V=K; W=K dual+O+O for the nonprincipal Higgs. The base27 roots carry the physical-family fundamental, so H1(V)=H1(K) is used.',
        cover_h_K=h,cover_h_Kdual=hd,cohomology_types=[1,1,2],cover_chiral_modes=12,
        quotient_group='free diagonal Z2 x Z2, generated by diag(1,-1) and coordinate swap on all four CP1 factors',
        line_lift_commutator='(-1)^(sum of multidegrees)=+1 for every K_i',determinant_linearization='trivial natural product',
        invariant_tetraquadric_sections=21,basepoint_free_availability_patterns=len(patterns),ambient_nonidentity_fixed_points=48,
        smooth_free_family='The21-dimensional invariant system is basepoint-free (all81 minimal availability patterns pass). Bertini gives generic smoothness. Each of g,h,gh has16 isolated fixed points; the O(2,2,2,2) fiber action there is trivial, so avoiding their finite union is a nonempty open condition. Four coordinate determinant signs preserve the residue3-form.',
        cohomology_characters=traces,quotient_chiral_modes=3,quotient_opposite_modes=0,
        V_cover_c3=-24,V_quotient_c3=-6,cover_holomorphic_Euler_index=-12,quotient_holomorphic_Euler_index=-3,
        net_H1_minus_H2_cover=12,net_H1_minus_H2_quotient=3,
        orientation='The signs follow the actual fundamental-family root dictionary and chi(V)=integral c3(V)/2. Conjugating all matter reverses chirality and X charges; no dynamical orientation is selected.',
        positive_Kahler_point=[str(s.simplify(x)) for x in t],half_slopes=[str(x) for x in slopes],
        natural_invariant_vectors=[list(map(int,v)) for v in vectors],
        exact_cover_cup=int(raw),quotient_cup_in_declared_Serre_normalization=str(raw/4),
        unit_algebraic_basis_cover_cup='1/sqrt(2)',
        normalization='Serre evaluation pairs monomial basis with its dual. Overall residue/holomorphic3-form normalization is declared, not measured. Euclidean coefficient norm is not the Ricci-flat/HYM kinetic metric.',
        physical_formula='lambda_phys=exp(Kmod/2)*lambda_hol/sqrt(Z1 Z2 Z3); positive finite Z_i preserve nonvanishing, but their values are not computed.',
        prior='Blesneag et al.1512.05322 owns type112 and free Klein4 tetraquadric methods; its eq4.17 has (2,2,4) modes. This supplied degree choice has (4,4,4). Prior11741 all-type1 inventory remains cubic-zero.',
        scope='A supplied smooth free CY quotient family with three net chiral cohomology modes and a nonzero holomorphic cubic. Neither measured masses/mixing nor canonical physical normalization, full compactification/anomaly vacuum or geometric selection is derived.')


def theta(a):
    return add(*(add({r:c*pairing(t,a)} if pairing(t,a) else {},
                     {t:c*pairing(r,a)} if pairing(r,a) else {}) for r,t,c in M.theta_terms()))


@lru_cache(None)
def frame_data():
    section=[('A',3,i) for i in range(9) if i!=3]
    rs=[]
    for u in section:
        matches=[{b:s.Integer(c)} if a==u else {a:s.Integer(c)} for a,b,c in M.theta_terms() if u in (a,b)]
        rs.append(matches[0] if matches else {})
    labs,_,_=P.roots();basis=[*labs,*[('H',i) for i in range(8)]]
    return section,rs,basis


@lru_cache(None)
def flux_frame_certificate():
    section,rs,basis=frame_data();identities=[];nilpotency=0
    assert all(not bv(r,t) for r,t in it.combinations(rs,2))
    assert all(not bv(r,{u:1}) for r in rs for u in section)
    for a in basis:
        D=add(*(bv({u:1},bv(r,{a:1})) for u,r in zip(section,rs)))
        assert D==scale(6,theta(a)),(a,D,theta(a))
        # Ancillary sharp: -sum B(R_i,a) S_i, constrained to the same section.
        pR=add(*(scale(pairing(u,a),r) for u,r in zip(section,rs)))
        qS=add(*({u:sum(c*pairing(v,a) for v,c in r.items())} for u,r in zip(section,rs)))
        assert add(pR,qS)==theta(a)
        assert add(pR,D,qS)==scale(7,theta(a))
        # Full ancillary closure: q_i([Theta(a),b])=0 because [R_i,Theta(a)]=0.
        assert all(not bv(r,theta(a)) for r in rs)
        for r in rs:
            v={a:1};n=0
            while v:
                n+=1;v=bv(r,v)
                assert n<=4
            nilpotency=max(nilpotency,n)
        if theta(a):identities.append([list(a),[[list(x),str(c)] for x,c in theta(a).items()]])
    return dict(status='PASS',section=[list(u) for u in section],
        derivative_generators=[[[list(a),int(c)] for a,c in r.items()] for r in rs],
        local_frame='E_a(y)=exp(ad C(y)) a, C(y)=sum_i y_i R_i, rho=1',
        inverse_twist='U=exp(-ad C); all R_i commute with every R_j and S_j',
        anchor='p_a^i=B(S_i,a), constant under exp(ad C)',
        ancillary='Sigma_a sharp=-sum_i B(R_i,a) S_i; constant and section-constrained',
        double_bracket_identity='sum_i [S_i,[R_i,a]]=6 Tsharp(a)',all248_basis_checks=len(basis),
        generator_nilpotency_bound=nilpotency,nonzero_Tsharp_columns=identities,
        generalized_vector_product='L_(E_a,Sigma_a) E_b=7 exp(ad C)[Tsharp(a),b]',
        full_ancillary_product='0=Sigma_(7[Tsharp(a),b]); transport/divergence vanish; DeltaSigma vanishes since the rotation is constant and in the abelian image.',
        effective_embedding_tensor='7 T, up to overall sign convention X and arbitrary gauge coupling',
        singlet_and_trombone=0,integrable_coordinate_section=True,
        prior='General E8 generalized-frame/ancillary formulas: Inverso--Rovere2410.14520 eqs3.3,3.10-3.24. General14D abelian gauging type predates this witness (Hohm2006). Actual projected T is owned by11732/11734.',
        scope='An explicit local generalized parallelization on a supplied R8 physical section, including ancillary closure, for the certified split-E8 tensor. Global compact patching, flux quantization, higher-dimensional field equations and a vacuum are not established. It is a separate duality construction, not the compact E8 gauge bundle on the CY threefold.')


@lru_cache(None)
def matter_dictionary():
    cert=M.cubic_certificate();labs=list(map(tuple,cert['base27_root_dictionary']))
    roots,weights,_=P.roots();X=(1,1,1,0,0,0,-5,1,1)
    charges=[int(sum(x*w for x,w in zip(X,weights[roots.index(a)]))//3) for a in labs]
    D=np.zeros((27,27,27),dtype=int)
    for i,j,k,c in cert['signed_cubic_entries']:D[i,j,k]=c
    return labs,charges,D


def family_mass(v):
    a,b,c=v;return s.Matrix([[0,c,b],[c,0,a],[b,a,0]])/2


@lru_cache(None)
def anomaly_exotic_certificate():
    labs,charges,D=matter_dictionary()
    assert Counter(charges)=={2:10,-4:5,-1:10,5:2}
    five=[i for i,q in enumerate(charges) if q==-4];bars=[i for i,q in enumerate(charges) if q==-1]
    sing=labs.index(('A',3,6));block=s.Matrix(D[sing][np.ix_(five,bars)].tolist())
    assert block.rank()==5
    v=s.symbols('v1:4');Y=family_mass(v);det=s.factor(Y.det());assert det==s.prod(v)/4
    full=s.kronecker_product(Y,block);assert full.subs(dict(zip(v,(1,1,1)))).rank()==15
    # Standard SU5 Dynkin indices normalized to I(5)=1/2.
    anomalies={'SU5^3':1+1-2,'SU5^2_X':s.Rational(3,2)*2+s.Rational(1,2)*(-4)+2*s.Rational(1,2)*(-1),
               'grav_X':10*2+5*(-4)+10*(-1)+2*5,'X^3':10*2**3+5*(-4)**3+10*(-1)**3+2*5**3}
    assert all(x==0 for x in anomalies.values())
    charge=s.Matrix(K).T;sublattice=charge*s.Matrix([[1,0],[0,1],[-1,-1]])
    assert sublattice.rank()==2
    return dict(status='PASS',X_Cartan=[1,1,1,0,0,0,-5,1,1],
        actual27_charge_multiplicities={str(k):v for k,v in sorted(Counter(charges).items())},
        SU5_branch='10_2 + 5_-4 + 2 bar5_-1 + 2 singlet_5',
        anomalies_per27={k:str(v) for k,v in anomalies.items()},
        family_axion_charge_matrix=sublattice.tolist(),family_Stueckelberg_rank=2,
        X_Stueckelberg_charge=0,singlet_root=list(labs[sing]),
        actual_E6_singlet_five_bar5_block=block.tolist(),one_family_gauge_block_rank=5,
        three_family_mass_matrix=[[str(x) for x in row] for row in Y.tolist()],family_mass_determinant=str(det),
        full_five_bar5_mass_shape=[15,30],full_mass_rank_at_equal_nonzero_VEVs=15,
        conditional_survivors='Three10 plus three bar5 chiral SU5 families, after pairing all three5 with three of the six bar5; singlets and other sectors still require analysis.',
        original_inventory_D_term='D_X=5 sum_i,alpha |S_i,alpha|^2 with zero X FI and no opposite-charge SM-singlet zero modes; positive kinetic metric forces S=0.',
        obstruction='The nonzero cubic gives a full-rank exotic mass channel, but that channel cannot acquire a supersymmetric SM-preserving singlet VEV in this minimal zero-mode inventory. Anomaly-free X is not removed by the rank2 family axion map.',
        scope='Actual-root branching, perturbative SU5/X anomaly checks and conditional exotic pairing, with an exact minimal-inventory D-flat obstruction. Neither a full anomaly-complete compactification, a supersymmetric SM vacuum nor a proton-safe spectrum is certified.')


@lru_cache(None)
def coupled_action_certificate():
    # An explicit added vectorlike pair is a conditional EFT repair, not a CY zero mode.
    r,mu=s.symbols('r mu',positive=True)
    p2=(s.sqrt(r*r+4*mu**4)-r)/2;q2=(s.sqrt(r*r+4*mu**4)+r)/2
    assert s.simplify(p2*q2-mu**4)==0 and s.simplify(q2-p2-r)==0
    Js=P.su2_generators((1,1,1,2));Phi=[1j*j for j in Js]
    residual=max(np.max(abs(Phi[(i+1)%3]@Phi[(i+2)%3]-Phi[(i+2)%3]@Phi[(i+1)%3]+Phi[i])) for i in range(3))
    assert residual<1e-13 and np.max(abs(sum(a@a.conj().T-a.conj().T@a for a in Phi)))<1e-13
    rows=[]
    for parts in P.partitions(5):
        j=P.su2_generators(parts);phi=[1j*a for a in j]
        err=max(np.max(abs(phi[(i+1)%3]@phi[(i+2)%3]-phi[(i+2)%3]@phi[(i+1)%3]+phi[i])) for i in range(3))
        assert err<1e-12;rows.append(list(parts))
    # At S_i=1, P,Q solve all specified F/D equations; Z and charged exotics=0.
    vals={r:3,mu:1};assert s.simplify((q2-p2-r).subs(vals))==0
    assert family_mass((1,1,1)).rank()==3
    assert abs((s.Rational(2,3)*sum(np.trace(a@a) for a in Phi))+1)<1e-13
    # Normal Phi alone has zero adjoint D, but the A36 singlets are SU2
    # highest-weight doublets: their density contributes r Jz. Move along
    # the complex F-flat orbit to cancel that missing gauge equation.
    t=(s.sqrt(13)-3)/2;a=s.sqrt(t)
    jp=s.Matrix([[0,1],[0,0]]);jm=jp.T;jz=s.diag(s.Rational(1,2),-s.Rational(1,2))
    exactPhi=[s.I*(a*jp+jm/a)/2,(a*jp-jm/a)/2,s.I*jz]
    exactD=sum((v*v.conjugate().T-v.conjugate().T*v for v in exactPhi),s.zeros(2))
    assert (exactD+3*jz).applyfunc(s.simplify)==s.zeros(2)
    assert all((exactPhi[(i+1)%3]*exactPhi[(i+2)%3]-exactPhi[(i+2)%3]*exactPhi[(i+1)%3]+exactPhi[i]).applyfunc(s.simplify)==s.zeros(2) for i in range(3))
    assert s.simplify(s.Rational(2,3)*sum(s.trace(v*v) for v in exactPhi))==-1
    assert s.simplify(t-1/t+3)==0
    return dict(status='PASS',supplied_superpotential='Tr(Phi1[Phi2,Phi3])+(m/2)sum_a Tr(Phi_a^2) + W_E6 + Z(P Q+(2/3)sum_a Tr(Phi_a^2))',
        W_E6='The11742 cup multiplies the11271/11636 signed E6 cubic; its actual exotic restriction is11744.',
        imported_fields='P,Q are additional SU5-singlet chiral fields of X charges+5,-5, zero family charges; Z is neutral. They are not derived from the11742 cohomology.',
        imported_pair_anomalies={'grav_X':0,'X^3':0},
        branch_Phi='i m g J_a g^-1 on O^2, zero on K dual; g=diag(sqrt(a),1/sqrt(a)), a^2=(sqrt(r^2+4m^4)-r)/(2m^2). m=1,r=3 in the witness.',matrix_F_term_max_residual=float(residual),
        coupled_scale='On this branch (2/3)sum Tr(Phi_a^2)=-m^2, so F_Z sets P Q=m^2. The balancing-pair scale is tied to the Higgs mass input, rather than an independent mu input.',
        SU2_singlet_D_control='At normal Phi=i m J and nonzero A36 singlets the SU2 D term is r Jz, not zero. The complex F-flat rescaling contributes m^2(a^2-a^-2) Jz=-r Jz.',
        exact_rescaled_doublet_Higgs=[[[[str(s.re(v)),str(s.im(v))] for v in row] for row in phi.tolist()] for phi in exactPhi],
        all_stated_gauge_D_terms='SU2: adjoint plus singlet density cancels exactly; X: 5(r+|P|^2-|Q|^2)=0; family T2: equal singlet norms; SU5: singlets and commuting Cartan/Higgs backgrounds.',
        singlet_flat_solution='S_i=1 in the A36 singlet component; Z=0, charged exotics=0; |P|^2=(sqrt(9+4mu^4)-3)/2, |Q|^2=(sqrt(9+4mu^4)+3)/2, P Q=mu^2.',
        general_flat_solution={'P_squared':str(p2),'Q_squared':str(q2),'r':'sum_i |S_i|^2','mu':'mu=m on the coupled branch','shared_rescaling':'P=m a, Q=m/a, so the same a solves both SU2 and X D terms'},
        family_D_terms='Equal canonically weighted |S_i|^2 sum their three family weights to zero at the supplied slope-zero point.',
        original_inventory_control='Removing Q makes D_X strictly positive for any nonzero S or P; the repair is an additional assumption.',
        all_zero_F_Higgs_partitions=rows,nonprincipal_branch_selected=False,
        global_partition_boundary='Seven is a local matrix census, not seven global bundle vacua. The11728 c3 obstruction still excludes the global principal5; zero and the trivial-doublet branch both extend globally, so uniqueness still fails.',
        unresolved_flat_directions='All seven SU2 partitions solve the supplied N=1* F terms, including zero and principal5. Kähler overall volume and complex structure are not stabilized. No clock is coupled or selected by this action.',
        global_Higgs_compatibility='The (2,1,1,1) branch acts on the two trivial lines, but its scalar fields and superpotential are supplied EFT fields, not bundle-derived massless moduli.',
        scope='An explicit classical rigid-N=1 broken-phase EFT F/D-flat conditional repair, with extra vectorlike matter and a supplied coupled action. It shows which missing input repairs the minimal D obstruction; it is not a full E8-covariant field inventory and does not derive that input, select geometry/Higgs/clock together, solve supergravity F equations or prove vacuum stability after quantum corrections.')


def boson_hamiltonian(N=2,interaction=s.Rational(2,3)):
    assert N in (1,2)
    L=P.w33_laplacian();A=12*np.eye(40)-L
    basis=[tuple([i]) for i in range(40)] if N==1 else list(it.combinations_with_replacement(range(40),2))
    ix={v:i for i,v in enumerate(basis)};rows=[];cols=[];vals=[]
    for col,occupied in enumerate(basis):
        ns=Counter(occupied);rows.append(col);cols.append(col)
        vals.append(12*N+float(interaction)*sum(n*(n-1)/2 for n in ns.values()))
        for j,nj in ns.items():
            for i in np.flatnonzero(A[:,j]):
                new=list(occupied);new.remove(j);new.append(int(i));new.sort()
                rows.append(ix[tuple(new)]);cols.append(col);vals.append(-np.sqrt(nj*(ns.get(int(i),0)+1)))
    return coo_matrix((vals,(rows,cols)),shape=(len(basis),)*2).tocsr(),basis


@lru_cache(None)
def fixed_data_vacuum_certificate():
    H2,basis=boson_hamiltonian();H1,_=boson_hamiltonian(1)
    assert H2.shape==(820,820) and not (H2-H2.T).nnz
    assert np.allclose(H1.toarray(),P.w33_laplacian())
    local=np.array([v.count(0) for v in basis],float)
    comm=H2.multiply(local[None,:])-H2.multiply(local[:,None]);assert comm.nnz>0
    # Reuse one initial state, same observation time and boundary sector for all C.
    H=H1.toarray();psi=np.eye(40,dtype=complex)[:,0];time=.173;C=.731
    unshifted=expm(-1j*time*H)@psi;shifted=expm(-1j*time*(H+C*np.eye(40)))@psi
    phase_error=float(np.max(abs(shifted-np.exp(-1j*time*C)*unshifted)))
    assert phase_error<1e-13
    beta=.17
    def rho(op):
        a=expm(-beta*op);return a/np.trace(a)
    thermal_error=float(np.max(abs(rho(H+C*np.eye(40))-rho(H))))
    assert thermal_error<1e-13
    inhom=np.diag(np.eye(40)[0]);local_response=float(np.linalg.norm(rho(H+C*inhom)-rho(H)))
    assert local_response>1e-4
    V=s.diag(1,2);x=s.symbols('C',real=True);b=s.symbols('beta',positive=True)
    upper=1/(1+s.exp(b*x));response=s.diff(upper,x)
    assert s.simplify(response+b*upper*(1-upper))==0
    return dict(status='PASS',graph='actual W33 Pauli commutation graph,40 vertices and degree12',
        Hamiltonian='sum_ij L_ij b_i dagger b_j + (u/2)sum_i n_i(n_i-1), u=2/3',
        exact_N_sector_dimensions={'1':40,'2':820},fixed_N2_hopping_nonzeros=H2.nnz,
        local_volume_not_conserved=True,total_volume_operator='alpha sum_i n_i=alpha N I in each fixed-N sector',
        fixed_initial_state='one boson at canonical W33 point0, same observation time .173 and N=1',
        common_shift_unitary_phase_error=phase_error,fixed_sector_Gibbs_error=thermal_error,
        inhomogeneous_shift_Gibbs_response_norm=local_response,
        mixed_volume_probability_derivative=str(response),
        scope='A supplied quantum W33 many-body Hamiltonian with exactly conserved total occupation and dynamical local occupation. Common vacuum shifts cancel from normalized fixed-sector observables, while local shifts and volume-sector weights respond. Occupation is only a candidate volume carrier: no derived spacetime volume constraint, Einstein dynamics, gravitational screening or measured cosmological constant is established.')


@lru_cache(None)
def character_robustness_certificate():
    acts=cohomology_actions();rows=[];zeros=0
    for chars in it.product(CHARS,repeat=3):
        vs=[character_vector(a,c) for a,c in zip(acts,chars)];raw=cup(*vs)
        allowed=all(np.prod([c[k] for c in chars])==1 for k in range(2))
        if allowed:
            assert abs(raw)==2;rows.append(dict(characters=[list(c) for c in chars],cover_cup=int(raw)))
        else:assert raw==0;zeros+=1
    assert len(rows)==16 and zeros==48
    # SU5 Wilson parity acts identically on5 andbar5. All S_i are invariant.
    masses=[]
    for chi in CHARS:
        mat=s.zeros(3)
        for i,j in it.combinations(range(3),2):
            k=3-i-j;cs=[chi]*3;cs[k]=(1,1)
            vs=[character_vector(a,c) for a,c in zip(acts,cs)]
            mat[i,j]=mat[j,i]=cup(*vs)/4
        assert mat.rank()==3
        masses.append(dict(five_bar5_character=list(chi),matrix=mat.tolist(),determinant=str(mat.det())))
    # Integrate only the declared massive5/bar5 block. Reconstruct its
    # linear sources from the actual signed E6 tensor, not representation counts.
    labs,charges,D=matter_dictionary()
    five=[i for i,q in enumerate(charges) if q==-4]
    bars=[i for i,q in enumerate(charges) if q==-1 and labs[i][0]=='k']
    sing=labs.index(('A',3,6));gauge=s.Matrix(D[sing][np.ix_(five,bars)].tolist())
    mass=s.kronecker_product(family_mass((1,1,1)),gauge)
    a,b,c,d=s.symbols('a b c d');light=[{}, {}, {}]
    fields=[(0,('x',1,2,3),a),(1,('x',3,7,8),b),(2,('x',0,1,3),c),(0,('A',3,1),d)]
    for fam,lab,v in fields:light[fam][labs.index(lab)]=v
    sources=[]
    for heavy in (five,bars):
        vec=[]
        for fam in range(3):
            other=[i for i in range(3) if i!=fam]
            for index in heavy:
                value=0
                for ii,x in light[other[0]].items():
                    for jj,y in light[other[1]].items():
                        inds=[0]*3;inds[fam]=index;inds[other[0]]=ii;inds[other[1]]=jj
                        value+=s.Rational(1,2)*int(D[tuple(inds)])*x*y
                vec.append(value)
        sources.append(s.Matrix(vec))
    effective=s.expand(-(sources[1].T*mass.inv()*sources[0])[0])
    assert effective==-a*b*c*d/4
    return dict(status='PASS',all_character_triples=64,determinant_compatible_triples=16,
        compatible_nonzero_cups=rows,forbidden_zero_triples=zeros,
        every_character_sector_dimension_per_line=1,exotic_mass_matrices=masses,
        doublet_triplet_boundary='At the chosen equal singlet VEVs all four character mass blocks have full rank. Electroweak doublets are lifted along with colored triplets; this inventory has no retained light5/bar5 Higgs pair.',
        light_quartic_fields=[dict(family=f,root=list(lab),variable=str(v)) for f,lab,v in fields],
        heavy_linear_sources=[[str(v) for v in vec] for vec in sources],
        exact_integrated_superpotential_monomial=str(effective),
        proton_operator='The displayed component is Uc_family0 Ec_family1 Uc_family2 Dc_family0 of the SU5 operator10 10 10 bar5. It survives diag(1,1,1,-1,-1) visible Wilson parity.',
        proton_boundary='At equal supplied singlet VEVs the actual cubic therefore generates a nonzero dimension-five baryon/lepton-violating operator upon tree-level heavy-block elimination. This is an operator-existence obstruction, not a computed decay rate or a bound for every possible alignment/extra sector.',
        scope='An exhaustive exact lift/Wilson-character audit of the declared three-cohomology cup, plus a signed-root tree-level quartic witness. All16 compatible triples are nonzero; all48 forbidden triples vanish. The simple conditional exotic-lifting vacuum also removes the Higgs pair and generates a proton-decay operator, so it is not a realistic completed model.')


@lru_cache(None)
def anomaly_class_certificate():
    c2,_=M.chern_coefficients(K);pairs=list(it.combinations(range(4),2))
    budget=s.Matrix([4-c2[','.join(map(str,p))] for p in pairs])
    pairing_matrix=s.Matrix([[2*int(i not in p) for p in pairs] for i in range(4)])
    relation=s.Matrix([1,-1,0,0,-1,1]);assert pairing_matrix*relation==s.zeros(4,1)
    effective=budget-relation;assert list(budget)==[6,0,2,3,-1,5]
    assert list(effective)==[5,1,2,3,0,4] and all(x>=0 for x in effective)
    assert pairing_matrix*budget==s.Matrix([14,14,14,18])
    return dict(status='PASS',pair_order=[list(p) for p in pairs],raw_cover_budget=list(map(int,budget)),
        intersection_pairing_matrix=pairing_matrix.tolist(),pairing_rank=pairing_matrix.rank(),
        exact_cohomology_relation='J0J1+J2J3-J0J2-J1J3=0 in H4(X,Q)',
        relation_coefficients=list(map(int,relation)),effective_representative=list(map(int,effective)),
        budget_divisor_pairings=[14,14,14,18],
        proof='h11(X)=4 for the favorable smooth tetraquadric; Poincare duality makes zero pairing with all four J_i equivalent to a zero rational H4 class. Each nonnegative J_i J_j is a complete-intersection effective curve class.',
        descent_control='An effective cover cycle is not an explicitly descended equivariant cycle of the required quotient class. Averaging a representative over Gamma multiplies the class by4; dividing an effective cycle by4 is not an integral-cycle construction.',
        scope='Exact rational cohomology and effective cover Bianchi budget, correcting a basis-dependent negative-coefficient false alarm. Integral quotient anomaly data, equivariant hidden bundle/fivebrane realization, torsion classes, corrected HYM slopes and backreaction remain open.')


@lru_cache(None)
def kinetic_identifiability_certificate():
    Y=family_mass((1,1,1));assert Y.det()!=0
    examples=[]
    for masses in [(1,2,3),(1,s.Rational(1,10),s.Rational(1,100))]:
        D=s.diag(*masses);Z=Y.T*D**-2*Y
        assert Z.is_positive_definite and s.simplify(Y*Z.inv()*Y.T-D**2)==s.zeros(3)
        examples.append(dict(target_singular_values=list(map(str,masses)),positive_right_kinetic_metric=[[str(v) for v in row] for row in Z.tolist()]))
    # Any invertible holomorphic Dirac Y can realize any positive Hermitian Q:
    # Z_R=Y dagger Q^-1 Y gives Y Z_R^-1 Y dagger=Q, Z_L=I.
    Q=s.Matrix([[2,1,s.I],[1,3,0],[-s.I,0,4]])
    assert Q.is_positive_definite
    Z=Y.T*Q.inv()*Y;assert Z.is_positive_definite and Y*Z.inv()*Y.T==Q
    return dict(status='PASS',fixed_holomorphic_matrix=Y.tolist(),metric_counterexamples=examples,
        exact_general_map='Z_L=I, Z_R=Y dagger Q^-1 Y -> M M dagger=Q for M=Y Z_R^(-1/2), any positive Hermitian Q and invertible Y',
        nontrivial_complex_target_Q=[[[str(s.re(v)),str(s.im(v))] for v in row] for row in Q.tolist()],
        equal_VEV_holomorphic_eigenvalues=['1','-1/2','-1/2'],
        scope='A precise identifiability boundary: the same nonzero full-rank holomorphic interaction admits arbitrary Dirac singular values and left mixing when positive kinetic metrics are unspecified. This is not a freely adjustable metric claim inside a fixed CY vacuum; that vacuum must compute its metrics. It also does not claim independent left/right metrics for a single symmetric Majorana field.')


def payload():
    funcs=[flavor_certificate,flux_frame_certificate,anomaly_exotic_certificate,
           coupled_action_certificate,fixed_data_vacuum_certificate,
           character_robustness_certificate,anomaly_class_certificate,kinetic_identifiability_certificate]
    out=dict(status='PASS',reservation='3b08c1d72',schema='w33-nonzero-flavor-flux-v1',passes={},
             source_sha256=hashlib.sha256(Path(__file__).read_bytes().replace(b'\r\n',b'\n')).hexdigest())
    for n,f in enumerate(funcs,11742):
        out['passes'][str(n)]=f();print(n,'PASS',flush=True)
    out['physical_boundary']='Observed flavor, geometric anomaly completion, a jointly selected geometry/Higgs/clock, Lorentzian4D gravity and cosmological-constant screening remain unproved. The local split-duality frame and compact CY gauge bundle are distinct constructions.'
    return out


if __name__=='__main__':
    def encode(v):
        if isinstance(v,(s.Integer,np.integer)):return int(v)
        if isinstance(v,s.Basic):return str(v)
        raise TypeError(type(v).__name__)
    OUT.write_text(json.dumps(payload(),indent=2,sort_keys=True,default=encode)+'\n');print(OUT)
