#!/usr/bin/env python3
from __future__ import annotations
import hashlib,json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
def canon(d):
 x=dict(d);x.pop('sha256',None);return hashlib.sha256(json.dumps(x,sort_keys=True,separators=(',',':')).encode()).hexdigest()
def main():
 a=json.loads((ROOT/'data/w33_pass1857_lower_syndrome_orbit_atlas.json').read_text());d=json.loads((ROOT/'data/w33_pass1847_exact_weight5_decoder_completion.json').read_text())
 assert a['status']=='PASS' and a['sha256']==canon(a);assert d['status']=='PASS' and d['sha256']==canon(d)
 dec=d['decoder'];checks={'lower_orbits_110':a['orbit_count']==110,'lower_syndromes_1892792':a['lower_syndrome_count']==1892792,'weight1_single_orbit':a['minimum_weight_orbit_count']=={'1':1,'3':109},'fixed_partition':dec['fixed_coordinate_total']==dec['fixed_lower_shadow']+dec['fixed_unique_minimum_weight5']+dec['fixed_ambiguous_minimum_weight5'],'global_partition':dec['global_total_weight5']==dec['global_lower_shadow']+dec['global_unique_minimum_weight5']+dec['global_ambiguous_minimum_weight5']}
 out={'schema':'w33.pass1857.weight5_syndrome_orbit_atlas.v1','status':'PASS' if all(checks.values()) else 'FAIL','checks':checks,'lower_orbit_certificate_sha256':a['sha256'],'weight5_decoder_certificate_sha256':d['sha256'],'lower_syndrome_count':a['lower_syndrome_count'],'lower_orbit_count':a['orbit_count'],'minimum_weight_orbit_count':a['minimum_weight_orbit_count'],'orbit_type_count':len(a['orbit_type_histogram']),'fixed_coordinate_weight5':{'total':dec['fixed_coordinate_total'],'distinct_syndromes':dec['distinct_fixed_syndromes'],'lower_shadow':dec['fixed_lower_shadow'],'unique_minimum':dec['fixed_unique_minimum_weight5'],'ambiguous_minimum':dec['fixed_ambiguous_minimum_weight5'],'maximum_syndrome_multiplicity':dec['maximum_fixed_syndrome_multiplicity'],'minimum_syndrome_group_histogram':dec['minimum_syndrome_group_histogram']},'global_weight5':{'total':dec['global_total_weight5'],'lower_shadow':dec['global_lower_shadow'],'unique_minimum':dec['global_unique_minimum_weight5'],'ambiguous_minimum':dec['global_ambiguous_minimum_weight5']},'theorem':'Every syndrome reachable at odd weight below five lies in one of exactly 110 PSp(4,3)-orbits. One orbit has minimum weight one and 109 have minimum weight three. Coupled with the exact fixed-coordinate weight-five multiplicity sort, this is a symmetry-compressed fail-closed decoder atlas for all lower shadows and all local minimum multiplicities.','boundary':'The lower odd syndrome orbit atlas is complete. The minimum-weight-five multiplicity atlas is exact in one coordinate chart and global counts are exact by edge transitivity, but the full PSp orbit decomposition of all minimum-weight-five syndromes remains open.'}
 raw=json.dumps(out,sort_keys=True,separators=(',',':')).encode();out['sha256']=hashlib.sha256(raw).hexdigest();print(json.dumps(out,sort_keys=True,separators=(',',':')));raise SystemExit(out['status']!='PASS')
if __name__=='__main__':main()
