#!/usr/bin/env python3
"""Factor the 18 E8 holonomy characters as selector C3 x physical C6.

Parents:
  data/w33_e8_holonomy_packet18_homogeneous_bridge.json
  data/w33_physical_holonomy_e8_chevalley_lift.json

The packet-18 E8 table uses three commuting grading labels
  rho in C3 : the A8 selector inside E8,
  a   in C3 : the physical order-three Wilson line,
  b   in C2 : physical theta^3 parity.

Because C3 x C2 ~= C6, define the Chinese-remainder coordinate
  n = 4 a + 3 b mod 6.
Indeed n mod3=a and n mod2=b, and the physical generator (a,b)=(1,1)
is n=1.

Therefore
  K = C3_rho x C3_a x C2_b ~= C3_rho x C6_n.

Re-indexing the exact 18 E8 sector dimensions by (rho,n) gives
  rho=0: (16,12,12,16,12,12), sum 80  = sl9
  rho=1: (14,14,13,16,13,14), sum 84  = Lambda^3(9)
  rho=2: (14,14,13,16,13,14), sum 84  = Lambda^6(9)

Summing the three rho slices gives the independently derived physical C6
spectrum on E8:
  (44,40,38,48,38,40).

The power traces are
  chi(g^k) = (248,-2,14,-8,14,-2), k=0..5.
They agree entry-for-entry with the packet holonomy trace fingerprint along
the cyclic subgroup generated by (rho,a,b)=(0,1,1):
  g^k = (0, k mod3, k mod2).

There is also a basis-free recognition theorem. For a real 248-dimensional
C6 representation, m1=m5 and m2=m4. If
  dim Fix(g)=44,
  dim Fix(g^2)=92,
  dim Fix(g^3)=120,
then necessarily
  m=(44,40,38,48,38,40).
Thus the fixed algebras D4+A3+u1, D7+u1, D8 already determine the whole
physical C6 character without reference to the SU9 basis.

Boundary:
  This identifies the physical C6 inside the E8 HOLONOMY CHARACTER GROUP.
  It does not turn the runtime packet18 homogeneous space into that group;
  the packet18 parent explicitly proves that no such group identification
  exists. The surviving runtime relation remains a torsor/address bridge.
"""
from __future__ import annotations
import cmath,json,math
from pathlib import Path

ROOT=Path(__file__).resolve().parents[1]
OUT=ROOT/'data/w33_e8_holonomy_c3xc6_factorization.json'

def crt_n(a,b):
    return (4*a+3*b)%6

def dft_traces(m):
    z=cmath.exp(2j*math.pi/6)
    out=[]
    for k in range(6):
        x=sum(m[j]*(z**(j*k)) for j in range(6))
        assert abs(x.imag)<1e-8 and abs(x.real-round(x.real))<1e-8
        out.append(int(round(x.real)))
    return out

def main(write=True):
    packet=json.loads((ROOT/'data/w33_e8_holonomy_packet18_homogeneous_bridge.json').read_text())
    physical=json.loads((ROOT/'data/w33_physical_holonomy_e8_chevalley_lift.json').read_text())
    assert packet['status']=='PASS_TORSOR_BRIDGE__GROUP_IDENTIFICATION_KILLED'
    assert physical['status']=='PASS_PHYSICAL_INNER_CHEVALLEY_LIFT'

    dims={tuple(map(int,k.split(','))):int(v)
          for k,v in packet['E8_joint_sector_dimensions'].items()}
    traces={tuple(map(int,k.split(','))):int(v)
            for k,v in packet['E8_holonomy_trace_fingerprint'].items()}
    assert len(dims)==len(traces)==18
    assert sum(dims.values())==248

    # CRT isomorphism C3 x C2 -> C6.
    seen={}
    for a in range(3):
        for b in range(2):
            n=crt_n(a,b)
            assert n%3==a and n%2==b
            seen[n]=(a,b)
    assert len(seen)==6 and seen[1]==(1,1)

    slices={}
    for rho in range(3):
        m=[0]*6
        for a in range(3):
            for b in range(2):
                m[crt_n(a,b)]=dims[(rho,a,b)]
        slices[rho]=m

    assert slices[0]==[16,12,12,16,12,12]
    assert slices[1]==[14,14,13,16,13,14]
    assert slices[2]==[14,14,13,16,13,14]
    assert [sum(slices[r]) for r in range(3)]==[80,84,84]

    total=[sum(slices[r][n] for r in range(3)) for n in range(6)]
    assert total==physical['physical_C6_eigenvalue_multiplicities']
    assert total==[44,40,38,48,38,40]

    # Trace fingerprint along the physical cyclic subgroup.
    power_traces=dft_traces(total)
    assert power_traces==[248,-2,14,-8,14,-2]
    subgroup=[]
    for k in range(6):
        key=(0,k%3,k%2)
        subgroup.append({'k':k,'rho':0,'a':k%3,'b':k%2,
                         'trace':traces[key]})
        assert traces[key]==power_traces[k]

    # Basis-free reconstruction from fixed dimensions.
    fix_g=physical['fixed_algebras']['order6_product']['dimension']
    fix_g2=physical['fixed_algebras']['order3_W3']['dimension']
    fix_g3=physical['fixed_algebras']['order2_theta3']['dimension']
    assert (fix_g,fix_g2,fix_g3)==(44,92,120)

    m0=fix_g
    m3=fix_g2-m0
    # g^3 fixes the even exponents 0,2,4; reality gives m2=m4.
    m2=(fix_g3-m0)//2
    m4=m2
    remainder=248-(m0+m3+m2+m4)
    assert remainder%2==0
    m1=m5=remainder//2
    recovered=[m0,m1,m2,m3,m4,m5]
    assert recovered==total

    out={
      'schema':'w33.e8_holonomy_c3xc6_factorization.v1',
      'status':'PASS_EXACT_C3_SELECTOR_X_PHYSICAL_C6_FACTORIZATION',
      'headline':'The 18 E8 holonomy characters factor canonically as C3_selector x C6_physical under n=4a+3b mod6. The three rho slices are exactly the SU9 branching dimensions 80+84+84, with C6 spectra (16,12,12,16,12,12), (14,14,13,16,13,14), and its conjugate copy. Their sum is the physical E8 C6 spectrum (44,40,38,48,38,40). The power traces (248,-2,14,-8,14,-2) coincide exactly with the packet holonomy fingerprint along <(rho,a,b)=(0,1,1)>.',
      'group_factorization':{
        'original':'C3_rho x C3_a x C2_b',
        'reindexed':'C3_rho x C6_n',
        'CRT':'n=4a+3b mod6',
        'inverse':'a=n mod3, b=n mod2',
        'physical_C6_generator':'(rho,a,b)=(0,1,1) <-> (rho,n)=(0,1)'},
      'rho_slices':{
        '0':{'dimension':80,'SU9_branch':'sl9','C6_multiplicities':slices[0]},
        '1':{'dimension':84,'SU9_branch':'Lambda^3(9)','C6_multiplicities':slices[1]},
        '2':{'dimension':84,'SU9_branch':'Lambda^6(9)','C6_multiplicities':slices[2]}},
      'full_E8':{
        'dimension':248,
        'C6_multiplicities':total,
        'power_traces':power_traces,
        'cyclic_subgroup_trace_witness':subgroup},
      'basis_free_recognition':{
        'fixed_dimensions':{'g':fix_g,'g2':fix_g2,'g3':fix_g3},
        'fixed_algebras':{'g':'D4+A3+u1','g2':'D7+u1','g3':'D8'},
        'reality_constraints':'m1=m5 and m2=m4',
        'recovered_C6_multiplicities':recovered,
        'conclusion':'The three fixed-algebra dimensions uniquely determine the full real C6 character.'},
      'runtime_boundary':'The physical C6 lives in the E8 holonomy character group. The 18 runtime packet blocks are a homogeneous space with no C3^2 x C2 group law; only the previously certified torsor/address bridge survives.',
      'parents':['data/w33_e8_holonomy_packet18_homogeneous_bridge.json',
                 'data/w33_physical_holonomy_e8_chevalley_lift.json'],
      'checks':{
        'CRT_bijection':True,
        'rho_slices_80_84_84':True,
        'sum_matches_physical_C6':True,
        'power_traces_match_packet_fingerprint':True,
        'fixed_dimensions_recover_spectrum':True}}
    if write:OUT.write_text(json.dumps(out,indent=2)+'\n')
    print(json.dumps(out,indent=2));return out

if __name__=='__main__':main(True)
