"""Pass 11656: the label-sensitive arrows are the two lowest arrows dressed by the shared spectrum.

On the equal-spectra locus Sigma(Z, X) (Pass 11648), let e_s, Pi_s be the e2 and the triple product of the shared
spectrum and N = |psi|^2.  FOUND (numerically, certified through degree 15 by the floating-point rank check of 11648):
  * the restriction of the whole time-odd module to Sigma is generated by the two lowest arrows g6 (= h6 up to scale,
    Pass 11434) and g7 over the polynomial ring R = C[N, e_s, Pi_s];
  * the dependencies among {g6 R_(k-6), g7 R_(k-7)} number 0, 0, 0, 1, 1, 2, 3, 4, 5, 7 in degrees 6..15 -- exactly the
    coefficients of t^9 / ((1-t)(1-t^2)(1-t^3)): ONE relation in degree 9, generating a free R-module.
  Hence  Hilb(O|Sigma) = (t^6 + t^7 - t^9) / ((1-t)(1-t^2)(1-t^3)),  which DERIVES the series fitted in Pass 11648
  (given this presentation).  The degree-9 relation  a N^3 g6 + b N e_s g6 + c Pi_s g6 + d N^2 g7 + f e_s g7 = 0  on
  Sigma is computed and its coefficients rationalised (checked on fresh points).
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "analysis"))
import w33_pass11648_label_blind_sigma as LB  # noqa: E402

OUT = ROOT / "data" / "w33_pass11656_sigma_module_two_arrows.json"


def ring_monos(deg, e_s, P_s):
    out = []
    for c in range(deg // 3 + 1):
        for b in range((deg - 3 * c) // 2 + 1):
            out.append(e_s ** b * P_s ** c)
    return out


def main():
    res = dict(pass_id=11656)
    sig = LB.sigma_points(300, 0, 1, seed=5)
    ps = np.array([LB.probs(x) for x in sig])
    q = ps[:, LB.mubs[0]]
    e_s = q[:, 0] * q[:, 1] + q[:, 0] * q[:, 2] + q[:, 1] * q[:, 2]
    P_s = q.prod(1)
    g = {name: LB.R(m, True, ps) for name, (dg, m) in LB.OG.items()}
    rows = {}
    for k in range(6, 16):
        cols = []
        for name, dg in (("g6", 6), ("g7", 7)):
            if k >= dg:
                cols += [g[name] * m for m in ring_monos(k - dg, e_s, P_s)]
        r_mod, _ = LB.rank(np.stack(cols, 1))
        r_full, _ = LB.rank(LB.odd_basis_vals(k, ps))
        rows[k] = dict(listed=len(cols), span=r_mod, full_on_Sigma=r_full, relations=len(cols) - r_mod)
        print(k, rows[k], flush=True)
    res["by_degree"] = rows
    pred = [0, 0, 0, 1, 1, 2, 3, 4, 5, 7]
    res["relations_match_t9_over_R"] = [rows[k]["relations"] for k in range(6, 16)] == pred
    res["generated_by_g6_g7"] = all(v["span"] == v["full_on_Sigma"] for v in rows.values())
    # the degree-9 relation (N = 1 on normalised states; homogenise by degree)
    A = np.stack([g["g6"], g["g6"] * e_s, g["g6"] * P_s, g["g7"], g["g7"] * e_s], 1)
    _, s, Vh = np.linalg.svd(A / np.abs(A).max(0))
    v = Vh[-1] / np.abs(A).max(0)
    v = v / v[np.argmax(np.abs(v))]
    import sympy as sp
    rat = [sp.nsimplify(float(x), tolerance=1e-7, rational=True) for x in v]
    sig2 = LB.sigma_points(100, 0, 1, seed=99)
    ps2 = np.array([LB.probs(x) for x in sig2])
    q2 = ps2[:, LB.mubs[0]]
    e2 = q2[:, 0] * q2[:, 1] + q2[:, 0] * q2[:, 2] + q2[:, 1] * q2[:, 2]
    P2 = q2.prod(1)
    g62, g72 = (LB.R(LB.OG[nm][1], True, ps2) for nm in ("g6", "g7"))
    A2 = np.stack([g62, g62 * e2, g62 * P2, g72, g72 * e2], 1)
    resid = np.abs(A2 @ np.array([float(x) for x in rat])).max() / np.abs(A2).max()
    res["degree9_relation"] = dict(terms=["N^3 g6", "N e_s g6", "Pi_s g6", "N^2 g7", "e_s g7"],
                                   coefficients=[str(x) for x in rat], smallest_singular_value_ratio=float(s[-1] / s[0]),
                                   relative_residual_on_fresh_points=float(resid))
    print(res["degree9_relation"], flush=True)
    json.dump(res, open(OUT, "w"), indent=1, default=str)


if __name__ == "__main__":
    main()
