#include <bits/stdc++.h>
using namespace std;
static const int NF=540,W=9;
struct Mask{array<uint64_t,W>w{}; bool operator==(Mask const&o)const{return w==o.w;}};
struct Hash{size_t operator()(Mask const&m)const noexcept{uint64_t h=1469598103934665603ULL;for(auto x:m.w){h^=x;h*=1099511628211ULL;}return h;}};
inline void setb(Mask&m,int x){m.w[x>>6]|=1ULL<<(x&63);} inline bool disj(const Mask&a,const Mask&b){for(int i=0;i<W;i++)if(a.w[i]&b.w[i])return false;return true;}
inline bool subset(const Mask&a,const Mask&b){for(int i=0;i<W;i++)if(a.w[i]&~b.w[i])return false;return true;} inline Mask subm(const Mask&a,const Mask&b){Mask c;for(int i=0;i<W;i++)c.w[i]=a.w[i]&~b.w[i];return c;}
inline int pop(const Mask&a){int n=0;for(auto x:a.w)n+=__builtin_popcountll(x);return n;} Mask transform(const Mask&k,const vector<int>&g){Mask y;for(int wi=0;wi<W;wi++){uint64_t x=k.w[wi];while(x){int b=__builtin_ctzll(x);x&=x-1;int r=64*wi+b;if(r<NF)setb(y,g[r]);}}return y;}
struct Search{vector<Mask>rows;vector<vector<int>>inc;uint64_t nodes=0;int target=8;vector<int>sol;chrono::steady_clock::time_point start;double limit=120;bool timeout=false;
 bool dfs(Mask rem,int depth){nodes++;if((nodes&0x3ffff)==0&&chrono::duration<double>(chrono::steady_clock::now()-start).count()>limit){timeout=true;return false;}int pc=pop(rem);if(pc==0)return depth==target;if(depth>=target||pc!=60*(target-depth))return false;int best=-1,bn=INT_MAX;for(int wi=0;wi<W;wi++){uint64_t x=rem.w[wi];while(x){int b=__builtin_ctzll(x);x&=x-1;int f=wi*64+b;if(f>=NF)continue;int n=0;for(int ri:inc[f])if(subset(rows[ri],rem))n++;if(n<bn){bn=n;best=f;if(n==0)return false;}}}vector<int>cand;for(int ri:inc[best])if(subset(rows[ri],rem))cand.push_back(ri);vector<pair<long long,int>>ord;for(int ri:cand){long long sc=0;for(int wi=0;wi<W;wi++){uint64_t x=rows[ri].w[wi];while(x){int b=__builtin_ctzll(x);x&=x-1;sc+=inc[wi*64+b].size();}}ord.push_back({sc,ri});}sort(ord.begin(),ord.end());for(auto[sc,ri]:ord){sol.push_back(ri);if(dfs(subm(rem,rows[ri]),depth+1))return true;sol.pop_back();if(timeout)return false;}return false;}};
int main(int argc,char**argv){if(argc<4){cerr<<"usage group.in reps.bin out.json [maxorbits] [seconds]\n";return 2;}int maxo=argc>4?atoi(argv[4]):327;double lim=argc>5?atof(argv[5]):120;ifstream fi(argv[1]);int nr,ne,ng;fi>>nr>>ne>>ng;int z;for(int i=0;i<nr*4;i++)fi>>z;vector<vector<int>>gens(ng,vector<int>(NF));for(auto&g:gens)for(int&i:g)fi>>i;vector<vector<int>>G;unordered_set<string>seen;vector<int>id(NF);iota(id.begin(),id.end(),0);auto key=[](auto const&p){return string((char*)p.data(),p.size()*sizeof(int));};G.push_back(id);seen.insert(key(id));for(size_t h=0;h<G.size();h++)for(auto&g:gens){vector<int>q(NF);for(int i=0;i<NF;i++)q[i]=g[G[h][i]];if(seen.insert(key(q)).second)G.push_back(move(q));}
 ifstream rb(argv[2],ios::binary);uint64_t nrep;rb.read((char*)&nrep,8);vector<Mask>reps(nrep);vector<uint32_t>os(nrep),st(nrep),hits(nrep);for(size_t i=0;i<nrep;i++){for(int j=0;j<60;j++){uint16_t x;rb.read((char*)&x,2);setb(reps[i],x);}rb.read((char*)&os[i],4);rb.read((char*)&st[i],4);rb.read((char*)&hits[i],4);}unordered_set<Mask,Hash>cs;cs.reserve(4500000);for(auto&r:reps)for(auto&g:G)cs.insert(transform(r,g));vector<Mask>covers(cs.begin(),cs.end());if(covers.size()!=3547800)return 3;ofstream out(argv[3]);out<<"{\"group_order\":"<<G.size()<<",\"global_covers\":"<<covers.size()<<",\"records\":[";bool first=true,any=false;int count13648=0;Mask full;for(int i=0;i<NF;i++)setb(full,i);
 for(int oi=0;oi<(int)nrep&&oi<maxo;oi++){vector<Mask>link;for(auto&m:covers)if(disj(m,reps[oi]))link.push_back(m);if(link.size()==13648)count13648++;Mask rem=subm(full,reps[oi]);Search S;S.rows=move(link);S.inc.assign(NF,{});S.limit=lim;for(int i=0;i<(int)S.rows.size();i++)for(int wi=0;wi<W;wi++){uint64_t x=S.rows[i].w[wi];while(x){int b=__builtin_ctzll(x);x&=x-1;int f=wi*64+b;if(f<NF)S.inc[f].push_back(i);}}S.start=chrono::steady_clock::now();bool sat=S.dfs(rem,0);double sec=chrono::duration<double>(chrono::steady_clock::now()-S.start).count();any|=sat;if(!first)out<<",";first=false;out<<"{\"orbit\":"<<oi<<",\"orbit_size\":"<<os[oi]<<",\"stabilizer_order\":"<<(25920/os[oi])<<",\"link_size\":"<<S.rows.size()<<",\"k8\":"<<(sat?"true":"false")<<",\"timeout\":"<<(S.timeout?"true":"false")<<",\"nodes\":"<<S.nodes<<",\"seconds\":"<<fixed<<setprecision(6)<<sec<<"}";out.flush();if(sat)break;}out<<"],\"any_k8\":"<<(any?"true":"false")<<",\"link_13648_count\":"<<count13648<<"}\n";}
