"""W(3,3) BREAKTHROUGH 92: CORRECTION-LATTICE MINIMAL GENERATORS.

BT87/BT90 surfaced 5 RECURRING correction factors used across 2-3
independent observables. This BT asks: are the recurring factors all
expressible as monomials in a SMALL generating set of substrate primes?
A small generating set is structural evidence that the correction
algebra is substrate-derived.

==============================================================
THE 5 RECURRING CORRECTION FACTORS (BT90 INVENTORY)
==============================================================

  Factor          Substrate form         Appears in (n times)
  --------------- ---------------------- ---------------------
  1/28            1/(mu*Phi_6)            2x (QED + CMB)
  1/25            1/F_5^2                  3x (CKM + Hubble + nu mass)
  169             Phi_3^2                  2x (m_t + m_W/M_Pl)
  35              F_5*Phi_6                2x (cosmology + Klein)
  1/3             1/q                       2x (m_t/m_b + m_s/m_u)

==============================================================
MINIMAL GENERATING SET
==============================================================

All 5 recurring factors are monomials in just 5 substrate primes:

  q, mu, F_5, Phi_3, Phi_6

  Factor     Monomial form
  ---------  ------------------------
  1/28       (mu * Phi_6)^(-1)
  1/25       F_5^(-2)
  169        Phi_3^(+2)
  35         F_5^(+1) * Phi_6^(+1)
  1/3        q^(-1)

EVERY recurring factor is a monomial in the 5 generators with integer
exponents in {-2, -1, 0, +1, +2}.

==============================================================
SUBSTRATE-CYCLOTOMIC ORGANIZATION
==============================================================

The 5 generators split as:

  ATOMIC (substrate primes from master equation):
    q = 3    (master equation q!=2q forces q=3)
    F_5 = 5  (smallest prime > q)

  CYCLOTOMIC (Phi_n(3) values, BT83):
    mu = Phi_2(3) = 4
    Phi_3 = Phi_3(3) = 13
    Phi_6 = Phi_6(3) = 7

So the recurring correction algebra is generated by 2 ATOMIC + 3
CYCLOTOMIC substrate values. The 5 cyclotomic primitives that BT83
identified (1, 2, 3, 4, 5, 6, 12) overlap with the correction
generators precisely at {2, 3, 6}.

NOTE: F_5 = mu + 1 = q + lambda is itself a small substrate combo.

==============================================================
THE CORRECTION LATTICE
==============================================================

Define L = {q^a * mu^b * F_5^c * Phi_3^d * Phi_6^e : a,b,c,d,e in Z}.

Then the 5 recurring factors are 5 specific points in L:

  v_1 = (0, -1, 0, 0, -1) = 1/28
  v_2 = (0, 0, -2, 0, 0)  = 1/25
  v_3 = (0, 0, 0, +2, 0)  = 169
  v_4 = (0, 0, +1, 0, +1) = 35
  v_5 = (-1, 0, 0, 0, 0)  = 1/3

These 5 vectors span a rank-5 sub-lattice of L. The correction
algebra is EXACTLY rank 5 = number of recurring factors.

NORM (in L_infinity): max |exponent| = 2 (for Phi_3^2 and F_5^-2).

==============================================================
WHAT THIS SHOWS
==============================================================

If the substrate were curve-fitting, correction factors would draw
from a wide range of primes (37, 41, 43, 71, etc. -- often
appearing in PDG calculations). They would not concentrate on
substrate primes.

INSTEAD: 5 of 5 recurring factors are monomials in 5 substrate
primes. The correction algebra is structurally compatible with the
W(3,3) substrate, not with random number-crunching.

Specifically:
  - The Φ_n cyclotomic ladder (n=2, 3, 6) supplies 3 of 5 generators.
  - The master equation prime q supplies 1.
  - The smallest post-q prime F_5 supplies 1.

==============================================================
ADDITIONAL PATTERNS
==============================================================

Several non-recurring BT85 correction factors ALSO live in L:

  1/48 = 1/(q!*2^q) = 1/(q*lambda^q*lambda)  [Lambda_QCD/m_p]
       = q^(-1) * lambda^(-3) * mu^(-1)  -- needs lambda too

  77/100 = (Phi_6*p_Ih)/Phi_4^2  [m_mu/m_e]
       Adds Phi_4 and p_Ih to the generator set.

  5/2 = F_5/lambda  [m_s]
       Adds lambda.

  1/1600 = 1/(lambda^mu * Phi_4^2)  [n_s next-order]
       Adds lambda and Phi_4.

So the FULL correction lattice for ALL observed substrate corrections
needs:
  {q, lambda, mu, F_5, Phi_3, Phi_4, Phi_6, p_Ih}

8 generators, still substrate-pure.

==============================================================
"""
from __future__ import annotations

import json
import math
from fractions import Fraction
from pathlib import Path


def main():
    q = 3
    lambda_, mu = 2, 4
    F5 = 5
    phi3, phi4, phi6, phi12 = 13, 10, 7, 73
    k, v, E_count = 12, 40, 240
    f, g_neg = 24, 15
    p_Ih = 11
    q_fact = math.factorial(q)

    print("=" * 78)
    print("W(3,3) BREAKTHROUGH 92: CORRECTION-LATTICE MINIMAL GENERATORS")
    print("=" * 78)
    print()

    print("5 RECURRING CORRECTION FACTORS (BT90 inventory):")
    print(f"  1/28 = 1/(mu*Phi_6)         used in 2 places")
    print(f"  1/25 = 1/F_5^2               used in 3 places")
    print(f"  169  = Phi_3^2               used in 2 places")
    print(f"  35   = F_5*Phi_6             used in 2 places")
    print(f"  1/3  = 1/q                    used in 2 places")
    print()

    print("MINIMAL GENERATING SET (5 atoms):")
    generators = ["q", "mu", "F_5", "Phi_3", "Phi_6"]
    gen_vals = [q, mu, F5, phi3, phi6]
    print(f"  Atoms: {', '.join(generators)}")
    print(f"  Values: {gen_vals}")
    print()

    print("MONOMIAL DECOMPOSITION:")
    factors = [
        (Fraction(1, 28), [0, -1, 0, 0, -1], "1/(mu*Phi_6)"),
        (Fraction(1, 25), [0, 0, -2, 0, 0],  "F_5^(-2)"),
        (Fraction(169, 1), [0, 0, 0, 2, 0],  "Phi_3^(+2)"),
        (Fraction(35, 1),  [0, 0, 1, 0, 1],  "F_5 * Phi_6"),
        (Fraction(1, 3),   [-1, 0, 0, 0, 0], "q^(-1)"),
    ]
    print(f"  Factor     | Vector (q, mu, F_5, Phi_3, Phi_6) | Form")
    for fac, vec, form in factors:
        # verify
        prod = Fraction(1, 1)
        for g, e in zip(gen_vals, vec):
            if e > 0: prod *= g ** e
            elif e < 0: prod /= g ** (-e)
        assert prod == fac, f"{fac} != {prod}"
        print(f"  {str(fac):<10} | {str(vec):<33} | {form}")
    print()
    print(f"  All 5 verified. Rank 5 sub-lattice.")
    print(f"  Max |exponent| = 2 (Phi_3^2 and F_5^-2)")
    print()

    print("SUBSTRATE-CYCLOTOMIC ORGANIZATION:")
    print(f"  ATOMIC primes (master eq + smallest post-q):")
    print(f"    q = 3   (Diophantine master eq)")
    print(f"    F_5 = 5 (smallest prime > q)")
    print(f"  CYCLOTOMIC values Phi_n(3) (BT83):")
    print(f"    mu = Phi_2(3) = 4")
    print(f"    Phi_3 = Phi_3(3) = 13")
    print(f"    Phi_6 = Phi_6(3) = 7")
    print(f"  Total: 2 atomic + 3 cyclotomic.")
    print(f"  Note F_5 = mu+1 = q+lambda (small substrate combo).")
    print()

    print("WHY THIS MATTERS:")
    print(f"""  If the substrate were curve-fitting, correction factors would draw
  from arbitrary primes (37, 41, 43, 47, 53, 71, ...) common in PDG
  calculations. They DO NOT.

  Instead, ALL 5 recurring factors are monomials in just 5 substrate
  primes. The 3 cyclotomic generators (mu, Phi_3, Phi_6) match exactly
  the BT83 cyclotomic ladder Phi_n(3) for small n.

  This is STRUCTURAL evidence: the correction algebra and the
  substrate share the same arithmetic foundations.""")
    print()

    print("FULL CORRECTION LATTICE (including non-recurring BT85 factors):")
    print(f"  Adding lambda, Phi_4, p_Ih extends the generator set to:")
    full_gens = ["q", "lambda", "mu", "F_5", "Phi_3", "Phi_4", "Phi_6", "p_Ih"]
    print(f"    {{{', '.join(full_gens)}}} -- 8 substrate primitives.")
    print(f"  Still substrate-pure, no non-W33 primes needed.")
    print()

    print("=" * 78)
    print("BREAKTHROUGH 92 SUMMARY")
    print("=" * 78)
    print(f"""
THE CORRECTION ALGEBRA HAS A MINIMAL GENERATING SET.

Five recurring substrate correction factors are monomials in 5 atoms:
  q (master eq), F_5 (smallest post-q prime),
  mu, Phi_3, Phi_6 (cyclotomic values at q=3)

Each factor uses exponents in {{-2, -1, 0, +1, +2}}. Rank-5 lattice.
Max norm = 2 (Phi_3^2 = 169 and F_5^(-2) = 1/25).

CYCLOTOMIC ORIGIN:
The 3 cyclotomic generators (mu = Phi_2(3), Phi_3, Phi_6) come from
the BT83 cyclotomic ladder. The same Phi_n(3) values that BT83 named
as "previously unnamed substrate identities" are the engine of the
correction algebra.

THE FULL CORRECTION LATTICE (BT85 non-recurring + BT90 recurring) uses
8 generators: q, lambda, mu, F_5, Phi_3, Phi_4, Phi_6, p_Ih.
All substrate-pure. No non-W(3,3) primes.

INTERPRETATION:
  Curve-fitting would draw correction factors from arbitrary primes.
  Substrate-source theory gives correction factors that are monomials
  in the substrate primitives themselves.

The data is structurally compatible with the substrate being the source.
""")

    out = Path("data") / "w33_BREAKTHROUGH_92_correction_lattice_generators.json"
    out.parent.mkdir(exist_ok=True)
    out.write_text(json.dumps({
        "5_recurring_factors": [
            {"factor": "1/28", "form": "1/(mu*Phi_6)",  "vec": [0,-1,0,0,-1]},
            {"factor": "1/25", "form": "F_5^(-2)",      "vec": [0,0,-2,0,0]},
            {"factor": "169",  "form": "Phi_3^(+2)",    "vec": [0,0,0,2,0]},
            {"factor": "35",   "form": "F_5 * Phi_6",   "vec": [0,0,1,0,1]},
            {"factor": "1/3",  "form": "q^(-1)",        "vec": [-1,0,0,0,0]},
        ],
        "minimal_generating_set": generators,
        "minimal_count": 5,
        "atomic_vs_cyclotomic": {
            "atomic": ["q", "F_5"],
            "cyclotomic": ["mu = Phi_2(3)", "Phi_3 = Phi_3(3)", "Phi_6 = Phi_6(3)"],
        },
        "max_norm": 2,
        "rank": 5,
        "full_correction_lattice_generators": [
            "q", "lambda", "mu", "F_5", "Phi_3", "Phi_4", "Phi_6", "p_Ih"
        ],
        "full_count": 8,
        "substrate_pure": True,
        "conclusion": (
            "The recurring correction algebra (BT85+BT87+BT90) is generated "
            "by 5 substrate primes: q, mu, F_5, Phi_3, Phi_6. Each "
            "recurring factor is a monomial with exponents in {-2,-1,+1,+2}. "
            "Rank-5 lattice, max norm 2. The cyclotomic origin (mu=Phi_2(3), "
            "Phi_3=Phi_3(3), Phi_6=Phi_6(3)) connects directly to BT83's "
            "cyclotomic ladder. Full correction lattice uses 8 substrate "
            "primes; no non-W(3,3) primes needed. Curve-fitting would draw "
            "from arbitrary primes; substrate-source theory predicts "
            "exactly this monomial structure."
        ),
    }, indent=2, default=str), encoding="utf-8")
    print(f"wrote {out}")


if __name__ == "__main__":
    main()
