#!/usr/bin/env python3
"""Pass10073-10080: an actual integral self-dual local Hermitian lift.

Let K=Q_3(i), O_K=Z_3[i], L=K(zeta_9), O_L=O_K[zeta_9], and t=zeta_9-1.
Then L/K is totally ramified of degree 6.  Define the semilinear involution

    tau(i)=-i,       tau(zeta_9)=zeta_9^{-1}.

It restricts to the unramified conjugation on K and sends t to -t/(1+t).

The relative different is generated by Phi_9'(zeta_9).  Since

    Phi_9'(zeta)=3*zeta^2*(2*zeta^3+1)

and, in t-adic valuation, v_L(3)=6 while

    2*zeta^3+1 = 3+6t+6t^2+2t^3

has valuation 3, the different exponent is 9:

    D_{L/K}=t^9 O_L.

Now c=i*t^{-9}.  Because tau(t^{-9})=-t^{-9} and tau(i)=-i, tau(c)=c.
Therefore

    h(x,y)=Tr_{L/K}( c*x*tau(y) )

is K/K^tau-Hermitian.  Since c O_L=D^{-1}, the trace-dual of O_L is exactly
O_L: this is an integral SELF-DUAL rank-6 O_K Hermitian lattice.  Moreover
zeta_9*tau(zeta_9)=1, so multiplication by zeta_9 is unitary.

Reduction mod 3 is a nondegenerate Hermitian form on O_L/3O_L, whose associated
F9 residue dimension is six.  Nondegenerate Hermitian forms of fixed dimension
over F9 are unique up to isometry, so this integral lattice lifts the explicit
rank-6 finite Hermitian form from Pass10009/10025 up to basis change.

This is stronger than a finite-level Hensel guess, but it is still LOCAL.  It
does not identify a global Niemeier lattice with O_L.
"""
from __future__ import annotations
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
OUT=ROOT/'data/PART_W33_PASS10073_10080_INTEGRAL_HERMITIAN_LIFT.json'

def t_valuation_terms(terms, v3):
    # terms = [(integer coefficient, t-power)] and v_L(3)=6.
    vals=[]
    for a,k in terms:
        n=abs(a);vp=0
        while n and n%3==0:vp+=1;n//=3
        vals.append(vp*v3+k)
    return min(vals),vals

def main():
    # Phi9(1+t) exact coefficient list low to high.
    phi=[3,9,18,21,15,6,1]
    assert [x%3 for x in phi]==[0,0,0,0,0,0,1]
    # derivative factor 2*zeta^3+1 = 3+6t+6t^2+2t^3
    vfac,termvals=t_valuation_terms([(3,0),(6,1),(6,2),(2,3)],6)
    assert vfac==3 and termvals==[6,7,8,3]
    different_exp=6+vfac
    assert different_exp==9
    # tau(t)=-t/(1+t), so tau(t^-9)=(-1)^-9 t^-9 (1+t)^9=-t^-9.
    tau_t_minus9_sign=-1
    tau_i_sign=-1
    assert tau_t_minus9_sign*tau_i_sign==1
    out={
      'schema':'w33.pass10073_10080.integral_hermitian_lift.v1','status':'PASS','passes':'10073-10080',
      'fields':{'K':'Q3(i)','O_K':'Z3[i]','L':'K(zeta9)','O_L':'O_K[zeta9]','relative_degree':6,'ramification':'totally ramified','uniformizer':'t=zeta9-1'},
      'involution':{'tau_i':'-i','tau_zeta9':'zeta9^-1','tau_t':'-t/(1+t)','residue_on_F9':'x -> x^3'},
      'different':{
        'Phi9_derivative':'3*zeta9^2*(2*zeta9^3+1)',
        '2zeta3_plus1_t_expansion':'3+6t+6t^2+2t^3',
        'term_valuations':termvals,'factor_valuation':vfac,'v_L_3':6,'different_exponent':different_exp,
        'ideal':'D_{L/K}=t^9 O_L'},
      'self_dual_form':{
        'c':'i*t^-9','tau_c_equals_c':True,
        'form':'h(x,y)=Tr_{L/K}(i*t^-9*x*tau(y))',
        'integral_reason':'c O_L = D^{-1}, the codifferent',
        'self_dual_reason':'the trace dual of O_L under c*x*tau(y) is c^-1 D^-1=O_L',
        'rank_over_O_K':6},
      'cyclotomic_unitary':{'operator':'multiplication by zeta9','identity':'zeta9*tau(zeta9)=1','unitary':True},
      'residue_match':{'mod3_algebra':'F9[t]/(t^6)','Hermitian_dimension_over_F9':6,'match_to_previous_explicit_H':'unique up to F9-Hermitian isometry'},
      'theorem':'O_L carries an explicit integral self-dual rank-6 O_K Hermitian form h(x,y)=Tr_{L/K}(i t^-9 x tau(y)) for which multiplication by zeta9 is unitary. Thus the finite F9^6 unitary module has an actual local integral self-dual lift, unique at residue level up to Hermitian isometry.',
      'boundary':'Local 3-adic theorem only. It does not prove that a global Niemeier lattice is an O_L lattice, nor that the previously chosen finite basis lifts coefficient-by-coefficient without change of basis.'}
    OUT.write_text(json.dumps(out,indent=2,sort_keys=True)+'\n')
    print(json.dumps({'status':'PASS','different_exponent':9,'self_dual':True,'zeta9_unitary':True}))
    return 0
if __name__=='__main__':raise SystemExit(main())
