"""Integral, PSp(4,3)-equivariant homology bridge from native 40-line W33
clique complex to the W33 point-line Levi graph, and canonical mod-3
cycle pairing. Character equality was PRIOR work, not claimed new.
"""
from pathlib import Path
from itertools import combinations
import sys,json,math,hashlib
import numpy as np
ROOT=Path(__file__).resolve().parents[1];sys.path.insert(0,str(ROOT/'analysis'))
from w33_pass1081_1086_core import build_w33,transvection_perm,outer_similitude_perm,line_perm
from w33_pass1081_1086_core import rank_mod
P=3

def chain():
 pts,ix,lines,li,pl,*_=build_w33()
 edges=sorted({tuple(sorted(e)) for L in lines for e in combinations(L,2)})
 tris=sorted({tuple(sorted(t)) for L in lines for t in combinations(L,3)})
 flags=sorted((p,l) for l,L in enumerate(lines) for p in L)
 ei={v:j for j,v in enumerate(edges)};fi={f:j for j,f in enumerate(flags)}
 E=np.zeros((40,240),dtype=np.int64)
 T=np.zeros((240,160),dtype=np.int64)
 DL=np.zeros((80,160),dtype=np.int64)
 M=np.zeros((160,240),dtype=np.int64)
 for j,(a,b) in enumerate(edges):
  E[a,j]=-1;E[b,j]=1
  line=next(l for l,L in enumerate(lines) if a in L and b in L)
  M[fi[(a,line)],j]=1;M[fi[(b,line)],j]=-1
 for j,(a,b,c) in enumerate(tris):
  T[ei[(b,c)],j]=1;T[ei[(a,c)],j]=-1;T[ei[(a,b)],j]=1
 for j,(p,l) in enumerate(flags):
  DL[p,j]=-1;DL[40+l,j]=1
 J=np.zeros((80,40),dtype=np.int64);J[:40,:40]=np.eye(40,dtype=np.int64)
 assert np.array_equal(DL@M,J@E)
 assert np.array_equal(M@T,np.zeros((160,160),dtype=np.int64))
 assert np.array_equal(E@T,np.zeros((40,160),dtype=np.int64))
 # Local integral lift. Pick lowest point a(L); for flag (p,L), p != a,
 # lift -[a,p] to clique oriented edge; a on the line is implicit.
 Lift=np.zeros((240,160),dtype=np.int64)
 for j,(p,l) in enumerate(flags):
  a=min(lines[l])
  if p==a:continue
  b=(min(a,p),max(a,p));Lift[ei[b],j]=-1 if a<p else 1
 return pts,ix,lines,li,edges,tris,flags,fi,E,T,DL,M,Lift

def integer_cycle_basis(flags):
 adj=[[] for _ in range(80)]
 for j,(p,l) in enumerate(flags):
  adj[p].append((40+l,j));adj[40+l].append((p,j))
 parent=[-1]*80;pe=[-1]*80;depth=[0]*80;seen={0};queue=[0]
 for v in queue:
  for w,j in adj[v]:
   if w not in seen:
    seen.add(w);parent[w]=v;pe[w]=j;depth[w]=depth[v]+1;queue.append(w)
 assert len(seen)==80
 tree=set(j for j in pe if j!=-1)
 chords=[j for j in range(160) if j not in tree]
 assert len(chords)==81
 Z=np.zeros((160,81),dtype=np.int64)
 # d(e) = end-start; add each chord and cancel its divergence up the tree
 for col,chord in enumerate(chords):
  x=np.zeros(160,dtype=np.int64);x[chord]=1
  p,l=flags[chord];balance=np.zeros(80,dtype=np.int64)
  balance[p]-=1;balance[40+l]+=1
  for v in sorted(range(1,80),key=lambda v:depth[v],reverse=True):
   e=pe[v];start,end=flags[e][0],40+flags[e][1]
   sign=1 if v==end else -1
   xv=-balance[v]*sign
   x[e]=xv;balance[v]=0;balance[parent[v]]-=sign*xv
  assert not np.any(balance)
  Z[:,col]=x
 assert np.array_equal(Z[chords],np.eye(81,dtype=np.int64))
 return Z,chords

def equivariance(pts,ix,lines,li,edges,flags,fi,M):
 ei={v:j for j,v in enumerate(edges)}
 gs=[transvection_perm(pts[i],pts,ix) for i in (0,1,4,5,13)]
 gs.append(outer_similitude_perm(pts,ix))
 counts=[]
 for g in gs:
  lp=line_perm(g,lines,li)
  edgeperm=[]
  for a,b in edges:
   v=(g[a],g[b]);edgeperm.append((ei[tuple(sorted(v))],1 if v[0]<v[1] else -1))
  newflags=[fi[(g[p],lp[l])] for p,l in flags]
  for j,(dest,sign) in enumerate(edgeperm):
   lhs=np.zeros(160,dtype=np.int64)
   for f in np.flatnonzero(M[:,j]):lhs[newflags[f]]+=int(M[f,j])
   assert np.array_equal(lhs,M[:,dest]*sign)
  counts.append(len(edges))
 return counts

def main():
 pts,ix,lines,li,edges,tris,flags,fi,E,T,DL,M,Lift=chain()
 Z,chords=integer_cycle_basis(flags)
 assert np.array_equal(DL@Z,np.zeros((80,81),dtype=np.int64))
 Y=Lift@Z
 assert np.array_equal(M@Y,Z)
 assert np.array_equal(E@Y,np.zeros((40,81),dtype=np.int64))
 # Matrix M has rank 40*(4-1)=120 integrally with saturated image:
 # per-line zero-sum lattice, generated by flag differences.
 assert rank_mod(M,3)==120 and rank_mod(T,3)==120
 assert rank_mod(np.concatenate((T%3,Y%3),axis=1),3)==201
 assert rank_mod(Y,3)==81
 eq=equivariance(pts,ix,lines,li,edges,flags,fi,M)
 # Legacy modular reverse map: each chamber (p,L) -> sum_{q!=p}(p->q).
 Psi=np.zeros((240,160),dtype=np.int64)
 ei={e:j for j,e in enumerate(edges)}
 for j,(p,l) in enumerate(flags):
  for q in lines[l]:
   if q==p:continue
   a,b=sorted((p,q))
   Psi[ei[(a,b)],j]=1 if (p,q)==(a,b) else -1
 assert np.array_equal(Psi,M.T)
 assert np.array_equal(M@Psi@Z,4*Z)
 # The transpose takes Levi cycles to the EXACT clique Hodge harmonic kernel;
 # the factor 2 normalizes Euclidean metrics, not merely module characters.
 L1=E.T@E+T@T.T
 assert np.array_equal(L1@Psi@Z,np.zeros((240,81),dtype=np.int64))
 assert np.array_equal((Psi@Z).T@(Psi@Z),4*(Z.T@Z))
 assert np.array_equal(M@M.T@Z,4*Z)
 assert np.array_equal((M.T@Z).T@(M.T@Z),4*(Z.T@Z))
 # Restriction of standard edge dot product to cycle lattice has Gram
 # determinant equal to number of spanning trees (Kirchhoff theorem).
 Gram=Z.T@Z
 pranks={str(p):int(rank_mod(Gram,p)) for p in (2,3,5,7,11)}
 assert pranks['3']==81 and pranks['5']<81 and pranks['2']<81
 # NN^T=A_W33+4I, eigenvalues 16^1,6^24,0^15; hence
 # Laplacian 4I - [0 N;N^T 0] eigen: 0,8,(4 ± sqrt6)^24,4^30.
 # tau = product nonzero laplacian eig /80 = 10^23*4^30.
 tau=(10**23)*(4**30)
 assert tau%3 and tau%5==0 and tau%2==0
 out=dict(status='PASS',theorem='An explicit integral (not merely rational/F3) PSp(4,3)-equivariant chain map sends each oriented clique edge [p,q] on its unique isotropic line L to incidence path [(p,L)]-[(q,L)]. It sends triangle boundaries to zero, is onto the Levi cycle lattice after restricting to clique cycles, and has kernel exactly the 120-rank triangle-boundary lattice. Therefore H1(clique,Z) ≅ H1(Levi,Z) naturally as G-lattices. The previously reported F3 reverse map is multiplication by 4 after this canonical map on integer building cycles, hence equals identity mod 3.',
   proof='On every 4-point line, the 6 oriented point-pair edges map onto the saturated sum-zero lattice of its four flags (rank3), with kernel the triangle cycle lattice (rank3). This holds integrally, independently on 40 lines. The Levi boundary of each mapped edge is the same point boundary as the source edge. Every Levi 1-cycle lies in the linewise sum-zero flag sublattice; a local integral star lift produces a closed clique chain. The kernel on clique cycles is the sum of the 40 triangle boundary lattices.',
   sizes=dict(pts=40,lines=40,clique_edges=240,clique_triangles=160,clique_tetra=40,
              clique_h1_rank=81,levi_vertices=80,levi_edges=160,levi_h1_rank=81),
   exact_identities=dict(boundary_commutes=True,triangles_annihilated=True,integral_right_inverse_on_cycles=True,
     reverse_modular_map_composite='M * Psi * Z = 4 Z over Z', Psi_equals_M_transpose=True,
     clique_Hodge_L1_annihilates_M_transpose_Z=True,
     clique_harmonic_Gram_equals_four_times_Levi_Gram=True,
     canonical_real_isometry='U=(1/2) M^T restrict ker(D_Levi) -> ker(L1_clique), U^T U=I',
     generator_equivariance_checks=eq),
   rank_mod3=dict(path_image=120,triangle_boundary=120,clique_kernel=201,logical_basis=81),
   cycles=dict(fundamental_chords=chords,Gram_mod_prime_ranks=pranks,
      critical_group_order=str(tau),critical_group_order_factorization={'2':83,'5':23},
      mod3_nondegenerate_pairing=True,
      canonical_odd_dim_phase_space_nogo='An alternating nondegenerate bilinear form on the odd 81-dimensional V=H1(F3) is impossible. The canonically doubled logical Pauli phase space V + V* has dimension 162 and standard symplectic pairing; Heisenberg center adds one order-three coordinate (group order 3^163). Its irreducible Schrödinger Hilbert representation has dimension 3^81, not 81. None of these numerical constructions fixes a physical Hamiltonian.',
      physical_reading='The finite 81-loop lattice admits an invariant nondegenerate F3 edge dot-product, canonically identifying 81 flux characters with 81 mod3 cycles. The 3-torsion of the U1 flat-connection torus is dual to H1(F3), hence matches its qutrit logical character group through this perfect pairing; neither gauge action nor photon coupling follows.'),
   certificate_sha256={'M_int8':hashlib.sha256(M.astype(np.int8).tobytes()).hexdigest(),
                       'Z_int8':hashlib.sha256(Z.astype(np.int8).tobytes()).hexdigest()},
   scope='This is an object-level topological and modular bridge. It does not derive a local 3+1D field theory, fix coupling constants, give 81 physical qubits, or imply independent photonic modes; gauge-link Hamiltonians require separate action and continuum scaling.')
 target=ROOT/'data/w33_20261009_toe_integral_clique_levi_bridge.json'
 target.write_text(json.dumps(out,indent=2)+'\n')
 print('INTEGRAL BRIDGE 81; modular Gram ranks',pranks,'tau',tau,'Z-chords',len(chords),flush=True)
if __name__=='__main__':main()
