#!/usr/bin/env python3
"""
Turning the buildable demonstrator into a falsification test of the substrate.

The single self-entangled photon (build sheet: PBS, tritter, delay ladder, EOM,
single-photon detectors, BC recirculation loop) is buildable NOW and needs no
GKP/squeezing. The architecture-closure physics (holonomic gates = gauge-
connection holonomy 2T=SL(2,3); the irrational Boerdijk-Coxeter drive) makes
PARAMETER-FREE, near-term predictions that DISCRIMINATE the substrate hypothesis
from generic quantum optics. Three signatures, all measurable on the demonstrator:

  (S1) GEOMETRIC-GATE TIMING-INDEPENDENCE (the discriminator). If the gates are
       Wilczek-Zee holonomies of the connection (substrate claim), the gate
       unitary depends ONLY on the loop traced in control space, not on the rate
       at which it is traced. Reparametrize the loop (slow/fast, any schedule
       with the same path): the measured gate -- via the trace-Choi visibility
       V(U)=|Tr U|/3 already in the paper -- is INVARIANT. A dynamical (non-
       geometric) gate changes with timing. This is the classic geometric-phase
       test; here the predicted holonomy is a specific 2T=SL(2,3) element.

  (S2) HOLONOMY-GROUP FINGERPRINT. Composing the geometric gates must close into
       2T = SL(2,3) (order 24), element-order spectrum {1:1,2:1,3:8,4:6,6:8}.
       Gate-set tomography of compositions reads this out; any deviation
       falsifies the gauge-connection-holonomy claim.

  (S3) APERIODIC CLOCK. The BC drive rotates by theta = arccos(-2/3) per pass.
       By Niven's theorem the only rational cos(r*pi) with r rational are
       {0,+-1/2,+-1}; cos theta = -2/3 is none, so theta/pi is IRRATIONAL and the
       drive NEVER recurs -- a provably aperiodic (time-quasicrystal) clock.
       Measurable: no return to the initial register phase at any finite pass n.

This script computes the measurable predictions.
"""
from __future__ import annotations

import json
import math
import numpy as np


F = 3


def matmul(A, B):
    return tuple(tuple(sum(A[i][k] * B[k][j] for k in range(2)) % F
                       for j in range(2)) for i in range(2))


def main():
    out = {}

    # ---- (S1)+(S2): the holonomy group 2T = SL(2,3) and its visibilities ----
    # single-qutrit Clifford via the metaplectic (Weil) rep, generated by the
    # qutrit Fourier F (the tritter) and phase S; trace-Choi V = |Tr U|/3.
    w = np.exp(2j * np.pi / 3)
    Fg = np.array([[1, 1, 1], [1, w, w**2], [1, w**2, w]]) / np.sqrt(3)  # tritter
    S = np.diag([1, 1, w])                                              # phase
    Z = np.diag([1, w, w**2])
    X = np.array([[0, 0, 1], [1, 0, 0], [0, 1, 0]])
    gens = {"F": Fg, "S": S, "Z": Z, "X": X}

    # close the group (mod global phase) and collect trace-Choi visibilities
    def key(U):
        # canonicalize global phase: divide by first nonzero entry's phase
        U = np.asarray(U)
        for x in U.flatten():
            if abs(x) > 1e-9:
                U = U * (abs(x) / x)
                break
        return tuple(np.round(U.flatten(), 6))
    group = {}
    frontier = [np.eye(3, dtype=complex)]
    group[key(np.eye(3))] = np.eye(3, dtype=complex)
    while frontier:
        U = frontier.pop()
        for g in gens.values():
            for V in (g @ U, np.conj(g).T @ U):
                k = key(V)
                if k not in group:
                    group[k] = V
                    frontier.append(V)
        if len(group) > 20000:
            break
    vis = sorted({round(abs(np.trace(U)) / 3, 4) for U in group.values()})
    print(f"[S1/S2] single-qutrit Clifford group size (mod phase) = {len(group)}")
    print(f"        trace-Choi visibility spectrum V=|Tr U|/3 : {vis}")
    print(f"        (V(F_3)=1/3={round(1/3,4)} and V(X)=V(Z)=0 are in the set: "
          f"{round(1/3,4) in vis and 0.0 in vis})")
    out["clifford_group_mod_phase"] = len(group)
    out["visibility_spectrum"] = vis

    # 2T = SL(2,3) order/spectrum (the mod-Pauli holonomy group)
    sl23 = [((a, b), (c, d)) for a in range(F) for b in range(F)
            for c in range(F) for d in range(F)
            if (a * d - b * c) % F == 1]
    I2 = ((1, 0), (0, 1))
    def ord2(g):
        p, k = g, 1
        while p != I2:
            p, k = matmul(p, g), k + 1
        return k
    from collections import Counter
    spec = dict(sorted(Counter(ord2(g) for g in sl23).items()))
    print(f"[S2] holonomy group 2T=SL(2,3): order {len(sl23)}, spectrum {spec}")
    out["holonomy_2T_order"] = len(sl23)
    out["holonomy_order_spectrum"] = spec
    assert len(sl23) == 24 and spec == {1: 1, 2: 1, 3: 8, 4: 6, 6: 8}

    # ---- (S3): BC drive aperiodicity (Niven) ----
    cos_theta = -2 / 3
    theta = math.acos(cos_theta)
    niven_rationals = {0.0, 0.5, -0.5, 1.0, -1.0}
    is_aperiodic = cos_theta not in niven_rationals     # cos = -2/3 not Niven
    print(f"\n[S3] BC drive: theta = arccos(-2/3) = {math.degrees(theta):.3f} deg")
    print(f"     cos theta = -2/3 not in Niven set {sorted(niven_rationals)} "
          f"=> theta/pi irrational => clock APERIODIC (quasicrystal): {is_aperiodic}")
    # demonstrate non-recurrence: min |n*theta mod 2pi| stays bounded away from 0
    mults = [(n, abs(((n * theta) % (2 * math.pi)))) for n in range(1, 40)]
    closest = min(min(m, 2 * math.pi - m) for _, m in mults)
    print(f"     closest return to 0 in first 39 passes: {closest:.4f} rad "
          f"(> 0 -> no recurrence)")
    out["bc_angle_deg"] = round(math.degrees(theta), 3)
    out["clock_aperiodic_niven"] = bool(is_aperiodic)
    assert is_aperiodic and closest > 1e-3

    print("\nRESULT: a parameter-free, near-term falsification test on the single-")
    print("  photon demonstrator (NO GKP/squeezing needed):")
    print("  (S1) gates timing-independent (geometric) with holonomy in 2T=SL(2,3)")
    print("       -- reparametrize the loop, V=|Tr U|/3 must be invariant;")
    print("  (S2) composed gates close into 2T=SL(2,3) (order 24, spectrum")
    print("       {1,1,8,6,8}) -- gate tomography fingerprint;")
    print("  (S3) the BC clock is provably aperiodic (arccos(-2/3), Niven) --")
    print("       no recurrence at any finite pass.")
    print("  Any deviation falsifies the holonomic/substrate hypothesis; the")
    print("  buildable machine becomes an experiment ON the substrate itself.")

    out["test"] = ("S1 geometric-gate timing-independence (discriminator); "
                   "S2 2T=SL(2,3) holonomy fingerprint; S3 BC aperiodic clock")
    out["near_term"] = "single-photon demonstrator only; no GKP/squeezing"
    with open("data/w33_near_term_falsification_test.json", "w") as f:
        json.dump(out, f, indent=2, default=str)
    print("\nwrote data/w33_near_term_falsification_test.json")


if __name__ == "__main__":
    main()
