#!/usr/bin/env python3
"""Pass 196: the S4 kernel is the flat shell; the elation core is Heisenberg.

Pass 192 proved the line stabilizer H (order 648) maps onto S4 with an
abelian exponent-3 kernel K of order 27.  The dual-torsor compiler has
exactly two order-27 shells: the flat F3^3 program shell of the Bell-line
parabolic 3^3:S4 and the noncommutative Heisenberg 3^{1+2} state shell of
the point parabolic.  This witness identifies both cores exactly:

1. LINE SIDE.  K = O_3(H) is computed directly (the join of all normal
   3-subgroups): order 27, elementary abelian -- the FLAT shell.  Since
   O_3 is unique, Pass 192's codec kernel IS the compiler's program
   shell.

2. POINT SIDE.  The elation group at a point (all elements fixing every
   line through the point) has order 27, is NONabelian with center of
   order 3 and exponent 3 -- the extraspecial Heisenberg shell 3^{1+2}.

The two parabolics of the same order 648 thus carry the two inequivalent
order-27 groups as their cores: the compiler's program/state duality is
the parabolic core dichotomy.
"""

from __future__ import annotations

import json
from pathlib import Path
import sys

import numpy as np

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from analysis.w33_pass158_chiral_trade_lattice_two_480s import (
    build_group,
    build_w33,
    w33_lines,
)

OUT = ROOT / "data" / "w33_pass196_kernel_flat_shell.json"


def perm_order(perm):
    order = 1
    current = list(perm)
    identity = list(range(40))
    while current != identity:
        current = [perm[x] for x in current]
        order += 1
    return order


def compose(a, b):
    return tuple(a[b[i]] for i in range(40))


def main():
    points, adjacency, symplectic = build_w33()
    lines = w33_lines(adjacency)
    checks = {}

    generators, group = build_group(points, symplectic)
    checks["group_order"] = len(group) == 25920

    # ------------------------------------------------------------------
    # 1. line side: O_3 of the line stabilizer
    # ------------------------------------------------------------------
    line0 = lines[0]
    H = [g for g in group if frozenset(g[x] for x in line0) == line0]
    checks["line_stabilizer_648"] = len(H) == 648
    H_set = set(H)

    # 3-elements of H whose full H-conjugacy class stays 3-elementary and
    # generates a normal 3-subgroup: compute O_3 as the largest normal
    # 3-subgroup = the set of elements x such that <x^H> is a 3-group.
    # Practical route: collect all order-3 elements whose H-classes
    # multiply into a 3-group; start from the candidates and close.
    three_elements = [g for g in H if perm_order(g) in (3, 9, 27)]
    # candidate core: elements of 3-power order whose conjugates all have
    # 3-power order and which normalize: build the subgroup generated by
    # all NORMAL 3-elements via iterative closure and normality testing.
    identity = tuple(range(40))

    def subgroup_closure(gens):
        seen = {identity}
        frontier = [identity]
        while frontier:
            new = []
            for element in frontier:
                for g in gens:
                    composed = compose(g, element)
                    if composed not in seen:
                        seen.add(composed)
                        new.append(composed)
            frontier = new
        return seen

    def inverse(perm):
        out = [0] * 40
        for i, v in enumerate(perm):
            out[v] = i
        return tuple(out)

    # O_3(H): intersect the Sylow 3-subgroups; equivalently, the set of
    # 3-elements x with <x>^H a 3-group.  With |H| = 648 = 2^3 * 3^4 we
    # can find one Sylow-3 (order 81) by closing 3-elements greedily and
    # then intersect its H-conjugates.
    sylow = None
    for x in three_elements:
        candidate = subgroup_closure([x])
        for y in three_elements:
            trial = subgroup_closure(list(candidate) + [y])
            if len(trial) in (3, 9, 27, 81):
                candidate = trial
            if len(candidate) == 81:
                break
        if len(candidate) == 81:
            sylow = candidate
            break
    checks["sylow3_81_found"] = sylow is not None

    core = set(sylow)
    for h in H:
        h_inv = inverse(h)
        conjugate = {compose(compose(h, s), h_inv) for s in sylow}
        core &= conjugate
        if len(core) <= 27:
            # keep intersecting to confirm stability
            pass
    checks["core_order_27"] = len(core) == 27
    core_list = sorted(core)
    abelian = all(
        compose(a, b) == compose(b, a)
        for i, a in enumerate(core_list)
        for b in core_list[i + 1 :]
    )
    exponent3 = all(perm_order(g) in (1, 3) for g in core_list)
    checks["core_elementary_abelian"] = abelian and exponent3

    # Pass 192's kernel: H -> Sym(pair partitions of the line) has kernel
    # containing exactly the elements acting trivially on the 3 partitions
    line_sorted = sorted(line0)
    partitions = [
        frozenset([frozenset(line_sorted[:2]), frozenset(line_sorted[2:])]),
        frozenset(
            [
                frozenset([line_sorted[0], line_sorted[2]]),
                frozenset([line_sorted[1], line_sorted[3]]),
            ]
        ),
        frozenset(
            [
                frozenset([line_sorted[0], line_sorted[3]]),
                frozenset([line_sorted[1], line_sorted[2]]),
            ]
        ),
    ]

    def acts_trivially_on_line(g):
        return all(g[x] == x for x in line0)

    kernel_192 = [g for g in H if acts_trivially_on_line(g)]
    # the S4 image acts faithfully on the 4 line points; its kernel is
    # exactly the pointwise line stabilizer
    checks["pointwise_kernel_27"] = len(kernel_192) == 27
    checks["kernel_equals_O3"] = set(kernel_192) == core

    # ------------------------------------------------------------------
    # 2. point side: the elation group = O_3(point stabilizer)
    # ------------------------------------------------------------------
    p0 = 0
    pencil = [line for line in lines if p0 in line]
    checks["four_pencil_lines"] = len(pencil) == 4
    stab_p = [g for g in group if g[p0] == p0]
    checks["point_stabilizer_648"] = len(stab_p) == 648
    opposite = [x for x in range(40) if x != p0 and not adjacency[p0, x]]
    checks["27_opposite_points"] = len(opposite) == 27

    def o3_core(subgroup):
        """The largest normal 3-subgroup: intersection of Sylow 3-subgroups."""
        threes = [g for g in subgroup if perm_order(g) in (3, 9, 27, 81)]
        syl = None
        for x in threes:
            candidate = subgroup_closure([x])
            for y in threes:
                trial = subgroup_closure(list(candidate) + [y])
                if len(trial) in (3, 9, 27, 81):
                    candidate = trial
                if len(candidate) == 81:
                    break
            if len(candidate) == 81:
                syl = candidate
                break
        c = set(syl)
        for h in subgroup:
            h_inv = inverse(h)
            c &= {compose(compose(h, s), h_inv) for s in syl}
        return c

    elations = o3_core(stab_p)
    # elations about p: the extraspecial core, regular on the 27 opposite
    checks["elation_group_27"] = len(elations) == 27
    checks["elation_regular_on_opposite"] = (
        len({tuple(g[x] for x in opposite) for g in elations}) == 27
    )
    el_sorted = sorted(elations)
    el_abelian = all(
        compose(a, b) == compose(b, a)
        for i, a in enumerate(el_sorted)
        for b in el_sorted[i + 1 :]
    )
    center = [
        z for z in el_sorted if all(compose(z, g) == compose(g, z) for g in el_sorted)
    ]
    el_exponent3 = all(perm_order(g) in (1, 3) for g in el_sorted)
    checks["elation_nonabelian"] = not el_abelian
    checks["elation_center_3"] = len(center) == 3
    checks["elation_exponent_3"] = el_exponent3

    all_pass = all(checks.values())
    payload = {
        "schema": "w33.pass196.kernel_flat_shell.v1",
        "status": "PASS" if all_pass else "FAIL",
        "line_side": {
            "core": "O_3(line stabilizer) = pointwise line stabilizer",
            "order": 27,
            "structure": "elementary abelian C3^3 -- the FLAT program shell",
            "identification": (
                "Pass 192's S4-codec kernel equals O_3 of the Bell-line "
                "parabolic 3^3:S4: the signed-trade register's hidden "
                "27 is the compiler's flat F3^3 program shell"
            ),
        },
        "point_side": {
            "core": "elation group at a point",
            "order": 27,
            "structure": (
                "extraspecial 3^{1+2} (nonabelian, center C3, exponent 3) "
                "-- the Heisenberg state shell"
            ),
        },
        "reading": (
            "the dual-torsor compiler's program/state shell dichotomy is "
            "the parabolic core dichotomy: same order 648, same core "
            "order 27, abelian vs extraspecial"
        ),
        "checks": {name: bool(value) for name, value in checks.items()},
    }

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")
    print(json.dumps(payload, indent=2))
    return 0 if all_pass else 1


if __name__ == "__main__":
    raise SystemExit(main())
