"""Part MCLXXXVI: Tomotope edge-cell-flag tensor lock.

Continuation of MCLXXXII-MCLXXXV.

From verified tomotope packet:
  edges E = 12,
  cells C = 8,
  automorphism A = 96,
  flags F = 192,
  monodromy M = 18432.

New lock:
  A = E*C,
  M = E*C*F = A*F.

So automorphism is an edge-cell generator and monodromy is the full
edge-cell-flag tensor volume.
"""

from __future__ import annotations

import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]


def _load(path: Path) -> dict[str, object]:
    with open(path, "r", encoding="utf-8") as handle:
        return json.load(handle)


def tomotope_edge_cell_flag_tensor_lock_packet() -> dict[str, object]:
    mclxxxii = _load(ROOT / "PART_MCLXXXII_Q4_TOMOTOPE_REYE_DOUBLE_COVER_results.json")
    mclxxxv = _load(ROOT / "PART_MCLXXXV_Q4_TOMOTOPE_TRIPRODUCT_MONODROMY_LOCK_results.json")

    edges = int(mclxxxii["tomotope_lock"]["edges"])                   # 12
    cells = int(mclxxxii["tomotope_lock"]["cells"])                   # 8
    automorphism = int(mclxxxii["tomotope_lock"]["automorphism_group_order"])  # 96
    flags = int(mclxxxii["tomotope_lock"]["flags"])                   # 192
    monodromy = int(mclxxxv["lock"]["monodromy"])                     # 18432

    tensor_volume = edges * cells * flags

    checks = {
        "automorphism_equals_edges_times_cells": automorphism == edges * cells,
        "flags_are_double_automorphism": flags == 2 * automorphism,
        "monodromy_equals_edge_cell_flag_tensor": monodromy == tensor_volume,
        "monodromy_equals_automorphism_times_flags": monodromy == automorphism * flags,
        "tensor_and_bilinear_forms_match": tensor_volume == automorphism * flags,
        "monodromy_over_flags_is_automorphism": monodromy // flags == automorphism,
        "monodromy_over_automorphism_is_flags": monodromy // automorphism == flags,
        "monodromy_over_cells_is_edges_times_flags": monodromy // cells == edges * flags,
        "monodromy_over_edges_is_cells_times_flags": monodromy // edges == cells * flags,
        "numeric_identity": (edges, cells, automorphism, flags, monodromy) == (12, 8, 96, 192, 18432),
    }

    return {
        "part": "MCLXXXVI",
        "theorem": "Tomotope edge-cell-flag tensor lock",
        "tomotope_packet": {
            "edges": edges,
            "cells": cells,
            "automorphism": automorphism,
            "flags": flags,
            "monodromy": monodromy,
        },
        "locks": {
            "edge_cell_generator": edges * cells,
            "edge_cell_flag_tensor": tensor_volume,
            "automorphism_times_flags": automorphism * flags,
            "identity": "18432 = 12*8*192 = 96*192 with 96=12*8",
        },
        "finite_universality_surrogate": {
            "statement": "tomotope automorphism and monodromy are generated by edge-cell and edge-cell-flag tensor packets",
            "boundary": "finite combinatorial/symmetry lock; not a continuum field equation",
        },
        "claim_boundary": "finite edge-cell-flag factorization law on tomotope packets",
        "checks": checks,
        "n_verified": sum(1 for value in checks.values() if value),
    }


def main() -> None:
    packet = tomotope_edge_cell_flag_tensor_lock_packet()
    out_path = ROOT / "PART_MCLXXXVI_TOMOTOPE_EDGE_CELL_FLAG_TENSOR_LOCK_results.json"
    with open(out_path, "w", encoding="utf-8") as handle:
        json.dump(packet, handle, indent=2)

    print("=== Part MCLXXXVI: Tomotope Edge-Cell-Flag Tensor Lock ===")
    print(packet["locks"]["identity"])
    print(f"verified: {packet['n_verified']} / {len(packet['checks'])}")


if __name__ == "__main__":
    main()
