#!/usr/bin/env python3
"""Pass 1507: rational Morita context and exact lower bound for the joint algebra."""
from __future__ import annotations
import argparse, hashlib, importlib.util, json, time
from functools import reduce
from math import gcd
from pathlib import Path
import numpy as np
ROOT=Path(__file__).resolve().parents[1]
BASE=ROOT/'analysis'/'w33_pass1416_cokernel_signed_turn_intertwiner.py'
OUT=ROOT/'data'/'w33_pass1507_joint_algebra_morita.json'
PRIME=1009;TARGET=301

def load_base():
 s=importlib.util.spec_from_file_location('p1416',BASE);m=importlib.util.module_from_spec(s);s.loader.exec_module(m);return m
def content(A):return reduce(gcd,(abs(int(x)) for x in A.ravel() if x),0)

def certificate(target=TARGET):
 b=load_base();points,edges,lines,frames,G,M,A,N,d,K=b.build_geometry();I40=np.eye(40,dtype=np.int64);I240=np.eye(240,dtype=np.int64)
 P=(A-12*I40)@(A-2*I40);C=(N.T@P@N)//16;F=(d.T@P@N)//16;Q0=(K+6*I240)@(K-2*I240)@(K-4*I240);Q=Q0//content(Q0)
 S=M.T@M;U=N.T@N;D=d.T@d
 names=['S','K','U','D','C','F','Ft','Q'];gens=[X%PRIME for X in (S,K,U,D,C,F,F.T,Q)]
 pivots=[];basis=[];queue=[];words=[]
 def add(X,word):
  v=(X%PRIME).reshape(-1).astype(np.int64)
  for p,row in zip(pivots,basis):
   a=int(v[p])
   if a:v=(v-a*row)%PRIME
  nz=np.flatnonzero(v)
  if not len(nz):return False
  p=int(nz[0]);v=(v*pow(int(v[p]),-1,PRIME))%PRIME
  j=int(np.searchsorted(pivots,p));pivots.insert(j,p);basis.insert(j,v);queue.append((X%PRIME,word));words.append(word);return True
 add(np.eye(240,dtype=np.int64),'I');processed=0;t0=time.time()
 while queue and len(pivots)<target:
  X,w=queue.pop(0);processed+=1
  for name,Gm in zip(names,gens):
   if add((X@Gm)%PRIME,w+'*'+name) and len(pivots)>=target:break
 elapsed=time.time()-t0
 commutators={
  '[K,S]':b.rank_mod(K@S-S@K,PRIME),'[S,U]':b.rank_mod(S@U-U@S,PRIME),
  '[K,U]':b.rank_mod(K@U-U@K,PRIME),'[D,S]':b.rank_mod(D@S-S@D,PRIME),
  '[F,Ft]':b.rank_mod(F@F.T-F.T@F,PRIME),
 }
 witness_hash=hashlib.sha256(json.dumps({'prime':PRIME,'pivots':pivots,'words':words},sort_keys=True,separators=(',',':')).encode()).hexdigest()
 checks={
  'all_required_generators_present':names[:6]==['S','K','U','D','C','F'],
  'target_301_reached':len(pivots)==target==301,
  '301_words_recorded':len(words)==301,
  'pivots_distinct_sorted':len(set(pivots))==len(pivots) and pivots==sorted(pivots),
  'modular_independence_implies_rational_lower_bound':len(pivots)==301,
  'joint_algebra_noncommutative':all(v>0 for v in commutators.values()),
  'morita_xy_q':np.max(np.abs(F@F.T-48*Q))==0,
  'morita_yx_e':np.max(np.abs(F.T@F-96*C))==0,
  'corner_support_QF':np.max(np.abs(Q@F-96*F))==0,
  'corner_support_FC':np.max(np.abs(F@C-48*F))==0,
 }
 checks={k:bool(v) for k,v in checks.items()}
 return {
  'schema':'w33.pass1507.joint_algebra_morita.v1','status':'PASS' if all(checks.values()) else 'FAIL',
  'theorem':('Inside the joint frame-turn algebra, e=C/48 and q=Q/96 are equivalent rational idempotents. With x=F/48 and y=F^T/96, xy=q and yx=e, so the unsigned and signed 15-dimensional corners are explicitly Morita equivalent over Q and over every localization away from 2 and 3. The algebra generated by M^TM, K, N^TN, d^Td, C, F, F^T, and Q has dimension at least 301 over Q, certified by 301 words independent modulo 1009.'),
  'generators':names,'prime':PRIME,'dimension_lower_bound':len(pivots),'processed_basis_words':processed,'queued_at_stop':len(queue),
  'witness_words':words,'pivot_columns':pivots,'witness_sha256':witness_hash,'last_word':words[-1],
  'commutator_ranks_mod_1009':commutators,
  'morita_context':{'e':'C/48','q':'Q/96','x':'F/48','y':'F^T/96','identities':['e^2=e','q^2=q','xy=q','yx=e','qx=x=xe','ey=y=yq']},
  'checks':checks,'boundary':'The 301-dimensional result is a certified lower bound, not the complete Wedderburn decomposition. The rational corner equivalence is exact; integral degeneration at 2 and 3 is handled in Pass 1506.'
 }

def main():
 ap=argparse.ArgumentParser();ap.add_argument('--output',type=Path,default=OUT);ap.add_argument('--check',action='store_true');a=ap.parse_args();p=certificate();s=json.dumps(p,sort_keys=True,separators=(',',':'))+'\n'
 if a.check:
  if not a.output.exists() or a.output.read_text()!=s:raise SystemExit('Pass 1507 certificate drift')
 else:a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(s)
 print(json.dumps({'status':p['status'],'checks':sum(p['checks'].values()),'dimension_lower_bound':p['dimension_lower_bound'],'last_word':p['last_word']}));return 0 if p['status']=='PASS' else 1
if __name__=='__main__':raise SystemExit(main())
