#!/usr/bin/env python3
"""Exact packet18 / E8 holonomy Fourier tomography.

The physical E8 holonomy is K=C3_rho x C3_a x C2_b.  The repository freezes
the 18 joint E8 eigenspace dimensions d(rho,a,b), summing to 248, and an
independent packet18 theorem realizes the same abstract K as a regular
permutation action on the 18 packet addresses (left F3^2 translations times
the right deck C2).

This file proves the exact character-theory bridge:

    chi_hat(u,v,e)
      = sum_{rho,a,b} d(rho,a,b)
          omega^(-u rho-v a) (-1)^(e b)

is INTEGER-VALUED at all 18 characters and equals the already-frozen physical
E8 holonomy trace fingerprint point-for-point.

Conversely the inverse transform reconstructs every sector dimension:

    18 d(rho,a,b)
      = sum_{u,v,e} chi_hat(u,v,e)
          omega^(u rho+v a) (-1)^(e b).

Thus packet18 provides an exact *address-space Fourier basis* for the physical
holonomy character table.  No identification of packet states with E8 root
states is needed: this is a compiler/tomography statement on the common finite
group K.

The physical C6 generator g=(0,1,1) is recovered as the six-point restriction
    Tr(g^k) = (248,-2,14,-8,14,-2), k=0..5,
exactly matching the physical Chevalley-lift certificate.

Evidence boundary:
  packet18 supplies the finite regular K action and therefore its character
  Fourier modes.  A laboratory measurement still needs a physical observable
  whose packet-address statistics equal the E8 sector weights; this theorem
  does not manufacture such a transducer.
"""
from __future__ import annotations
import json
from pathlib import Path

ROOT=Path(__file__).resolve().parents[1]
OUT=ROOT/'data/w33_packet18_e8_holonomy_fourier_tomography.json'

# Exact Z[omega] pair a+b*omega with omega^2=-1-omega.
def add(x,y): return (x[0]+y[0],x[1]+y[1])
def neg(x): return (-x[0],-x[1])
def mul(x,y):
    a,b=x;c,d=y
    return (a*c-b*d, a*d+b*c-b*d)
ONE=(1,0); OMEGA=(0,1)
def wpow(n):
    n%=3
    return ONE if n==0 else OMEGA if n==1 else (-1,-1)
def scale(n,x): return (n*x[0],n*x[1])

def char(k,x,minus=False):
    u,v,e=k; r,a,b=x
    z=wpow((u*r+v*a) * (-1 if minus else 1))
    return scale(-1,z) if (e*b)%2 else z

def main(write=True):
    parent=json.loads((ROOT/'data/w33_e8_holonomy_packet18_homogeneous_bridge.json').read_text())
    action=json.loads((ROOT/'data/w33_packet18_external_regular_holonomy_action.json').read_text())
    factor=json.loads((ROOT/'data/w33_e8_holonomy_c3xc6_factorization.json').read_text())
    assert parent['status']=='PASS_TORSOR_BRIDGE__GROUP_IDENTIFICATION_KILLED'
    assert action['status']=='PASS_EXTERNAL_REGULAR_HOLONOMY_ACTION'
    assert action['holonomy_action']['regular_on_packet18'] is True
    assert factor['status']=='PASS_EXACT_C3_SELECTOR_X_PHYSICAL_C6_FACTORIZATION'

    dims={tuple(map(int,k.split(','))):int(v)
          for k,v in parent['E8_joint_sector_dimensions'].items()}
    traces={tuple(map(int,k.split(','))):int(v)
            for k,v in parent['E8_holonomy_trace_fingerprint'].items()}
    K=[(r,a,b) for r in range(3) for a in range(3) for b in range(2)]
    assert set(dims)==set(traces)==set(K)
    assert sum(dims.values())==248

    hats={}
    for k in K:
        s=(0,0)
        for x in K:
            s=add(s,scale(dims[x],char(k,x,minus=True)))
        hats[k]=s
        assert s[1]==0
        assert s[0]==traces[k]

    # Exact inverse transform.
    recovered={}
    for x in K:
        s=(0,0)
        for k in K:
            s=add(s,scale(hats[k][0],char(k,x,minus=False)))
        assert s[1]==0 and s[0] % 18 == 0
        recovered[x]=s[0]//18
        assert recovered[x]==dims[x]

    # Parseval over the finite abelian group.
    lhs=sum(t*t for t in traces.values())
    rhs=18*sum(d*d for d in dims.values())
    assert lhs==rhs==62136

    # Restrict to the physical C6 subgroup generated by (0,1,1).
    c6=[]
    for k in range(6):
        g=(0,k%3,k%2)
        c6.append(traces[g])
    assert c6==[248,-2,14,-8,14,-2]
    assert c6==factor['full_E8']['power_traces']

    table=[{
      'character':[u,v,e],
      'sector_dimension':dims[(u,v,e)],
      'fourier_trace':traces[(u,v,e)]}
      for u,v,e in K]

    out={
      'schema':'w33.packet18_e8_holonomy_fourier_tomography.v1',
      'status':'PASS_EXACT_PACKET18_HOLONOMY_FOURIER_DUALITY',
      'headline':'The 18 physical E8 holonomy-sector dimensions and the 18 holonomy traces are exact discrete-Fourier duals on K=C3^2 x C2. Packet18 carries an exact regular K action through left F3^2 translations and the right deck C2, so after choosing an origin/sheet convention its address Fourier modes provide a finite character-tomography compiler for the E8 holonomy fingerprint. The physical C6 restriction is (248,-2,14,-8,14,-2).',
      'group':'K=C3_rho x C3_a x C2_b',
      'order':18,
      'forward_transform':'trace(u,v,e)=sum d(r,a,b) omega^(-ur-va)(-1)^(eb)',
      'inverse_transform':'18 d(r,a,b)=sum trace(u,v,e) omega^(ur+va)(-1)^(eb)',
      'all_fourier_values_integral':True,
      'sector_sum':248,
      'parseval':{
        'sum_trace_squared':lhs,
        '18_times_sum_dimension_squared':rhs,
        'equal':True},
      'physical_C6':{
        'generator':'(rho,a,b)=(0,1,1)',
        'power_traces_k0_to5':c6,
        'packet_action':'three 6-cycles on packet18'},
      'packet_compiler':{
        'parent':'data/w33_packet18_external_regular_holonomy_action.json',
        'regular_K_action':True,
        'interpretation':'the regular packet-address representation contains every K character exactly once, so the same 18-point Fourier matrix diagonalizes the packet K action and transforms E8 sector weights into E8 holonomy traces',
        'origin_sheet_dependence':'coordinate labels require an origin and sheet convention; character multiset and transform theorem do not'},
      'table':table,
      'boundary':'Exact finite character theory and control/address compilation. No physical E8-to-packet state transducer or laboratory sector-weight measurement is claimed.',
      'parents':[
        'data/w33_e8_holonomy_packet18_homogeneous_bridge.json',
        'data/w33_packet18_external_regular_holonomy_action.json',
        'data/w33_e8_holonomy_c3xc6_factorization.json'],
      'checks':{
        '18_sector_dimensions':True,
        '18_trace_values':True,
        'forward_DFT_exact':True,
        'inverse_DFT_exact':True,
        'all_DFT_values_are_integers':True,
        'parseval_62136':True,
        'physical_C6_trace_recovered':True,
        'packet18_regular_K_action_loaded':True}}
    if write:OUT.write_text(json.dumps(out,indent=2)+'\n')
    print(json.dumps(out,indent=2));return out

if __name__=='__main__':main(True)
