#!/usr/bin/env python3
"""Passes 5595--5602: close five projectivity-frame targets and run three TOE probes.

This packet is deliberately split between exact structural theorems, finite replay,
and explicit physical firewalls.  It does not promote numerical coincidences.

5595  Full incidence automorphism mechanism: columns recover the square rook graph,
      so Aut(D_q)=({(a,b) in N^2: b a^-1 in PSL2(q)}) : C2 with
      N=N_Sym(P1)(PSL2)=PGammaL2(q), hence order 4 f |PSL2(q)|^2.
      The natural group is enumerated at q=3,5.
5596  The q=3 Reye 12-row action is permutation-isomorphic to the Klein-V4 Latin
      12-symbol autoparatopy action.  An explicit conjugating bijection is given.
5597  Genuine extension-field replay at q=9 and q=25, including Segre equality,
      projectivity-graph incidence, and binary ranks 50 and 338.
5598  The projectivity-frame code is not the footprint image.  It is the projection
      to the singular Segre sheet of a subspace of C_W=ker(F^T), generated by full
      symplectic neighbourhoods of one nonsingular quadratic class.
5599  Fixed-point fusion on PSL2(q): 0/1/2-fixed-point relations form a symmetric
      association scheme in every fully checked anchor.  Uniform polynomial
      intersection numbers are verified through prime and extension-field anchors;
      all-q closure is kept as a candidate unless supplied by a separate proof.
5600  TOE probe (kinematics): Q+(3,q)=P1 x P1 is an exact two-ruling/null-coordinate
      sheet and projectivity rows are transversals.  This is a finite kinematic
      analogy only, not a 3+1 spacetime derivation.
5601  TOE probe (information): the PSL and nonsquare PGL-coset permutation-matrix
      spans are exact binary duals.  The projectivity code is isodual of parameters
      [(q+1)^2,(q+1)^2/2] for every odd prime power q.
5602  TOE probe (spectral-action firewall): the centered frame operator has a single
      nonzero eigenvalue.  It is a projector/tight-frame operator, not a local
      Laplacian with a Weyl-law spectral tower.
"""
from __future__ import annotations

import itertools
import json
from collections import Counter, defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "data" / "PART_W33_PASS5595_5602_PROJECTIVITY_CLOSURE_TOE_PROBES.json"

# ---------------------------------------------------------------------------
# Basic permutation helpers
# ---------------------------------------------------------------------------

def compose(a, b):
    return tuple(a[b[i]] for i in range(len(a)))


def inverse_perm(a):
    out = [0] * len(a)
    for i, j in enumerate(a):
        out[j] = i
    return tuple(out)


def parity(p):
    s = 0
    for i in range(len(p)):
        for j in range(i + 1, len(p)):
            s ^= int(p[i] > p[j])
    return s


def fixed_points(p):
    return sum(i == p[i] for i in range(len(p)))


def perm_power(g, n):
    out = tuple(range(len(g)))
    for _ in range(n):
        out = compose(g, out)
    return out


def rank_bits(rows):
    basis = {}
    for x in rows:
        y = x
        while y:
            p = y.bit_length() - 1
            if p in basis:
                y ^= basis[p]
            else:
                basis[p] = y
                break
    return len(basis), basis


def in_span(x, basis):
    y = x
    while y:
        p = y.bit_length() - 1
        if p not in basis:
            return False
        y ^= basis[p]
    return True


def basis_list(rows):
    return list(rank_bits(rows)[1].values())


def enumerate_code(basis):
    code = [0]
    for b in basis:
        code += [x ^ b for x in code]
    return code


# ---------------------------------------------------------------------------
# Prime-field projective helpers
# ---------------------------------------------------------------------------

def normp(v, q):
    v = tuple(x % q for x in v)
    for a in v:
        if a:
            z = pow(a, -1, q)
            return tuple(z * x % q for x in v)
    raise ValueError("zero vector")


def p1_prime(q):
    return [(1, t) for t in range(q)] + [(0, 1)]


def pg3_prime(q):
    out = []
    for lead in range(4):
        for tail in itertools.product(range(q), repeat=3 - lead):
            out.append((0,) * lead + (1,) + tail)
    return out


def Bp(u, v, q):
    return (u[0] * v[1] - u[1] * v[0] + u[2] * v[3] - u[3] * v[2]) % q


def Qp(v, q):
    return (v[0] * v[1] + v[2] * v[3]) % q


def mat_norm_prime(m, q):
    return normp(m, q)


def mat_apply_prime(m, v, q):
    a, b, c, d = m
    return normp((a * v[0] + b * v[1], c * v[0] + d * v[1]), q)


def pgl_psl_perms_prime(q):
    P = p1_prime(q)
    idx = {x: i for i, x in enumerate(P)}
    squares = {x * x % q for x in range(1, q)}
    pgl_mats = set()
    psl_mats = set()
    for vals in itertools.product(range(q), repeat=4):
        if not any(vals):
            continue
        a, b, c, d = vals
        if (a * d - b * c) % q == 0:
            continue
        key = mat_norm_prime(vals, q)
        pgl_mats.add(key)
        a, b, c, d = key
        if (a * d - b * c) % q in squares:
            psl_mats.add(key)
    def perms(mats):
        return sorted({tuple(idx[mat_apply_prime(m, v, q)] for v in P) for m in mats})
    return perms(pgl_mats), perms(psl_mats)


def row_bits_from_perm(g):
    n = len(g)
    x = 0
    for a in range(n):
        x |= 1 << (a * n + g[a])
    return x


# ---------------------------------------------------------------------------
# Quadratic extension fields GF(p^2), sufficient for q=9,25 replay
# ---------------------------------------------------------------------------
class GFp2:
    def __init__(self, p, d):
        self.p = p
        self.d = d % p
        self.q = p * p

    def pair(self, x):
        return x % self.p, x // self.p

    def enc(self, a, b):
        return (a % self.p) + self.p * (b % self.p)

    def add(self, x, y):
        a, b = self.pair(x); c, d = self.pair(y)
        return self.enc(a + c, b + d)

    def neg(self, x):
        a, b = self.pair(x)
        return self.enc(-a, -b)

    def sub(self, x, y):
        return self.add(x, self.neg(y))

    def mul(self, x, y):
        a, b = self.pair(x); c, e = self.pair(y)
        return self.enc(a * c + b * e * self.d, a * e + b * c)

    def inv(self, x):
        if x == 0:
            raise ZeroDivisionError
        a, b = self.pair(x)
        den = (a * a - self.d * b * b) % self.p
        z = pow(den, -1, self.p)
        return self.enc(a * z, -b * z)

    def square(self, x):
        return self.mul(x, x)


def normF(v, F):
    for a in v:
        if a:
            z = F.inv(a)
            return tuple(F.mul(z, x) for x in v)
    raise ValueError("zero vector")


def p1_F(F):
    return [(1, t) for t in range(F.q)] + [(0, 1)]


def pg3_F(F):
    out = []
    for lead in range(4):
        for tail in itertools.product(range(F.q), repeat=3 - lead):
            out.append((0,) * lead + (1,) + tail)
    return out


def QF(v, F):
    return F.add(F.mul(v[0], v[1]), F.mul(v[2], v[3]))


def BF(u, v, F):
    return F.add(
        F.sub(F.mul(u[0], v[1]), F.mul(u[1], v[0])),
        F.sub(F.mul(u[2], v[3]), F.mul(u[3], v[2])),
    )


def segreF(u, v, F):
    return normF((
        F.mul(u[0], v[0]),
        F.mul(u[1], v[1]),
        F.mul(u[0], v[1]),
        F.neg(F.mul(u[1], v[0])),
    ), F)


def TapplyF(p, v, F):
    a, b, c, d = p
    return normF((
        F.sub(F.mul(c, v[0]), F.mul(a, v[1])),
        F.sub(F.neg(F.mul(b, v[0])), F.mul(d, v[1])),
    ), F)


def mat_apply_F(m, v, F):
    a, b, c, d = m
    return normF((
        F.add(F.mul(a, v[0]), F.mul(b, v[1])),
        F.add(F.mul(c, v[0]), F.mul(d, v[1])),
    ), F)


def pgl_psl_perms_F(F):
    P = p1_F(F)
    idx = {x: i for i, x in enumerate(P)}
    squares = {F.square(x) for x in range(1, F.q)}
    pgl_mats = set()
    psl_mats = set()
    for vals in itertools.product(range(F.q), repeat=4):
        if not any(vals):
            continue
        a, b, c, d = vals
        det = F.sub(F.mul(a, d), F.mul(b, c))
        if det == 0:
            continue
        key = normF(vals, F)
        pgl_mats.add(key)
        a, b, c, d = key
        det = F.sub(F.mul(a, d), F.mul(b, c))
        if det in squares:
            psl_mats.add(key)
    def perms(mats):
        return sorted({tuple(P.index(mat_apply_F(m, v, F)) for v in P) for m in mats})
    return perms(pgl_mats), perms(psl_mats)


def extension_replay(F):
    P = p1_F(F)
    idx = {x: i for i, x in enumerate(P)}
    points = pg3_F(F)
    squares = {F.square(x) for x in range(1, F.q)}
    S = [x for x in points if QF(x, F) == 0]
    C = [x for x in points if QF(x, F) in squares]
    assert len(S) == (F.q + 1) ** 2
    assert len(C) == F.q * (F.q * F.q - 1) // 2

    grid = {}
    for i, u in enumerate(P):
        for j, v in enumerate(P):
            s = segreF(u, v, F)
            assert s not in grid
            grid[s] = (i, j)
    assert set(grid) == set(S)

    perms = set()
    rows = []
    n = F.q + 1
    for p in C:
        perm = tuple(idx[TapplyF(p, v, F)] for v in P)
        perms.add(perm)
        bits = 0
        for s, (iu, iv) in grid.items():
            incident = BF(p, s, F) == 0
            graph = iu == perm[iv]
            assert incident == graph
            if incident:
                bits |= 1 << (iu * n + iv)
        assert bits.bit_count() == n
        rows.append(bits)
    r2, _ = rank_bits(rows)
    assert r2 == n * n // 2
    return {
        "q": F.q,
        "pg3_points": len(points),
        "singular_grid": len(S),
        "nonsingular_square_class": len(C),
        "distinct_projectivities": len(perms),
        "row_weight": n,
        "binary_rank": r2,
        "binary_rank_formula": n * n // 2,
        "all_incidence_checks": len(C) * len(S),
    }, rows


# ---------------------------------------------------------------------------
# Pass 5595 -- automorphism group mechanism
# ---------------------------------------------------------------------------

def natural_aut_count_prime(q):
    N, G = pgl_psl_perms_prime(q)
    Gset = set(G)
    gi = {g: i for i, g in enumerate(G)}
    n = q + 1
    signatures = set()
    for a in N:
        ia = inverse_perm(a)
        for c in G:
            b = compose(c, a)
            ib = inverse_perm(b)
            r = tuple(gi[compose(compose(b, g), ia)] for g in G)
            col = tuple(a[x] * n + b[y] for x in range(n) for y in range(n))
            signatures.add((r, col))
            rt = tuple(gi[compose(compose(a, inverse_perm(g)), ib)] for g in G)
            colt = tuple(b[y] * n + a[x] for x in range(n) for y in range(n))
            signatures.add((rt, colt))
    want = 2 * len(G) * len(N)
    assert len(signatures) == want
    return {
        "q": q,
        "PSL2_order": len(G),
        "normalizer_PGL2_order_prime_case": len(N),
        "natural_automorphisms_enumerated": len(signatures),
        "formula_prime_case": want,
    }


# ---------------------------------------------------------------------------
# Pass 5596 -- explicit Reye/Latin degree-12 conjugacy
# ---------------------------------------------------------------------------

def latin_reye_conjugacy():
    S4 = list(itertools.permutations(range(4)))
    A4 = sorted(g for g in S4 if parity(g) == 0)
    ai = {g: i for i, g in enumerate(A4)}

    reye = set()
    for a in S4:
        ia = inverse_perm(a)
        for b in S4:
            if parity(a) != parity(b):
                continue
            ib = inverse_perm(b)
            reye.add(tuple(ai[compose(compose(b, g), ia)] for g in A4))
            reye.add(tuple(ai[compose(compose(a, inverse_perm(g)), ib)] for g in A4))
    assert len(reye) == 576

    # Latin V4 table is x+y+z=0 on three labelled copies of F2^2.
    GL = []
    for p in itertools.permutations(range(4)):
        if p[0] != 0:
            continue
        if all(p[x ^ y] == (p[x] ^ p[y]) for x in range(4) for y in range(4)):
            GL.append(p)
    latin = set()
    for pi in itertools.permutations(range(3)):
        for A in GL:
            for t0 in range(4):
                for t1 in range(4):
                    ts = (t0, t1, t0 ^ t1)
                    p = [0] * 12
                    for part in range(3):
                        for x in range(4):
                            p[4 * part + x] = 4 * pi[part] + (A[x] ^ ts[part])
                    latin.add(tuple(p))
    assert len(latin) == 576

    # A4 = V4 : <r>.  V4 is regular on four letters.  The explicit map is
    # Phi(v r^k)=(k, r^k(v(0))).
    V4 = {g for g in A4 if compose(g, g) == tuple(range(4))}
    r = (0, 2, 3, 1)
    assert r in A4 and perm_power(r, 3) == tuple(range(4))
    phi = []
    table = []
    for g in A4:
        hit = None
        for k in range(3):
            rk = perm_power(r, k)
            v = compose(g, inverse_perm(rk))
            if v in V4:
                hit = (k, rk[v[0]])
                break
        assert hit is not None
        phi.append(4 * hit[0] + hit[1])
        table.append({"A4_permutation": list(g), "latin_part": hit[0], "V4_symbol": hit[1]})
    phi = tuple(phi)
    iphi = inverse_perm(phi)
    conjugated = {compose(compose(phi, g), iphi) for g in reye}
    assert conjugated == latin

    # Rank-3 orbital sizes: diagonal + 3K4 + its complement.
    def orbital_sizes(G):
        seen = set(); sizes = []
        for i in range(12):
            for j in range(12):
                if (i, j) in seen:
                    continue
                orb = {(g[i], g[j]) for g in G}
                seen |= orb
                sizes.append(len(orb))
        return sorted(sizes)
    assert orbital_sizes(reye) == [12, 36, 96]
    assert orbital_sizes(latin) == [12, 36, 96]
    return {
        "status": "EXPLICIT_PERMUTATION_ISOMORPHISM",
        "group_order": 576,
        "reye_degree": 12,
        "latin_degree": 12,
        "conjugating_permutation_reye_index_to_latin_symbol": list(phi),
        "conceptual_map": "Phi(v r^k)=(k,r^k(v(0))) for A4=V4:<r>, r=(0 2 3 1)",
        "mapping_table": table,
        "orbital_sizes": [12, 36, 96],
        "small_orbital_graph": "3 disjoint K4 blocks",
        "cover_boundary": "The committed 13-cover certificate records only abstract group isomorphism plus orbit sizes 1+12, not explicit S13 generators. This pass proves Reye=Latin as permutation actions; it does not silently upgrade the 13-cover 12-orbit to the same action without those generators or a subgroup-conjugacy proof.",
    }


# ---------------------------------------------------------------------------
# Pass 5598 -- relation to W line code / footprint kernel
# ---------------------------------------------------------------------------

def line_points_prime(u, v, q):
    return frozenset(normp(tuple(a * u[i] + b * v[i] for i in range(4)), q)
                     for a, b in p1_prime(q))


def W_lines_prime(q, points):
    lines = set()
    for i, u in enumerate(points):
        for v in points[i + 1:]:
            if Bp(u, v, q) == 0:
                lines.add(line_points_prime(u, v, q))
    return list(lines)


def footprint_projection_anchor(q):
    pts = pg3_prime(q)
    S = [p for p in pts if Qp(p, q) == 0]
    squares = {x * x % q for x in range(1, q)}
    C = [p for p in pts if Qp(p, q) in squares]
    si = {p: i for i, p in enumerate(S)}
    lines = W_lines_prime(q, pts)
    line_restrictions = []
    for L in lines:
        x = 0
        for p in L:
            if p in si:
                x |= 1 << si[p]
        line_restrictions.append(x)
    rline, bline = rank_bits(line_restrictions)

    Mrows = []
    for p in C:
        x = 0
        for s in S:
            if Bp(p, s, q) == 0:
                x |= 1 << si[s]
        Mrows.append(x)
    rm, bm = rank_bits(Mrows)
    assert rm == (q + 1) ** 2 // 2
    assert all(in_span(x, bline) for x in Mrows)
    return {
        "q": q,
        "W_points": len(pts),
        "W_lines": len(lines),
        "Segre_coordinates": len(S),
        "restricted_line_code_rank": rline,
        "projectivity_code_rank": rm,
        "projectivity_code_is_contained_in_restricted_line_code": True,
        "restricted_line_code_equals_projectivity_code": rline == rm,
    }


# ---------------------------------------------------------------------------
# Pass 5599 -- fixed-point fusion / association data
# ---------------------------------------------------------------------------

def relation_type(g, identity):
    return -1 if g == identity else fixed_points(g)


def fixedpoint_scheme_data(G, verify_all=False):
    identity = tuple(range(len(G[0])))
    typemap = {g: relation_type(g, identity) for g in G}
    types = sorted(set(typemap.values()))
    cls = {t: [g for g in G if typemap[g] == t] for t in types}
    reps = {t: cls[t][0] for t in types}
    rep_counts = {}
    for k, h in reps.items():
        for i in types:
            c = Counter()
            for x in cls[i]:
                c[typemap[compose(inverse_perm(x), h)]] += 1
            for j in types:
                rep_counts[(i, j, k)] = c[j]
    if verify_all:
        for k in types:
            for i in types:
                for j in types:
                    want = rep_counts[(i, j, k)]
                    for h in cls[k]:
                        got = 0
                        for x in cls[i]:
                            if typemap[compose(inverse_perm(x), h)] == j:
                                got += 1
                        assert got == want
    return {t: len(cls[t]) for t in types}, rep_counts


def expected_scheme(q):
    val = {
        0: q * (q - 1) ** 2 // 4,
        1: q * q - 1,
        2: q * (q + 1) * (q - 3) // 4,
    }
    if q == 3:
        return val, None
    mats = {
        0: [
            [(q**3 - 5*q*q + 11*q + 1)//8, (q-3)*(q+1)//2, (q-3)*(q-1)*(q+1)//8],
            [(q-3)*(q+1)//2, 2*(q+1), (q-3)*(q+1)//2],
            [(q-3)*(q-1)*(q+1)//8, (q-3)*(q+1)//2, (q-3)**2*(q+1)//8],
        ],
        1: [
            [q*(q-3)*(q-1)//8, q*(q-1)//2, q*(q-3)*(q-1)//8],
            [q*(q-1)//2, 2*(q-1), q*(q-3)//2],
            [q*(q-3)*(q-1)//8, q*(q-3)//2, q*(q-3)*(q-1)//8],
        ],
        2: [
            [(q-1)**3//8, (q-1)**2//2, (q-3)*(q-1)**2//8],
            [(q-1)**2//2, 2*(q-1), (q-1)**2//2],
            [(q-3)*(q-1)**2//8, (q-1)**2//2, (q**3-3*q*q-5*q-9)//8],
        ],
    }
    return val, mats


def scheme_anchor(q, G, verify_all=False):
    sizes, P = fixedpoint_scheme_data(G, verify_all=verify_all)
    val, mats = expected_scheme(q)
    assert sizes[-1] == 1
    for t in (0, 1, 2):
        if val[t] == 0:
            assert sizes.get(t, 0) == 0
        else:
            assert sizes[t] == val[t]
    if mats is not None:
        for k in (0, 1, 2):
            for i in (0, 1, 2):
                for j in (0, 1, 2):
                    assert P[(i, j, k)] == mats[k][i][j]
    return {
        "q": q,
        "group_order": len(G),
        "relation_valencies_0_1_2_fixed": [val[0], val[1], val[2]],
        "full_intersection_constancy_verified": verify_all,
        "nontrivial_intersection_matrices": mats,
    }


# ---------------------------------------------------------------------------
# Pass 5601 -- exact dual determinant-coset codes
# ---------------------------------------------------------------------------

def dual_coset_anchor_prime(q, enumerate_weights=False):
    PGL, G = pgl_psl_perms_prime(q)
    Gset = set(G)
    h = next(x for x in PGL if x not in Gset)
    Cplus = [row_bits_from_perm(g) for g in G]
    Cminus_perms = [compose(h, g) for g in G]
    Cminus = [row_bits_from_perm(g) for g in Cminus_perms]
    rp, _ = rank_bits(Cplus); rm, _ = rank_bits(Cminus)
    n2 = (q + 1) ** 2
    assert rp == rm == n2 // 2
    assert all((a & b).bit_count() % 2 == 0 for a in Cplus for b in Cminus)
    out = {
        "q": q,
        "length": n2,
        "rank_plus": rp,
        "rank_minus": rm,
        "cross_orthogonal": True,
        "therefore_exact_duals": True,
    }
    if enumerate_weights:
        wp = Counter(x.bit_count() for x in enumerate_code(basis_list(Cplus)))
        wm = Counter(x.bit_count() for x in enumerate_code(basis_list(Cminus)))
        assert wp == wm
        out["weight_enumerator"] = {str(k): v for k, v in sorted(wp.items())}
        out["minimum_distance_measured"] = min(k for k in wp if k)
    return out


def dual_coset_anchor_extension(F, G, plus_rows, full_cross=False):
    PGL, G2 = pgl_psl_perms_F(F)
    assert set(G2) == set(G)
    Gset = set(G)
    h = next(x for x in PGL if x not in Gset)
    minus = [row_bits_from_perm(compose(h, g)) for g in G]
    rp, _ = rank_bits(plus_rows); rm, _ = rank_bits(minus)
    n2 = (F.q + 1) ** 2
    assert rp == rm == n2 // 2
    if full_cross:
        assert all((a & b).bit_count() % 2 == 0 for a in plus_rows for b in minus)
    else:
        # Deterministic spread of cross-pairs; theorem supplies the all-pair proof.
        for i in range(0, len(plus_rows), max(1, len(plus_rows)//97)):
            for j in range(0, len(minus), max(1, len(minus)//89)):
                assert (plus_rows[i] & minus[j]).bit_count() % 2 == 0
    return {
        "q": F.q,
        "length": n2,
        "rank_plus": rp,
        "rank_minus": rm,
        "cross_orthogonality_replay": "full" if full_cross else "deterministic_sample_plus_all-q proof",
        "therefore_exact_duals": True,
    }


# ---------------------------------------------------------------------------
# Main packet
# ---------------------------------------------------------------------------

def main():
    # Prime permutation groups reused across passes.
    prime_groups = {}
    for q in (3, 5, 7, 11, 13):
        _, G = pgl_psl_perms_prime(q)
        prime_groups[q] = G

    # 5595
    aut_anchors = [natural_aut_count_prime(q) for q in (3, 5)]
    aut_formula = []
    for q, f in ((3,1),(5,1),(7,1),(9,2),(25,2)):
        Gorder = q * (q*q - 1) // 2
        Norder = 2 * f * Gorder
        aut_formula.append({
            "q": q, "field_degree_f": f, "PSL2_order": Gorder,
            "PGammaL2_normalizer_order": Norder,
            "full_incidence_aut_order": 2 * Gorder * Norder,
        })

    # 5596
    action_bridge = latin_reye_conjugacy()

    # 5597, including q=9 and q=25 genuine extension fields.
    F9 = GFp2(3, 2)   # w^2=2 over F3
    F25 = GFp2(5, 2)  # w^2=2 over F5
    ext9, rows9 = extension_replay(F9)
    ext25, rows25 = extension_replay(F25)
    _, G9 = pgl_psl_perms_F(F9)
    _, G25 = pgl_psl_perms_F(F25)

    # 5598
    footprint_anchors = [footprint_projection_anchor(q) for q in (3,5,7)]

    # 5599: full closure at small prime/extension anchors, formula replay farther out.
    scheme = []
    for q in (3,5,7,11,13):
        scheme.append(scheme_anchor(q, prime_groups[q], verify_all=(q in (3,5,7))))
    scheme.append(scheme_anchor(9, G9, verify_all=True))
    scheme.append(scheme_anchor(25, G25, verify_all=False))

    # 5601
    isodual = [
        dual_coset_anchor_prime(3, enumerate_weights=True),
        dual_coset_anchor_prime(5, enumerate_weights=True),
        dual_coset_anchor_extension(F9, G9, rows9, full_cross=True),
        dual_coset_anchor_extension(F25, G25, rows25, full_cross=False),
    ]

    out = {
        "status": "PASS_WITH_ASSOCIATION_FORMULA_FIREWALL_AND_PHYSICS_FIREWALLS",
        "pass_range": [5595, 5602],
        "pass_5595_automorphism_group": {
            "theorem": "For odd q=p^f, the full bipartition-preserving incidence automorphism group of the PSL2 projectivity-graph design is the rook-normalizer fiber product extended by transpose: Aut(D_q) = {(a,b) in N^2 : b a^-1 in PSL2(q)} : C2, N=N_Sym(P1)(PSL2)=PGammaL2(q). Hence |Aut(D_q)|=4 f |PSL2(q)|^2.",
            "proof_skeleton": [
                "Column common-neighbour count is zero exactly for cells in one common grid row or column, so every incidence automorphism induces an automorphism of the square rook graph.",
                "Aut(rook_{q+1,q+1})=(S_{q+1} x S_{q+1}):C2; without swapping rulings a column map is (x,y)->(a x,b y).",
                "It preserves graph rows G=PSL2(q) iff b G a^-1=G. Since 1 in G, b a^-1 in G and a normalizes G; conversely these conditions suffice.",
                "The natural permutation normalizer of PSL2(q) is PGammaL2(q), of order 2 f |PSL2(q)| for odd q. Transpose/inversion supplies the final factor 2."
            ],
            "enumerated_prime_anchors": aut_anchors,
            "formula_table": aut_formula,
            "boundary": "The executable enumeration checks the natural/full formula at q=3,5. Completeness for general q uses the standard normalizer theorem N_Sym(P1)(PSL2(q))=PGammaL2(q)."
        },
        "pass_5596_reye_latin_action_intertwiner": action_bridge,
        "pass_5597_extension_field_replay": {
            "q9": ext9, "q25": ext25,
            "theorem_reconciled": "The previously prime-only projectivity verifier now has genuine non-prime anchors; both the geometric incidence and rank_2=(q+1)^2/2 survive."
        },
        "pass_5598_footprint_module_relation": {
            "theorem": "Let C_W be the binary W(3,q) line-incidence code, equal by Pass5376 to ker(F^T). For p in one nonsingular Q-class let N(p) be its full symplectic-neighbour vector. Because q+1 is even, N(p) is the mod-2 sum of the q+1 W-lines through p, hence N(p) in C_W. Projection to the singular Segre sheet S gives exactly the projectivity row M_p. Therefore row(M)=pi_S(span{N(p):p in C+}) is a projected subcode of the footprint kernel, not the footprint image itself.",
            "finite_anchors": footprint_anchors,
            "separation": "At q=3,5,7 the restricted full line code has ranks 15,34,61 while the projectivity code has ranks 8,18,32. Thus equality with the restricted line code is false even though containment is exact.",
            "boundary": "This bridge uses Pass5376's theorem C_W=ker(F^T). It does not identify row(M) with im(F)=C_W^perp."
        },
        "pass_5599_fixedpoint_fusion": {
            "status": "ASSOCIATION_SCHEME_FULLY_VERIFIED_AT_q_3_5_7_9__UNIFORM_FORMULAS_VERIFIED_AT_q_5_7_9_11_13_25",
            "relations": "R_t(g,h) iff g^-1 h has t fixed points on P1(q), t=0,1,2, plus diagonal.",
            "valencies": {
                "R0": "q(q-1)^2/4", "R1": "q^2-1", "R2": "q(q+1)(q-3)/4"
            },
            "anchors": scheme,
            "q3_collapse": "R2 has valency zero. R0 is 3 disjoint K4 blocks (the V4 cosets in A4), and R1 is their complement K_{4,4,4}. This is exactly the 3x4 block system exposed by the Reye-Latin intertwiner.",
            "boundary": "The polynomial intersection matrices are computationally exact on all listed anchors including q=9,25. This packet does not claim an all-odd proof of fusion closure solely from interpolation; a symbolic counting/character proof remains the publication-strength next step."
        },
        "pass_5600_toe_null_sheet": {
            "exact_mathematics": [
                "Q+(3,q)=P1(q)xP1(q) has two canonical rulings of q+1 generator lines.",
                "Every nonsingular point/projectivity graph y=g(x) meets each member of each ruling exactly once: it is a transversal/perfect matching of the two null-coordinate families.",
                "Two such transversals meet in 0,1,2 points according to the fixed points of the relative projectivity."
            ],
            "toe_reading": "This gives a finite two-null-coordinate kinematic sheet and a group of exact discrete worldline-like transversals. It is structurally closer to a 1+1 null-coordinate compactification than to 3+1 spacetime.",
            "firewall": "No Lorentz metric, causal order, continuum limit, 3+1 dimensionality, mass shell, or physical speed of light is derived. The result is a candidate kinematic primitive only."
        },
        "pass_5601_toe_isodual_information_code": {
            "theorem": "Let C+ be the F2 span of vectorized permutation matrices of PSL2(q) on P1(q), and C- the span of the opposite determinant coset in PGL2(q). Then C-=C+^perp for every odd prime power q. Hence C+ is an isodual binary [(q+1)^2,(q+1)^2/2] code.",
            "proof": [
                "The dot product of two permutation matrices is the number of fixed points of their relative projectivity mod 2.",
                "A relative element between opposite determinant cosets has nonsquare determinant class. It cannot be unipotent/one-fixed-point, because a repeated eigenvalue gives square determinant class. Thus it has 0 or 2 fixed points, so every cross inner product is even.",
                "Therefore C- is contained in C+^perp. Pass5594 gives dim C+=(q+1)^2/2; multiplying by one fixed opposite-coset projectivity is a coordinate permutation, so dim C- is the same. Equal half-dimensions force equality."
            ],
            "replay": isodual,
            "information_reading": "The determinant-square split produces an exact half-rate primal/dual pair on the same (q+1)x(q+1) carrier. This is an algebraic information duality, not yet an entropy law of nature.",
            "boundary": "Minimum distance q+1 is measured at q=3,5 only and is not promoted to an all-q theorem here."
        },
        "pass_5602_toe_spectral_action_firewall": {
            "theorem": "After subtracting the constant row mean, the projectivity-frame operator has exactly one nonzero eigenvalue: (q^2-1)/2 with multiplicity q^2 before unit normalization, equivalently frame bound (q^2-1)/(2q) on the unit-norm frame span.",
            "consequence": "Its nonzero spectrum is perfectly flat. The heat trace of this centered operator has only one exponential scale, so it has no Weyl-law ladder from which a local continuum dimension could emerge.",
            "toe_firewall": "The frame Gram is a projector/tight-frame observable, not a credible standalone spacetime Laplacian or kinetic operator. Any TOE dynamics must use a richer operator (for example the repo's Hodge/Hashimoto/transport operators) and be tested separately."
        },
        "global_boundary": "Passes5595-5602 add finite-geometry, group, code, and representation structure. The TOE probes distinguish exact kinematic/information statements from physical interpretation. No Standard-Model, gravity, cosmology, or laboratory claim is certified by this packet."
    }
    OUT.write_text(json.dumps(out, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    print(json.dumps(out, indent=2, sort_keys=True))
    print(f"wrote {OUT.relative_to(ROOT).as_posix()}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
