WF4 := GO(1,4,3);;
GL43 := GL(4,3);;
Sp43 := Sp(4,3);;
n := 0;;
cc := ConjugacyClassesSubgroups(GL43);;
o := Filtered(cc, c -> Size(Representative(c)) = 1152);;
iso := Filtered(o, c -> IsomorphismGroups(Representative(c), WF4) <> fail);;
repo := GAPInfo.SystemEnvironment.W33_REPO;;
f := OutputTextFile(Concatenation(repo, "/data/_gap_ambient.json"), false);;
SetPrintFormattingStatus(f, false);;
AppendTo(f, "{");
AppendTo(f, " \"GL43_order\": ", Size(GL43), ",");
AppendTo(f, " \"classes_order_1152_in_GL43\": ", Length(o), ",");
AppendTo(f, " \"classes_iso_WF4_in_GL43\": ", Length(iso), ",");
AppendTo(f, " \"WF4_in_GL43\": ", Length(iso) > 0, ",");
AppendTo(f, " \"GO4plus3_is_subgroup_of_GL43\": ", IsSubgroup(GL43, WF4), ",");
AppendTo(f, " \"GO4plus3_inside_Sp43\": ", IsSubgroup(Sp43, WF4));
AppendTo(f, "}");
CloseStream(f);;
