#!/usr/bin/env python3
"""Construct a trinification H27 in E6 whose center is literally Z(E6),
then glue it to the physical external-A2 H27 inside E8 to obtain the
two-qutrit Pauli group 3_+^(1+4) of order 243.

The prior no-go applies only to the Pass369 regular Weyl H27.  Here we use the
different maximal-rank trinification subgroup
    E6 >= (SU3_1 x SU3_2 x SU3_3) / Delta Z3
with
    27 = (3,3bar,1) + (1,3,3bar) + (3bar,1,3).

Write qutrit matrices with ZX = omega XZ in each SU3 factor. Define
    X_int = (X, X, I)
    Z_int = (Z^2, Z, I).
Then
    [Z_int,X_int] = (omega^2 I, omega I, I).
On the three nonets of the 27 this central triple acts by omega, omega, omega,
so it represents the generator z6 of Z(E6).

The physical external-A2 theorem supplies a second H27 in SU3_ext whose center
z3 is the measured FI/Qpsi phase. In
    (E6 x SU3_ext)/C3 <= E8
the kernel is generated by (z6, z3^-1), hence the two H27 centers are
identified. Their commuting images therefore form the central product
    H27 o H27 = 3_+^(1+4)
of order 27*27/3 = 243, exponent 3, with center order 3 and quotient F3^4.

This is exactly the two-qutrit Pauli/Heisenberg group at the finite-group level.

Boundary: no heterotic vacuum, low-energy family assignment, or hardware
implementation is inferred.
"""
from __future__ import annotations
import json
from itertools import product
from pathlib import Path

ROOT=Path(__file__).resolve().parents[1]
OUT=ROOT/"data/w33_e8_trinification_two_qutrit_pauli243.json"

def add(a,b): return tuple((x+y)%3 for x,y in zip(a,b))

# One H27 in normal form (a,b,c)=Z^a X^b omega^c with ZX=omega XZ.
def hmul(g,h):
    a,b,c=g; A,B,C=h
    return ((a+A)%3,(b+B)%3,(c+C-b*A)%3)

H=[(a,b,c) for a,b,c in product(range(3),repeat=3)]
I=(0,0,0)

def hinv(g):
    for h in H:
        if hmul(g,h)==I and hmul(h,g)==I: return h
    raise AssertionError(g)

def comm(g,h):
    return hmul(hmul(hmul(g,h),hinv(g)),hinv(h))

def main(write=True):
    ext=json.loads((ROOT/"data/w33_physical_external_a2_h27.json").read_text())
    nogo=json.loads((ROOT/"data/w33_e6_internal_h27_center_gluing_nogo.json").read_text())
    assert ext["status"]=="PASS_EXPLICIT_PHYSICAL_EXTERNAL_A2_HEISENBERG_27_IN_E8"
    assert nogo["status"]=="PASS_PASS369_CENTER_CANNOT_GLUE_TO_E6_CENTER"

    # Trinification center exponents (a,b,c) mean (omega^a,omega^b,omega^c).
    # Block scalars on (3,3bar,1),(1,3,3bar),(3bar,1,3):
    def block_scalars(t):
        a,b,c=t
        return ((a-b)%3,(b-c)%3,(-a+c)%3)

    delta=(1,1,1)
    ze6=(2,1,0)
    assert block_scalars(delta)==(0,0,0)  # kernel Delta Z3
    assert block_scalars(ze6)==(1,1,1)    # scalar omega on the full 27

    # Internal qutrit pair.  The commutator factor exponents are 2,1,0.
    Xint=("X","X","I")
    Zint=("Z^2","Z","I")
    comm_center=(2,1,0)
    assert comm_center==ze6

    # Abstract H27 checks for each factor.
    assert len(H)==27
    z=(0,0,1); X=(0,1,0); Z=(1,0,0)
    assert comm(Z,X)==z
    center=[g for g in H if all(hmul(g,h)==hmul(h,g) for h in H)]
    assert center==[(0,0,0),(0,0,1),(0,0,2)]
    assert all(hmul(hmul(g,g),g)==I for g in H)

    # Central product model: (H x H)/<(z,z^-1)>.
    pairs=[(g,h) for g in H for h in H]
    kernel=[((0,0,k),(0,0,(-k)%3)) for k in range(3)]
    def pmul(p,q): return (hmul(p[0],q[0]),hmul(p[1],q[1]))
    def pinv(p): return (hinv(p[0]),hinv(p[1]))
    def canonical_coset(p):
        orbit=[]
        for k in kernel:
            orbit.append(pmul(p,k))
        return min(orbit)
    cosets={canonical_coset(p) for p in pairs}
    assert len(cosets)==243

    # Quotient group diagnostics.
    identity=canonical_coset((I,I))
    def cmul(a,b): return canonical_coset(pmul(a,b))
    # Every element has exponent 3.
    assert all(cmul(cmul(g,g),g)==identity for g in cosets)
    # Center exactly common scalar C3.
    ccenter=[g for g in cosets if all(cmul(g,h)==cmul(h,g) for h in cosets)]
    assert len(ccenter)==3
    # Derived subgroup generated by commutators is the same C3.
    comms={canonical_coset(pmul(pmul(pmul(g,h),pinv(g)),pinv(h))) for g in cosets for h in cosets}
    assert len(comms)==3 and set(comms)==set(ccenter)

    # Projective quotient has order 81 = 3^4.
    projective_order=len(cosets)//len(ccenter)
    assert projective_order==81

    out={
      "schema":"w33.e8_trinification_two_qutrit_pauli243.v1",
      "status":"PASS_E8_CONTAINS_TRINIFICATION_CENTRAL_PRODUCT_TWO_QUTRIT_PAULI243",
      "headline":"A new internal trinification H27, distinct from the rejected Pass369 Weyl H27, has center exactly Z(E6). In E6 >= (SU3^3)/DeltaZ3 take X_int=(X,X,I), Z_int=(Z^2,Z,I); with ZX=omegaXZ their commutator is (omega^2,omega,1), which acts as scalar omega on all three nonets of the E6 27. The physical external-A2 H27 has center the measured FI/Qpsi Z3. The kernel of (E6 x SU3_ext)->E8 identifies these two centers, so the commuting H27 factors form their central product of order 243, exponent 3: the two-qutrit Pauli group 3_+^(1+4).",
      "trinification":{
        "subgroup":"(SU3_1 x SU3_2 x SU3_3)/Delta Z3 <= E6",
        "27_branching":"(3,3bar,1)+(1,3,3bar)+(3bar,1,3)",
        "diagonal_kernel_exponents":[1,1,1],
        "E6_center_representative_exponents":[2,1,0],
        "E6_center_action_on_three_nonets":[1,1,1],
        "internal_shift":"(X,X,I)",
        "internal_clock":"(Z^2,Z,I)",
        "commutator":"(omega^2 I, omega I, I) = z_E6"
      },
      "external":{
        "group":"physical external-A2 H27",
        "center":"z_FI = exp(2*pi*i Qpsi/3)",
        "order":27
      },
      "E8_gluing":{
        "subgroup":"(E6 x SU3_ext)/< (z_E6,z_ext^-1) >",
        "centers_identified":True,
        "factors_commute_before_quotient":True,
        "central_product_order":243
      },
      "two_qutrit_pauli":{
        "structure":"3_+^(1+4) = H27 o H27",
        "order":243,
        "exponent":3,
        "center_order":3,
        "derived_order":3,
        "projective_quotient":"F3^4",
        "projective_order":81
      },
      "hostile_control_resolution":"The Pass369 regular Weyl H27 still cannot glue because its center is not Z(E6). The trinification H27 constructed here is a different subgroup specifically engineered and checked to have commutator center Z(E6).",
      "boundary":"Exact finite subgroup/representation theorem. It does not prove a D/F-flat heterotic vacuum, observed family identification, Standard Model dynamics, or photonic implementation.",
      "parents":[
        "data/w33_physical_external_a2_h27.json",
        "data/w33_e6_internal_h27_center_gluing_nogo.json",
        "analysis/w33_standard_model_from_trinification.py"
      ],
      "checks":{
        "trinification_delta_center_is_kernel_on_27":True,
        "new_internal_commutator_is_ZE6":True,
        "two_H27_centers_identified_in_E8_quotient":True,
        "central_product_order243":True,
        "exponent3":True,
        "center_order3":True,
        "derived_order3":True,
        "projective_F3_4_order81":True
      }
    }
    if write: OUT.write_text(json.dumps(out,indent=2)+"\n")
    print(json.dumps(out,indent=2))
    return out

if __name__=="__main__": main(True)
