from __future__ import annotations
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
OUT=ROOT/'data'/'w33_pass1116_runtime_closure.json'
def load(path):return json.loads((ROOT/path).read_text())
def main():
 q=load('data/w33_pass1112_qontrol_q8iv_transport.json');a=load('data/w33_pass1113_e8_a2_triple_carrier_extension.json');c=load('data/w33_pass1114_full_cubic_central_phase_extension.json');f=load('data/w33_pass1115_formal_a2_phase_qontrol_lock.json');d=load('data/w33_pass1120_we6_class_algebra_decomposition.json');i=load('data/w33_pass1121_e8_a2_cubic_incidence.json')
 wf_path='.github/workflows/pass1112_1121_runtime.yml';wf=(ROOT/wf_path).read_text();umbrella=(ROOT/'formal/W33.lean').read_text();obs_path=ROOT/'data/w33_pass1116_runtime_observations.json';obs=json.loads(obs_path.read_text()) if obs_path.exists() else None
 observed=bool(obs and obs.get('ctbllib',{}).get('status')=='PASS' and obs.get('canonical_sign',{}).get('status')=='PASS' and obs.get('lean',{}).get('status')=='PASS')
 checks={'qontrol_reference_passed':q['status']=='PASS_REFERENCE_TRANSPORT','a2_extension_passed':a['status']=='PASS','all45_phase_extension_passed':c['status'] in {'PASS','PASS_WITH_EXPLICIT_SIGN_BOUNDARY'},'formal_source_certificate_passed':f['status'].startswith('PASS_SOURCE_READY'),'class_algebra_decomposition_passed':d['status']=='PASS' and d['checks']['row_orthogonality'],'complete_degree_reconstruction':sum(x['degree']*x['multiplicity'] for x in d['irreducible_rows'])==2240,'a2_cubic_incidence_passed':i['status']=='PASS' and i['counts']['total_cubic_lifts']==540,'workflow_has_python_gap_sign_lean_jobs':all(x in wf for x in ['exact-python:','ctbllib-observed:','canonical-sign-observed:','strict-lean-observed:']),'workflow_is_pull_request_visible':'pull_request:' in wf,'umbrella_imports_pass1115':'import W33.Pass1115A2PhaseQontrolClosure' in umbrella,'pair_and_triple_minima_separated':a['a2_triple_carrier']['degree']==2240 and a['upstream_pass1104']['pair_universe_minimum']['degree']==3360,'central_phase_histogram_exact':c['central_phase_histogram']=={'0':25,'1':10,'2':10},'second_vendor_boundary_is_explicit':q['vendor_profile']['vendor']=='Qontrol' and q['scope'].startswith('Concrete vendor protocol'),'runtime_state_explicit':observed or obs is None,'no_physical_hardware_claim':'No serial port' in q['scope']};assert all(checks.values()),checks
 counts={'pass1112':q['check_count'],'pass1113':a['check_count'],'pass1114':c['check_count'],'pass1115':f['check_count'],'pass1120':d['check_count'],'pass1121':i['check_count'],'pass1116':len(checks)};counts['total']=sum(counts.values())
 out={'schema':'w33.pass1116.runtime_closure.v3','status':'PASS_OBSERVED_RUNTIME_CLOSURE' if observed else 'PASS_LOCAL_RUNTIME_PENDING','headline':('CTblLib row identities, the exact class-algebra decomposition, the canonical cubic sign solve, and the strict serial Lean build have all been observed.' if observed else 'The exact class-algebra decomposition and source certificates pass. CTblLib canonical row ordering remains pending; the canonical sign solve and strict Lean build already have observed receipts.'),'local_exact_checks':counts,'runtime_observations':obs,'workflow':wf_path,'check_count':len(checks),'checks':checks,'scope':'Runtime closure records only observed artifacts. Missing CTblLib evidence leaves status explicitly pending rather than inferred. No physical hardware claim is made.'}
 OUT.write_text(json.dumps(out,indent=2)+'\n');print(json.dumps({'status':out['status'],'checks':len(checks),'total':out['local_exact_checks']['total']},indent=2))
if __name__=='__main__':main()
