#!/usr/bin/env python3
"""Recursive W(3,3) instance compression and scaling witness.

This joins four previously separate architecture facts:

* one W(3,3) instance is an executable component map;
* the Holonet recurses as 40 children per parent;
* the route plane scales with bound 8n for 40^n leaves;
* the mirror bus scales as a depth-independent four-server queue per chart.

The result is an engineering theorem: the recursive machine does not replicate
router/scheduler/bus tables at every level.  It replicates one finite incidence
law.  Conventional control tables scale like I_n=(40^n-1)/39; W(3,3) control
state stays generated by the same local symplectic predicate and exact-cover
objects at every level.
"""

from __future__ import annotations

import argparse
import json
from fractions import Fraction
from pathlib import Path
from typing import Any

from w33_instance_architecture_map import build_report


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_JSON = ROOT / "data" / "w33_recursive_instance_compression.json"
DEFAULT_MD = ROOT / "docs" / "w33_recursive_instance_compression.md"


def load_json(relpath: str) -> dict[str, Any]:
    with (ROOT / relpath).open(encoding="utf-8") as handle:
        return json.load(handle)


def instances(level: int, branching: int = 40) -> int:
    if level < 1:
        raise ValueError("level must be positive")
    return (branching**level - 1) // (branching - 1)


def commit_ticks(level: int) -> int:
    return 4 * (7**level - 1)


def ledger_item(report: dict[str, Any], name: str) -> dict[str, Any]:
    for item in report["compression_ledger"]:
        if item["name"] == name:
            return item
    raise KeyError(name)


def build_payload(levels: int = 6) -> dict[str, Any]:
    if levels < 1:
        raise ValueError("levels must be positive")

    instance_report = build_report()
    bt827 = load_json("data/bt827_holonet_fractal_architecture.json")
    bt1299 = load_json("data/bt1299_harmonic_microframe_runtime.json")
    bt1305 = load_json("data/bt1305_mirror_bus_queueing_law.json")

    inst = instance_report["instance"]
    routes = instance_report["routes"]
    route_table = ledger_item(instance_report, "next-hop routing table")
    control_table_bytes = sum(
        int(item["naive_bytes"]) for item in instance_report["compression_ledger"]
    )

    per_instance = {
        "points_sites_registers_addresses": inst["points"],
        "direct_channels": inst["edges"],
        "line_buses": inst["lines"],
        "spread_clock_frames": inst["spreads"],
        "ordered_nonidentity_routes": inst["points"] * (inst["points"] - 1),
        "routing_table_bytes_avoided": route_table["naive_bytes"],
        "control_table_bytes_avoided": control_table_bytes,
        "max_route_hops": routes["max_hops"],
        "two_hop_relay_choices": 4,
        "mirror_slots": bt827["single_core"]["mirror_slots"],
        "chart_count": bt827["single_core"]["charts"],
        "apartment_slack_slots": bt827["single_core"]["apartments"],
        "microframe_ticks": bt1299["microframe"]["oscillator_horizon_total"],
        "route_tick": bt1299["microframe"]["route_tick"],
    }

    bt827_rows = {
        row["level"]: row for row in bt827["fractal_scaling"]["levels"]
    }
    bt1305_rows = {row["level"]: row for row in bt1305["recursive_scaling"]}

    rows: list[dict[str, Any]] = []
    for level in range(1, levels + 1):
        count = instances(level)
        leaves = inst["points"] ** level
        route_bound = per_instance["route_tick"] * level
        demand = per_instance["chart_count"] * count
        capacity = per_instance["mirror_slots"] * count
        slack = per_instance["apartment_slack_slots"] * count
        utilization = Fraction(demand, capacity)
        row = {
            "level": level,
            "leaf_sites": leaves,
            "w33_instances": count,
            "direct_channels": per_instance["direct_channels"] * count,
            "line_buses": per_instance["line_buses"] * count,
            "spread_clock_frames": per_instance["spread_clock_frames"] * count,
            "ordered_route_entries_avoided": per_instance[
                "ordered_nonidentity_routes"
            ]
            * count,
            "routing_table_bytes_avoided": per_instance[
                "routing_table_bytes_avoided"
            ]
            * count,
            "control_table_bytes_avoided": per_instance[
                "control_table_bytes_avoided"
            ]
            * count,
            "reversible_route_bound": route_bound,
            "persistent_commit_ticks": commit_ticks(level),
            "commit_ticks_mod_microframe": commit_ticks(level)
            % per_instance["microframe_ticks"],
            "commit_frame_locked": commit_ticks(level)
            % per_instance["microframe_ticks"]
            == 0,
            "mirror_one_packet_per_chart_demand": demand,
            "mirror_capacity": capacity,
            "mirror_slack": slack,
            "mirror_utilization": f"{utilization.numerator}/{utilization.denominator}",
        }
        rows.append(row)

    commit_table = bt1299["commit_clock"]["table"]
    expected_frame_locked = [
        row["level"] for row in commit_table if row["frame_locked"]
    ]
    checks = {
        "instance_report_passes": instance_report["status"] == "PASS",
        "bt827_verified": all(bt827["checks"].values()),
        "bt1299_verified": bt1299["verified"] is True,
        "bt1305_verified": bt1305["verified"] is True,
        "per_instance_routing_bytes_are_1170": per_instance[
            "routing_table_bytes_avoided"
        ]
        == 1170,
        "per_instance_control_bytes_are_1816": per_instance[
            "control_table_bytes_avoided"
        ]
        == 1816,
        "one_packet_per_chart_is_quarter_bus": all(
            row["mirror_utilization"] == "1/4" for row in rows
        ),
        "mirror_slack_is_1620_per_instance": all(
            row["mirror_slack"] == per_instance["apartment_slack_slots"] * row["w33_instances"]
            for row in rows
        ),
        "route_bound_is_8n": all(
            row["reversible_route_bound"] == 8 * row["level"] for row in rows
        ),
        "commit_clock_matches_bt827": all(
            row["persistent_commit_ticks"]
            == bt827_rows[row["level"]]["persistent_commit_ticks"]
            for row in rows
            if row["level"] in bt827_rows
        ),
        "queue_rows_match_bt1305": all(
            row["mirror_capacity"] == bt1305_rows[row["level"]]["mirror_capacity"]
            and row["mirror_slack"] == bt1305_rows[row["level"]]["slack"]
            for row in rows
            if row["level"] in bt1305_rows
        ),
        "level6_leaf_count_matches_bt827": (
            rows[5]["leaf_sites"] == bt827_rows[6]["leaf_photonic_cores"]
            if len(rows) >= 6
            else True
        ),
        "level6_instances_match_bt827": (
            rows[5]["w33_instances"] == bt827_rows[6]["w33_instances_total"]
            if len(rows) >= 6
            else True
        ),
        "level6_route_table_bytes_avoided_exact": (
            rows[5]["routing_table_bytes_avoided"] == 122_879_999_970
            if len(rows) >= 6
            else True
        ),
        "commit_frame_lock_period_is_q": expected_frame_locked == [3, 6, 9, 12],
    }

    payload = {
        "schema": "w33.recursive_instance_compression.v1",
        "theorem": "recursive W(3,3) instance compression law",
        "status": "PASS" if all(checks.values()) else "FAIL",
        "source_artifacts": [
            "analysis/w33_instance_architecture_map.py",
            "analysis/bt827_holonet_fractal_architecture.py",
            "analysis/bt1299_harmonic_microframe_runtime.py",
            "analysis/bt1305_mirror_bus_queueing_law.py",
        ],
        "per_instance": per_instance,
        "formulas": {
            "leaf_sites": "40^n",
            "w33_instances": "I_n = (40^n - 1) / 39",
            "routing_table_bytes_avoided": "1170 * I_n",
            "control_table_bytes_avoided": "1816 * I_n",
            "reversible_route_bound": "8n",
            "persistent_commit_ticks": "4*(7^n - 1)",
            "mirror_capacity": "2160 * I_n",
            "one_packet_per_chart_demand": "540 * I_n",
            "mirror_slack": "1620 * I_n",
        },
        "recursive_rows": rows,
        "checks": checks,
        "interpretation": (
            "The recursion copies instances, not tables.  Every level reuses the "
            "same local incidence law: points are sites/addresses/registers, "
            "edges are direct routes/gate channels, lines are K4 buses, spreads "
            "are global clock frames, and the spread-overlap graph is the "
            "scheduler.  The avoided conventional control state scales with "
            "I_n, while the reversible route depth scales only as 8n."
        ),
        "honesty_boundary": (
            "This witness proves finite control-state compression and exact "
            "scheduler/queue scaling inside the repository model. It does not "
            "claim host CPU acceleration or physical photonic hardware speedup."
        ),
    }
    return payload


def markdown(payload: dict[str, Any]) -> str:
    per = payload["per_instance"]
    row_lines = []
    for row in payload["recursive_rows"]:
        row_lines.append(
            "| {level} | {leaf_sites:,} | {w33_instances:,} | {reversible_route_bound} | "
            "{persistent_commit_ticks:,} | {routing_table_bytes_avoided:,} | "
            "{control_table_bytes_avoided:,} | {mirror_utilization} |".format(**row)
        )

    return f"""# Recursive W(3,3) Instance Compression

This witness connects the one-instance machine map to the older Holonet
fractal, microframe, and mirror-bus witnesses.  The result is a concrete
systems claim:

> A recursive Holonet copies `W(3,3)` instances, not routing tables.  The control
> state that a conventional network would store grows like `I_n=(40^n-1)/39`,
> while the Holonet regenerates the route, bus, clock, and scheduler layers from
> the same incidence law at every level.

## One Instance

- Sites/registers/addresses: `{per['points_sites_registers_addresses']}`
- Direct route/gate channels: `{per['direct_channels']}`
- K4 line buses: `{per['line_buses']}`
- Spread clock frames: `{per['spread_clock_frames']}`
- Ordered nonidentity routes: `{per['ordered_nonidentity_routes']}`
- Routing table bytes avoided per instance: `{per['routing_table_bytes_avoided']}`
- Total listed control-table bytes avoided per instance: `{per['control_table_bytes_avoided']}`
- Route tick: `{per['route_tick']}`
- Microframe: `{per['microframe_ticks']}`
- Mirror bus: `{per['mirror_slots']}` slots = `{per['chart_count']}` charts x 4

## Recursive Scaling

| Level | Leaf sites | W33 instances | Route bound | Commit ticks | Routing bytes avoided | Control bytes avoided | Mirror use |
|---:|---:|---:|---:|---:|---:|---:|---:|
{chr(10).join(row_lines)}

At level 6, the architecture has `4,096,000,000` leaf sites and
`105,025,641` W33 instances.  A conventional per-instance next-hop table would
replicate `122,879,999,970` routing bytes before counting adjacency, bus,
spread, or frame-transition tables.  The listed finite control tables together
would account for `190,726,564,056` bytes.  In the Holonet those layers are not
persistent tables; they are regenerated from projective addresses, the
symplectic predicate, exact line incidence, spread exact covers, and spread
overlap.

## Architecture Reading

The local component map and the recursive scaling law say the same thing from
opposite ends:

1. Locally, topology encodes operation legality: addresses, routes, gates,
   buses, clock frames, and scheduler transitions are incidence predicates.
2. Recursively, the machine scales by replacing a point with another full
   W33 instance, so the formula `40^n` counts leaves while `(40^n-1)/39` counts
   the internal W33 machines that would otherwise need independent control
   tables.
3. Temporally, an `8n` reversible route bound coexists with the durable
   `4(7^n-1)` commit clock.  The fast route plane and the slower memory plane
   are different subsystems, not a contradiction.
4. Operationally, one packet per chart uses exactly `1/4` of the mirror bus at
   every depth, leaving `1620` slack slots per W33 instance for repair,
   retries, and admission control.

Boundary: this is an exact finite architecture and compression witness. It is
not a claim that a classical host CPU has been physically bypassed; it specifies
the topology-native control plane a host can emulate or a future qutrit device
could implement directly.
"""


def display_path(path: Path) -> str:
    try:
        return str(path.relative_to(ROOT))
    except ValueError:
        return str(path)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--levels", type=int, default=6)
    parser.add_argument("--json-out", default=str(DEFAULT_JSON))
    parser.add_argument("--md-out", default=str(DEFAULT_MD))
    args = parser.parse_args(argv)

    payload = build_payload(args.levels)
    json_out = Path(args.json_out)
    if not json_out.is_absolute():
        json_out = ROOT / json_out
    md_out = Path(args.md_out)
    if not md_out.is_absolute():
        md_out = ROOT / md_out
    json_out.parent.mkdir(parents=True, exist_ok=True)
    md_out.parent.mkdir(parents=True, exist_ok=True)
    json_out.write_text(json.dumps(payload, indent=2), encoding="utf-8")
    md_out.write_text(markdown(payload), encoding="utf-8")

    last = payload["recursive_rows"][-1]
    print(f"status: {payload['status']}")
    print(
        "level {level}: leaves={leaf_sites:,}, instances={w33_instances:,}, "
        "route_bound={reversible_route_bound}, commit_ticks={persistent_commit_ticks:,}".format(
            **last
        )
    )
    print(
        "table compression: {routing_table_bytes_avoided:,} routing bytes, "
        "{control_table_bytes_avoided:,} listed control bytes avoided".format(**last)
    )
    print(
        "mirror bus: demand={mirror_one_packet_per_chart_demand:,}, "
        "capacity={mirror_capacity:,}, utilization={mirror_utilization}".format(**last)
    )
    print(f"wrote: {display_path(json_out)}")
    print(f"wrote: {display_path(md_out)}")
    return 0 if payload["status"] == "PASS" else 1


if __name__ == "__main__":
    raise SystemExit(main())
