#!/usr/bin/env python3
"""Pass 1886: identify Aut(T) with Fix(alpha) and freeze its voltage orbifold."""
from __future__ import annotations
import hashlib,importlib.util,json
from pathlib import Path
import networkx as nx
import sympy as sp
ROOT=Path(__file__).resolve().parents[1]
CORE=ROOT/'analysis/w33_pass1861_1865_outer_doily_transfer_clock.py';OUT=ROOT/'data/w33_pass1886_geometric_c4_clock_model.json'

def load_core():
 s=importlib.util.spec_from_file_location('outerclock',CORE);m=importlib.util.module_from_spec(s);assert s.loader;s.loader.exec_module(m);return m
def cycles(p):
 seen=set();out=[]
 for i in range(len(p)):
  if i not in seen:
   z=[];j=i
   while j not in seen:seen.add(j);z.append(j);j=p[j]
   out.append(tuple(z))
 return out
def canonical_hash(d):
 x=dict(d);x.pop('sha256_without_hash_field',None);return hashlib.sha256(json.dumps(x,sort_keys=True,separators=(',',':')).encode()).hexdigest()
def main():
 c=load_core();base=c.main(None);T=sp.Matrix(base['outer_transfer_matrix']);duads=tuple(tuple(x) for x in base['duads']);alpha,_=c.generate_outer_automorphism();fixed=[g for g in alpha if alpha[g]==g]
 autos=[]
 for g in alpha:
  q=c.induced_action_on_duads(g,duads);P=c.permutation_matrix(q)
  if P*T==T*P:autos.append(g)
 gen=(1,4,3,2,5,0);qg=c.induced_action_on_duads(gen,duads);orbs=cycles(qg);names=('A','B','C','D','E');phase={v:(i,r) for i,o in enumerate(orbs) for r,v in enumerate(o)}
 DG=nx.DiGraph();DG.add_nodes_from(range(15))
 for i in range(15):
  for j in range(15):
   if T[i,j]:DG.add_edge(i,j)
 nautos=list(nx.algorithms.isomorphism.DiGraphMatcher(DG,DG).isomorphisms_iter())
 arcs={}
 for name,o in zip(names,orbs):
  v=o[0];arcs[name]=[]
  for j in DG.successors(v):
   oi,r=phase[j];arcs[name].append({'to':names[oi],'offset':r})
 arcs['E']=[{'to':'D','offset':0},{'to':'D','offset':1},{'to':'E','offset':0}]
 checks={'alpha_fixed_group_order4':len(fixed)==4,'fixed_equals_commuting_s6':set(fixed)==set(autos),'generator_order4':c.cycle_type(gen)==(4,2),'full_digraph_aut_order4':len(nautos)==4,'orbit_sizes_44421':[len(o) for o in orbs]==[4,4,4,2,1],'single_loop_at_23':list(nx.simple_cycles(DG,length_bound=1))==[[9]] and duads[9]==(2,3),'strongly_connected':nx.is_strongly_connected(DG),'diameter3':nx.diameter(DG)==3,'arc_count45':DG.number_of_edges()==45}
 out={'schema':'w33.pass1886.geometric_c4_clock_model.v1','status':'PASS','outer_automorphism_fixed_subgroup_order':len(fixed),'outer_automorphism_fixed_subgroup_structure':'C4','generator_on_six_labels':list(gen),'generator_cycles':'(0 1 4 5)(2 3)','generator_on_duads':list(qg),'duad_orbits':{n:[list(duads[i]) for i in o] for n,o in zip(names,orbs)},'orbit_sizes':[len(o) for o in orbs],'vertex_stabilizers':{'A':'1','B':'1','C':'1','D':'C2','E':'C4'},'quotient_voltage_orbifold_arcs':arcs,'lift_rule':'Apply the C4 generator simultaneously to source and target. Offsets are phases from the displayed representative; D phases are modulo 2 and E has one phase.','fixed_loop':{'vertex_index':9,'duad':[2,3],'base_vertex':'E'},'directed_graph':{'vertices':15,'arcs':45,'outdegree':3,'strongly_connected':True,'diameter':3,'loops':1,'automorphism_group_order':len(nautos)},'tutte_coxeter_fold':'The graph is the one-part exceptional fold T=P^T D of the Tutte-Coxeter Levi graph. Its residual C4 symmetry is exactly Fix(alpha), not an accidental graph automorphism.','checks':{k:bool(v) for k,v in checks.items()},'theorem':'The full directed automorphism group of the outer-doily transfer graph is exactly Fix(alpha), the fixed subgroup of the exceptional S6 outer automorphism. It is generated by (0 1 4 5)(2 3), hence is C4. Its duad orbits are 4+4+4+2+1, and the unique loop is the fixed duad {2,3}. The five-vertex graph-of-groups voltage data reconstructs all 45 arcs.','boundary':'This is a finite exceptional-fold/voltage model. The C4 phase labels are graph phases, not physical time or optical phase.'}
 assert all(checks.values()),{k:v for k,v in checks.items() if not v};out['sha256_without_hash_field']=canonical_hash(out);OUT.write_text(json.dumps(out,sort_keys=True,separators=(',',':'))+'\n');print(json.dumps({'status':'PASS','aut':'C4','sha256':out['sha256_without_hash_field']},indent=2));return out
if __name__=='__main__':main()
