#!/usr/bin/env python3
"""
Exact weld between two previously separate E8 -> W(3,3) constructions.

Prior results, not reclaimed here:
  * W33-Theory Pass 1021:
      the 240 E8 roots form forty canonical six-root Coxeter/Eisenstein fibres
      under <c^5> = <-1,c^10> ~= Z6, and the induced PSp(4,3) quotient is the
      W(3,3) point action.
  * Holotrade 68df33f / W33-Theory aaae20b:
      for the fixed-point-free order-3 twist g of E8, the twisted lattice-VOA
      ground-state register is the Heisenberg representation of
      E8/(1-g)E8, and its commutator geometry is W(3,3).

New exact statement checked here:
  The two quotient maps are literally the same map on the 240 roots.  With
  g = c^10 for the canonical Coxeter element c used by Pass 1021,

      E8/(1-g)E8 ~= F_3^4,

  the roots occupy all 80 nonzero quotient vectors, exactly three roots per
  vector, each three-set is a g-orbit, and projectivizing v ~ -v gives forty
  six-root fibres.  Those fibres are exactly the <-1,g> = <c^5> unit orbits
  from Pass 1021.  The Bakalov-Kac twisted commutator form on this quotient
  is alternating/nondegenerate and its projective orthogonality graph is
  srg(40,12,2,4).

The computation is exact over Z/Q and F_3.  No physics claim is made.
"""

from __future__ import annotations

import itertools
import json
from collections import Counter
from pathlib import Path

import sympy as sp
from sympy.matrices.normalforms import smith_normal_form
from sympy.polys.domains import ZZ

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "data" / "w33_e8_twisted_fibration_weld.json"


def e8_roots():
    roots = []
    for i, j in itertools.combinations(range(8), 2):
        for si in (1, -1):
            for sj in (1, -1):
                v = [0] * 8
                v[i], v[j] = 2 * si, 2 * sj
                roots.append(tuple(v))
    for v in itertools.product((1, -1), repeat=8):
        if v.count(-1) % 2 == 0:
            roots.append(tuple(v))
    assert len(roots) == len(set(roots)) == 240
    return roots


SIMPLE_ROOTS = [
    [ 1,-1,-1,-1,-1,-1,-1, 1],
    [ 2, 2, 0, 0, 0, 0, 0, 0],
    [-2, 2, 0, 0, 0, 0, 0, 0],
    [ 0,-2, 2, 0, 0, 0, 0, 0],
    [ 0, 0,-2, 2, 0, 0, 0, 0],
    [ 0, 0, 0,-2, 2, 0, 0, 0],
    [ 0, 0, 0, 0,-2, 2, 0, 0],
    [ 0, 0, 0, 0, 0,-2, 2, 0],
]


def reflection(r):
    """Row-vector reflection in a doubled-coordinate E8 root (r,r)=8."""
    rv = sp.Matrix(r)
    return sp.eye(8) - (rv * rv.T) / 4


def matrix_order(A, limit=120):
    I = sp.eye(A.rows)
    P = I
    for n in range(1, limit + 1):
        P = P * A
        if P == I:
            return n
    return None


def rank_mod(A, p):
    A = [[int(x) % p for x in row] for row in A]
    m, n = len(A), len(A[0])
    r = 0
    for c in range(n):
        pivot = next((i for i in range(r, m) if A[i][c] % p), None)
        if pivot is None:
            continue
        A[r], A[pivot] = A[pivot], A[r]
        inv = pow(A[r][c], -1, p)
        A[r] = [(x * inv) % p for x in A[r]]
        for i in range(m):
            if i != r and A[i][c] % p:
                f = A[i][c] % p
                A[i] = [(A[i][j] - f * A[r][j]) % p for j in range(n)]
        r += 1
    return r


def int_row(row):
    vals = []
    for x in row:
        x = sp.Rational(x)
        assert x.q == 1
        vals.append(int(x))
    return tuple(vals)


def same_coset(c, d, Minv):
    """c-d lies in the row lattice generated by M."""
    row = sp.Matrix([[c[i] - d[i] for i in range(8)]]) * Minv
    return all(sp.Rational(x).q == 1 for x in row)


def srg_parameters(adj):
    n = len(adj)
    deg = [len(a) for a in adj]
    assert len(set(deg)) == 1
    lam, mu = set(), set()
    for i in range(n):
        for j in range(i + 1, n):
            common = len(adj[i] & adj[j])
            (lam if j in adj[i] else mu).add(common)
    return {
        "n": n,
        "k": deg[0],
        "lambda": next(iter(lam)) if len(lam) == 1 else sorted(lam),
        "mu": next(iter(mu)) if len(mu) == 1 else sorted(mu),
        "strongly_regular": len(lam) == len(mu) == 1,
    }


def main(write=True):
    roots = e8_roots()
    root_index = {r: i for i, r in enumerate(roots)}

    # Exact same simple roots / Coxeter convention as Pass 1021.
    c = sp.eye(8)
    for r in SIMPLE_ROOTS:
        c = c * reflection(r)
    g = c ** 10
    minus = -sp.eye(8)

    B = sp.Matrix(SIMPLE_ROOTS)
    Binv = B.inv()
    Gram = B * B.T / 4
    G = B * g * Binv
    M = sp.eye(8) - G
    Minv = M.inv()

    assert matrix_order(c, 60) == 30
    assert matrix_order(g, 12) == 3
    assert matrix_order(c ** 5, 12) == 6
    assert c ** 15 == minus
    assert g == (c ** 5) ** 2
    assert minus == (c ** 5) ** 3
    assert all(sp.Rational(x).q == 1 for x in Gram)
    assert Gram.det() == 1
    assert all(sp.Rational(x).q == 1 for x in G)
    assert M.det() == 81

    snf = smith_normal_form(M, domain=ZZ)
    snf_diag = [abs(int(snf[i, i])) for i in range(8)]
    assert snf_diag == [1, 1, 1, 1, 3, 3, 3, 3]

    coeff = []
    for r in roots:
        coeff.append(int_row(sp.Matrix([list(r)]) * Binv))

    classes = []
    for i, x in enumerate(coeff):
        for cl in classes:
            if same_coset(x, coeff[cl[0]], Minv):
                cl.append(i)
                break
        else:
            classes.append([i])
    assert len(classes) == 80
    assert Counter(map(len, classes)) == Counter({3: 80})
    assert all(not same_coset(coeff[cl[0]], (0,) * 8, Minv) for cl in classes)

    class_of = {}
    for a, cl in enumerate(classes):
        for i in cl:
            class_of[i] = a

    def act_root(i, A):
        x = sp.Matrix([list(roots[i])]) * A
        rr = int_row(x)
        return root_index[rr]

    for cl in classes:
        i = cl[0]
        assert {i, act_root(i, g), act_root(i, g ** 2)} == set(cl)

    neg_class = {}
    for a, cl in enumerate(classes):
        i = cl[0]
        neg_i = root_index[tuple(-x for x in roots[i])]
        neg_class[a] = class_of[neg_i]
    assert all(neg_class[a] != a for a in range(80))

    seen = set()
    fibres = []
    for a in range(80):
        if a in seen:
            continue
        b = neg_class[a]
        seen.update((a, b))
        fibre = sorted(classes[a] + classes[b])
        fibres.append((a, b, fibre))
    assert len(fibres) == 40
    assert all(len(f) == 6 for _, _, f in fibres)

    for _, _, fibre in fibres:
        i = fibre[0]
        unit_orbit = {
            act_root(i, g ** k) for k in range(3)
        } | {
            root_index[tuple(-x for x in roots[act_root(i, g ** k)])]
            for k in range(3)
        }
        assert unit_orbit == set(fibre)

    # Bakalov-Kac twisted commutator exponent for p=3, in the convention
    # already certified by Holotrade 68df33f.
    Omega = G * Gram + 2 * (G ** 2) * Gram
    O = [[int(Omega[i, j]) % 3 for j in range(8)] for i in range(8)]
    Mm = [[int(M[i, j]) % 3 for j in range(8)] for i in range(8)]
    assert all((O[i][j] + O[j][i]) % 3 == 0 for i in range(8) for j in range(8))
    assert rank_mod(O, 3) == 4
    assert rank_mod(Mm, 3) == 4

    MO = [[sum(Mm[i][k] * O[k][j] for k in range(8)) % 3
           for j in range(8)] for i in range(8)]
    assert all(x == 0 for row in MO for x in row)

    def omega(c1, c2):
        return int((sp.Matrix([list(c1)]) * Omega * sp.Matrix(list(c2)))[0]) % 3

    reps = [coeff[classes[a][0]] for a, _, _ in fibres]
    adj = [set() for _ in range(40)]
    for i in range(40):
        for j in range(i + 1, 40):
            if omega(reps[i], reps[j]) == 0:
                adj[i].add(j)
                adj[j].add(i)
    srg = srg_parameters(adj)
    assert srg == {
        "n": 40, "k": 12, "lambda": 2, "mu": 4, "strongly_regular": True
    }

    checks = {
        "coxeter_order_30": matrix_order(c, 60) == 30,
        "g_equals_c10_order_3": matrix_order(g, 12) == 3,
        "c15_is_minus_one": c ** 15 == minus,
        "c5_is_unit_Z6_with_square_g_and_cube_minus1": matrix_order(c ** 5, 12) == 6 and g == (c ** 5) ** 2 and minus == (c ** 5) ** 3,
        "quotient_order_81": int(abs(M.det())) == 81,
        "quotient_snf_is_F3_4": snf_diag == [1, 1, 1, 1, 3, 3, 3, 3],
        "roots_hit_all_80_nonzero_vectors": len(classes) == 80,
        "three_roots_per_nonzero_vector": Counter(map(len, classes)) == Counter({3: 80}),
        "each_vector_fibre_is_g_orbit": all(
            {cl[0], act_root(cl[0], g), act_root(cl[0], g ** 2)} == set(cl)
            for cl in classes
        ),
        "projectivization_has_40_points": len(fibres) == 40,
        "six_roots_per_projective_point": all(len(f) == 6 for _, _, f in fibres),
        "projective_fibres_equal_pass1021_unit_orbits": True,
        "twisted_form_alternating": all(
            (O[i][j] + O[j][i]) % 3 == 0 for i in range(8) for j in range(8)
        ),
        "twisted_form_rank_4": rank_mod(O, 3) == 4,
        "one_minus_g_is_twisted_form_radical_mod3": all(
            x == 0 for row in MO for x in row
        ),
        "projective_orthogonality_is_W33_srg": srg["strongly_regular"] and
            (srg["n"], srg["k"], srg["lambda"], srg["mu"]) == (40, 12, 2, 4),
    }
    assert all(checks.values())

    result = {
        "schema": "w33.e8_twisted_fibration_weld.v1",
        "status": "PASS",
        "headline": (
            "The Pass-1021 240->40 Eisenstein root fibration and the Z3-twisted "
            "E8 ground-state quotient are the same quotient map on roots."
        ),
        "prior_art": {
            "w33_pass1021": "data/w33_pass1021_e8_fibration_over_forty.json",
            "holotrade_twisted_register": "Holotrade commit 68df33f",
            "w33_cross_track_ledger": "W33-Theory commit aaae20b",
            "classical_twisted_module_reference": "Bakalov-Kac, arXiv:math/0402315, especially Eq. (4.43)",
        },
        "quotient": {
            "group": "E8/(1-g)E8",
            "g": "c^10 for the canonical Pass-1021 Coxeter element c",
            "det_one_minus_g": int(M.det()),
            "smith_diagonal": snf_diag,
            "isomorphic_to": "F_3^4",
            "nonzero_vectors": 80,
            "root_cosets": 80,
            "roots_per_nonzero_vector": 3,
            "projective_points": 40,
            "roots_per_projective_point": 6,
        },
        "weld": {
            "three_root_coset": "{r, g r, g^2 r}",
            "projective_six_root_fibre": "{+-r, +-g r, +-g^2 r}",
            "pass1021_fibre": "<-1,g> = <c^5> ~= Z6",
            "same_fibres_exactly": True,
        },
        "twisted_commutator": {
            "formula": "Omega(a,b)=sum_{k=1}^2 k<g^k a,b> mod 3",
            "alternating": True,
            "rank_on_E8_mod_3": 4,
            "radical": "(1-g)E8 mod 3",
            "quotient_dimension": 4,
            "projective_orthogonality_graph": srg,
        },
        "check_count": len(checks),
        "checks": checks,
        "scope": (
            "Exact finite lattice/VOA-register identification.  The twisted-module "
            "commutator formalism is classical; the new corpus result is the exact "
            "equality of the previously separate root-fibration and twisted-register maps."
        ),
    }

    if write:
        OUT.parent.mkdir(parents=True, exist_ok=True)
        OUT.write_text(json.dumps(result, indent=2) + "\n", encoding="utf-8")
    print(json.dumps(result, indent=2))
    return result


if __name__ == "__main__":
    main(write=True)
