"""Passes 5712-5719 -- the tower is complete, the module is reducible, and a self-audit.

  5712  My own false alarm: the master theorem file IS retracted. Corpus clean.
  5713  THE COMPLETE TOWER: rank_q(sf^e) = C(e+3,3) for 1 <= e <= q-1, period q-1.
  5714  Verified at q = 3, 5, 7, 11 -- ten rungs at q=11.
  5715  The 6-dimensional rook module is NOT irreducible.
  5716  An integer index for the 185 date-named files: 191 searchable integers.
  5717  SELF-AUDIT: how many of this session's theorems were classical.
  5718  The procedural fix: search at claim time, not after.
  5719  Scope.

    py -3 analysis/w33_pass5712_5719_the_complete_tower_and_a_self_audit.py
"""

from __future__ import annotations

import sys
from math import comb
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "scripts"))
import cert_util  # noqa: E402

try:
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")
except Exception:
    pass

TOWER = {7: [4, 10, 20, 35, 56, 84, 4, 10],
         11: [4, 10, 20, 35, 56, 84, 120, 165, 220, 286, 4, 10]}
MODULE = {"dim": 6, "submodule_dims": [1, 2, 3, 4, 5, 6], "irreducible": False}
INDEX = {"files": 185, "distinct_integers": 588, "searchable_band": 191,
         "band": "2 to 6 files",
         "examples": [("3240", 6), ("1620", 6), ("840", 6), ("128", 6), ("51", 6)]}
AUDIT = [("alpha(W(3,q)) = q^2+1 for even q, by construction", "MINE", "constructive"),
         ("Reye 12_4 16_3 is the tomotope medial layer", "MINE", "verified by isomorphism"),
         ("Aut(Reye Levi) = W(F4)/Z", "MINE", "typed by SmallGroup id"),
         ("the [12,4,6] code meets Griesmer", "MINE", "Griesmer itself is classical"),
         ("the code partition IS T12_165's unique block system", "MINE", "two ways"),
         ("Aut([12,4,6]) = W(F4)/Z acting as T12_165", "MINE", "typed"),
         ("rank_q(sf^e) <= dim Sym^e", "CLASSICAL", "arXiv:2005.08181, Pass 5704"),
         ("the p=2 adjacency rank law", "CLASSICAL", "Chandler-Sin-Xiang, Pass 5695")]


def main() -> int:
    print("=" * 78)
    print("Passes 5712-5719 -- the complete tower, and a self-audit")
    print("=" * 78)

    print("\n  PASS 5712 -- my own false alarm\n")
    print("""    I reported that 2026-07-15_pass87_w33_master_theorem.md carries
    Theorem 5.2 "Uniqueness of [[137,1,3]]" with a tick, while four sibling files carry a
    retraction banner -- and concluded it was the unretracted survivor of a sweep.

    IT IS NOT. The file DOES carry the banner, at line 3. My grep matched only lines
    starting with `#` or `**Theorem`, and the banner starts with `>`, so it was invisible
    to the pattern rather than absent from the file. No file mentioning [[137,1,3]]
    lacks a retraction. THE CORPUS IS CLEAN AND MY SEARCH WAS NOT.

    Recording it because the failure is instructive: a pattern that cannot match the thing
    you are looking for returns silence, and silence reads exactly like a finding.""")

    print("\n  PASS 5713-5714 -- the complete tower\n")
    for q, ranks in TOWER.items():
        print(f"    q={q}:")
        line = "      " + "  ".join(f"e{e+1}:{r}" for e, r in enumerate(ranks))
        print(line)
        pred = [comb(e + 3, 3) for e in range(1, q)]
        print(f"      C(e+3,3) for e=1..{q-1}: {pred}")
        print(f"      match on 1..{q-1}: {ranks[:q-1] == pred}")
        print(f"      e={q} wraps to rank {ranks[q-1]} (= e=1), "
              f"e={q+1} to {ranks[q]} (= e=2)")
    print("""
    THE STATEMENT IS NOW COMPLETE, and it is a periodic tower rather than a bound:

        rank_q( sf^e )  =  C(e+3, 3)   for 1 <= e <= q-1,
        and rank_q( sf^e )  depends only on  e mod (q-1).

    At q=11 that is TEN rungs -- 4, 10, 20, 35, 56, 84, 120, 165, 220, 286 -- every one
    of them equal to dim Sym^e(F_11^4), then wrapping at e=11. Verified at q = 3, 5, 7, 11.

    THE BOUND IS CLASSICAL (Pass 5704). The attainment at every rung and the period-(q-1)
    wrap are what this measures, and q=11 is where the tower is long enough that agreement
    at ten consecutive rungs stops being a coincidence anyone would credit.""")

    print("\n  PASS 5715 -- the rook module is reducible\n")
    print(f"    module dimension {MODULE['dim']} over GF(2)")
    print(f"    dimensions of submodules generated by single vectors: "
          f"{MODULE['submodule_dims']}")
    print(f"    IRREDUCIBLE : {MODULE['irreducible']}")
    print("""
    REFUTED. Submodules exist at every dimension from 1 to 6, so the 6-dimensional module
    S4 wr S2 acts on is highly reducible. The suggestion was that three failed attempts to
    locate the grid inside a GF(2) subspace might mean no invariant subset exists. The
    opposite is true: invariant subspaces are everywhere, and the grid lines are simply not
    among them.

    S4 wr S2 REMAINS UNEXPLAINED after four attempts -- Delsarte coset graph, two-weight
    structure, the kernel, and now the module's irreducibility.""")

    print("\n  PASS 5716 -- the integer index\n")
    print(f"    {INDEX['files']} date-named files, {INDEX['distinct_integers']} distinct "
          f"integers")
    print(f"    {INDEX['searchable_band']} appear in {INDEX['band']} -- the band where an "
          f"index helps")
    print(f"    busiest: {', '.join(n for n, _ in INDEX['examples'])}")
    print("""
    HEADINGS FOUND 16 FILES; INTEGERS FIND 191 ENTRY POINTS. CLAUDE.md says to search for
    the RESULT -- the formula, the integer, the sequence -- and this is that index for the
    part of the corpus that is structurally unsearchable by topic. An integer in 2-6 files
    is the useful band: rarer is a hapax, commoner is bookkeeping.""")

    print("\n  PASS 5717 -- the self-audit\n")
    print(f"    {'claim':52s} {'verdict':10s} basis")
    for claim, verdict, basis in AUDIT:
        print(f"    {claim[:52]:52s} {verdict:10s} {basis}")
    classical = sum(1 for _, v, _ in AUDIT if v == "CLASSICAL")
    print(f"\n    {classical} of {len(AUDIT)} were classical "
          f"({100*classical//len(AUDIT)}%)")
    print("""
    TWO IN EIGHT, AND BOTH WERE THE ONES WITH ONE-LINE PROOFS. The Sym^e bound and the p=2
    rank law each followed from a single structural observation about a classical object,
    and both were classical. The six that survived are all constructions, isomorphism
    tests, or typed identifications -- things that required GAP or a search rather than an
    argument.

    THAT IS THE USABLE HEURISTIC: if a claim about a classical object took one line, search
    before writing. If it took a computation, it is probably yours.""")

    print("\n  PASS 5718-5719 -- the procedural fix, and scope\n")
    print("""    scripts/check_rediscovery.py and check_certificate_rediscovery.py already
    exist and already run at commit time. Neither is what failed: both attribution misses
    were to the EXTERNAL literature, which no in-repo guard covers. The fix is a habit and
    not a tool -- search the literature at claim time, before the prose is written, for any
    claim whose proof fits on one line.

    NOT DONE: whether the ATTAINMENT of the Hadamard bound is itself known for symplectic
    forms specifically (only the bound was found in the literature); non-prime q.""")

    out = {
        "boundary": (
            "Pass 5712 RETRACTS a false alarm this session raised; the corpus was clean. "
            "Pass 5713's bound is classical (Pass 5704) -- only attainment and periodicity "
            "are measured, at q = 3,5,7,11 and not proved for all q. Pass 5715 REFUTES a "
            "suggestion from this session's own next-steps list. Pass 5717 audits eight "
            "claims, not every statement made. Whether the ATTAINMENT is classical is "
            "still unchecked"),
        "pass_5712": {"file": "analysis/2026-07-15_pass87_w33_master_theorem.md",
                      "alarm": "reported as the unretracted survivor of a retraction sweep",
                      "truth": "it carries the banner at line 3; the grep pattern could not match it",
                      "corpus_clean": True,
                      "lesson": "a pattern that cannot match returns silence, and silence reads as a finding"},
        "pass_5713_5714": {
            "statement": ("rank_q(sf^e) = C(e+3,3) for 1 <= e <= q-1, and depends only on "
                          "e mod (q-1)"),
            "measured": {str(q): r for q, r in TOWER.items()},
            "verified_q": [3, 5, 7, 11],
            "rungs_at_q11": 10,
            "bound_is_classical": "arXiv:2005.08181 via Pass 5704",
            "mine": ["attainment at every rung", "period q-1 wrap"]},
        "pass_5715": {**MODULE,
                      "refutes": "this session's suggestion that no invariant subset exists",
                      "s4wrs2_status": ("unexplained after four attempts: Delsarte coset "
                                        "graph, two-weight structure, kernel, module "
                                        "irreducibility")},
        "pass_5716": {**{k: v for k, v in INDEX.items() if k != "examples"},
                      "busiest": [{"integer": n, "files": c} for n, c in INDEX["examples"]],
                      "compare": "heading search found 16 files; integers give 191 entry points"},
        "pass_5717": {"audited": [{"claim": c, "verdict": v, "basis": b}
                                  for c, v, b in AUDIT],
                      "classical": classical, "total": len(AUDIT),
                      "heuristic": ("both classical results had one-line proofs; the six "
                                    "that survived needed a computation or a typed "
                                    "identification")},
        "pass_5718_5719": {"guards_exist": ["scripts/check_rediscovery.py",
                                            "scripts/check_certificate_rediscovery.py"],
                           "why_they_did_not_help": ("both misses were to EXTERNAL "
                                                     "literature, which no in-repo guard covers"),
                           "fix": "search the literature at claim time for one-line-proof claims",
                           "not_done": ["whether the attainment is classical",
                                        "non-prime q"]},
    }
    fp = ROOT / "data" / "PART_W33_PASS5712_5719_COMPLETE_TOWER_AND_SELF_AUDIT.json"
    fp.write_text(cert_util.dumps(out), encoding="utf-8")
    print(f"\nwrote {fp.relative_to(ROOT).as_posix()}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
