#!/usr/bin/env python3
from pathlib import Path
import json,hashlib,collections,itertools
ROOT=Path(__file__).resolve().parents[1];Q=3
def norm(v):
 v=tuple(x%Q for x in v)
 for x in v:
  if x:return tuple((pow(x,-1,Q)*y)%Q for y in v)
def sp(u,v):return (u[0]*v[3]-u[3]*v[0]+u[1]*v[2]-u[2]*v[1])%Q
def graph():
 pts=sorted({norm(v) for v in itertools.product(range(Q),repeat=4) if any(v)});pi={p:i for i,p in enumerate(pts)};A=[[i!=j and sp(pts[i],pts[j])==0 for j in range(40)] for i in range(40)];L=set()
 for i,j in itertools.combinations(range(40),2):
  if not A[i][j]:continue
  S=set()
  for a,b in itertools.product(range(3),repeat=2):
   w=tuple((a*pts[i][k]+b*pts[j][k])%3 for k in range(4))
   if any(w):S.add(pi[norm(w)])
  L.add(tuple(sorted(S)))
 lines=sorted(L);wedges=[(i,j) for i,j in itertools.combinations(range(40),2) if A[i][j]];ei={e:k for k,e in enumerate(wedges)};F=[]
 for a,b in itertools.combinations(range(40),2):
  if set(lines[a])&set(lines[b]):continue
  m=[]
  for x in lines[a]:
   y=next(y for y in lines[b] if A[x][y]);m.append(ei[tuple(sorted((x,y)))])
  F.append(set(m))
 E=set()
 for e in range(240):
  C=[i for i,f in enumerate(F) if e in f];assert len(C)==9;E.update(tuple(sorted(x)) for x in itertools.combinations(C,2))
 return E
def digest(d):
 x=dict(d);x.pop('sha256_without_hash_field',None);return hashlib.sha256(json.dumps(x,sort_keys=True,separators=(',',':')).encode()).hexdigest()
def main():
 E=graph();q=(ROOT/'data/w33_pass2561_coloring11.txt').read_text().split();K=int(q[0]);c=list(map(int,q[1:]));old=json.loads((ROOT/'data/w33_pass2551_complete_cover_link_k8_refutation.json').read_text())
 out={'schema':'w33.pass2561.chromatic_interval_10_11.v1','status':'PASS_EXACT_ELEVEN_COLORING_WITH_NINE_REFUTED','graph':{'vertices':540,'edges':len(E)},'chromatic':{'proved_lower_bound':old['chromatic_consequence']['proved_lower_bound'],'explicit_upper_bound':K,'color_class_sizes':dict(collections.Counter(c)),'coloring':c},'coordinate_convention':'canonical symplectic point-line frame ordering generated by the verifier; no frozen-ordering sidecar required','checks':{'length540':len(c)==540,'colors_0_10':min(c)==0 and max(c)==10,'all_8640_edges_proper':len(E)==8640 and all(c[a]!=c[b] for a,b in E),'lower_bound10':old['chromatic_consequence']['proved_lower_bound']==10},'theorem':'The frozen 540-frame graph has a literal proper eleven-colouring. Together with the complete Pass-2551 refutation of nine-colourability, this gives 10 <= chi(H) <= 11.','boundary':'The exact choice between 10 and 11 remains open; unsuccessful bounded ten-colour searches are not mathematical evidence.'}
 assert all(out['checks'].values());out=json.loads(json.dumps(out,sort_keys=True,separators=(',',':')));out['sha256_without_hash_field']=digest(out);(ROOT/'data/w33_pass2561_chromatic_interval_10_11.json').write_text(json.dumps(out,sort_keys=True,separators=(',',':'))+'\n');print(out['sha256_without_hash_field'])
if __name__=='__main__':main()
