#!/usr/bin/env python3
"""Physicalize the old qutrit-Heisenberg center as the measured E8 FI Z3.

Passes 5727/5730 already construct on the E8 family C^3 multiplicity factor
the qutrit Schrödinger pair

    X|j> = |j+1>,      Z|j> = omega^j |j>,

with ZX = omega XZ and <X,Z> = H_27.  Their center is generated by
z = omega I_3.

The newer physical-FI theorem independently identifies the measured organizer-
E8 FI projection with the central SU(3) element on

    248 = (78,1) + (1,8) + (27,3) + (27bar,3bar),

so it acts as 1,1,omega,omega^2 on those four blocks.  The Qpsi theorem proves
that this same action is exp(2*pi*i*Qpsi/3).

This file closes exactly the finite central-character identification:

    z_H27 = z_FI = exp(2*pi*i*Qpsi/3)

on the E8 family multiplicity factor and its conjugate.

It does NOT identify the entire affine/torsion SU(3) construction of the old
passes with a low-energy gauge algebra, nor does it solve D/F flatness.
"""
from __future__ import annotations
import json
from pathlib import Path

ROOT=Path(__file__).resolve().parents[1]
OUT=ROOT/"data/w33_physical_fi_is_h27_center.json"

# H27 normal form: Z^a X^b omega^c, (a,b,c) in F3^3.
# ZX=omega XZ gives
#   (a,b,c)(a',b',c')=(a+a',b+b',c+c' - b*a') mod3
# for this ordering convention.
def mul(g,h):
    a,b,c=g; A,B,C=h
    return ((a+A)%3,(b+B)%3,(c+C-b*A)%3)

def inv(g):
    for h in H:
        if mul(g,h)==I and mul(h,g)==I:return h
    raise AssertionError(g)

I=(0,0,0)
H=[(a,b,c) for a in range(3) for b in range(3) for c in range(3)]

def comm(g,h):
    return mul(mul(mul(g,h),inv(g)),inv(h))

def main(write=True):
    old_src=(ROOT/"analysis/w33_pass5727_5730_torsion_family_heisenberg.py").read_text()
    assert "Z=np.diag([1,w,w*w])" in old_src
    assert "X=np.array([[0,0,1],[1,0,0],[0,1,0]],complex)" in old_src
    assert "'commutation':'Z X = omega X Z'" in old_src
    assert "'generated_group_order':27" in old_src

    fi=json.loads((ROOT/"data/w33_physical_fi_e6_a2_z3_grading.json").read_text())
    qpsi=json.loads((ROOT/"data/w33_qpsi_mod12_unification.json").read_text())
    split=json.loads((ROOT/"data/w33_e8_a2_center_vs_coxeter_order3.json").read_text())
    assert fi["status"]=="PASS_PHYSICAL_FI_REALIZES_E6_A2_Z3_GRADING"
    assert qpsi["status"]=="PASS_SINGLE_INTEGER_QPSI_UNIFIES_E8_Z2_Z3_Z4_Z6_Z12"
    assert split["status"]=="PASS_PHYSICAL_A2_CENTER_AND_PASS1147_COXETER_ARE_DISTINCT_E8_ORDER3_CLASSES"

    # Exact abstract H27 checks.
    assert len(H)==27 and len(set(H))==27
    assert all(mul(g,I)==g and mul(I,g)==g for g in H)
    assert all(mul(mul(g,h),k)==mul(g,mul(h,k)) for g in H for h in H for k in H)
    X=(0,1,0); Z=(1,0,0); omegaI=(0,0,1)
    # With our Z^a X^b convention, [Z,X]=omega and ZX=omega XZ.
    assert comm(Z,X)==omegaI
    center=[g for g in H if all(mul(g,h)==mul(h,g) for h in H)]
    assert center==[(0,0,0),(0,0,1),(0,0,2)]
    assert {mul(g,g) for g in H if g!=I}  # smoke: nontrivial group law
    assert all(mul(mul(g,g),g)==I for g in H)  # exponent 3

    # Physical E8 center character.
    assert fi["E8"]["root_grades"]=={"0":78,"1/3":81,"2/3":81}
    assert qpsi["residue_dimensions"]["mod3_CE2_and_physical_FI"]==[86,81,81]
    p=split["physical_FI_center_Z3"]
    assert p["adjoint_eigendimensions"]==[86,81,81]
    assert p["fixed_reductive_algebra"]=="E6+A2"

    # On the family factor 3, z=omega I.  The conjugate 3bar has omega^2.
    blocks={
      "(78,1)":0,
      "(1,8)":0,
      "(27,3)":1,
      "(27bar,3bar)":2,
    }
    dims={"(78,1)":78,"(1,8)":8,"(27,3)":81,"(27bar,3bar)":81}
    eig=[sum(dims[k] for k,g in blocks.items() if g==j) for j in range(3)]
    assert eig==[86,81,81]

    # Qpsi mod3 is the same central character channelwise.
    for channel,meta in qpsi["channel_mod3_certificate"].items():
        assert meta["all_charges_match_grade_mod3"] is True
    assert qpsi["channel_mod3_certificate"]["g1"]["grade"]==1
    assert qpsi["channel_mod3_certificate"]["g2"]["grade"]==2

    out={
      "schema":"w33.physical_fi_is_h27_center.v1",
      "status":"PASS_PHYSICAL_FI_Z3_EQUALS_QUTRIT_HEISENBERG_CENTER_CHARACTER",
      "headline":"The qutrit H27 center already acting on the E8 family C^3 factor is exactly the newly certified physical FI Z3 central character. In the Pass5727 Schrödinger convention ZX=omega XZ, [Z,X]=omega I; the measured FI action is the same omega I on (27,3), omega^2 I on (27bar,3bar), and identity on E6+A2. Hence z_H27=z_FI=exp(2*pi*i Qpsi/3) as an E8 central-character action.",
      "H27":{
        "order":27,"exponent":3,"center_order":3,
        "normal_form":"Z^a X^b omega^c",
        "weyl_relation":"Z X = omega X Z",
        "commutator":"[Z,X]=omega I",
        "center":[[0,0,0],[0,0,1],[0,0,2]],
        "faithful_schrodinger_dimension":3
      },
      "E8":{
        "branching":"248=(78,1)+(1,8)+(27,3)+(27bar,3bar)",
        "center_exponents":{"(78,1)":0,"(1,8)":0,"(27,3)":1,"(27bar,3bar)":2},
        "adjoint_eigendimensions":[86,81,81],
        "fixed_algebra":"E6+A2"
      },
      "identity":{
        "H27_center_generator":"omega I_3",
        "physical_FI_generator":"central SU(3) element omega I_3 on the family triplet",
        "Qpsi_form":"exp(2*pi*i*Qpsi/3)",
        "same_central_character":True
      },
      "what_this_upgrades":"Pass5727 previously proved a finite Heisenberg/projective torsion action on the E8 family multiplicity factor but left its physical family-center interpretation open. The measured FI/Qpsi theorem now identifies its scalar center exactly.",
      "what_remains_open":"The noncentral H27 generators X and Z are finite qutrit operators. This theorem does not identify the older affine Lie su(3) construction with the full E8 family SU(3) Lie algebra, prove a heterotic vacuum, or assign observed generations.",
      "parents":[
        "analysis/w33_pass5727_5730_torsion_family_heisenberg.py",
        "data/w33_physical_fi_e6_a2_z3_grading.json",
        "data/w33_qpsi_mod12_unification.json",
        "data/w33_e8_a2_center_vs_coxeter_order3.json"
      ],
      "checks":{
        "H27_group_law_exact":True,"H27_order_27":True,"H27_center_order_3":True,
        "commutator_is_center_generator":True,"physical_FI_spectrum_86_81_81":True,
        "Qpsi_mod3_matches_FI":True,"central_character_identified":True
      }
    }
    if write:OUT.write_text(json.dumps(out,indent=2)+"\n")
    print(json.dumps(out,indent=2));return out

if __name__=="__main__":main(True)
