#!/usr/bin/env python3
from __future__ import annotations
import itertools, json, sys
from collections import Counter
from pathlib import Path
import numpy as np

ROOT=Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0,str(ROOT))
OUT=ROOT/"data/w33_20260924_common_winding_orientation_chain_map.json"

from analysis.w33_20260924_history_invariant_cycle_orientation import (
    HS, EDGES, EIDX, TRIS, boundary_triangle,
)
from analysis.w33_20260924_positive_null_counter_cover import D, coords

VID={s:i for i,s in enumerate(HS)}

def add3(a,b):
    return tuple((int(a[i])+int(b[i]))%3 for i in range(3))

def signed_edge(chain,u,v,coef=1):
    a,b=VID[u],VID[v]
    if a<b:
        chain[EIDX[(a,b)]]+=coef
    else:
        chain[EIDX[(b,a)]]-=coef

def loop_from(s,directions):
    cur=s
    edges=[]
    for d in directions:
        nxt=add3(cur,d)
        edges.append((cur,nxt))
        cur=nxt
    assert cur==s
    return edges
def main():
    directions=[coords(M) for M in D]
    assert directions==[
        (1,0,0),(0,0,1),(1,1,1),(1,2,1)
    ]
    assert tuple(sum(d[i] for d in directions)%3 for i in range(3))==(0,0,0)

    loops=[]
    total=np.zeros(len(EDGES),dtype=int)
    direction_chains=[]
    for _ in directions:
        direction_chains.append(np.zeros(len(EDGES),dtype=int))

    for s in HS:
        edges=loop_from(s,directions)
        row=[]
        for j,(u,v) in enumerate(edges):
            signed_edge(total,u,v,1)
            signed_edge(direction_chains[j],u,v,1)
            row.append([VID[u],VID[v]])
        loops.append({"base_history":list(s),"directed_edges":row})

    assert np.count_nonzero(total)==108
    assert set(map(int,total))=={-1,1}
    supports=[set(np.flatnonzero(c)) for c in direction_chains]
    assert all(len(S)==27 for S in supports)
    assert len(set().union(*supports))==108
    assert all(not(a&b) for a,b in itertools.combinations(supports,2))

    old=json.loads(
        (ROOT/"data/w33_20260924_history_invariant_cycle_orientation.json").read_text()
    )
    invariant=np.array(old["invariant_cycle"]["edge_coefficients"],dtype=int)
    assert np.array_equal(total,invariant)
    # The same cycle is the boundary of the signed sum of all 36 temporal triangles.
    tri_sum=np.zeros(len(EDGES),dtype=int)
    for t in TRIS:
        tri_sum+=boundary_triangle(t)
    assert np.array_equal(tri_sum,total)

    h1=json.loads(
        (ROOT/"data/w33_20260924_history_to_global_h1_intertwiner.json").read_text()
    )
    assert h1["homology"]["kernel_is_exactly_history_triangle_boundary_space"] is True
    assert h1["homology"]["history_triangle_boundary_rank"]==36
    assert h1["homology"]["filled_history_H1_dimension"]==46

    cover=json.loads(
        (ROOT/"data/w33_20260924_positive_null_counter_cover.json").read_text()
    )
    assert cover["integer_cover"]["fundamental_winding_matrix"]==[[3,0],[0,3]]
    assert cover["integer_cover"]["trace_increment_per_winding"]==6

    # A chain map from the one-generator winding complex C1=Z, d=0:
    # generator 1 maps to total. Since div(total)=0 this is a valid chain map.
    div=np.zeros(27,dtype=int)
    for k,(i,j) in enumerate(EDGES):
        div[i]-=total[k]
        div[j]+=total[k]
    assert np.all(div==0)

    out={
      "schema":"w33.20260924.common_winding_orientation_chain_map.v1",
      "status":"PASS_COMMON_NULL_WINDING_ORBIT_SUM_EQUALS_GLOBAL_HISTORY_ORIENTATION_CYCLE",
      "source_winding":{
        "counter_generator":[1,1,1,1],
        "integer_lift":"D0+Dinf+Dplus+Dminus=3 I2",
        "trace_increment":6,
        "one_base_loop_length":4,
        "base_loop_closes_mod3":True,
      },
      "chain_map":{
        "source":"C1(S1;Z)=Z generated by one common four-null pulse",
        "target":"oriented edge cycle space of the 27-history null graph",
        "map":"w -> sum over all 27 translations of the four-step loop",
        "translated_loops":27,
        "directed_steps_total":108,
        "support_size":int(np.count_nonzero(total)),
        "coefficient_histogram":{str(k):v for k,v in Counter(map(int,total)).items()},
        "four_direction_supports":[len(S) for S in supports],
        "supports_partition_all_108_edges":True,
        "equals_preexisting_invariant_orientation_cycle":True,
        "vertex_boundary_zero":True,
      },
      "homology_resolution":{
        "triangle_identity":"Phi(w)=boundary(sum of all 36 oriented temporal triangles)",
        "filled_history_H1_class":"zero",
        "global_W33_H1_image_class":"zero under the certified history-to-global chain map",
        "reason":"the exact kernel on history cycles is the 36D temporal triangle-boundary space",
        "nontrivial_filled_history_H1_dimension":46,
        "interpretation":(
          "the monotone integer winding is the distinguished invariant orientation "
          "boundary, not one of the 46 nontrivial filled-history H1 modes"
        ),
      },
      "sample_loops":loops[:6],
      "theorem":(
        "One positive pulse in each of the four projective null directions is a "
        "closed four-edge loop after reduction mod 3. Summing its 27 translates "
        "uses every one of the 108 null-history edges exactly once with orientation, "
        "and the resulting chain is exactly the previously certified unique PSp-"
        "invariant orientation cycle. It is also exactly the boundary of the sum "
        "of all 36 temporal triangles. Therefore the integer-cover common winding "
        "maps canonically to the orientation cycle but dies in filled temporal H1 "
        "and hence in its injective global-W33 H1 image."
      ),
      "boundary":(
        "This closes the previously explicit chain-map gap. It also supplies a "
        "negative result: the common winding itself is homologically trivial once "
        "temporal triangles are filled. Any physical topological time observable "
        "must therefore use the unfilled cycle/orientation line or a different "
        "relative/cohomological construction."
      ),
    }
    OUT.write_text(json.dumps(out,indent=2,sort_keys=True)+"\n",encoding="utf-8")
    print(json.dumps({
      "status":out["status"],
      "support":out["chain_map"]["support_size"],
      "equals_orientation":out["chain_map"]["equals_preexisting_invariant_orientation_cycle"],
      "filled_H1":out["homology_resolution"]["filled_history_H1_class"],
    },indent=2,sort_keys=True))

if __name__=="__main__":
    main()
