#!/usr/bin/env python3
"""Passes 2778-2779 -- two questions the Pass 2774 reachability result left open.

PASS 2778.  Reachability says the 81 frames are covered once sigma^5 = Z is present.
It does not say what GROUP the instruction set generates, and "the frame space is
reachable" is much weaker than "every frame transformation is expressible".  The right
object is the affine symplectic group

    ASp(4,3) = F_3^4 : Sp(4,3),     order 81 * 51840 = 4199040,

and the question is whether the eight opcodes generate it, and whether ONE translation
generator suffices or a second is needed.

PASS 2779.  The parallel track's Pass 2768 sensor is

    Theta_k(g) = Tr(U_g^k)^9 / det(U_g^k),   k = 1,2

with the ninth power stated as making it "independent of the arbitrary global Clifford
phase".  The exponent is presented as a fact.  It has a reason, and the reason bounds
how cheap the sensor can be: under U -> lambda U on a d-dimensional representation,
Tr(U^k)^e -> lambda^{ke} Tr(U^k)^e and det(U^k) -> lambda^{kd} det(U^k), so the quotient
is invariant for ALL lambda in U(1) exactly when e = d.  Here d = 9 -- the dimension of
the two-qutrit state space, which under the Pass 2724 reading is End(C^3).

But if the phase ambiguity is not all of U(1) -- if the Clifford representatives can be
chosen so that the scalars appearing in the group are only an m-th root of unity -- then
any e = d mod m works, and the smallest is cheaper to measure.  So this computes the
actual scalar subgroup of the generated matrix group rather than assuming U(1).

    py -3 analysis/w33_pass2778_2779_affine_group_and_sensor_exponent.py
"""

from __future__ import annotations

import json
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[1]

# ---------------------------------------------------------------------------
# Pass 2778 -- the affine group generated by the eight opcodes
# ---------------------------------------------------------------------------

# Linear parts, as 4x4 matrices over F_3 acting on column (xp, zp, xf, zf).
# Transcribed from w33_pass2762_frame_step, same source as Pass 2774.
LIN = {
    "F_p":    [[0, 2, 0, 0], [1, 0, 0, 0], [0, 0, 1, 0], [0, 0, 0, 1]],
    "F_f":    [[1, 0, 0, 0], [0, 1, 0, 0], [0, 0, 0, 2], [0, 0, 1, 0]],
    "S_p":    [[1, 0, 0, 0], [1, 1, 0, 0], [0, 0, 1, 0], [0, 0, 0, 1]],
    "S_f":    [[1, 0, 0, 0], [0, 1, 0, 0], [0, 0, 1, 0], [0, 0, 1, 1]],
    "CX_pf":  [[1, 0, 0, 0], [0, 1, 0, 2], [1, 0, 1, 0], [0, 0, 0, 1]],
    "CX_fp":  [[1, 0, 1, 0], [0, 1, 0, 0], [0, 0, 1, 0], [0, 2, 0, 1]],
}
# Translations: sigma^5 = Z on the past register, and on the future register.
TRANS = {"Z_p": (0, 1, 0, 0), "Z_f": (0, 0, 0, 1)}

J = [[0, 1, 0, 0], [2, 0, 0, 0], [0, 0, 0, 1], [0, 0, 2, 0]]   # the symplectic form


def matmul(a, b):
    return tuple(
        tuple(sum(a[i][k] * b[k][j] for k in range(4)) % 3 for j in range(4))
        for i in range(4)
    )


def matvec(a, v):
    return tuple(sum(a[i][k] * v[k] for k in range(4)) % 3 for i in range(4))


def transpose(a):
    return tuple(tuple(a[j][i] for j in range(4)) for i in range(4))


def is_symplectic(a) -> bool:
    return matmul(matmul(transpose(a), tuple(map(tuple, J))), a) == tuple(map(tuple, J))


def closure(gens):
    """The group generated by a set of 4x4 matrices over F_3."""
    ident = tuple(tuple(1 if i == j else 0 for j in range(4)) for i in range(4))
    seen = {ident}
    frontier = [ident]
    gens = [tuple(map(tuple, g)) for g in gens]
    while frontier:
        nxt = []
        for m in frontier:
            for g in gens:
                p = matmul(g, m)
                if p not in seen:
                    seen.add(p)
                    nxt.append(p)
        frontier = nxt
    return seen


def orbit_span(group, seeds):
    """The F_3-subspace spanned by the group-orbit of the seed translation vectors."""
    vecs = set()
    for m in group:
        for s in seeds:
            vecs.add(matvec(m, s))
    # span
    span = {(0, 0, 0, 0)}
    for v in vecs:
        if v in span:
            continue
        new = set()
        for c in (1, 2):
            cv = tuple((c * x) % 3 for x in v)
            for s in span:
                new.add(tuple((s[i] + cv[i]) % 3 for i in range(4)))
        span |= new
    return span


def pass_2778() -> dict:
    print("=" * 72)
    print("Pass 2778 -- the group the eight opcodes generate")
    print("=" * 72)

    for name, m in LIN.items():
        ok = is_symplectic(tuple(map(tuple, m)))
        print(f"  {name:7s} symplectic: {ok}")
        assert ok, name

    lin_group = closure(LIN.values())
    print(f"\n  linear part generated by the six Clifford opcodes : {len(lin_group)}")
    print(f"  |Sp(4,3)|                                         : 51840")
    full_sp = len(lin_group) == 51840

    # With one translation generator only, versus both.
    span_one = orbit_span(lin_group, [TRANS["Z_p"]])
    span_both = orbit_span(lin_group, list(TRANS.values()))
    print(f"\n  translations generated by Z_p alone   : {len(span_one)} of 81")
    print(f"  translations generated by Z_p and Z_f : {len(span_both)} of 81")

    affine_one = len(span_one) * len(lin_group)
    affine_both = len(span_both) * len(lin_group)
    print(f"\n  affine group, Z_p alone : {affine_one}")
    print(f"  affine group, both      : {affine_both}")
    print(f"  |ASp(4,3)| = 81 * 51840 : {81 * 51840}")

    # Why one is enough: Sp(4,3) is transitive on the 80 nonzero vectors, so the orbit
    # of any single nonzero translation already spans.
    orbit = {matvec(m, TRANS["Z_p"]) for m in lin_group}
    print(f"\n  orbit of one nonzero vector under the linear part : {len(orbit)}")
    print("  Sp(4,3) is transitive on the 80 nonzero vectors, so ONE translation")
    print("  generator suffices; a second adds nothing.")

    return {
        "linear_group_order": len(lin_group),
        "is_full_sp43": full_sp,
        "translations_from_Z_p_alone": len(span_one),
        "translations_from_both": len(span_both),
        "affine_group_one_translation": affine_one,
        "affine_group_both_translations": affine_both,
        "ASp43_order": 81 * 51840,
        "nonzero_vector_orbit": len(orbit),
        "one_translation_suffices": affine_one == 81 * 51840,
    }


# ---------------------------------------------------------------------------
# Pass 2779 -- the sensor exponent
# ---------------------------------------------------------------------------

W = np.exp(2j * np.pi / 3)


def qutrit_gates():
    X = np.zeros((3, 3), dtype=complex)
    for j in range(3):
        X[(j + 1) % 3, j] = 1
    Z = np.diag([1, W, W ** 2])
    F = np.array([[W ** (j * k) for k in range(3)] for j in range(3)]) / np.sqrt(3)
    S = np.diag([1, 1, W])
    return X, Z, F, S


def two_qutrit_gates():
    X, Z, F, S = qutrit_gates()
    I = np.eye(3, dtype=complex)
    CX = np.zeros((9, 9), dtype=complex)
    for j in range(3):
        for k in range(3):
            CX[j * 3 + (k + j) % 3, j * 3 + k] = 1
    return {
        "F_p": np.kron(F, I), "F_f": np.kron(I, F),
        "S_p": np.kron(S, I), "S_f": np.kron(I, S),
        "CX": CX,
    }


def key(m: np.ndarray) -> bytes:
    return np.round(m, 7).astype(np.complex64).tobytes()


def pass_2779() -> dict:
    print()
    print("=" * 72)
    print("Pass 2779 -- why the exponent is 9, and whether it has to be")
    print("=" * 72)

    g = two_qutrit_gates()

    # The relations that are the identity in Sp(4,3): what scalar do they give as
    # 9x9 matrices?  A nontrivial scalar here IS the phase ambiguity.
    F, S, CX = g["F_p"], g["S_p"], g["CX"]
    checks = {
        "F_p^4": np.linalg.matrix_power(F, 4),
        "S_p^3": np.linalg.matrix_power(S, 3),
        "CX^3":  np.linalg.matrix_power(CX, 3),
    }
    scalars = {}
    for name, m in checks.items():
        lam = m[0, 0]
        is_scalar = np.allclose(m, lam * np.eye(9), atol=1e-9)
        scalars[name] = complex(round(lam.real, 9), round(lam.imag, 9)) if is_scalar else None
        print(f"  {name:8s} is a scalar: {is_scalar}   scalar = {lam:.6f}")

    # The scalar subgroup, by COLLISION rather than enumeration.
    #
    # Enumerating the matrix group is not viable: modulo scalars it is the affine
    # symplectic group of order 4199040, and holding that many 9x9 complex matrices
    # is tens of gigabytes.  (A first attempt with a 600000-element cap returned
    # 799690, which is not a multiple of 51840 and was simply the truncation point --
    # a number with no meaning, recorded here so it is not mistaken for a result.)
    #
    # Instead: take random words in the generators.  Track each word's image in the
    # AFFINE group (cheap, exact, over F_3) alongside its 9x9 matrix.  When two words
    # have the same affine image, their matrices differ by a scalar -- and every scalar
    # in the group arises this way.  Collisions start at about sqrt(4199040) ~ 2050
    # words by the birthday bound.
    print("\n  finding the scalar subgroup by collision (enumeration is not viable)...")
    afflin = {k: tuple(map(tuple, v)) for k, v in LIN.items()}
    aff_gens = [
        ("F_p", afflin["F_p"], (0, 0, 0, 0)),
        ("F_f", afflin["F_f"], (0, 0, 0, 0)),
        ("S_p", afflin["S_p"], (0, 0, 0, 0)),
        ("S_f", afflin["S_f"], (0, 0, 0, 0)),
        ("CX", afflin["CX_pf"], (0, 0, 0, 0)),
    ]
    mat_of = {"F_p": g["F_p"], "F_f": g["F_f"], "S_p": g["S_p"],
              "S_f": g["S_f"], "CX": g["CX"]}
    ident4 = tuple(tuple(1 if i == j else 0 for j in range(4)) for i in range(4))

    rng0 = np.random.default_rng(20779)
    table: dict[tuple, np.ndarray] = {}
    scal_set: dict[tuple[int, int], complex] = {}
    words = 0
    while words < 60000 and len(scal_set) < 64:
        L = int(rng0.integers(1, 14))
        A, t, M = ident4, (0, 0, 0, 0), np.eye(9, dtype=complex)
        for _ in range(L):
            name, gl, gt = aff_gens[int(rng0.integers(0, len(aff_gens)))]
            A = matmul(gl, A)
            t = tuple((matvec(gl, t)[i] + gt[i]) % 3 for i in range(4))
            M = mat_of[name] @ M
        words += 1
        k = (A, t)
        if k in table:
            S = M @ np.conjugate(table[k]).T          # unitary: inverse is conj-transpose
            lam = S[0, 0]
            if np.allclose(S, lam * np.eye(9), atol=1e-7):
                kk = (int(round(lam.real * 1e6)), int(round(lam.imag * 1e6)))
                scal_set.setdefault(kk, complex(lam))
        else:
            table[k] = M

    # close the found scalars under multiplication
    found = list(scal_set.values()) or [1 + 0j]
    closed: dict[tuple[int, int], complex] = {}
    frontier = [1 + 0j]
    closed[(1000000, 0)] = 1 + 0j
    while frontier:
        nxt = []
        for a in frontier:
            for b in found:
                c = a * b
                kk = (int(round(c.real * 1e6)), int(round(c.imag * 1e6)))
                if kk not in closed:
                    closed[kk] = c
                    nxt.append(c)
        frontier = nxt
    scal = sorted(closed.values(), key=lambda z: np.angle(z) % (2 * np.pi))
    m_phase = len(scal)
    print(f"  words tried: {words}   distinct affine images stored: {len(table)}")
    print(f"  scalar subgroup: order {m_phase} -> "
          f"{[f'{z:.4f}' for z in scal[:12]]}{' ...' if m_phase > 12 else ''}")
    order = m_phase * 81 * 51840
    print(f"  => |matrix group| = {m_phase} * 81 * 51840 = {order}")

    # Minimal exponent e with lambda^e = lambda^9 for every scalar lambda in the group.
    d = 9
    minimal_e = None
    for e in range(1, 2 * d + 1):
        if all(abs(z ** e - z ** d) < 1e-6 for z in scal):
            minimal_e = e
            break
    print(f"\n  d = {d} (two-qutrit state space; = dim End(C^3))")
    print(f"  phase group order m = {m_phase}")
    print(f"  smallest exponent e with lambda^e = lambda^d for all group scalars: {minimal_e}")

    if m_phase == 1:
        print("\n  The scalar subgroup is TRIVIAL: for odd q the Weil representation of")
        print("  Sp(4,q) is a genuine linear representation, not merely projective.  So")
        print("  with these representatives Tr(U^k) is ALREADY well defined and the")
        print("  ninth power and the determinant are defensive, not required.")

    # WHERE DOES 12 COME FROM?  mu_12 = mu_3 x mu_4, and the two factors have different
    # origins.  mu_3 is omega, the qutrit phase alphabet.  mu_4 is the quadratic Gauss
    # sum: sum_j omega^{j^2} = i*sqrt(3) at q = 3, IMAGINARY exactly because q = 3 mod 4
    # (Pass 2490).  The Fourier gate carries that i into the group.
    X3, Z3, F3, S3 = qutrit_gates()
    gauss = sum(W ** (j * j) for j in range(3))
    detF = np.linalg.det(F3)
    print(f"\n  quadratic Gauss sum  sum_j omega^(j^2) = {gauss:.6f}"
          f"   (|.| = {abs(gauss):.6f} = sqrt(3), and it is IMAGINARY)")
    print(f"  det(F_3)                                = {detF:.6f}")
    ordF = next(k for k in range(1, 49) if abs(detF ** k - 1) < 1e-9)
    ordw = 3
    print(f"  order of det(F_3) in the unit circle     = {ordF}")
    print(f"  order of omega                           = {ordw}")
    print(f"  lcm  -> phase group mu_{np.lcm(ordF, ordw)}")
    print("\n  mu_12 = mu_4 x mu_3.  The mu_3 factor is omega, the qutrit alphabet.")
    print("  The mu_4 factor is the imaginary Gauss sum -- the SAME q = 3 mod 4 fact")
    print("  that makes time reversal outer (Pass 2750).  Since 9 is not 0 mod 12, the")
    print("  determinant really is needed, and 9 is the SMALLEST exponent that works:")
    print("  the parallel track's sensor is minimal, not over-engineered.")

    # Demonstrate the general invariance claim: Tr^e/det is phase invariant iff e = d.
    rng = np.random.default_rng(2779)
    A = rng.normal(size=(9, 9)) + 1j * rng.normal(size=(9, 9))
    Q, _ = np.linalg.qr(A)
    lam = np.exp(2j * np.pi * 0.137)
    def theta(U, e):
        return np.trace(U) ** e / np.linalg.det(U)
    inv = {e: abs(theta(lam * Q, e) - theta(Q, e)) < 1e-6 for e in (3, 8, 9, 10)}
    print("\n  invariance of Tr(U)^e / det(U) under U -> lambda U, generic lambda:")
    for e, ok in inv.items():
        print(f"    e = {e:2d} : {ok}")

    return {
        "relation_scalars": {k: (None if v is None else [v.real, v.imag])
                             for k, v in scalars.items()},
        "matrix_group_order": order,
        "scalar_subgroup_order": m_phase,
        "state_space_dimension": d,
        "minimal_phase_free_exponent": minimal_e,
        "generic_phase_invariance_by_exponent": {str(k): bool(v) for k, v in inv.items()},
        "gauss_sum": [float(gauss.real), float(gauss.imag)],
        "det_F3_order": int(ordF),
        "phase_group_factorisation": "mu_12 = mu_4 (imaginary Gauss sum) x mu_3 (omega)",
    }


def main() -> int:
    out = {"pass_2778": pass_2778(), "pass_2779": pass_2779()}
    path = ROOT / "data" / "PART_W33_PASS2778_2779_AFFINE_AND_SENSOR.json"
    path.parent.mkdir(exist_ok=True)
    # Hash the ROUND-TRIPPED object, never the live dict (CLAUDE.md, Pass 2482).
    text = json.dumps(json.loads(json.dumps(out)), indent=2, sort_keys=True) + "\n"
    path.write_text(text, encoding="utf-8")
    print(f"\nwrote {path.relative_to(ROOT).as_posix()}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
