#!/usr/bin/env python3
"""Pass6017-6024: post-6016 integrity replay.

The historical audit found false closure/realization claims. The live producer
files have now been corrected. This replay verifies that the corrections remain
in place while regenerating the frozen correction certificate.
"""
from __future__ import annotations
import json, math
from pathlib import Path

ROOT=Path(__file__).resolve().parents[1]
OUT=ROOT/'data'/'PART_W33_PASS6017_6024_POSTCLOSURE_INTEGRITY_AUDIT.json'

def rd(p): return (ROOT/p).read_text()
def gcd_all(xs):
    g=0
    for x in xs:g=math.gcd(g,x)
    return g

def main():
    ce2=rd('scripts/w33_ce2_anchor22_closure.py')
    yuk=rd('scripts/w33_yukawa_radical_pair_closure.py')
    k3=rd('scripts/w33_k3_glue_slot_realization.py')
    closure=rd('scripts/w33_bridge_full_closure_theorem.py')
    oracle=rd('tools/qiskit/toe_bridge_completed_avatar_oracle.py')
    summary=rd('docs/pass_5957_6016_summary.md')

    # Corrected CE2 live contract.
    assert 'OPEN_BEYOND_THREE_IMPORTED_WITNESSES' in ce2
    assert "'full_orbit_enumerated':False" in ce2
    assert 'def ce2_triple_weight' not in ce2

    # Exact Yukawa block arithmetic + corrected flag status.
    A=((367,-55),(-55,175)); B=((323,275),(275,659))
    trA=A[0][0]+A[1][1]; detA=A[0][0]*A[1][1]-A[0][1]*A[1][0]
    trB=B[0][0]+B[1][1]; detB=B[0][0]*B[1][1]-B[0][1]*B[1][0]
    discA=trA*trA-4*detA; discB=trB*trB-4*detB
    row_sums_A=(sum(A[0]),sum(A[1])); row_sums_B=(sum(B[0]),sum(B[1]))
    assert (trA,detA,discA)==(542,61200,48964)
    assert (trB,detB,discB)==(982,137232,415396)
    assert row_sums_A==(312,120) and row_sums_B==(598,934)
    assert 'equal-coordinate/generation-flag eigenvector alignment' in yuk
    assert 'assert not results' in yuk

    # Corrected K3 live contract.
    gen=[780,7944,62600,53979]; g=gcd_all(gen); assert g==1
    assert 'assert g==1' in k3
    assert "'status':'FORMAL_AVATAR_ONLY'" in k3
    assert "'genuine_K3_glue_witness':'OPEN'" in k3
    assert 217*780//12==14105 and (217*780)%12==0

    # Corrected closure ledger must no longer inherit superseded physics as exact.
    historical_inherited=[
      'Yang-Mills mass gap: Delta_YM = 1818 MeV',
      'Neutrino mass m_nu3 = 0.0500 eV',
      'Inflationary r = 1/45',
      'Scalar resonance 3.206 TeV',
    ]
    assert 'ANSATZ/COMPARISON-ONLY per Pass5957-5964' in closure
    assert 'actual_gcd_of_780_7944_62600_53979' in closure
    assert 'CE2 anchor-22 is NOT globally closed' in closure

    # Corrected Qiskit file is explicitly a scaffold and implements no phase oracle.
    assert 'SEARCH SCAFFOLD' in oracle
    assert 'No phase oracle or computed predicate is implemented.' in oracle
    assert 'qc.h(qr)' in oracle and 'qc.measure(qr,cr)' in oracle
    assert 'MARKED_CE2' not in oracle

    assert 'CORRECTED BY PASS6017–6024' in summary
    assert 'actual gcd **1**, not 217' in summary

    out={
      'schema':'w33.pass6017_6024.postclosure_integrity_audit.v1',
      'status':'PASS_CORRECTION',
      'pass_6017_ce2_anchor22':{
        'verdict':'NOT_CLOSED',
        'evidence':['only three pre-promoted witness rows are input',
                    'the original purported full-orbit weights were generated by a hard-coded ce2_triple_weight rule',
                    'the original cancellation test checked only denominator integrality after multiplying by 54/108',
                    'loops over integer labels 1..39 were not a W(3,3) automorphism-orbit enumeration'],
        'retained':'three witness rows exactly as prior data; full anchor orbit remains open'},
      'pass_6018_yukawa_pairs':{
        'verdict':'REAL_SPECTRA_RETAINED__GENERATION_FLAG_REFUTED',
        'pair_A':{'trace':trA,'det':detA,'discriminant':discA,'row_sums':list(row_sums_A)},
        'pair_B':{'trace':trB,'det':detB,'discriminant':discB,'row_sums':list(row_sums_B)},
        'deduction':'both 2x2 symmetric blocks have real spectra, but (1,1) is not an eigenvector of either block'},
      'pass_6019_k3_glue':{
        'verdict':'SCRIPT_ASSERTION_FAILS__FORMAL_AVATAR_ONLY',
        'advertised_generator':[780,7944,62600,53979],
        'actual_gcd':g,
        'claimed_gcd':217,
        'retained':['formal square-zero 162x162 block with inserted I_81 off-diagonal','arithmetic identity (217/12)*780=14105'],
        'not_retained':'claim that the primitive generator has gcd 217 or that a genuine K3-side glue witness was realized'},
      'pass_6020_bridge_coefficient':{
        'verdict':'FORMAL_PARAMETERIZATION_ONLY',
        'deduction':'351/(4*pi^2) and 10530/pi^2 were assigned downstream coefficients; the failed gcd premise means they are not promoted as geometric K3 invariants by that producer'},
      'pass_6021_full_closure_ledger':{
        'verdict':'INTERNALLY_STALE__NOW_REPAIRED',
        'superseded_physics_imports':historical_inherited,
        'deduction':'the live closure ledger now inherits Pass5957-5964 ANSATZ/COMPARISON-ONLY status instead of listing these as proved'},
      'pass_6022_qiskit_avatar':{
        'verdict':'ENCODING_SPEC_NOT_THEOREM_ORACLE',
        'evidence':['historical marked shard was assigned from named labels','demonstration circuit only prepares uniform Hadamards and measures','no theorem-derived predicate/phase-marking circuit is implemented'],
        'retained':'state-count bookkeeping and analytic Grover-iteration arithmetic conditional on a supplied marked predicate'},
      'pass_6023_summary_claim_tiers':{
        'ce2_22':'OPEN beyond the three imported witnesses',
        'yukawa':'real 2x2 spectra exact; generation-flag alignment refuted',
        'k3':'formal avatar only; historical producer failed its gcd assertion and live producer records gcd=1',
        'qiskit':'encoding/search scaffold only',
        'physics_5933_5956':'ANSATZ/COMPARISON-ONLY per Pass5957-5964'},
      'pass_6024_release_rule':{
        'rule':'A script does not verify a global orbit by inventing a rule on integer labels; a formal inserted matrix is not a geometric realization; an oracle is not implemented until its marked predicate is computed by a circuit rather than assigned as a constant.'}
    }
    OUT.write_text(json.dumps(out,indent=2,sort_keys=True)+'\n')
    print(json.dumps(out,indent=2,sort_keys=True))
    return out

if __name__=='__main__': main()
