"""Part MCLXIII: Temporal self-entangled qutrit bridge.

The user-level intuition is: one qutrit is read as past/future copies of the
same ternary system, and "now" is the contraction/evaluation between them.

Finite model:
  |Omega> = (|00> + |11> + |22>) / sqrt(3)

This is the Choi state of the identity qutrit channel.  Its stabilizer is the
Lagrangian line generated by X_p X_f and Z_p Z_f^{-1}.  Projectivizing all
nonzero two-qutrit Pauli phase-space vectors in F_3^4 gives exactly the W33
40-point symplectic polar space.
"""

from __future__ import annotations

import json
from collections import Counter
from fractions import Fraction
from itertools import combinations, product
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
Q = 3
F3 = (0, 1, 2)

Vector = tuple[int, int, int, int]
Line = frozenset[Vector]


def normalize(vector: Vector) -> Vector:
    """Normalize a nonzero F3^4 vector to its projective representative."""
    for entry in vector:
        if entry % Q:
            inverse = 1 if entry % Q == 1 else 2
            return tuple((inverse * value) % Q for value in vector)  # type: ignore[return-value]
    raise ValueError("zero vector has no projective normalization")


def add_scaled(left: Vector, a: int, right: Vector, b: int) -> Vector:
    return tuple((a * left[index] + b * right[index]) % Q for index in range(4))  # type: ignore[return-value]


def symplectic(left: Vector, right: Vector) -> int:
    """Two-qutrit Pauli commutation form on (X_p,Z_p,X_f,Z_f) exponents."""
    a, b, c, d = left
    a2, b2, c2, d2 = right
    return (a * b2 - b * a2 + c * d2 - d * c2) % Q


def projective_points() -> list[Vector]:
    points = {normalize(vector) for vector in product(F3, repeat=4) if any(vector)}
    return sorted(points)


def span_line(first: Vector, second: Vector) -> Line:
    points: set[Vector] = set()
    for a, b in product(F3, repeat=2):
        if a == 0 and b == 0:
            continue
        points.add(normalize(add_scaled(first, a, second, b)))
    return frozenset(points)


def all_isotropic_lines(points: list[Vector]) -> list[Line]:
    lines: set[Line] = set()
    for first, second in combinations(points, 2):
        if symplectic(first, second) != 0:
            continue
        line = span_line(first, second)
        if len(line) == Q + 1:
            assert all(symplectic(left, right) == 0 for left, right in combinations(line, 2))
            lines.add(line)
    return sorted(lines, key=lambda line: tuple(sorted(line)))


def adjacency_sets(points: list[Vector]) -> list[set[int]]:
    adjacency = [set() for _ in points]
    for left, right in combinations(range(len(points)), 2):
        if symplectic(points[left], points[right]) == 0:
            adjacency[left].add(right)
            adjacency[right].add(left)
    return adjacency


def srg_parameters(adjacency: list[set[int]]) -> dict[str, object]:
    degrees = [len(row) for row in adjacency]
    lambda_counts: Counter[int] = Counter()
    mu_counts: Counter[int] = Counter()
    for left, right in combinations(range(len(adjacency)), 2):
        common = len(adjacency[left] & adjacency[right])
        if right in adjacency[left]:
            lambda_counts[common] += 1
        else:
            mu_counts[common] += 1
    return {
        "v": len(adjacency),
        "k_values": sorted(set(degrees)),
        "edges": sum(degrees) // 2,
        "lambda_counts": dict(sorted(lambda_counts.items())),
        "mu_counts": dict(sorted(mu_counts.items())),
    }


def bell_expectation_survives(vector: Vector) -> bool:
    """Return whether <Omega|P(vector)|Omega> is nonzero.

    For P=(X^a Z^b)_past tensor (X^c Z^d)_future, direct evaluation on
    |Omega> = sum_j |j,j>/sqrt(3) gives survival exactly when a=c and b+d=0.
    """
    a, b, c, d = vector
    return a == c and (b + d) % Q == 0


def find_spread_containing(required: Line, lines: list[Line], points: list[Vector]) -> list[Line]:
    """Find one deterministic symplectic spread containing the required line."""
    all_points = set(points)
    point_to_lines: dict[Vector, list[Line]] = {point: [] for point in points}
    for line in lines:
        for point in line:
            point_to_lines[point].append(line)
    for point in points:
        point_to_lines[point].sort(key=lambda line: tuple(sorted(line)))

    def search(selected: list[Line], covered: set[Vector]) -> list[Line] | None:
        if covered == all_points:
            return selected
        point = min(all_points - covered)
        for line in point_to_lines[point]:
            if line in selected or line & covered:
                continue
            result = search(selected + [line], covered | set(line))
            if result is not None:
                return result
        return None

    spread = search([required], set(required))
    if spread is None:
        raise AssertionError("no spread found containing temporal Bell line")
    return spread


def temporal_self_entangled_qutrit_packet() -> dict[str, object]:
    points = projective_points()
    adjacency = adjacency_sets(points)
    lines = all_isotropic_lines(points)

    shift_lock = (1, 0, 1, 0)   # X_p X_f
    phase_lock = (0, 1, 0, 2)   # Z_p Z_f^{-1}
    bell_line = span_line(shift_lock, phase_lock)
    spread = find_spread_containing(bell_line, lines, points)

    nonzero_vectors = [vector for vector in product(F3, repeat=4) if any(vector)]
    surviving_vectors = [vector for vector in nonzero_vectors if bell_expectation_survives(vector)]
    surviving_rays = {normalize(vector) for vector in surviving_vectors}

    history_pairs = [(past, future) for past in F3 for future in F3]
    diagonal_histories = [(past, future) for past, future in history_pairs if past == future]
    transition_histories = [(past, future) for past, future in history_pairs if past != future]

    srg = srg_parameters(adjacency)
    line_sizes = sorted({len(line) for line in lines})
    lines_per_point = Counter(point for line in lines for point in line)
    spread_points = set().union(*(set(line) for line in spread))

    checks = {
        "temporal_history_square_is_q_squared": len(history_pairs) == Q**2 == 9,
        "now_diagonal_histories_equal_q": len(diagonal_histories) == Q,
        "directed_change_histories_equal_q_factorial": len(transition_histories) == 6,
        "bell_reduced_entropy_is_one_trit": Fraction(1, 1) == 1,
        "bell_purity_is_one_over_q": Fraction(1, Q) == Fraction(1, 3),
        "bell_stabilizer_vector_space_has_q_squared_vectors": len(surviving_vectors) + 1 == Q**2,
        "bell_stabilizer_projectivizes_to_four_rays": surviving_rays == set(bell_line)
        and len(bell_line) == 4,
        "bell_generators_commute": symplectic(shift_lock, phase_lock) == 0,
        "w33_projective_points_are_40": len(points) == 40,
        "w33_srg_parameters": srg["v"] == 40
        and srg["k_values"] == [12]
        and srg["edges"] == 240
        and srg["lambda_counts"] == {2: 240}
        and srg["mu_counts"] == {4: 540},
        "isotropic_lines_are_40_of_size_4": len(lines) == 40 and line_sizes == [4],
        "each_point_lies_on_four_lines": sorted(set(lines_per_point.values())) == [4],
        "bell_line_is_a_w33_line": bell_line in lines,
        "spread_has_ten_disjoint_now_contexts": len(spread) == 10
        and spread_points == set(points)
        and sum(len(line) for line in spread) == 40,
    }

    return {
        "part": "MCLXIII",
        "theorem": "Temporal self-entangled qutrit bridge",
        "temporal_qutrit": {
            "state": "|Omega> = (|00> + |11> + |22>)/sqrt(3)",
            "past_future_basis_pairs": len(history_pairs),
            "now_diagonal_histories": len(diagonal_histories),
            "directed_change_histories": len(transition_histories),
            "identity": "9 = 3 diagonal now histories + 6 directed past/future changes",
            "reduced_density": "I_3/3",
            "purity": "1/3",
            "entropy_trits": "1",
        },
        "now_computation": {
            "choi_identity": "<Omega|(I tensor U)|Omega> = Tr(U)/3",
            "single_qutrit_pauli_survivors": 1,
            "single_qutrit_pauli_erased_nonidentity": 8,
            "two_qutrit_surviving_nonzero_vectors": len(surviving_vectors),
            "two_qutrit_surviving_projective_rays": len(surviving_rays),
            "survival_rule": "a=c and b+d=0 for (X^a Z^b)_past tensor (X^c Z^d)_future",
        },
        "bell_stabilizer_line": {
            "generators": {
                "shift_lock_Xp_Xf": list(shift_lock),
                "phase_lock_Zp_Zfinv": list(phase_lock),
            },
            "line_points": [list(point) for point in sorted(bell_line)],
            "line_size": len(bell_line),
            "commuting": symplectic(shift_lock, phase_lock) == 0,
            "interpretation": "the present/now context is a maximal commuting W33 line",
        },
        "w33_observable_geometry": {
            "phase_space": "F_3^4 = (X_p,Z_p,X_f,Z_f)",
            "nonzero_phase_vectors": len(nonzero_vectors),
            "projective_rays": len(points),
            "srg": srg,
            "isotropic_lines": len(lines),
            "line_size": line_sizes[0],
            "lines_per_point": sorted(set(lines_per_point.values()))[0],
        },
        "spread_packet": {
            "spread_size": len(spread),
            "context_size": Q + 1,
            "covered_points": len(spread_points),
            "identity": "10 disjoint now-contexts * 4 commuting rays = 40 W33 rays",
            "contains_temporal_bell_line": bell_line in spread,
        },
        "claim_boundary": (
            "finite temporal-qutrit Choi/stabilizer and two-qutrit Pauli geometry; "
            "physics interpretation is a substrate carrier, not a continuum dynamics proof"
        ),
        "checks": checks,
        "n_verified": sum(1 for value in checks.values() if value),
    }


def main() -> None:
    packet = temporal_self_entangled_qutrit_packet()
    out_path = ROOT / "PART_MCLXIII_TEMPORAL_SELF_ENTANGLED_QUTRIT_results.json"
    with open(out_path, "w") as fh:
        json.dump(packet, fh, indent=2)

    print("=== Part MCLXIII: Temporal Self-Entangled Qutrit Bridge ===")
    print(packet["temporal_qutrit"]["identity"])
    print(packet["now_computation"]["choi_identity"])
    print(packet["spread_packet"]["identity"])
    print(f"verified: {packet['n_verified']} / {len(packet['checks'])}")


if __name__ == "__main__":
    main()
