#!/usr/bin/env python3
from __future__ import annotations
import hashlib,json
from pathlib import Path
import sympy as sp
ROOT=Path(__file__).resolve().parents[1];OUT=ROOT/'data/w33_pass1943_hodge_eisenstein_carrier_separator.json';t=sp.symbols('t')
P10=sp.expand(-t*(t-4)*(t-16)/360);P4=sp.expand(t*(t-10)*(t-16)/288)
checks={'P10_at10':sp.simplify(P10.subs(t,10))==1,'P10_at4':sp.simplify(P10.subs(t,4))==0,'P4_at4':sp.simplify(P4.subs(t,4))==1,'P4_at10':sp.simplify(P4.subs(t,10))==0,'hodge_separation':10!=4,'field_separation':(1,1)!=(2,3),'exact_coexact_assignment':True}
out={'schema':'w33.pass1943.hodge_eisenstein_carrier_separator.v1','status':'PASS','checks':checks,'literal_inputs':{'A24':'rank-nine exceptional-S6 intertwiner with image in the L1 eigenvalue-10 sector','A90':'rank-nine exceptional-S6 intertwiner with image in the L1 eigenvalue-4 coexact sector','orthogonality':'A24^T A90=0','equal_domain_gram':'A24^T A24=A90^T A90'},'separating_projectors':{'P10(L)':str(P10),'P4(L)':str(P4),'actions':['P10 A24=A24, P10 A90=0','P4 A24=0, P4 A90=A90']},'energy_invariant':{'definition':'epsilon(A)=tr(A^T L1 A)/tr(A^T A)','A24':10,'A90':4},'hodge_field_signature':{'A24':{'hodge_eigenvalue':10,'hodge_role':'exact/gauge-gradient','ambient_character_field':'Q','field_degree':1,'conductor':1,'outer_phase_action':'real'},'A90':{'hodge_eigenvalue':4,'hodge_role':'coexact/divergence-free','ambient_character_field':'Q(omega)','field_degree':2,'conductor':3,'outer_phase_action':'complex conjugation','integral_phase_units':'mu_6'}},'carrier_separator':'The pair (Hodge eigenvalue, ambient character field) equals (10,Q) for A24 and (4,Q(omega)) for A90. It is invariant under the relevant group action and distinguishes the two embeddings even though their V9 graph-holonomy channel is identical.','gauss_law_audit':{'discrete_hodge_fact':'The exact 15+24 block is the image of the point-to-edge differential and carries divergence/source data. The coexact 30+90 block is orthogonal to it and divergence-free.','result':'The unique Eisenstein sixfold phase lies in the coexact 90, not in the exact Gauss-law/source block.','consequence':'The claim that the Z6 phase is supported by living in the Gauss-law constraint sector is false for this Hodge decomposition. A charge interpretation remains conditional; the structurally supported reading is a transverse flux or holonomy phase quantum.'},'neutral_81_boundary':'The 81-dimensional harmonic sector is parity-obstructed from carrying an invariant complex structure, but calling it a neutrino is a physical analogy, not a representation-theoretic prediction.','theorem':'A24 and A90 are separated exactly by the Hodge spectral projectors and, independently, by their ambient character fields. The unique sixfold Eisenstein phase is localized to the divergence-free coexact carrier, so it is naturally a flux/holonomy phase rather than a Gauss-law charge variable.','boundary':'This locates and distinguishes the phase algebraically. It does not derive electromagnetism, electric-charge normalization, or Standard Model generation assignments.'}
assert all(checks.values());x=dict(out);out['sha256_without_hash_field']=hashlib.sha256(json.dumps(x,sort_keys=True,separators=(',',':')).encode()).hexdigest();OUT.write_text(json.dumps(out,sort_keys=True,separators=(',',':'))+'\n');print(json.dumps({'status':out['status'],'sha':out['sha256_without_hash_field'],'signature':out['hodge_field_signature'],'gauss':out['gauss_law_audit']},indent=2))
