#!/usr/bin/env python3
"""Passes 4740 and 4744: demand an actual Golay intertwiner, or certify why it fails.

4740  The established W33/Golay files contain many exact parameter equalities,
      but a coordinate-equivariant bridge would require the W33 symmetry to act
      on the 24 Golay coordinates.  A faithful PSp(4,3) coordinate action is
      impossible: |PSp(4,3)|=2^6*3^4*5 does not divide
      |M24|=2^10*3^3*5*7*11*23.  This is only a coordinate-permutation no-go;
      it does NOT rule out a non-coordinate Leech/Conway representation.

      The most natural 24-coordinate puncture supplied by the new involution
      geometry removes the sixteen W33 lines fixed by a 45-class involution.
      It gives H10|_24 = [24,10,6], with an explicit weight-6 word, hence cannot
      be a subcode of the extended binary Golay [24,12,8].  Shortening H10 on
      those sixteen positions gives only [24,2,16].

4744  Census a second intrinsic 24-coordinate family: complements of the 135
      weight-16 H10 words.  All 135 give the same puncture signature [24,9,4]
      and shortening [24,1,24].  Thus neither canonical 24-coordinate family is
      Golay.  The dual puncture along the involution-fixed family is [24,22,2],
      so the minimum-shell side also fails immediately.  This turns the old
      numerical 24/12/8 bridge into a precise boundary: the standard coordinate
      route is blocked, while a non-coordinate Conway/Leech intertwiner remains
      a legitimate separate problem.
"""
from __future__ import annotations
import itertools,json,math
from collections import Counter
from pathlib import Path
import numpy as np

from w33_pass4495_4502_distance_prism_reconstruction import geometry
from w33_pass4721_4724_support12_involution_square_root_cover import build_groups, compose_perm, fixed_mask

ROOT=Path(__file__).resolve().parents[1]
OUT=ROOT/'data/PART_W33_PASS4740_4744_GOLAY_INTERTWINER_MINOR_NO_GO.json'
M24_ORDER=244_823_040
PSP_ORDER=25_920

def gf2_basis(vals):
    piv={};out=[]
    for x in vals:
        y=int(x)
        while y:
            p=y.bit_length()-1
            if p in piv:y^=piv[p]
            else:piv[p]=y;out.append(y);break
    return out

def codewords(basis):
    out=[]
    for m in range(1<<len(basis)):
        x=0
        for i,b in enumerate(basis):
            if (m>>i)&1:x^=b
        out.append(x)
    return out

def compress(x,keep):
    y=0
    for j,i in enumerate(keep):
        if (x>>i)&1:y|=1<<j
    return y

def signature(words):
    W=set(words);basis=gf2_basis(W)
    d=min((x.bit_count() for x in W if x),default=None)
    return {'dimension':len(basis),'minimum_distance':d,
            'weight_enumerator':dict(sorted(Counter(x.bit_count() for x in W).items()))}

def main():
    pts,pidx,lines,Astar,apartments,_m,_H=geometry();Astar=np.asarray(Astar,dtype=np.uint8)
    rows=[sum(int(Astar[i,j])<<j for j in range(40)) for i in range(40)]
    hb=gf2_basis(rows);assert len(hb)==10
    H10=codewords(hb);assert len(H10)==1024
    assert Counter(x.bit_count() for x in H10)==Counter({0:1,12:40,16:135,20:672,24:135,28:40,40:1})

    # 45 involution-fixed 16-sets, one PSp orbit.
    _gens,inner,_full=build_groups(pts,pidx,lines);ident=tuple(range(40))
    fixed16=[]
    for p in inner:
        if p!=ident and compose_perm(p,p)==ident:
            f=fixed_mask(p)
            if f.bit_count()==16:fixed16.append(f)
    assert len(fixed16)==45 and len(set(fixed16))==45

    inv_puncture_sigs=Counter();inv_shorten_sigs=Counter();dual_sigs=Counter()
    # H10^perp is generated by the 270 weight-4 residue masks.
    residues=[]
    for C in itertools.combinations(range(40),4):
        if not np.any(np.sum(Astar[:,C],axis=1)&1):residues.append(sum(1<<i for i in C))
    rb=gf2_basis(residues);assert len(residues)==270 and len(rb)==30

    for f in fixed16:
        keep=[i for i in range(40) if not ((f>>i)&1)]
        P={compress(x,keep) for x in H10}
        Sh={compress(x,keep) for x in H10 if not (x&f)}
        ps=signature(P);ss=signature(Sh)
        inv_puncture_sigs[json.dumps(ps,sort_keys=True)]+=1
        inv_shorten_sigs[json.dumps(ss,sort_keys=True)]+=1
        assert ps['dimension']==10 and ps['minimum_distance']==6
        assert ss['dimension']==2 and ss['minimum_distance']==16

        # puncture(H10^perp) = shorten(H10)^perp.  Dimension 22; prove d=2
        # by no zero parity-check column (d>=2) and an explicit projected
        # weight-2 residue generator (d<=2).
        projected=[compress(x,keep) for x in rb]
        assert len(gf2_basis(projected))==22
        shb=gf2_basis(Sh);assert len(shb)==2
        column_types=[]
        for j in range(24):column_types.append(tuple((b>>j)&1 for b in shb))
        assert all(c!=(0,0) for c in column_types)
        assert any(compress(r,keep).bit_count()==2 for r in residues)
        dual_sigs['[24,22,2]']+=1
    assert len(inv_puncture_sigs)==len(inv_shorten_sigs)==1

    # Second intrinsic 24-family: complements of all 135 H10 weight-16 words.
    weight16=[x for x in H10 if x.bit_count()==16];assert len(weight16)==135
    h16_puncture=Counter();h16_shorten=Counter()
    for f in weight16:
        keep=[i for i in range(40) if not ((f>>i)&1)]
        ps=signature({compress(x,keep) for x in H10})
        ss=signature({compress(x,keep) for x in H10 if not (x&f)})
        h16_puncture[json.dumps(ps,sort_keys=True)]+=1
        h16_shorten[json.dumps(ss,sort_keys=True)]+=1
        assert ps['dimension']==9 and ps['minimum_distance']==4
        assert ss['dimension']==1 and ss['minimum_distance']==24
    assert len(h16_puncture)==len(h16_shorten)==1

    # Group-order obstruction to faithful coordinate equivariance.
    psp_factors={2:6,3:4,5:1};m24_factors={2:10,3:3,5:1,7:1,11:1,23:1}
    assert PSP_ORDER==math.prod(p**e for p,e in psp_factors.items())
    assert M24_ORDER==math.prod(p**e for p,e in m24_factors.items())
    assert M24_ORDER%PSP_ORDER!=0 and psp_factors[3]>m24_factors[3]

    inv_ps=json.loads(next(iter(inv_puncture_sigs)))
    inv_ss=json.loads(next(iter(inv_shorten_sigs)))
    h16_ps=json.loads(next(iter(h16_puncture)));
    h16_ss=json.loads(next(iter(h16_shorten)))
    out={'passes':[4740,4744],
      '4740_coordinate_intertwiner_no_go':{
        'PSp_order':PSP_ORDER,'PSp_factorization':'2^6 * 3^4 * 5',
        'M24_order':M24_ORDER,'M24_factorization':'2^10 * 3^3 * 5 * 7 * 11 * 23',
        'PSp_order_divides_M24':False,
        'conclusion':'No faithful PSp(4,3) action by permutations of the 24 extended-Golay coordinates.',
        'scope_boundary':'Does not rule out non-coordinate embeddings into Conway/Leech symmetry.',
        'involution_fixed16_complement':{
          'orbit_size':45,'punctured_H10':inv_ps,'shortened_H10':inv_ss,
          'punctured_dual':'[24,22,2]',
          'Golay_subcode_obstruction':'punctured H10 has weight 6 < extended Golay minimum 8'
        }},
      '4744_minor_census':{
        'H10_weight16_supports':135,
        'complement24_puncture_signature':h16_ps,
        'complement24_shorten_signature':h16_ss,
        'all_135_same_signature':True,
        'Golay_subcode_obstruction':'minimum 4 < 8',
      },
      'boundary':'The old W33/Golay parameter equalities remain arithmetic observations.  These tests block the two canonical 24-coordinate code intertwiners and any faithful PSp coordinate-permutation action; they do not disprove a genuinely non-coordinate Leech-lattice representation.'}
    OUT.write_text(json.dumps(out,indent=2,sort_keys=True)+'\n',encoding='utf-8');print(json.dumps(out,indent=2,sort_keys=True));return 0
if __name__=='__main__':raise SystemExit(main())
