#!/usr/bin/env python3
"""Export aligned F2 generator matrices for two 48-dimensional PSp(4,3)
modules:

  H1_48  -- binary homology of the doubled 90-D4 prism;
  Omega48 -- im(LP-PL mod 2) in the 160-chamber Hecke module.

The second object is canonical in characteristic two: Omega mod 2 has rank 48
and Omega^2=0, so no reduction of the rational projector -Omega^2/60 is used.
The output GAP file is consumed by w33_20260901_binary48_ext_compare.g.
"""
from __future__ import annotations

import json
from pathlib import Path
import numpy as np

import w33_20260829_216_clifford_torsor_nogo as groupbase
from w33_pass4992_4999_common import build_base
from w33_pass7225_7232_spread_code_doily_puncture import coordinate_isomorphism
from w33_20260901_d4_prism_lift import d4_data
from w33_20260901_binary_h1_48_nonsplit import (
    rref,rank,col_basis,nullspace,coord_solver,act_columns,
)

ROOT=Path(__file__).resolve().parents[1]
GOUT=ROOT/'analysis/PART_W33_20260901_BINARY48_MATRICES.g'
JOUT=ROOT/'data/PART_W33_20260901_BINARY48_EXPORT.json'


def matrix_gap(A):
    A=np.asarray(A,dtype=np.uint8)
    return '['+','.join('['+','.join(str(int(x)) for x in row)+']' for row in A)+']'


def list_gap(xs):return '['+','.join(str(int(x)+1) for x in xs)+']'


def fixed_dim(gs,n):
    M=np.concatenate([g^np.eye(n,dtype=np.uint8) for g in gs],axis=0)
    return n-rank(M)


def main():
    # -------- H1_48, replaying the frozen nonsplit certificate --------
    b=build_base();T=b['tritangents'];N=(1-np.asarray(b['M'],dtype=np.uint8))&1
    D4,pairs,supports,_packs=d4_data(b['W'])
    packet_to_tri=coordinate_isomorphism(supports,T)
    P=np.zeros((45,45),dtype=np.uint8)
    for s,t in enumerate(packet_to_tri):P[t,s]=1
    R=np.zeros((27,45),dtype=np.uint8)
    for j,t in enumerate(T):R[list(t),j]=1
    J=np.zeros((90,45),dtype=np.uint8)
    for s,(a,c) in enumerate(pairs):J[a,s]=J[c,s]=1
    N90=(J@P.T@N)&1;R90=(R@P@J.T)&1
    assert rank(N90)==rank(R90)==21 and not np.any((R90@N90)&1)

    I=col_basis(N90);S=J.copy();cur=I.copy();rr=21;Acols=[]
    for j in range(45):
        z=S[:,j:j+1]
        if rank(np.concatenate([cur,z],axis=1))>rr:
            Acols.append(z[:,0]);cur=np.concatenate([cur,z],axis=1);rr+=1
    assert len(Acols)==24 and rr==45
    A=np.stack(Acols,axis=1)
    K=nullspace(R90);cur=np.concatenate([I,A],axis=1);rr=45;Bcols=[]
    for j in range(K.shape[1]):
        z=K[:,j:j+1]
        if rank(np.concatenate([cur,z],axis=1))>rr:
            Bcols.append(z[:,0]);cur=np.concatenate([cur,z],axis=1);rr+=1
    assert len(Bcols)==24 and rr==69
    B=np.stack(Bcols,axis=1);Full=np.concatenate([I,A,B],axis=1);solve=coord_solver(Full)

    pts=b['P'];idx={v:i for i,v in enumerate(pts)};qidx={q:i for i,q in enumerate(D4)}
    gens40=[]
    for v in pts:
        for alpha in (1,2):
            p=[]
            for x in pts:
                z=alpha*groupbase.form(x,v)%3
                y=groupbase.norm(tuple((x[k]+z*v[k])%3 for k in range(4)))
                p.append(idx[y])
            gens40.append(tuple(p))
    chosen=(18,62,77,10);G40=[gens40[i] for i in chosen]
    gens90=[]
    for p in G40:
        gens90.append(tuple(qidx[frozenset(p[x] for x in q)] for q in D4))
    Egens=[]
    for p in gens90:
        C=solve(act_columns(np.concatenate([A,B],axis=1),p))
        E=C[21:,:]&1;assert E.shape==(48,48) and not np.any(E[24:,:24])
        Egens.append(E)
    Ag=[E[:24,:24] for E in Egens];Bg=[E[24:,24:] for E in Egens]
    assert fixed_dim(Egens,48)==1 and fixed_dim(Ag,24)==1 and fixed_dim(Bg,24)==0

    # -------- canonical chamber Omega48 --------
    # Use exactly the same 40-point generators; rebuild their 40 isotropic lines.
    wpts,widx,wlines,_N=groupbase.geometry()
    assert wpts==pts
    wlines=[tuple(L) for L in wlines];lidx={frozenset(L):i for i,L in enumerate(wlines)}
    flags=[(p,l) for l,L in enumerate(wlines) for p in L];fidx={f:i for i,f in enumerate(flags)}
    assert len(flags)==160
    PP=np.zeros((160,160),dtype=np.uint8);LL=np.zeros((160,160),dtype=np.uint8)
    for i,(p,l) in enumerate(flags):
        for j,(q,m) in enumerate(flags):
            if i!=j and p==q:PP[i,j]=1
            if i!=j and l==m:LL[i,j]=1
    Omega=(LL@PP+PP@LL)&1  # subtraction equals addition in F2
    assert rank(Omega)==48 and not np.any((Omega@Omega)&1)
    OB=col_basis(Omega);assert OB.shape==(160,48);osolve=coord_solver(OB)
    Fgens=[]
    for p in G40:
        pl=tuple(lidx[frozenset(p[x] for x in L)] for L in wlines)
        pf=tuple(fidx[(p[x],pl[l])] for x,l in flags)
        image=act_columns(OB,pf)
        C=osolve(image)&1;assert C.shape==(48,48)
        assert np.array_equal((OB@C)&1,image)
        Fgens.append(C)
    assert fixed_dim(Fgens,48)==1

    # Export row-action matrices to GAP by transposing the column-action matrices.
    linesg=['# generated by w33_20260901_binary48_ext_export.py','F:=GF(2);;']
    linesg.append('PermGens40:=['+','.join('PermList('+list_gap(p)+')' for p in G40)+'];;')
    for name,gs in [('Amats',Ag),('Bmats',Bg),('Hmats',Egens),('Cmats',Fgens)]:
        linesg.append(name+':=['+','.join('Matrix(F,'+matrix_gap(g.T)+')' for g in gs)+'];;')
    GOUT.write_text('\n'.join(linesg)+'\n')

    out={'schema':'w33.20260901.binary48-export.v1','status':'PASS',
      'H1':{'dimension':48,'filtration':[24,24],'fixedDimension':1,
            'A24Fixed':1,'B24Fixed':0},
      'chamberOmega':{'ambientChambers':160,'rankMod2':48,'squareZero':True,
                      'imageDimension':48,'fixedDimension':1,
                      'definition':'im((LP-PL) mod 2) = im((LP+PL) mod 2)'},
      'alignedGenerators':4,'gapMatrixFile':str(GOUT.relative_to(ROOT)),
      'boundary':'This exports exact aligned modules; isomorphism, composition factors and Ext are decided by the GAP consumer.'}
    JOUT.write_text(json.dumps(out,indent=2,sort_keys=True)+'\n')
    print(json.dumps({'status':'PASS','H1':48,'OmegaRank':48,'OmegaSquareZero':True,'fixed':[1,1]},sort_keys=True))

if __name__=='__main__':main()
