#!/usr/bin/env python3
"""
Thermal time: the machine's clock is the substrate's modular flow, and the gauge/
matter sector is timeless -- so the Fano clock is the unique origin of time.

Connes-Rovelli thermal-time hypothesis: in a generally covariant quantum theory
physical time is not assumed; it is the modular (Tomita-Takesaki) automorphism
flow of the state. For a state rho the modular Hamiltonian is K = -ln rho and the
modular flow is sigma_t(A) = rho^{it} A rho^{-it} = e^{iKt} A e^{-iKt}; the state
is KMS (thermal) at inverse temperature 1 with respect to it.

On the substrate this picks out the clock exactly:
  - TIMELESS GAUGE/MATTER. The logical H1=81 sector is a single irreducible
    PSp(4,3) block (BT1688); its natural invariant state is maximally mixed,
    rho = I/81. Then K = -ln rho = (ln 81) I is a multiple of the identity, so the
    modular flow sigma_t = id is TRIVIAL: the gauge/matter sector carries no
    intrinsic time.
  - THE CLOCK GENERATES TIME. The Fano/Heawood clock oscillator has a non-flat
    spectrum (Laplacian L_H, middle shell q +- sqrt(lambda) = 3 +- sqrt2). Its
    Gibbs state rho = e^{-beta L_H}/Z has modular Hamiltonian K = beta L_H + (ln Z)I,
    so the modular flow is generated by L_H itself: sigma_t(A) = e^{i L_H (beta t)}
    A e^{-i L_H (beta t)}. The clock's tick IS the modular flow; the modular
    frequency is the oscillator frequency sqrt(lambda) = sqrt2 (= the top-mass
    scale, w33_machine_clock_is_mass.py).

So time emerges from the state, not from a background, and it emerges SPECIFICALLY
from the clock layer: the gauge/matter sector (flat spectrum) is timeless, the
Fano clock (oscillator spectrum) is the time-source. This is the modular-flow
reason for the two-layer split (w33_clock_gauge_two_layer.py).

Verifies: (a) maximally-mixed sector -> trivial modular flow (timeless);
(b) clock Gibbs state -> modular flow generated by L_H; (c) the KMS condition
Tr(rho A B) = Tr(rho B sigma_{i beta}(A)) holds exactly.
"""
from __future__ import annotations

import json

import numpy as np

Q, LAM = 3, 2


def heawood_laplacian():
    lines = [tuple(sorted(((i) % 7, (i + 1) % 7, (i + 3) % 7))) for i in range(7)]
    A = np.zeros((14, 14))
    for li, ln in enumerate(lines):
        for p in ln:
            A[p, 7 + li] = A[7 + li, p] = 1
    return np.diag(A.sum(1)) - A


def expm_h(H, t):
    # exp(i H t) for Hermitian H via eigendecomposition (t may be complex)
    ev, U = np.linalg.eigh(H)
    return U @ np.diag(np.exp(1j * t * ev)) @ U.conj().T


def main():
    out = {}
    rng = np.random.default_rng(3)

    # (a) timeless gauge/matter sector: maximally mixed -> K ~ I -> trivial flow
    n = 81
    rho_mix = np.eye(n) / n
    K_mix = -np.log(np.diag(rho_mix).real)  # eigen of -ln rho
    spread = K_mix.max() - K_mix.min()
    print("[a] gauge/matter sector (H1=81, maximally mixed)")
    print(
        f"    modular Hamiltonian K = -ln rho has spread {spread:.2e} "
        f"(= 0) -> K prop-to I -> modular flow trivial -> TIMELESS"
    )
    assert spread < 1e-12
    out["gauge_sector_timeless"] = True

    # (b) clock Gibbs state -> modular flow generated by L_H
    L = heawood_laplacian()
    beta = 1.0
    ev, U = np.linalg.eigh(L)
    rho = U @ np.diag(np.exp(-beta * ev)) @ U.conj().T
    rho /= np.trace(rho).real
    # K = -ln rho (from the NORMALIZED Gibbs state) ; compare to beta L + (ln Z) I
    rho_eigs = np.exp(-beta * ev)
    Z = rho_eigs.sum()
    lnZ = np.log(Z)
    K = U @ np.diag(-np.log(rho_eigs / Z)) @ U.conj().T
    resid = np.linalg.norm(K - (beta * L + lnZ * np.eye(14)))
    mid = sorted(set(round(float(x), 4) for x in ev))
    print("\n[b] clock oscillator (Heawood Laplacian) Gibbs state")
    print(f"    spectrum {mid} (middle shell 3 +- sqrt2)")
    print(f"    K = -ln rho = beta*L_H + (ln Z) I  (residual {resid:.2e})")
    print(
        f"    => modular flow generated by L_H; modular frequency = sqrt(lambda) "
        f"= sqrt(2) = {np.sqrt(LAM):.4f} (the clock/top-mass frequency)"
    )
    assert resid < 1e-9
    out["clock_modular_generator_is_L_H"] = True
    out["modular_frequency"] = float(np.sqrt(LAM))

    # (c) KMS condition: Tr(rho A B) = Tr(rho B sigma_{i beta}(A))
    A = rng.standard_normal((14, 14)) + 1j * rng.standard_normal((14, 14))
    A = A + A.conj().T
    B = rng.standard_normal((14, 14)) + 1j * rng.standard_normal((14, 14))
    B = B + B.conj().T
    sigma_ibeta_A = expm_h(L, 1j * beta) @ A @ expm_h(L, -1j * beta)
    lhs = np.trace(rho @ A @ B)
    rhs = np.trace(rho @ B @ sigma_ibeta_A)
    print("\n[c] KMS condition (thermal state at inverse temp beta=1)")
    print(f"    Tr(rho A B) = {lhs:.6f}")
    print(f"    Tr(rho B sigma_(i beta)(A)) = {rhs:.6f}")
    print(f"    KMS holds: {np.allclose(lhs, rhs)}")
    assert np.allclose(lhs, rhs)
    out["KMS_holds"] = True

    print("\nRESULT: time is the substrate's modular (Tomita-Takesaki) flow, and it")
    print("  emerges from the CLOCK. The gauge/matter sector (H1=81, maximally mixed,")
    print("  flat spectrum) has K prop-to I, so its modular flow is trivial -- it is")
    print("  timeless. The Fano/Heawood clock oscillator (non-flat Laplacian, middle")
    print("  shell 3 +- sqrt2) has modular Hamiltonian = beta L_H, so its modular")
    print("  flow IS the clock tick, at modular frequency sqrt(lambda) = sqrt2 -- the")
    print("  same frequency that sets the top mass. Time is not assumed: it is the")
    print("  modular flow of the state, and only the clock layer can source it. This")
    print("  is the Connes-Rovelli reason the machine needs a separate Fano clock.")

    out["summary"] = (
        "Connes-Rovelli thermal time = modular flow sigma_t(A)="
        "rho^{it}A rho^{-it}; gauge/matter sector (max mixed, flat) "
        "K prop-to I -> timeless; clock Gibbs state K = beta L_H -> modular "
        "flow = clock tick at frequency sqrt(lambda)=sqrt2; KMS holds. "
        "Time emerges from the state and only the Fano clock layer "
        "sources it -- the modular-flow reason for the two-layer split."
    )
    out["sources"] = [
        "Connes-Rovelli, Von Neumann algebra automorphisms and "
        "time-thermodynamics relation, Class. Quant. Grav. 11 (1994)",
        "Tomita-Takesaki modular theory; KMS condition; "
        "w33_machine_clock_is_mass.py, w33_clock_gauge_two_layer.py",
    ]
    with open("data/w33_thermal_time_clock.json", "w") as fh:
        json.dump(out, fh, indent=2)
    print("\nwrote data/w33_thermal_time_clock.json")


if __name__ == "__main__":
    main()
