"""Pass 7229 -- the full A2 census of E8, and what singles out the 40 that are W(3,3).

THREE QUESTIONS AT ONCE.

  (1) How many A2 root subsystems does E8 have, and which W(E8)-orbit are the 40 of Pass
      7221 in? That converts "the fibration depends on a chosen J" into a statement about
      subsystem orbits.

  (2) What are the OTHER A2s doing? If E8 has 1120 A2s and only 40 are J-stable, the
      remaining 1080 are either inert or they form further quadrangles under other order-3
      elements -- in which case the 40 is one leaf of a family, not a distinguished set.

  (3) The other lane reports 3,150 D4 subsystems with 90 selected by W(3,3). A D4 contains
      A2s, so their 90 and my 40 are two views of one object. This counts the D4s spanned by
      pairs of my A2s and compares.

METHOD. Every pair of roots r, s with (r,s) = -1 generates an A2 = {+-r, +-s, +-(r+s)}. Collect
the distinct 6-element sets. Then test J-stability (J(A) = A setwise) for the specific J of
Pass 7217, and for other fixed-point-free order-3 elements, to see whether "40" is
J-specific or a universal count.

    py -3 analysis/w33_pass7229_a2_census_of_e8.py
"""

from __future__ import annotations

import itertools
import json
import random
import sys
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "analysis"))

try:
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")
except Exception:
    pass

import numpy as np  # noqa: E402
from w33_pass7217_ovoid_pullback_to_e8 import (  # noqa: E402
    CARTAN, roots_in_root_basis, simple_reflection, order_of,
)


def all_a2_subsystems(Rarr, G):
    """Every A2 subsystem: generated by a pair of roots at inner product -1."""
    n = len(Rarr)
    seen = set()
    for i in range(n):
        ri = Rarr[i]
        for j in range(i + 1, n):
            if int(ri @ G @ Rarr[j]) != -1:
                continue
            s = Rarr[j]
            t = ri + s
            fam = [ri, s, t, -ri, -s, -t]
            key = frozenset(tuple(int(x) for x in v) for v in fam)
            if len(key) == 6:
                seen.add(key)
    return sorted(seen, key=lambda f: sorted(f))


def main() -> int:
    print("=" * 78)
    print("Pass 7229 -- the A2 census of E8")
    print("=" * 78)

    R = roots_in_root_basis()
    Rarr = np.array(R, dtype=np.int64)
    G = CARTAN
    I8 = np.eye(8, dtype=np.int64)
    gens = [simple_reflection(i) for i in range(8)]

    A2s = all_a2_subsystems(Rarr, G)
    print(f"\n  A2 subsystems of E8: {len(A2s)}   (classical count is 1120)")

    # the Pass 7217 J
    cox = I8.copy()
    for g in gens:
        cox = cox @ g
    J = np.linalg.matrix_power(cox, 10)
    assert order_of(J, 8) == 3 and int(np.trace(J)) == -4

    def stable(fam, M):
        img = {tuple(int(x) for x in (M @ np.array(v, dtype=np.int64))) for v in fam}
        return img == set(fam)

    st = [f for f in A2s if stable(f, J)]
    print(f"  J-stable A2 subsystems (J = c^10): {len(st)}")
    print(f"    -> these are exactly the 40 points of W(3,3)? {len(st) == 40}")

    # (2) what about the others -- is 40 universal across J?
    rng = random.Random(7229)
    counts = Counter()
    found = 0
    tested_J = []
    for _ in range(4000):
        M = I8.copy()
        for _ in range(rng.randrange(2, 16)):
            M = M @ gens[rng.randrange(8)]
        o = order_of(M, 40)
        if o is None or o % 3:
            continue
        Jc = np.linalg.matrix_power(M, o // 3)
        if order_of(Jc, 4) != 3 or int(np.trace(Jc)) != -4:
            continue
        key = tuple(Jc.flatten().tolist())
        if key in tested_J:
            continue
        tested_J.append(key)
        counts[len([f for f in A2s if stable(f, Jc)])] += 1
        found += 1
        if found >= 8:
            break
    print(f"\n  stable-A2 counts over {found} distinct fixed-point-free order-3 elements: "
          f"{dict(counts)}")
    universal = set(counts) == {40}
    print(f"    every such J stabilises exactly 40 A2s? {universal}")

    # (3) D4 subsystems spanned by orthogonal pairs of the 40
    def orth(f1, f2):
        return all(int(np.array(a) @ G @ np.array(b)) == 0 for a in f1 for b in f2)

    pairs = [(i, j) for i, j in itertools.combinations(range(40), 2)
             if orth(st[i], st[j])]
    print(f"\n  orthogonal pairs among the 40 A2s: {len(pairs)}")
    print(f"    (= collinear point pairs of W(3,3), which is 40*12/2 = 240)")

    # the reflection closure of an orthogonal A2 pair
    def closure(S):
        gen = set(S)
        fr = list(S)
        while fr:
            nx = []
            for a in fr:
                av = np.array(a, dtype=np.int64)
                for b in list(gen):
                    bv = np.array(b, dtype=np.int64)
                    c = tuple(int(x) for x in (bv - int(bv @ G @ av) * av))
                    if c not in gen:
                        gen.add(c)
                        nx.append(c)
            fr = nx
        return gen

    cl = Counter()
    for i, j in pairs[:40]:
        S = list(st[i]) + list(st[j])
        c = closure(S)
        rk = np.linalg.matrix_rank(np.array(list(c), dtype=float))
        cl[(len(S), len(c), rk)] += 1
    print(f"  reflection closure of an orthogonal A2 pair (12 roots): {dict(cl)}")
    print(f"    A2+A2 stays 12 if the pair is already closed; D4 would be 24")

    out = {"boundary": ("a census, not a theorem: counts A2 subsystems of E8 and how many "
                        "each fixed-point-free order-3 element stabilises"),
           "a2_subsystems_of_E8": len(A2s),
           "J_stable": len(st),
           "stable_counts_over_many_J": {str(k): v for k, v in counts.items()},
           "count_is_universal": bool(universal),
           "orthogonal_pairs_among_the_40": len(pairs),
           "closure_of_orthogonal_pair": {str(k): v for k, v in cl.items()}}
    fp = ROOT / "data" / "PART_W33_PASS7229_A2_CENSUS.json"
    fp.write_text(json.dumps(out, indent=2), encoding="utf-8")
    print(f"\nwrote {fp.relative_to(ROOT).as_posix()}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
