#!/usr/bin/env python3
"""Pass 2314: cubic arithmetic controller versus finite D24 command algebra.

The matrices R4 and U6 generate the arithmetic controller.  Their independent
exponent coordinates do map two-to-one onto twelve hardware phases, but that map
does not descend to the matrix group: an exact identity relation carries phase 6.
"""
from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path

import sympy as sp


def digest(obj):
    return hashlib.sha256(json.dumps(obj, sort_keys=True, separators=(",", ":")).encode()).hexdigest()


def phase(a: int, b: int) -> int:
    return (3 * a + 2 * b) % 12


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--write-json", type=Path)
    args = ap.parse_args()

    x = sp.symbols("x")
    I = sp.eye(3)
    R = sp.Matrix([[0, -1, 0], [1, 0, 0], [0, 0, 1]])
    U = sp.Matrix([[1, 0, 0], [0, 0, 1], [0, -1, 1]])

    relation_left = U**3 * R
    relation_right = R**-1 * U**3
    identity_word = U**3 * R * U**-3 * R
    assert relation_left == relation_right
    assert identity_word == I

    # The same matrix is represented by two normal-form exponent pairs.
    left_label = phase(1, 3)
    right_label = phase(-1, 3)
    identity_label = phase(2, 0)  # exponent sum in U^3 R U^-3 R
    assert (left_label, right_label, identity_label) == (9, 3, 6)

    fibers = {d: [] for d in range(12)}
    for a in range(4):
        for b in range(6):
            fibers[phase(a, b)].append((a, b))
    assert all(len(v) == 2 for v in fibers.values())
    assert fibers[0] == [(0, 0), (2, 3)]

    words = {
        "R4_U6_squared_plastic": R * U**2,
        "R4_U6_supergolden": R * U,
        "R4_squared_U6_golden": R**2 * U,
    }
    charpolys = {name: str(sp.factor(M.charpoly(x).as_expr())) for name, M in words.items()}
    expected = {
        "R4_U6_squared_plastic": "x**3 - x - 1",
        "R4_U6_supergolden": "x**3 - x**2 - 1",
        "R4_squared_U6_golden": "(x + 1)*(x**2 - x - 1)",
    }
    assert charpolys == expected

    out = {
        "schema": "w33.pass2314.cubic_controller_nonquotient.v1",
        "status": "PASS_COMMAND_TORUS_AND_ARITHMETIC_NONQUOTIENT_BOUNDARY",
        "generators": {
            "R4": [list(map(int, row)) for row in R.tolist()],
            "U6": [list(map(int, row)) for row in U.tolist()],
        },
        "orders": {"R4": 4, "U6": 6},
        "determinants": {"R4": int(R.det()), "U6": int(U.det())},
        "matrix_relation": "U6^3 R4 = R4^-1 U6^3",
        "identity_obstruction_word": "U6^3 R4 U6^-3 R4 = I",
        "command_phase_labels": {
            "U6^3_R4": left_label,
            "R4^-1_U6^3": right_label,
            "identity_word": identity_label,
        },
        "command_quotient": {
            "map": "C4 x C6 -> C12, (a,b) |-> 3a+2b mod 12",
            "fiber_size": 2,
            "kernel": [list(z) for z in fibers[0]],
            "duo_translation": "(a,b)->(a+2,b+3)",
        },
        "short_word_characteristic_polynomials": charpolys,
        "checks": {
            "R4_order_4": R**4 == I and R**2 != I,
            "U6_order_6": U**6 == I and U**3 != I,
            "both_in_SL3Z": R.det() == 1 and U.det() == 1,
            "inversion_relation_exact": relation_left == relation_right,
            "obstruction_word_is_matrix_identity": identity_word == I,
            "obstruction_word_has_nonzero_command_phase": identity_label == 6,
            "command_map_surjective_two_to_one": all(len(v) == 2 for v in fibers.values()),
            "plastic_supergolden_golden_polynomials": charpolys == expected,
        },
        "theorem": "The map (a,b)->3a+2b mod 12 is an exact two-to-one quotient of the independent C4 x C6 command coordinates, but it is not a homomorphism from the arithmetic matrix group generated by R4 and U6. The matrix identity U6^3 R4 U6^-3 R4=I receives hardware phase 6.",
        "engineering_consequence": "The D24 block is an external scheduler/interface algebra. Arithmetic words must be compiled with relation-aware state, not reduced by exponent totals alone.",
        "boundary": "This obstruction does not invalidate the RTL D24 action. It forbids only the stronger identification of that action as a quotient representation of the infinite arithmetic controller group under the implemented generator labels.",
    }
    out["sha256_without_hash_field"] = digest(out)
    text = json.dumps(out, indent=2, sort_keys=True) + "\n"
    if args.write_json:
        args.write_json.parent.mkdir(parents=True, exist_ok=True)
        args.write_json.write_text(text)
    print(text, end="")


if __name__ == "__main__":
    main()
