"""Round28 discrete graph wave propagation vs external spatial continuum."""
import numpy as np,json,math,sys
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1];sys.path.insert(0,str(ROOT/'analysis'))
from w33_20261009_toe26_css_matching_family import wilson
OUT=ROOT/'data/w33_20261009_toe28_wave_geometry_comparison.json'
def run():
 edges,*_=wilson();A=np.zeros((80,80),dtype=float)
 for a,b in edges:A[a,b]=A[b,a]=1.
 L=np.eye(80)-A/4
 h=.7
 phi=np.zeros(80);phi[0]=1.
 hist=[phi.copy(),phi-.5*h*h*L@phi]
 for n in range(2,7):hist.append(2*hist[-1]-hist[-2]-h*h*L@hist[-1])
 dist=np.full(80,100);dist[0]=0
 frontier={0}
 for k in range(1,5):
  nextset={int(j) for i in frontier for j in np.flatnonzero(A[i]) if dist[j]==100}
  for j in nextset:dist[j]=k
  frontier=nextset
 assert max(dist)==4
 assert all(not np.any(abs(phi[dist>t])>1e-10) for t,phi in enumerate(hist))
 counts=[int(sum(dist==i)) for i in range(5)]
 Lphys=10.;k=2*math.pi/Lphys
 rows=[]
 for N in (8,16,32,64,128):
  a=Lphys/N
  lam=(2*math.sin(math.pi/N)/a)**2
  rows.append(dict(N=N,spatial_sites=N**3,relative_error=lam/k**2-1,
   stability_step_limit=2/math.sqrt(12/a**2+.08)))
  print('SPATIAL',N,'error',rows[-1]['relative_error'],flush=True)
 assert abs(rows[-1]['relative_error'])<.0003
 result=dict(status='PASS',W33_diameter=4,graph_distance_shells=counts,
  leapfrog_graph_locality_verified_for_times=list(range(7)),
  W33_normalized_Laplacian_spectrum=[0,1-math.sqrt(6)/4,1,1+math.sqrt(6)/4,2],
  external_three_dimensional_spatial_lattice=rows,
  mathematical_distinction='Local leapfrog updates have zero support beyond t graph edges after t steps. The graph reaches all 80 vertices within 4 steps and provides no Lorentzian 3+1 continuum.',
  external_model='An imposed spatial lattice C_N^3 and external time coordinate yield omega squared = (4 c²/a²) sum sin²(k_i a/2) + mu² lambda_internal, converging to c²|k|² + mu²lambda_internal. Its 3+1 dimension is ASSUMED, not generated by W33.',
  negative_finding='No four-dimensional gravitational field, Minkowski metric, spin-2 excitation or emergent light cone arises from native W33 adjacency alone.',
  provenance='Existing Round27 normalized graph heat no-go and October8 externally imposed torus were already in repository. New explicit finite-step graph-wave propagation and continuum comparison.')
 OUT.write_text(json.dumps(result,indent=2)+'\n');return result
if __name__=='__main__':run()
