#!/usr/bin/env python3
"""Passes 4025-4032: physics-first audit of the W33 photon computer.

This verifier closes four exact physics fronts, records the externally queued
algebra front, and freezes three falsifiers required before promoting the
architecture as a universal physical computer or theory of everything.
"""
from __future__ import annotations
import hashlib,itertools,json,math
from pathlib import Path
import networkx as nx
import numpy as np
import sympy as sp
ROOT=Path(__file__).resolve().parents[1]
OUT=ROOT/'data/PART_4025_4032_PHYSICS_FIRST_UNIVERSAL_COMPUTER.json'
def sha(x):return hashlib.sha256(json.dumps(x,sort_keys=True,separators=(',',':')).encode()).hexdigest()
def norm(v):
 v=tuple(x%3 for x in v)
 for x in v:
  if x:return tuple((1 if x==1 else 2)*y%3 for y in v)
 raise ValueError
def symp(u,v):return (u[0]*v[2]+u[1]*v[3]-u[2]*v[0]-u[3]*v[1])%3
def build():
 pts=sorted({norm(v) for v in itertools.product(range(3),repeat=4) if any(v)})
 W=nx.Graph();W.add_nodes_from(range(40))
 for i,u in enumerate(pts):
  for j in range(i+1,40):
   if symp(u,pts[j])==0:W.add_edge(i,j)
 lines=sorted(tuple(sorted(c)) for c in nx.find_cliques(W) if len(c)==4);assert len(lines)==40
 N=np.zeros((40,40))
 for j,line in enumerate(lines):
  for i in line:N[i,j]=1
 A=N@N.T-4*np.eye(40);assert np.allclose(A.sum(1),12)
 L=nx.Graph();L.add_nodes_from(range(80));edges=[]
 for j,line in enumerate(lines):
  for p in line:L.add_edge(p,40+j);edges.append((p,40+j))
 edges=sorted(edges);D=np.zeros((80,160))
 for k,(p,l) in enumerate(edges):D[p,k]=-1;D[l,k]=1
 Xg=nx.line_graph(L)
 return W,L,Xg,N,A,D
def error_budget():
 d,t=sp.symbols('d t',real=True);d0=2*sp.sqrt(2);t0=sp.pi/sp.sqrt(2)
 def amp(s):
  o=sp.sqrt(d*d+4*s*s)
  return sp.exp(-sp.I*d*t/2)*(sp.cos(o*t/2)+sp.I*d*sp.sin(o*t/2)/o)
 def leak(s):
  o=sp.sqrt(d*d+4*s*s);return 4*s*s*sp.sin(o*t/2)**2/o**2
 tr=15+amp(4)-24*amp(sp.sqrt(6));F=sp.re(tr*sp.conjugate(tr))/1600
 P=(leak(4)+24*leak(sp.sqrt(6)))/40;v=[d,t]
 HF=sp.Matrix([[sp.simplify(sp.diff(F,a,b).subs({d:d0,t:t0})) for b in v] for a in v])
 HP=sp.Matrix([[sp.simplify(sp.diff(P,a,b).subs({d:d0,t:t0})) for b in v] for a in v])
 assert HF==sp.Matrix([[-323*sp.pi**2/5184,-17*sp.pi/36],[-17*sp.pi/36,-8]])
 assert HP==sp.Matrix([[149*sp.pi**2/5184,17*sp.pi/36],[17*sp.pi/36,8]])
 return {'coordinates':{'delta_d':'delta(Delta/g)','delta_tau':'delta(g t)'},'target':{'Delta_over_g':'2*sqrt(2)','g_t':'pi/sqrt(2)'},'infidelity_second_order':'1-F_e = 1/2[(323*pi^2/5184) dd^2 + 2(17*pi/36) dd dtau + 8 dtau^2] + O(3)','leakage_second_order':'P_leak = 1/2[(149*pi^2/5184) dd^2 + 2(17*pi/36) dd dtau + 8 dtau^2] + O(3)','phase_residual':'(1-F_e)-P_leak = (29*pi^2/1728) dd^2 + O(3)','optimal_retiming':'delta_tau = -(17*pi/288) delta_d','retimed_infidelity':'(119*pi^2/6912) delta_d^2 + O(3)','retimed_leakage':'(pi^2/2304) delta_d^2 + O(3)','tolerance_1e-3':{'pure_timing_relative':0.00711762543417177,'pure_detuning_relative':0.020162824357454635,'retimed_detuning_relative':0.027122737316768977},'boundary':'Local quadratic uniform-control budget; loss and correlated disorder excluded.'}
def compiler(N):
 H=np.block([[np.zeros((40,40)),N],[N.T,np.zeros((40,40))]])
 alpha=-3/20+4*np.sqrt(6)/15;beta=1/40-np.sqrt(6)/60
 P=alpha*H+beta*np.linalg.matrix_power(H,3);w,V=np.linalg.eigh(H);S=(V*np.where(abs(w)>1e-9,np.sign(w),0))@V.T
 err=float(np.linalg.norm(P-S,2));assert err<1e-12
 return {'H':'H_L=[[0,N],[N^T,0]]','X':'sign(H_L) on bright sectors, zero on kernel','polynomial':'X=alpha H_L+beta H_L^3','alpha':'-3/20+4sqrt(6)/15','beta':'1/40-sqrt(6)/60','numerical_alpha':float(alpha),'numerical_beta':float(beta),'T':'N^T(alpha I+beta N N^T)','operator_error':err,'reading':'Exact cubic spectral transform: one sparse incidence traversal plus a three-hop correction.','boundary':'Algebraic compiler, not yet a passive finite-depth hardware synthesis.'}
def bridge(D):
 P=np.eye(160)-np.linalg.pinv(D)@D;Q=np.eye(160)-P
 assert round(np.trace(P))==81 and np.linalg.matrix_rank(D)==79
 e=np.eye(160)[:,0];V=P@np.outer(e,e)@Q;s=float(np.linalg.svd(V,compute_uv=False)[0])
 assert abs(s-math.sqrt(81*79)/160)<1e-12
 return {'no_go':'The algebra generated by D,D^T preserves im(D^T) and ker(D); incidence-only linear dynamics cannot write cut/mode information into H1.','dimensions':{'mode':80,'links':160,'cut':79,'H1':81},'local_port':'V_e=P_H1|e><e|P_cut','rank':1,'singular_value':'sqrt(81*79)/160','singular_value_numeric':s,'strength_squared':'6399/25600','uniform_port':'P_H1 I P_cut=0','reading':'Controlled local detuning is a rank-one write/read port; symmetry breaking is required.','boundary':'No complete pulse or fault-tolerance proof.'}
def ds_w33(t):
 z=1+24*np.exp(-10*t)+15*np.exp(-16*t);return 2*t*(240*np.exp(-10*t)+240*np.exp(-16*t))/z
def ds_line(t):
 vals=[0,4-np.sqrt(6),4,4+np.sqrt(6),8];mul=[1,24,30,24,81]
 z=sum(m*np.exp(-l*t) for m,l in zip(mul,vals));return 2*t*sum(m*l*np.exp(-l*t) for m,l in zip(mul,vals))/z
def main():
 W,L,X,N,A,D=build();assert nx.diameter(W)==2 and nx.diameter(L)==4 and nx.diameter(X)==4
 x={'schema':'w33.pass4025_4032.physics_first_universal_computer.v1','status':'PASS_EXACT_PHYSICS_FIRST_FIVE_FRONT_THREE_BONKERS_TOE_NOT_ESTABLISHED','pass4025_exact_revival_error_budget':error_budget(),'pass4026_exact_polar_compiler':compiler(N),'pass4027_mode_H1_bridge':bridge(D),'pass4028_noise_aware_tomography':{'model':'Q=cI+theta(12I-A)+E','center':'C=Q-(TrQ/40)I=-theta A+E_c','scale':'theta_hat=||C||_F/sqrt(480)','recovery':'A=-C/theta_hat','checksum':'(C+12theta I)(C+2theta I)(C-4theta I)=0','common_delay_invariant':True,'edge_recovery_condition':'||E_c||_max<theta/4 and ||E_c||_F/sqrt(480)<theta/4 imply exact threshold recovery at theta_hat/2.','spectral_stability':'||E_c||_2<3theta keeps all three clusters disjoint.','probe_counts':{'full_real_symmetric':820,'ideal_parameters':2},'boundary':'Deterministic norm theorem; no experimental noise model or RIP proof.'},'pass4029_algebra_execution':{'pull_request':281,'run_id':31105713885,'status':'queued','relation_output':False,'monster_output':False,'boundary':'Launched with artifact capture, but queued is not executed and no algebra result is promoted.'},'pass4030_causality_speed':{'diameters':{'W33':2,'Levi':4,'line_graph':4},'short_time':'Distance-r amplitudes start at order t^r for local adjacency dynamics.','no_go':'A fixed diameter-four cell cannot itself supply macroscopic locality or a continuum light cone.','LR_scale':'v_LR<=C_graph aJ/hbar; refinement must keep aJ controlled and node count alone cannot determine c.','gate_time':'pi/(sqrt(2)g)','Delta_E':'2 hbar g','E_above_ground':'2sqrt(2) hbar g','QSL':{'MT':'pi/(4g)','ML':'pi/(4sqrt(2)g)','gate_over_MT':2*np.sqrt(2),'gate_over_ML':4},'vertex_target_overlap':'1/5','generalized_MT_ratio':float((np.pi/np.sqrt(2))/(np.arccos(.2)/2)),'boundary':'Internal speed budget, not vacuum c.'},'pass4031_spectral_dimension':{'W33_Z':'1+24e^-10t+15e^-16t','W33_ds_max':{'t':0.25879990039091844,'value':float(ds_w33(0.25879990039091844))},'line_graph_ds_max':{'t':1.6024931717003175,'value':float(ds_line(1.6024931717003175))},'limits':'d_s->0 in both UV and IR for every fixed finite graph; no four-dimensional Weyl plateau.','tensor':'Z_m=Z^m and d_s,m=m d_s, multiplying rather than selecting dimension.','obligation':'Need a refinement/RG family with Z~t^-2 over a stable window plus Lorentzian causal observables.','boundary':'Finite cell is an internal spectral factor, not spacetime.'},'pass4032_thermodynamic_holographic_capacity':{'H1_dimension':81,'frame_vectors':1620,'redundancy':20,'capacity_bits':math.log2(81),'Landauer':'Q_erase>=k_B T ln(81)','Landauer_nats':math.log(81),'frame_warning':'1620 compact states are overcomplete, not 1620 orthogonal messages; capacity stays <=log2(81).','Bekenstein_status':'Cannot test without physical E,R/area,species and encoder/decoder restrictions.','ledger':{'programmable_three_sector_unitaries':'proved in controlled model','protected_H1_memory':'proved in symmetric model','preparation_readout':'synthetic; lab pending','entangling_operations':'conditional remote qutrit SUM exists','non_Clifford_FT_injection':'not proved; M36_Q4_RAW remains fail-closed','scalable_locality':'not proved','thermodynamic_budget':'lower bounds only','continuum_gravity_functor':'absent','Standard_Model_functor':'not theorem-grade'},'verdict':'Strong finite quantum-information architecture; THE universal computer and TOE remain hypotheses with explicit unmet obligations.'},'primary_sources':['Margolus-Levitin quant-ph/9710043','Reeb-Wolf 1306.4352','Bisio-D Ariano-Tosini 1212.2839','Jacobson 1505.04753 and gr-qc/9504004','Pastawski et al. 1503.06237','Chamseddine-Connes hep-th/9606001'],'boundaries':['Exact finite-dimensional statements only.','No fabricated device, universal fault-tolerant gate set, emergent Lorentz invariance, Einstein equation, Standard Model functor, scale derivation, Monster embedding, or TOE is claimed.']}
 x['semantic_sha256']=sha(x);assert x['semantic_sha256']=='cc50a83926bd9d32770c33dcfb48ba04640d3601a3fbf64b29f34bb22f940a2f';OUT.write_text(json.dumps(x,indent=2,sort_keys=True)+'\n');print('PASS_4025_4032_PHYSICS_FIRST',x['semantic_sha256'])
if __name__=='__main__':main()
