"""Pass 11651: the n-qutrit Hesse space -- the dual even Weil representation, G4 at one qutrit, G33 at two, and the
40 stabiliser bases as the generalized quadrangle of order 3.

THE SPACE.  The Heisenberg-invariant symmetric cubic tensors on (C^3)^(x n): the diagonal sum_a e_a^(x3) and, for each
direction +-d in F3^n, the symmetrised sum over the lines {a, a+d, a-d}.  Dimension 1 + (3^n - 1)/2 = (3^n + 1)/2 (2 for
one qutrit: Pass 11641's Hesse doublet; 5 for two qutrits).  u(psi) = B^T psi^(x3) is a Clifford-covariant cubic map.

FOUND HERE (n = 1, 2).
  * The Clifford group preserves the space; its action is projectively the DUAL (complex-conjugate) EVEN WEIL
    representation: spectra match those of conj(V(g)) on the parity-even subspace for every sampled Weil word (n = 2: 60
    of 60; the unconjugated even Weil rep fails).
  * n = 1: the linear group generated has order 48 and is generated by its 14 reflections (orders 2 and 3; the Fourier
    image R(F) is itself an order-2 reflection), with invariant dimensions matching degrees 4 and 12: Shephard-Todd G6.
    n = 2: the linear group generated has order 103680 with 4 scalars; its 45 reflections all have order 2 and generate a
    group of order exactly 51840 whose invariant dimensions in degrees 2, 4, 6, 8, 10, 12 are 0, 1, 1, 1, 2, 3 -- the
    Molien series of Shephard-Todd G33 (degrees 4, 6, 10, 12, 18), the symmetry group of the Burkhardt quartic.
    Classically: n = 1 is the Hesse pencil (elliptic curves with level-3 structure), n = 2 the Heisenberg-invariant
    (Coble) cubics in P^8 (abelian surfaces with level-3 structure).  The qutrit reading is new here.
  * The 40 two-qutrit stabiliser bases (Lagrangian planes) each map to ONE ray (Heisenberg acts trivially).  Their
    overlaps are |<u_a, u_b>|^2 = 1/3 when the planes meet in a line and 1/9 when they meet in 0; the 1/3-graph is
    strongly regular (40, 12, 2, 4).  It is the collinearity graph of Q(4,3) -- the DUAL of W(3,3), whose points are the
    lines of W(3,3) -- and NOT the W(3,3) point graph: its non-adjacent pairs are antiregular (|{x,y}^perp perp| = 2),
    while every pair of W(3,3) points is regular (4).  Both are SRG(40,12,2,4); for odd q they are non-isomorphic.
  * |u|^2 is affine in the stabiliser third moment M3 = sum_s |<s|psi>|^6: n = 1: |u|^2 = M3 - 1; n = 2:
    |u|^2 = (M3 - 2)/6 (residual 1e-15).  This is the Gross-Nezami-Walter structure of the third tensor power of the
    Clifford group (arXiv:1712.08628); Pass 11641's (b) is its n = 1 case.
  * Pass 11641's LINEAR law (Bloch data = stabiliser triple products) does NOT extend: at n = 2 the Hermitian form u u^dag
    is not in the span of the 480 stabiliser line triple products (residual ~1e-2 at full rank 480) -- interference
    between parallel lines enters.
"""

from __future__ import annotations

import itertools
import json
import sys
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "data" / "w33_pass11651_n_qutrit_hesse_space.json"
w = np.exp(2j * np.pi / 3)
X1 = np.roll(np.eye(3), 1, axis=0)
Z1 = np.diag([1, w, w * w])
F1 = np.array([[w ** (a * b) for b in range(3)] for a in range(3)]) / np.sqrt(3)
D1 = np.diag([w ** (2 * j * j) for j in range(3)])
I3 = np.eye(3)


def kron_all(ms):
    out = np.eye(1)
    for m in ms:
        out = np.kron(out, m)
    return out


def setup(n):
    d = 3 ** n
    pts = list(itertools.product(range(3), repeat=n))
    idx = {p: i for i, p in enumerate(pts)}

    def add(a, b, s=1):
        return tuple((x + s * y) % 3 for x, y in zip(a, b))
    dirs = []
    for v in pts:
        if any(v) and tuple((-x) % 3 for x in v) not in dirs:
            dirs.append(v)
    tens = []
    T0 = np.zeros((d, d, d))
    for a in pts:
        T0[idx[a], idx[a], idx[a]] = 1
    tens.append(T0)
    for v in dirs:
        T = np.zeros((d, d, d))
        for a in pts:
            tr = (idx[a], idx[add(a, v)], idx[add(a, v, -1)])
            for p in itertools.permutations(tr):
                T[p] += 1
        tens.append(T)
    B = np.stack([t.ravel() / np.linalg.norm(t) for t in tens], 1)
    wg = {}
    for i in range(n):
        wg[f"F{i}"] = kron_all([F1 if j == i else I3 for j in range(n)])
        wg[f"D{i}"] = kron_all([D1 if j == i else I3 for j in range(n)])
    if n == 2:
        wg["CZ"] = np.diag([w ** (a[0] * a[1]) for a in pts])
    return d, pts, idx, B, wg


def R_of(B, g):
    return B.conj().T @ np.kron(np.kron(g, g), g) @ B


def closure(gl, cap=300000):
    def key(M):
        return hash((np.round(M, 6) + 0.0).tobytes())
    I = np.eye(gl[0].shape[0], dtype=complex)
    seen = {key(I): I}
    frontier = [I]
    while frontier and len(seen) < cap:
        new = []
        for M in frontier:
            for g in gl:
                P = g @ M
                k = key(P)
                if k not in seen:
                    seen[k] = P
                    new.append(P)
        frontier = new
    return list(seen.values())


def is_reflection(M):
    return int(np.sum(np.abs(np.linalg.eigvals(M) - 1) > 1e-6)) == 1


def weyl(v, n):
    return kron_all([np.linalg.matrix_power(X1, v[2 * i]) @ np.linalg.matrix_power(Z1, v[2 * i + 1]) for i in range(n)])


def stabiliser_bases(n):
    def om(u, v):
        return sum(u[2 * i] * v[2 * i + 1] - u[2 * i + 1] * v[2 * i] for i in range(n)) % 3
    vecs = [v for v in itertools.product(range(3), repeat=2 * n) if any(v)]
    lag = set()
    for gens in itertools.combinations(vecs, n):
        if all(om(a, b) == 0 for a, b in itertools.combinations(gens, 2)):
            span = frozenset(tuple(sum(c * g[i] for c, g in zip(cs, gens)) % 3 for i in range(2 * n))
                             for cs in itertools.product(range(3), repeat=n))
            if len(span) == 3 ** n:
                lag.add(span)
    lag = list(lag)
    rng = np.random.default_rng(0)
    bases = []
    for L in lag:
        nz = [v for v in L if any(v)]
        Hm = sum(rng.normal() * (weyl(v, n) + weyl(v, n).conj().T) + rng.normal() * 1j * (weyl(v, n) - weyl(v, n).conj().T)
                 for v in nz)
        _, V = np.linalg.eigh(Hm)
        bases.append(V)
    return lag, bases


def run_n(n, rng):
    d, pts, idx, B, wg = setup(n)
    out = dict(dimension=B.shape[1], formula_half_3n_plus_1=(3 ** n + 1) // 2)
    gl = [R_of(B, g) for g in wg.values()]
    out["Clifford_preserves_space"] = all(np.allclose(B @ R_of(B, g), np.kron(np.kron(g, g), g) @ B) for g in wg.values())
    # dual even Weil representation
    neg = np.zeros((d, d))
    for a in pts:
        neg[idx[tuple((-x) % 3 for x in a)], idx[a]] = 1
    ev, Ve = np.linalg.eigh((np.eye(d) + neg) / 2)
    Ve = Ve[:, ev > 0.5]

    def match(A, Bm):
        ea, eb = np.linalg.eigvals(A), np.linalg.eigvals(Bm)
        for ph in eb:
            c = ph / ea[0]
            if all(np.min(np.abs(eb - c * x)) < 1e-7 for x in ea):
                return True
        return False
    names = list(wg)
    direct = conj = 0
    for _ in range(60):
        g = np.eye(d, dtype=complex)
        for i in rng.integers(0, len(names), size=rng.integers(1, 8)):
            g = wg[names[i]] @ g
        Rg = R_of(B, g)
        Eg = Ve.conj().T @ g @ Ve
        direct += match(Rg, Eg)
        conj += match(Rg, Eg.conj())
    out["spectra_match_even_Weil"] = direct
    out["spectra_match_conjugate_even_Weil"] = conj
    out["words"] = 60
    Gfull = closure(gl)
    refl = [M for M in Gfull if is_reflection(M)]
    out["linear_group_order"] = len(Gfull)
    out["scalars_in_group"] = int(sum(np.allclose(M, M[0, 0] * np.eye(len(M))) for M in Gfull))
    out["reflections"] = len(refl)
    from collections import Counter as _C
    out["reflections_by_order"] = dict(_C(int(round(2 * np.pi / abs(np.angle([e for e in np.linalg.eigvals(M) if abs(e - 1) > 1e-6][0])))) for M in refl))
    out["reflection_orders"] = sorted({int(round(2 * np.pi / abs(np.angle([e for e in np.linalg.eigvals(M) if abs(e - 1) > 1e-6][0]))))
                                       for M in refl})
    Gr = closure(refl) if refl else []
    out["order_generated_by_reflections"] = len(Gr)
    # invariant dimensions of the reflection group by Reynolds rank
    GrA = np.array(Gr)
    P0 = rng.normal(size=(60, B.shape[1])) + 1j * rng.normal(size=(60, B.shape[1]))
    imgs = np.einsum("gij,pj->gpi", GrA, P0)
    dims = {}
    for deg in range(1, 13):
        rows, scale = [], 0.0
        for _ in range(12):
            l = rng.normal(size=B.shape[1]) + 1j * rng.normal(size=B.shape[1])
            vals = (imgs @ l) ** deg
            scale = max(scale, float(np.abs(vals).mean()))
            rows.append(vals.mean(0))
        s = np.linalg.svd(np.array(rows), compute_uv=False)
        dims[deg] = int((s > 1e-9 * scale).sum())
    out["invariant_dims_by_degree"] = dims
    # stabiliser bases
    lag, bases = stabiliser_bases(n)
    out["stabiliser_bases"] = len(lag)
    U = []
    for V in bases:
        us = [B.T @ np.kron(np.kron(V[:, k], V[:, k]), V[:, k]) for k in range(d)]
        assert all(abs(abs(np.vdot(us[0], x)) - np.linalg.norm(us[0]) * np.linalg.norm(x)) < 1e-9 for x in us)
        U.append(us[0] / np.linalg.norm(us[0]))
    U = np.array(U)
    Gm = np.abs(U.conj() @ U.T) ** 2
    vals = sorted(set(np.round(Gm[~np.eye(len(U), dtype=bool)], 8).tolist()))
    out["basis_point_overlaps"] = vals
    graphs = {}
    for v in vals:
        A = (np.abs(Gm - v) < 1e-6) & ~np.eye(len(U), dtype=bool)
        lam = {int((A[i] & A[j]).sum()) for i in range(len(U)) for j in range(len(U)) if i != j and A[i, j]}
        mu = {int((A[i] & A[j]).sum()) for i in range(len(U)) for j in range(len(U)) if i != j and not A[i, j]}
        graphs[str(v)] = dict(degree=sorted(set(A.sum(1).tolist())), lam=sorted(lam), mu=sorted(mu))
    out["overlap_graphs"] = graphs
    if n == 2:
        # which GQ(3,3)?  W(3,3) points are regular (|{x,y}^perp perp| = 4); Q(4,3) points (W(3,3) lines) antiregular (2)
        def regularity(A):
            res_ = set()
            for x in range(len(A)):
                for y in range(len(A)):
                    if x != y and not A[x, y]:
                        Tn = [zz for zz in range(len(A)) if A[x, zz] and A[y, zz]]
                        res_.add((len(Tn), len([q for q in range(len(A)) if all(A[q, tt] for tt in Tn)])))
            return sorted(res_)
        A3 = (np.abs(Gm - 1 / 3) < 1e-6) & ~np.eye(len(U), dtype=bool)
        P40 = [v for v in itertools.product(range(3), repeat=4) if any(v) and next(x for x in v if x) == 1]
        omg = lambda a, b: (a[0] * b[1] - a[1] * b[0] + a[2] * b[3] - a[3] * b[2]) % 3
        Aw = np.array([[i != j and omg(P40[i], P40[j]) == 0 for j in range(40)] for i in range(40)])
        out["regularity_stabiliser_rays"] = regularity(A3)
        out["regularity_W33_point_graph"] = regularity(Aw)
        out["which_GQ"] = ("Q(4,3) (antiregular): the lines of W(3,3), NOT the W(3,3) point graph"
                           if out["regularity_stabiliser_rays"] == [(4, 2)] else "other")
    inter = sorted({(len(set(lag[i]) & set(lag[j])), round(float(Gm[i, j]), 6)) for i in range(len(lag)) for j in range(len(lag)) if i != j})
    out["intersection_size_vs_overlap"] = inter
    # norm vs stabiliser third moment
    allst = np.concatenate(bases, 1)
    A_, y_ = [], []
    for _ in range(300):
        psi = rng.normal(size=d) + 1j * rng.normal(size=d)
        psi /= np.linalg.norm(psi)
        u = B.T @ np.kron(np.kron(psi, psi), psi)
        A_.append([1, (np.abs(allst.conj().T @ psi) ** 6).sum()])
        y_.append(float(np.vdot(u, u).real))
    c, *_ = np.linalg.lstsq(np.array(A_), np.array(y_), rcond=None)
    out["norm_affine_in_M3"] = dict(a=float(c[0]), b=float(c[1]), max_residual=float(np.abs(np.array(A_) @ c - y_).max()))
    return out, B, bases, lag


def triple_product_test(B, bases, lag, rng, n=2):
    d = 3 ** n
    labels = []
    for L, V in zip(lag, bases):
        nz = [v for v in L if any(v)]
        u1 = nz[0]
        u2 = next(v for v in nz if not any(tuple((c * x) % 3 for x in u1) == v for c in range(3)))
        l1 = [np.vdot(V[:, k], weyl(u1, n) @ V[:, k]) for k in range(d)]
        l2 = [np.vdot(V[:, k], weyl(u2, n) @ V[:, k]) for k in range(d)]
        lab = [(int(round(np.angle(l1[k] / l1[0]) / (2 * np.pi / 3))) % 3, int(round(np.angle(l2[k] / l2[0]) / (2 * np.pi / 3))) % 3)
               for k in range(d)]
        assert len(set(lab)) == d
        labels.append(lab)

    def feats(psi):
        out = []
        for V, lab in zip(bases, labels):
            p = np.abs(V.conj().T @ psi) ** 2
            pos = {l: i for i, l in enumerate(lab)}
            lines = {frozenset(tuple((x + t * y) % 3 for x, y in zip(a, dv)) for t in range(3))
                     for a in lab for dv in [(0, 1), (1, 0), (1, 1), (1, 2)]}
            out += [np.prod([p[pos[l]] for l in ln]) for ln in lines]
        return np.array(out)
    Xf, Y = [], []
    for _ in range(1500):
        psi = rng.normal(size=d) + 1j * rng.normal(size=d)
        psi /= np.linalg.norm(psi)
        u = B.T @ np.kron(np.kron(psi, psi), psi)
        Hm = np.outer(u, u.conj())
        Xf.append(feats(psi))
        Y.append(np.concatenate([Hm.real.ravel(), Hm.imag.ravel()]))
    Xf, Y = np.array(Xf), np.array(Y)
    coef, *_ = np.linalg.lstsq(Xf, Y, rcond=None)
    return dict(features=Xf.shape[1], feature_rank=int(np.linalg.matrix_rank(Xf, tol=1e-10)),
                max_residual=float(np.abs(Xf @ coef - Y).max()), typical_entry=float(np.abs(Y).mean()))


def main():
    rng = np.random.default_rng(11651)
    res = dict(pass_id=11651)
    for n in (1, 2):
        out, B, bases, lag = run_n(n, rng)
        if n == 2:
            out["triple_product_law"] = triple_product_test(B, bases, lag, rng)
        res[f"n{n}"] = out
        print(n, out, flush=True)
    json.dump(res, open(OUT, "w"), indent=1, default=str)


if __name__ == "__main__":
    main()
