#!/usr/bin/env python3
"""Pass10669-10676: constructive chain-level C13 intertwiner blueprint.

For the free C13 cover Gamma=Levi(H4) -> Q, Q has 210 vertices, 525 edges and
beta1(Q)=316.  Choose a spanning tree of Q and collapse its lift equivariantly.
The cellular chain complex reduces to

    R^316 --d--> R -> F2 -> 0,

where R=F2[C13]=F2[g]/(g^13-1) and each cotree edge e_j has

    d(e_j)=g^{a_j}-1.

Connectedness means the voltage exponents generate C13. Since 13 is prime,
choose one nonzero exponent as pivot and change clock generator so a_0=1.
Then

    g^a-1=(g-1) q_a,  q_a=1+g+...+g^{a-1}.

Hence for j>0, e_j-q_{a_j}e_0 is a free R-valued cycle. Multiplication by g-1
has one-dimensional kernel spanned by the norm N=1+g+...+g^12, so N e_0 is
the remaining trivial cycle. Thus explicitly

    H1 ~= F2*(N e0) + direct_sum_{j=1}^{315} R*(e_j-q_j e0).

This constructs the Pass10525 module isomorphism after choices. The gauge
freedom is explicit: spanning tree; quotient lift section (C13^209 after fixing
one base vertex); choice of one of 12 clock generators; and choice of pivot
nonzero-voltage cotree edge.
"""
from __future__ import annotations
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
OUT=ROOT/'data/PART_W33_PASS10669_10676_C13_CHAIN_INTERTWINER_BLUEPRINT.json'
P=2;N=13

def add(a,b): return [(x^y) for x,y in zip(a,b)]
def mul(a,b):
    c=[0]*N
    for i,x in enumerate(a):
      if x:
       for j,y in enumerate(b):
        if y:c[(i+j)%N]^=1
    return c

def basis(k):
    v=[0]*N;v[k%N]=1;return v
ONE=basis(0);G=basis(1)

def sub_same(a,b): return add(a,b)  # characteristic two

def rank_f2(cols):
    rows=[[col[r] for col in cols] for r in range(N)]
    m=[sum((bit&1)<<j for j,bit in enumerate(row)) for row in rows]
    rank=0;col=0
    while col<len(cols) and rank<N:
      q=next((i for i in range(rank,N) if (m[i]>>col)&1),None)
      if q is None:col+=1;continue
      m[rank],m[q]=m[q],m[rank]
      for i in range(N):
        if i!=rank and ((m[i]>>col)&1):m[i]^=m[rank]
      rank+=1;col+=1
    return rank

def main():
    gm1=add(G,ONE)
    # multiplication-by-(g-1) matrix columns
    cols=[mul(gm1,basis(k)) for k in range(N)]
    r=rank_f2(cols);assert r==12
    norm=[1]*N
    assert mul(gm1,norm)==[0]*N
    # kernel is exactly the norm line because rank=12 in dimension13.

    # Verify factorization g^a-1=(g-1)(1+...+g^{a-1}) for all nonzero a.
    qs={}
    for a in range(1,N):
      q=[0]*N
      for k in range(a):q[k]=1
      lhs=add(basis(a),ONE);rhs=mul(gm1,q)
      assert lhs==rhs;qs[str(a)]=q

    # Cover counts and dimensions.
    Vq,Eq=210,525;beta=Eq-Vq+1
    assert beta==316
    hdim=1+315*N;assert hdim==4096
    gauge_sections=N**(Vq-1)

    out={
      'schema':'w33.pass10669_10676.c13_chain_intertwiner_blueprint.v1','status':'PASS','passes':'10669-10676',
      'quotient_graph':{'vertices':Vq,'edges':Eq,'beta1':beta,'cover_group':'C13'},
      'group_algebra':{'R':'F2[C13]','dimension':13,'multiplication_g_minus_1_rank':12,'kernel':'F2 * N, N=1+g+...+g^12','augmentation_ideal_dimension':12},
      'collapsed_chain_complex':'R^316 --d--> R -> F2 -> 0, d(e_j)=g^{a_j}-1',
      'pivot_construction':{
        'connectedness':'voltage exponents generate C13; since 13 is prime any nonzero voltage is a generator',
        'normalize':'choose generator and pivot e0 so d(e0)=g-1',
        'factorization':'g^a-1=(g-1)(1+g+...+g^{a-1})',
        'trivial_cycle':'N e0',
        'free_cycles':'e_j - q_{a_j} e0 for j=1,...,315',
        'result':'H1 ~= F2 + R^315','F2_dimension':hdim},
      'gauge_freedom':{
        'spanning_tree':'arbitrary spanning tree of the 210-vertex quotient graph',
        'lift_section_after_base_fix':'C13^209 choices','lift_section_choice_count_decimal':str(gauge_sections),
        'clock_generator_choices':12,
        'pivot':'any cotree edge with nonzero voltage after chosen section/tree',
        'canonicality':'the module isomorphism class is canonical; the displayed basis/intertwiner is choice-dependent'},
      'theorem':'After choosing a quotient spanning tree and one nonzero-voltage pivot edge, the free C13 cover admits an explicit chain-level decomposition H1 = F2*(N e0) plus 315 free F2[C13] summands generated by e_j-q_j e0. This gives a constructive 4096-dimensional intertwiner blueprint to F2[V2], whose one fixed state and 315 free C13 orbits have the same standard module basis.',
      'boundary':'Exact group-algebra construction for the free C13 cover. A numeric 4096x4096 matrix requires choosing an actual spanning tree, lift section and ordering of V2 orbits; those choices are intentionally not called canonical.'}
    OUT.write_text(json.dumps(out,indent=2,sort_keys=True)+'\n')
    print(json.dumps({'status':'PASS','H1':'F2 + R^315','dimension':4096,'section_gauge':'13^209'}))
if __name__=='__main__':main()
