"""TOE36/2: explicit Spin11 adjoint decomposition under triality twist.

The central order3 t_c commuting with spinorial SL(2,9) acts on
R11=R6⊕R5 by equal 2π/3 rotations on 3 orthogonal planes
in R6 and trivially on R5. Its action on so11=Λ² R11
has eigenspace sizes (1:19, omega:18, omega²:18), furnishing
u3⊕so5 commutant. Verify parallel Pass11857 certificate.
This central Z3 is NOT the full 3^4 Minkowski translation
subgroup, and SU3xSO5xU1 is not SM gauge algebra.
"""
from pathlib import Path
import json,math,itertools,numpy as np
ROOT=Path(__file__).resolve().parents[1]
OUT=ROOT/'data/w33_20261010_toe36_spinorial_triality_translation_gate.json'
def wedge2(R):
 n=len(R);ps=list(itertools.combinations(range(n),2))
 W=np.zeros((len(ps),len(ps)))
 for col,(a,b) in enumerate(ps):
  for row,(i,j) in enumerate(ps):
   W[row,col]=R[i,a]*R[j,b]-R[i,b]*R[j,a]
 return W
def run():
 theta=2*math.pi/3;c=math.cos(theta);s=math.sin(theta)
 R=np.eye(11)
 for a,b in ((0,1),(2,3),(4,5)):
  R[np.ix_([a,b],[a,b])]=[[c,-s],[s,c]]
 assert np.linalg.norm(np.linalg.matrix_power(R,3)-np.eye(11))<1e-13
 W=wedge2(R);assert W.shape==(55,55)
 assert np.linalg.norm(W@W.T-np.eye(55))<1e-12
 z=np.linalg.eigvals(W)
 ones=int(np.count_nonzero(abs(z-1)<1e-8))
 w=np.exp(2j*math.pi/3)
 plus=int(np.count_nonzero(abs(z-w)<1e-8))
 minus=int(np.count_nonzero(abs(z-w.conjugate())<1e-8))
 assert (ones,plus,minus)==(19,18,18),(ones,plus,minus)
 # Dimension count for so(11): so(6)+so(5)+(6x5)
 # central u3=9 plus so5=10, other 36 twist in 18+18
 assert 55==15+10+30
 parallel=json.loads((ROOT/'data/w33_pass11854_11857_family_nogo_chirality_firewall_combined.json').read_text())
 assert parallel['combined']['commutant']['dim']==19
 assert parallel['combined']['commutant']['derived_dim']==18
 assert parallel['combined']['commutant']['centre_dim']==1
 assert parallel['combined']['commutant']['structure_su3_u1_so5']
 out=dict(status='PASS',group='spinorial 2.A6=SL2(9) plus central commuting order-3 triality element',
  adjoint_so11_dimension=55,
  SO11_real_vector_twist='R6 rotation by +120° in each of 3 orthogonal 2-planes, R5 pointwise fixed',
  R11_order3_error=float(np.linalg.norm(np.linalg.matrix_power(R,3)-np.eye(11))),
  wedge2_adjoint_eigenmultiplicities={'1':ones,'omega':plus,'omega2':minus},
  exact_commutant_dimension=ones,derived_gauge_algebra='su(3)⊕so(5)',centre='u(1)',
  prior_certificate='data/w33_pass11854_11857_family_nogo_chirality_firewall_combined.json',
  compatibility='The 19-dimensional Spin11 commutant under t_c matches the independent published actual E8 centralizer of SL2(9)×Z3.',
  translation_obstruction='Because t_c commutes with EVERY finite Lorentz generator and has only 3 elements, the group generated by t_c is a central Z3, not an F3^4 of noncentral four spacetime translations. The 19-dim rank5 unbroken gauge algebra is su3+so5+u1, NOT exactly su3+su2+u1. A fully Lorentz-covariant 3^4 translation subgroup still needs distinct explicit generators and commutator tests.',
  scope='This independently verifies the exact 19=9+10 Lie algebra centralizer of the PREVIOUSLY known central Z3; it is not a new SM+finite Poincare embedding. An E8 group centre or triality twist is not a physical translation in 3+1D.')
 OUT.write_text(json.dumps(out,indent=2)+'\n')
 print('TOE36 SPINORIAL TRIALITY eig',ones,plus,minus,'commutant su3+so5',flush=True)
 return out
if __name__=='__main__':run()
