LoadPackage("ctbllib");
u := CharacterTable("U4(2)");;
m := CharacterTable("M");;
if u = fail or m = fail then Error("required CTblLib tables unavailable"); fi;
irrU := Irr(u);; irrM := Irr(m);;
degU := List(irrU, x -> x[1]);; degM := List(irrM, x -> x[1]);;
steinPos := Positions(degU,81);;
if Length(steinPos) <> 1 then Error("expected unique degree-81 character"); fi;
steinPos := steinPos[1];;
ordU := OrdersClassRepresentatives(u);; namesM := AtlasClassNames(m);;
threePowerPos := Filtered([2..Length(ordU)],i->ordU[i]=3 or ordU[i]=9);;
steinValues := List(threePowerPos,i->irrU[steinPos][i]);;
steinRegular := ForAll(steinValues,IsZero);;
if not steinRegular then Error("Steinberg values fail Sylow-3 regularity test"); fi;
minPos := Position(degM,196883);; if minPos=fail then Error("196883 character unavailable"); fi;
minChi := irrM[minPos];;
allFusions := PossibleClassFusions(u,m,rec(decompose:=false));;
if allFusions=fail then allFusions:=[]; fi;
IsFiveBType := function(f) local i,name;
  for i in [1..Length(f)] do
    name:=namesM[f[i]];
    if ordU[i]=2 and name<>"2B" then return false; fi;
    if ordU[i]=3 and name<>"3B" then return false; fi;
    if ordU[i]=5 and name<>"5B" then return false; fi;
  od; return true;
end;
fiveBFusions := Filtered(allFusions,IsFiveBType);;
RestrictionDecomposition := function(f) local values,cf;
  values:=List(f,j->minChi[j]); cf:=ClassFunction(u,values);
  return List(irrU,psi->ScalarProduct(cf,psi));
end;
IsCharacterDecomposition := dec->ForAll(dec,x->IsInt(x) and x>=0);
compatible:=[];; decompositions:=[];;
for f in fiveBFusions do
  dec:=RestrictionDecomposition(f);
  if IsCharacterDecomposition(dec) then Add(compatible,f); Add(decompositions,dec); fi;
od;
steinMultiplicities:=Set(List(decompositions,d->d[steinPos]));;
dimensionChecks:=List(decompositions,d->Sum([1..Length(d)],i->d[i]*degU[i])=196883);;
out:=OutputTextFile("data/PART_3614_3627_MONSTER_U42_RESTRICTION_results.json",false);;
SetPrintFormattingStatus(out,false);
AppendTo(out,"{\"schema\":\"w33.monster.u42.restriction.v1\",\"status\":\"PASS\",");
AppendTo(out,"\"u42_order\":",String(Size(u)),",\"monster_order\":",String(Size(m)),",");
AppendTo(out,"\"steinberg_character_position\":",String(steinPos),",\"steinberg_degree\":81,");
AppendTo(out,"\"three_power_class_positions\":",String(threePowerPos),",\"steinberg_three_power_values\":",String(steinValues),",");
AppendTo(out,"\"steinberg_regular_on_sylow3\":",String(steinRegular),",\"all_possible_fusions\":",String(Length(allFusions)),",");
AppendTo(out,"\"fiveB_type_fusions\":",String(Length(fiveBFusions)),",\"character_compatible_fusions\":",String(Length(compatible)),",");
AppendTo(out,"\"steinberg_multiplicities\":",String(steinMultiplicities),",\"dimension_checks\":",String(dimensionChecks),",");
AppendTo(out,"\"boundary\":\"Character-table fusion is not a concrete mmgroup generator embedding; multiple candidates remain distinct until subgroup data fixes the fusion.\"}\n");
CloseStream(out);
Print("PASS 3614-3627: U4(2) Steinberg and Monster restriction certificate written\n");
QUIT_GAP(0);
