#!/usr/bin/env python3
"""Pass7861-7868: intrinsic Leech top/socle polarity no-go and canonical 4xAG(2,3).

Starting only from the corrected order-9 Leech linking module
    C=(Z/9)^2 +(Z/3)^2
with its standard perfect alternating pairing, classify the full pairing-preserving
automorphism group and its induced actions on top T=C/3C and socle S=C[3].
The key question from Pass7709/7725 is whether the linked module itself canonically
identifies T and S.  It does not: Hom_G(T,S) is one-dimensional and generated by
multiplication by 3, which has rank 2.  The induced degenerate alternating form on
PG(T)=PG(3,3) has a 4-point radical and four 9-point complete components; retaining
its isotropic projective lines upgrades those four 9-sets to four AG(2,3) planes
sharing the same four parallel-class labels.
"""
from __future__ import annotations
import itertools,json
from collections import Counter,deque
from pathlib import Path
import numpy as np

ROOT=Path(__file__).resolve().parents[1]
OUT=ROOT/'data/PART_W33_PASS7861_7868_LEECH_EQUIVARIANT_POLARITY_NOGO.json'
p=3
J=np.array([[0,1],[-1,0]],dtype=int)%p
I2=np.eye(2,dtype=int)%p

def det2(A,m=3):return int(A[0,0]*A[1,1]-A[0,1]*A[1,0])%m
def inv2(A):
    d=det2(A);q=pow(d,-1,3)
    return (q*np.array([[A[1,1],-A[0,1]],[-A[1,0],A[0,0]]],dtype=int))%3

def rref(M,p=3):
    A=np.asarray(M,dtype=int).copy()%p;m,n=A.shape;r=0;piv=[]
    for c in range(n):
        z=next((i for i in range(r,m) if A[i,c]),None)
        if z is None:continue
        A[[r,z]]=A[[z,r]];A[r]=(A[r]*pow(int(A[r,c]),-1,p))%p
        for i in range(m):
            if i!=r and A[i,c]:A[i]=(A[i]-int(A[i,c])*A[r])%p
        piv.append(c);r+=1
    return A,piv

def canon(v):
    v=tuple(int(x)%3 for x in v)
    for x in v:
        if x:return tuple(((1 if x==1 else 2)*y)%3 for y in v)
    raise ValueError

def line(u,v):
    return frozenset(canon(tuple((a*u[i]+b*v[i])%3 for i in range(4)))
                     for a in range(3) for b in range(3) if (a,b)!=(0,0))

def induced_pair(A,D,C):
    L=(A.T@J)%3
    B=(-inv2(L)@(C.T@J@D))%3
    T=np.block([[A,np.zeros((2,2),int)],[C,D]])%3
    S=np.block([[A,B],[np.zeros((2,2),int),D]])%3
    return T,S

def main():
    SL=[]
    for z in itertools.product(range(3),repeat=4):
        A=np.array(z,dtype=int).reshape(2,2)%3
        if det2(A)==1:SL.append(A)
    assert len(SL)==24

    # Exact order of Aut(C,lambda).  Write an automorphism as
    # (a,b)->(A a+3B b, C a_bar+D b).  Pairing preservation gives
    # det(A)+3 det(C)=1 mod 9, D in SL2(3), and then a unique B mod 3.
    lift_hist=Counter()
    for A0 in SL:
      for cz in itertools.product(range(3),repeat=4):
        C=np.array(cz,dtype=int).reshape(2,2)
        target=(1-3*det2(C))%9;n=0
        for xz in itertools.product(range(3),repeat=4):
            X=np.array(xz,dtype=int).reshape(2,2)
            A=(A0+3*X)%9
            if det2(A,9)==target:n+=1
        lift_hist[n]+=1
    assert lift_hist==Counter({27:24*81})
    aut_order=24*81*27*24
    assert aut_order==1259712

    # Generate the induced top/socle representations.  A,D use standard SL2
    # generators; four elementary C's generate the tensor/unipotent layer.
    g1=np.array([[1,1],[0,1]],dtype=int)%3
    g2=np.array([[0,-1],[1,0]],dtype=int)%3
    pairs=[]
    for A,D,C in [(g1,I2,np.zeros((2,2),int)),(g2,I2,np.zeros((2,2),int)),
                  (I2,g1,np.zeros((2,2),int)),(I2,g2,np.zeros((2,2),int))]:
        pairs.append(induced_pair(A,D,C))
    for i in range(2):
      for j in range(2):
        C=np.zeros((2,2),int);C[i,j]=1;pairs.append(induced_pair(I2,I2,C))

    # Solve S_g F = F T_g for all generators, over F3.
    eq=[]
    for T,S in pairs:
      for i in range(4):
       for j in range(4):
        row=[0]*16
        for k in range(4):row[4*k+j]=(row[4*k+j]+int(S[i,k]))%3
        for k in range(4):row[4*i+k]=(row[4*i+k]-int(T[k,j]))%3
        eq.append(row)
    R,piv=rref(eq);free=[i for i in range(16) if i not in piv]
    assert len(free)==1
    x=np.zeros(16,dtype=int);x[free[0]]=1
    for rr,c in enumerate(piv):x[c]=(-sum(int(R[rr,f])*int(x[f]) for f in free))%3
    F=x.reshape(4,4)%3
    M3=np.diag([1,1,0,0]).astype(int)%3
    assert np.array_equal(F,M3) or np.array_equal(F,(-M3)%3)
    assert np.linalg.matrix_rank(F.astype(float))==2
    for T,S in pairs:assert np.array_equal((S@F)%3,(F@T)%3)

    # Cross pairing T x S is diag(J,J); compose with the only equivariant map.
    H=np.block([[J,np.zeros((2,2),int)],[np.zeros((2,2),int),J]])%3
    K=(H@F)%3
    assert np.array_equal((K+K.T)%3,np.zeros((4,4),int))
    assert len(rref(K)[1])==2

    P=sorted({canon(v) for v in itertools.product(range(3),repeat=4) if any(v)})
    A=np.zeros((40,40),dtype=np.int8);rad=[]
    for i,u in enumerate(P):
        uu=np.array(u,dtype=int)
        if all(int(uu@K@np.array(v,dtype=int))%3==0 for v in P):rad.append(i)
        for j in range(i+1,40):
            if int(uu@K@np.array(P[j],dtype=int))%3==0:A[i,j]=A[j,i]=1
    assert len(rad)==4 and Counter(map(int,A.sum(1)))==Counter({12:36,39:4})
    non=[i for i in range(40) if i not in rad];B=A[np.ix_(non,non)]
    assert Counter(map(int,B.sum(1)))==Counter({8:36})
    # Connected components are four K9's.
    comps=[];seen=set()
    for s in range(36):
        if s in seen:continue
        C={s};q=[s];seen.add(s)
        while q:
            u=q.pop()
            for v in np.flatnonzero(B[u]):
                v=int(v)
                if v not in C:C.add(v);seen.add(v);q.append(v)
        comps.append(sorted(C))
    assert sorted(map(len,comps))==[9,9,9,9]
    assert all(np.all(B[np.ix_(C,C)]==np.ones((9,9),int)-np.eye(9,dtype=int)) for C in comps)

    # All K-isotropic projective lines: one radical line plus 48 others.
    lines=set()
    for u,v in itertools.combinations(P,2):lines.add(line(u,v))
    iso=[L for L in lines if all(int(np.array(u)@K@np.array(v))%3==0 for u,v in itertools.combinations(L,2))]
    rset=frozenset(P[i] for i in rad);assert len(iso)==49 and rset in iso
    aff=[L for L in iso if L!=rset];assert len(aff)==48 and all(len(L&rset)==1 for L in aff)

    # Each of the four 9-point components carries exactly 12 traces of those
    # isotropic lines, with four parallel classes indexed by the four radical points.
    ag=[]
    for C in comps:
        pts=frozenset(P[non[i]] for i in C)
        traces=[]
        for L in aff:
            T=frozenset(L&pts)
            if T:assert len(T)==3;traces.append((T,next(iter(L&rset))))
        assert len(traces)==12 and len({x[0] for x in traces})==12
        # Every point pair lies on exactly one affine line.
        for u,v in itertools.combinations(pts,2):assert sum(u in T and v in T for T,_ in traces)==1
        pc=Counter(r for _,r in traces);assert set(pc.values())=={3} and len(pc)==4
        for r in rset:
            block=[T for T,s in traces if s==r];assert len(block)==3 and len(set().union(*map(set,block)))==9
            assert all(not (set(x)&set(y)) for x,y in itertools.combinations(block,2))
        ag.append(12)

    out={
      'schema':'w33.pass7861_7868.leech_equivariant_polarity_nogo.v1','status':'PASS','passes':'7861-7868',
      'module':'C=(Z/9)^2 x (Z/3)^2 with perfect alternating linking form',
      'Aut_C_lambda_order':aut_order,'Aut_factorization':'2^6 * 3^9',
      'top':'C/3C = F3^4','socle':'C[3] = F3^4',
      'equivariant_Hom_dimension':1,'unique_equivariant_map':'scalar multiples of multiplication-by-3','equivariant_map_rank':2,
      'canonical_polarity_nogo':'No invertible top-to-socle identification is intrinsic under the full linked-module automorphism group. A smaller Co0 centralizer could still supply extra data, so this is an intrinsic-module no-go rather than a Co0 no-go.',
      'canonical_rank2_form':{'projective_radical_points':4,'nonradical_points':36,'nonradical_orthogonality_graph':'4 K9','all_isotropic_projective_lines':49,'nonradical_isotropic_lines':48},
      'affine_resolution':{'components':4,'points_per_component':9,'lines_per_component':12,'parallel_classes_per_component':4,'lines_per_parallel_class':3,'identification':'four AG(2,3) planes sharing the same four radical-point/parallel-class labels'},
      'theorem':'The corrected Leech 3-adic linking module does not canonically polarize its two 40-shells. Its unique intrinsic top-to-socle operator is rank-two multiplication by 3, and the resulting degenerate projective symplectic geometry canonically resolves the 36 nonradical points into four AG(2,3) qutrit phase planes.',
      'prior_art_boundary':'Pass7709/7725 classified dual PG(3,3) and all 234 possible nondegenerate polarities. This pass adds the full linked-module equivariance obstruction and the canonical degenerate four-affine-plane geometry.',
      'claim_boundary':'Exact finite abelian-group/linear/projective geometry. No physical qutrit or Leech-to-W33 selection is inferred.'}
    OUT.write_text(json.dumps(out,indent=2,sort_keys=True)+'\n')
    print(json.dumps({'status':'PASS','Aut':aut_order,'Hom_dim':1,'rank':2,'geometry':'4 x AG(2,3)'}))
if __name__=='__main__':main()
