#!/usr/bin/env python3
"""The 1,216,215 three-W33 decompositions as a six-qutrit refactorization graph.

The certified Suzuki/Leech incidence tower has N=1,216,215 unordered orthogonal
decompositions V=U1 perp U2 perp U3 into full W33 4-spaces, with exactly 27
decompositions through each W33.  Define two frames adjacent when they share one
W33 block.  A frame has 3*(27-1)=78 neighbors; distinct frames cannot share two
blocks because the third is the unique symplectic complement.  Hence the graph
has 47,432,385 edges.

For the group closure, let H_U be the stabilizer in Suz of one full W33 U.  The
135135 action identifies H_U as the maximal subgroup 2_-^{1+6}:U4(2).  For two
distinct blocks U,V in one decomposition, H_U and H_V are distinct conjugate
maximal subgroups.  Therefore <H_U,H_V>=Suz: a subgroup containing maximal H_U
is either H_U or Suz, and H_V is not contained in H_U (same order would force
equality).  Lifting the projective Suzuki action to the exact 12-dimensional
symplectic representation gives 2.Suz <= Sp(12,3).

Thus the complete library of local refactorization moves that keep one W33 block
fixed generates the full 2.Suz sporadic Clifford subgroup.  It does NOT generate
all of Sp(12,3): the exact index is 16054507443872541110987520.

This is a finite group/compiler theorem.  It does not say physical hardware can
implement these moves, nor that the moves are non-Clifford/universal quantum gates.
"""
from __future__ import annotations
import json,math
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
OUT=ROOT/'data'/'w33_suzuki_refactorization_compiler.json'

def sp_order(n,q):
    # |Sp(2n,q)|=q^(n^2) prod_i(q^(2i)-1)
    z=q**(n*n)
    for i in range(1,n+1):z*=q**(2*i)-1
    return z

def main(write=True):
    frames=1216215; through_block=27; blocks_per_frame=3
    degree=blocks_per_frame*(through_block-1);assert degree==78
    edges=frames*degree//2;assert edges==47432385
    suz=448345497600;twosuz=2*suz
    sp=sp_order(6,3);assert sp==14395932257291877030764312963579904000
    idx=sp//twosuz;assert sp%twosuz==0 and idx==16054507443872541110987520
    # Stabilizer orders from orbit-stabilizer.
    h=suz//135135; k=suz//frames
    assert h==3317760 and k==368640
    out={
      'schema':'w33.suzuki_refactorization_compiler.v1','status':'PASS',
      'headline':'The 1,216,215 three-W33 decompositions form a natural degree-78 refactorization graph with 47,432,385 edges. The group generated by the complete local move libraries fixing the W33 blocks of one frame is Suz projectively and 2.Suz in the 12-dimensional F3 symplectic lift. This is a large six-qutrit Clifford subgroup, but has index 16054507443872541110987520 in Sp(12,3).',
      'frame_graph':{'vertices':frames,'blocks_per_frame':3,'frames_through_each_block':through_block,'degree':degree,'edges':edges,'adjacency':'share exactly one W33 block'},
      'stabilizers':{'Suz_order':suz,'W33_stabilizer_order':h,'decomposition_stabilizer_order':k,'W33_stabilizer_shape':'2_-^(1+6):U4(2)','decomposition_stabilizer_shape':'2^(2+8):(A5 x S3)'},
      'move_group':{'projective':'Suz','symplectic_lift':'2.Suz','order_2Suz':twosuz,'argument':'two distinct W33 stabilizers are distinct conjugate maximal subgroups; maximality forces their generated subgroup to be Suz'},
      'six_qutrit_clifford':{'Sp12_3_order':sp,'index_of_2Suz':idx,'full_Clifford_generated':False},
      'boundary':'The theorem concerns exact finite symplectic/permutation actions. Refactorization moves are Clifford operations in this model and do not by themselves provide non-Clifford magic or physical implementability.',
      'checks':{'degree_78':True,'edges_47432385':True,'stabilizer_orders':True,'Sp_order':True,'index_exact':True}}
    if write:OUT.write_text(json.dumps(out,indent=2)+'\n')
    print(json.dumps(out,indent=2));return out
if __name__=='__main__':main(True)
