#!/usr/bin/env python3
"""Compute the full PGSp-equivariant Hom spaces among the three mod-3 St81 models.

The three models are:
  C = canonical [[240,81,3]]_3 CSS logical Steinberg,
  E = common reduction of the two rational outer-even obstruction channels,
  O = reduction of the rational outer-odd obstruction channel.

All three are the same restricted PSp4(3) Steinberg module in the common W33
building-cycle coordinates.  A prior exact defining-characteristic Schur audit
proves End_{PSp}(St81)=F3, so every PSp-equivariant Hom between two copies is
one-dimensional and generated by the common-coordinate identity.

The corrected outer-transport certificate gives

    C : +S,   E : -S,   O : +S.

Therefore the full PGSp Hom problem is no longer a large matrix solve: the
only possible PSp intertwiner is c I, and the outer equation decides whether
that scalar survives.  Same outer sign => dimension 1.  Opposite outer sign =>
0 because 2 != 0 in F3 and S is invertible.

For auditability this script regenerates the frozen scalar-centralizer
certificate if it is absent, reads the exact chain/transport certificates, and
materializes the complete directed Hom-dimension tables.
"""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SCHUR = ROOT / 'data/PART_W33_PASS7513_7516_STEINBERG_F3_CENTRALIZER.json'
CHAIN = ROOT / 'data/PART_W33_20260901_BUILDING_CHAIN_INJECTIONS.json'
MOD = ROOT / 'data/PART_W33_20260902_MOD3_PGSP_EXTENSION_TWIN.json'
BRIDGE = ROOT / 'data/PART_W33_20260902_MOD3_EVEN_GLUING_CSS_BRIDGE.json'
OUT = ROOT / 'data/PART_W33_20260902_PGSP_MOD3_HOM_SPACES.json'


def relsign(name: str) -> int:
    if name == '+S':
        return 1
    if name == '-S':
        return -1
    raise ValueError(name)


def main():
    # The old pass script is theorem-grade but its JSON was historically
    # gitignored on some branches.  Regenerate it deterministically if needed.
    if not SCHUR.exists():
        import w33_pass7513_7516_steinberg_f3_centralizer as schur
        schur.main()
    schur = json.loads(SCHUR.read_text())
    chain = json.loads(CHAIN.read_text())
    mod = json.loads(MOD.read_text())
    bridge = json.loads(BRIDGE.read_text())

    assert schur['status'] == 'PASS'
    assert schur['Steinberg_dimension'] == 81
    assert schur['centralizer_dimension_F3'] == 1
    assert schur['operator_algebra_dimension'] == 6561
    assert chain['status'] == 'PASS'
    assert chain['W33_H1_81']['H1Dimension'] == 81
    assert len(chain['W33_H1_81']['primitiveInjections']) == 3
    assert mod['status'] == 'PASS' and mod['field'] == 'F3'
    assert mod['allThreeImagesOuterInvariant'] is True
    assert bridge['status'] == 'PASS'
    assert bridge['cssBridge']['bothRanks'] == 81

    t = mod['solvedTransports']
    signs = {
        'CSS': relsign(t['CSSLogicalSteinberg']['relationToBuildingOuterS']),
        'obstructionEven': relsign(t['obstructionCommonEvenReduction']['relationToBuildingOuterS']),
        'obstructionOdd': relsign(t['obstructionOddReduction']['relationToBuildingOuterS']),
    }
    assert signs == {'CSS': 1, 'obstructionEven': -1, 'obstructionOdd': 1}

    names = ['CSS', 'obstructionEven', 'obstructionOdd']
    psp = {a: {b: 1 for b in names} for a in names}
    pgsp = {}
    generators = {}
    for a in names:
        pgsp[a] = {}
        generators[a] = {}
        for b in names:
            same = signs[a] == signs[b]
            pgsp[a][b] = 1 if same else 0
            generators[a][b] = (
                'common-coordinate scalar maps c*I, c in F3' if same else
                'zero only; the unique PSp line is outer-anti-equivariant'
            )

    # The important cross-carrier consequences.
    assert pgsp['CSS']['obstructionOdd'] == 1
    assert pgsp['obstructionOdd']['CSS'] == 1
    assert pgsp['CSS']['obstructionEven'] == 0
    assert pgsp['obstructionEven']['CSS'] == 0
    assert pgsp['obstructionEven']['obstructionOdd'] == 0
    assert pgsp['obstructionOdd']['obstructionEven'] == 0

    out = {
        'schema': 'w33.20260902.pgsp-mod3-hom-spaces.v1',
        'status': 'PASS',
        'field': 'F3',
        'restrictedGroup': 'PSp4(3)',
        'extendedGroup': 'PGSp4(3)',
        'moduleDimension': 81,
        'commonCoordinateSource': 'H1(W(3,3);F3) building-cycle basis',
        'inputCertificates': {
            'scalarSchur': str(SCHUR.relative_to(ROOT)),
            'chainInjections': str(CHAIN.relative_to(ROOT)),
            'outerTransports': str(MOD.relative_to(ROOT)),
            'cssBridge': str(BRIDGE.relative_to(ROOT)),
        },
        'outerSignsRelativeToBuildingS': signs,
        'HomPSpDimensions': psp,
        'HomPGSpDimensions': pgsp,
        'HomPGSpGenerators': generators,
        'crossCarrierResults': {
            'CSS_to_obstructionOdd': {
                'dimension': 1,
                'generator': '(Phi Z) h -> Y_odd h',
                'interpretation': 'same +S PGSp extension',
            },
            'CSS_to_obstructionEven': {
                'dimension': 0,
                'PSpHomDimension': 1,
                'interpretation': 'the common-coordinate PSp isomorphism is killed by the opposite outer sign',
            },
            'obstructionEven_to_obstructionOdd': {
                'dimension': 0,
                'PSpHomDimension': 1,
                'interpretation': 'opposite PGSp extensions of the same restricted Steinberg',
            },
        },
        'signTwistStatement': (
            'Tensoring either endpoint by the nontrivial PGSp/PSp sign character flips its '
            'outer sign and restores the one-dimensional Hom exactly when the displayed '
            'untwisted Hom dimension is zero.'
        ),
        'theorem': (
            'The full defining-characteristic PGSp Hom table among CSS, the common rational-even '
            'obstruction reduction, and the rational-odd obstruction reduction is determined '
            'exactly. Every restricted PSp Hom has dimension one by the scalar Schur theorem. '
            'After adjoining the explicit outer involution, Hom has dimension one precisely '
            'between modules with the same solved outer sign and dimension zero between opposite '
            'signs. Consequently CSS is PGSp-isomorphic to the obstructionOdd reduction, not to '
            'the common obstructionEven reduction, although all three are PSp-isomorphic.'
        ),
        'boundary': (
            'This distinguishes finite PGSp extensions of one modular Steinberg module. It does '
            'not identify physical particles, chirality sectors, or continuum fields.'
        ),
    }
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(json.dumps(out, indent=2, sort_keys=True) + '\n')
    print(json.dumps({'status': 'PASS', 'signs': signs, 'HomPGSp': pgsp}, sort_keys=True))


if __name__ == '__main__':
    main()
