# Pass 1375 -- name the point stabiliser of the three 432-orbits, and settle a
# dispute about its ORDER.
#
# Pass 1126 found that W(E6)'s three orbits of size 432 on the 2240 A2 root
# triples each carry exactly one degree-81 irreducible, and every other orbit
# carries none.  It reported the point stabiliser as having order 120 and
# deliberately declined to name it.
#
# A parallel contribution (commit 2da603e52, analysis/2026-07-27_432_orbit_
# stabilizer_gap_plan.md) issued a "correction": it asserts
#
#     |Sp(4,3)| = 25920,  so  stab = 25920/432 = 60,  "not 120"
#
# and froze `stabilizer order = 60` into data/ALIAS_REGISTRY.json.  BOTH of its
# premises are wrong, and this script demonstrates it rather than asserting it:
#
#   * |Sp(4,3)| = 51840.  25920 is |PSp(4,3)| = |U4(2)|.  Sp(4,3) = 2.U4(2) is
#     the DOUBLE COVER; this is precisely the conflation Pass 1020 had to correct
#     in five separate files.
#   * The group acting on the 2240 A2 triples is neither of those: it is
#     W(E6) = U4(2):2, also of order 51840 but NOT isomorphic to Sp(4,3)
#     (Pass 1124: 25 irreducibles and two degree-81s, vs 34 and one).
#
# So 432 * 120 = 51840 is the only arithmetic available, and the "correction"
# divides by the order of a group that is not acting.
#
# It also mislocates the object.  Its GAP script searches for 432-orbits among
# the 2-element subsets of the 40 points of W(3,3).  There are C(40,2) = 780 of
# those and they split 240 + 540 under the full group, so no orbit of size 432
# exists there at all and the script prints nothing.  The 432s live on the 2240
# A2 root triples in E8, not on point pairs.  That check is run below too.
#
# What is genuinely open, and what this pass answers: WHICH group of order 120,
# and are the three stabilisers conjugate?

LogTo();
out := "C:/Repos/Theory of Everything/data/w33_pass1375_432_stabiliser.txt";
PrintTo(out, "Pass 1375: the 432-orbit stabiliser\n\n");
A := function(s) AppendTo(out, s); end;

A(Concatenation("|Sp(4,3)|   = ", String(Size(Sp(4,3))), "\n"));
A(Concatenation("|PSp(4,3)|  = ", String(Size(PSp(4,3))), "\n"));
A(Concatenation("|Sp| = 2*|PSp| ? ",
   String(Size(Sp(4,3)) = 2*Size(PSp(4,3))), "\n\n"));

# ---------------------------------------------------------------- the claim's
# own object: are there 432-orbits on 2-subsets of the 40 points?  (No.)
SP4  := Sp(4,3);
pts  := Orbit(SP4, NormedRowVector([1,0,0,0]*Z(3)^0), OnLines);
G40  := Action(SP4, pts, OnLines);
A(Concatenation("degree-40 image of Sp(4,3) has order ", String(Size(G40)),
   "  (= PSp(4,3) = 25920? ", String(Size(G40) = 25920), ")\n"));
prs := Combinations([1..40], 2);
ob  := Orbits(G40, prs, OnSets);
A(Concatenation("orbits of PSp(4,3) on the 780 point-pairs: ",
   String(List(ob, Length)), "\n"));
A(Concatenation("any orbit of size 432 there? ",
   String(ForAny(ob, o -> Length(o) = 432)), "   <- the disputed script's search\n\n"));

# ------------------------------------------------------------------ E8 roots
roots := [];
for i in [1..8] do for j in [i+1..8] do
  for si in [-2,2] do for sj in [-2,2] do
    v := ListWithIdenticalEntries(8, 0); v[i] := si; v[j] := sj; Add(roots, v);
  od; od;
od; od;
for m in [0..255] do
  v := List([0..7], k -> 1 - 2*((QuoInt(m, 2^k)) mod 2));
  if Sum(v) mod 4 = 0 then Add(roots, v); fi;
od;
A(Concatenation("E8 roots: ", String(Length(roots)),
  "   all norm 8: ", String(ForAll(roots, x -> x*x = 8)), "\n"));

rootIndex := function(x) return Position(roots, x); end;
ReflPerm := function(r)
  return PermList(List(roots, x -> rootIndex(x - ((x*r)/4)*r)));
end;
# W(E8) generated by ALL root reflections -- robust, and avoids the trap that
# an A7 chain plus a root ORTHOGONAL to it generates only S8 x C2 (order 80640).
W := Group(List(roots, ReflPerm));
A(Concatenation("|W(E8)| = ", String(Size(W)), "\n"));

# ------------------------------------------------- the 2240 A2 root triples
trip := [];
for i in [1..240] do for j in [i+1..240] do
  k := rootIndex(-(roots[i] + roots[j]));
  if k <> fail and k > j then Add(trip, [i,j,k]); fi;
od; od;
A(Concatenation("A2 triples (alpha+beta+gamma = 0): ", String(Length(trip)), "\n"));

# W(E6) = POINTWISE stabiliser of one A2 triple  (E8 contains A2 x E6)
t0 := trip[1];
K := Stabilizer(W, t0, OnTuples);
A(Concatenation("|pointwise stab of an A2 triple| = ", String(Size(K)),
   "   (= |W(E6)| = 51840? ", String(Size(K) = 51840), ")\n"));
A(Concatenation("K is U4(2):2 not Sp(4,3)?  #Irr = ", String(Length(Irr(K))),
   "  (25 = U4(2):2, 34 = Sp(4,3))\n\n"));

# ------------------------------------------------------- act on the triples
hom  := ActionHomomorphism(K, trip, OnSets);
KT   := Image(hom);
orbs := Orbits(KT, [1..Length(trip)]);
A(Concatenation("W(E6) orbits on the 2240: ", String(SortedList(List(orbs, Length))), "\n"));
A(Concatenation("sum = ", String(Sum(orbs, Length)), "\n\n"));

# ------------------------------- the three 432s: order, name, conjugacy class
A("=== the three 432-orbits ===\n");
stabs := [];
for o in orbs do
  if Length(o) = 432 then
    S := Stabilizer(KT, o[1]);
    Add(stabs, S);
    A(Concatenation("  orbit 432  |stab| = ", String(Size(S)),
      "   51840/432 = ", String(51840/432), "\n"));
    A(Concatenation("    IdGroup            = ", String(IdGroup(S)), "\n"));
    A(Concatenation("    StructureDescription= ", StructureDescription(S), "\n"));
    A(Concatenation("    element orders      = ",
        String(Collected(List(ConjugacyClasses(S), c -> Order(Representative(c))))), "\n"));
    A(Concatenation("    abelianisation      = ",
        String(AbelianInvariants(S)), "\n"));
    A(Concatenation("    isomorphic to S5?   = ",
        String(IdGroup(S) = [120,34]), "\n"));
    A(Concatenation("    isomorphic to SL(2,5)? = ",
        String(IdGroup(S) = [120,5]), "\n"));
    A(Concatenation("    isomorphic to C2xA5?   = ",
        String(IdGroup(S) = [120,35]), "\n"));
  fi;
od;
if Length(stabs) = 3 then
  A(Concatenation("\n  stab1 ~conj~ stab2 in W(E6)? ",
     String(IsConjugate(KT, stabs[1], stabs[2])), "\n"));
  A(Concatenation("  stab1 ~conj~ stab3 in W(E6)? ",
     String(IsConjugate(KT, stabs[1], stabs[3])), "\n"));
  A(Concatenation("  stab2 ~conj~ stab3 in W(E6)? ",
     String(IsConjugate(KT, stabs[2], stabs[3])), "\n"));
fi;

# ------------------------- is this S5 the SAME S5 as Pass 1125's tree generator?
# Pass 1125's S5 = SmallGroup[120,34] lives in PSp(4,3) at index 216.  The 432
# stabiliser lives in W(E6) = U4(2):2.  Abstract isomorphism would NOT make them
# the same subgroup; the honest question is whether the 432-stabiliser meets the
# derived subgroup PSp(4,3) in a tree-quotient subgroup.
A("\n=== does the 432 stabiliser lie in the derived subgroup? ===\n");
if Length(stabs) > 0 then
  D := DerivedSubgroup(KT);
  A(Concatenation("  |W(E6)'| = ", String(Size(D)), "  (25920 = PSp(4,3)? ",
     String(Size(D) = 25920), ")\n"));
  A(Concatenation("  |stab n W(E6)'| = ", String(Size(Intersection(stabs[1], D))), "\n"));
  A(Concatenation("  IdGroup of that = ",
     String(IdGroup(Intersection(stabs[1], D))), "\n"));
fi;

A("\nDONE\n");
QUIT;
