#!/usr/bin/env python3
"""Pass5336: exact local A5/V4 fiber algebra inside the q=5 K0 minimum shell.

The 15 words over one W(3,5) base point are unordered pairs of its six incident
lines. Pass5296 identifies the induced point-stabilizer image with PSL2(5)=A5.
This pass computes the 15-point orbital algebra directly. The pair stabilizer is
V4, so the fiber is A5/V4. Its orbital algebra is noncommutative of rank 6 with
complex Wedderburn C^2 + M2(C), and the permutation module decomposes

    15 = 1 + 4 + 2*5.

Thus the local augmentation fiber 14 is 4 + 5 + 5, not an undifferentiated
14-dimensional object.
"""
from __future__ import annotations
import itertools,json
from pathlib import Path
import numpy as np
from sympy import Matrix
from sympy.combinatorics import Permutation,PermutationGroup
ROOT=Path(__file__).resolve().parents[1]
OUT=ROOT/'data/PART_W33_PASS5336_Q5_LOCAL_FIBER_A5_WEDDERBURN.json'

def a5_degree6():
    # PSL2(5) on P^1(F5)={0,1,2,3,4,infinity}; generated by x->x+1 and x->-1/x.
    INF=5
    def t(x):return INF if x==INF else (x+1)%5
    def s(x):
        if x==INF:return 0
        if x==0:return INF
        return (-pow(x,-1,5))%5
    G=PermutationGroup([Permutation([t(x) for x in range(6)]),Permutation([s(x) for x in range(6)])])
    assert G.order()==60
    return G

def main():
    G=a5_degree6();pairs=list(itertools.combinations(range(6),2));pi={p:i for i,p in enumerate(pairs)}
    H=PermutationGroup([Permutation([pi[tuple(sorted((g(a),g(b))))] for a,b in pairs]) for g in G.generators])
    assert H.order()==60 and len(H.orbit(0))==15
    St=H.stabilizer(0);assert St.order()==4 and St.center().order()==4
    orbs=sorted([sorted(O) for O in St.orbits()],key=lambda O:(len(O),O[0]))
    assert list(map(len,orbs))==[1,1,1,4,4,4]
    els=list(H.generate_schreier_sims());to0=[next(g for g in els if g(x)==0) for x in range(15)]
    sub=np.empty(15,dtype=np.uint8)
    for i,O in enumerate(orbs):sub[O]=i
    R=np.empty((15,15),dtype=np.uint8)
    for x,h in enumerate(to0):
        for y in range(15):R[x,y]=sub[h(y)]
    tr=[int(R[O[0],0]) for O in orbs];assert tr==[0,2,1,3,4,5]
    r=6;P=np.zeros((r,r,r),dtype=int)
    for k,O in enumerate(orbs):
        y=O[0]
        for z in range(15):P[k,R[0,z],R[z,y]]+=1
    L=[]
    for i in range(r):
        M=np.zeros((r,r),dtype=int)
        for j in range(r):M[:,j]=P[:,i,j]
        L.append(M)
    rows=[]
    for j in range(r):
        C=[L[i]@L[j]-L[j]@L[i] for i in range(r)]
        for a in range(r):
            for b in range(r):
                v=[int(C[i][a,b]) for i in range(r)]
                if any(v):rows.append(v)
    Z=Matrix(rows);assert r-Z.rank()==3
    comm=[]
    for i in range(r):
        for j in range(r):comm.append(list(map(int,P[:,i,j]-P[:,j,i])))
    assert Matrix(comm).rank()==3
    # Character check: fixed pair counts on A5 classes are 15,3,0,0,0.
    class_profile=[]
    for C in G.conjugacy_classes():
        g=next(iter(C));fixed=sum(tuple(sorted((g(a),g(b))))==(a,b) for a,b in pairs)
        class_profile.append((len(C),int(g.order()),fixed))
    assert sorted(class_profile)==sorted([(1,1,15),(15,2,3),(20,3,0),(12,5,0),(12,5,0)])
    out={'pass':5336,'status':'THEOREM_Q5_LOCAL_K0_FIBER_IS_A5_OVER_V4_WITH_NONCOMMUTATIVE_RANK6_ALGEBRA',
      'local_fiber_size':15,'group':'PSL2(5) ~= A5','group_order':60,'pair_stabilizer':'V4','pair_stabilizer_order':4,
      'subdegrees':[1,1,1,4,4,4],'orbital_rank':6,'symmetric_orbitals':4,'directed_orbitals':2,
      'center_dimension':3,'commutator_dimension':3,'complex_wedderburn':'C^2 + M2(C)',
      'permutation_module':'15 = 1 + 4 + 2*5','augmentation_module':'14 = 4 + 5 + 5',
      'class_fixed_pair_profile':[{'class_size':a,'element_order':b,'fixed_pairs':c} for a,b,c in sorted(class_profile)],
      'conclusion':'The 15-word PG(3,2) fiber already carries a local noncommutative multiplicity-two 5-dimensional sector. The global rank21 noncommutativity of Pass5332 therefore has a concrete local A5/V4 source.',
      'boundary':'Finite representation theorem for the q5 code fiber only; the number14 is not identified with a G2 adjoint module.'}
    OUT.write_text(json.dumps(out,indent=2)+'\n');print(json.dumps(out,indent=2))
if __name__=='__main__':main()
