"""Pass 11642: label-blind time -- which Clifford invariants of a qutrit state see only the four MUB outcome SPECTRA.

Measure a qutrit state in each of its four mutually unbiased bases and forget which outcome is which inside each basis:
what remains is, for every MUB b, the multiset of its three probabilities, i.e. (with N = |psi|^2)
    e2_b = sum_{s<s' in b} p_s p_s' ,     Pi_b = prod_{s in b} p_s .
A Clifford unitary permutes the four MUBs by an element of A4; complex conjugation (time reversal) swaps two of them.
So the LABEL-BLIND invariants are the S4-symmetric (time-even) and S4-alternating (time-odd) polynomials in N, e2_b, Pi_b.

Questions answered here, exactly (evaluations at Z[omega] points, where q_s = 3 p_s is an integer, modulo P = 2^31 - 19;
rank mod P <= rank over Q, and equality with the Molien dimension of Pass 11491 is a proof of spanning):
  1. even: is every time-even invariant label-blind?  (Pass 11534 says the even ring is generated by the stabiliser moments
     M_k = sum_b sum_{s in b} p_s^k through degree 20, which are label-blind; checked independently here.)
  2. odd: in which degrees do label-blind time arrows exist, and what fraction of the time-odd module do they span?
     A degree argument gives >= 9 (an alternant needs four distinct monomials in (e2, Pi), of degrees >= 0+2+3+4);
     the true arrow starts at degree 6 (Pass 11491).
  3. relations: the complete list of minimal polynomial relations among N, e2_b, Pi_b through a degree bound.
"""

from __future__ import annotations

import itertools
import json
import sys
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "analysis"))
import w33_pass11534_time_arrow_module_exact as E  # noqa: E402

OUT = ROOT / "data" / "w33_pass11642_label_blind_time.json"
PR = E.PR
_M = json.load(open(ROOT / "data" / "w33_pass11491_time_odd_molien.json"))["sequences"]
EK, OK = _M["even"], _M["odd"]
PERMS = list(itertools.permutations(range(4)))


def perm_sign(p):
    s = 1
    for i, j in itertools.combinations(range(4), 2):
        if p[i] > p[j]:
            s = -s
    return s


SIGNS = np.array([perm_sign(p) for p in PERMS], np.int64)


def mub_data(n_points=420, seed=11642):
    w = np.exp(2j * np.pi / 3)
    F = np.array([[w ** (j * k) for k in range(3)] for j in range(3)]) / np.sqrt(3)
    Xm = np.roll(np.eye(3), 1, axis=0)
    Zm = np.diag([1, w, w * w])
    bases = [np.eye(3)]
    for a in range(3):
        _, V = np.linalg.eig(Xm @ np.linalg.matrix_power(Zm, a))
        bases.append(V)
    # labels Z, X, XZ, XZ2; complex conjugation swaps the last two (Pass 11641)
    rng = np.random.default_rng(seed)
    a, b = rng.integers(-3, 4, size=(2, n_points, 3))
    psi = a + b * w
    q = np.stack([3 * np.abs(psi @ B.conj()) ** 2 for B in bases], 1)      # (pts, 4, 3)
    qi = np.rint(q).astype(np.int64)
    assert np.abs(q - qi).max() < 1e-7
    n3 = qi[:, 0].sum(1)
    assert all((qi[:, b].sum(1) == n3).all() for b in range(4))
    e2 = qi[:, :, 0] * qi[:, :, 1] + qi[:, :, 0] * qi[:, :, 2] + qi[:, :, 1] * qi[:, :, 2]
    P3 = qi[:, :, 0] * qi[:, :, 1] * qi[:, :, 2]
    # time reversal check: conj(psi) swaps MUB spectra 2 <-> 3
    qc = np.stack([3 * np.abs(np.conj(psi) @ B.conj()) ** 2 for B in bases], 1)
    assert np.allclose(np.sort(qc[:, 2], 1), np.sort(q[:, 3], 1)) and np.allclose(np.sort(qc[:, 0], 1), np.sort(q[:, 0], 1))
    return n3 % PR, e2 % PR, P3 % PR, F


def lb_monomials(k):
    """(a, i[4], j[4]) with a + 2 sum i + 3 sum j = k"""
    out = []
    for J in range(k // 3 + 1):
        for I in range((k - 3 * J) // 2 + 1):
            a = k - 3 * J - 2 * I
            for js in itertools.product(range(J + 1), repeat=4):
                if sum(js) != J:
                    continue
                for is_ in itertools.product(range(I + 1), repeat=4):
                    if sum(is_) == I:
                        out.append((a, is_, js))
    return out


def powmod(x, e):
    r = np.ones_like(x)
    for _ in range(e):
        r = r * x % PR
    return r


_POW = {}


class LB:
    def __init__(self, n_points=420, seed=11642):
        self.n3, self.e2, self.P3, _ = mub_data(n_points, seed)
        self.npts = len(self.n3)
        self.cache = {}

    def mono(self, a, is_, js, perm):
        v = powmod(self.n3, a)
        for slot in range(4):
            b = perm[slot]
            v = v * powmod(self.e2[:, b], is_[slot]) % PR * powmod(self.P3[:, b], js[slot]) % PR
        return v

    def sym(self, m, odd):
        a, is_, js = m
        tot = np.zeros(self.npts, np.int64)
        for p, s in zip(PERMS, SIGNS):
            v = self.mono(a, is_, js, p)
            tot = (tot + (v if (s > 0 or not odd) else PR - v)) % PR
        return tot

    def space(self, k, odd):
        seen = set()
        cols = []
        for a, is_, js in lb_monomials(k):
            key = tuple(sorted(zip(is_, js)))                 # S4 orbit of the slot data
            if (a, key) in seen:
                continue
            seen.add((a, key))
            v = self.sym((a, is_, js), odd)
            if v.any():
                cols.append(v)
        return cols


def nullspace_mod(A):
    """basis of {x : A x = 0} over GF(PR); A rows = points, cols = monomials"""
    A = np.array(A, np.int64) % PR
    rows, cols = A.shape
    piv_cols = []
    r = 0
    A = A.copy()
    for c in range(cols):
        piv = next((i for i in range(r, rows) if A[i, c]), None)
        if piv is None:
            continue
        A[[r, piv]] = A[[piv, r]]
        A[r] = A[r] * pow(int(A[r, c]), PR - 2, PR) % PR
        nz = np.flatnonzero(A[:, c])
        nz = nz[nz != r]
        if len(nz):
            A[nz] = (A[nz] - A[nz, c][:, None] * A[r][None, :] % PR) % PR
        piv_cols.append(c)
        r += 1
        if r == rows:
            break
    free = [c for c in range(cols) if c not in piv_cols]
    basis = []
    for f in free:
        x = np.zeros(cols, np.int64)
        x[f] = 1
        for i, c in enumerate(piv_cols):
            x[c] = (-A[i, f]) % PR
        basis.append(x)
    return basis


def relations(lb, D=12):
    """minimal relations among n3, e2_b, P3_b (plain polynomial ring, no symmetry) through weighted degree D"""
    out = {}
    gens = {}                                                  # degree -> list of relation vectors (as dict monomial->coef)
    for k in range(1, D + 1):
        mons = lb_monomials(k)
        vals = np.stack([lb.mono(a, i, j, (0, 1, 2, 3)) for a, i, j in mons], 1)
        ker = nullspace_mod(vals)
        dimR = len(ker)
        # ideal generated by lower minimal relations in degree k
        idx = {m: c for c, m in enumerate(mons)}
        gen_cols = []
        for d0, rels in gens.items():
            for rel in rels:
                for a, i, j in lb_monomials(k - d0):
                    vec = np.zeros(len(mons), np.int64)
                    for (a2, i2, j2), coef in rel.items():
                        key = (a + a2, tuple(x + y for x, y in zip(i, i2)), tuple(x + y for x, y in zip(j, j2)))
                        vec[idx[key]] = (vec[idx[key]] + coef) % PR
                    gen_cols.append(vec)
        r_ideal = E.rank_mod(np.stack(gen_cols, 0)) if gen_cols else 0
        new = dimR - r_ideal
        if new:
            # pick kernel vectors not in the ideal span
            chosen = []
            base = list(gen_cols)
            r0 = r_ideal
            for v in ker:
                if E.rank_mod(np.stack(base + [v], 0)) > r0:
                    base.append(v)
                    r0 += 1
                    chosen.append({mons[c]: int(v[c]) for c in np.flatnonzero(v)})
                    if len(chosen) == new:
                        break
            gens[k] = chosen
        out[str(k)] = dict(monomials=len(mons), relations=dimR, from_lower=r_ideal, new_minimal=new)
        print("rel", k, out[str(k)], flush=True)
    return out, gens


def ratrec(a):
    """rational reconstruction of a mod PR with |num|, den <= sqrt(PR/2)"""
    from math import isqrt
    B = isqrt(PR // 2)
    r0, r1, s0, s1 = PR, int(a) % PR, 0, 1
    while r1 > B:
        q = r0 // r1
        r0, r1, s0, s1 = r1, r0 - q * r1, s1, s0 - q * s1
    if s1 == 0 or abs(s1) > B:
        return None
    from fractions import Fraction
    return Fraction(r1, s1)


def lift_and_verify(rel, n_check=300, seed=99):
    """lift a mod-PR relation to Q (normalised by its first coefficient) and verify it EXACTLY in integers at fresh
    Z[omega] points (where N, e_b, P_b are integers)"""
    from fractions import Fraction
    from math import lcm
    items = list(rel.items())
    c0 = pow(int(items[0][1]), PR - 2, PR)
    lifted = {}
    for m, c in items:
        fr = ratrec(int(c) * c0 % PR)
        if fr is None:
            return None
        lifted[m] = fr
    L = lcm(*[f.denominator for f in lifted.values()])
    coef = {m: int(f * L) for m, f in lifted.items()}
    w = np.exp(2j * np.pi / 3)
    rng = np.random.default_rng(seed)
    Xm = np.roll(np.eye(3), 1, axis=0)
    Zm = np.diag([1, w, w * w])
    bases = [np.eye(3)] + [np.linalg.eig(Xm @ np.linalg.matrix_power(Zm, a))[1] for a in range(3)]
    for _ in range(n_check):
        a, b = rng.integers(-5, 6, size=(2, 3))
        psi = a + b * w
        q = [np.rint(3 * np.abs(psi @ B.conj()) ** 2).astype(np.int64).tolist() for B in bases]
        n3 = sum(q[0])
        e2 = [x[0] * x[1] + x[0] * x[2] + x[1] * x[2] for x in q]
        P3 = [x[0] * x[1] * x[2] for x in q]
        tot = 0
        for (aa, ii, jj), c in coef.items():
            v = c * n3 ** aa
            for s in range(4):
                v *= e2[s] ** ii[s] * P3[s] ** jj[s]
            tot += v
        if tot != 0:
            return False
    return coef


def readable(rel):
    def sym(c):
        c = int(c)
        return c if c <= PR // 2 else c - PR
    terms = []
    for (a, i, j), c in rel.items():
        f = [f"N^{a}" if a else ""] + [f"e{b}^{x}" if x else "" for b, x in enumerate(i)] + \
            [f"P{b}^{x}" if x else "" for b, x in enumerate(j)]
        terms.append(f"{sym(c)}*" + "*".join(t for t in f if t))
    return " + ".join(terms)


def main():
    D = int(sys.argv[1]) if len(sys.argv) > 1 else 20
    lb = LB()
    res = dict(pass_id=11642, prime=PR, points=lb.npts, conventions="q_s = 3 p_s; N = sum_{s in b} q_s = 3|psi|^2; "
               "e_b = e2 of the three q_s of MUB b; P_b = their product = 27 Pi_b; MUB order Z, X, XZ, XZ2")
    rel, gens = relations(LB(2400, 116420), 12)       # more points than the 975 degree-12 monomials
    res["relations"] = rel
    res["minimal_relations_mod_P"] = {k: [readable(r) for r in v] for k, v in gens.items()}
    exact = {}
    for k, v in gens.items():
        exact[k] = []
        for r in v:
            c = lift_and_verify(r)
            exact[k].append(None if not c else " + ".join(f"{cc}*N^{a}*e^{list(i)}*P^{list(j)}" for (a, i, j), cc in c.items()))
    res["minimal_relations_exact_integer_verified_300_points"] = exact
    res["all_minimal_relations_lift_to_Z"] = all(x is not None for v in exact.values() for x in v)
    print("lifted", res["all_minimal_relations_lift_to_Z"], flush=True)
    rows = {}
    for k in range(1, D + 1):
        ev = lb.space(k, False)
        od = lb.space(k, True)
        re_ = E.rank_mod(np.stack(ev, 1)) if ev else 0
        ro = E.rank_mod(np.stack(od, 1)) if od else 0
        rows[str(k)] = dict(E_k=EK[k], label_blind_even=re_, O_k=OK[k], label_blind_odd=ro)
        print(k, rows[str(k)], flush=True)
    res["by_degree"] = rows
    res["first_label_blind_odd_degree"] = next((int(k) for k, v in rows.items() if v["label_blind_odd"]), None)
    lb2 = LB()
    a9 = lb2.sym((0, (0, 1, 0, 2), (0, 0, 1, 0)), True)            # slots 1, e, P, e^2: the alternant det[1, e_b, P_b, e_b^2]
    res["degree9_alternant_det(1,e,P,e^2)_nonzero"] = bool(a9.any())
    res["even_all_label_blind_through_D"] = all(v["label_blind_even"] == v["E_k"] for v in rows.values())
    json.dump(res, open(OUT, "w"), indent=1, default=str)


if __name__ == "__main__":
    main()
