"""General symplectic GQ W(3,q), prime q in 2,3,5:
q^4 top Levi homology; integral clique-to-Levi map; exact Hodge
normalization sqrt(q+1) and characteristic-p perfect cycle pairing.
A family theorem, NOT proof of four-dimensional spacetime.
"""
from pathlib import Path
from itertools import product,combinations
from collections import Counter
import sys,json,math
import numpy as np
ROOT=Path(__file__).resolve().parents[1]
sys.path.insert(0,str(ROOT/'analysis'))
from w33_20261009_toe_integral_clique_levi_bridge import integer_cycle_basis as _q3_cycle_basis

def canonical(v,q):
 a=next(x for x in v if x%q)
 inv=pow(a,-1,q)
 return tuple((int(x)*inv)%q for x in v)
def form(x,y,q):
 return (x[0]*y[1]-x[1]*y[0]+x[2]*y[3]-x[3]*y[2])%q
def geometry(q):
 vectors=sorted(set(canonical(v,q) for v in product(range(q),repeat=4) if any(v)))
 idx={p:i for i,p in enumerate(vectors)}
 lines=set()
 for i,j in combinations(range(len(vectors)),2):
  x,y=vectors[i],vectors[j]
  if form(x,y,q):continue
  line=tuple(sorted({idx[canonical(tuple(a*x[k]+b*y[k] for k in range(4)),q)]
    for a,b in product(range(q),repeat=2) if a or b}))
  assert len(line)==q+1
  lines.add(line)
 return vectors,sorted(lines)

def check_small(q,lines,n):
 from itertools import combinations
 edges=sorted({e for L in lines for e in combinations(L,2)})
 flags=sorted((p,l) for l,L in enumerate(lines) for p in L)
 eidx={e:i for i,e in enumerate(edges)};fidx={f:i for i,f in enumerate(flags)}
 C=np.zeros((len(flags),len(edges)),dtype=np.int64)
 B=np.zeros((n+len(lines),len(flags)),dtype=np.int64)
 d1=np.zeros((n,len(edges)),dtype=np.int64)
 for j,(a,b) in enumerate(edges):
  d1[a,j]=-1;d1[b,j]=1
  l=next(k for k,L in enumerate(lines) if a in L and b in L)
  C[fidx[(a,l)],j]=1;C[fidx[(b,l)],j]=-1
 for j,(p,l) in enumerate(flags):
  B[p,j]=-1;B[n+l,j]=1
 J=np.zeros((n+len(lines),n),dtype=np.int64)
 J[:n,:]=np.eye(n,dtype=np.int64)
 assert np.array_equal(B@C,J@d1)
 # Fundamental Levi cycle basis:
 adj=[[] for _ in range(n+len(lines))]
 for e,(p,l) in enumerate(flags):
  adj[p].append((n+l,e));adj[n+l].append((p,e))
 seen={0};queue=[0];parent=[-1]*(n+len(lines));pe=[-1]*(n+len(lines));depth=[0]*(n+len(lines))
 for v in queue:
  for w,k in adj[v]:
   if w not in seen:
    seen.add(w);parent[w]=v;pe[w]=k;depth[w]=depth[v]+1;queue.append(w)
 tree={e for e in pe if e>=0};chords=[e for e in range(len(flags)) if e not in tree]
 Z=np.zeros((len(flags),len(chords)),dtype=np.int64)
 for j,c in enumerate(chords):
  z=np.zeros(len(flags),dtype=np.int64);z[c]=1
  bal=B[:,c].copy()
  for v in sorted(range(1,len(parent)),key=lambda i:depth[i],reverse=True):
   e=pe[v];sign=int(B[v,e]);k=-int(bal[v])*sign
   z[e]=k;bal[v]=0;bal[parent[v]]-=sign*k
  assert not np.any(bal);Z[:,j]=z
 assert Z.shape[1]==q**4
 L=C.T@Z
 assert np.array_equal(d1@L,np.zeros((n,q**4),dtype=np.int64))
 assert np.array_equal(C@L,(q+1)*Z)
 assert np.array_equal(L.T@L,(q+1)*(Z.T@Z))
 return dict(clique_edges=len(edges),flags=len(flags),cycle_dimension=q**4,
     transpose_image_euclidean_scale_squared=q+1,exact_chain_identity=True)

def main():
 records={}
 for q in (2,3,5):
  pts,lines=geometry(q)
  n=(q+1)*(q*q+1)
  assert len(pts)==len(lines)==n
  assert all(len(L)==q+1 for L in lines)
  edges=sum(len(L) for L in lines)
  assert edges==(q+1)*n
  cycle=edges-2*n+1
  assert cycle==q**4
  f=q*(q+1)**2//2
  g=q*(q*q+1)//2
  assert f+g+1==n
  factor={str(q*q+1):f-1,str(q+1):2*g}
  tau=(q*q+1)**(f-1)*(q+1)**(2*g)
  assert tau%q!=0
  rec=dict(q=q,points=n,lines=n,flags=edges,clique_edges=n*math.comb(q+1,2),
   Levi_first_homology_rank=cycle,
   graph_eigen_mult=(dict(NNt_largest=(q+1)**2,multiplicity=1),
                    dict(NNt_middle=2*q,multiplicity=f),
                    dict(NNt_zero=0,multiplicity=g)),
   critical_group_order=str(tau),critical_group_order_prime_p_not_divisible=True,
   critical_group_factor_expression=f'({q*q+1})^{f-1} * ({q+1})^{2*g}',
   canonical_real_Hodge_isometry_scale=f'1/sqrt({q+1})')
  if q==2:rec['explicit_q2_identity']=check_small(q,lines,n)
  records[str(q)]=rec
  print('GQ',q,'points',n,'flags',edges,'cycles',cycle,'tau modq',tau%q,flush=True)
 result=dict(status='PASS',prime_field_cases=records,
  algebraic_family_theorem='For any classical symplectic GQ W(3,q) with q a prime power, 40= (q+1)(q²+1) at q=3 generalizes to P=L=(q+1)(q²+1), flags=(q+1)P, incidence cycle rank q^4. The clique edge-to-Levi two-step path map induces an INTEGRAL homology isomorphism and its transpose restricts to the harmonic H1 with norm squared multiplied by q+1. The number of spanning trees is (q²+1)^[q(q+1)²/2 -1] * (q+1)^[q(q²+1)], coprime to characteristic p|q. Hence the native edge dot-product on the cycle lattice is perfect mod p.',
  proof='Every pair of collinear points belongs to exactly one line and all maximal cliques are line simplices. On each line K_(q+1), the edge incidence map to its q+1 flags has image the saturated sum-zero lattice and kernel generated by its triangles. The Levi cycle condition at line vertices is precisely the sum-zero lattice condition. The graph cycle rank follows E-V+1=q^4. On a q+1 flag block, M M^T=(q+1)I-J; J vanishes on Levi cycles. The GQ point graph adjacency eigenvalues are q(q+1), q-1, -(q+1), with multiplicities 1, q(q+1)^2/2, q(q²+1)/2, yielding the matrix-tree formula.',
  physical_nogo='The exponent four in q^4 is the graph cycle-rank growth of this finite incidence family, NOT an inference of 4D spacetime. The q=3 loop space is 81-dimensional; finite graph topology fixes neither time, mass scale, Lorentz dynamics nor gravity coupling.')
 (ROOT/'data/w33_20261009_toe_q4_family_theorem.json').write_text(json.dumps(result,indent=2)+'\n')
if __name__=='__main__':main()
