#!/usr/bin/env python3
"""Test whether the rank-threshold S4 is conjugate to a six-circuit S4 complement.

This is an explicit subgroup comparison inside the same paired PSp(4,3)
action on the 40 W33 points and 45 minimum sentinel words.  It deliberately
does not infer a bridge from the common order 24.

S4_rank is the point stabilizer inside the S5 stabilizer of one 5-circuit used
by the subgroup zero-mode audit.  S4_six is a complement to the central C2 in
the order-48 stabilizer of one of the 540 six-circuits.  We enumerate all
complements generated by an order-4 and an order-3 element, then test exact
PSp conjugacy.
"""
from __future__ import annotations
import itertools,json
from collections import Counter,deque
from pathlib import Path

from w33_20260829_216_clifford_torsor_nogo import (
    geometry,supports_from_N,closure_paired,norm,form,compose,porder
)
from w33_20260830_sentinel_six_circuit_orbit import six_circuits

ROOT=Path(__file__).resolve().parents[1]
OUT=ROOT/'data/PART_W33_20260830_S4_SIX_CIRCUIT_CONJUGACY.json'

def inv(p):
    q=[0]*len(p)
    for i,j in enumerate(p):q[j]=i
    return tuple(q)

def pair_comp(a,b):
    return (compose(a[0],b[0]),compose(a[1],b[1]))

def pair_inv(a):return (inv(a[0]),inv(a[1]))

def pair_order(a):return porder(a[1])

def pair_closure(gens,limit=1000):
    e=(tuple(range(40)),tuple(range(45)))
    H={e};Q=deque([e])
    while Q:
        a=Q.popleft()
        for g in gens:
            h=pair_comp(g,a)
            if h not in H:
                H.add(h);Q.append(h)
                if len(H)>limit:raise AssertionError('closure exceeded limit')
    return frozenset(H)

def conj_subgroup(H,g):
    gi=pair_inv(g)
    return frozenset(pair_comp(pair_comp(g,h),gi) for h in H)

def orbit_sizes(H,component,n):
    unseen=set(range(n));out=[]
    while unseen:
        x=min(unseen);O={h[component][x] for h in H};out.append(len(O));unseen-=O
    return sorted(out)

def main():
    pts,idxp,lines,N=geometry();supports,masks=supports_from_N(N)
    gens40=[]
    for v in pts:
        for alpha in (1,2):
            p=[]
            for x in pts:
                z=alpha*form(x,v)%3;y=norm(tuple((x[k]+z*v[k])%3 for k in range(4)));p.append(idxp[y])
            gens40.append(tuple(p))
    si={S:i for i,S in enumerate(supports)}
    gens45=[tuple(si[frozenset(p[x] for x in S)] for S in supports) for p in gens40]
    chosen=(18,62,77,10)
    G=frozenset(closure_paired([gens40[i] for i in chosen],[gens45[i] for i in chosen]));assert len(G)==25920

    # Rank-threshold S4: point stabilizer in the first five-circuit stabilizer S5.
    c5=[]
    for cc in itertools.combinations(range(45),5):
        w=0
        for i in cc:w^=masks[i]
        if w==0:c5.append(cc)
    assert len(c5)==216
    C5=tuple(c5[0]);C5set=set(C5)
    S5=frozenset(h for h in G if {h[1][x] for x in C5set}==C5set);assert len(S5)==120
    S4rank=frozenset(h for h in S5 if h[1][C5[0]]==C5[0]);assert len(S4rank)==24

    # Six-circuit stabilizer and its central kernel on the six labels.
    C6=tuple(six_circuits(masks)[0]);C6set=set(C6)
    Stab6=frozenset(h for h in G if {h[1][x] for x in C6set}==C6set);assert len(Stab6)==48
    kernel=frozenset(h for h in Stab6 if all(h[1][x]==x for x in C6));assert len(kernel)==2
    e=next(h for h in kernel if pair_order(h)==1);z=next(h for h in kernel if h!=e);assert pair_order(z)==2
    assert all(pair_comp(z,h)==pair_comp(h,z) for h in Stab6)

    # Enumerate distinct order-24 complements found from order-4/order-3 pairs.
    by={o:[h for h in Stab6 if pair_order(h)==o] for o in (3,4)}
    comps=set()
    for a in by[4]:
        for b in by[3]:
            H=pair_closure([a,b],49)
            if len(H)==24 and z not in H:
                comps.add(H)
    assert comps

    rank_conjugates={conj_subgroup(S4rank,g) for g in G}
    matches=[H for H in comps if H in rank_conjugates]
    isconj=bool(matches)

    # Count distinct ambient conjugates and conjugators to one matching complement.
    conjugator_count=0;target=None
    if isconj:
        target=matches[0]
        conjugator_count=sum(conj_subgroup(S4rank,g)==target for g in G)
        assert conjugator_count>0

    comp_rows=[]
    for i,H in enumerate(sorted(comps,key=lambda K: sorted(tuple(x[1]) for x in K))):
        comp_rows.append({
          'index':i,
          'conjugateToRankS4':H in rank_conjugates,
          'orbitSizes40':orbit_sizes(H,0,40),
          'orbitSizes45':orbit_sizes(H,1,45),
          'elementOrders':{str(k):v for k,v in sorted(Counter(pair_order(h) for h in H).items())}
        })

    out={
      'schema':'w33.20260830.s4-six-circuit-conjugacy.v1','status':'PASS',
      'ambientGroup':{'name':'PSp(4,3)','order':len(G)},
      'rankThresholdS4':{
        'order':len(S4rank),'construction':'point stabilizer in sentinel five-circuit S5',
        'orbitSizes40':orbit_sizes(S4rank,0,40),'orbitSizes45':orbit_sizes(S4rank,1,45),
        'ambientConjugateCount':len(rank_conjugates)
      },
      'sixCircuitStabilizer':{'order':len(Stab6),'centralKernelOrder':len(kernel),'numberOfEnumeratedS4Complements':len(comps)},
      'complements':comp_rows,
      'conjugateBridgeExists':isconj,
      'conjugatorsToFirstMatchingComplement':conjugator_count,
      'theorem':('The rank-threshold S4 is PSp-conjugate to an S4 complement in the six-circuit stabilizer.' if isconj else
                 'No enumerated S4 complement of the chosen six-circuit stabilizer is PSp-conjugate to the rank-threshold S4.'),
      'boundary':'Exact subgroup conjugacy in the native paired permutation action. If conjugate, this is an explicit group-action bridge; it does not by itself identify individual coupling coefficients with circuit observables.'
    }
    OUT.parent.mkdir(parents=True,exist_ok=True);OUT.write_text(json.dumps(out,indent=2,sort_keys=True)+'\n')
    print(json.dumps({'status':'PASS','conjugateBridgeExists':isconj,'complements':len(comps),'ambientConjugates':len(rank_conjugates),'conjugators':conjugator_count},sort_keys=True))

if __name__=='__main__':main()
