#!/usr/bin/env python3
"""Passes 7297--7304: ternary shadow and Smith form of the 36 doily slices.

The same 45x36 doily-slice matrix N that generates the binary E8 spread code has a
surprisingly different characteristic-3 life.  Because every column has weight 15 and
pairwise intersections are 6 or 3, N^T N vanishes modulo 3.  The integer Smith form
then reveals a seven-dimensional 3-primary rank defect.

This pass computes the complete ternary code generated by the 36 slice columns.
"""
from __future__ import annotations

import json
from collections import Counter
from pathlib import Path

import numpy as np
import sympy as sp
from sympy.matrices.normalforms import smith_normal_form

from w33_pass4992_4999_common import build_base

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "data" / "PART_W33_PASS7297_7304_TERNARY_DOILY_SHADOW.json"


def modp_column_basis(A, p):
    M = np.asarray(A, dtype=np.int64) % p
    R = M.copy()
    m, n = R.shape
    row = 0
    pivcols = []
    for col in range(n):
        piv = next((r for r in range(row, m) if R[r, col] % p), None)
        if piv is None:
            continue
        R[[row, piv]] = R[[piv, row]]
        inv = pow(int(R[row, col]), -1, p)
        R[row] = (R[row] * inv) % p
        for r in range(m):
            if r != row and R[r, col]:
                R[r] = (R[r] - R[r, col] * R[row]) % p
        pivcols.append(col)
        row += 1
        if row == m:
            break
    return M[:, pivcols]


def main() -> int:
    base = build_base()
    N = 1 - np.asarray(base["M"], dtype=np.int64)
    assert N.shape == (45, 36)
    assert set(map(int, N.sum(axis=0))) == {15}
    assert np.all((N.T @ N) % 3 == 0)

    # Integral Smith form: 14 unit factors, seven 3-factors, fifteen zero factors.
    D = smith_normal_form(sp.Matrix(N), domain=sp.ZZ)
    diag = [abs(int(D[i, i])) for i in range(min(D.shape)) if D[i, i] != 0]
    assert Counter(diag) == Counter({1: 14, 3: 7})
    assert len(diag) == 21

    Bcols = modp_column_basis(N, 3)
    assert Bcols.shape == (45, 14)
    G = Bcols.T.astype(np.int16)  # 14 x 45 generator matrix
    assert np.all((G @ G.T) % 3 == 0)

    # Exhaust the full 3^14 code in deterministic chunks.
    total = 3 ** 14
    chunk = 100000
    enumerator = Counter()
    minw = 46
    minwords = set()
    for start in range(0, total, chunk):
        nums = np.arange(start, min(start + chunk, total), dtype=np.int64)
        coeff = np.empty((len(nums), 14), dtype=np.int8)
        tmp = nums.copy()
        for j in range(14):
            coeff[:, j] = (tmp % 3).astype(np.int8)
            tmp //= 3
        words = (coeff.astype(np.int16) @ G) % 3
        wt = np.count_nonzero(words, axis=1)
        vals, cnts = np.unique(wt, return_counts=True)
        for v, c in zip(vals, cnts):
            enumerator[int(v)] += int(c)
        nz = wt[wt > 0]
        if len(nz):
            local = int(nz.min())
            if local < minw:
                minw = local
                minwords.clear()
            if local == minw:
                for idx in np.flatnonzero(wt == minw):
                    minwords.add(tuple(map(int, words[idx])))

    expected = {
        0: 1,
        15: 72,
        18: 6420,
        21: 19440,
        24: 336060,
        27: 1109420,
        30: 1781136,
        33: 1215720,
        36: 295170,
        39: 18360,
        42: 1080,
        45: 90,
    }
    assert dict(sorted(enumerator.items())) == expected
    assert minw == 15 and len(minwords) == 72

    # The 72 minimum words are exactly +/- the 36 doily-slice columns.
    expected_min = set()
    for j in range(36):
        v = tuple(map(int, N[:, j] % 3))
        expected_min.add(v)
        expected_min.add(tuple((2 * x) % 3 for x in v))
    assert minwords == expected_min

    out = {
        "schema": "w33.pass7297_7304.ternary_doily_shadow.v1",
        "status": "PASS",
        "passes": "7297-7304",
        "smith_normal_form_nonzero": {"1": 14, "3": 7},
        "integer_rank": 21,
        "rank_mod_3": 14,
        "new_mod3_rank_defect": 7,
        "ternary_code": {
            "parameters": [45, 14, 15],
            "self_orthogonal": True,
            "reason": "N^T N = 0 over F3 because 15,6,3 are all divisible by 3",
            "size": total,
            "weight_enumerator": {str(k): v for k, v in expected.items()},
            "minimum_words": 72,
            "minimum_words_equal_plus_minus_36_doily_slices": True,
        },
        "cokernel_3_primary": "(Z/3Z)^7 in the torsion part of coker(N: Z^36 -> Z^45)",
        "boundary": "Exact integral/ternary coding theorem. The seven 3-primary factors are not assigned a physical meaning here.",
    }
    OUT.write_text(json.dumps(out, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    print(json.dumps({"status": "PASS", "code": "[45,14,15]_3", "minwords": 72, "snf3": 7}))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
