#!/usr/bin/env python3
"""
The whole tower on one axis: substrate vs world, with the dated kill-shots. This witness emits
the cover figure for the standalone manuscript -- a single picture with two panels. Panel A is a
forest plot of every MEASURED observable's fractional agreement |pred-obs|/obs on a log axis
(0.005% to 10%): the mass/coupling postdictions (m_p/m_e, 1/alpha, sin^2 th_W, M_Z, the CC,
m_Higgs) cluster at 0.01-0.3% (integer / leading-order level), and the inflation/neutrino
observables (A_s, n_s, alpha_s, Dm^2_31/Dm^2_21, sin^2 th_23, Omega_DM/Omega_b) sit at 1-5%,
each within its measurement error. Panel B is the falsification timeline 2025-2040 with the dated
tests that can KILL the theory: LZ (~2028, m_DM = 22.8 GeV), Simons Observatory (~2027, first r
hint), JUNO (~2030, Dm^2_31/Dm^2_21 = 33), DESI/CMB-S4 (~2030, Sum m_nu = 58 meV), LiteBIRD
(~2035, r = 1/300), nEXO/LEGEND (~2030s, m_betabeta ~ 1.4 meV). One figure shows both the
over-determination (many numbers, one alphabet, all consistent) and the dated kill-shots.

This is the referee's one-look figure and the cover image for w33_everything.tex: the substrate's
~20 predictions against the world on a single axis, with the future arrows.

PANEL A (agreement). Each measured observable plotted at its fractional deviation |pred-obs|/obs
in percent (log axis). The tight cluster (masses, couplings) at 0.01-0.3% is the integer /
leading-order postdiction; the looser inflation/neutrino points at 1-5% are each within their
(larger) measurement errors. Zero observables are off the chart.

PANEL B (the dated kill-shots). The future tests on a 2025-2040 timeline, each a single
measurement that can falsify: r = 1/300 (LiteBIRD ~2035, the headline), Sum m_nu = 58 meV
(DESI/CMB-S4), m_DM = 22.8 GeV (LZ ~2028), Dm^2_31/Dm^2_21 = 33 (JUNO), m_betabeta ~ 1.4 meV
(nEXO/LEGEND). By the mid-2030s several independent numbers are decided.

Honest scope: Panel A mixes integer/leading-order postdictions (the masses/couplings, where the
residual is higher-order running) with theory-sigma-limited measurements (inflation/neutrinos),
so the common axis is fractional deviation, not sigma -- the caption says so. The figure is a
presentation of the scorecard, not a new result; its value is showing the over-determination and
the dated falsifiability in one view. The kill-shot dates are the experiments' published
schedules (may slip).

Emits analysis/w33_tower_falsification_fig.tex (the two-panel figure) and records the plotted
rows and dated tests.
"""
from __future__ import annotations

import json
import math


def main():
    out = {}
    # measured observables: (label, fractional deviation in percent, category)
    #   cat 'mc' = mass/coupling (integer/LO postdiction); 'in' = inflation/neutrino (within meas. error)
    measured = [
        ("$m_p/m_e$", 0.008, "mc"),
        ("$1/\\alpha$", 0.026, "mc"),
        ("$m_H$", 0.08, "mc"),
        ("CC $\\log_{10}$", 0.10, "mc"),
        ("$\\sin^2\\theta_W$", 0.19, "mc"),
        ("$M_Z$", 0.21, "mc"),
        ("$\\alpha_s$", 0.34, "mc"),
        ("$\\Delta m^2_{31}/\\Delta m^2_{21}$", 1.2, "in"),
        ("$\\Omega_{\\rm DM}/\\Omega_b$", 1.6, "in"),
        ("$A_s$", 1.9, "in"),
        ("$\\sin^2\\theta_{23}$", 2.1, "in"),
        ("Jarlskog $J$", 2.6, "in"),
        ("$1-n_s$", 5.1, "in"),
    ]
    # dated future kill-shots: (label, year, what it decides)
    future = [
        ("SO", 2027, "$r$ hint"),
        ("LZ", 2028, "$m_{\\rm DM}{=}22.8$"),
        ("JUNO", 2030, "$\\Delta m^2$ ratio $=33$"),
        ("DESI/S4", 2030, "$\\Sigma m_\\nu{=}58$"),
        ("nEXO", 2032, "$m_{\\beta\\beta}{\\sim}1.4$"),
        ("LiteBIRD", 2035, "$r{=}1/300$"),
    ]
    print("== the whole tower on one axis: substrate vs world ==")
    print(
        f"  Panel A: {len(measured)} measured observables, fractional deviation (log %)"
    )
    print(f"  Panel B: {len(future)} dated kill-shots, 2025-2040")
    out["measured"] = [{"label": l, "dev_pct": d, "cat": c} for l, d, c in measured]
    out["future"] = [{"label": l, "year": y, "decides": w} for l, y, w in future]

    # log-x mapping for Panel A: dev% in [0.005, 10] -> x in [0, W]
    lo, hi = 0.005, 10.0
    W = 12.0  # cm

    def xa(dev):
        return (
            W * (math.log10(dev) - math.log10(lo)) / (math.log10(hi) - math.log10(lo))
        )

    # y rows top-down for Panel A
    n = len(measured)
    ya_top, dy = 0.0, 0.62
    lines = []
    lines.append(r"% Auto-generated by w33_tower_falsification_figure.py")
    lines.append(r"\begin{figure}[ht]\centering")
    lines.append(r"\begin{tikzpicture}[font=\footnotesize]")
    # Panel A frame + axis
    lines.append(
        r"\node[anchor=west,font=\small\bfseries] at (0,%.2f) {A. Substrate vs.\ world: fractional agreement $|{\rm pred}-{\rm obs}|/{\rm obs}$};"
        % (dy)
    )
    # x ticks at 0.01,0.1,1,10 %
    for t in (0.01, 0.1, 1.0, 10.0):
        x = xa(t)
        lines.append(
            r"\draw[gray!50] (%.2f,%.2f)--(%.2f,%.2f);" % (x, -n * dy - 0.1, x, 0.0)
        )
        lbl = ("%g" % t) + r"\%"
        lines.append(
            r"\node[gray,font=\tiny,below] at (%.2f,%.2f) {%s};"
            % (x, -n * dy - 0.1, lbl)
        )
    # shaded "integer / LO" zone < 0.3%
    xz = xa(0.3)
    lines.append(
        r"\fill[green!8] (%.2f,%.2f) rectangle (%.2f,%.2f);"
        % (xa(lo), -n * dy - 0.05, xz, 0.0)
    )
    lines.append(
        r"\node[green!50!black,font=\tiny,rotate=90,anchor=south] at (%.2f,%.2f) {integer / LO ($<0.3\%%$)};"
        % (xz - 0.25, -n * dy / 2)
    )
    # rows
    for i, (label, dev, cat) in enumerate(measured):
        y = -(i + 1) * dy
        x = xa(dev)
        color = "blue!65!black" if cat == "mc" else "orange!75!black"
        lines.append(r"\node[anchor=east] at (-0.2,%.2f) {%s};" % (y, label))
        lines.append(r"\fill[%s] (%.2f,%.2f) circle (2.4pt);" % (color, x, y))
        lines.append(
            r"\node[font=\tiny,anchor=west] at (%.2f,%.2f) {%.2g\%%};"
            % (x + 0.15, y, dev)
        )
    # Panel B: timeline
    yb = -(n + 2) * dy
    y0, y1 = 2025, 2040

    def xb(yr):
        return W * (yr - y0) / (y1 - y0)

    lines.append(
        r"\node[anchor=west,font=\small\bfseries] at (0,%.2f) {B. The dated kill-shots (one measurement each can falsify)};"
        % (yb + 0.55)
    )
    lines.append(r"\draw[thick,-{Stealth}] (0,%.2f)--(%.2f,%.2f);" % (yb, W + 0.5, yb))
    for yr in range(2025, 2041, 5):
        x = xb(yr)
        lines.append(r"\draw (%.2f,%.2f)--(%.2f,%.2f);" % (x, yb - 0.1, x, yb + 0.1))
        lines.append(
            r"\node[font=\tiny,below] at (%.2f,%.2f) {%d};" % (x, yb - 0.1, yr)
        )
    # stagger future markers above/below the line
    for j, (label, yr, what) in enumerate(future):
        x = xb(yr)
        up = j % 2 == 0
        yy = yb + (0.45 if up else -0.5)
        anch = "south" if up else "north"
        lines.append(r"\fill[red!70!black] (%.2f,%.2f) circle (2.2pt);" % (x, yb))
        lines.append(r"\draw[red!50,thin] (%.2f,%.2f)--(%.2f,%.2f);" % (x, yb, x, yy))
        lines.append(
            r"\node[font=\tiny,anchor=%s,align=center] at (%.2f,%.2f) {\textbf{%s}\\ %s};"
            % (anch, x, yy, label, what)
        )
    lines.append(r"\end{tikzpicture}")
    lines.append(
        r"""\caption{The whole substrate tower on one axis. \textbf{A:} every measured
observable's fractional agreement $|{\rm pred}-{\rm obs}|/{\rm obs}$ (log scale). The
mass/coupling postdictions (blue: $m_p/m_e$, $1/\alpha$, $\sin^2\theta_W$, $M_Z$, the CC, $m_H$)
cluster at $0.01$--$0.3\%$ (integer / leading-order level, green zone); the inflation/neutrino
observables (orange) sit at $1$--$5\%$, each within its (larger) measurement error. The common
axis is fractional deviation, not $\sigma$ (the blue points are integer/LO postdictions whose
residual is higher-order running; the orange points are measurement-limited). \textbf{B:} the
dated falsification frontier --- each future test is one measurement that can kill the theory:
$m_{\rm DM}$ (LZ $\sim$2028), the first $r$ hint (SO $\sim$2027), the $\Delta m^2$ ratio (JUNO),
$\Sigma m_\nu$ (DESI/CMB-S4), $m_{\beta\beta}$ (nEXO/LEGEND), and the headline $r=1/300$
(LiteBIRD $\sim$2035). One $q=3$ alphabet, $\sim$20 numbers, all consistent --- and decided by
the mid-2030s.}"""
    )
    lines.append(r"\label{fig:tower-falsification}")
    lines.append(r"\end{figure}")
    fig = "\n".join(lines) + "\n"
    with open("analysis/w33_tower_falsification_fig.tex", "w") as fh:
        fh.write(fig)
    print("\nwrote analysis/w33_tower_falsification_fig.tex")
    out["figure"] = "analysis/w33_tower_falsification_fig.tex"

    print(
        "\nRESULT: the whole tower is on one axis. Panel A is a forest plot of every measured"
    )
    print(
        "  observable's fractional agreement |pred-obs|/obs on a log scale: the mass/coupling"
    )
    print(
        "  postdictions (m_p/m_e, 1/alpha, sin^2 th_W, M_Z, the CC, m_H) cluster at 0.01-0.3%"
    )
    print(
        "  (integer / leading-order), and the inflation/neutrino observables (A_s, n_s, alpha_s,"
    )
    print(
        "  Dm^2 ratio, sin^2 th_23, Omega_DM/Omega_b) sit at 1-5%, each within its measurement"
    )
    print(
        "  error; zero observables are off the chart. Panel B is the dated falsification"
    )
    print(
        "  timeline 2025-2040: the single measurements that can kill the theory -- m_DM (LZ"
    )
    print(
        "  ~2028), the first r hint (SO ~2027), the Dm^2 ratio (JUNO), Sum m_nu (DESI/CMB-S4),"
    )
    print(
        "  m_betabeta (nEXO/LEGEND), and the headline r = 1/300 (LiteBIRD ~2035). The figure"
    )
    print(
        "  shows BOTH the over-determination (one q=3 alphabet, ~20 numbers, all consistent) and"
    )
    print(
        "  the dated kill-shots in one view -- the cover image for the standalone manuscript."
    )
    print(
        "  Honest: the common axis is fractional deviation (not sigma), mixing integer/LO"
    )
    print(
        "  postdictions with measurement-limited points (the caption says so); it is a"
    )
    print(
        "  presentation of the scorecard, not a new result. The dates are published schedules."
    )

    out["summary"] = (
        "the whole substrate tower on one axis -- the cover figure for w33_everything.tex. "
        "Panel A: a forest plot of every measured observable's fractional agreement "
        "|pred-obs|/obs (log scale) -- the mass/coupling postdictions (m_p/m_e, 1/alpha, "
        "sin^2 th_W, M_Z, CC, m_H) cluster at 0.01-0.3% (integer/LO), the inflation/neutrino "
        "observables (A_s, n_s, alpha_s, Dm^2 ratio, sin^2 th_23, Omega_DM/Omega_b) at 1-5%, "
        "each within its measurement error; zero off the chart. Panel B: the dated kill-shots "
        "2025-2040 -- m_DM (LZ ~2028), first r hint (SO ~2027), Dm^2 ratio (JUNO), Sum m_nu "
        "(DESI/CMB-S4), m_betabeta (nEXO/LEGEND), headline r=1/300 (LiteBIRD ~2035). One figure "
        "shows the over-determination (one q=3 alphabet, ~20 numbers, all consistent) AND the "
        "dated falsifiability. HONEST: the common axis is fractional deviation not sigma (mixes "
        "integer/LO postdictions with measurement-limited points; caption says so); a "
        "presentation of the scorecard, not a new result; dates are published schedules. Emits "
        "w33_tower_falsification_fig.tex (two-panel figure)."
    )
    out["sources"] = [
        "final-scorecard ledger (w33_final_scorecard.py); experiment schedules (LZ, Simons "
        "Observatory, JUNO, DESI, CMB-S4, LiteBIRD, nEXO/LEGEND); substrate predictions "
        "r=1/300, Sum m_nu=58 meV, m_DM=22.8 GeV, Dm^2 ratio=33, m_betabeta~1.4 meV."
    ]
    with open("data/w33_tower_falsification_figure.json", "w") as fh:
        json.dump(out, fh, indent=2)
    print("wrote data/w33_tower_falsification_figure.json")


if __name__ == "__main__":
    main()
