#!/usr/bin/env python3
"""Firewall the two distinct Z6 structures carried by the flagship A5 lattice.

There are TWO exact order-six objects around the same A5:

(1) Discriminant/center gluing:
      P(A5)/Q(A5) ~= Z6, generated by [omega1].
    The flagship hypercharge is -omega1.

(2) Weyl/Coxeter dynamics:
      c=(0 1 2 3 4 5) in W(A5)=S6,
    of order six on Q(A5).

They are not the same action.

Every Weyl reflection acts trivially on P/Q, hence the Coxeter element acts
trivially on the discriminant Z6. Explicitly c(omega1)-omega1 is an A5 root.

On Q(A5) tensor C, c has the five nontrivial sixth roots of unity as
eigenvalues. Therefore
  fixed_dim(c)=0,
  fixed_dim(c^2)=1,
  fixed_dim(c^3)=2.

By contrast, the physical W3, theta3, and their C6 product are commuting INNER
TORUS automorphisms of E8. Ad(t) fixes the Cartan pointwise, so on the rank-five
Cartan lattice L~=A5 their fixed dimension is 5 for every power.

Thus no intertwiner can identify the A5 Coxeter C6 action on L with the
physical holonomy C6 action on L.  The valid common structure is the A5 lattice
itself; its discriminant gluing and its Weyl dynamics are categorically
different.
"""
from __future__ import annotations
import cmath,json
from fractions import Fraction as F
from pathlib import Path

ROOT=Path(__file__).resolve().parents[1]
OUT=ROOT/'data/w33_a5_coxeter_vs_hypercharge_z6_firewall.json'

def shift(v,k=1):
    n=len(v);k%=n
    out=[None]*n
    for i,x in enumerate(v):out[(i+k)%n]=x
    return tuple(out)

def sub(a,b):return tuple(x-y for x,y in zip(a,b))
def norm2(v):return sum(x*x for x in v)

def in_A5_root_lattice(v):
    return all(x.denominator==1 for x in v) and sum(v)==0

def main(write=True):
    omega1=(F(5,6),)+(-F(1,6),)*5
    c_omega=shift(omega1,1)
    delta=sub(c_omega,omega1)
    assert in_A5_root_lattice(delta)
    assert norm2(delta)==2

    # Coxeter eigenvalues on the zero-sum standard representation.
    eig=[cmath.exp(2j*cmath.pi*k/6) for k in range(1,6)]
    fixed={}
    for p in (1,2,3,6):
        fixed[p]=sum(abs(z**p-1)<1e-9 for z in eig)
    assert fixed=={1:0,2:1,3:2,6:5}

    # Physical inner torus automorphisms fix the Cartan pointwise.
    physical_fixed={1:5,2:5,3:5,6:5}

    parent=json.loads((ROOT/'data/w33_a5_duad_gauge_intertwiner.json').read_text())
    hol=json.loads((ROOT/'data/w33_e8_holonomy_c3xc6_factorization.json').read_text())
    assert parent['status']=='PASS_A5_DUAD_INTERTWINER'
    assert hol['status']=='PASS_EXACT_C3_SELECTOR_X_PHYSICAL_C6_FACTORIZATION'

    out={
      'schema':'w33.a5_coxeter_vs_hypercharge_z6_firewall.v1',
      'status':'PASS_DISTINCT_A5_Z6_STRUCTURES',
      'headline':'The A5 discriminant Z6 carrying hypercharge and the A5 Coxeter C6 are exact but distinct structures. The Coxeter element has order6 on the A5 root module yet acts trivially on P(A5)/Q(A5)=Z6; physical inner-torus holonomies fix the A5 Cartan complement pointwise, whereas the Coxeter powers have fixed dimensions 0,1,2,5. No action-level intertwiner can identify them.',
      'discriminant_Z6':{
        'group':'P(A5)/Q(A5) ~= Z/6',
        'generator':'[omega1]; flagship Y=-omega1',
        'coxeter_action_on_discriminant':'identity',
        'explicit_witness':'c(omega1)-omega1 is an A5 root',
        'witness_norm2':'2'},
      'coxeter_C6':{
        'element':'c=(0 1 2 3 4 5)',
        'order':6,
        'eigenphases':'2*pi*k/6, k=1..5',
        'fixed_dimensions_by_power':{str(k):v for k,v in fixed.items()}},
      'physical_holonomy_C6':{
        'type':'product of commuting inner torus automorphisms of E8',
        'action_on_rank5_A5_Cartan':'identity',
        'fixed_dimensions_by_power':{str(k):v for k,v in physical_fixed.items()}},
      'no_go':{
        'same_action_on_A5':False,
        'reason':'fixed-space dimensions disagree already for powers 1,2,3',
        'safe_common_structure':'the same A5 lattice supports both discriminant gluing and an independent Weyl Coxeter action'},
      'physics_reading':'The SM global Z6 is a center/discriminant quotient, not a six-step dynamical rotation. Any Floquet use of the Coxeter six-cycle must be presented as a separate control symmetry, not as the physical hypercharge-center kernel.',
      'parents':['data/w33_a5_duad_gauge_intertwiner.json','data/w33_e8_holonomy_c3xc6_factorization.json'],
      'checks':{'coxeter_order6':True,'coxeter_trivial_on_discriminant':True,
                'coxeter_fixed_0_1_2_5':True,'physical_torus_fixes_Cartan5':True,
                'action_identification_killed':True}}
    if write:OUT.write_text(json.dumps(out,indent=2)+'\n')
    print(json.dumps(out,indent=2));return out

if __name__=='__main__':main(True)
