#!/usr/bin/env python3
"""Compile the E6 Qpsi clock directly from one GQ(2,4) anchor.

For the 27-point meet graph A of the cubic-surface lines, an anchor a defines

    q_a(i) = 1 + 3 delta(a,i) - 3 A(a,i).

Thus a has charge 4, its ten neighbours have charge -2, and its sixteen
non-neighbours have charge 1.  Every GQ line has charge pattern either
(-2,-2,4) or (-2,1,1), hence total charge zero.

The 27 charts form one W(E6) orbit.  The anchor stabilizer is the parabolic
W(D5), generated by the five simple reflections fixing the highest weight;
its order is 1920 and 51840/1920=27.  This turns the familiar branching
27=1_4+10_-2+16_1 into an exact incidence compiler and identifies choosing a
Qpsi chart with choosing one point/weight of the minuscule 27.

The result is coordinate-free after the anchor is chosen.  It does not select
that anchor physically.  Parallel representation audits prove that a full
H27- or K-equivariant address-to-operator basis conjugacy cannot exist; the
remaining compiler problem is explicitly symmetry-changing.
"""
from __future__ import annotations

import importlib.util
import json
import sys
from collections import Counter
from pathlib import Path

import networkx as nx
from sympy.combinatorics import Permutation, PermutationGroup


ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "data/w33_qpsi_gq24_parabolic_compiler.json"


def load(path: Path, name: str):
    spec = importlib.util.spec_from_file_location(name, path)
    assert spec and spec.loader
    module = importlib.util.module_from_spec(spec)
    sys.modules[name] = module
    spec.loader.exec_module(module)
    return module


def charge(meet: nx.Graph, anchor: int, point: int) -> int:
    """The Qpsi charge from equality and collinearity with one anchor."""
    return 1 + 3 * int(point == anchor) - 3 * int(meet.has_edge(anchor, point))


def main(write: bool = True) -> dict:
    h27_obstruction = json.loads(
        (ROOT / "data/w33_address_operator_h27_intertwiner_obstruction.json").read_text()
    )
    k81_obstruction = json.loads(
        (ROOT / "data/w33_scheduler_operator_k81_intertwiner_obstruction.json").read_text()
    )
    assert h27_obstruction["intertwiner"]["maximum_rank"] == 9
    assert h27_obstruction["intertwiner"]["invertible_intertwiner_exists"] is False
    assert k81_obstruction["intertwiner"]["maximum_rank"] == 27
    assert k81_obstruction["intertwiner"]["invertible_equivariant_compiler_exists"] is False
    prior = load(
        ROOT / "analysis/w33_z6_objectwise_33_48_32_carrier.py",
        "qpsi_objectwise_prior",
    )
    common = load(
        ROOT / "analysis/w33_pass4992_4999_common.py",
        "qpsi_gq24_common",
    )

    # Exact E6 minuscule orbit and its conventional Qpsi chart.
    weights = prior.orbit((1, 0, 0, 0, 0, 0))
    weight_index = {weight: idx for idx, weight in enumerate(weights)}
    assert len(weights) == 27
    conventional = [prior.qpsi(weight) for weight in weights]
    assert Counter(conventional) == Counter({1: 16, -2: 10, 4: 1})
    singlet_index = conventional.index(4)
    assert weights[singlet_index] == (1, 0, 0, 0, 0, 0)

    # The E6 root-difference graph is Schlaefli, complementary to the meet
    # graph GQ(2,4).  Anchor the conventional 1_4 weight at point zero.
    simple_root = tuple(prior.A[row][0] for row in range(6))
    roots = set(prior.orbit(simple_root))
    assert len(roots) == 72
    weight_graph = nx.Graph()
    weight_graph.add_nodes_from(range(27))
    for left in range(27):
        for right in range(left + 1, 27):
            delta = tuple(weights[left][j] - weights[right][j] for j in range(6))
            if delta in roots or tuple(-x for x in delta) in roots:
                weight_graph.add_edge(left, right)
    assert set(dict(weight_graph.degree()).values()) == {16}

    base = common.build_base()
    meet = base["G27"]
    lines = {frozenset(line) for line in base["tritangents"]}
    assert len(lines) == 45
    schlaefli = nx.complement(meet)
    nx.set_node_attributes(
        weight_graph, {i: i == singlet_index for i in weight_graph}, "anchor"
    )
    nx.set_node_attributes(schlaefli, {i: i == 0 for i in schlaefli}, "anchor")
    matcher = nx.algorithms.isomorphism.GraphMatcher(
        weight_graph,
        schlaefli,
        node_match=lambda left, right: left["anchor"] == right["anchor"],
    )
    weight_to_point = next(matcher.isomorphisms_iter())
    assert weight_to_point[singlet_index] == 0
    assert all(
        conventional[i] == charge(meet, 0, weight_to_point[i])
        for i in range(27)
    )

    # Transport the six simple E6 reflections to the 27 points.
    reflections = []
    for node in range(6):
        images = [None] * 27
        for idx, weight in enumerate(weights):
            images[weight_to_point[idx]] = weight_to_point[
                weight_index[prior.refl(weight, node)]
            ]
        reflection = Permutation(images)
        reflections.append(reflection)
        assert {frozenset(reflection(i) for i in line) for line in lines} == lines

    we6 = PermutationGroup(reflections)
    assert we6.order() == 51840
    assert len(we6.orbit(0)) == 27
    stabilizer = we6.stabilizer(0)
    assert stabilizer.order() == 1920

    # Deleting the minuscule node leaves D5.  Its five simple reflections fix
    # the highest-weight anchor and generate the full point stabilizer.
    parabolic = PermutationGroup(reflections[1:])
    assert all(reflection(0) == 0 for reflection in reflections[1:])
    assert reflections[0](0) != 0
    assert parabolic.order() == stabilizer.order() == 1920
    d5_cartan = [list(row[1:]) for row in prior.A[1:]]
    assert d5_cartan == [
        [2, -1, 0, 0, 0],
        [-1, 2, -1, -1, 0],
        [0, -1, 2, 0, 0],
        [0, -1, 0, 2, -1],
        [0, 0, 0, -1, 2],
    ]

    # Every possible anchor gives the same branching and cubic selection rule.
    charts = []
    for anchor in range(27):
        values = {point: charge(meet, anchor, point) for point in range(27)}
        histogram = Counter(values.values())
        patterns = Counter(
            tuple(sorted(values[point] for point in line)) for line in lines
        )
        assert histogram == Counter({1: 16, -2: 10, 4: 1})
        assert patterns == Counter({(-2, 1, 1): 40, (-2, -2, 4): 5})
        assert all(sum(values[point] for point in line) == 0 for line in lines)
        charts.append(
            {
                "anchor": anchor,
                "charge_histogram": {"-2": 10, "1": 16, "4": 1},
                "cubic_pattern_counts": {
                    "(-2,-2,4)": 5,
                    "(-2,1,1)": 40,
                },
            }
        )

    # The formula is equivariant, so the chart orbit is exactly the point orbit.
    assert all(
        charge(meet, reflection(anchor), reflection(point))
        == charge(meet, anchor, point)
        for reflection in reflections
        for anchor in range(27)
        for point in range(27)
    )

    out = {
        "schema": "w33.qpsi_gq24_parabolic_compiler.v2",
        "status": "PASS_QPSI_IS_AN_ANCHORED_GQ24_PARABOLIC_CLOCK",
        "headline": (
            "On the 27 cubic-surface lines, choosing one anchor a compiles the E6 "
            "Qpsi charge by q_a(i)=1+3 delta_ai-3 A_ai: the anchor is 1_4, its "
            "ten GQ(2,4) neighbours are 10_-2, and its sixteen nonneighbours are "
            "16_1. Every tritangent is automatically neutral, with patterns "
            "5*(-2,-2,4)+40*(-2,1,1). The 27 clocks form one W(E6) orbit and "
            "each clock stabilizer is the order-1920 parabolic W(D5)."
        ),
        "incidence_clock": {
            "formula": "q_a(i) = 1 + 3*delta(a,i) - 3*A(a,i)",
            "A": "adjacency matrix of the 27-point GQ(2,4) meet graph",
            "branching": "27 = 1_4 + 10_-2 + 16_1",
            "address_phase_rule": "D12(a)|i,p> = zeta12^(q_a(i)) |i,p>",
            "predicate_compiler": "one equality predicate plus one GQ adjacency predicate",
            "conventional_Qpsi_anchor": 0,
            "conventional_weight_to_point": {
                str(index): weight_to_point[index] for index in range(27)
            },
        },
        "cubic_neutrality": {
            "tritangents": 45,
            "lines_through_anchor": 5,
            "through_anchor_pattern": [-2, -2, 4],
            "other_line_pattern": [-2, 1, 1],
            "pattern_counts": {"(-2,-2,4)": 5, "(-2,1,1)": 40},
            "all_charge_sums_zero": True,
        },
        "weyl_parabolic": {
            "W_E6_order": we6.order(),
            "chart_orbit_size": len(we6.orbit(0)),
            "point_stabilizer_order": stabilizer.order(),
            "parabolic_generators": [1, 2, 3, 4, 5],
            "parabolic_type": "W(D5)",
            "parabolic_order": parabolic.order(),
            "orbit_stabilizer": "51840 / 1920 = 27",
            "D5_cartan_after_deleting_minuscule_node": d5_cartan,
        },
        "all_anchor_charts": charts,
        "ownership": {
            "prior_objectwise_owner": "analysis/w33_z6_objectwise_33_48_32_carrier.py",
            "prior_result": "for one chosen 1_4 anchor, the 10 meeting and 16 far frames carry charges -2 and 1",
            "increment": "closed formula for all 27 anchors, exact W(E6)/W(D5) chart orbit, equivariance, and incidence-only cubic-neutrality compiler",
        },
        "equivariant_compiler_obstruction": {
            "H27_maximum_rank": h27_obstruction["intertwiner"]["maximum_rank"],
            "H27_target_dimension": h27_obstruction["intertwiner"]["target_dimension"],
            "K81_maximum_rank": k81_obstruction["intertwiner"]["maximum_rank"],
            "K81_target_dimension": k81_obstruction["intertwiner"]["target_dimension"],
            "invertible_H27_equivariant_intertwiner_exists": False,
            "invertible_K81_equivariant_compiler_exists": False,
            "surviving_frontier": (
                "Choose and justify a non-equivariant, proper-subgroup-covariant, or "
                "otherwise symmetry-changing root-coordinate dictionary."
            ),
        },
        "boundary": (
            "The theorem identifies the 27 conjugate Qpsi charts and compiles a chosen "
            "clock on frame addresses. It does not physically select an anchor, identify "
            "observed generations, or select a symmetry-changing frozen-root-to-trinification "
            "operator dictionary. Full H27/K-equivariant conjugacies are ruled out at maximum "
            "ranks 9/27 and 27/81. The separate complete Steiner-atlas certificate now decides "
            "the monomial Pauli-algebra normalizer question uniformly across all 51840 charts."
        ),
        "parents": [
            "data/w33_address_operator_h27_intertwiner_obstruction.json",
            "data/w33_scheduler_operator_k81_intertwiner_obstruction.json",
            "data/w33_steiner_trinification_qpsi_normalizer.json",
        ],
        "checks": {
            "conventional_Qpsi_equals_anchor_formula": True,
            "all_27_anchor_charts_have_1_10_16_branching": True,
            "all_45_cubics_are_Qpsi_neutral_for_every_anchor": True,
            "six_reflections_generate_W_E6": True,
            "five_anchor_fixing_reflections_generate_W_D5": True,
            "chart_orbit_has_27_elements": True,
            "formula_is_W_E6_equivariant": True,
            "H27_equivariant_intertwiner_is_rank_obstructed": True,
            "K81_equivariant_compiler_is_rank_obstructed": True,
            "symmetry_changing_compiler_remains_open": True,
        },
    }
    if write:
        OUT.write_text(json.dumps(out, indent=2) + "\n")
    print(
        json.dumps(
            {
                "status": out["status"],
                "formula": out["incidence_clock"]["formula"],
                "patterns": out["cubic_neutrality"]["pattern_counts"],
                "parabolic": out["weyl_parabolic"],
            },
            indent=2,
        )
    )
    return out


if __name__ == "__main__":
    main(True)
